// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define([],function(){function l(a,b,c){a=(a.x-c.x)*(b.y-c.y)-(a.y-c.y)*(b.x-c.x);return a>-t&&a<t?k.COLLINEAR:0<a?k.CCW:k.CW}function w(a,b,c,d){var m=d.x;d=d.y;var e=a.x-m;a=a.y-d;return e*(b.y-d)-(b.x-m)*a<=t||(c.x-m)*a-e*(c.y-d)<=t?!1:!0}var s={},r=function(a,b){this.name="PointError";this.points=b=b||[];this.message=a||"Invalid Points!";for(var c=0;c<b.length;c++)this.message+=" "+f.toString(b[c])};r.prototype=Error();r.prototype.constructor=r;var f=function(a,b,c){this.x=+a||0;this.y=+b||0;this.metaZ=
+c||0;this._p2t_edge_list=null};f.prototype.toString=function(){return"("+this.x+";"+this.y+")"};f.prototype.clone=function(){return new f(this.x,this.y)};f.prototype.set_zero=function(){this.y=this.x=0;return this};f.prototype.set=function(a,b){this.x=+a||0;this.y=+b||0;return this};f.prototype.negate=function(){this.x=-this.x;this.y=-this.y;return this};f.prototype.add=function(a){this.x+=a.x;this.y+=a.y;return this};f.prototype.sub=function(a){this.x-=a.x;this.y-=a.y;return this};f.prototype.mul=
function(a){this.x*=a;this.y*=a;return this};f.prototype.length=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};f.prototype.normalize=function(){var a=this.length();this.x/=a;this.y/=a;return a};f.prototype.equals=function(a){return this.x===a.x&&this.y===a.y};f.negate=function(a){return new f(-a.x,-a.y)};f.add=function(a,b){return new f(a.x+b.x,a.y+b.y)};f.sub=function(a,b){return new f(a.x-b.x,a.y-b.y)};f.mul=function(a,b){return new f(a*b.x,a*b.y)};f.cross=function(a,b){return"number"===
typeof a?"number"===typeof b?a*b:new f(-a*b.y,a*b.x):"number"===typeof b?new f(b*a.y,-b*a.x):a.x*b.y-a.y*b.x};f.toString=function(a){var b=a.toString();return"[object Object]"===b?f.prototype.toString.call(a):b};f.compare=function(a,b){return a.y===b.y?a.x-b.x:a.y-b.y};f.cmp=f.compare;f.equals=function(a,b){return a.x===b.x&&a.y===b.y};f.dot=function(a,b){return a.x*b.x+a.y*b.y};var y=function(a,b){this.p=a;this.q=b;if(a.y>b.y)this.q=a,this.p=b;else if(a.y===b.y)if(a.x>b.x)this.q=a,this.p=b;else if(a.x===
b.x)throw new r("poly2tri Invalid Edge constructor: repeated points!",[a]);this.q._p2t_edge_list||(this.q._p2t_edge_list=[]);this.q._p2t_edge_list.push(this)},g=function(a,b,c){this.points_=[a,b,c];this.neighbors_=[null,null,null];this.interior_=!1;this.constrained_edge=[!1,!1,!1];this.delaunay_edge=[!1,!1,!1]};g.prototype.toString=function(){var a=f.toString;return"["+a(this.points_[0])+a(this.points_[1])+a(this.points_[2])+"]"};g.prototype.getPoint=function(a){return this.points_[a]};g.prototype.GetPoint=
g.prototype.getPoint;g.prototype.getNeighbor=function(a){return this.neighbors_[a]};g.prototype.containsPoint=function(a){var b=this.points_;return a===b[0]||a===b[1]||a===b[2]};g.prototype.containsEdge=function(a){return this.containsPoint(a.p)&&this.containsPoint(a.q)};g.prototype.containsPoints=function(a,b){return this.containsPoint(a)&&this.containsPoint(b)};g.prototype.isInterior=function(){return this.interior_};g.prototype.setInterior=function(a){this.interior_=a;return this};g.prototype.markNeighborPointers=
function(a,b,c){var d=this.points_;if(a===d[2]&&b===d[1]||a===d[1]&&b===d[2])this.neighbors_[0]=c;else if(a===d[0]&&b===d[2]||a===d[2]&&b===d[0])this.neighbors_[1]=c;else if(a===d[0]&&b===d[1]||a===d[1]&&b===d[0])this.neighbors_[2]=c;else throw Error("poly2tri Invalid Triangle.markNeighborPointers() call");};g.prototype.markNeighbor=function(a){var b=this.points_;a.containsPoints(b[1],b[2])?(this.neighbors_[0]=a,a.markNeighborPointers(b[1],b[2],this)):a.containsPoints(b[0],b[2])?(this.neighbors_[1]=
a,a.markNeighborPointers(b[0],b[2],this)):a.containsPoints(b[0],b[1])&&(this.neighbors_[2]=a,a.markNeighborPointers(b[0],b[1],this))};g.prototype.clearNeigbors=function(){this.neighbors_[0]=null;this.neighbors_[1]=null;this.neighbors_[2]=null};g.prototype.clearDelunayEdges=function(){this.delaunay_edge[0]=!1;this.delaunay_edge[1]=!1;this.delaunay_edge[2]=!1};g.prototype.pointCW=function(a){var b=this.points_;return a===b[0]?b[2]:a===b[1]?b[0]:a===b[2]?b[1]:null};g.prototype.pointCCW=function(a){var b=
this.points_;return a===b[0]?b[1]:a===b[1]?b[2]:a===b[2]?b[0]:null};g.prototype.neighborCW=function(a){return a===this.points_[0]?this.neighbors_[1]:a===this.points_[1]?this.neighbors_[2]:this.neighbors_[0]};g.prototype.neighborCCW=function(a){return a===this.points_[0]?this.neighbors_[2]:a===this.points_[1]?this.neighbors_[0]:this.neighbors_[1]};g.prototype.getConstrainedEdgeCW=function(a){return a===this.points_[0]?this.constrained_edge[1]:a===this.points_[1]?this.constrained_edge[2]:this.constrained_edge[0]};
g.prototype.getConstrainedEdgeCCW=function(a){return a===this.points_[0]?this.constrained_edge[2]:a===this.points_[1]?this.constrained_edge[0]:this.constrained_edge[1]};g.prototype.setConstrainedEdgeCW=function(a,b){a===this.points_[0]?this.constrained_edge[1]=b:a===this.points_[1]?this.constrained_edge[2]=b:this.constrained_edge[0]=b};g.prototype.setConstrainedEdgeCCW=function(a,b){a===this.points_[0]?this.constrained_edge[2]=b:a===this.points_[1]?this.constrained_edge[0]=b:this.constrained_edge[1]=
b};g.prototype.getDelaunayEdgeCW=function(a){return a===this.points_[0]?this.delaunay_edge[1]:a===this.points_[1]?this.delaunay_edge[2]:this.delaunay_edge[0]};g.prototype.getDelaunayEdgeCCW=function(a){return a===this.points_[0]?this.delaunay_edge[2]:a===this.points_[1]?this.delaunay_edge[0]:this.delaunay_edge[1]};g.prototype.setDelaunayEdgeCW=function(a,b){a===this.points_[0]?this.delaunay_edge[1]=b:a===this.points_[1]?this.delaunay_edge[2]=b:this.delaunay_edge[0]=b};g.prototype.setDelaunayEdgeCCW=
function(a,b){a===this.points_[0]?this.delaunay_edge[2]=b:a===this.points_[1]?this.delaunay_edge[0]=b:this.delaunay_edge[1]=b};g.prototype.neighborAcross=function(a){return a===this.points_[0]?this.neighbors_[0]:a===this.points_[1]?this.neighbors_[1]:this.neighbors_[2]};g.prototype.oppositePoint=function(a,b){var c=a.pointCW(b);return this.pointCW(c)};g.prototype.legalize=function(a,b){var c=this.points_;if(a===c[0])c[1]=c[0],c[0]=c[2],c[2]=b;else if(a===c[1])c[2]=c[1],c[1]=c[0],c[0]=b;else if(a===
c[2])c[0]=c[2],c[2]=c[1],c[1]=b;else throw Error("poly2tri Invalid Triangle.legalize() call");};g.prototype.index=function(a){var b=this.points_;if(a===b[0])return 0;if(a===b[1])return 1;if(a===b[2])return 2;throw Error("poly2tri Invalid Triangle.index() call");};g.prototype.edgeIndex=function(a,b){var c=this.points_;if(a===c[0]){if(b===c[1])return 2;if(b===c[2])return 1}else if(a===c[1]){if(b===c[2])return 0;if(b===c[0])return 2}else if(a===c[2]){if(b===c[0])return 1;if(b===c[1])return 0}return-1};
g.prototype.markConstrainedEdgeByIndex=function(a){this.constrained_edge[a]=!0};g.prototype.markConstrainedEdgeByEdge=function(a){this.markConstrainedEdgeByPoints(a.p,a.q)};g.prototype.markConstrainedEdgeByPoints=function(a,b){var c=this.points_;if(b===c[0]&&a===c[1]||b===c[1]&&a===c[0])this.constrained_edge[2]=!0;else if(b===c[0]&&a===c[2]||b===c[2]&&a===c[0])this.constrained_edge[1]=!0;else if(b===c[1]&&a===c[2]||b===c[2]&&a===c[1])this.constrained_edge[0]=!0};var z=3*Math.PI/4,u=Math.PI/2,t=1E-12,
k={CW:1,CCW:-1,COLLINEAR:0},v=function(a,b){this.point=a;this.triangle=b||null;this.prev=this.next=null;this.value=a.x},p=function(a,b){this.head_=a;this.tail_=b;this.search_node_=a};p.prototype.head=function(){return this.head_};p.prototype.setHead=function(a){this.head_=a};p.prototype.tail=function(){return this.tail_};p.prototype.setTail=function(a){this.tail_=a};p.prototype.search=function(){return this.search_node_};p.prototype.setSearch=function(a){this.search_node_=a};p.prototype.findSearchNode=
function(){return this.search_node_};p.prototype.locateNode=function(a){var b=this.search_node_;if(a<b.value)for(;b=b.prev;){if(a>=b.value)return this.search_node_=b}else for(;b=b.next;)if(a<b.value)return this.search_node_=b.prev;return null};p.prototype.locatePoint=function(a){var b=a.x,c=this.findSearchNode(b),d=c.point.x;if(b===d){if(a!==c.point)if(a===c.prev.point)c=c.prev;else if(a===c.next.point)c=c.next;else throw Error("poly2tri Invalid AdvancingFront.locatePoint() call");}else if(b<d)for(;(c=
c.prev)&&a!==c.point;);else for(;(c=c.next)&&a!==c.point;);c&&(this.search_node_=c);return c};var x=function(){this.right_node=this.bottom_node=this.left_node=null;this.width=0;this.left_highest=!1};x.prototype.clear=function(){this.right_node=this.bottom_node=this.left_node=null;this.width=0;this.left_highest=!1};var A=function(){this.constrained_edge=null;this.right=!1},h=function(a,b){b=b||{};this.triangles_=[];this.map_=[];this.points_=b.cloneArrays?a.slice(0):a;this.edge_list=[];this.af_tail_=
this.af_middle_=this.af_head_=this.tail_=this.head_=this.front_=this.pmin_=this.pmax_=null;this.basin=new x;this.edge_event=new A;this.initEdges(this.points_)};h.prototype.addHole=function(a){this.initEdges(a);var b,c=a.length;for(b=0;b<c;b++)this.points_.push(a[b]);return this};h.prototype.AddHole=h.prototype.addHole;h.prototype.addPoint=function(a){this.points_.push(a);return this};h.prototype.AddPoint=h.prototype.addPoint;h.prototype.addPoints=function(a){this.points_=this.points_.concat(a);return this};
h.prototype.triangulate=function(){e.triangulate(this);return this};h.prototype.getBoundingBox=function(){return{min:this.pmin_,max:this.pmax_}};h.prototype.getTriangles=function(){return this.triangles_};h.prototype.GetTriangles=h.prototype.getTriangles;h.prototype.front=function(){return this.front_};h.prototype.pointCount=function(){return this.points_.length};h.prototype.head=function(){return this.head_};h.prototype.setHead=function(a){this.head_=a};h.prototype.tail=function(){return this.tail_};
h.prototype.setTail=function(a){this.tail_=a};h.prototype.getMap=function(){return this.map_};h.prototype.initTriangulation=function(){var a=this.points_[0].x,b=this.points_[0].x,c=this.points_[0].y,d=this.points_[0].y,e,n=this.points_.length;for(e=1;e<n;e++){var q=this.points_[e];q.x>a&&(a=q.x);q.x<b&&(b=q.x);q.y>c&&(c=q.y);q.y<d&&(d=q.y)}this.pmin_=new f(b,d);this.pmax_=new f(a,c);e=0.3*(a-b);c=0.3*(c-d);this.head_=new f(a+e,d-c);this.tail_=new f(b-e,d-c);this.points_.sort(f.compare)};h.prototype.initEdges=
function(a){var b,c=a.length;for(b=0;b<c;++b)this.edge_list.push(new y(a[b],a[(b+1)%c]))};h.prototype.getPoint=function(a){return this.points_[a]};h.prototype.addToMap=function(a){this.map_.push(a)};h.prototype.locateNode=function(a){return this.front_.locateNode(a.x)};h.prototype.createAdvancingFront=function(){var a,b,c;c=new g(this.points_[0],this.tail_,this.head_);this.map_.push(c);a=new v(c.getPoint(1),c);b=new v(c.getPoint(0),c);c=new v(c.getPoint(2));this.front_=new p(a,c);a.next=b;b.next=
c;b.prev=a;c.prev=b};h.prototype.removeNode=function(a){};h.prototype.mapTriangleToNodes=function(a){for(var b=0;3>b;++b)if(!a.getNeighbor(b)){var c=this.front_.locatePoint(a.pointCW(a.getPoint(b)));c&&(c.triangle=a)}};h.prototype.removeFromMap=function(a){var b,c=this.map_,d=c.length;for(b=0;b<d;b++)if(c[b]===a){c.splice(b,1);break}};h.prototype.meshClean=function(a){a=[a];for(var b,c;b=a.pop();)if(!b.isInterior()){b.setInterior(!0);this.triangles_.push(b);for(c=0;3>c;c++)b.constrained_edge[c]||
a.push(b.getNeighbor(c))}};var e={triangulate:function(a){a.initTriangulation();a.createAdvancingFront();e.sweepPoints(a);e.finalizationPolygon(a)},sweepPoints:function(a){var b,c=a.pointCount();for(b=1;b<c;++b)for(var d=a.getPoint(b),m=e.pointEvent(a,d),d=d._p2t_edge_list,n=0;d&&n<d.length;++n)e.edgeEventByEdge(a,d[n],m)},finalizationPolygon:function(a){for(var b=a.front().head().next.triangle,c=a.front().head().next.point;!b.getConstrainedEdgeCW(c);)b=b.neighborCCW(c);a.meshClean(b)},pointEvent:function(a,
b){var c=a.locateNode(b),d=e.newFrontTriangle(a,b,c);b.x<=c.point.x+t&&e.fill(a,c);e.fillAdvancingFront(a,d);return d},edgeEventByEdge:function(a,b,c){a.edge_event.constrained_edge=b;a.edge_event.right=b.p.x>b.q.x;e.isEdgeSideOfTriangle(c.triangle,b.p,b.q)||(e.fillEdgeEvent(a,b,c),e.edgeEventByPoints(a,b.p,b.q,c.triangle,b.q))},edgeEventByPoints:function(a,b,c,d,m){if(null!==d&&!e.isEdgeSideOfTriangle(d,b,c)){var n=d.pointCCW(m),q=l(c,n,b);if(q===k.COLLINEAR)if(d.containsPoints(c,n))d.markConstrainedEdgeByPoints(c,
n),a.edge_event.constrained_edge.q=n,d=d.neighborAcross(m),e.edgeEventByPoints(a,b,n,d,n);else throw new r("poly2tri EdgeEvent: Collinear not supported!",[c,n,b]);else{var f=d.pointCW(m),g=l(c,f,b);if(g===k.COLLINEAR)if(d.containsPoints(c,f))d.markConstrainedEdgeByPoints(c,f),a.edge_event.constrained_edge.q=f,d=d.neighborAcross(m),e.edgeEventByPoints(a,b,f,d,f);else throw new r("poly2tri EdgeEvent: Collinear not supported!",[c,n,b]);else q===g?(d=q===k.CW?d.neighborCCW(m):d.neighborCW(m),e.edgeEventByPoints(a,
b,c,d,m)):e.flipEdgeEvent(a,b,c,d,m)}}},isEdgeSideOfTriangle:function(a,b,c){var d=a.edgeIndex(b,c);return-1!==d?(a.markConstrainedEdgeByIndex(d),(a=a.getNeighbor(d))&&a.markConstrainedEdgeByPoints(b,c),!0):!1},newFrontTriangle:function(a,b,c){var d=new g(b,c.point,c.next.point);d.markNeighbor(c.triangle);a.addToMap(d);b=new v(b);b.next=c.next;b.prev=c;c.next.prev=b;c.next=b;e.legalize(a,d)||a.mapTriangleToNodes(d);return b},fill:function(a,b){var c=new g(b.prev.point,b.point,b.next.point);c.markNeighbor(b.prev.triangle);
c.markNeighbor(b.triangle);a.addToMap(c);b.prev.next=b.next;b.next.prev=b.prev;e.legalize(a,c)||a.mapTriangleToNodes(c)},fillAdvancingFront:function(a,b){for(var c=b.next,d;c.next;){d=e.holeAngle(c);if(d>u||d<-u)break;e.fill(a,c);c=c.next}for(c=b.prev;c.prev;){d=e.holeAngle(c);if(d>u||d<-u)break;e.fill(a,c);c=c.prev}b.next&&b.next.next&&(d=e.basinAngle(b),d<z&&e.fillBasin(a,b))},basinAngle:function(a){return Math.atan2(a.point.y-a.next.next.point.y,a.point.x-a.next.next.point.x)},holeAngle:function(a){var b=
a.next.point.x-a.point.x,c=a.next.point.y-a.point.y,d=a.prev.point.x-a.point.x;a=a.prev.point.y-a.point.y;return Math.atan2(b*a-c*d,b*d+c*a)},legalize:function(a,b){for(var c=0;3>c;++c)if(!b.delaunay_edge[c]){var d=b.getNeighbor(c);if(d){var m=b.getPoint(c),f=d.oppositePoint(b,m),g=d.index(f);if(d.constrained_edge[g]||d.delaunay_edge[g])b.constrained_edge[c]=d.constrained_edge[g];else if(e.inCircle(m,b.pointCCW(m),b.pointCW(m),f))return b.delaunay_edge[c]=!0,d.delaunay_edge[g]=!0,e.rotateTrianglePair(b,
m,d,f),(m=!e.legalize(a,b))&&a.mapTriangleToNodes(b),(m=!e.legalize(a,d))&&a.mapTriangleToNodes(d),b.delaunay_edge[c]=!1,d.delaunay_edge[g]=!1,!0}}return!1},inCircle:function(a,b,c,d){var e=a.x-d.x;a=a.y-d.y;var f=b.x-d.x;b=b.y-d.y;var g=e*b-f*a;if(0>=g)return!1;var h=c.x-d.x;c=c.y-d.y;d=h*a-e*c;return 0>=d?!1:0<(e*e+a*a)*(f*c-h*b)+(f*f+b*b)*d+(h*h+c*c)*g},rotateTrianglePair:function(a,b,c,d){var e,f,g,h;e=a.neighborCCW(b);f=a.neighborCW(b);g=c.neighborCCW(d);h=c.neighborCW(d);var k,l,p,r;k=a.getConstrainedEdgeCCW(b);
l=a.getConstrainedEdgeCW(b);p=c.getConstrainedEdgeCCW(d);r=c.getConstrainedEdgeCW(d);var s,t,u,v;s=a.getDelaunayEdgeCCW(b);t=a.getDelaunayEdgeCW(b);u=c.getDelaunayEdgeCCW(d);v=c.getDelaunayEdgeCW(d);a.legalize(b,d);c.legalize(d,b);c.setDelaunayEdgeCCW(b,s);a.setDelaunayEdgeCW(b,t);a.setDelaunayEdgeCCW(d,u);c.setDelaunayEdgeCW(d,v);c.setConstrainedEdgeCCW(b,k);a.setConstrainedEdgeCW(b,l);a.setConstrainedEdgeCCW(d,p);c.setConstrainedEdgeCW(d,r);a.clearNeigbors();c.clearNeigbors();e&&c.markNeighbor(e);
f&&a.markNeighbor(f);g&&a.markNeighbor(g);h&&c.markNeighbor(h);a.markNeighbor(c)},fillBasin:function(a,b){l(b.point,b.next.point,b.next.next.point)===k.CCW?a.basin.left_node=b.next.next:a.basin.left_node=b.next;for(a.basin.bottom_node=a.basin.left_node;a.basin.bottom_node.next&&a.basin.bottom_node.point.y>=a.basin.bottom_node.next.point.y;)a.basin.bottom_node=a.basin.bottom_node.next;if(a.basin.bottom_node!==a.basin.left_node){for(a.basin.right_node=a.basin.bottom_node;a.basin.right_node.next&&a.basin.right_node.point.y<
a.basin.right_node.next.point.y;)a.basin.right_node=a.basin.right_node.next;a.basin.right_node!==a.basin.bottom_node&&(a.basin.width=a.basin.right_node.point.x-a.basin.left_node.point.x,a.basin.left_highest=a.basin.left_node.point.y>a.basin.right_node.point.y,e.fillBasinReq(a,a.basin.bottom_node))}},fillBasinReq:function(a,b){if(!e.isShallow(a,b)){e.fill(a,b);var c;if(!(b.prev===a.basin.left_node&&b.next===a.basin.right_node)){if(b.prev===a.basin.left_node){c=l(b.point,b.next.point,b.next.next.point);
if(c===k.CW)return;b=b.next}else if(b.next===a.basin.right_node){c=l(b.point,b.prev.point,b.prev.prev.point);if(c===k.CCW)return;b=b.prev}else b=b.prev.point.y<b.next.point.y?b.prev:b.next;e.fillBasinReq(a,b)}}},isShallow:function(a,b){return a.basin.width>(a.basin.left_highest?a.basin.left_node.point.y-b.point.y:a.basin.right_node.point.y-b.point.y)?!0:!1},fillEdgeEvent:function(a,b,c){a.edge_event.right?e.fillRightAboveEdgeEvent(a,b,c):e.fillLeftAboveEdgeEvent(a,b,c)},fillRightAboveEdgeEvent:function(a,
b,c){for(;c.next.point.x<b.p.x;)l(b.q,c.next.point,b.p)===k.CCW?e.fillRightBelowEdgeEvent(a,b,c):c=c.next},fillRightBelowEdgeEvent:function(a,b,c){c.point.x<b.p.x&&(l(c.point,c.next.point,c.next.next.point)===k.CCW?e.fillRightConcaveEdgeEvent(a,b,c):(e.fillRightConvexEdgeEvent(a,b,c),e.fillRightBelowEdgeEvent(a,b,c)))},fillRightConcaveEdgeEvent:function(a,b,c){e.fill(a,c.next);c.next.point!==b.p&&(l(b.q,c.next.point,b.p)===k.CCW&&l(c.point,c.next.point,c.next.next.point)===k.CCW)&&e.fillRightConcaveEdgeEvent(a,
b,c)},fillRightConvexEdgeEvent:function(a,b,c){l(c.next.point,c.next.next.point,c.next.next.next.point)===k.CCW?e.fillRightConcaveEdgeEvent(a,b,c.next):l(b.q,c.next.next.point,b.p)===k.CCW&&e.fillRightConvexEdgeEvent(a,b,c.next)},fillLeftAboveEdgeEvent:function(a,b,c){for(;c.prev.point.x>b.p.x;)l(b.q,c.prev.point,b.p)===k.CW?e.fillLeftBelowEdgeEvent(a,b,c):c=c.prev},fillLeftBelowEdgeEvent:function(a,b,c){c.point.x>b.p.x&&(l(c.point,c.prev.point,c.prev.prev.point)===k.CW?e.fillLeftConcaveEdgeEvent(a,
b,c):(e.fillLeftConvexEdgeEvent(a,b,c),e.fillLeftBelowEdgeEvent(a,b,c)))},fillLeftConvexEdgeEvent:function(a,b,c){l(c.prev.point,c.prev.prev.point,c.prev.prev.prev.point)===k.CW?e.fillLeftConcaveEdgeEvent(a,b,c.prev):l(b.q,c.prev.prev.point,b.p)===k.CW&&e.fillLeftConvexEdgeEvent(a,b,c.prev)},fillLeftConcaveEdgeEvent:function(a,b,c){e.fill(a,c.prev);c.prev.point!==b.p&&(l(b.q,c.prev.point,b.p)===k.CW&&l(c.point,c.prev.point,c.prev.prev.point)===k.CW)&&e.fillLeftConcaveEdgeEvent(a,b,c)},flipEdgeEvent:function(a,
b,c,d,f){var g=d.neighborAcross(f);if(!g)throw Error("poly2tri [BUG:FIXME] FLIP failed due to missing triangle!");var h=g.oppositePoint(d,f);if(w(f,d.pointCCW(f),d.pointCW(f),h))if(e.rotateTrianglePair(d,f,g,h),a.mapTriangleToNodes(d),a.mapTriangleToNodes(g),f===c&&h===b)c===a.edge_event.constrained_edge.q&&b===a.edge_event.constrained_edge.p&&(d.markConstrainedEdgeByPoints(b,c),g.markConstrainedEdgeByPoints(b,c),e.legalize(a,d),e.legalize(a,g));else{var k=l(c,h,b);d=e.nextFlipTriangle(a,k,d,g,f,
h);e.flipEdgeEvent(a,b,c,d,f)}else h=e.nextFlipPoint(b,c,g,h),e.flipScanEdgeEvent(a,b,c,d,g,h),e.edgeEventByPoints(a,b,c,d,f)},nextFlipTriangle:function(a,b,c,d,f,g){if(b===k.CCW)return b=d.edgeIndex(f,g),d.delaunay_edge[b]=!0,e.legalize(a,d),d.clearDelunayEdges(),c;b=c.edgeIndex(f,g);c.delaunay_edge[b]=!0;e.legalize(a,c);c.clearDelunayEdges();return d},nextFlipPoint:function(a,b,c,d){var e=l(b,d,a);if(e===k.CW)return c.pointCCW(d);if(e===k.CCW)return c.pointCW(d);throw new r("poly2tri [Unsupported] nextFlipPoint: opposing point on constrained edge!",
[b,d,a]);},flipScanEdgeEvent:function(a,b,c,d,f,g){var h=f.neighborAcross(g);if(!h)throw Error("poly2tri [BUG:FIXME] FLIP failed due to missing triangle");f=h.oppositePoint(f,g);w(c,d.pointCCW(c),d.pointCW(c),f)?e.flipEdgeEvent(a,c,f,h,f):(f=e.nextFlipPoint(b,c,h,f),e.flipScanEdgeEvent(a,b,c,d,h,f))}};s.PointError=r;s.Point=f;s.Triangle=g;s.SweepContext=h;s.triangulate=e.triangulate;s.sweep={Triangulate:e.triangulate};return s});