// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../geometry/Geometry ../Graphic ../geometry/support/jsonUtils ./Dictionary ./languageUtils ./ImmutableArray ../geometry/Point".split(" "),function(r,s,l,q,m,k,h,n,p){return function(){function g(a,c){this.attributes=this.geometry=null;this.immutable=!0;if(a instanceof g)this.attributes=a.attributes,this.geometry=a.geometry;else if(a instanceof q)this.geometry=a.geometry,this.attributes=void 0===a.attributes?{}:null===a.attributes?{}:a.attributes;else if(a instanceof k)this.attributes=
a.field("attributes"),null!==this.attributes&&(this.attributes=this.attributes instanceof k?this.attributes.attributes:null),this.geometry=a.field("geometry"),null!==this.geometry&&(this.geometry instanceof k?this.geometry=g.parseGeometryFromDictionary(this.geometry):this.geometry instanceof l||(this.geometry=null));else if(c instanceof l||null===c)this.geometry=c,this.attributes=void 0===a?{}:null===a?{}:a;else if("string"===typeof a){var b=JSON.parse(a);null!==b.geometry&&void 0!==b.geometry&&(this.geometry=
m.fromJSON(b.geometry));this.attributes=void 0===b.attributes?{}:null===b.attributes?{}:b.attributes}else void 0===a?this.attributes={}:null===a&&(this.attributes={}),this.geometry=null}g.prototype.castToText=function(){var a="",c;for(c in this.attributes){""!==a&&(a+=",");var b=this.attributes[c];null!=b&&(h.isBoolean(b)||h.isNumber(b)||h.isString(b)?a+=JSON.stringify(c)+":"+JSON.stringify(b):b instanceof l?a+=JSON.stringify(c)+":"+h.toStringExplicit(b):b instanceof n?a+=JSON.stringify(c)+":"+h.toStringExplicit(b):
b instanceof Array?a+=JSON.stringify(c)+":"+h.toStringExplicit(b):b instanceof Date?a+=JSON.stringify(c)+":"+JSON.stringify(b):null!==b&&"object"===typeof b&&void 0!==b.castToText&&(a+=JSON.stringify(c)+":"+b.castToText()))}return'{"geometry":'+(null===this.geometry?"null":h.toStringExplicit(this.geometry))+',"attributes":'+a+"}"};g.prototype._fixDateFields=function(a){for(var c=0;c<a.length;c++){var b=this.attributes[a[c]];if(null!==b)if(void 0===b)for(var d in this.attributes){if(d.toLowerCase()===
a[c]){b=this.attributes[d];null!==b&&!(b instanceof Date)&&(this.attributes[d]=new Date(b));break}}else b instanceof Date||(this.attributes[a[c]]=new Date(b))}};g.prototype.field=function(a){var c=a.toLowerCase();a=this.attributes[a];if(void 0!==a)return a;for(var b in this.attributes)if(b.toLowerCase()===c)return this.attributes[b];throw Error("Field not Found");};g.prototype.setField=function(a,c){if(this.immutable)throw Error("Feature is Immutable");var b=a.toLowerCase();if(void 0===this.attributes[a])for(var d in this.attributes)if(d.toLowerCase()===
b){this.attributes[d]=c;return}this.attributes[a]=c};g.prototype.hasField=function(a){var c=a.toLowerCase();if(void 0!==this.attributes[a])return!0;for(var b in this.attributes)if(b.toLowerCase()===c)return!0;return!1};g.prototype.keys=function(){var a=[],c;for(c in this.attributes)a.push(c);return a=a.sort()};g.fromFeature=function(a){return new g(a)};g.parseGeometryFromDictionary=function(a){a=g.convertDictionaryToJson(a,!0);void 0!==a.spatialreference&&(a.spatialReference=a.spatialreference,delete a.spatialreference);
void 0!==a.rings&&(a.rings=this.fixPathArrays(a.rings,!0===a.hasZ,!0===a.hasM));void 0!==a.paths&&(a.paths=this.fixPathArrays(a.paths,!0===a.hasZ,!0===a.hasM));void 0!==a.points&&(a.points=this.fixPointArrays(a.points,!0===a.hasZ,!0===a.hasM));return m.fromJSON(a)};g.fixPathArrays=function(a,c,b){var d=[];if(a instanceof Array)for(var f=0;f<a.length;f++)d.push(this.fixPointArrays(a[f],c,b));else if(a instanceof n)for(f=0;f<a.length();f++)d.push(this.fixPointArrays(a.get(f),c,b));return d};g.fixPointArrays=
function(a,c,b){var d=[];if(a instanceof Array)for(var f=0;f<a.length;f++){var e=a[f];e instanceof p?c&&b?d.push([e.x,e.y,e.z,e.m]):c?d.push([e.x,e.y,e.z]):b?d.push([e.x,e.y,e.m]):d.push([e.x,e.y]):d.push(e)}else if(a instanceof n)for(f=0;f<a.length();f++)e=a.get(f),e instanceof p?c&&b?d.push([e.x,e.y,e.z,e.m]):c?d.push([e.x,e.y,e.z]):b?d.push([e.x,e.y,e.m]):d.push([e.x,e.y]):d.push(e);return d};g.convertDictionaryToJson=function(a,c){void 0===c&&(c=!1);var b={},d;for(d in a.attributes){var f=a.attributes[d];
f instanceof k&&(f=g.convertDictionaryToJson(f));c?b[d.toLowerCase()]=f:b[d]=f}return b};g.parseAttributesFromDictionary=function(a){var c={},b;for(b in a.attributes){var d=a.attributes[b];if(h.isString(d)||h.isNumber(d)||h.isBoolean(d)||h.isDate(d))c[b]=d;else throw Error("Illegal Argument");}return c};g.fromJson=function(a){var c=null;null!==a.geometry&&void 0!==a.geometry&&(c=m.fromJSON(a.geometry));var b={};if(null!==a.attributes&&void 0!==a.attributes)for(var d in a.attributes){var f=a.attributes[d];
if(h.isString(f)||h.isNumber(f)||h.isBoolean(f)||h.isDate(f))b[d]=f;else throw Error("Illegal Argument");}return new g(b,c)};return g}()});