// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../geometry/Geometry ../moment dojo/number ./ImmutableArray ../kernel ./ImmutablePointArray ./ImmutablePathArray ../geometry/Point".split(" "),function(z,c,q,g,r,m,w,x,y,s){function k(a,b,d){if(""===b||null===b||void 0===b||b===d||b===d)return a;do a=a.replace(b,d);while(-1!==a.indexOf(b));return a}function e(a){return"string"===typeof a||a instanceof String}function h(a){return"boolean"===typeof a}function l(a){return"number"===typeof a}function t(a){return a instanceof Array}
function f(a){return a instanceof Date}function n(a,b){if(!1===isNaN(a)){if(void 0===b||null===b||""===b)return a.toString();b=k(b,"\u2030","");b=k(b,"\u00a4","");return r.format(a,{pattern:b})}return a.toString()}function p(a,b){var d=g(a);return void 0===b||null===b||""===b?d.format():d.format(b)}function u(a,b){if(e(a))return a;if(null===a)return"";if(l(a))return n(a,b);if(h(a))return a.toString();if(f(a))return p(a,b);if(a instanceof q)return JSON.stringify(a.toJSON());if(t(a)){for(var d=[],c=
0;c<a.length;c++)d[c]=v(a[c]);return"["+d.join(",")+"]"}if(a instanceof m){d=[];for(c=0;c<a.length();c++)d[c]=v(a.get(c));return"["+d.join(",")+"]"}return null!==a&&"object"===typeof a&&void 0!==a.castToText?a.castToText():""}function v(a){if(null!==a){if(h(a)||l(a)||e(a))return JSON.stringify(a);if(a instanceof q||a instanceof m||a instanceof Array)return u(a);if(a instanceof Date)return JSON.stringify(a);if(null!==a&&"object"===typeof a&&void 0!==a.castToText)return a.castToText()}return"null"}
c.isVersion4=0===w.version.indexOf("4.");c.multiReplace=k;c.defaultUndefined=function(a,b){return void 0===a?b:a};c.isString=e;c.isBoolean=h;c.isNumber=l;c.isArray=t;c.isImmutableArray=function(a){return a instanceof m};c.isDate=f;c.pcCheck=function(a,b,c){if(a.length<b||a.length>c)throw Error("Function called with wrong number of Parameters");};c.generateUUID=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c=(a+16*Math.random())%
16|0;a=Math.floor(a/16);return("x"===b?c:c&3|8).toString(16)})};c.formatNumber=n;c.formatDate=p;c.equalityTest=function(a,b){if(a===b)return!0;if(f(a)&&f(b))return a.getTime()===b.getTime();if(a instanceof y||a instanceof x)return a.equalityTest(b);if(a instanceof s&&b instanceof s){var d=void 0,e=void 0;c.isVersion4?(d=a.cache._arcadeCacheId,e=b.cache._arcadeCacheId):(d=a.getCacheValue("_arcadeCacheId"),e=b.getCacheValue("_arcadeCacheId"));if(void 0!==d&&null!==d)return d===e}return void 0!==a&&
void 0!==b&&null!==a&&null!==b&&"object"===typeof a&&"object"===typeof b&&a._arcadeCacheId===b._arcadeCacheId&&void 0!==a._arcadeCacheId&&null!==a._arcadeCacheId?!0:!1};c.toString=function(a,b){return e(a)?a:null===a?"":l(a)?n(a,b):h(a)?a.toString():f(a)?p(a,b):""};c.toStringExplicit=u;c.toNumber=function(a,b){return l(a)?a:null===a||f(a)||h(a)||""===a||void 0===a?NaN:void 0!==b&&e(a)?(b=k(b,"\u2030",""),b=k(b,"\u00a4",""),r.parse(a,{pattern:b})):Number(a)};c.toDate=function(a,b){if(f(a))return a;
if(e(a)){var c=g(a,[void 0===b||null===b||""===b?g.ISO_8601:b]);if(c.isValid())return c.toDate()}return null};c.toDateM=function(a,b){if(f(a))return g(a);if(e(a)){var c=g(a,[void 0===b||null===b||""===b?g.ISO_8601:b]);if(c.isValid())return c}return null};c.toBoolean=function(a){if(h(a))return a;e(a)&&(a=a.toLowerCase());switch(a){case !0:case "true":case 1:case "1":case "on":case "yes":return!0;default:return!1}};c.fixSpatialReference=function(a,b){if(null===a)return null;if(null===a.spatialReference||
void 0===a.spatialReference)a.spatialReference=b;return a}});