// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports dojo/aspect ./utils ./get ../ArrayPool ../ObjectPool".split(" "),function(l,f,h,e,r,k,s){function m(b,a,c){var d=b.binding;d||(d=b.binding=new t(b));d.add(a,c);return d.uid}function n(b,a,c){var d=b.binding;d&&(d.remove(a,c),0===d.numCursors&&(d.destroy(),b.binding=null))}function p(b,a,c){return e.parse(b,a,c,function(a,c,b){var g=q.acquire();g.install(a,c,b);return{remove:e.once(function(){q.release(g);g=null})}})}l=function(){function b(){this.stack=[]}b.prototype.install=
function(a,c,d){this.target=a;this.properties=e.getProperties(a);this.path=c;this.chain=e.pathToArray(c);this.callback=d;this.stack.push({target:this.target,properties:this.properties,propertyName:this.chain[0],uid:m(this.properties,this.chain[0],this)});this.moveForward()};b.prototype.dispose=function(){for(var a;a=this.stack.pop();)n(a.properties,a.propertyName,this);this.target=this.callback=this.chain=this.path=null};b.prototype.propertyInvalidated=function(a){this.callback(this.path,this.target)};
b.prototype.propertyCommitted=function(a){this.moveTo(a);this.moveForward();this.callback(this.path,this.target)};b.prototype.value=function(a){a="number"===typeof a?this.stack[a]:a;return r.valueOf(a.properties,a.propertyName,!1)};b.prototype.index=function(){return this.stack.length-1};b.prototype.last=function(){return this.stack[this.index()]};b.prototype.moveTo=function(a){for(var c=this.last();c.uid!==a;)n(c.properties,c.propertyName,this),this.stack.pop(),c=this.last()};b.prototype.moveForward=
function(){for(var a=this.value(this.last()),c,d;a&&this.index()<this.chain.length-1;){c=this.chain[this.index()+1];d=e.getProperties(a);if(!d)break;this.stack.push({target:a,properties:d,propertyName:c,uid:m(d,c,this)});a=this.value(this.last())}};return b}();var u=0,t=function(){function b(a){var c=this;this.properties=a;this.uid="binding-"+u++;this.numCursors=0;this.cursors={};this.aspectHandles=[h.before(this.properties,"propertyInvalidated",function(a){return c.propertyInvalidated(a)}),h.after(this.properties,
"propertyCommitted",function(a,b){return c.propertyCommitted(a)},!0),h.before(this.properties,"destroy",function(){return c.destroy()})]}b.prototype.destroy=function(){var a=this.cursors;this.cursors={};this.numCursors=0;this.aspectHandles.forEach(function(a){return a.remove()});for(var c=0,b=Object.getOwnPropertyNames(a);c<b.length;c++){var e=a[b[c]];if(e){for(var f=0,g=e;f<g.length;f++)g[f].dispose();k.release(e)}}};b.prototype.add=function(a,c){this.cursors[a]||(this.cursors[a]=k.acquire());this.cursors[a].push(c);
this.numCursors+=1};b.prototype.remove=function(a,c){var b=this.cursors[a];this.cursors[a]&&(b.splice(b.indexOf(c),1),0===b.length&&(this.cursors[a]=null,k.release(b)),this.numCursors-=1)};b.prototype.propertyInvalidated=function(a){var b=this;(a=this.cursors[a])&&a.forEach(function(a){return a.propertyInvalidated(b.uid)})};b.prototype.propertyCommitted=function(a){var b=this;(a=this.cursors[a])&&a.forEach(function(a){return a.propertyCommitted(b.uid)})};return b}(),q=new s(l);f.whenMayChange=p;Object.defineProperty(f,
"__esModule",{value:!0});f.default=p});