// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/has dojo/on dojo/aspect ./ArrayPool ./ObjectPool ./Accessor ./Evented ./Scheduler ./accessorSupport/ensureType".split(" "),function(r,w,x,q,y,z,A,B,u){u=u.ensureType;var C=function(){},D=x.after,E=0,s=function(a){return!a?[]:(!a?0:a.isInstanceOf&&a.isInstanceOf(h))?a.toArray():a.length?Array.prototype.slice.apply(a):[]},t=function(a){return!a||!a.length?void 0:a[0]};r=function(){this.target=null;this.defaultPrevented=this.cancellable=!1};r.prototype.preventDefault=function(){this.cancellable&&
(this.defaultPrevented=!0)};r.prototype.reset=function(a){this.defaultPrevented=!1;this.item=a};var p=new y(r,function(){this.target=this.item=null}),h=z.createSubclass([A],{declaredClass:"esri.core.Collection",properties:{length:{},items:{}},constructor:function(){this.id=(new Date).getTime().toString(16)+"-collection"+E++;this._chgListeners=[];this._timer=this._notification=null;this._items=[];this._dispatchColChange=this._dispatchColChange.bind(this)},normalizeCtorArgs:function(a){return!a?{}:
Array.isArray(a)||a.isInstanceOf&&a.isInstanceOf(h)?{items:a}:a},onchange:null,"onbefore-add":null,"onbefore-remove":null,"onafter-add":null,"onafter-remove":null,length:0,_itemsGetter:function(){return this._items},_itemsSetter:function(a){this._splice(0,this.length,s(a))},on:function(a,b){return w.parse(this,a,b,function(a,d){if("change"===d){a._notification&&a._dispatchColChange();var g={removed:!1,callback:b};a._chgListeners.push(g);return{remove:function(){this.remove=C;g.removed=!0;a._chgListeners.splice(a._chgListeners.indexOf(g),
1)}}}return D(a,"on"+d,b,!0)})},hasEventListener:function(a){return"change"===a?0<this._chgListeners.length:this.inherited(arguments)},add:function(a,b){b=this.getNextIndex(b);this._splice(b,0,[a]);return this},addMany:function(a,b){b=this.getNextIndex(b);this._splice(b,0,s(a))},removeAll:function(){return this._splice(0,this.length)||[]},clone:function(){return this._createNewInstance({items:this._items})},concat:function(a){var b=s(arguments).map(s);return this._createNewInstance({items:Array.prototype.concat.apply(this._items,
b)})},drain:function(a,b){var c=this.removeAll(),d,g;d=0;for(g=c.length;d<g;d++)a.call(b,c[d],d,c)},every:function(a,b){return this._items.every(a,b)},filter:function(a,b){var c;c=2===arguments.length?this._items.filter(a,b):this._items.filter(a);return this._createNewInstance({items:c})},find:function(a,b){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var c=this._items,d,g=0,f=this.length;g<f;g++)if(d=c[g],a.call(b,d,g,c))return d},findIndex:function(a,b){if("function"!==
typeof a)throw new TypeError(a+" is not a function");var c=this._items,d=this.length,g,f;for(f=0;f<d;f++)if(g=c[f],a.call(b,g,f,c))return f;return-1},forEach:function(a,b){return this._items.forEach(a,b)},getItemAt:function(a){return this._items[a]},getNextIndex:function(a){var b=this.length;a=null==a?b:a;0>a?a=0:a>b&&(a=b);return a},includes:function(a,b){return!arguments.length?!1:-1!==this._items.indexOf(a,b||0)},indexOf:function(a,b){var c=arguments.length;return 0===c?-1:1===c?this._items.indexOf(a):
this._items.indexOf(a,b)},join:function(a){return arguments.length?this._items.join(a):this._items.join()},lastIndexOf:function(a,b){var c=arguments.length;return 1===c?this._items.lastIndexOf(a):2===c?this._items.lastIndexOf(a,b):-1},map:function(a,b){return new h({items:this._items.map(a,b)})},reorder:function(a,b){var c=this.indexOf(a),d=this._items.length-1;if(-1!==c)return b=null==b?d:b,0>b?b=0:b>d&&(b=d),c!==b&&(this._splice(c,1),this._splice(b,0,[a])),a},pop:function(){return!this._items.length?
void 0:t(this._splice(this._items.length-1,1))},push:function(a){this._splice(this._items.length,0,Array.prototype.slice.call(arguments));return this._items.length},reduce:function(a,b){var c=this._items;return 2===arguments.length?c.reduce(a,b):c.reduce(a)},reduceRight:function(a,b){var c=this._items;return 2===arguments.length?c.reduceRight(a,b):c.reduceRight(a)},remove:function(a){a=this.indexOf(a);return this.removeAt(a)},removeAt:function(a){if(0<=a&&a<this.length)return t(this._splice(a,1))},
removeMany:function(a){if(!a||!a.length)return a;(!a?0:a.isInstanceOf&&a.isInstanceOf(h))&&(a=a.toArray());var b=this._items,c=[],d,g,f;d=0;for(g=a.length;d<g;d++)f=a[d],f=b.indexOf(f),-1<f&&(f=t(this._splice(f,1)))&&c.push(f);return c},shift:function(){return!this._items.length?void 0:t(this._splice(0,1))},slice:function(a,b){var c=arguments.length,d=null;0===c?d=this._items.slice():1===c?d=this._items.slice(a):2===c&&(d=this._items.slice(a,b));return this._createNewInstance({items:d})},some:function(a,
b){return this._items.some(a,b)},sort:function(a){var b=this._splice(0,this._items.length);if(!b)return this;arguments.length?b.sort(a):b.sort();this._splice(0,0,b);return this},toArray:function(){return this._items.slice()},toLocaleString:function(){return this._items.toLocaleString()},toString:function(){return this._items.toString()},unshift:function(a){this._splice(0,0,Array.prototype.slice.call(arguments));return this._items.length},_createNewInstance:function(a){return new this.constructor(a)},
_splice:function(a,b,c){var d=this._items,g=this.itemType,f,k,m,e;this.hasEventListener("change")&&!this._notification&&(this._notification={listeners:this._chgListeners.slice(),items:d.slice(),changes:[]},this._timer&&this._timer.remove(),this._timer=B.schedule(this._dispatchColChange));if(b){f=d.splice(a,b);if(this.hasEventListener("before-remove")){e=p.acquire();e.target=this;e.cancellable=!0;b=0;for(k=f.length;b<k;b++)m=f[b],e.reset(m),this.emit("before-remove",e),e.defaultPrevented&&(f.splice(b,
1),d.splice(a,0,m),a+=1,b-=1,k-=1);p.release(e)}this.length=this._items.length;if(this.hasEventListener("after-remove")){e=p.acquire();e.target=this;e.cancellable=!1;b=0;for(k=f.length;b<k;b++)m=f[b],e.reset(m),this.emit("after-remove",e);p.release(e)}this._notifyColChange(null,f)}c&&c.length&&(g&&(c=c.map(u.bind(null,g))),this.hasEventListener("before-add")&&(e=p.acquire(),e.target=this,e.cancellable=!0,c=c.filter(function(a){e.reset(a);this.emit("before-add",e);return!e.defaultPrevented},this),
p.release(e)),Array.prototype.splice.apply(d,[a,0].concat(c)),this.length=this._items.length,this.hasEventListener("after-add")&&(e=p.acquire(),e.target=this,e.cancellable=!1,c.forEach(function(a){e.reset(a);this.emit("after-add",e)},this),p.release(e)),this._notifyColChange(c,null));return f},_notifyColChange:function(a,b){this.hasEventListener("change")&&this._notification.changes.push({added:a,removed:b})},_dispatchColChange:function(){this._timer&&(this._timer.remove(),this._timer=null);if(this._notification){var a=
this._notification,b=a.items,c=a.changes,d=q.acquire(),g=q.acquire(),f=q.acquire(),k,m,e,h,l,n;this._notification=null;k=0;for(m=c.length;k<m;k++){h=c[k];if(h.added){l=h.added;if(0<g.length)for(e=l.length-1;0<=e;e--)n=g.indexOf(l[e]),-1!==n&&(l.splice(e,1),f.push(g.splice(n,1)[0]));d=d.concat(l)}if(h.removed){l=h.removed;if(0<d.length||0<f.length)for(e=l.length-1;0<=e;e--)n=d.indexOf(l[e]),-1!==n?(d.splice(n,1),l.splice(e,1)):(n=f.indexOf(l[e]),-1!==n&&f.splice(n,1));g=g.concat(l)}}f=f.filter(function(a){return b.indexOf(a)!==
this._items.indexOf(a)},this);if(a.listeners&&(d.length||g.length||f.length)){h={target:this,added:d,removed:g,moved:f};k=0;for(m=a.listeners.length;k<m;k++)c=a.listeners[k],c.removed||c.callback.call(this,h)}q.release(d);q.release(g);q.release(f)}}}),v={};h.ofType=function(a){var b=a.prototype.declaredClass;if(!b)return h;if(b&&v[b])return v[b];var c=h.createSubclass({declaredClass:"esri.core.Collection\x3c"+b+"\x3e"});Object.defineProperty(c.prototype,"itemType",{value:a,configurable:!1,enumerable:!1,
writable:!1});return v[b]=c};return h});