// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["./ArrayPool","./ObjectPool","./nextTick","./requestAnimationFrame","./now"],function(f,d,q,r,l){var g=["prepare","preRender","render","postRender","update"],m=new d(function(){this.isActive=!0;this.callback=null},function(){this.isActive=!1;this.callback=null}),s=function(){},t=function(){this.item.isActive=!1;n.release(this)},h={time:0,deltaTime:0,spendInFrame:0,spendInTask:0},n=new d(function(){this.remove=t;this.item=null},function(){this.remove=s;this.item=null}),p=function(a){var b=
n.acquire();b.item=a;return b};d=function(){this._boundDispatch=this._dispatch.bind(this);this._deferred=f.acquire();this._isProcessing=!1;this._queue=f.acquire();this._task=null;this.deferWhileProcessing=!1;this._frameTasks=f.acquire();this._phaseTasks={};this._previousFrameTime=-1;for(var a=0;a<g.length;a++)this._phaseTasks[g[a]]=f.acquire();this._boundAnimationFrame=this._animationFrame.bind(this);this._animationFrameRequested=this.executing=!1};d.prototype={schedule:function(a){if(this._isProcessing&&
this.deferWhileProcessing)return this._defer(a);var b=m.acquire();b.callback=a;this._schedule(b);return p(b)},_defer:function(a){var b=m.acquire();b.callback=a;this._deferred||(this._deferred=f.acquire());this._deferred.push(b);return p(b)},_dispatch:function(){var a=this._queue;this._isProcessing=!0;this._task.remove();for(this._task=null;a.length;){var b=a.shift();b.isActive&&(b.isActive=!1,b.callback())}this._isProcessing=!1;if((a=this._deferred)&&a.length){for(this._deferred=null;a.length;)this._schedule(a.shift());
f.release(a)}},_schedule:function(a){this._task||(this._task=q(this._boundDispatch));this._queue.push(a)},addFrameTask:function(a){var b={phases:a,paused:!1,pausedAt:0,epoch:-1,dt:0,ticks:-1,removed:!1};this._frameTasks.push(b);for(var e=0;e<g.length;e++){var c=g[e];a[c]&&this._phaseTasks[c].push(b)}this._animationFrameRequested||(this._previousFrameTime=-1,this._requestAnimationFrame());return{isPaused:function(){return b.paused},remove:function(){b.removed=!0},pause:function(){b.paused=!0;b.pausedAt=
l()},resume:function(){b.paused=!1;-1!==b.epoch&&(b.epoch+=l()-b.pausedAt)}}},clearFrameTasks:function(){for(var a=0;a<this._frameTasks.length;a++)this._frameTasks[a].removed=!0},_purge:function(){for(var a=0;a<this._frameTasks.length;){var b=this._frameTasks[a];a++;if(b.removed){this._frameTasks.splice(a-1,1);for(var e=0;e<g.length;e++){var c=g[e];if(b.phases[c]){var c=this._phaseTasks[c],d=c.indexOf(b);-1!==d&&c.splice(d,1)}}}}},_animationFrame:function(a){this._animationFrameRequested=!1;this.executing=
!0;0<this._frameTasks.length&&this._requestAnimationFrame();a=l();0>this._previousFrameTime&&(this._previousFrameTime=a);var b=a-this._previousFrameTime;this._previousFrameTime=a;for(var e=0;e<this._frameTasks.length;e++){var c=this._frameTasks[e];-1!==c.epoch&&(c.dt=b)}for(e=0;e<g.length;e++)for(var b=g[e],d=this._phaseTasks[b],f=0;f<d.length;f++)c=d[f],!c.paused&&!c.removed&&(0===e&&c.ticks++,-1===c.epoch&&(c.epoch=a),h.time=a,h.deltaTime=c.dt,h.spendInFrame=l()-a,h.spendInTask=a-c.epoch,c.phases[b].call(c,
h));this._purge();this.executing=!1},_requestAnimationFrame:function(){r(this._boundAnimationFrame);this._animationFrameRequested=!0}};var k=new d;d.schedule=function(a){return k.schedule(a)};d.addFrameTask=function(a){return k.addFrameTask(a)};d.clearFrameTasks=function(){return k.clearFrameTasks()};Object.defineProperty(d,"executing",{get:function(){return k.executing}});d.instance=k;return d});