// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/window dojo/_base/lang dojo/_base/url dojo/io-query ../config ./sniff".split(" "),function(h,m,n,t,s,u){h=new n(h.global.location);var p=h.path,b={},r=s.request,q=h.scheme+":";s=h.scheme+"://"+h.host+(null!=h.port?":"+h.port:"")+p.substring(0,p.lastIndexOf(p.split("/")[p.split("/").length-1]));"file:"===q&&(q="http:");var v={};b.corsServersUrlCache=v;b.burstUrlCache=function(){b.corsServersUrlCache=v={}};b.appUrl=h;b._appBaseUrl=s;b._toURL=function(a){if("string"===typeof a)return new n(b.getAbsoluteUrl(a));
a.scheme||(a.scheme=b.appUrl.scheme);return a};b.urlToObject=function(a){var b={},c=new n(a),e=a.indexOf("?");null===c.query?b={path:a,query:null}:(b.path=a.substring(0,e),b.query=t.queryToObject(c.query));c.fragment&&(b.hash=c.fragment,null===c.query&&(b.path=b.path.substring(0,b.path.length-(c.fragment.length+1))));return b};b.getProxyUrl=function(a,d){var c=m.isString(a)?0===m.trim(a).toLowerCase().indexOf("https:"):a,e=r.proxyUrl,g,f;if(m.isString(a)&&(f=b.getProxyRule(a)))e=f.proxyUrl;if(!e)throw console.log("esri/config: esriConfig.request.proxyUrl is not set. If making a request to a CORS-enabled server, please push the domain into esriConfig.request.corsEnabledServers."),
Error("esri/config: esriConfig.request.proxyUrl is not set. If making a request to a CORS-enabled server, please push the domain into esriConfig.request.corsEnabledServers.");c&&(!1!==d&&"https"===b.appUrl.scheme)&&(c=e,0!==c.toLowerCase().indexOf("http")&&(c=b.getAbsoluteUrl(c)),c=c.replace(/^http:/i,"https:"),b.canUseXhr(c)&&(e=c,g=1));e=b.urlToObject(e);e._xo=g;return e};b.addProxy=function(a){var d=b.getProxyRule(a),c;d?c=b.urlToObject(d.proxyUrl):r.forceProxy&&(c=b.getProxyUrl());c&&(d=b.urlToObject(a),
a=c.path+"?"+d.path,(c=t.objectToQuery(m.mixin(c.query||{},d.query)))&&(a+="?"+c));return a};b.addProxyRule=function(a){var d=b.urlToObject(a.urlPrefix).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),c=r.proxyRules,e,g=c.length,f,k=g;a.urlPrefix=d;for(e=0;e<g;e++){f=c[e].urlPrefix;if(0===d.indexOf(f)){if(d.length===f)return-1;k=e;break}0===f.indexOf(d)&&(k=e+1)}c.splice(k,0,a);return k};b.getProxyRule=function(a){var d=r.proxyRules,c=d.length,e=b.urlToObject(a).path.replace(/([^\/])$/,
"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),g;for(a=0;a<c;a++)if(0===e.indexOf(d[a].urlPrefix)){g=d[a];break}return g};b.hasSameOrigin=function(a,d,c){a=b._toURL(a);d=b._toURL(d);return(c||a.scheme===d.scheme)&&a.host.toUpperCase()===d.host.toUpperCase()&&a.port===d.port};b.canUseXhr=function(a,d){var c=!!u("esri-phonegap"),e=b.hasSameOrigin,g=r.corsEnabledServers||[],f,k,h,l,p,q=-1;m.isString(a)&&(a=a.toLowerCase(),a=0===a.indexOf("http")?new n(a):b.appUrl);if(!c&&u("esri-cors")){k=0;for(h=
g.length;k<h;k++){f=g[k];l=b.corsServersUrlCache;l[f]||(0!==m.trim(f).toLowerCase().indexOf("http")?l[f]=[new n("http://"+f),new n("https://"+f)]:l[f]=[new n(f)]);f=l[f];l=0;for(p=f.length;l<p;l++)if(e(a,f[l])){q=k;c=!0;break}}}return d?q:c};b.getAbsoluteUrl=function(a){return m.isString(a)&&!/^https?:\/\//i.test(a)?0===a.indexOf("//")?q+a:0===a.indexOf("/")?q+"//"+b.appUrl.host+(b.appUrl.port?":"+b.appUrl.port:"")+a:b._appBaseUrl+a:a};b.isAbsoluteUrl=function(a){return/^[A-Za-z][A-Za-z0-9-+.]*:/.test(a)};
b.fixUrl=function(a){return b._ensureProtocol(a).replace(/^(https?:\/\/)(arcgis\.com)/i,"$1www.$2")};b.normalize=function(a){a=b._ensureProtocol(a);return a=b._ensureProperProtocolForAGOResource(a)};b.join=function(a,b){if(null==b)return a;for(var c=Array.prototype.slice.call(arguments),c=[].concat.apply([],c.map(function(a,b){return a.split("/")})),e=[],g=0;g<c.length;g++){var f=c[g];".."===f?e.pop():"."!==f&&(""!==f||1>=g)&&e.push(f)}return e.join("/")};b._ensureProtocol=function(a){var d;if(!a)return a;
/^\/\//i.test(a)&&(d=b.appUrl.scheme,a=("file"===d?"https":d)+":"+a);return a};b._ensureProperProtocolForAGOResource=function(a){return"https"===b.appUrl.scheme&&(/^http\:\/\/server\.arcgisonline\.com(?!:)/i.test(a)||/^http\:\/\/services\.arcgisonline\.com(?!:)/i.test(a)||/^http\:\/\/.+\.arcgis\.com(?!:)/i.test(a))?a.replace(/http:/i,"https:"):a};return b});