// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../core/Accessor ../../core/Collection ../../core/Error ../../core/Evented ../../core/HandleRegistry ../../core/lang ../../core/promiseList ../../core/watchUtils ../../geometry/Extent ../../geometry/Point ../../geometry/SpatialReference ../../geometry/support/scaleUtils ../../Graphic ../../PopupTemplate ../../styles/basic ../../symbols/PictureMarkerSymbol ../../symbols/SimpleFillSymbol ../../symbols/SimpleLineSymbol ../../symbols/SimpleMarkerSymbol ../../symbols/TextSymbol ../../tasks/Locator ../../tasks/support/Query dojo/_base/array dojo/_base/lang dojo/Deferred dojo/i18n!./nls/Search require".split(" "),
function(t,E,v,F,G,w,z,u,A,x,H,B,y,I,J,K,L,M,N,S,O,T,P,s,p,r,Q){var C={locator:new O({url:"//geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer"}),singleLineFieldName:"SingleLine",outFields:["Addr_type","Match_addr","StAddr","City"],name:r.esriLocatorName,localSearchOptions:{minScale:3E5,distance:5E4},placeholder:r.placeholder,resultSymbol:new K({url:Q.toUrl("./images/search-symbol-32.png"),size:24,width:24,height:24,xoffset:0,yoffset:0})},R=/https?:\/\/services.*\.arcgis\.com/i;t=t.createSubclass([F],
{properties:{activeSource:{},activeSourceIndex:{},allPlaceholder:{},autoNavigate:{},autoSelect:{},currentSuggestion:{},defaultSource:{readOnly:!0},resultGraphicEnabled:{},resultGraphic:{},locationToAddressDistance:{},maxInputLength:{},maxResults:{},maxSuggestions:{},minSuggestCharacters:{},placeholder:{},popup:{dependsOn:["view.popup"],readOnly:!0},popupEnabled:{},popupTemplate:{type:I},results:{},scale:{dependsOn:["view.scale"],readOnly:!0},searchAllEnabled:{},selectedResult:{},popupOpenOnSelect:{},
searchTerm:{},sources:{type:E},suggestionDelay:{},suggestions:{},suggestionsEnabled:{},view:{},zoomScale:{}},declaredClass:"esri.widgets.Search.SearchViewModel",constructor:function(){this._deferredSuggestions=[];this._handles=new G;this._manageSuggest=this._manageSuggest.bind(this)},getDefaults:function(){return s.mixin(this.inherited(arguments),{defaultSource:C,popupTemplate:{},sources:[C]})},initialize:function(){this._handles.add([u.init(this,"activeSourceIndex",function(a){this._updateActiveSource();
this._setPlaceholder(a)}.bind(this)),u.init(this,"allPlaceholder",function(){this._setPlaceholder(this.activeSourceIndex)}.bind(this)),u.init(this,"sources",this._setDefaultActiveSourceIndex.bind(this)),u.init(this,"searchTerm",function(a){this.currentSuggestion&&this.currentSuggestion.text!==a&&(this.currentSuggestion=null)}.bind(this)),u.init(this,"searchAllEnabled",this._setDefaultActiveSourceIndex.bind(this))])},destroy:function(){this.clearGraphics();this._viewReadyPromise&&this._viewReadyPromise.cancel();
this._handles.destroy();this._handles=null},_i18n:r,_defaultSR:H.WGS84,activeSource:null,activeSourceIndex:0,allPlaceholder:r.allPlaceholder,autoNavigate:!0,autoSelect:!0,resultGraphicEnabled:!0,popupEnabled:!0,currentSuggestion:null,defaultSource:null,resultGraphic:null,locationToAddressDistance:1500,maxInputLength:128,maxResults:6,maxSuggestions:6,minSuggestCharacters:1,placeholder:"",popup:null,_popupGetter:function(){return this.get("view.popup")||null},popupTemplate:null,results:null,scale:null,
_scaleGetter:function(){return this.get("view.scale")||null},searchAllEnabled:!0,selectedResult:null,popupOpenOnSelect:!0,searchTerm:"",sources:null,_sourcesSetter:function(a){a.forEach(function(a){a.name||(a.name=this._getSourceName(a))},this);this._set("sources",a)},suggestionDelay:150,suggestions:null,suggestionsEnabled:!0,view:null,zoomScale:1E3,clear:function(){this.set({searchTerm:"",results:null,suggestions:null,selectedResult:null,currentSuggestion:null});this.clearGraphics();this.emit("search-clear")},
search:function(a){this.emit("search-start");return this._viewReady().then(function(){return this._searchDeferred(a)}.bind(this)).then(function(a){var c=a.results;this.results=c;this.emit("search-complete",a);this._selectFirstResult(c,a.activeSourceIndex);return c}.bind(this))},suggest:function(){this.cancelSuggest();this._suggestionQueryTimer=setTimeout(this._manageSuggest,this.suggestionDelay)},cancelSuggest:function(){this._cancelDeferreds();this._suggestionQueryTimer&&clearTimeout(this._suggestionQueryTimer)},
select:function(a){var d=this._getDefaultSymbol(a),c,b=this.sources,e=this.activeSourceIndex,f=this.resultGraphicEnabled,h=this.autoNavigate,l=this.popupOpenOnSelect,k=this.popupEnabled,g=this.popupTemplate,n=a.feature.clone();this.selectedResult=a;if("all"===e){var q=this._getSourceIndexOfResult(a);null!==q&&(c=b.getItemAt(q),e=q)}else c=b.getItemAt(e);c&&(b=c.featureLayer,c.hasOwnProperty("resultSymbol")&&(d=c.resultSymbol),c.hasOwnProperty("resultGraphicEnabled")&&(f=c.resultGraphicEnabled),c.hasOwnProperty("autoNavigate")&&
(h=c.autoNavigate),c.hasOwnProperty("popupOpenOnSelect")&&(l=c.popupOpenOnSelect),c.hasOwnProperty("popupEnabled")&&(k=c.popupEnabled),c.hasOwnProperty("popupTemplate")?g=c.popupTemplate:b&&b.popupTemplate&&(g=b.popupTemplate));if(n){var m=this.resultGraphic,b=s.mixin({},n.attributes,this.getExtraSearchResultAttributes(a)),q=null;k&&(q=g);this._removeFromGraphics(m);m=new y({geometry:n.geometry,symbol:d,attributes:b,popupTemplate:q});"text-symbol"===m.get("symbol.type")&&(m.symbol.text=a.name);var D=
this.popup,d=this.view,g=new p;d&&h&&a&&a.hasOwnProperty("extent")?d.goTo(a.extent).always(g.resolve):g.resolve();g.then(function(){f&&this._addToGraphics(m);D&&(k&&l)&&D.open({features:[m],location:m.geometry})}.bind(this));this.resultGraphic=m}this.emit("select-result",{result:a,source:c,sourceIndex:e})},clearGraphics:function(){this.view&&this.view.graphics.remove(this.resultGraphic);this.resultGraphic=null},getExtraSearchResultAttributes:function(a){},_manageSuggest:function(a){return this._viewReady().then(function(){return this._suggestDeferred(a)}.bind(this)).then(function(a){var c=
null;a&&(c=a.results);this.suggestions=c;this.emit("suggest-complete",a);return c}.bind(this))},_addToGraphics:function(a){this.view&&this.view.graphics.push(a)},_removeFromGraphics:function(a){this.view&&this.view.graphics.remove(a)},_error:function(a){return v(this.declaredClass,a)},_searchDeferred:function(a){var d=new p,c=this.searchTerm,b=this.activeSourceIndex;a&&a.hasOwnProperty("index")&&(b=a.index);this.clearGraphics();var e={magicKey:this.currentSuggestion?this.currentSuggestion.magicKey:
null,text:c};a?"string"===typeof a?(e.text=a,a=this._searchQueries(e)):a="object"===typeof a&&a.hasOwnProperty("magicKey")?this._searchQueries(a):"object"===typeof a&&a.hasOwnProperty("geometry")?this._searchQueries({geometry:a}):"object"===typeof a&&a.hasOwnProperty("_objectId")?this._searchQueries(a):"object"===typeof a&&"point"===a.type?this._searchQueries({point:a}):a instanceof Array&&2===a.length?this._searchQueries({latlon:a}):this._searchQueries(e):a=this._searchQueries(e);a.always(function(a){a=
this._formatResults(a,b,c);d.resolve(a)}.bind(this));return d.promise},_viewReady:function(){var a=new p;this._viewReadyPromise&&this._viewReadyPromise.cancel();var d=this.view;d?this._viewReadyPromise=d.always(function(){a.resolve()}):a.resolve();return a.promise},_suggestDeferred:function(a){var d=new p;this._deferredSuggestions.push(d);a||(a=this.searchTerm);var c=this.activeSourceIndex;this._suggestQueries({text:a}).always(function(b){var e;if(b)for(var f=0;f<b.length;f++)b[f]&&(e=!0);e?(b=this._formatResults(b,
c,a),d.resolve(b)):d.resolve()}.bind(this));return d.promise},_getDefaultSymbol:function(a){var d,c,b,e,f;if(e=this.get("view.map"))if(e=e.basemap)f=e.id;f||(f="topo");a&&(a.feature&&a.feature.geometry)&&(b=a.feature.geometry.type);if(b){if(a=J.getSchemes({theme:"default",basemap:f,geometryType:b}))c=a.primaryScheme;c&&(c.color&&c.hasOwnProperty("opacity")&&(c.color.a=c.opacity),d=c,a=c.color,c=c.size,d="point"===b?new N({color:a,size:null!==c?c:d.size,outline:{color:d.outline.color,width:d.outline.width}}):
"polyline"===b?new M({color:a,width:null!==c?c:d.width}):"polygon"===b?new L({color:a,outline:{color:d.outline.color,width:d.outline.width}}):void 0)}return d},_selectFirstResult:function(a,d){var c;this.autoSelect&&a&&(c=this._getFirstResult(a))&&this.select(c)},_getSourceResults:function(a,d){return a&&a[d]&&a[d].results},_getSourceIndexOfResult:function(a){var d=this.results;if(d)for(var c=0;c<d.length;c++){var b=d[c].sourceIndex,e=this._getSourceResults(d,c);if(e)for(var f=0;f<e.length;f++)if(e[f]===
a)return parseInt(b,10)}return null},_getFirstResult:function(a){if(a)for(var d=0;d<a.length;d++){var c=this._getSourceResults(a,d);if(c=c&&c[0])return c}return!1},_validField:function(a,d){return a.getField(d)},_validFields:function(a,d){return!a||!d?!1:d.every(function(c){return this._validField(a,c)},this)},_getCodedName:function(a,d){if(a&&a.length)for(var c=0,b=a.length;c<b;c++){var e=a[c];if(e.code===d)return e.name}},_getCodedValue:function(a,d,c){if(a&&a.length)for(var b=0,e=a.length;b<e;b++){var f=
a[b],h=f.name,l=d;c||(h=h.toLowerCase(),l=l.toLowerCase());if(h===l)return f.code}return!1},_whereClause:function(a,d,c,b){var e=null;if(a){var f="";R.test(d.url)&&this._containsNonLatinCharacter(a)&&(f="N");if(c&&c.length)for(var h=0,l=c.length;h<l;h++){var k="",g=a.replace(/\'/g,"''"),k=c[h],n=d.getField(k),q=n.domain;q&&"codedValue"===q.type&&(g=this._getCodedValue(q.codedValues,g,b));!1!==g&&(n=n.type,"string"===n||"date"===n?k=b?k+" \x3d "+f+"'"+g+"'":"UPPER("+k+") LIKE "+f+"'%"+g.toUpperCase()+
"%'":"small-integer"===n||"integer"===n||"single"===n||"double"===n?(g=parseFloat(g),k=isNaN(g)?!1:k+" \x3d "+g):k=k+" \x3d "+g,k&&(e=e?e+" or ":"",e+=k))}}return e},_suggest:function(a){a||(a={index:this.activeSourceIndex,text:this.searchTerm});var d=new p,c=a.index,b=this.sources.getItemAt(c),e=b.featureLayer,f=this.suggestionsEnabled;b.hasOwnProperty("suggestionsEnabled")&&(f=b.suggestionsEnabled);var h=0,l;a.hasOwnProperty("text")&&a.text&&(l=s.trim(a.text),h=a.text.length);a=b.minSuggestCharacters||
this.minSuggestCharacters;if(f&&l&&h>=a){var k="";b.prefix&&(k+=b.prefix);k+=l;b.suffix&&(k+=b.suffix);var g=this._defaultSR,g=this.get("view.spatialReference"),f={};if(b.locator){b.categories&&(f.categories=b.categories);b.locator.outSpatialReference=g;if(this.view&&(b.localSearchOptions&&b.localSearchOptions.hasOwnProperty("distance")&&b.localSearchOptions.hasOwnProperty("minScale"))&&(h=this.scale,!b.localSearchOptions.minScale||h&&h<=parseFloat(b.localSearchOptions.minScale)))f.location=this.view.extent.center,
f.distance=b.localSearchOptions.distance;f.text=k;b.withinViewEnabled&&this.get("view.extent")&&(f.searchExtent=this.view.extent);b.searchExtent&&(f.searchExtent=b.searchExtent);f.maxSuggestions=b.maxSuggestions||this.maxSuggestions;b.sourceCountry&&(f.countryCode=b.sourceCountry);b.countryCode&&(f.countryCode=b.countryCode);b.locator.suggestLocations(f).then(function(a){d.resolve(a)},function(a){a||(a=this._error("Locator suggestLocations could not be performed."));d.reject(a)}.bind(this))}else e?
this._loadLayer(e).then(function(){if(this._supportsPagination(e)){var a=this._getDisplayField(b),f=b.searchFields||[a],h=[];b.suggestionTemplate?b.suggestionTemplate.replace(/(?:\{([^}]+)\})/g,function(a,b){h.push(b)}):h.push(a);-1===P.indexOf(h,e.objectIdField)&&h.push(e.objectIdField);var a=this._validField(e,a),l=this._validFields(e,h),p=this._validFields(e,f);!a||!l||!p?d.reject(this._error("Invalid FeatureLayer field")):(a=e.createQueryParameters(),b.hasOwnProperty("suggestQueryParams")&&s.mixin(a,
b.suggestQueryParams),a.outSpatialReference=g,a.returnGeometry=!1,a.num=b.maxSuggestions||this.maxSuggestions,a.outFields=h,b.withinViewEnabled&&this.get("view.extent")&&(a.geometry=this.view.extent),b.searchExtent&&(a.geometry=b.searchExtent),(f=this._whereClause(k,e,f,!1))?(a.where=f,e.queryFeatures(a).then(function(a){var b;(a=a.features)&&(b=this._hydrateResults(a,c,!0));d.resolve(b)}.bind(this),function(a){a||(a=this._error("FeatureLayer queryFeatures errored with suggestions"));d.reject(a)}.bind(this))):
d.resolve())}else d.resolve()}.bind(this)):d.reject(this._error("Invalid source"))}else d.resolve();return d.promise},_loadLayer:function(a){var d=new p;a&&"not-loaded"===a.loadStatus?a.load().then(d.resolve,d.reject):d.resolve(a);return d.promise},_supportsPagination:function(a){return a&&a.get("advancedQueryCapabilities.supportsPagination")},_suggestQueries:function(a){var d=this.sources,c=this.activeSourceIndex,b=[];if("all"===c)for(c=0;c<d.length;c++)a.index=c,b.push(this._suggest(a));else a.index=
c,b.push(this._suggest(a));return z(b)},_searchQueries:function(a){a.hasOwnProperty("index")||(a.index=this.activeSourceIndex);var d=this.sources,c=[];if("all"===a.index)for(var b=0;b<d.length;b++)a.index=b,c.push(this._search(a));else c.push(this._search(a));return z(c)},_getPointFromGeometry:function(a){if(a&&a.type){var d=a.type;return"point"===d?a:"extent"===d?a.center:a.extent.center}},_search:function(a){a||(a={text:this.searchTerm,magicKey:null,geometry:null,point:null,index:this.activeSourceIndex,
latlon:null});var d,c=new p,b=a.index,e=this.sources.getItemAt(b),f;a.hasOwnProperty("text")&&a.text&&(f=s.trim(a.text));if(e){var h=e.featureLayer,l="";e.prefix&&!a.magicKey&&(l+=e.prefix);l+=f;e.suffix&&!a.magicKey&&(l+=e.suffix);var k=this._defaultSR,k=this.get("view.spatialReference");if(e.locator)if(a.hasOwnProperty("text")&&f){var g={};e.categories&&(g.categories=e.categories);k&&(e.locator.outSpatialReference=k);if(this.view&&e.localSearchOptions&&e.localSearchOptions.hasOwnProperty("distance")&&
e.localSearchOptions.hasOwnProperty("minScale")){var n=this.scale;if(!e.localSearchOptions.minScale||n&&n<=parseFloat(e.localSearchOptions.minScale))g.location=this.view.extent.center,g.distance=e.localSearchOptions.distance}g.address={};g.maxLocations=e.maxResults||this.maxResults;e.withinViewEnabled&&this.get("view.extent")&&(g.searchExtent=this.view.extent);e.searchExtent&&(g.searchExtent=e.searchExtent);e.sourceCountry&&(g.countryCode=e.sourceCountry);e.countryCode&&(g.countryCode=e.countryCode);
a.magicKey&&(g.magicKey=a.magicKey);e.singleLineFieldName?g.address[e.singleLineFieldName]=l:g.address["Single Line Input"]=l;e.outFields&&(g.outFields=e.outFields);e.locator.addressToLocations(g).then(function(a){a=this._hydrateResults(a,b,!1);c.resolve(a)}.bind(this),function(a){a||(a=this._error("Locator addressToLocations could not be performed"));c.reject(a)}.bind(this))}else a.geometry?(d=this._getPointFromGeometry(a.geometry.geometry))?this._reverseGeocodePoint(b,d).then(function(a){c.resolve(a)},
function(a){c.reject(a)}):c.reject(this._error("Invalid point to reverse geocode")):a.point?this._reverseGeocodePoint(b,a.point).then(function(a){c.resolve(a)},function(a){c.reject(a)}):a.latlon?(g=new x({longitude:a.latlon[0],latitude:a.latlon[1]}),this._reverseGeocodePoint(b,g).then(function(a){c.resolve(a)},function(a){c.reject(a)})):a.hasOwnProperty("text")&&!f?c.resolve([]):c.reject(this._error("Invalid query type for Locator"));else h?this._loadLayer(h).then(function(){var g=this._getDisplayField(e),
m=e.searchFields||[g],g=this._validField(h,g),n=this._validFields(h,m);if(!g||!n)c.reject(this._error("Invalid FeatureLayer field"));else{g=h.createQueryParameters();e.hasOwnProperty("searchQueryParams")&&s.mixin(g,e.searchQueryParams);if(k&&(g.outSpatialReference=k,n=B.getUnitValueForSR(k)))g.maxAllowableOffset=n;g.returnGeometry=!0;e.outFields&&(g.outFields=e.outFields);var p;a.hasOwnProperty("_objectId")||(this._supportsPagination(h)&&(g.num=e.maxResults||this.maxResults),e.withinViewEnabled&&
this.get("view.extent")&&(g.geometry=this.view.extent),e.searchExtent&&(g.geometry=e.searchExtent),p=e.exactMatch);a.hasOwnProperty("text")&&f?(m=this._whereClause(l,h,m,p))?(g.where=m,m=!0):m=!1:a.hasOwnProperty("_objectId")?(g.objectIds=[a._objectId],m=!0):a.geometry?(g.geometry=a.geometry,m=!0):a.point?(g.geometry=a.point,m=!0):a.latlon?(d=new x({longitude:a.latlon[0],latitude:a.latlon[1]}),g.geometry=d,m=!0):(a.hasOwnProperty("text")&&!f?c.resolve([]):c.reject(this._error("Invalid query type for FeatureLayer")),
m=!1);m?h.queryFeatures(g).then(function(a){a=a.features;var d;a&&(d=this._hydrateResults(a,b,!1));c.resolve(d)}.bind(this),function(a){a||(a=this._error("FeatureLayer queryFeatures could not be performed"));c.reject(a)}.bind(this)):c.resolve()}}.bind(this)):c.reject(this._error("Invalid source"))}else c.reject(this._error("Source is undefined"));return c.promise},_formatResults:function(a,d,c){c={activeSourceIndex:d,searchTerm:c,numResults:0,numErrors:0,errors:null,results:null};var b=this.sources,
e=[],f=[],h;if(a)if("all"===d)for(d=0;d<a.length;d++)a[d]||(a[d]=[]),h=b.getItemAt(d),a[d]instanceof v?(e.push({sourceIndex:d,source:h,error:a[d]}),c.numErrors++):(f.push({sourceIndex:d,source:h,results:a[d]}),c.numResults+=a[d].length);else a[0]||(a[0]=[]),h=b.getItemAt(d),a[0]instanceof v?(e.push({sourceIndex:d,source:h,error:a[0]}),c.numErrors++):(f.push({sourceIndex:d,source:h,results:a[0]}),c.numResults+=a[0].length);c.numErrors&&(c.errors=e);c.numResults&&(c.results=f);return c},_reverseGeocodePoint:function(a,
d){var c=new p,b=this.sources.getItemAt(a);if(d&&b){var e=b.locationToAddressDistance||this.locationToAddressDistance;b.locator.outSpatialReference=this._defaultSR;b.locator.outSpatialReference=this.get("view.spatialReference");b.locator.locationToAddress(d,e,function(b){b=this._hydrateResults([b],a,!1);c.resolve(b)}.bind(this),function(a){a||(a=this._error("Locator locationToAddress could not be performed"));c.reject(a)}.bind(this))}else c.reject(this._error("No point or source defined for reverse geocoding"));
return c.promise},_cancelDeferreds:function(){this._deferredSuggestions.forEach(function(a){a.cancel(this.declaredClass+" cancelling request")},this);this._deferredSuggestions.length=0},_getSourceName:function(a){return this._getName(a)||this._getName(a.featureLayer)||r.untitledSource},_getName:function(a){return a&&a.name},_getFirstStringField:function(a){if(a&&(a=a.fields)&&a.length)for(var d=0;d<a.length;d++){var c=a[d];if("string"===c.type)return c.name}return""},_getDisplayField:function(a){return a.displayField||
a.featureLayer.displayField||this._getFirstStringField(a.featureLayer)},_validExtent:function(a){return a&&a.xmin&&"NaN"!==a.xmin&&a.ymin&&"NaN"!==a.ymin&&a.xmax&&"NaN"!==a.xmax&&a.ymax&&"NaN"!==a.ymax},_hydrateResult:function(a,d,c){var b={},e=this._defaultSR,f;d=this.sources.getItemAt(d);var h=this.get("view.map"),e=this.get("view.spatialReference");if(a.hasOwnProperty("text")&&a.hasOwnProperty("magicKey"))return a;if(a instanceof y){if(b.feature=a.clone(),f=b.feature.geometry)f.spatialReference=
e}else if(a.hasOwnProperty("location")){var l=new x({x:a.location.x,y:a.location.y,spatialReference:e});f={};a.hasOwnProperty("attributes")&&(f=a.attributes);a.hasOwnProperty("score")&&(f.score=a.score);b.feature=new y({geometry:l,attributes:f})}else b.feature=null;if(a.hasOwnProperty("extent")&&this._validExtent(a.extent))b.extent=new A(a.extent),b.extent.spatialReference=e;else if(b.feature&&b.feature.geometry)switch(b.feature.geometry.type){case "extent":b.extent=b.feature.geometry;break;case "multipoint":b.extent=
b.feature.geometry.extent;break;case "polygon":b.extent=b.feature.geometry.extent;break;case "polyline":b.extent=b.feature.geometry.extent;break;case "point":h?(e=this.zoomScale,d&&d.zoomScale&&(e=d.zoomScale),b.extent=this.scale>e?B.getExtentForScale(this.view,e).clone().centerAt(b.feature.geometry):this.view.extent.clone().centerAt(b.feature.geometry)):b.extent=new A({xmin:b.feature.geometry.x-0.25,ymin:b.feature.geometry.y-0.25,xmax:b.feature.geometry.x+0.25,ymax:b.feature.geometry.y+0.25})}else b.extent=
null;d.featureLayer?d.suggestionTemplate&&c?b.name=w.substitute(a.attributes,d.suggestionTemplate):d.searchTemplate?b.name=w.substitute(a.attributes,d.searchTemplate):(c=this._getDisplayField(d),d=d.featureLayer.getField(c).domain,c&&(a.hasOwnProperty("attributes")&&a.attributes.hasOwnProperty(c))&&(a=a.attributes[c],b.name=d&&"codedValue"===d.type?this._getCodedName(d.codedValues,a):a)):a.address&&d.searchTemplate?b.name=w.substitute(a.address,d.searchTemplate):a.hasOwnProperty("name")?b.name=a.name:
a.hasOwnProperty("attributes")&&"object"===typeof a.attributes&&a.attributes.Match_addr?(b.name=a.attributes.Match_addr,a.attributes.Addr_type&&("POI"===a.attributes.Addr_type&&a.attributes.StAddr&&a.attributes.City)&&(b.name+=" - "+a.attributes.StAddr+", "+a.attributes.City)):a.hasOwnProperty("address")&&"string"===typeof a.address?b.name=a.address:a.hasOwnProperty("address")&&"object"===typeof a.address&&a.address.hasOwnProperty("Address")?b.name=a.address.Address:b.feature&&b.feature.geometry&&
(b.name=b.feature.geometry.x+","+b.feature.geometry.y);b.name||(b.name=r.untitledResult);return b},_hydrateResults:function(a,d,c){var b=[],e=a&&a.length;if(e)for(var f=0;f<e;f++){var h=this._hydrateResult(a[f],d,c);b.push(h)}return b},_containsNonLatinCharacter:function(a){for(var d=0;d<a.length;d++)if(255<a.charCodeAt(d))return!0;return!1},_setPlaceholder:function(a){var d="",c=this.sources.getItemAt(a);"all"===a?d=this.allPlaceholder||r.allPlaceholder:c&&c.placeholder&&(d=c.placeholder);this.placeholder=
d},_updateActiveSource:function(){var a=this.sources,d=this.activeSourceIndex;this.activeSource=a&&a.getItemAt(d)||null},_setDefaultActiveSourceIndex:function(){var a=this.sources;this.activeSourceIndex=a&&1===a.length||!this.searchAllEnabled?0:"all"}});t.ALL_INDEX="all";t.OBJECT_ID_FIELD="_objectId";return t});