// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["./support/ActiveLayerInfo","../../core/Accessor","../../core/Collection","../../core/HandleRegistry","../../core/watchUtils"],function(f,g,h,k,c){return g.createSubclass({properties:{activeLayerInfos:{type:h.ofType(f)},layerInfos:{},state:{dependsOn:["view.ready"],readOnly:!0},view:{}},declaredClass:"esri.widgets.Legend.LegendViewModel",constructor:function(){this._handles=new k;this._layerInfosByLayerViewId={};this._activeLayerInfosByLayerViewId={};var a=c.watch(this,"view",function(a){this._handles.remove("view-ready-watcher");
a&&this._handles.add(c.init(this,"state",function(d){this._handles.remove("allLayerViews-change");this._handles.remove("layerInfos-change");this._destroyViewActiveLayerInfos();this.activeLayerInfos.removeAll();"ready"===d&&this._updateActiveLayerInfos(a.allLayerViews)}.bind(this)),"view-ready-watcher")}.bind(this));this._handles.add(a,"view-watcher")},getDefaults:function(){return{activeLayerInfos:[]}},destroy:function(){this._destroyViewActiveLayerInfos();this._handles.destroy();this._handles=null},
activeLayerInfos:null,layerInfos:null,state:"disabled",_stateGetter:function(){return this.get("view.ready")?"ready":"disabled"},view:null,_destroyViewActiveLayerInfos:function(){Object.keys(this._activeLayerInfosByLayerViewId).forEach(this._destroyViewActiveLayerInfo,this)},_destroyViewActiveLayerInfo:function(a){this._handles.remove(a);var b=this._activeLayerInfosByLayerViewId[a];b&&(b.tearingDown=!0,delete this._activeLayerInfosByLayerViewId[a])},_updateActiveLayerInfos:function(a){a.length&&this._refresh();
this._handles.add(a.on("change",function(a){a.removed.forEach(function(a){this._destroyViewActiveLayerInfo(a.id)},this);this._refresh()}.bind(this)),"allLayerViews-change");this._handles.add(c.watch(this,"layerInfos",function(){this._destroyViewActiveLayerInfos();this._refresh()}.bind(this)),"layerInfos-change")},_refresh:function(){var a=this.layerInfos;this._layerInfosByLayerViewId={};this.activeLayerInfos.removeAll();this.view.allLayerViews.filter(function(b){var d=b.layer.uid;return a&&a.length?
a.some(function(a){return a.layer&&(this._hasLayerUID(a.layer.layers,d)||a.layer.uid===d)?(this._layerInfosByLayerViewId[b.uid]=a,!0):!1},this):!0},this).filter(this._isLayerViewSupported,this).forEach(this._generateActiveLayerInfo,this)},_hasLayerUID:function(a,b){return!a?!1:a.some(function(a){return this._hasLayerUID(a.layers,b)||a.uid===b},this)},_generateActiveLayerInfo:function(a){var b=a.layer,d=a.id,c=this._layerInfosByLayerViewId[d],e=this._activeLayerInfosByLayerViewId[d];e||(e=new f({layer:b,
title:c&&c.title||b.title}),this._buildActiveLayerInfo(e,a),this._activeLayerInfosByLayerViewId[d]=e);this._isLayerActive(b,a)&&e&&this.activeLayerInfos.add(e)},_isLayerViewSupported:function(a){a=a.layer.declaredClass;return"esri.layers.FeatureLayer"===a||"esri.layers.StreamLayer"===a},_buildActiveLayerInfo:function(a,b){var d=b.layer,l=d.renderer,e=b.id,f=c.watch(d,"renderer, opacity",function(){a.ready=!1}),g=c.whenFalse(a,"ready",function(b,c){c&&(a.legendElements=[],l=d.renderer);l&&a.buildLegendElements(l,
this.view.scale);a.ready=!0}.bind(this)),h=c.watch(d,"legendEnabled",function(c){c?this._isLayerActive(d,b)&&this.activeLayerInfos.add(a):this.activeLayerInfos.remove(a)}.bind(this)),k=c.watch(b,"suspended",function(c){c?this.activeLayerInfos.remove(a):this._isLayerActive(d,b)&&this.activeLayerInfos.add(a)}.bind(this));this._handles.add([f,g,h,k],e)},_isLayerActive:function(a,b){return!b.suspended&&a.legendEnabled}})});