// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports","dojo/_base/lang","./I3SUtil"],function(u,k,m,l){function t(f,b,d){for(var c="",a=0,g=0,e=0,h=0;a<d;)if(g=f[b+a],128>g)c+=String.fromCharCode(g),a++;else if(191<g&&224>g){if(a+1>=d)throw Error("UTF-8 Decode failed. Two byte character was truncated.");e=f[b+a+1];c+=String.fromCharCode((g&31)<<6|e&63);a+=2}else{if(a+2>=d)throw Error("UTF-8 Decode failed. Multi byte character was truncated.");e=f[b+a+1];h=f[b+a+2];c+=String.fromCharCode((g&15)<<12|(e&63)<<6|h&63);a+=3}return c}
function n(f,b){for(var d={byteOffset:0,byteCount:0,fields:Object.create(null)},c=0,a=0;a<b.length;a++){var g=b[a],e=new l.valueType2TypedArrayClassMap[g.valueType||g.type](f,c,1);d.fields[g.property]=e[0];c+=e.byteLength}d.byteCount=c;return d}function q(f,b,d){var c=[],a,g=0,e;for(e=0;e<f;e+=1){a=b[e];if(0<a){if(c.push(t(d,g,a-1)),0!==d[g+a-1])throw Error("invalid string array: missing null termination.");}else c.push(null);g+=a}return c}function p(f,b){return new l.valueType2TypedArrayClassMap[b.valueType](f,
b.byteOffset,b.count*b.valuesPerElement)}function r(f,b){return new Uint8Array(f,b.byteOffset,b.byteCount)}function s(f,b){for(var d=n(f,b.header),c={header:d,byteOffset:d.byteCount,byteCount:0,entries:Object.create(null)},a=d.byteCount,g=0;g<b.ordering.length;g++){var e=b.ordering[g],h=m.clone(b[e]);h.count=d.fields.count;if("String"===h.valueType){if(h.byteOffset=a,h.byteCount=d.fields[e+"ByteCount"],"UTF-8"!==h.encoding)throw Error("Unsupported String encoding: '"+h.encoding+"'.");}else if(l.isValueType(h.valueType)){var k=
l.getBytesPerValue(h.valueType),a=a+(0!==a%k?k-a%k:0);h.byteOffset=a;h.byteCount=k*h.valuesPerElement*h.count}else throw Error("Unsupported valueType: '"+h.valueType+"'.");a+=h.byteCount;c.entries[e]=h}c.byteCount=a-c.byteOffset;return c}k.readHeader=n;k.readStringArray=q;k.createTypedView=p;k.createRawView=r;k.createAttributeDataIndex=s;k.createGeometryDataIndex=function(f,b,d){var c=n(f,b.header),a=c.byteCount,g={header:c,byteOffset:c.byteCount,byteCount:0,vertexAttributes:m.clone(b.vertexAttributes)},
e=g.vertexAttributes;!d&&null!=e.region&&delete e.region;for(d=0;d<b.ordering.length;d++){var h=b.ordering[d];null!=e[h]&&(e[h].byteOffset=a,e[h].count=c.fields.vertexCount,a+=l.getBytesPerValue(e[h].valueType)*e[h].valuesPerElement*c.fields.vertexCount)}if(b.faces){g.faces=m.clone(b.faces);e=g.faces;for(d=0;d<b.ordering.length;d++)name=b.ordering[d],e[name].byteOffset=a,e[name].count=c.fields.vertexCount;a+=l.getBytesPerValue(e[name].valueType)*e[name].valuesPerElement*c.fields.vertexCount}if(b.featureAttributes&&
b.featureAttributeOrder&&c.fields.featureCount){g.featureAttributes=m.clone(b.featureAttributes);e=g.featureAttributes;for(d=0;d<b.featureAttributeOrder.length;d++)name=b.featureAttributeOrder[d],e[name].byteOffset=a,e[name].count=c.fields.featureCount,h=l.getBytesPerValue(e[name].valueType),"UInt64"===e[name].valueType&&(h=8),a+=h*e[name].valuesPerElement*c.fields.featureCount}if(f.byteLength<a)throw Error("Invalid geometry size ( expected: "+a+", actual: "+f.byteLength+")");f.byteLength>a&&console.warn("Invalid geometry size ( expected: "+
a+", actual: "+f.byteLength+")");g.byteCount=a-g.byteOffset;return g};k.readBinaryAttribute=function(f,b){f["attributeByteCounts "]&&!f.attributeByteCounts&&(console.error("Warning: Trailing space in 'attributeByteCounts '."),f.attributeByteCounts=f["attributeByteCounts "]);"ObjectIds"===f.ordering[0]&&f.hasOwnProperty("objectIds")&&(console.error("Warning: Case error in objectIds"),f.ordering[0]="objectIds");var d=s(b,f),c=d.byteOffset+d.byteCount;if(c>b.byteLength)throw Error("invalid attribute array length\n(expected: "+
c+" bytes, got: "+b.byteLength+" bytes).");c<b.byteLength&&console.error("Warning: attribute array too long\n(expected: "+c+" bytes, got: "+b.byteLength+" bytes).");if(c=d.entries.attributeValues||d.entries.objectIds){if("String"===c.valueType){var d=d.entries.attributeByteCounts,a=p(b,d),c=r(b,c);return q(d.count,a,c)}return p(b,c)}throw Error("Bad attributeStorageInfo specification.");}});