// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../../core/declare dojo/_base/lang ../../support/PromiseLightweight ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Util ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/materials/Material ../../webgl-engine/lib/Texture".split(" "),function(G,H,r,I,z,J,K,L,M,N){var O=I.mat4d,w=J.assert;return G(null,{constructor:function(c){this.streamDataSupplier=c},destroy:function(){},fetchSymbol:function(c,d){d=d||{};var f=new r.Promise;this.streamDataSupplier.request(c,
"json").then(function(c,m){var b=this._createStageResources(m,d);f.done(b)}.bind(this),function(){f.reject()});return f},_gatherExternalTextures:function(c){for(var d in c.textureDefinitions)for(var f=c.textureDefinitions[d],k=0;k<f.images.length;k++)"href"in f.images[k]&&console.warn("External image resources not yet supported");return{}},_extractTextureImageFromBin:function(c,d){var f=new r.Promise,k=new Uint8Array(c,d.byteOffset,d.length),k=new Blob([k],{type:d.encoding}),m=window.URL.createObjectURL(k),
b=new Image;b.onerror=function(){window.URL.revokeObjectURL(m);f.reject();b.url="";b.onerror=void 0;b.onload=void 0};b.onload=function(){window.URL.revokeObjectURL(m);d.img=b;f.done();b.url="";b.onerror=void 0;b.onload=void 0};b.src=m;return f},_createStageResources:function(c,d){var f=[],k=[],m=[],b=[],r=[],B=[],A="meshsymbol_"+c.model.name,s=c.textureDefinitions,C={},t;for(t in s){var n=s[t],g=n.images[0].data;w(g,"symbol resources must have embedded texture data (at the moment)");var h="/textureDefinitions/"+
t,g=new N(n.encoding+";base64,"+g,A,{noUnpackFlip:!0});r.push(g);C[h]={engineTexObj:g,transparent:"rgba"===n.channels}}s=c.model.geometries;t=c.materialDefinitions;for(n=0;n<s.length;n++){h=s[n];h.params.components||this._createSingleComponent(h);var g=h.params.components,p=g.length,x=h.params.faces,u=h.params.vertexAttributes,e=h.params.topology||"Indexed",v={},l;for(l in u){var a=u[l];w(a.values,"symbol resources with external geometry bin not yet supported");v[l]={data:a.values,size:a.valuesPerElement}}var D,
u=Array(p);if("Indexed"===e)for(l in D=x.componentIndices,x);else"PerAttributeArray"!==e?console.warn("I3S symbol loader: unsupported topology type "+e):1!==p&&console.warn("I3S symbol loader: if topology is not Indexed, only single component geometries are supported");m.push([]);for(p=0;p<g.length;p++){e=g[p];a={type:"triangle",positionKey:"position",indices:{}};if(D)for(l in x){if("componentIndices"!==l){var q=x[l];w(q.values,"symbol resources with external geometry bin not yet supported");a.indices[l]=
new Uint32Array(q.values)}}else{for(var q=v.position.data.length/v.position.size,E=new Uint32Array(q),y=0;y<q;y++)E[y]=y;q=E;for(l in v)a.indices[l]=q}u[p]=a;var F;e.texture&&(F=C[e.texture].engineTexObj.getId());a=b[e.material]?b[e.material][e.texture]:null;a||(a=e.material.substring(e.material.lastIndexOf("/")+1),a=t[a].params,1===a.transparency&&(a.transparency=0),a={ambient:a.diffuse,diffuse:a.diffuse,specular:a.specular,shininess:a.shininess,opacity:1-a.transparency,textureId:F,doubleSided:!0,
cullFace:"none",flipV:!1},a.transparent=1>a.opacity,d.materialParamsMixin&&H.mixin(a,d.materialParamsMixin),a=new M(a,A),b[e.material]||(b[e.material]={}),b[e.material][e.texture]=a,k.push(a));m[n].push(a)}g=new K(new L(u,v),A);h=O.create(h.transformation);f.push(g);B.push(h)}b={stageResources:{}};b.stageResources[z.ModelContentType.TEXTURE]=r;b.stageResources[z.ModelContentType.MATERIAL]=k;b.stageResources[z.ModelContentType.GEOMETRY]=f;b.geometryTransformations=B;b.materialsByComponent=m;b.pivotOffset=
c.model.pivotOffset;return b},_createSingleComponent:function(c){var d=c.params;w(d.material);d.components=[{id:1,material:c.params.material,texture:c.params.texture,region:c.params.texture}];d.faces&&(d.faces.componentIndices=[d.faces.position.count])}})});