// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../lib/glMatrix ../../support/earthUtils ../../support/projectionUtils ../../../../core/urlUtils ../../../../core/requireUtils ../../../../core/promiseUtils dojo/_base/lang dojo/promise/all ../../../../request ../../webgl-engine/Stage ../../webgl-engine/materials/Material ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/Layer ../../webgl-engine/lib/BufferVectorMath ../../webgl-engine/lib/Util ./I3SBinaryReader".split(" "),
function(K,f,v,x,u,y,L,t,M,N,O,g,r,z,A,B,P,Q,R,S){function C(a,h){return y.isAbsoluteUrl(h)?h:y.join(a,h)}function D(a,h,c){void 0===c&&(c=["*"]);return a?L.when(K,["../../../../tasks/support/Query","../../../../tasks/QueryTask"]).then(function(b){var k=b[1];b=new b[0]({objectIds:[h],outFields:c});return(new k(a.parsedUrl.path)).execute(b)}).then(function(a){return a&&a.features&&0<a.features.length?a.features[0].attributes:t.reject(Error("Feature not found in companion feature layer."))}):t.reject(Error("Companion feature layer not present."))}
function E(a,h,c,b){void 0===b&&(b=["*"]);var k=b.some(function(a){return"*"===a});return N(h.attributeData.map(function(c,e){if(!k&&!b.some(function(c){return a[e].name===c}))return t.resolve(null);var d=C(h.baseUrl,c.href);return O(d,{responseType:"array-buffer"}).then(function(c){return S.readBinaryAttribute(a[e],c.data)}).otherwise(function(){return null})})).then(function(b){for(var e={},d=0;d<b.length;d++)null!=b[d]&&(e[a[d].name]=b[d][c]);return e})}function F(a){return f.valueType2TypedArrayClassMap.hasOwnProperty(a)}
var G=v.vec4d,q=v.vec3d,s=v.mat4d,H=R.assert,m=q.create(),I=q.create(),J=G.create();f.DDS_ENCODING_STRING="image/vnd-ms.dds";f.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS=["image/jpeg","image/png"];f.addTrailingSlash=function(a){"/"!==a[a.length-1]&&(a+="/");return a};f.concatUrl=C;f.extractWkid=function(a){return a&&parseInt(a.substring(a.lastIndexOf("/")+1,a.length),10)};f.getAppropriateTextureEncoding=function(a,h){if(Array.isArray(a)){if(h){var c=a.indexOf(f.DDS_ENCODING_STRING);if(-1<c)return c}for(c=
0;c<a.length;c++)if(-1<f.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS.indexOf(a[c]))return c;throw Error("Could not find appropriate texture encoding (among "+a.toString()+")");}return-1};f.findIntersectingNodes=function(a,h,c,b,k,f){if(null!=c&&(u.mbsToMbs(c.mbs,b,J,h),0!==this.intersectBoundingBoxWithMbs(a,J))){f.push(c);for(var e=null!=c.children?c.children.length:0,d=0;d<e;d++)this.findIntersectingNodes(a,h,k[c.children[d].id],b,k,f)}};f.intersectBoundingBoxWithMbs=function(a,h){var c=h[0],b=h[1],
k=h[2],f=h[3],e=0;if(c<a[0])var d=a[0]-c,e=e+d*d;b<a[1]&&(d=a[1]-b,e+=d*d);k<a[2]&&(d=a[2]-k,e+=d*d);c>a[3]&&(d=c-a[3],e+=d*d);b>a[4]&&(d=b-a[4],e+=d*d);k>a[5]&&(d=k-a[5],e+=d*d);if(e>f*f)return 0;if(0<e)return 1;e=Infinity;c-a[0]<e&&(e=c-a[0]);b-a[1]<e&&(e=b-a[1]);k-a[2]<e&&(e=k-a[2]);a[3]-c<e&&(e=a[3]-c);a[4]-b<e&&(e=a[4]-b);a[5]-k<e&&(e=a[5]-k);return e>f?2:1};f.recomputeNormals=function(a,h){for(var c=Q.Vec3Compact.subtract,b=a.map(function(a){return a.indices.position.length/3}).reduce(function(a,
c){return a+c}),b=new Float32Array(3*b),f=h.position.data,g=0,e=0;e<a.length;e++){for(var d=a[e].indices.position,n=new Uint32Array(d.length),l=0;l<d.length;l+=3){c(f,3*d[l],f,3*d[l+1],I,0);c(f,3*d[l],f,3*d[l+2],m,0);q.cross(m,I);q.normalize(m);var w=g/3;b[g++]=m[0];b[g++]=m[1];b[g++]=m[2];n[l]=w;n[l+1]=w;n[l+2]=w}a[e].indices.normal=n}h.normal.data=b};f.makeNodeDebugVisualizer=function(a,f,c){function b(a){return{ambient:a,diffuse:[0,0,0],transparent:!0,opacity:0.5,blendModeOneOne:!1}}var k=new z(A.createCylinderGeometry(1,
1,64,[0,0,1],[0,0,0],!1),"debugCylinder"),m=new z(A.createSphereGeometry(1),"debugSphere"),e={red:new r(b([0.8,0,0]),"debugMaterialRed"),grey:new r(b([0.4,0.4,0.4]),"debugMaterialGrey"),brown:new r(b([0.2,0.1,0]),"debugMaterialBrown"),green:new r(b([0,0.8,0]),"debugMaterialGreen"),blue:new r(b([0,0,0.8]),"debugMaterialBlue"),yellow:new r(b([0.8,0.8,0]),"debugMaterialYellow"),magenta:new r(b([0.8,0,0.8]),"debugMaterialMagenta")},d;for(d in e)a.add(g.ModelContentType.MATERIAL,e[d]);a.add(g.ModelContentType.GEOMETRY,
k);c=new P(c+"_debug",{interaction:"IGNORED"},c+"_debug");a.add(g.ModelContentType.LAYER,c);a.addToViewContent([c.getId()]);var n=q.create(),l=s.create();return{engineLayer:c,added:{},show:function(a,c,b){var d=a.computedMbs;d||(d=G.create(),u.mbsToMbs(a.mbs,c,d,f.spatialReference));var g="node"+a.id+"dbg";q.set(d,n);var p=d[3];if(p>x.earthRadius/10&&f.spatialReference===u.SphericalRenderSpatialReference){this.showWS(n,Math.max(0.01*p,1E4),b,g+"_center");var d=q.length(n),m=x.earthRadius;m+p>d&&(p=
(d*d+m*m-p*p)/(2*d),q.scale(n,p/d),p=Math.sqrt(m*m-p*p))}s.identity(l);s.scale(l,[p,p,0.05*p]);b=e[b];H(b);b=new B({name:g,geometries:[k],materials:[[b]],transformations:[l],castShadow:!1,idHint:g});u.computeLinearTransformation(c,a.mbs,l,f.spatialReference);null!=n&&(l[12]=n[0],l[13]=n[1],l[14]=n[2]);b.setObjectTransformation(l);this._addToStage(b,g)},showWS:function(a,b,c,d){var f=s.identity();s.scale(f,[b,b,b]);b=e[c];H(b);f=new B({name:d,geometries:[m],materials:[[b]],transformations:[f],castShadow:!1,
idHint:d});b=s.identity();s.translate(b,a);f.setObjectTransformation(b);this._addToStage(f,d)},_addToStage:function(b,c){a.add(g.ModelContentType.OBJECT,b);this.engineLayer.addObject(b);var d=this.added[c];void 0!==d&&(a.remove(g.ModelContentType.OBJECT,d.getId()),this.engineLayer.removeObject(d));this.added[c]=b},clear:function(){for(var b in this.added){var c=this.added[b];a.remove(g.ModelContentType.OBJECT,c.getId());this.engineLayer.removeObject(c)}this.added={}},dispose:function(){this.clear();
for(var b in e)a.remove(g.ModelContentType.MATERIAL,e[b].getId());a.remove(g.ModelContentType.GEOMETRY,k.getId());a.remove(g.ModelContentType.LAYER,this.engineLayer.getId())}}};f.postData=function(a,f,c){var b=new XMLHttpRequest;b.open("PUT","/put.php"+a,!0);b.setRequestHeader("Content-type",c);b.send(f)};f.whenGraphicAttributes=function(a,f,c,b,k){b=b.filter(function(a){return!f.attributes.hasOwnProperty(a)});if(0===b.length)return t.resolve(f);var g=function(a){M.mixin(f.attributes,a);return f},
e=a.companionFeatureLayer;a=a.attributeStorageInfo;return e?D(e,c,b).then(g):a&&(c=k(),null!=c)?E(a,c.node,c.index,b).then(g):t.reject()};f.queryAttributesFromFeatureLayer=D;f.queryAttributesFromCachedAttributes=E;f.valueType2TypedArrayClassMap={Float32:Float32Array,Float64:Float64Array,UInt8:Uint8Array,Int8:Int8Array,UInt16:Uint16Array,Int16:Int16Array,UInt32:Uint32Array,Int32:Int32Array};f.isValueType=F;f.getBytesPerValue=function(a){return F(a)&&f.valueType2TypedArrayClassMap[a].BYTES_PER_ELEMENT}});