// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["../../core/declare","dojo/_base/lang","dojo/_base/array"],function(h,f,g){var k=h(null,{constructor:function(){this._requestIds={};this._queue=[]},add:function(a,b){this.contains(a)||(this._requestIds[a]=b,this._queue.push(b))},contains:function(a){return null!=this._requestIds[a]},get:function(a){for(var b=[],c;!this.isEmpty()&&b.length<a;)c=this._queue.pop(),delete this._requestIds[c.id],b.push(c);return b},remove:function(a){if(!this.contains(a))return null;var b=this._requestIds[a];this._queue.splice(g.indexOf(this._queue,
b),1);delete this._requestIds[a];return b},isEmpty:function(){return 0===this._queue.length}}),e=h(null,{constructor:function(a){a=f.mixin({loaders:{},contentType:"img",activeRequests:{},numActiveRequests:0,maxActiveRequests:10},a||{});f.mixin(this,a);this._requestLoadHandler=this._requestLoadHandler.bind(this);this._requestErrorHandler=this._requestErrorHandler.bind(this);this.queue||(this.queue=new k)},paused:!1,pause:function(){this.paused=!0},resume:function(){this.paused=!1;this._next()},load:function(a){var b=
a.id;!this.activeRequests[b]&&!this.queue.contains(b)&&(this.queue.add(b,a),this._next());return b},cancel:function(a){this.queue.contains(a)?(a=this.queue.remove(a),this._requestErrorHandler({request:a,canceled:!0})):this.activeRequests[a]&&this.activeRequests[a].cancel()},dispose:function(a){var b=this.getLoader(a.contentType||this.contentType);b&&b.dispose&&b.dispose(a.data)},registerLoader:function(a,b){f.isArray(a)?g.forEach(a,function(a){this.registerLoader(a,b)}):this.loaders[a.toLowerCase()]=
b},getLoader:function(a){a=a.toLowerCase();var b=e.getLoader(a);a=this.loaders[a];return!a&&!b?null:a||b},_next:function(){this.paused||(this.queue.isEmpty()?0===this.numActiveRequests&&(this.running=!1):this.numActiveRequests<this.maxActiveRequests&&this._loadRequests(this.queue.get(this.maxActiveRequests-this.numActiveRequests)))},_loadRequests:function(a){var b,c,d=a.length;for(c=0;c<d;c++)b=a[c],this._loadRequest(b)},_loadRequest:function(a){var b=a.contentType||this.contentType,c=this.getLoader(b);
this.numActiveRequests++;b?c?(b=c.load(a,this._requestLoadHandler,this._requestErrorHandler))&&(this.activeRequests[a.id]=b):(a.error="No loader for contentType:"+b,this._requestErrorHandler({request:a})):(a.error="contentType not set",this._requestErrorHandler({request:a}))},_requestLoadHandler:function(a){this.numActiveRequests--;this.activeRequests[a.request.id]&&delete this.activeRequests[a.request.id];a.canceled?a.request.errorCallback.call(this,a):a.request.loadCallback.call(this,a);this._next()},
_requestErrorHandler:function(a){this.activeRequests[a.request.id]&&(this.numActiveRequests--,delete this.activeRequests[a.request.id]);a.request.errorCallback.call(null,a);this._next()}});e.loaders={};e.registerLoader=function(a,b){f.isArray(a)?g.forEach(a,function(a){e.registerLoader(a,b)}):e.loaders[a.toLowerCase()]=b};e.getLoader=function(a){a=a.toLowerCase();return void 0===e.loaders[a]?void 0:e.loaders[a]};e.registerLoader("img",{load:function(a,b,c){var d=document.createElement("img");d.setAttribute("alt",
"");d.onload=function(c){d.onload=d.onerror=null;c.canceled||b.call(this,{request:a,data:d})};d.onerror=function(b){d.onload=d.onerror=null;c.call(this,{request:a,error:b})};d.src=a.url;return{cancel:function(){d.onload=d.onerror=null;c.call(this,{request:a,canceled:!0})}}}});return e});