// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("./math/common ./math/mat2d ./math/vec2 ../../Viewpoint ../../core/promiseUtils ../../geometry/SpatialReference ../../geometry/Geometry ../../geometry/Point ../../geometry/Extent ../../geometry/support/webMercatorUtils ../../geometry/support/scaleUtils".split(" "),function(n,k,e,A,Q,R,B,u,S,C,D){var E=6370997*Math.PI/180,T=180/Math.PI,F=function(a,b,c,d){return d&&(c&&!d.equals(c)&&d._canProject(c))&&d.isWebMercator?(d.isWebMercator?(c=b[1],89.99999<c?c=89.99999:-89.99999>c&&(c=-89.99999),
c=Math.sin(n.toRadian(c)),a=e.set(a,6378137*n.toRadian(b[0]),3189068.5*Math.log((1+c)/(1-c)))):(c=n.toDegree(b[0]/6378137),a=e.set(a,c-360*Math.floor((c+180)/360),n.toDegree(0.5*Math.PI-2*Math.atan(Math.exp(-1*b[1]/6378137))))),a):e.copy(a,b)},s=function(a){return a.wkid?a:a.spatialReference||R.WGS84},q=function(a,b){return b.type?e.set(a,b.x,b.y):e.copy(a,b)},v=function(a,b){return Math.max(a.width/b[0],a.height/b[1])*G(a.spatialReference)},r=function(a,b,c){var d;if(!a)return null;if(Array.isArray(a)&&
2===a.length&&"number"===typeof a[0]&&"number"===typeof a[1])return new u(a);if(a.forEach)return a.reduce(function(a,c){return r(c,b,a)},c);if(Array.isArray(a)){for(d=0;d<a.length;d++)if(c=r(a[d],b,c),!c)return null;return c}a instanceof B?d=a:a.geometry&&(d=a.geometry);if(!d)return null;a="point"===d.type?new S({xmin:d.x,ymin:d.y,xmax:d.x,ymax:d.y,spatialReference:d.spatialReference}):d.extent;if(!a||!C.canProject(a.spatialReference,b))return null;a=C.project(a,b);return c=c?c.union(a):a.clone()},
H=function(a,b){if(!a)return new A({targetGeometry:new u,scale:0,rotation:0});var c=b.spatialReference,d=b.size,g=b.currentViewpoint,f=b.constraints,h=null;"esri.Viewpoint"===a.declaredClass?h=a:a.viewpoint?h=a.viewpoint:a.target&&"esri.Viewpoint"===a.target.declaredClass&&(h=a.target);var k=null,l=null;if(h&&h.targetGeometry)l=h.targetGeometry;else if(a instanceof B)l=a;else if(a||a&&(a.hasOwnProperty("center")||a.hasOwnProperty("extent")||a.hasOwnProperty("target")))l=r(a.center,c)||r(a.extent,
c)||r(a.target,c)||r(a,c);!l&&g&&g.targetGeometry?l=g.targetGeometry:!l&&b.extent&&(l=b.extent);var m=s(l);c||(c=s(b.spatialReference||b.extent||l));k=l.center?l.center:l;k=q(e.create(),k);k=new u(F(k,k,m,c),c);c=null;c=h&&h.targetGeometry&&"point"===h.targetGeometry.type?h.scale:a.hasOwnProperty("scale")?a.scale:a.hasOwnProperty("zoom")&&f&&f.effectiveLODs?f.zoomToScale(a.zoom):Array.isArray(l)||"point"===l.type||"extent"===l.type&&0===l.width&&0===l.height?b.extent?v(b.extent,d):g.scale:v(l.extent,
d);d=0;h?d=h.rotation:a.hasOwnProperty("rotation")?d=a.rotation:g&&(d=g.rotation);f&&(f.rotationEnabled||(d=0),f.snapToZoom&&(c=f.snapScale(c)),0!==f.effectiveMinScale&&(c=Math.min(f.effectiveMinScale,c)),0!==f.effectiveMaxScale&&(c=Math.max(f.effectiveMaxScale,c)));return new A({targetGeometry:k,scale:c,rotation:d})},m=function(a,b){var c=a.targetGeometry,d=b.targetGeometry;c.x=d.x;c.y=d.y;c.spatialReference=d.spatialReference;a.scale=b.scale;a.rotation=b.rotation;return a},I=function(a,b,c){if(!c)return e.scale(a,
b,0.5);e.set(a,0.5*(b[0]-c.right+c.left),0.5*(b[1]-c.bottom+c.top));return a},U=function(){var a=e.create();return function(b,c,d){var e=c.targetGeometry;q(a,e);c=0.5*p(c);b.xmin=a[0]-c*d[0];b.ymin=a[1]-c*d[1];b.xmax=a[0]+c*d[0];b.ymax=a[1]+c*d[1];b.spatialReference=e.spatialReference;return b}}(),J=function(a,b,c){a=w(a,b,c);return k.invert(a,a)},V=function(){var a=e.create(),b=e.create();return function(c,d,e){q(a,d.targetGeometry);K(b,d,e);e=0.5*p(d);c.set({xmin:a[0]-e*b[0],ymin:a[1]-e*b[1],xmax:a[0]+
e*b[0],ymax:a[1]+e*b[1],spatialReference:d.targetGeometry.spatialReference});return c}}(),K=function(a,b,c){var d=n.toRadian(b.rotation)||0;b=Math.abs(Math.cos(d));d=Math.abs(Math.sin(d));return e.set(a,Math.round(c[1]*d+c[0]*b),Math.round(c[1]*b+c[0]*d))},M=function(){var a=e.create();return function(b,c,d){return e.sub(b,L(b,c),I(a,c,d))}}(),x=function(){var a=k.create(),b=e.create();return function(c,d,g,f){var h=p(d);d=n.toRadian(d.rotation)||0;e.set(b,h,h);k.fromScaling(a,b);k.rotate(a,a,d);
k.translate(a,a,M(b,g,f));k.translate(a,a,[0,f.top-f.bottom]);e.set(c,a[4],a[5]);return c}}(),p=function(a){return a.scale*N(a.targetGeometry.spatialReference)},N=function(a){return 1/(96*39.37*(D.getUnitValueForSR(a)||E))},G=function(a){return 96*39.37*(D.getUnitValueForSR(a)||E)},L=function(a,b){return e.scale(a,b,0.5)},O=function(){var a=e.create(),b=e.create(),c=e.create();return function(d,g,f,h,m){e.negate(a,g);e.scale(b,f,0.5);e.set(c,1/h,-1/h);k.identity(d);k.translate(d,d,b);m&&k.rotate(d,
d,m);k.scale(d,d,c);k.translate(d,d,a);return d}}(),w=function(){var a=e.create();return function(b,c,d){var e=p(c),f=n.toRadian(c.rotation)||0;q(a,c.targetGeometry);return O(b,a,d,e,f)}}(),W=function(){var a=e.create();return function(b,c,d){var e=p(c);q(a,c.targetGeometry);return O(b,a,d,e,0)}}(),X=function(){var a=e.create(),b=e.create(),c=e.create();return function(d,g,f){e.subtract(a,d,g);e.normalize(a,a);e.subtract(b,d,f);e.normalize(b,b);e.cross(c,a,b);d=Math.acos(e.dot(a,b)/(e.length(a)*e.length(b)))*
T;0>c[2]&&(d=-d);isNaN(d)&&(d=0);return d}}(),Y=function(){var a=e.create();return function(b,c,d,e){var f=b.targetGeometry;m(b,c);x(a,c,d,e);f.x+=a[0];f.y+=a[1];return b}}(),Z=function(){var a=e.create();return function(b,c,d,e){var f=b.targetGeometry;m(b,c);x(a,c,d,e);f.x-=a[0];f.y-=a[1];return b}}(),P=function(){var a=e.create();return function(b,c,d){m(b,c);c=b.targetGeometry;var e=s(d),f=s(c);q(a,d);F(a,a,e,f);c.x=a[0];c.y=a[1];return b}}(),$=function(){var a=e.create();return function(b,c,d,
g,f){f||(f="center");e.sub(a,d,g);e.scale(a,a,0.5);d=a[0];g=a[1];switch(f){case "center":e.set(a,0,0);break;case "left":e.set(a,-d,0);break;case "top":e.set(a,0,g);break;case "right":e.set(a,d,0);break;case "bottom":e.set(a,0,-g);break;case "top-left":e.set(a,-d,g);break;case "bottom-left":e.set(a,-d,-g);break;case "top-right":e.set(a,d,g);break;case "bottom-right":e.set(a,d,-g)}t(b,c,a);return b}}(),aa=function(){var a=e.create();return function(b,c,d,g,f){m(b,c);0!==d&&(y(a,g,c,f),b.scale=c.scale/
d,z(a,a,b,f),t(b,b,e.set(a,a[0]-g[0],g[1]-a[1])));return b}}(),ba=function(){var a=e.create();return function(b,c,d,g,f,h){m(b,c);0!==d&&(y(a,f,c,h),b.scale=c.scale/d,b.rotation+=g,z(a,a,b,h),t(b,b,e.set(a,a[0]-f[0],f[1]-a[1])));return b}}(),y=function(){var a=k.create();return function(b,c,d,g){return e.transformMat2d(b,c,J(a,d,g))}}(),z=function(){var a=k.create();return function(b,c,d,g){return e.transformMat2d(b,c,w(a,d,g))}}(),t=function(){var a=e.create(),b=k.create();return function(c,d,g){m(c,
d);var f=p(d),h=c.targetGeometry;k.fromRotation(b,n.toRadian(d.rotation)||0);k.scale(b,b,e.fromValues(f,f));e.transformMat2d(a,g,b);h.x+=a[0];h.y+=a[1];return c}}();return{create:H,createAsync:function(a,b){return Q.resolve(H(a,b))},copy:m,getAnchor:I,getExtent:U,setExtent:function(a,b,c,d,e){P(a,b,c.center);a.scale=v(c,d);e&&e.constraints&&e.constraints.constrain(a);return a},getPaddingMapTranslation:x,getPaddingScreenTranslation:M,getResolution:p,getScreenCenter:L,getTransform:w,getTransformNoRotation:W,
getInverseTransform:J,getOuterExtent:V,getOuterSize:K,getResolutionToScaleFactor:G,getScaleToResolutionFactor:N,angleBetween:X,addPadding:Y,centerAt:P,pixelSizeAt:function(a,b,c){return p(b)},removePadding:Z,resize:$,rotateBy:function(a,b,c){m(a,b);a.rotation+=c;return a},rotateTo:function(a,b,c){m(a,b);a.rotation=c;return a},scaleBy:aa,scaleTo:function(a,b,c){m(a,b);a.scale=c;return a},scaleAndRotateBy:ba,toMap:y,toScreen:z,translateBy:t}});