// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../geometry/Geometry ../../geometry/Polygon ../../geometry/Polyline ../../geometry/Point ../../geometry/Extent ../../geometry/Multipoint ../../geometry/support/jsonUtils ../languageUtils ../Dictionary ../Feature".split(" "),function(x,w,t,p,q,r,u,s,k,e,h,f){w.registerFunctions=function(l,m,v){l.polygon=function(c,d){return m(c,d,function(b,g,a){e.pcCheck(a,1,1);b=null;if(a[0]instanceof h){if(b=e.fixSpatialReference(f.parseGeometryFromDictionary(a[0]),c.spatialReference),
!1===b instanceof p)throw Error("Illegal Parameter");}else b=a[0]instanceof p?k.fromJSON(a[0].toJSON()):e.fixSpatialReference(new p(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return b})};l.polyline=function(c,d){return m(c,d,function(b,g,a){e.pcCheck(a,1,1);b=null;if(a[0]instanceof h){if(b=e.fixSpatialReference(f.parseGeometryFromDictionary(a[0]),
c.spatialReference),!1===b instanceof q)throw Error("Illegal Parameter");}else b=a[0]instanceof q?k.fromJSON(a[0].toJSON()):e.fixSpatialReference(new q(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return b})};l.point=function(c,d){return m(c,d,function(b,g,a){e.pcCheck(a,1,1);b=null;if(a[0]instanceof h){if(b=e.fixSpatialReference(f.parseGeometryFromDictionary(a[0]),
c.spatialReference),!1===b instanceof r)throw Error("Illegal Parameter");}else b=a[0]instanceof r?k.fromJSON(a[0].toJSON()):e.fixSpatialReference(new r(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return b})};l.multipoint=function(c,d){return m(c,d,function(b,g,a){e.pcCheck(a,1,1);b=null;if(a[0]instanceof h){if(b=e.fixSpatialReference(f.parseGeometryFromDictionary(a[0]),
c.spatialReference),!1===b instanceof s)throw Error("Illegal Parameter");}else b=a[0]instanceof s?k.fromJSON(a[0].toJSON()):e.fixSpatialReference(new s(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return b})};l.extent=function(c,d){return m(c,d,function(b,g,a){e.pcCheck(a,1,1);b=null;a[0]instanceof h?b=e.fixSpatialReference(f.parseGeometryFromDictionary(a[0]),
c.spatialReference):a[0]instanceof r?(b={xmin:a[0].x,ymin:a[0].y,xmax:a[0].x,ymax:a[0].y,spatialReference:a[0].spatialReference.toJSON()},a[0].hasZ?(b.zmin=a[0].z,b.zmax=a[0].z):a[0].hasM&&(b.mmin=a[0].m,b.mmax=a[0].m),b=k.fromJSON(b)):b=a[0]instanceof p?k.fromJSON(a[0].extent.toJSON()):a[0]instanceof q?k.fromJSON(a[0].extent.toJSON()):a[0]instanceof s?k.fromJSON(a[0].extent.toJSON()):a[0]instanceof u?k.fromJSON(a[0].toJSON()):e.fixSpatialReference(new u(JSON.parse(a[0])),c.spatialReference);if(null!==
b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return b})};l.geometry=function(c,d){return m(c,d,function(b,g,a){e.pcCheck(a,1,1);b=null;b=a[0]instanceof f?e.fixSpatialReference(a[0].geometry,c.spatialReference):a[0]instanceof h?e.fixSpatialReference(f.parseGeometryFromDictionary(a[0]),c.spatialReference):e.fixSpatialReference(k.fromJSON(JSON.parse(a[0])),c.spatialReference);if(null!==
b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return b})};l.feature=function(c,d){return m(c,d,function(b,g,a){if(0===a.length)throw Error("Missing Parameters");b=null;if(1===a.length)if(e.isString(a[0]))b=f.fromJson(JSON.parse(a[0]));else if(a[0]instanceof f)b=new f(a[0]);else if(a[0]instanceof t)b=new f(null,a[0]);else if(a[0]instanceof h)b=a[0].hasField("geometry")?a[0].field("geometry"):
null,g=a[0].hasField("attributes")?a[0].field("attributes"):null,null!==b&&b instanceof h&&(b=f.parseGeometryFromDictionary(b)),null!==g&&(g=f.parseAttributesFromDictionary(g)),b=new f(g,b);else throw Error("Illegal Argument");else{if(2===a.length){g=b=null;if(null!==a[0])if(a[0]instanceof t)b=a[0];else if(b instanceof h)b=f.parseGeometryFromDictionary(a[0]);else throw Error("Illegal Argument");if(null!==a[1])if(a[1]instanceof h)g=f.parseAttributesFromDictionary(a[1]);else throw Error("Illegal Argument");
}else{b=null;g={};if(null!==a[0])if(a[0]instanceof t)b=a[0];else if(b instanceof h)b=f.parseGeometryFromDictionary(a[0]);else throw Error("Illegal Argument");for(var n=1;n<a.length;n+=2)if(e.isString(a[n])){var d=a[n+1];if(null===d||void 0===d||e.isString(d)||isNaN(d)||e.isDate(d)||e.isNumber(d)||e.isBoolean(d)){if(v(d))throw Error("Illegal Argument");g[a[n]]=d}else throw Error("Illegal Argument");}else throw Error("Illegal Argument");}b=new f(g,b)}b.geometry=e.fixSpatialReference(b.geometry,c.spatialReference);
b.immutable=!1;return b})};l.dictionary=function(c,d){return m(c,d,function(b,c,a){if(0===a.length)throw Error("Missing Parameters");if(0!==a.length%2)throw Error("Missing Parameters");b={};for(c=0;c<a.length;c+=2)if(e.isString(a[c])){var d=a[c+1];if(null===d||void 0===d||e.isString(d)||isNaN(d)||e.isDate(d)||e.isNumber(d)||e.isBoolean(d)){if(v(d))throw Error("Illegal Argument");b[a[c]]=d}else throw Error("Illegal Argument");}else throw Error("Illegal Argument");a=new h(b);a.immutable=!1;return a})}}});