// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["../../lib/IdGen","../../lib/gl-matrix","../../parts/Model","../../lib/VertexBufferLayout","../../lib/Util"],function(V,E,W,X,F){var x=E.vec3d,Y=E.mat4d,Q=E.mat4,z=F.VertexAttrConstants,g={};g.__Material_idGen=new V;g.__GLMaterial_id=0;g.IDENTITY=Y.identity();g.Layouts=X.Defaults;g.fill=function(a,b,c,d,f,e){if(void 0===f||3!==e)for(f=0;f<e;++f)c[d+f]=a[b+f];else{var t=a[b],n=a[b+1];a=a[b+2];c[d]=f[0]*t+f[4]*n+f[8]*a+f[12];c[d+1]=f[1]*t+f[5]*n+f[9]*a+f[13];c[d+2]=f[2]*t+f[6]*n+f[10]*a+f[14]}return e};
var R=function(a,b,c,d,f,e){for(var t=a.length,n=0;n<t;++n){for(var M=c*a[n],l=0;l<c;++l)d[f+l]=b[M+l];f+=e}};g.fillInterleaved=function(a,b,c,d,f,e,t,n){var M=f.getAttributes();f=f.getStride();for(var l in M){var k=t+M[l].offset;if(!(null!=n&&null==n[l])){var h;switch(l){case z.UV0:h=a.vertexAttr[l];null!=h&&R(a.faces.indices[l],h.data,h.size,e,k,f);break;case z.REGION:h=a.vertexAttr[l];var g=a.faces.indices[l],w=h.data,m=h.size;h=e;var p=f;h=new Uint16Array(h.buffer);for(var k=2*k,p=2*p,u=g.length,
r=0;r<u;++r){var v=m*g[r],q;for(q=0;q<m;++q)h[k+q]=w[v+q];k+=p}break;case z.COLOR:h=a.vertexAttr[l];if(d&&d.color){g=a.faces.indices[l];w=h.data;m=d.color;h=h.size;p=e;u=f;p=new Uint8Array(p.buffer);k*=4;u*=4;r=g.length;for(v=0;v<r;++v){q=h*g[v];var s;for(s=0;s<h;++s)p[k+s]=w[q+s]*m[s];4>s&&(p[k+3]=255*m[3]);k+=u}}else{g=a.faces.indices[l];w=h.data;m=h.size;h=e;p=f;h=new Uint8Array(h.buffer);k*=4;p*=4;u=g.length;for(r=0;r<u;++r){v=m*g[r];for(q=0;q<m;++q)h[k+q]=w[v+q];4>q&&(h[k+3]=255);k+=p}}break;
default:if(h=a.vertexAttr[l],m=l===z.POSITION?b:l===z.NORMAL?c:void 0,void 0!==m&&3===h.size){g=a.faces.indices[l];w=h.data;h=e;p=f;u=g.length;for(r=0;r<u;++r)s=3*g[r],v=w[s],q=w[s+1],s=w[s+2],h[k]=m[0]*v+m[4]*q+m[8]*s+m[12],h[k+1]=m[1]*v+m[5]*q+m[9]*s+m[13],h[k+2]=m[2]*v+m[6]*q+m[10]*s+m[14],k+=p}else R(a.faces.indices[l],h.data,h.size,e,k,f)}}}};g.triangleVertexArrayToWireframeLines=function(a,b,c,d){for(c=Math.floor(c/3)-1;0<=c;c--){var f=b+3*c*d,e=b+6*c*d+5*d;this.fill(a,f,a,e,null,d);e-=d;this.fill(a,
f+d,a,e,null,d);e-=d;this.fill(a,f+d,a,e,null,d);e-=d;this.fill(a,f+2*d,a,e,null,d);e-=d;this.fill(a,f+2*d,a,e,null,d);e-=d;this.fill(a,f,a,e,null,d)}};var S=x.create(),Z=x.create(),$=x.create(),aa=x.create(),T=function(a,b,c,d,f){var e=a.getCenter();x.project(e,b,c,S);var e=x.dist2(S,e),t=a.getBSRadius();if(e<t*t){var e=a.getPrimitiveIndices(),t=a.getIndices(),n=a.getPosition(),g=e?e.length:t.length/3;if(1E4<g&&(a=a.getChildren(),void 0!==a)){for(e=0;8>e;++e)void 0!==a[e]&&T(a[e],b,c,d,f);return}a=
n.size;var n=n.data,l=b[0],k=b[1];b=b[2];var h=c[0]-l,z=c[1]-k;c=c[2]-b;for(var w=0;w<g;++w){var m=e?e[w]:w,p=a*t[3*m],u=a*t[3*m+1],r=a*t[3*m+2],v=n[p],q=n[p+1],p=n[p+2],s=n[u],C=n[u+1],u=n[u+2],D=n[r],E=n[r+1],r=n[r+2],G=s-v,H=C-q,I=u-p,J=D-v,A=E-q,B=r-p,K=z*B-A*c,L=c*J-B*h,F=h*A-J*z,y=G*K+H*L+I*F;if(!(y>-d&&y<d)){var y=1/y,N=l-v,O=k-q,P=b-p,K=y*(N*K+O*L+P*F);0>K||1<K||(L=O*I-H*P,I=P*G-I*N,G=N*H-G*O,H=y*(h*L+z*I+c*G),0>H||1<K+H||(J=y*(J*L+A*I+B*G),0<=J&&(A=Z,B=$,y=aa,x.set3(v,q,p,A),x.set3(s,C,u,
B),x.set3(D,E,r,y),x.subtract(B,A,B),x.subtract(y,A,y),x.normalize(x.cross(B,y,A)),f(J,A,m))))}}}};g.intersectTriangleGeometry=function(a,b,c,d,f,e,t,n,g,l,k){F.assert("triangle"===a.getData().getFaces()[b].type);T(a.getBoundingInfo(b),t,n,l,k)};g.basicMaterialConstructor=function(a,b){var c=!0,d=0,f=g.__Material_idGen.gen(b);a.getId=function(){return f};var e;a.getParentStage=function(){return e};a.addParentStage=function(a){F.assert(void 0===e,"Material can only be added to a single Stage");e=a};
a.removeParentStage=function(a){e=void 0};a.setVisible=function(e){c!==e&&(c=e,a.notifyDirty("matChanged"))};a.isVisible=function(){return c};a.notifyDirty=function(c){e&&e.notifyDirty(W.ContentType.MATERIAL,a,c)};a.setRenderPriority=function(a){d=a;this.notifyDirty("matChanged")};a.getRenderPriority=function(){return d}};var C=g.aquireIfNotUndefined=function(a,b,c,d){return void 0===a?void 0:c.aquire(a,b,d)},D=g.releaseIfNotUndefined=function(a,b){void 0!==a&&b.release(a)},U=Q.create();g.bindView=
function(a,b,c){Q.translate(b,a,U);c.uniformMatrix4fv("view",U)};g.bindCamPos=function(a,b,c){c.uniform3f("camPos",b[3]-a[0],b[7]-a[1],b[11]-a[2])};g.basicGLMaterialConstructor=function(a,b){var c=g.__GLMaterial_id++;a.getId=function(){return c};a.getMaterialId=function(){return b.getId()};var d=!0;a.isVisible=function(){return d};a.updateVisibility=function(){d=b.isVisible()};a.getRenderPriority=function(){return b.getRenderPriority()}};g.singleTextureGLMaterialConstructor=function(a,b,c,d){var f=
C(c.textureId,c.initTexture,b,d);a.updateTexture=function(a){c.textureId!==a&&(D(c.textureId,b),c.textureId=a,f=C(c.textureId,c.initTexture,b,d))};a.renderTexture=function(a){var d=b.getTexture(c.textureId);d&&d.renderGl&&d.renderGl(f,a)};a.bindTexture=function(a,d){void 0!==f&&(d.uniform1i("tex",0),a.bindTexture(a.TEXTURE_2D,f))};a.dispose=function(){D(c.textureId,b)}};g.multiTextureGLMaterialConstructor=function(a,b,c,d){for(var f=d.length,e=Array(f),g=0;g<f;g++)e[g]=C(c[d[g][0]],c[d[g][1]],b);
a.updateTextures=function(a){for(var g=0;g<f;g++){var l=c[d[g][0]],k=a[d[g][0]];l!==k&&(D(l,b),c[d[g][0]]=k,e[g]=C(k,c[d[g][1]],b))}};a.bindTextures=function(a,c){for(var b=0;b<f;b++)void 0!==e[b]&&(c.uniform1i(d[b][2],b),a.activeTexture(a.TEXTURE0+b),a.bindTexture(a.TEXTURE_2D,e[b]));a.activeTexture(a.TEXTURE0)};a.bindOneTexture=function(a,c,b){c.uniform1i(d[b][2],b);a.activeTexture(a.TEXTURE0+b);a.bindTexture(a.TEXTURE_2D,e[b]);a.activeTexture(a.TEXTURE0)};a.disposeTextures=function(){for(var a=
0;a<f;a++)D(c[d[a][0]],b)}};return g});