// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../../core/declare ./Graphics3DSymbolLayer ./Graphics3DGraphicLayer ./Graphics3DDrapedGraphicLayer ./ElevationAligners ./Graphics3DSymbolCommonCode ./lineUtils ../../../../core/screenUtils ../../../../geometry/Polygon ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/RenderGeometry".split(" "),function(C,D,E,F,y,k,s,t,G,z,A,H,I,J){var B=z.vec3d,v=z.mat4d;return C([D],{_prepareResources:function(){var a=
this.symbol,c=this._isPropertyDriven("size"),d={idHint:this._getStageIdHint(),width:this._getWidth(a),color:this._getMaterialOpacityAndColor()};if(c||2<d.width)c&&(d.width=0),d.miterLimit=a.miterLimit,d.join=a.join,this._isNativeLineMaterial=!1,this._material=s.createRibbonMaterial(d);else if(0<d.width)this._isNativeLineMaterial=!0,this._material=s.createNativeMaterial(d);else{this.reject();return}this._context.stage.add(A.ModelContentType.MATERIAL,this._material);this.resolve()},_getWidth:function(a){return null!=
a.size?t.pt2px(a.size):1},destroy:function(){this.isFulfilled()||this.reject();this._material&&(this._context.stage.remove(A.ModelContentType.MATERIAL,this._material.getId()),this._material=null)},createGraphics3DGraphic:function(a,c){var d=a.geometry;if("polyline"!==d.type&&"polygon"!==d.type&&"extent"!==d.type)return this._logWarning("unsupported geometry type for line symbol: "+d.type),null;var d="polygon"===d.type||"extent"===d.type?"rings":"paths",m="graphic"+a.id,b=this._getVertexOpacityAndColor(c,
Float32Array,255),n=0;c.size&&this._isPropertyDriven("size")&&(n=k.getSingleSizeDriver(c.size),n=t.pt2px(n));var e=this._getGraphicElevationInfo(a);return e.mode===k.ELEV_MODES.ON_THE_GROUND?this._createAsOverlay(a,d,b,n,e,m):this._createAs3DShape(a,d,b,n,e,m,a.id)},layerPropertyChanged:function(a,c,d){if("opacity"===a)return this._isNativeLineMaterial?(c=this._material.getColor(),c[3]=this._getMaterialOpacity(),this._material.setColor(c)):(c=this._material.getParameterValues(),c.color[3]=this._getMaterialOpacity(),
this._material.setParameterValues({color:c.color})),!0;if("elevationInfo"===a){a=this._elevationInfo.mode;this._updateElevationInfo();var m=this._elevationInfo.mode;if(null==a||null==m)return!1;var b=k.ELEV_MODES;if(a===b.ON_THE_GROUND&&m===b.ON_THE_GROUND)return!0;if(a!==m&&(a===b.ON_THE_GROUND||m===b.ON_THE_GROUND))return!1;a=m===b.RELATIVE_TO_GROUND?y.perVertexElevationAligner:null;var m=this._context.elevationProvider,b=this._context.renderCoordsHelper,n;for(n in c){var e=c[n],f=e._graphics[d];
f&&(e=e.graphic,f.elevationAligner=a,f.elevationInfo.set(this._getGraphicElevationInfo(e)),y.perVertexElevationAligner(f,m,b))}return!0}return!1},_getOutlineGeometry:function(a,c){return a._outlineSegments?s.createOutlineGeometryFromSegments(c,a._outlineSegments):c},_getGeometry:function(a){a=a.geometry;"extent"===a.type&&(a=G.fromExtent(a));return a},_createAs3DShape:function(a,c,d,m,b,n,e){var f=this._getGeometry(a),r=f.hasZ,l=this._getOutlineGeometry(f,f[c]);if(0<l.length){a=[];for(var g=[],p=
[],q=B.create(),t=Array(6),l=k.getGeometryVertexData3D(l,r,f.spatialReference,this._context.renderSpatialReference,this._context.elevationProvider,b),f=l.geometryData.outlines,r=l.eleVertexData,l=l.vertexData,w=0;w<f.length;++w){var x=f[w],h=x.index,u=x.count;if(this._context.clippingExtent&&(k.computeBoundingBox(r,h,u,t),k.boundingBoxClipped(t,this._context.clippingExtent)))continue;k.chooseOrigin(l,h,u,q);k.subtractCoordinates(l,h,u,q);x=new Float64Array(r.buffer,3*h*r.BYTES_PER_ELEMENT,3*u);h=
new Float64Array(l.buffer,3*h*l.BYTES_PER_ELEMENT,3*u);h=s.createPolylineGeometry(h,x,"rings"===c,d,m,!1);h=new I(h,n+"path"+w);h.singleUse=!0;a.push(h);g.push([this._material]);h=v.identity();v.translate(h,q,h);p.push(h)}c=new H({geometries:a,materials:g,transformations:p,castShadow:!1,metadata:{layerId:this._context.layer.id,graphicId:e},idHint:n});d=null;b.mode===k.ELEV_MODES.RELATIVE_TO_GROUND&&(d=y.perVertexElevationAligner);return new E(this,c,a,null,null,d,b)}this._logWarning("no paths found for line symbol");
return null},_createAsOverlay:function(a,c,d,m,b,n){var e=this._getGeometry(a);this._material.setRenderPriority(this._symbolLayerOrder);var f=this._getOutlineGeometry(e,e[c]);if(0<f.length){a=[];b=Array(6);for(var r=B.create(),f=k.getGeometryVertexDataDraped(f,e.spatialReference,this._context.overlaySR),e=f.vertexData,f=f.geometryData.outlines,l=0;l<f.length;++l){var g=f[l],p=g.index,g=g.count;k.computeBoundingBox(e,p,g,b);if(!k.boundingBoxClipped(b,this._context.clippingExtent)){k.chooseOrigin(e,
p,g,r);k.subtractCoordinates(e,p,g,r);k.setZ(e,p,g,this._getDrapedZ());g=new Float64Array(e.buffer,3*p*e.BYTES_PER_ELEMENT,3*g);p=v.identity();v.translate(p,r,p);var g=s.createPolylineGeometry(g,null,"rings"===c,d,m,!0),q=new J(g);q.material=this._material;q.center=[0.5*(b[0]+b[3]),0.5*(b[1]+b[4]),0];q.bsRadius=0.5*Math.sqrt((b[3]-b[0])*(b[3]-b[0])+(b[4]-b[1])*(b[4]-b[1]));q.transformation=p;q.name=n;q.uniqueName=n+"#"+g.id;a.push(q)}}return new F(this,a,null,null,b)}return null}})});