// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../support/earthUtils ../../support/projectionUtils ../../support/intersectionUtils ../../lib/glMatrix".split(" "),function(s,t,h,n,k,l){var c=l.vec3d,m=l.vec4d,g=-0.3*h.earthRadius,p=0.5*h.earthRadius*Math.PI,q=0.9*h.earthRadius,r=function(){function b(){this.extent=Array(4);this.planes=Array(4);this.maxSpan=0;this.center={origin:c.create(),direction:c.create()};for(var a=0;4>a;a++)this.extent[a]={origin:c.create(),direction:c.create(),cap:{next:null,direction:c.create()}},
this.planes[a]=m.create();this.planes[4]=m.create()}b.prototype.update=function(a,b,f,e,d){c.set3(a[0],a[1],g,this.extent[0].origin);c.set3(a[2],a[1],g,this.extent[1].origin);c.set3(a[2],a[3],g,this.extent[2].origin);c.set3(a[0],a[3],g,this.extent[3].origin);if(!d)for(d=0;4>d;d++)n.vectorToVector(this.extent[d].origin,e,this.extent[d].origin,f);c.add(this.extent[0].origin,this.extent[2].origin,this.center.origin);c.scale(this.center.origin,0.5);b(this.center.origin,this.center.direction);for(d=0;4>
d;d++)f=this.extent[d],b(f.origin,f.direction),e=this.extent[3===d?0:d+1],f.cap.next=e.origin,c.direction(e.origin,f.origin,f.cap.direction),c.cross(this.extent[d].cap.direction,this.extent[d].direction,this.planes[d]),this.planes[d][3]=-c.dot(this.planes[d],this.extent[d].origin);this.maxSpan=Math.max(Math.abs(a[0]-a[2]),Math.abs(a[1]-a[3]))};b.prototype.isVisibleInFrustumGlobal=function(a){if(0>c.dot(this.center.direction,a.direction))return!0;for(var b=0;4>b;b++)if(0>c.dot(this.extent[b].direction,
a.direction))return!0;return!1};b.prototype.isVisibleInFrustum=function(a,b){if("global"===a.viewingMode){if(this.maxSpan>p)return!0;if(b.altitude()>=q)return this.isVisibleInFrustumGlobal(b)}for(var c=0;c<this.extent.length;c++){var e=this.extent[c];if(k.frustumRay(b.planes,e.origin,null,e.direction)||k.frustumLineSegment(b.planes,e.origin,e.cap.next,e.cap.direction))return!0}for(c=0;c<b.lines.length;c++)if(e=b.lines[c],k.frustumLineSegment(this.planes,e.origin,e.endpoint,e.direction))return!0;return!1};
return b}();return function(){function b(){this.frustumVisibilityDirty=this.frustumVisibility=!0;this.extent=null;this.extentEngine=new r;this.extentEngineDirty=!0;this.layerView=this.renderSREqualsViewSR=null}b.prototype.initialize=function(a){this.layerView=a;this.renderSREqualsViewSR=a.view.renderSpatialReference.equals(a.view.spatialReference)};b.prototype.destroy=function(){this.extentEngine=this.extent=this.layerView=null};b.prototype.needsIdleUpdate=function(){return this.frustumVisibilityDirty};
b.prototype.canResume=function(){return this.frustumVisibility};b.prototype.setExtent=function(a){this.extent=a;this.frustumVisibilityDirty=this.extentEngineDirty=!0};b.prototype.viewChange=function(){this.frustumVisibilityDirty=!0};b.prototype.idleUpdate=function(a){!a.done()&&this.frustumVisibilityDirty&&(this.updateSuspendFrustumVisible(),this.frustumVisibilityDirty=!1)};b.prototype.updateExtentEngine=function(){if(this.extentEngineDirty){this.extentEngineDirty=!1;var a=this.layerView.view;this.extentEngine.update(this.extent,
a.renderCoordsHelper.worldUpAtPosition,a.renderSpatialReference,a.spatialReference,this.renderSREqualsViewSR)}};b.prototype.updateSuspendFrustumVisible=function(){if(this.extent){this.updateExtentEngine();var a=this.layerView.view.getFrustum(),a=this.extentEngine.isVisibleInFrustum(this.layerView.view,a);a!==this.frustumVisibility&&(this.frustumVisibility=a,this.layerView._notifySuspendedChange())}else this.frustumVisibility=!0};return b}()});