// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../../geometry/Point ../../../../geometry/support/mathUtils ./graphicUtils ./ElevationInfo ../../support/projectionUtils ../../lib/glMatrix ../../webgl-engine/lib/Object3D".split(" "),function(x,v,y,t,u,w,z){var A=w.mat4d,k=w.vec3d.create(),B=A.identity(),r={x:0,y:0,z:0,spatialReference:null},m={createStageObjectForPoint:function(b,a,d,c,e,g,f,h,C){var n=a?a.length:0,l=this._context.clippingExtent;m.reprojectPoint(b,k,this._context.elevationProvider.spatialReference);if(l&&!m.pointInBox2D(k,
l))return null;m.reprojectPoint(b,k,this._context.renderSpatialReference);l=this._context.localOriginFactory.getOrigin(k);f=new z({castShadow:!1,metadata:{layerId:h,graphicId:C},idHint:f});for(h=0;h<n;h++)f.addGeometry(a[h],d[h],c?c[h]:B,e,l);m.setObjectElevation(f,b,g,this._context.renderSpatialReference,this._context.elevationProvider);return f},extendPointGraphicElevationInfo:function(b,a,d){b=b.elevationInfo;d=d.spatialReference;m.reprojectPoint(a,k,d);b.centerPointInElevationSR={x:k[0],y:k[1],
z:a.hasZ?k[2]:void 0,spatialReference:d}},placePointOnPolyline:function(b){var a=b.paths[0],a=v.getPointOnPath(a,v.getPathLength(a)/2);return new x(a[0],a[1],a[2],b.spatialReference)},placePointOnPolygon:function(b){return y.computeCentroid(b)},computeElevation:function(b,a,d){var c=0,e=a.z||0,g=0,g=d.mode,f=d.offset||0;g===t.MODES.ON_THE_GROUND?c=g=b.getElevation(a)||0:g===t.MODES.RELATIVE_TO_GROUND?(g=b.getElevation(a)||0,c=g+f,null==d.featureExpression&&(c+=e)):g===t.MODES.ABSOLUTE_HEIGHT&&(c=
e+f);return c},applyElevation:function(b,a,d,c,e,g,f){var h=f.mode,m=f.offset,n=0,n=0;r.spatialReference=b.spatialReference;d*=3;e*=3;for(var l=0;l<g;++l)r.x=a[d+0],r.y=a[d+1],r.z=a[d+2],h===t.MODES.ON_THE_GROUND?n=b.getElevation(r)||0:h===t.MODES.RELATIVE_TO_GROUND?(n=b.getElevation(r)||0,n+=m,null==f.featureExpression&&(n+=r.z)):h===t.MODES.ABSOLUTE_HEIGHT&&(n=r.z+m),c[e+0]=a[d+0],c[e+1]=a[d+1],c[e+2]=n,d+=3,e+=3},setObjectElevation:function(b,a,d,c,e){d=m.computeElevation(e,a,d);e=b.getObjectTransformation();
k[0]=a.x;k[1]=a.y;k[2]=d;u.computeLinearTransformation(a.spatialReference,k,e,c)?b.setObjectTransformation(e):console.warn("Could not locate symbol object properly, it might be misplaced")},getSingleSizeDriver:function(b){return isFinite(b[0])?b[0]:null},isCounterClockwise:function(b){for(var a=0,d=b.length-1,c=0;c<d;c++)a+=b[c][0]*b[c+1][1]-b[c+1][0]*b[c][1];return 0<=a},copyPointData:function(b,a,d,c,e,g){c*=3;for(var f=0;f<e;++f){var h=b[a++];d[c++]=h[0];d[c++]=h[1];d[c++]=g?h[2]:0}return c/3},
copyPathData:function(b,a){for(var d=b.length,c=Array(d),e=Array(d),g=Array(d),f=0,h=0,k=0,n=0,l=0;l<d;++l)n+=b[l].length;for(var n=new Float64Array(3*n),s=0,r=d-1;0<=r;r--){var p=b[r];if(m.isCounterClockwise(p))c[f++]=p;else{for(var q=p.length,l=0;l<f;++l)q+=c[l].length;l={index:s,pathLengths:Array(f+1),count:q,holeIndices:Array(f)};l.pathLengths[0]=p.length;0<p.length&&(g[k++]={index:s,count:p.length});s=m.copyPointData(p,0,n,s,p.length,a);for(p=0;p<f;++p)q=c[p],l.holeIndices[p]=s,l.pathLengths[p+
1]=q.length,0<q.length&&(g[k++]={index:s,count:q.length}),s=m.copyPointData(q,0,n,s,q.length,a);f=0;0<l.count&&(e[h++]=l)}}for(p=0;p<f;++p)q=c[p],0<q.length&&(g[k++]={index:s,count:q.length}),s=m.copyPointData(q,0,n,s,q.length,a);h<d&&(e.length=h);k<d&&(g.length=k);return{vertexData:n,polygons:e,outlines:g}},copyVertices:function(b,a,d,c,e){a*=3;c*=3;for(var g=0;g<e;++g)d[c++]=b[a++],d[c++]=b[a++],d[c++]=b[a++]},chooseOrigin:function(b,a,d,c){a=Math.floor(a+(d-1)/2);c[0]=b[3*a+0];c[1]=b[3*a+1];c[2]=
b[3*a+2]},subtractCoordinates:function(b,a,d,c){a*=3;for(var e=0;e<d;++e)b[a++]-=c[0],b[a++]-=c[1],b[a++]-=c[2]},setZ:function(b,a,d,c){a*=3;for(var e=0;e<d;++e)b[a+2]=c,a+=3},offsetZ:function(b,a,d,c){a*=3;for(var e=0;e<d;++e)b[a+2]+=c,a+=3},scaleZ:function(b,a,d,c){a*=3;for(var e=0;e<d;++e)b[a+2]*=c,a+=3},flatArrayToArrayOfArrays:function(b,a,d){var c=[];a*=3;for(var e=0;e<d;++e)c.push([b[a++],b[a++],b[a++]]);return c},reproject:function(b,a,d,c,e,g,f){u.bufferToBuffer(b,d,a,c,g,e,f)},reprojectPoint:function(b,
a,d){u.pointToVector(b,a,d)},getGeometryVertexData3D:function(b,a,d,c,e,g){var f=e.spatialReference;b=m.copyPathData(b,a);a=b.vertexData;var h=a.length/3,k=new Float64Array(a.length);d.equals(f)?m.copyVertices(a,0,k,0,a.length):m.reproject(a,0,d,k,0,f,h);m.applyElevation(e,k,0,a,0,h,g);f.equals(c)||m.reproject(a,0,f,a,0,c,h);return{geometryData:b,vertexData:a,eleVertexData:k}},getGeometryVertexDataDraped:function(b,a,d){b=m.copyPathData(b,!1);var c=b.vertexData,e=c.length/3;a.equals(d)||u.bufferToBuffer(c,
a,0,c,d,0,e);return{geometryData:b,vertexData:c}},computeBoundingBox:function(b,a,d,c){c[0]=Number.MAX_VALUE;c[1]=Number.MAX_VALUE;c[2]=Number.MAX_VALUE;c[3]=-Number.MAX_VALUE;c[4]=-Number.MAX_VALUE;c[5]=-Number.MAX_VALUE;a*=3;for(var e=0;e<d;++e){var g=b[a++],f=b[a++],h=b[a++];g<c[0]&&(c[0]=g);f<c[1]&&(c[1]=f);h<c[2]&&(c[2]=h);g>c[3]&&(c[3]=g);f>c[4]&&(c[4]=f);h>c[5]&&(c[5]=h)}return c},pointInBox2D:function(b,a){return!(b[0]>a[3]||b[0]<a[0]||b[1]>a[4]||b[1]<a[1])},boxesIntersect2D:function(b,a){return!(a[0]>
b[3]||a[3]<b[0]||a[1]>b[4]||a[4]<b[1])},boundingBoxClipped:function(b,a){return a?!m.boxesIntersect2D(b,a):!1},ELEV_MODES:t.MODES};return m});