// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../../core/declare ../../../../Color ./Graphics3DSymbolLayer ./Graphics3DGraphicLayer ./ElevationAligners ./Graphics3DSymbolCommonCode ../i3s/I3SSymbolLoader ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/materials/Material ../../webgl-engine/lib/Util".split(" "),function(D,z,E,v,w,q,F,A,n,G,h,H,I){var J=I.assert,r=A.mat4d,B=A.vec3d,t=[1,1,1],K=[10,10,10],C=[n.ModelContentType.MATERIAL,n.ModelContentType.TEXTURE,
n.ModelContentType.GEOMETRY];return D([E],{_prepareResources:function(){var a=this.symbol,c=this._getStageIdHint();a.resource&&a.resource.href?((a=a.resource.href)&&(0===a.indexOf("http")&&"https:"===location.protocol)&&(a=a.replace(/^http:/i,"https:")),this._prepareModelResources(a,c)):this._preparePrimitiveResources(a.resource?a.resource.primitive:"sphere",c)},_sizeToScale:function(a,c,b,d){for(var e=Array(3),g=2;0<=g;g--){var f=a[g];null!==f&&isFinite(f)?e[g]=f/(c[g+3]-c[g]):e[g]="symbolValue"===
f?b?b[g]:1:null}a=d;c=0;for(g=2;0<=g;g--)f=e[g],null!==f&&(a=f,c=Math.max(c,Math.abs(f)));for(g=2;0<=g;g--)null===e[g]?e[g]=a:0===e[g]&&(e[g]=0.0010*c);return e},_computeSymbolScale:function(a,c){var b=[a.width,a.depth,a.height];return b[0]||b[1]||b[2]?this._sizeToScale(b,c,null,1):null},_preparePrimitiveResources:function(a,c){var b=this.symbol;if("sphere"===a)this._geometryData=h.createPolySphereGeometry(0.5,2,!0),this._geometryOrigin="center";else if("cube"===a)this._geometryData=h.createBoxGeometry(1),
this._geometryOrigin="center";else if("cylinder"===a)this._geometryData=h.createCylinderGeometry(1,0.5,16,[0,0,1],[0,0,0.5]),this._geometryOrigin="bottom";else if("cone"===a)0>b.height?(this._geometryData=h.createConeGeometry(1,0.5,15,!0),b.height=-b.height):this._geometryData=h.createConeGeometry(1,0.5,15,!1),h.cgToGIS(this._geometryData),this._geometryOrigin="bottom";else if("tetrahedron"===a)this._geometryData=h.createTetrahedronGeometry(1),h.cgToGIS(this._geometryData),this._geometryOrigin="bottom";
else if("diamond"===a)this._geometryData=h.createDiamondGeometry(1),h.cgToGIS(this._geometryData),this._geometryOrigin="center";else{console.warn("Unknown object symbol primitive: "+a);this.reject();return}this._geometry=new G(this._geometryData,c);this._context.stage.add(n.ModelContentType.GEOMETRY,this._geometry);var d=[-0.5,-0.5,-0.5,0.5,0.5,0.5];this._symbolScale=this._computeSymbolScale(b,d);this._boundingBox=d;d=this._getMaterialOpacity();d={specular:[0,0,0],shininess:3,opacity:d,transparent:1>
d||this._isPropertyDriven("opacity"),instanced:this._hasPerInstanceColor()?["transformation","color"]:["transformation"]};this._isPropertyDriven("color")?(d.ambient=t,d.diffuse=t):(b=b.material?z.toUnitRGB(b.material.color):t,d.ambient=b,d.diffuse=b);this._material=new H(d,c+"_objectmat");this._context.stage.add(n.ModelContentType.MATERIAL,this._material);this.resolve()},_prepareModelResources:function(a,c){var b={materialParamsMixin:{instanced:this._hasPerInstanceColor()?["transformation","color"]:
["transformation"]},idHint:c};(new F(this._context.streamDataSupplier)).fetchSymbol(a,b).then(function(a){if(!this.isRejected()){var b=a.stageResources,c=this._context.stage,f=this.symbol.material,x;this._isPropertyDriven("color")?x={ambient:t,diffuse:t}:f&&f.color&&(f=z.toUnitRGB(f.color),x={ambient:f.map(function(a){return a/1.5}),diffuse:f});var k=this._computeModelOpacityOverride();a.originalMaterialOpacities=Array(b[n.ModelContentType.MATERIAL].length);b[n.ModelContentType.MATERIAL].forEach(function(b,
c){var e=b.getParameterValues();a.originalMaterialOpacities[c]=e.opacity;x&&b.setParameterValues(x);k.overwrite?b.setParameterValues({opacity:k.overwrite,transparent:k.blendingRequired}):null!=k.multiply&&(e.opacity*=k.multiply,e.transparent=1>e.opacity,b.setParameterValues({opacity:e.opacity,transparent:e.transparent}))});C.forEach(function(a){for(var d=b[a],f=0;d&&f<d.length;f++)c.add(a,d[f])});for(var p=b[n.ModelContentType.GEOMETRY],f=a.geometryTransformations,l=[Number.MAX_VALUE,Number.MAX_VALUE,
Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE],h=[0,0,0],u=[0,0,0],s=0;s<p.length;s++)for(var q=p[s],y=0,v=q.getNumGroups();y<v;++y){var m=q.getBoundingInfo(y);r.multiplyVec3(f[s],m.getBBMin(),h);r.multiplyVec3(f[s],m.getBBMax(),u);for(m=0;3>m;++m){if(h[m]>u[m]){var w=h[m];h[m]=u[m];u[m]=w}l[m]=Math.min(l[m],h[m]);l[m+3]=Math.max(l[m+3],u[m])}}this._boundingBox=l;this._symbolScale=this._computeSymbolScale(this.symbol,l);B.scale(a.pivotOffset,-1);p=f.length;for(l=0;l<p;l++)r.translate(f[l],
a.pivotOffset);B.scale(a.pivotOffset,-1);this._i3sModel=a;this.resolve()}}.bind(this),function(){this.reject()}.bind(this))},_computeModelOpacityOverride:function(){var a={overwrite:null,blendingRequired:!1,multiply:null},c=this._getMaterialOpacity();this._isPropertyDriven("opacity")?(a.overwrite=c,a.blendingRequired=!0):this.symbol.material&&void 0!==this.symbol.material.transparency?(a.overwrite=c,a.blendingRequired=1>a.overwrite):1>c&&(a.multiply=c,a.blendingRequired=!0);return a},destroy:function(){this.isFulfilled()||
this.reject();var a=this._context.stage;if(this._i3sModel){var c=this._i3sModel.stageResources;C.forEach(function(b){for(var d=c[b],e=0;d&&e<d.length;e++)a.remove(b,d[e].getId())})}else this._material&&a.remove(n.ModelContentType.MATERIAL,this._material.getId()),this._geometry&&a.remove(n.ModelContentType.GEOMETRY,this._geometry.getId())},createGraphics3DGraphic:function(a,c){var b=a.geometry;if("polyline"===b.type)b=q.placePointOnPolyline(b);else if("polygon"===b.type)b=q.placePointOnPolygon(b);
else if("extent"===b.type)b=b.get("center");else if("point"!==b.type)return this._logWarning("unsupported geometry type for object symbol: "+b.type),null;var d="graphic"+a.id,e=this._getGraphicElevationInfo(a);return this._createAs3DShape(a,b,c,e,d,a.id)},layerPropertyChanged:function(a,c,b){if("opacity"===a){if(this._i3sModel){var d=this._computeModelOpacityOverride();this._i3sModel.stageResources[n.ModelContentType.MATERIAL].forEach(function(a,b){if(d.overwrite)a.setParameterValues({opacity:d.overwrite,
transparent:d.blendingRequired});else{var c=this._i3sModel.originalMaterialOpacities[b];null!=d.multiply&&(c*=d.multiply);a.setParameterValues({opacity:c,transparent:1>c})}}.bind(this))}else c=this._getMaterialOpacity(),this._material.setParameterValues({opacity:c,transparent:1>c||this._isPropertyDriven("opacity")});return!0}if("elevationInfo"===a){this._updateElevationInfo();a=this._context.elevationProvider;var e=this._context.renderCoordsHelper,g=w.perObjectElevationAligner,f=q.ELEV_MODES.ABSOLUTE_HEIGHT,
h;for(h in c){var k=c[h],p=k._graphics[b];p&&(k=this._getGraphicElevationInfo(k.graphic),p.elevationAligner=k.mode!==f?g:null,p.elevationInfo.set(k),g(p,a,e))}return!0}return!1},_createAs3DShape:function(a,c,b,d,e,g){a=this._hasPerInstanceColor()?{color:this._mixinColorAndOpacity(b.color,b.opacity)}:null;b=this._computeObjectScale(b,!this._i3sModel);var f=this._context.layer.id;if(this._i3sModel){var h=this._i3sModel.stageResources[n.ModelContentType.GEOMETRY],k=this._i3sModel.materialsByComponent,
p=this._i3sModel.geometryTransformations;e=q.createStageObjectForPoint.call(this,c,null,null,null,null,d,e,f,g);if(null===e)return null;for(g=0;g<h.length;g++){f=p[g];if(b){var l=r.identity();r.scale(l,b);r.multiply(l,f);f=l}for(var l=k[g],t=l.length,u=Array(t),s=0;s<t;s++)u[s]=a;e.addGeometry(h[g],l,f,u)}}else k=this.symbol,"bottom"===k.anchor&&"center"===this._geometryOrigin?h=[0,0,0.5]:"center"===k.anchor&&"bottom"===this._geometryOrigin&&(h=[0,0,-0.5]),k=r.identity(),b&&r.scale(k,b),h&&r.translate(k,
h),e=q.createStageObjectForPoint.call(this,c,[this._geometry],[[this._material]],[k],[a],d,e,f,g);if(null===e)return null;e.setCastShadow(!0);a=null;d.mode!==q.ELEV_MODES.ABSOLUTE_HEIGHT&&(a=w.perObjectElevationAligner);d=new v(this,e,null,null,null,a,d,v.VisibilityModes.REMOVE_OBJECT);q.extendPointGraphicElevationInfo(d,c,this._context.elevationProvider);return d},_computeObjectScale:function(a,c){var b;a.size&&this._isPropertyDriven("size")?(b=this._sizeToScale(a.size,this._boundingBox,this._symbolScale,
null),J(null!=b[0],"sizeInfo has no values")):b=this._symbolScale?this._symbolScale.slice(0):c?K.slice(0):[1,1,1];for(var d=this._context.renderCoordsHelper.unitInMeters,e=2;0<=e;e--)b[e]/=d;return 1!==b[0]||1!==b[1]||1!==b[2]?b:null},_hasPerInstanceColor:function(){return this._isPropertyDriven("color")||this._isPropertyDriven("opacity")}})});