// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports dojo/promise/all dojo/Deferred ../../webgl-engine/lib/TextTextureAtlas ../../webgl-engine/lib/MaterialCollection ../../webgl-engine/materials/HUDMaterial ../../../../layers/support/LabelClass ../../lib/glMatrix".split(" "),function(n,k,r,s,t,u,v,p,l){var w=l.vec3d;n=function(){function b(){this.hudMaterialCollection=this.textTextureAtlas=null;this.showLabelsChangeOnResume=!1;this.labelClasses=[];this.eventHandles=[];this.graphicsCore=this.layer=this.layerView=null}b.prototype.initialize=
function(f,e,c){var a=this;this.layerView=f;this.layer=e;this.graphicsCore=c;this.layerView.view.labelManager.addSceneServiceLayerView(this);this.eventHandles.push(this.layerView.watch("suspended",function(){return a.suspendedChange()}))};b.prototype.destroy=function(){this.layerView.view.labelManager.removeSceneServiceLayerView(this);this.textTextureAtlas&&(this.textTextureAtlas.dispose(),this.textTextureAtlas=null);this.hudMaterialCollection&&(this.hudMaterialCollection.dispose(),this.hudMaterialCollection=
null);this.labelClasses=null;this.eventHandles.forEach(function(f){return f.remove()});this.graphicsCore=this.layer=this.layerView=this.eventHandles=null};b.prototype.clear=function(){this.layerView.view.labelManager.setDirty();this.textTextureAtlas&&(this.textTextureAtlas.dispose(),this.textTextureAtlas=null);this.hudMaterialCollection&&(this.hudMaterialCollection.dispose(),this.hudMaterialCollection=null)};b.prototype.suspendedChange=function(){!1===this.layerView.suspended&&this.showLabelsChangeOnResume&&
this.showLabelsChange()};b.prototype.initLabelingInfo=function(){var f=this,e=new s;this.layer.then(function(){var c=f.layer.labelingInfo;if(c){f.labelClasses=Array(c.length);for(var a=[],d=0;d<c.length;d++){var b=f.graphicsCore.getOrCreateGraphics3DSymbol(c[d].symbol);b.then(function(a,d){f.labelClasses[a]={labelClass:c[a],graphics3DSymbolLayer:d,graphics3DGraphics:[]}}.bind(f,d,b));a.push(b)}r(a).then(function(){e.resolve()})}else e.resolve()});return e.promise};b.prototype.createLabelsForGraphic=
function(f,b){if(this.labelClasses&&0<this.labelClasses.length&&b._graphics[0])for(var c=0;c<this.labelClasses.length;c++){var a=this.labelClasses[c];if(p.evaluateWhere(a.labelClass.where,f.attributes)){var d=a.labelClass.getLabelExpression();if(d&&(d=p.buildLabelText(d,f.attributes,this.layer.fields))){var c=a.graphics3DSymbolLayer.childGraphics3DSymbols[0],g=this.evalLabelPlacementParams(f,b);null==this.textTextureAtlas&&(this.textTextureAtlas=new t(this.layer.id,this.layerView.view._stage),this.hudMaterialCollection=
new u(this.layerView.view._stage));if(d=c.createGraphics3DGraphic(f,{text:d,centerOffset:g.centerOffset,translation:g.translation,screenOffset:g.screenOffset,anchor:g.anchor},this.hudMaterialCollection,this.textTextureAtlas))d._labelClass=a.labelClass,b.addLabelGraphic(d),a.graphics3DGraphics.push(b),d.setVisibilityFlag("VISIBILITY_LABEL_SHOW",this.layerLabelsEnabled()),this.layerView.view.labelManager.setInitialLabelGraphicState(d);break}}}return b};b.prototype.evalLabelPlacementParams=function(b,
e){var c=h[this.layer.labelingInfo[0].labelPlacement]||h["default"];if("polygon"===b.geometry.type||"polyline"===b.geometry.type||"extent"===b.geometry.type)return{anchor:"center"};if("point"!==b.geometry.type)return{anchor:c.anchor};var a=e.graphics3DSymbol.symbol.symbolLayers.getItemAt(0),d={screenOffset:[0,0],centerOffset:[0,0,0,-1],translation:e.getCenterObjectSpace(),anchor:c.anchor};if("Icon"===a.type)if(a=e._graphics[0].getScreenSize(),e.isDraped())d.anchor="center";else{var g=e._graphics[0].stageObject.getGeometryRecords()[0].materials[0];
g instanceof v?(g=g.getParams(),d.screenOffset=[a[0]/2*(c.normalizedOffset[0]-2*(g.anchorPos[0]-0.5)),a[1]/2*(c.normalizedOffset[1]-2*(g.anchorPos[1]-0.5))]):d.screenOffset=[a[0]/2*c.normalizedOffset[0],a[1]/2*c.normalizedOffset[1]]}else"Object"===a.type&&(a=e._graphics[0].getBoundingBoxObjectSpace(),a=[a[3]-a[0],a[4]-a[1],a[5]-a[2]],g=Math.max(a[0],a[1]),d.centerOffset[0]=1.1*g/2*c.normalizedOffset[0],d.translation[2]+=1.1*a[2]/2*c.normalizedOffset[1],a=w.length(a),d.centerOffset[2]=1.1*a/2*c.normalizedOffset[2]);
return d};b.prototype.layerLabelsEnabled=function(){return this.layer.labelsVisible};b.prototype.getGraphics3DGraphics=function(){return this.graphicsCore.getGraphics3DGraphics()};b.prototype.getGraphics3DGraphicsKeys=function(){return this.graphicsCore.getGraphics3DGraphicsKeys()};b.prototype.showLabelsChange=function(){var b=this;if(this.layerView.suspended)this.showLabelsChangeOnResume=!0;else if(this.layerView.loadedGraphics){var e=this.layerLabelsEnabled();this.layerView.loadedGraphics.forEach(function(c){var a=
b.graphicsCore.getGraphics3DGraphicById(c.id);if(a){if(e&&0===a._labelGraphics.length){a=b.createLabelsForGraphic(c,a);for(c=0;c<a._labelGraphics.length;c++){var d=a._labelGraphics[c];d.initialize(b.graphicsCore.labelStageLayer,b.layerView.view._stage)}}for(c=0;c<a._labelGraphics.length;c++)d=a._labelGraphics[c],d.setVisibilityFlag("VISIBILITY_LABEL_SHOW",e)}});this.layerView.view.labelManager.setDirty();this.showLabelsChangeOnResume=!1}};b.prototype.elevationInfoChange=function(){this.labelClasses&&
this.labelClasses.forEach(function(b){b.graphics3DSymbolLayer.layerPropertyChanged("elevationInfo",{})})};return b}();var h={"above-center":{normalizedOffset:[0,1,0],anchor:"bottom"},"above-left":{normalizedOffset:[-1,1,0],anchor:"bottom-right"},"above-right":{normalizedOffset:[1,1,0],anchor:"bottom-left"},"below-center":{normalizedOffset:[0,-1,2],anchor:"top"},"below-left":{normalizedOffset:[-1,-1,0],anchor:"top-right"},"below-right":{normalizedOffset:[1,-1,0],anchor:"top-left"},"center-center":{normalizedOffset:[0,
0,1],anchor:"center"},"center-left":{normalizedOffset:[-1,0,0],anchor:"right"},"center-right":{normalizedOffset:[1,0,0],anchor:"left"}};k={"above-center":["default","esriServerPointLabelPlacementAboveCenter"],"above-left":["esriServerPointLabelPlacementAboveLeft"],"above-right":["esriServerPointLabelPlacementAboveRight"],"below-center":["esriServerPointLabelPlacementBelowCenter"],"below-left":["esriServerPointLabelPlacementBelowLeft"],"below-right":["esriServerPointLabelPlacementBelowRight"],"center-center":["esriServerPointLabelPlacementCenterCenter"],
"center-left":["esriServerPointLabelPlacementCenterLeft"],"center-right":["esriServerPointLabelPlacementCenterRight"]};var q,m;for(m in k)l=k[m],q=h[m],l.forEach(function(b){h[b]=q});Object.freeze&&(Object.freeze(h),Object.keys(h).forEach(function(b){Object.freeze(h[b]);Object.freeze(h[b].normalizedOffset)}));return n});