// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/HandleRegistry ./Graphics3DCore ./Graphics3DLabeling ./Graphics3DScaleVisibility ./Graphics3DFrustumVisibility ./Graphics3DSharedResources ./Graphics3DElevationAlignment ./Graphics3DVerticalScale".split(" "),function(n,p,d,e,f,g,h,k,l,m){return function(){function c(a){var b=this;this._handles=new d;this.layer=a.layer;this.owner=a.owner;this.spatialIndex=a.spatialIndex;this.updateClippingExtent=a.updateClippingExtent;this.updateSuspendResumeExtent=a.updateSuspendResumeExtent;
this.elevationChanged=a.elevationChanged;this.graphicsCore=new e;this.sharedResources=new k;a.frustumVisibilityEnabled&&(this.frustumVisibility=new h,this._handles.add([this.owner.view.on("resize",function(){return b.frustumVisibility.viewChange()}),this.owner.view.navigation.on("currentViewChanged",function(){return b.frustumVisibility.viewChange()})]));a.scaleVisibilityEnabled&&(a.spatialIndex?(this.scaleVisibility=new g,this._handles.add(this.layer.watch("minScale,maxscale",function(){return b.scaleVisibility.layerMinMaxScaleChangeHandler()}))):
console.warn("scaleVisibility requires a spatialIndex"));a.elevationAlignmentEnabled&&(this.elevationAlignment=new l,this._handles.add(this.layer.watch("elevationInfo",function(){return b.graphicsCore.elevationInfoChange()})));a.labelingEnabled&&(this.labeling=new f,this._handles.add(this.layer.watch("labelsVisible",function(){return b.labeling.showLabelsChange()})));a.verticalScaleEnabled&&(this.verticalScale=new m({sourceSpatialReference:this.layer.spatialReference,destSpatialReference:this.owner.view.spatialReference}))}
c.prototype.initialize=function(){var a=this;this.spatialIndex&&this.spatialIndex.initialize(this.owner,this.layer,this.owner.view.spatialReference,this.graphicsCore);this.sharedResources.initialize(this.owner.view._stage,this.owner.view.resourceController,this.layer);this.frustumVisibility&&this.frustumVisibility.initialize(this.owner);var b=this.owner.view.basemapTerrain;this.scaleVisibility&&this.scaleVisibility.initialize(this.owner,this.layer,this.spatialIndex,this.graphicsCore,b);this.elevationAlignment&&
this.elevationAlignment.initialize(this.owner,function(b,c,d){return a._elevationChanged(b,c,d)},this.graphicsCore,b);this.labeling&&this.labeling.initialize(this.owner,this.layer,this.graphicsCore);this.graphicsCore.initialize(this.owner,this.layer,this.elevationAlignment,this.sharedResources,this.scaleVisibility,this.spatialIndex,this.labeling,function(){a.updateSuspendResumeExtent&&a._updateSuspendResumeExtent(a.updateSuspendResumeExtent())},function(b){return a.verticalScale?a.verticalScale.adjust(b):
b},b);this._handles.add([this.layer.watch("renderer",function(b){return a.graphicsCore.rendererChange(b)}),this.layer.watch("opacity",function(){return a.graphicsCore.opacityChange()})]);this._handles.add(this.layer.on("graphic-update",function(b){return a.graphicsCore.graphicUpdateHandler(b)}));this.owner.view.resourceController.registerIdleFrameWorker(this,{needsUpdate:this._needsIdleUpdate,idleFrame:this._idleUpdate});this.updateClippingExtent&&(this._handles.add(this.owner.view.watch("clippingArea",
function(){return a._updateClippingExtent()})),this._updateClippingExtent())};c.prototype.destroy=function(){this.owner&&this.owner.view.resourceController.deregisterIdleFrameWorker(this);this._handles&&(this._handles.destroy(),this._handles=null);this.frustumVisibility&&(this.frustumVisibility.destroy(),this.frustumVisibility=null);this.scaleVisibility&&(this.scaleVisibility.destroy(),this.scaleVisibility=null);this.elevationAlignment&&(this.elevationAlignment.destroy(),this.elevationAlignment=null);
this.labeling&&(this.labeling.destroy(),this.labeling=null);this.graphicsCore&&(this.graphicsCore.destroy(),this.graphicsCore=null);this.sharedResources&&(this.sharedResources.destroy(),this.sharedResources=null);this.owner=this.layer=null};c.prototype.canResume=function(){return(!this.frustumVisibility||this.frustumVisibility.canResume())&&(!this.scaleVisibility||this.scaleVisibility.canResume())};c.prototype._needsIdleUpdate=function(){return this.frustumVisibility&&this.frustumVisibility.needsIdleUpdate()||
this.scaleVisibility&&this.scaleVisibility.needsIdleUpdate()||this.elevationAlignment&&this.elevationAlignment.needsIdleUpdate()?!0:!1};c.prototype._idleUpdate=function(a){this.frustumVisibility&&this.frustumVisibility.idleUpdate(a);this.scaleVisibility&&this.scaleVisibility.idleUpdate(a);this.elevationAlignment&&this.elevationAlignment.idleUpdate(a)};c.prototype._updateSuspendResumeExtent=function(a){this.frustumVisibility&&this.frustumVisibility.setExtent(a);this.scaleVisibility&&this.scaleVisibility.setExtent(a)};
c.prototype._updateClippingExtent=function(){var a=this.owner.view.clippingArea;this.graphicsCore.setClippingExtent(a,this.owner.view.spatialReference)&&(this.updateClippingExtent(a)||this.graphicsCore.recreateAllGraphics())};c.prototype._elevationChanged=function(a,b,c){this.elevationChanged?this.elevationChanged(a,b,c):this.spatialIndex&&this.spatialIndex.intersects(a,b,c)};return c}()});