// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports"],function(r,s){return function(){function b(){this._scaleRangeActive=!1;this.layerScaleRangeVisibilityDirty=this.layerScaleRangeVisibility=!0;this.layerScaleRangeVisibilityQuery=!1;this.basemapTerrain=this.graphicsCore=this.extent=this.spatialIndex=this.layer=this.layerView=this.scaleChangeEventHandle=null}b.prototype.initialize=function(c,a,e,b,n){this.layerView=c;this.layer=a;this.spatialIndex=e;this.graphicsCore=b;this._scaleRangeActive=null!==a.minScale&&0<a.minScale&&
8E7>a.minScale||1E3<a.maxScale;this.basemapTerrain=n;this.layerMinMaxScaleChangeHandler()};b.prototype.destroy=function(){this.graphicsCore=this.spatialIndex=this.extent=this.layerView=null};b.prototype.needsIdleUpdate=function(){return this.layerView.view.basemapTerrain&&this.layerScaleRangeVisibilityDirty};b.prototype.canResume=function(){return this.layerScaleRangeVisibility};b.prototype.setExtent=function(c){this.extent=c;this.layerScaleRangeVisibilityDirty=!0};b.prototype.idleUpdate=function(c){this.layerView.view.basemapTerrain&&
(!c.done()&&this.layerScaleRangeVisibilityDirty)&&(this.updateSuspendScaleVisible(),this.layerScaleRangeVisibilityDirty=!1)};b.prototype.scaleRangeActive=function(){return this._scaleRangeActive};b.prototype.updateSuspendScaleVisibleFinish=function(c){this.layerScaleRangeVisibilityQuery=!1;this.layerScaleRangeVisibility!==c&&(this.layerScaleRangeVisibility=c,this.layerView._notifySuspendedChange())};b.prototype.updateSuspendScaleVisible=function(){var c=this,a=this.layerView.view.basemapTerrain;!this.extent||
!a||!this._scaleRangeActive?this.updateSuspendScaleVisibleFinish(!0):this.layerScaleRangeVisibilityQuery||(this.layerScaleRangeVisibilityQuery=!0,a.queryVisibleScaleRange(this.extent,this.layer.minScale,this.layer.maxScale,function(a){return c.updateSuspendScaleVisibleFinish(a)}))};b.prototype.visibleAtScale=function(c){var a=this.layer.minScale;return c>this.layer.maxScale&&(!a||c<a)};b.prototype.visibleAtScaleLabel=function(c,a){return c>a.maxScale&&(!a.minScale||c<a.minScale)};b.prototype.graphicVisible=
function(c,a){var b;a.centroid?b=a.centroid:"point"===c.geometry.type&&(b=c.geometry);return b?(b=this.layerView.view.basemapTerrain?this.layerView.view.basemapTerrain.getScale(b):1,this.visibleAtScale(b)):!0};b.prototype.updateGraphicScaleVisibility=function(c,a){if(this._scaleRangeActive&&a.addedToSpatialIndex){var b=this.graphicVisible(c,a);return a.setVisibilityFlag("VISIBILITY_SCALERANGE",b)}return!1};b.prototype.scaleUpdateHandler=function(b){var a=this;if(!this.layerView.suspended&&this.spatialIndex.hasGraphics()){var e=
b.extent,l=b.scale;this.spatialIndex.intersects(e,b.spatialReference,function(b,c){for(var p=a.visibleAtScale(l),m=!1,h=0;h<c;h++){var f=a.graphicsCore.getGraphics3DGraphicById(b[h]);if(f){var d=f.centroid;if(!d||!(e[0]>d.x||e[1]>d.y||e[2]<d.x||e[3]<d.y)){for(var d=f.setVisibilityFlag("VISIBILITY_SCALERANGE",p),k=0;k<f._labelGraphics.length;k++){var g=f._labelGraphics[k];if(g._labelClass&&null!=g._labelClass.minScale&&null!=g._labelClass.maxScale)var q=a.visibleAtScaleLabel(l,g._labelClass),d=d||
g.setVisibilityFlag("VISIBILITY_SCALERANGE_LABEL",q)}d&&a.layerView.view.labelManager.setDirty();d&&f.isDraped()&&(m=!0)}}}m&&a.layerView._notifyDrapedDataChange()})}this.layerScaleRangeVisibilityDirty=!0};b.prototype.layerMinMaxScaleChangeHandler=function(){var b=this,a=this.layer;(this._scaleRangeActive=null!==a.minScale&&0<a.minScale&&8E7>a.minScale||1E3<a.maxScale)&&!this.scaleChangeEventHandle?(this.scaleChangeEventHandle=this.basemapTerrain.on("scale-change",function(a){return b.scaleUpdateHandler(a)}),
this.layerView.suspended||this.spatialIndex.addGraphicsToSpatialIndex(this._scaleRangeActive)):!this._scaleRangeActive&&this.scaleChangeEventHandle&&(this.scaleChangeEventHandle.remove(),this.scaleChangeEventHandle=null);this.layerView.suspended||this.graphicsCore.updateAllGraphicsVisibility();this.layerScaleRangeVisibilityDirty=!0};return b}()});