// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../../core/declare dojo/_base/lang dojo/when ./Graphics3DSymbolLayer ./Graphics3DGraphicLayer ./Graphics3DDrapedGraphicLayer ./ElevationAligners ./Graphics3DSymbolCommonCode ./SignedDistanceFunctions ../../../../core/urlUtils ../../../../core/screenUtils ../../../../config ../../../../Color ../../../../geometry/Polygon ../../support/projectionUtils ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/lib/Texture ../../webgl-engine/materials/HUDMaterial".split(" "),
function(n,E,u,F,G,H,v,k,l,w,r,x,I,J,K,y,p,L,z,M,N,A){function s(a){return"cross"===a||"x"===a}function O(a){var b,f=t,c=f*B;"primitive:"===a.substring(0,10)&&(a=a.substring(10));switch(a){case m.PRIM_CIRCLE:b=l.computeSignedDistancefieldCicle(f,c);break;case m.PRIM_SQUARE:b=l.computeSignedDistancefieldSquare(f,c,!1);break;case m.PRIM_KITE:b=l.computeSignedDistancefieldSquare(f,c,!0);break;case m.PRIM_CROSS:b=l.computeSignedDistancefieldCrossAndX(f,c,!1);break;case m.PRIM_X:b=l.computeSignedDistancefieldCrossAndX(f,
c,!0)}return new N(b,"sdf_"+a,{mipmap:!1,wrapClamp:!0,width:t,height:t,components:4})}var P=y.vec3d,Q=y.mat4d.identity(),C=[0,0,1],R=[0,0,0,0],D="center bottom top left right bottom-left bottom-right top-left top-right".split(" "),t=128,B=0.5,m={PRIM_CIRCLE:"circle",PRIM_SQUARE:"square",PRIM_CROSS:"cross",PRIM_X:"x",PRIM_KITE:"kite"};n=n([F],{_prepareResources:function(){var a=this.symbol,b=null!=a.size?r.pt2px(a.size):16;this._size=null;this._symbolTextureRatio=1;this._primitive=null;var f=this._getStageIdHint();
this._isPropertyDriven("size")&&64>b&&(b=64);var c=a.resource||{primitive:"circle"},e={anchorPos:this._getAnchorPos(a)},d=c.href||c.dataURI;d?(e.color=this._getFillColor(a,null),e.outlineColor=this._getOutlineColor(a),e.outlineSize=this._getOutlineSize(a,null),e.textureIsSignedDistanceField=!1,this._prepareImageResources(d,b,e,f)):(c=c.primitive||"circle",d="primitive:"+c,this._primitive=c,e.color=this._getFillColor(a,c),e.outlineColor=this._getOutlineColor(a),e.outlineSize=this._getOutlineSize(a,
c),s(c)&&0===e.outlineSize?this.reject():(this.texture=this._context.sharedResources.textures.acquire(d,O),this._textureURI=d,e.textureIsSignedDistanceField=!0,e.textureId=this.texture.getId(),this._createMaterialsAndAddToStage(e,this._context.stage,f),this._size=[b,b],this._symbolTextureRatio=1/B,this.resolve()))},_getOutlineDefaultSize:function(a){return s(a)?1.5:0},_getOutlineSize:function(a,b){return a.outline?null!=a.outline.size?r.pt2px(a.outline.size):this._getOutlineDefaultSize(b):this._getOutlineDefaultSize(b)},
_getOutlineColor:function(a){var b=this._getLayerOpacity();if(a.outline&&null!=a.outline.color){var f=I.toUnitRGB(a.outline.color);return[f[0],f[1],f[2],a.outline.color.a*b]}return[0,0,0,b]},_getFillColor:function(a,b){return s(b)?R:this._getMaterialOpacityAndColor()},_getAnchorPos:function(a){return-1<D.indexOf(a.anchor)?a.anchor:"center"},_prepareImageResources:function(a,b,f,c){0===a.indexOf("http")&&"https:"===location.protocol&&(a=a.replace(/^http:/i,"https:"));var e=function(a){if(!this.isRejected()){var d=
a.params,e=d.width/d.height;this._size=b?1<e?[b,b/e]:[b*e,b]:[d.width,d.height];f.textureId=a.getId();this._createMaterialsAndAddToStage(f,this._context.stage,c);this.resolve()}}.bind(this),d="data:image/svg"===a.substring(0,14),g=".svg"===a.substring(a.length-4,a.length);if(!d&&!g)u(this._context.sharedResources.textures.acquire(a),e,function(){this.reject()}.bind(this)),this._textureURI=a;else{0===a.indexOf("//")&&(a=window.location.protocol+a);var h=new Image,g=!d&&w.hasSameOrigin(a,window.location.href);
d||(g||w.canUseXhr(a)?g||(h.crossOrigin="anonymous"):x.request.proxyUrl&&(a=x.request.proxyUrl+"?"+a));h.src=a;h.onerror=function(){this.reject()}.bind(this);h.onload=function(){var a=h.width,c=h.height,d=1;a&&c&&(d=a/c);null!=b&&(1<d?(a=b,c=Math.round(b/d)):(c=b,a=Math.round(b*d)));d=document.createElement("canvas");d.width=a;d.height=c;d.getContext("2d").drawImage(h,0,0,a,c);a=d.toDataURL();u(this._context.sharedResources.textures.acquire(a),e,function(){this.reject()});this.textureURI=a}.bind(this);
h.onerror=function(){console.warn("Failed to create Icon primitive");this.reject()}.bind(this)}},_createMaterialsAndAddToStage:function(a,b,f){var c=E.clone(a);c.occlusionTest=!1;c.shaderPolygonOffset=0;this._drapedMaterial=new A(c,f+"_iconDraped");b.add(p.ModelContentType.MATERIAL,this._drapedMaterial);a.occlusionTest=!0;this._material=new A(a,f+"_icon");b.add(p.ModelContentType.MATERIAL,this._material)},destroy:function(){this.isFulfilled()||this.reject();this._material&&(this._context.stage.remove(p.ModelContentType.MATERIAL,
this._material.getId()),this._material=null);this._drapedMaterial&&(this._context.stage.remove(p.ModelContentType.MATERIAL,this._drapedMaterial.getId()),this._drapedMaterial=null);this._textureURI&&(this._context.sharedResources.textures.release(this._textureURI),this._textureURI=null)},createGraphics3DGraphic:function(a,b,f){var c=a.geometry;"extent"===c.type&&(c=J.fromExtent(c));if("polyline"===c.type)c=k.placePointOnPolyline(c);else if("polygon"===c.type)c=k.placePointOnPolygon(c);else if("point"!==
c.type)return this._logWarning("unsupported geometry type for icon symbol: "+c.type),null;var e="graphic"+a.id,d=1;if(this._isPropertyDriven("size")&&b.size){for(var g=0;3>g;g++)b.size[g]&&(b.size[g]=r.pt2px(b.size[g]));g=this._size[0]>this._size[1]?this._size[0]:this._size[1];isFinite(b.size[0])?d=b.size[0]/g:"symbolValue"===b.size[0]?d=1:isFinite(b.size[2])&&(d=b.size[2]/g)}b=this._getVertexOpacityAndColor(b);d*=this._symbolTextureRatio;d=[this._size[0]*d,this._size[1]*d];g=this._getGraphicElevationInfo(a);
return g.mode===k.ELEV_MODES.ON_THE_GROUND?this._createAsOverlay(a,c,b,d,g,e,a.id,f):this._createAs3DShape(a,c,b,d,g,e,a.id,f)},layerPropertyChanged:function(a,b,f){if("opacity"===a)return b=this._getFillColor(this.symbol,this._primitive),this._drapedMaterial.setParameterValues({color:b}),this._material.setParameterValues({color:b}),b=this._getOutlineColor(this.symbol),this._drapedMaterial.setParameterValues({outlineColor:b}),this._material.setParameterValues({outlineColor:b}),!0;if("elevationInfo"===
a){var c=this._elevationInfo.mode;this._updateElevationInfo();a=this._elevationInfo.mode;var e=k.ELEV_MODES;if(c===e.ON_THE_GROUND&&a===e.ON_THE_GROUND)return!0;if(c!==a&&(c===e.ON_THE_GROUND||a===e.ON_THE_GROUND))return!1;var c=this._context.elevationProvider,d=this._context.renderCoordsHelper,g=v.perObjectElevationAligner,h;for(h in b){var q=b[h],l=q._graphics[f];l&&(q=this._getGraphicElevationInfo(q.graphic),l.elevationAligner=a===e.RELATIVE_TO_GROUND?g:null,l.elevationInfo.set(q),g(l,c,d))}return!0}return!1},
setDrawOrder:function(a,b,f){this._drapedMaterial&&(this._drapedMaterial.setRenderPriority(a),f[this._drapedMaterial.getId()]=!0)},_defaultElevationInfoNoZ:{mode:k.ELEV_MODES.RELATIVE_TO_GROUND,offset:0},_getGraphicElevationInfo:function(a){var b=this.inherited(arguments);b.mode===k.ELEV_MODES.RELATIVE_TO_GROUND&&(0===b.offset&&!a.geometry.get("hasZ"))&&(b.offset=1/this._context.renderCoordsHelper.unitInMeters);return b},_createAs3DShape:function(a,b,f,c,e,d,g){a=z.createPointGeometry(C,null,f,c);
a=[new L(a,d)];d=k.createStageObjectForPoint.call(this,b,a,[[this._material]],null,null,e,d,this._context.layer.id,g);if(null===d)return null;g=null;e.mode===k.ELEV_MODES.RELATIVE_TO_GROUND&&(g=v.perObjectElevationAligner);e=new G(this,d,a,null,null,g,e);e.getScreenSize=function(a,b){return function(){return[a,b]}}(c[0]/this._symbolTextureRatio,c[1]/this._symbolTextureRatio);k.extendPointGraphicElevationInfo(e,b,this._context.elevationProvider);return e},_createAsOverlay:function(a,b,f,c,e,d,g){this._drapedMaterial.setRenderPriority(this._symbolLayerOrder);
a=P.create();K.pointToVector(b,a,this._context.overlaySR);a[2]=this._getDrapedZ();if((b=this._context.clippingExtent)&&!k.pointInBox2D(a,b))return null;f=z.createPointGeometry(C,a,f,c,!0);b=new M(f);b.material=this._drapedMaterial;b.center=a;b.bsRadius=0;b.transformation=Q;b.name=d;b.uniqueName=d+"#"+f.id;d=new H(this,[b],null,null);d.getScreenSize=function(a,b){return function(){return[a,b]}}(c[0]/this._symbolTextureRatio,c[1]/this._symbolTextureRatio);return d}});n.VALID_ANCHOR_STRINGS=D;return n});