// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/watchUtils ../../../../core/arrayUtils ../../support/projectionUtils ../../../../geometry/Point ../../../../geometry/Extent ../../webgl-engine/Stage ../../webgl-engine/lib/Util ../../webgl-engine/lib/Layer ../../webgl-engine/lib/FloatingBoxLocalOriginFactory ../../lib/glMatrix ../graphics/SymbolConverter ../graphics/Graphics3DGraphic ../graphics/Graphics3DSymbol ../graphics/graphicUtils ../../../../core/Error ../../support/aaBoundingBox ../../support/mathUtils ../../../../core/promiseUtils dojo/Deferred".split(" "),
function(v,M,r,C,p,D,E,s,w,x,F,y,z,G,H,I,A,B,n,J,K){v=y.vec3d;var q=new D,t=v.create(),L=function(){return function(){this.localOriginFactory=this.layer=this.overlaySR=this.renderCoordsHelper=this.renderSpatialReference=this.clippingExtent=this.layerOrder=this.stage=this.renderer=this.elevationProvider=this.streamDataSupplier=this.sharedResources=null}}();return function(){function c(){this.graphics={};this.graphicsDrapedIds={};this.graphicsBySymbol={};this.graphicsKeys=[];this.symbols={};this.computedExtent=
null;this.symbolCreationContext=new L;this.hasDraped=!1;this.updatingGraphicIds={};this.graphicTransformFunc=this.onComputedExtentChange=this.stage=this.labelStageLayer=this.stageLayer=this.tilingSchemeHandle=null;this.eventHandles=[];this.labeling=this.spatialIndex=this.scaleVisibility=this.elevation=this.layer=this.layerView=this.viewSR=null;this.whenGraphics3DGraphicRequests={}}c.prototype.initialize=function(a,b,d,h,f,e,c,g,l,u){var m=this;this.layerView=a;this.layer=b;this.viewSR=a.view.spatialReference;
this.elevation=d;this.scaleVisibility=f;this.spatialIndex=e;this.labeling=c;this.onComputedExtentChange=g;this.graphicTransformFunc=l;this.initializeStage(this.layerView.view,this.layer.id);this.symbolCreationContext.sharedResources=h;this.symbolCreationContext.renderer=this.layer.renderer;this.symbolCreationContext.stage=this.stage;this.symbolCreationContext.streamDataSupplier=h.streamDataSupplier;this.symbolCreationContext.renderSpatialReference=this.layerView.view.renderSpatialReference;this.symbolCreationContext.renderCoordsHelper=
this.layerView.view.renderCoordsHelper;this.symbolCreationContext.layer=this.layer;this.symbolCreationContext.layerOrder=0;this.symbolCreationContext.localOriginFactory=new F(5E6,16);this.symbolCreationContext.elevationProvider=u;this.tilingSchemeHandle=r.when(u,"tilingScheme",function(a){a.spatialReference.equals(m.symbolCreationContext.overlaySR)||(m.symbolCreationContext.overlaySR=u.spatialReference,m.recreateAllGraphics())});this.eventHandles.push(this.layerView.watch("suspended",function(){return m.suspendedChange()}));
this.eventHandles.push(r.on(a,"loadedGraphics","change",function(a){return m.graphicsCollectionChanged(a)},function(){m.clearSymbolsAndGraphics();m.graphicsCollectionChanged({added:m.layerView.loadedGraphics.toArray(),removed:[]})}))};c.prototype.destroy=function(){var a=this;this.clear();if(this.stage){var b=[this.stageLayer.getId()];this.labelStageLayer&&b.push(this.labelStageLayer.getId());this.stage.removeFromViewContent(b);b.forEach(function(b){return a.stage.remove(s.ModelContentType.LAYER,
b)});this.stage=this.labelStageLayer=this.stageLayer=null}this.tilingSchemeHandle&&(this.tilingSchemeHandle.remove(),this.tilingSchemeHandle=null);this.eventHandles.forEach(function(a){return a.remove()});this.layerView=this.labeling=this.scaleVisibility=this.viewSR=this.onComputedExtentChange=this.eventHandles=null;for(var d in this.whenGraphics3DGraphicRequests)this.whenGraphics3DGraphicRequests[d].reject(new A("graphic:layer-destroyed","Layer has been destroyed"));this.whenGraphics3DGraphicRequests=
null};c.prototype.clear=function(){var a=!1,b;for(b in this.graphics)a=a||this.graphics[b].isDraped(),this.graphics[b].destroy();this.graphics={};this.graphicsKeys=null;for(var d in this.symbols)this.symbols[d].destroy();this.symbols={};this.graphicsBySymbol={};this.hasDraped=!1;a&&this.layerView._notifyDrapedDataChange()};c.prototype.initializeStage=function(a,b){this.stage=a._stage;this.stageLayer=new x(b,{state:this.layerView.suspended?"HIDDEN":"VISIBLE"},b);this.stage.add(s.ModelContentType.LAYER,
this.stageLayer);var d=[this.stageLayer.getId()];this.labeling&&(this.labelStageLayer=new x(b,{state:this.layerView.suspended?"HIDDEN":"IGNORED"},b+"_labels"),this.stage.add(s.ModelContentType.LAYER,this.labelStageLayer),d.push(this.labelStageLayer.getId()));this.stage.addToViewContent(d)};c.prototype.setDrawingOrder=function(a){this.symbolCreationContext.layerOrder=a;var b={},d={},h;for(h in this.graphics)this.graphics[h].setDrawOrder(a,b,d);for(var f in d)this.symbols[f].setDrawOrder(a,b);w.objectEmpty(b)||
(this.stage.getTextureGraphicsRenderer().updateRenderOrder(b),this.layerView._notifyDrapedDataChange())};c.prototype.suspendedChange=function(){!0===this.layerView.suspended?(this.stageLayer.setState("HIDDEN"),this.labelStageLayer&&this.labelStageLayer.setState("HIDDEN"),this.hideAllGraphics()):!1===this.layerView.suspended&&(this.stageLayer.setState("VISIBLE"),this.labelStageLayer&&this.labelStageLayer.setState("IGNORED"),this.updateAllGraphicsVisibility())};c.prototype.getGraphics3DGraphics=function(){return this.graphics};
c.prototype.getGraphics3DGraphicById=function(a){return this.graphics[a]};c.prototype.getGraphics3DGraphicsKeys=function(){null===this.graphicsKeys&&(this.graphicsKeys=Object.keys(this.graphics));return this.graphicsKeys};c.prototype.numNodesUpdating=function(){return Object.keys(this.updatingGraphicIds).length};c.prototype.whenGraphics3DGraphic=function(a){var b=this.graphics[a.id];if(b)return J.resolve(b);b=this.whenGraphics3DGraphicRequests[a.id];b||(b=new K,this.whenGraphics3DGraphicRequests[a.id]=
b);return b};c.prototype.boundsForGraphics3DGraphic=function(a,b){void 0===b&&(b=B.create());var d=this.layerView.view.spatialReference,h=this.layerView.view.renderSpatialReference,f=this.layerView.view.basemapTerrain.spatialReference,e=a.getProjectedBoundingBox(function(a,b,c){return p.bufferToBuffer(a,h,b,a,d,b,c)},function(a,b,h){return p.bufferToBuffer(a,f,b,a,d,b,h)},b);if(!e)return null;var c=a.isDraped(),g=this.symbolCreationContext.elevationProvider;c&&g&&(B.center(e,t),q.x=t[0],q.y=t[1],
q.z=void 0,q.spatialReference=d,c=g.getElevation(q)||0,e[2]=Math.min(e[2],c),e[5]=Math.max(e[5],c));return e};c.prototype.whenGraphicBounds=function(a){var b=this;return r.whenOnce(this.layerView,"loadedGraphics").then(function(){if(b.layerView.loadedGraphics.some(function(b){return b===a}))return b.whenGraphics3DGraphic(a);throw new A("internal:graphic-not-part-of-view","Graphic is not part of this view");}).then(function(a){return b.boundsForGraphics3DGraphic(a)})};c.prototype.graphicsCollectionChanged=
function(a){var b=this.graphicTransformFunc?this.graphicTransformFunc(a.added):a.added;this.add(b);this.remove(a.removed)};c.prototype.graphicUpdateHandler=function(a){var b=this.graphics[a.graphic.id];if(b)switch(a.property){case "visible":b.setVisibilityFlag("VISIBILITY_GRAPHIC",a.newValue)&&(b.isDraped()&&this.layerView._notifyDrapedDataChange(),this.labeling&&this.layerView.view.labelManager.setDirty())}};c.prototype.beginGraphicUpdate=function(a){this.updatingGraphicIds[a.id]=!0;this.layerView.get("symbols-updating")||
this.layerView.set("symbols-updating",!0);this.layerView._evaluateUpdatingState()};c.prototype.endGraphicUpdate=function(a){a&&delete this.updatingGraphicIds[a.id];this.layerView.get("symbols-updating")&&w.objectEmpty(this.updatingGraphicIds)&&(this.layerView.view.flushDisplayModifications(),this.layerView.set("symbols-updating",!1));this.layerView._evaluateUpdatingState()};c.prototype.expandComputedExtent=function(a){var b,d,h,f,e,k;if("point"===a.type)b=d=a.x,h=f=a.y,a.z&&(e=k=a.z);else if("polygon"===
a.type){k=a.extent;if(!k)return;b=k.xmin;d=k.xmax;h=k.ymin;f=k.ymax;e=k.zmin;k=k.zmax}var g=this.viewSR,l=c.tmpVec;!a.spatialReference.equals(g)&&p.xyzToVector(b,h,0,a.spatialReference,l,g)&&(b=l[0],h=l[1],p.xyzToVector(d,f,0,a.spatialReference,l,g),d=l[0],f=l[1]);n.isFinite(b)&&(n.isFinite(d)&&n.isFinite(h)&&n.isFinite(f))&&((g=this.computedExtent)?(g.xmin=Math.min(b,g.xmin),g.xmax=Math.max(d,g.xmax),g.ymin=Math.min(h,g.ymin),g.ymax=Math.max(f,g.ymax)):this.computedExtent=g=new E(b,h,d,f,a.spatialReference),
n.isFinite(e)&&!n.isFinite(k)&&(g.zmin=null!=g.zmin?Math.min(e,g.zmin):e,g.zmax=null!=g.zmax?Math.max(k,g.zmax):k),this.onComputedExtentChange&&this.onComputedExtentChange())};c.prototype.updateHasDraped=function(){this.hasDraped=!1;for(var a in this.graphicsDrapedIds)if(this.graphicsDrapedIds.hasOwnProperty(a)){this.hasDraped=!0;break}};c.prototype.elevationInfoChange=function(){this.labeling&&this.labeling.elevationInfoChange();for(var a in this.graphicsBySymbol){var b=this.graphicsBySymbol[a];
if(this.symbols[a].layerPropertyChanged("elevationInfo",b))for(var d in b)for(var h=b[d],c=h.graphic,h=h._labelGraphics,e=0;e<h.length;e++){var k=h[e];k.graphics3DSymbolLayer.updateGraphicElevationInfo(c,k)}else this.recreateSymbol(a)}};c.prototype.clearSymbolsAndGraphics=function(){this.clear();this.elevation&&this.elevation.clear();this.labeling&&this.labeling.clear()};c.prototype.recreateAllGraphics=function(){this.clearSymbolsAndGraphics();this.computedExtent=null;this.onComputedExtentChange&&
this.onComputedExtentChange();this.layerView.loadedGraphics&&this.layerView.view.basemapTerrain.tilingScheme&&this.add(this.layerView.loadedGraphics.toArray())};c.prototype.recreateSymbol=function(a){var b=this.graphicsBySymbol[a],d=[],h=!1,c;for(c in b){var e=b[c];e.isDraped()&&(delete this.graphicsDrapedIds[c],h=!0);d.push(e.graphic);e.destroy();this.graphics[c]=null}this.graphicsBySymbol[a]={};this.symbols[a].destroy();this.symbols[a]=null;this.updateHasDraped();h&&this.layerView._notifyDrapedDataChange();
this.add(d)};c.prototype.add=function(a){if(this.layerView.view.basemapTerrain.tilingScheme){for(var b=a.length,d=Array(b),c=Array(b),f=Array(b),e=0;e<b;e++){var k=a[e],g=k.geometry;if(g&&(this.expandComputedExtent(g),(g=this.layerView.getRenderingInfo?this.layerView.getRenderingInfo(k):{symbol:k.symbol})&&g.symbol))if(c[e]=g.symbol,f[e]=g,g=this.getOrCreateGraphics3DSymbol(c[e],g.renderer))d[e]=g,this.beginGraphicUpdate(k)}for(e=0;e<b;e++)this.waitForSymbol(d[e],c[e],a[e],f[e])}};c.prototype.waitForSymbol=
function(a,b,d,c){var f=this;a&&a.then(function(){f.graphicsBySymbol[b.id]||(f.graphicsBySymbol[b.id]={});f.createGraphics3DGraphic(a,d,c);f.endGraphicUpdate(d);f.labeling&&f.layerView.view.labelManager.setDirty()},function(){f.endGraphicUpdate(d)})};c.prototype.remove=function(a){for(var b=!1,d=a.length,c=0;c<d;c++){var f=a[c].id,e=this.graphics[f];if(e){e.isDraped()&&(delete this.graphicsDrapedIds[f],b=!0);var k=e.graphics3DSymbol.symbol.id;e.destroy();delete this.graphics[f];delete this.graphicsBySymbol[k][f];
this.graphicsKeys=null}}this.updateHasDraped();b&&this.layerView._notifyDrapedDataChange();this.labeling&&this.layerView.view.labelManager.setDirty()};c.prototype.getOrCreateGraphics3DSymbol=function(a,b){var d=this.symbols[a.id];if(!d){var c=z.toWeb3DSymbol(a,!0,!1);if(c){d=void 0;if(b&&b.backgroundFillSymbol){var f=z.toWeb3DSymbol(b.backgroundFillSymbol,!1,!0);f&&(d=f.symbolLayers)}d=new H(c,this.symbolCreationContext,d);this.symbols[a.id]=d}}return d};c.prototype.createGraphics3DGraphic=function(a,
b,d){if(!this.graphics[b.id]&&(d=a.createGraphics3DGraphic(b,d),this.labeling&&this.labeling.layerLabelsEnabled()&&(d=this.labeling.createLabelsForGraphic(b,d)),this.graphics[b.id]=d,this.graphicsKeys=null,this.graphicsBySymbol[a.symbol.id][b.id]=d,d.initialize(this.stageLayer,this.labelStageLayer,this.stage),d.isDraped()&&(this.hasDraped=this.graphicsDrapedIds[b.id]=!0,this.layerView._notifyDrapedDataChange()),d.centroid=null,"point"!==b.geometry.type&&d instanceof G&&(d.centroid=I.computeCentroid(b.geometry,
this.viewSR)),a=this.scaleVisibility&&this.scaleVisibility.scaleRangeActive(),this.spatialIndex&&this.spatialIndex.shouldAddToSpatialIndex(b,d,a)&&this.spatialIndex.addGraphicToSpatialIndex(b,d),a&&this.scaleVisibility.updateGraphicScaleVisibility(b,d),d.setVisibilityFlag("VISIBILITY_GRAPHIC",b.visible&&!this.layerView.suspended),a=this.whenGraphics3DGraphicRequests[b.id]))a.resolve(d),delete this.whenGraphics3DGraphicRequests[b.id]};c.prototype.rendererChange=function(a){this.symbolCreationContext.renderer=
a;this.recreateAllGraphics()};c.prototype.opacityChange=function(){var a=!1,b;for(b in this.graphicsBySymbol){var d=this.graphicsBySymbol[b];this.symbols[b].layerPropertyChanged("opacity");if(!a)for(var c in d)if(d[c].isDraped()){this.layerView._notifyDrapedDataChange();a=!0;break}}};c.prototype.setClippingExtent=function(a,b){var d=this.symbolCreationContext.clippingExtent,c=[];p.extentToBoundingRect(a,c,b)?this.symbolCreationContext.clippingExtent=[c[0],c[1],-Infinity,c[2],c[3],Infinity]:this.symbolCreationContext.clippingExtent=
null;return!C.equals(this.symbolCreationContext.clippingExtent,d)};c.prototype.updateAllGraphicsVisibility=function(){var a=this;if(this.layerView.loadedGraphics){var b=!1;this.layerView.loadedGraphics.forEach(function(d){var c=a.getGraphics3DGraphicById(d.id);if(c){var f=c.setVisibilityFlag("VISIBILITY_GRAPHIC",d.visible);a.scaleVisibility&&(d=a.scaleVisibility.updateGraphicScaleVisibility(d,c),f=f||d);f&&c.isDraped()&&(b=!0)}});b&&this.layerView._notifyDrapedDataChange();this.layerView.view.labelManager.setDirty()}};
c.prototype.hideAllGraphics=function(){var a=this;if(this.layerView.loadedGraphics){var b=!1;this.layerView.loadedGraphics.forEach(function(c){(c=a.getGraphics3DGraphicById(c.id))&&c.setVisibilityFlag("VISIBILITY_GRAPHIC",!1)&&c.isDraped()&&(b=!0)});b&&this.layerView._notifyDrapedDataChange();this.layerView.view.labelManager.setDirty()}};c.tmpVec=y.vec3d.create();return c}()});