// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../../core/declare ../../../../core/Logger dojo/_base/lang ../../support/PromiseLightweight ./ElevationInfo ../../../../Color".split(" "),function(k,l,h,m,g,n){var f=new g,p=l.getLogger("esri.symbols.Symbol3D");return k([m.Promise],{constructor:function(a,b,d){this.symbol=a;this._context=b;this._symbolLayerOrder=b.layerOrder;this._symbolLayerOrderDelta=b.layerOrderDelta;this._elevationInfo=new g;this._updateDrivenProperties(d);this._updateElevationInfo();this._prepareResources()},_logWarning:function(a){p.warn(a)},
_prepareResources:function(a){throw Error("This is an abstract base class");},_defaultElevationInfoNoZ:{mode:g.MODES.ON_THE_GROUND,offset:0},_defaultElevationInfoZ:{mode:g.MODES.ABSOLUTE_HEIGHT,offset:0},_updateElevationInfo:function(){for(var a in this._elevationInfo)this._elevationInfo[a]=void 0;if(a=this._context.layer.elevationInfo)this._elevationInfo=h.mixin(this._elevationInfo,a);this.symbol.elevationInfo&&(this._elevationInfo=h.mixin(this._elevationInfo,this.symbol.elevationInfo))},_getGraphicElevationInfo:function(a){a=
a.geometry.hasZ?this._defaultElevationInfoZ:this._defaultElevationInfoNoZ;f.mode=this._elevationInfo.mode||a.mode;f.offset=null!=this._elevationInfo.offset?this._elevationInfo.offset:a.offset;f.featureExpression=this._elevationInfo.featureExpression;f.offset/=this._context.renderCoordsHelper.unitInMeters;return f},_getDrapedZ:function(){return-2},_updateDrivenProperties:function(a){var b={color:!1,opacity:!1,size:!1};if(!a&&(a=this._context.renderer))b.color=!!a.colorInfo,b.size=!!a.sizeInfo,a.visualVariables&&
a.visualVariables.forEach(function(a){switch(a.type){case "color":var c,e;b.color=!0;if(a.colors)for(c=0;c<a.colors.length;c++)if((e=a.colors[c])&&(Array.isArray(e)&&3<e.length&&255!==e[3]||void 0!==e.a&&255!==e.a))b.opacity=!0;if(a.stops)for(c=0;c<a.stops.length;c++)if((e=a.stops[c].color)&&(Array.isArray(e)&&3<e.length&&255!==e[3]||void 0!==e.a&&255!==e.a))b.opacity=!0;break;case "opacity":case "transparencyInfo":b.opacity=!0;break;case "size":b.size=!0}});this._drivenProperties=b},_isPropertyDriven:function(a){return this._drivenProperties[a]},
_getLayerOpacity:function(){var a=this._context.layer.opacity;return null!=a?a:1},_getMaterialOpacity:function(){var a;a=1*this._getLayerOpacity();var b=this.symbol.material;b&&!this._isPropertyDriven("opacity")&&(a*=b.color.a);return a},_getMaterialOpacityAndColor:function(){var a=this.symbol.material,b=this._getMaterialOpacity(),a=this._isPropertyDriven("color")||!a?null:n.toUnitRGB(a.color);return this._mixinColorAndOpacity(a,b)},_getVertexOpacityAndColor:function(a,b,d){var c=this._isPropertyDriven("color")?
a.color:null;a=this._isPropertyDriven("opacity")?a.opacity:null;c=this._mixinColorAndOpacity(c,a);d&&(c[0]*=d,c[1]*=d,c[2]*=d,c[3]*=d);return b?new b(c):c},_mixinColorAndOpacity:function(a,b){var d=[1,1,1,1];null!=a&&(d[0]=a[0],d[1]=a[1],d[2]=a[2]);null!=b?d[3]=b:null!=a&&3<a.length&&(d[3]=a[3]);return d},_getStageIdHint:function(){return this._context.layer.id+"_symbol"},setDrawOrder:function(a,b,d){this._material&&(this._material.setRenderPriority(a),d[this._material.getId()]=!0)},createGraphics3DGraphic:function(a,
b){throw Error("This is an abstract base class");},destroy:function(){throw Error("This is an abstract base class");}})});