// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang ../../../../symbols/Font ../../../../symbols/SimpleLineSymbol ../../../../symbols/SimpleMarkerSymbol ../../../../symbols/PictureMarkerSymbol ../../../../symbols/SimpleFillSymbol ../../../../symbols/TextSymbol ../../../../symbols/Symbol3D ../../../../symbols/Symbol ../../../../symbols/LineSymbol3D ../../../../symbols/PointSymbol3D ../../../../symbols/PolygonSymbol3D ../../../../symbols/LabelSymbol3D ../../../../renderers/support/jsonUtils".split(" "),function(l,q,r,d,m,s,t,
n,u,v,w,x,y,z){function h(a){return a.toRgb().map(function(a){return a})}function k(a){return Math.round(100*(1-a.a))}var p=function(a,A,e){var b;if(a instanceof r)b=v.fromJSON({symbolLayers:[{type:"Line",enable:!0,size:a.width||1,material:{color:a.color?h(a.color):[255,255,255],transparency:a.color?k(a.color):100}}]});else if(a instanceof m||a instanceof d){b=a.color?h(a.color):[255,255,255];var g=null==a.color?100:k(a.color),f,c;a instanceof m?(a.color&&0===a.color.r+a.color.g+a.color.b&&(b=[255,
255,255]),f=a.source.imageData&&a.source.contentType?{dataURI:"data:"+a.source.contentType+";base64,"+a.source.imageData}:"data:"===a.url.substring(0,5)?{dataURI:a.url}:{href:a.url},c=a.width):(f=a.style,c={},c[d.STYLE_CIRCLE]="circle",c[d.STYLE_CROSS]="cross",c[d.STYLE_DIAMOND]="kite",c[d.STYLE_SQUARE]="square",c[d.STYLE_X]="x",f in c?f=c[f]:(console.log(f+' cannot be mapped to Icon symbol. Fallback to "circle"'),f="circle"),f={primitive:f},c=a.size);b={type:"Icon",enable:!0,size:c,screenOffset:[a.xoffset,
a.yoffset],resource:f,material:{color:b,transparency:g}};a.outline&&(a.outline.color&&0<a.outline.width)&&(b.outline={size:a.outline.width,color:h(a.outline.color),transparency:k(a.outline.color)});b=w.fromJSON({symbolLayers:[b]})}else if(a instanceof s)b={symbolLayers:[{type:"Fill",enable:!0,material:{color:a.color?h(a.color):[255,255,255],transparency:a.color?k(a.color):100}}]},b=x.fromJSON(b),a.outline&&a.outline.color&&(b.symbolLayers.getItemAt(0).outline={size:a.outline.width||0,color:a.outline.color});
else if(a instanceof t){switch(a.verticalAlignment){case "top":b="top";break;case "middle":b="center";break;case "bottom":b="bottom";break;default:b="center"}switch(a.horizontalAlignment){case "left":b+="Left";break;case "center":b+="Center";break;case "right":b+="Right";break;default:b+="Center"}g=l.clone(q.defaultProps);a.font&&l.mixin(g,a.font);b=y.fromJSON({symbolLayers:[{type:"Text",enable:!0,size:g.size,font:{family:g.family,weight:g.weight,style:g.style},material:{color:h(a.color)},placement:b,
screenOffset:[a.xoffset,a.yoffset],text:a.text}]})}else a instanceof n?b=a:console.warn("SymbolConverter: don't know how to convert symbol of type '%s'",a.type||a.declaredClass);A&&b&&(b.id=a.id);if(e&&b)for(a=0;a<b.symbolLayers.length;++a)b.symbolLayers.getItemAt(a)._ignoreDrivers=!0;return b};return{toWeb3DSymbol:p,toWeb3DRenderer:function(a){function d(a){return a instanceof u&&!(a instanceof n)?p(a,!1,!1):a}var e=z.fromJSON(a.toJSON());e.defaultSymbol=d(e.defaultSymbol);e.symbol=d(e.symbol);var b=
e.classBreakInfos||e.uniqueValueInfos;Array.isArray(b)&&b.forEach(function(a){a.symbol=d(a.symbol)});"undefined"!==typeof a.isMaxInclusive&&(e.isMaxInclusive=a.isMaxInclusive);return e}}});