// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/sniff ../lib/glMatrix ../../../core/watchUtils ../webgl-engine/lib/Util ./NavigationConstants".split(" "),function(C,O,P,Q,R,t){var n=function(k,r){function v(a){if(!p||a.isPrimary)if(a.preventDefault(),0!==e&&!(void 0===a.originalTouchEvent&&void 0!==typeof a.movementX&&void 0!==typeof a.movementY&&0===a.movementX&&0===a.movementY)){var b=s(a,w),c=e-1;switch(l){case 1:h("mouseDragLeft",b,c);break;case 2:h("mouseDragMiddle",b,c);break;case 3:case 0:h("mouseDragRight",
b,c)}1===e&&!(0===Math.abs(b[0]-z[0])&&0===Math.abs(b[1]-z[1]))?e=2:3===e&&(u&&window.clearTimeout(u),l=e=0,A(a))}}function D(a){if(!p||a.isPrimary)a.preventDefault(),d.focus(),z=s(a),u&&window.clearTimeout(u),c.stop(),e=1,l=a.which,1===l&&(0<m?(h("mouseClickDouble",s(a,w),2),m=0):m=Date.now()),p?(d.setPointerCapture(a.pointerId),d.addEventListener(g.move,v,!0),d.addEventListener(g.up,x,!0)):(document.addEventListener(g.move,v,!0),document.addEventListener(g.up,x,!0))}function x(a){if(!p||a.isPrimary){a.preventDefault();
var b=s(a,w);1===e&&1===l?0<m&&setTimeout(function(){0<m&&(h("mouseClick",s(a,w)),m=0)},Math.max(S-(Date.now()-m),0)):m=0;2===e?(e=3,u=setTimeout(function(){if(3===e)switch(l){case 1:h("mouseDragLeft",b,2);break;case 2:h("mouseDragMiddle",b,2);break;case 3:case 0:h("mouseDragRight",b,2)}A(a);l=e=0},T)):(A(a),l=e=0)}}function E(a){a.preventDefault();var b=a.deltaY;switch(a.deltaMode){case 0:if(F||G)b=600*(b/document.documentElement.clientHeight);break;case 1:b*=30;break;case 2:b*=900}0!==b&&h("mouseWheel",
b,s(a,U))}function H(a){a.stopPropagation();var b=a.changedTouches[0],c="";if(!(1<a.touches.length)){var d;switch(a.type){case "touchstart":c="mousedown";break;case "touchmove":c="mousemove";break;case "touchend":c="mouseup";d=document.createEvent("MouseEvent");d.initMouseEvent("click",!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(d);a.preventDefault();break;default:return}d=document.createEvent("MouseEvent");d.initMouseEvent(c,!0,!0,window,1,b.screenX,
b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);d.originalTouchEvent=a;b.target.dispatchEvent(d);a.preventDefault()}}function I(a){a.preventDefault()}function J(a){if(!a.shiftKey&&!a.ctrlKey&&!a.altKey&&!a.metaKey){var b=K[a.keyCode];void 0!==b&&(V[b](),a.preventDefault())}}function L(a){var b=K[a.keyCode];void 0!==b&&(b=W[b],void 0!==b&&b(),a.preventDefault())}function s(a,b){b||(b=B.create());var c=d.getBoundingClientRect();b[0]=a.clientX-Math.round(c.left);b[1]=Math.round(c.height)-(a.clientY-
Math.round(c.top));return b}function h(a,b,c){a=r[a];if(void 0!==a)X[a](b,c)}var S=200,T=100,K={37:"panLeft",38:"panForward",39:"panRight",40:"panBackward",66:"lookAround",74:"panDown",78:"lookNorth",80:"lookDown",85:"panUp"},q,B=P.vec2d,y=R.assert,Y={down:"mousedown",move:"mousemove",up:"mouseup"},Z={down:"pointerdown",move:"pointermove",up:"pointerup"},F=O("trident"),G=parseFloat(navigator.appVersion.split("Edge/")[1])||void 0,p=!!window.PointerEvent&&(F||G),M=!p,g=p?Z:Y,N=["touchmove","touchstart",
"touchend","touchcancel"],d=null,A=function(a){p?(d.releasePointerCapture(a.pointerId),d.removeEventListener(g.move,v,!0),d.removeEventListener(g.up,x,!0)):(document.removeEventListener(g.move,v,!0),document.removeEventListener(g.up,x,!0))};this.connect=function(){if(d=k.get("canvas"))d.style.touchAction="none",M&&C.forEach(N,function(a){d.addEventListener(a,H,!0)}),d.addEventListener(g.down,D,!1),d.addEventListener("wheel",E,!1),d.addEventListener("contextmenu",I,!1),d.setAttribute("tabindex","1"),
d.addEventListener("keydown",J,!1),d.addEventListener("keyup",L,!1)};this.disconnect=function(){d&&(M&&C.forEach(N,function(a){d.removeEventListener(a,H,!0)}),d.removeEventListener(g.down,D,!1),d.removeEventListener("wheel",E,!1),d.removeEventListener("contextmenu",I,!1),d.removeEventListener("keydown",J,!1),d.removeEventListener("keyup",L,!1),d=null)};var $=Q.init(k,"canvas",function(){this.disconnect();this.connect()}.bind(this)),c=k.navigation;this.destroy=function(){this.disconnect();$.remove()};
this.setControls=function(a){q?q=a:r=a};this.getControls=function(){return r};var e=0,l=0,m=0,z=null,u,w=B.create(),U=B.create(),X={select:function(a){k.get("ready")&&k._stage.select(a)},clickStep:function(a,b){k.get("ready")&&c.zoom.stepScreen(Math.log(0.5)/Math.log(0.6),a)},pan:function(a,b){switch(b){case 0:c.pan.begin(a);break;case 1:c.pan.update(a);break;case 2:c.pan.end(a);break;default:y(!1)}},tumble:function(a,b){switch(b){case 0:c.rotate.begin(a,t.Rotate.PivotPoint.POI);break;case 1:c.rotate.update(a,
t.Rotate.PivotPoint.POI);break;case 2:c.rotate.end(a);break;default:y(!1)}},zoom:function(a,b){switch(b){case 0:c.zoom.begin(a);break;case 1:c.zoom.update(a);break;case 2:c.zoom.end(a);break;default:y(!1)}},zoomStep:function(a,b){c.zoom.stepScreen(-a/60,b)},lookAround:function(a,b){switch(b){case 0:c.rotate.begin(a,t.Rotate.PivotPoint.EYE);break;case 1:c.rotate.update(a,t.Rotate.PivotPoint.EYE);break;case 2:c.rotate.end(a);break;default:y(!1)}}},f=t.Pan.Direction,V={panLeft:function(){c.pan.beginContinuous(f.LEFT)},
panRight:function(){c.pan.beginContinuous(f.RIGHT)},panForward:function(){c.pan.beginContinuous(f.FORWARD)},panBackward:function(){c.pan.beginContinuous(f.BACKWARD)},panUp:function(){c.pan.beginContinuous(f.UP)},panDown:function(){c.pan.beginContinuous(f.DOWN)},lookAround:function(){q||(q=r,r=n.LOOK_AROUND)},lookNorth:function(){k.goTo({heading:0})},lookDown:function(){k.goTo({tilt:0})}},W={panLeft:function(){c.pan.endContinuous(f.LEFT)},panRight:function(){c.pan.endContinuous(f.RIGHT)},panForward:function(){c.pan.endContinuous(f.FORWARD)},
panBackward:function(){c.pan.endContinuous(f.BACKWARD)},panUp:function(){c.pan.endContinuous(f.UP)},panDown:function(){c.pan.endContinuous(f.DOWN)},lookAround:function(){q&&(r=q,q=void 0)}}};n.PAN={mouseClick:"select",mouseClickDouble:"clickStep",mouseDragLeft:"pan",mouseDragRight:"tumble",mouseDragMiddle:"zoom",mouseWheel:"zoomStep"};n.TUMBLE={mouseClick:"select",mouseClickDouble:"clickStep",mouseDragLeft:"tumble",mouseDragRight:"pan",mouseDragMiddle:"zoom",mouseWheel:"zoomStep"};n.LOOK_AROUND={mouseClick:"select",
mouseClickDouble:"clickStep",mouseDragLeft:"lookAround",mouseDragRight:"tumble",mouseDragMiddle:"pan",mouseWheel:"zoomStep"};n.OLD={mouseClick:"select",mouseClickDouble:"clickStep",mouseDragMiddle:"tumble",mouseDragRight:"pan",mouseWheel:"zoomStep"};n.PRO_PAN={mouseClick:"select",mouseClickDouble:"clickStep",mouseDragLeft:"pan",mouseDragMiddle:"tumble",mouseDragRight:"zoom",mouseWheel:"zoomStep"};n.PRO_TUMBLE={mouseClick:"select",mouseClickDouble:"clickStep",mouseDragLeft:"tumble",mouseDragMiddle:"pan",
mouseDragRight:"zoom",mouseWheel:"zoomStep"};return n});