// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../core/declare ../../../core/Scheduler ../support/eventUtils ./StreamDataManager ./PreallocArray ../webgl-engine/lib/Util".split(" "),function(k,p,q,r,s,l){function f(b){this.budget=this.begin=0;this.performance=l.performance;this.enabled=!0;void 0!==b&&this.reset(b)}var m=l.assert,g={TERRAIN:"terrain",SCENE:"scene",SYMBOLOGY:"symbols"},h=new s(20);f.prototype.now=function(){return this.performance.now()};f.prototype.reset=function(b){this.begin=this.now();this.budget=this.enabled?
b:Number.MAX_VALUE};f.prototype.done=function(){return this.enabled&&this.elapsed()>=this.budget};f.prototype.remaining=function(){return Math.max(this.budget-this.elapsed(),0)};f.prototype.elapsed=function(){return this.now()-this.begin};k=k(null,{constructor:function(b,a){this._clients=[];this._frameWorker=null;this._budget=new f;this._idleFrameWorkers=[];this._idleFrameWorkerRobin=0;this._idleUpdatesStartFired=!1;this._lastTargetChangeTime=l.performance.now();this.navigationTimeout=300;this.animatingFrameTimeBudget=
10;this.idleFrameWorkerBudget=30;this.idleFrameTimeBudget=50;var c={},d;for(d in g)c[g[d]]=0;c[g.TERRAIN]=15;c[g.SCENE]=20;c[g.SYMBOLOGY]=5;this._maxGpuMemory=1500;this.streamDataManager=new r(c);this._cameraListeners=q.on(b,{navigation:{currentViewReachedTarget:this._targetReached,targetViewChanged:this._targetChanged}},this);a||(a=p);this._frameTask=a.addFrameTask({update:this._frameUpdate.bind(this)});this._view=b;this.stats={frameUpdateTime:new n,idleUpdateTime:new n};this.frameUpdateNavigation=
null},destroy:function(){this._frameTask.remove();this._frameTask=null;this._cameraListeners.remove();this.streamDataManager.destroy();this.streamDataManager=null},setEnableBudget:function(b){this._budget.enabled=!!b},registerClient:function(b,a,c){this._clients.push({client:b,type:a});"function"===typeof b.setMaxGpuMemory&&b.setMaxGpuMemory(this._maxGpuMemory);return this.streamDataManager.makeSupplier(a,c)},deregisterClient:function(b){for(var a=0;a<this._clients.length;a++)if(this._clients[a].client===
b){this._clients[a]=this._clients[this._clients.length-1];this._clients.pop();return}console.warn("deregistering an unregistered client.")},setMaxGpuMemory:function(b){this._maxGpuMemory=b;for(var a=0;a<this._clients.length;a++){var c=this._clients[a].client;"function"===typeof c.setMaxGpuMemory&&c.setMaxGpuMemory(b)}},registerIdleFrameWorker:function(b,a){var c=this._idleFrameWorkers.some(function(a){return a.client===b});m(!c,"Can only register idle frame workers once per client/layer");m(!a.idleFrame||
a.needsUpdate,"needsUpdate has to be specified if idleFrame is specified");this._idleFrameWorkers.push({client:b,callbacks:a});this._isIdle()&&(this._idleUpdatesStartFired&&a.idleBegin)&&a.idleBegin.call(b)},deregisterIdleFrameWorker:function(b){for(var a=this._idleFrameWorkers,c=0;c<a.length;c++){var d=a[c];if(d.client===b){this._idleUpdatesStartFired&&d.callbacks.idleEnd&&d.callbacks.idleEnd.call(b);a[c]=a[a.length-1];a.pop();break}}},registerFrameWorker:function(b){m(!this._frameWorker,"Only one (non-idle) per-frame worker supported at the moment");
this._frameWorker=b},deregisterFrameWorker:function(){this._frameWorker=null},_targetChanged:function(b){this._lastTargetChangeTime=l.performance.now();this._targetReached=!1;this._idleUpdatesStartFired&&(this._idleUpdatesStartFired=!1,this._callWorkersNoScheduling("idleEnd"))},_targetReached:function(b){this._targetReached=!0},_frameUpdate:function(b){var a=this._isIdle();this._budget.reset((a?this.idleFrameWorkerBudget:this.animatingFrameTimeBudget)-b.spendInFrame);this._view.navigation&&this._view.navigation.step(b.deltaTime);
this._frameWorker&&(this._frameWorker(this._budget),this.stats.frameUpdateTime.addSample(this._budget.elapsed()));a&&(this._idleUpdatesStartFired||(this._callWorkersNoScheduling("idleBegin"),this._idleUpdatesStartFired=!0),this._budget.reset(this.idleFrameTimeBudget-this._budget.elapsed()),3<this._budget.remaining()&&(this._callWorkersStrictScheduling("idleFrame",this._budget),this.stats.idleUpdateTime.addSample(this._budget.elapsed())))},_isIdle:function(){return this._budget.now()-this._lastTargetChangeTime>
this.navigationTimeout&&this._targetReached},_callWorkersNoScheduling:function(b){for(var a=this._idleFrameWorkers,c=0;c<a.length;c++){var d=a[c];d.callbacks[b]&&d.callbacks[b].call(d.client)}},_callWorkersStrictScheduling:function(b,a){var c=this._idleFrameWorkers,d=c.length,e,f,g;h.clear();f=0;for(g=this._idleFrameWorkerRobin;f<d;f++)e=c[g++%d],e.callbacks.needsUpdate&&e.callbacks.needsUpdate.call(e.client)&&(0===h.length&&(this._idleFrameWorkerRobin=g),h.push(e));e=a.now();for(c=e+a.remaining();0<
h.length&&e<c;)a.reset((c-e)/h.length),e=h.pop(),e.callbacks[b].call(e.client,a),e=a.now()}});k.ClientType=g;var n=function(){this.addSample=function(b){this.min=Math.min(this.min,b);this.max=Math.max(this.max,b);this.total+=b;this.numSamples++};this.getAverage=function(){return this.total/this.numSamples};this.reset=function(){this.numSamples=this.total=0;this.min=Number.MAX_VALUE;this.max=-Number.MAX_VALUE};this.reset()};return k});