// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../geometry/SpatialReference ../../../geometry/Geometry ../../../geometry/Point ../../../geometry/Extent ../../../geometry/support/webMercatorUtils ../../../core/Error ../../../core/promiseUtils ../../../Camera ../../../Viewpoint ../../../Graphic ../lib/glMatrix ./mathUtils ./projectionUtils ./cameraUtils ./aaBoundingBox ./aaBoundingRect ./intersectionUtils".split(" "),function(C,Z,w,$,x,aa,D,E,F,ba,I,Q,u,g,s,R,ca){function G(a){return 360-Q.cyclicalDeg.normalize(a)}function z(a){return Q.cyclicalDeg.normalize(360-
a)}function S(a,b,c){if(!b)return null;var d=a.spatialReference||C.WGS84,e;if(b.camera){e=b.get("camera.position.spatialReference");if(!x.canProject(e,d))return null;b=b.camera.clone();e.equals(d)||(a=x.project(b.position,d),a.z=b.position.z,b.position=a);return b}if((e=b.get("targetGeometry.spatialReference"))&&!x.canProject(e,d))return null;var q=a.navigation.currentCamera;e=g.internalToExternal(a,q);var l={noReset:!1};null!=b.rotation&&(e.heading=G(b.rotation),l.noReset=!0);null!=c&&(e.tilt=c);
if(b.targetGeometry instanceof w){var f=b.targetGeometry;c=b.targetGeometry.clone();b=null!=b.scale?g.scaleToDistance(a,b.scale,f.latitude):q.distance;b=g.eyeHeadingTiltForCenterPointAtDistance(a,e.heading,e.tilt,c,b,l);a=u.vectorToPoint(b.eye,a.renderSpatialReference,d);return new E(a,b.heading,b.tilt,e.fov)}return g.fromExtent(a,b.targetGeometry.extent,e,l)}function J(a,b,c,d){var e=c.scale;null==e&&null!=c.zoom&&(e=g.zoomToScale(a,c.zoom));null==e&&null!=c.distance&&(b=b.center||b,e=g.distanceToScale(a,
c.distance,b.latitude));null==e&&d&&(e="function"===typeof d?d():d);return e}function T(a,b,c,d,e){if(!(b&&c.position||b&&c.direction||c.position&&c.direction))return!1;var q=a.spatialReference||C.WGS84,l=a.renderSpatialReference,k=c.direction;b&&c.position&&(k=null);c.position&&u.pointToVector(c.position,m,l);b&&u.pointToVector(b,p,l);if(k){var h=new w(c.position||b);h.x+=k[0];h.y+=k[1];2<k.length&&(h.z+=k[2]);u.pointToVector(h,v,l);f.subtract(v,c.position?m:p)}c.position&&k?(e.camera.position=new w(c.position),
g.directionToHeadingTilt(a,m,v,d.up,e.camera),f.add(m,v,p),a.navigation.getCenterIntersectTerrain(m,p,p),e.targetGeometry=u.vectorToPoint(p,l,q),e.scale=g.distanceToScale(a,f.dist(m,p),e.targetGeometry.latitude)):b&&k?(e.targetGeometry=new w(b),e.scale=J(a,e.targetGeometry,c,function(){return g.computeScale(a,d)}),b=g.scaleToDistance(a,e.scale,b.latitude),f.scale(v,b/f.length(v),m),f.add(m,p),e.camera.position=u.vectorToPoint(m,l,q),g.directionToHeadingTilt(a,m,v,d.up,e.camera)):(e.targetGeometry=
new w(b),e.camera.position=new w(c.position),f.subtract(p,m,v),g.directionToHeadingTilt(a,m,v,d.up,e.camera),e.scale=g.distanceToScale(a,f.dist(m,p),e.targetGeometry.latitude));e.rotation=z(e.camera.heading);return!0}function K(a,b){var c=!1;null!=b.heading?(a.heading=b.heading,c=!0):null!=b.rotation&&(a.heading=G(b.rotation),c=!0);null!=b.tilt&&(a.tilt=b.tilt,c=!0);null!=b.fov&&(a.fov=b.fov);return c}function H(a,b,c){var d=a.spatialReference||C.WGS84;b=b||g.externalToInternal(a,c.camera);c.targetGeometry=
u.vectorToPoint(b.center,a.renderSpatialReference,d);c.scale=g.computeScale(a,b);c.rotation=z(c.camera.heading);return c}function L(a,b,c){if(b){var d=[];if(!b.hasZ&&a.basemapTerrain){var e;e=b.isInstanceOf(w)?b:b.centroid||b.center;n[2]=e?a.basemapTerrain.getElevation(e)||0:0}da[b.declaredClass](b,function(a){d.push(a[0],a[1],a[2])},n);var f=d.length/3;if(0!==f&&(e=Array(d.length),u.bufferToBuffer(d,b.spatialReference,0,e,a.spatialReference,0,f))){b.hasZ&&(c.hasZ=!0);for(a=0;a<e.length;a+=3)b.hasZ?
(n[0]=e[a+0],n[1]=e[a+1],n[2]=e[a+2]):(n[0]=e[a+0],n[1]=e[a+1]),s.expand(c.boundingBox,n)}}}function ea(a,b,c){return a.whenViewForGraphic(b).then(function(a){if(a&&a.whenGraphicBounds)return a.whenGraphicBounds(b)}).then(function(a){s.expand(c.boundingBox,a);isFinite(a[2])&&(c.hasZ=!0)}).otherwise(function(){L(a,b.geometry,c)})}function U(a,b,c){if(Array.isArray(b)&&2===b.length&&"number"===typeof b[0]&&"number"===typeof b[1])t.x=b[0],t.y=b[1],t.z=void 0,t.spatialReference=C.WGS84,L(a,t,c);else{if(b&&
b.forEach){var d=D.resolve();b.forEach(function(b){d=d.then(function(){return U(a,b,c)})});return d}if(b instanceof Z)L(a,b,c);else if(b instanceof ba)return ea(a,b,c)}return D.resolve()}function fa(a,b,c,d){if(b.camera)return V(a,c,b.camera,d);d.scale=b.scale;d.rotation=b.rotation;d.targetGeometry=b.targetGeometry?b.targetGeometry.clone():null;d.camera=null;null!=c.heading?d.rotation=z(c.heading):null!=c.rotation&&(d.rotation=c.rotation);b=J(a,d.targetGeometry,c);null!=b&&(d.scale=b);d.camera=S(a,
d,c.tilt);return d}function V(a,b,c,d){d.camera=c.clone();d.camera.fov=a.camera.fov;b=a.spatialReference;c=d.camera.position.spatialReference;if(!x.canProject(c,b))return null;c.equals(b)||(b=x.project(d.camera.position,b),b.z=d.camera.position.z,d.camera.position=b);return H(a,null,d)}function M(a,b,c,d){if(!c)return null;d.targetGeometry=c.clone();var e=a.navigation.getCameraIntersectTerrain();if(T(a,d.targetGeometry,b,e,d))return d;g.internalToExternal(a,e,d.camera);var q={noReset:!1};K(d.camera,
b)&&(q.noReset=!0);d.scale=J(a,d.targetGeometry,b);null==d.scale&&(u.pointToVector(c,n,a.renderSpatialReference),ca.frustumPoint(e.frustumPlanes,n)?d.scale=g.distanceToScale(a,f.dist(e.eye,n),c.latitude):d.scale=g.computeScale(a,e));return!g.fromCenterScale(a,d.targetGeometry,d.scale,d.camera,q,d.camera)?null:d}function ga(a,b,c,d){d.targetGeometry=c.clone();var e=a.navigation.getCameraIntersectTerrain();g.internalToExternal(a,e,d.camera);e={noReset:!1};K(d.camera,b)&&(e.noReset=!0);return!g.fromExtent(a,
c,d.camera,e,d.camera)?null:d}function ha(a,b){if(!b||!a.spatialReference)return null;var c={};if(null==b.declaredClass&&!Array.isArray(b)){for(var d in b)c[d]=b[d];b.center&&!c.target&&(c.target=b.center)}else c.target=b;return c}function A(a){a&&(a.rotation=z(a.camera.heading));return D.resolve(a)}var f=I.vec3d,N=I.mat3d,W=I.mat4d,m=f.create(),p=f.create(),v=f.create(),O={heading:0,tilt:0},n=f.create(),X=W.create(),P=N.create(),B=s.create(),ia=R.create(),t=new w,da={"esri.geometry.Point":function(a,
b,c){c[0]=a.x;c[1]=a.y;a.hasZ&&(c[2]=a.z);b(c)},"esri.geometry.Polygon":function(a,b,c){for(var d=a.hasZ,e=0;e<a.rings.length;e++)for(var f=a.rings[e],l=0;l<f.length;l++)c[0]=f[l][0],c[1]=f[l][1],d&&(c[2]=f[l][2]),b(c)},"esri.geometry.Polyline":function(a,b,c){for(var d=a.hasZ,e=0;e<a.paths.length;e++)for(var f=a.paths[e],l=0;l<f.length;l++)c[0]=f[l][0],c[1]=f[l][1],d&&(c[2]=f[l][2]),b(c)},"esri.geometry.Multipoint":function(a,b,c){var d=a.points;a=a.hasZ;for(var e=0;e<d.length;e++)c[0]=d[e][0],c[1]=
d[e][1],a&&(c[2]=d[e][2]),b(c)},"esri.geometry.Extent":function(a,b,c){a.hasZ?(b(f.set3(a.xmin,a.ymin,a.zmin,c)),b(f.set3(a.xmax,a.ymin,a.zmin,c)),b(f.set3(a.xmin,a.ymax,a.zmin,c)),b(f.set3(a.xmax,a.ymax,a.zmin,c)),b(f.set3(a.xmin,a.ymin,a.zmax,c)),b(f.set3(a.xmax,a.ymin,a.zmax,c)),b(f.set3(a.xmin,a.ymax,a.zmax,c)),b(f.set3(a.xmax,a.ymax,a.zmax,c))):(b(f.set3(a.xmin,a.ymin,c[2],c)),b(f.set3(a.xmax,a.ymin,c[2],c)),b(f.set3(a.xmin,a.ymax,c[2],c)),b(f.set3(a.xmax,a.ymax,c[2],c)))}},Y={create:function(a,
b){var c=ha(a,b);if(!c)return D.reject(new aa("viewpointutils-create:no-target","Missing target for creating viewpoint"));var d=new F({camera:new E({fov:a.camera.fov})}),e=null!=c.scale||null!=c.zoom||null!=c.distance;if(c.target instanceof F)return A(fa(a,c.target,c,d));if(c.target instanceof E)return A(V(a,c,c.target,d));if(c.target instanceof $)return e?A(M(a,c,c.target.center,d)):A(ga(a,c,c.target,d));var q={boundingBox:s.create(s.NEGATIVE_INFINITY),spatialReference:a.spatialReference,hasZ:!1};
return U(a,c.target,q).then(function(){if(isFinite(q.boundingBox[0])){s.center(q.boundingBox,n);t.x=n[0];t.y=n[1];t.z=n[2];t.spatialReference=a.spatialReference;var b;!isFinite(t.z)||!q.hasZ?(t.z=void 0,b=R.isPoint(s.toRect(q.boundingBox,ia))):b=s.isPoint(q.boundingBox);if(e||b)return M(a,c,t,d);var k=t,h=q.boundingBox,r=Y.DEFAULT_FRAME_COVERAGE;d.targetGeometry=k.clone();b=a.navigation.getCameraIntersectTerrain();var m=0;k.hasZ?m=k.z:a.basemapTerrain&&(m=a.basemapTerrain.getElevation(k));f.set3(k.x,
k.y,m,n);u.computeLinearTransformation(a.spatialReference,n,X,a.renderSpatialReference);W.toMat3(X,P);N.transpose(P);s.set(B,s.NEGATIVE_INFINITY);for(var k=[[0,1,2],[3,1,2],[0,4,2],[3,4,2],[0,1,5],[3,1,5],[0,4,5],[3,4,5]],p=0;p<k.length;p++){var y=k[p],x=h[y[2]];isFinite(x)||(x=m);f.set3(h[y[0]],h[y[1]],x,n);u.vectorToVector(n,a.spatialReference,n,a.renderSpatialReference);s.expand(B,N.multiplyVec3(P,n))}h=s.width(B);m=s.height(B);k=s.depth(B);y=1/Math.tan(b.fovX/2);p=1/Math.tan(b.fovY/2);y=0.5*Math.sqrt(h*
h+k*k)*Math.max(p,y)+0.5*m;h=0.5*m*p+0.5*Math.max(h,k);r=Math.max(y,h)/r;g.internalToExternal(a,b,d.camera);b={noReset:!1};K(d.camera,c)&&(b.noReset=!0);d.scale=g.distanceToScale(a,r,d.targetGeometry.latitude);b=g.fromCenterScale(a,d.targetGeometry,d.scale,d.camera,b,d.camera)?d:null;return b}b=a.navigation.getCameraIntersectTerrain();T(a,null,c,b,d)?b=d:c.position?(b.computeDirection(v),g.directionToHeadingTilt(a,b.eye,v,b.up,O),d.camera.position=new w(c.position),b=d.camera,r=O.heading,h=c.heading,
null==h&&null!=c.rotation&&(h=G(c.rotation)),null==h&&r&&(h="function"===typeof r?r():r),b.heading=h,b=d.camera,r=O.tilt,r=null!=c.tilt?c.tilt:null!=r?"function"===typeof r?r():r:void 0,b.tilt=r,b=H(a,null,d)):(b=u.vectorToPoint(b.center,a.renderSpatialReference,t,a.spatialReference),b=M(a,c,b,d));return b}).then(function(a){return A(a)})},rotationToHeading:G,headingToRotation:z,toCamera:S,fromCamera:function(a,b,c){c||(c=new F);c.camera=b.clone();return H(a,null,c)},fromInternalCamera:function(a,
b,c){c||(c=new F({camera:new E}));g.internalToExternal(a,b,c.camera);return H(a,b,c)},DEFAULT_FRAME_COVERAGE:0.66};return Y});