// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/JSONSupporter ../Viewpoint ../Basemap ../support/basemapUtils ../core/Collection ../core/collectionUtils ../core/promiseUtils ./Environment ./Lighting dojo/_base/lang ../views/3d/lib/glMatrix ../core/accessoireSupport/typescript".split(" "),function(q,C,k,c,l,p,u,s,v,w,g,m,x,n,y,e){function h(c){return c.map(function(a){return{id:a.id}})}var z=0;q=function(f){function a(b){f.call(this,b);this.environment=
this.visibleLayers=this.basemap=this.viewpoint=this.thumbnail=this.description=this.title=this.id=this._currentAnimation=null}k(a,f);a.prototype.getDefaults=function(){return{id:Date.now().toString(16)+"-slide-"+z++,thumbnail:{},title:{},description:{},viewpoint:new p,environment:new m,visibleLayers:[]}};a.prototype.clone=function(){return new a({id:this.id,title:this.title.clone(),thumbnail:this.thumbnail.clone(),description:this.description&&this.description.clone()||null,viewpoint:this.viewpoint&&
this.viewpoint.clone()||null,basemap:this.basemap&&this.basemap.clone()||null,visibleLayers:h(this.visibleLayers),environment:this.environment&&this.environment.clone()||null})};a.prototype.toJSON=function(){var b={id:this.id,title:this.title.toJSON(),thumbnail:this.thumbnail.toJSON(),viewpoint:this.viewpoint.toJSON(),baseMap:this.basemap.toJSON(),visibleLayers:h(this.visibleLayers).toArray(),environment:this.environment.toJSON()};null!=this.description&&this.description.text&&(b.description=this.description.toJSON());
return b};a.prototype._updateVisibleLayersFrom=function(b){var a=this,d=[];return g.eachAlways(this._allLayers(b.map).map(function(a){return b.whenLayerView(a).then(function(b){b.visible&&d.push({id:b.layer.id})})}).toArray()).then(function(){a.visibleLayers.removeAll();a.visibleLayers.addMany(d)})};a.prototype.updateFrom=function(b,a){var d=this;a=n.mixin({screenshot:n.mixin({format:"jpeg",quality:80,width:120,height:75},a&&a.screenshot)},a);return this._updateVisibleLayersFrom(b).then(function(){d.viewpoint=
b.viewpoint.clone();d.environment.lighting=x.prototype.clone.apply(b.environment.lighting);d.basemap=b.map.basemap&&b.map.basemap.clone()||null;return b.takeScreenshot(a.screenshot)}).then(function(b){d.thumbnail=new t({url:b.dataURL});return d})};a.prototype.applyTo=function(b,a){var d=this,c=n.mixin({animate:!0},a);return this._applyBasemap(b).then(function(){return d._applyLayerVisibility(b)}).then(function(){return d._applyViewpoint(b,c)}).then(function(){return d})};a.prototype._applyBasemap=
function(b){var a=this;return this.basemap?this.basemap.load().always(function(){b.map.basemap=s.clonePreservingTiledLayers(a.basemap,b.map.basemap)}):g.resolve()};a.prototype._allLayers=function(b){var a=new v;this._collectLayers(b,a);this._collectLayers(b.ground,a);return a};a.prototype._collectLayers=function(b,a){var d=this;b.layers.forEach(function(b){a.add(b);b.layers&&d._collectLayers(b,a)})};a.prototype._applyLayerVisibility=function(b){var a=this;if(this.visibleLayers)return g.eachAlways(this._allLayers(b.map).map(function(d){return b.whenLayerView(d).then(function(b){b.visible=
a.visibleLayers.some(function(a){return a.id===b.layer.id})})}).toArray())};a.prototype._applyViewpoint=function(b,a){this.viewpoint.camera.fov=b.camera.fov;if(a.animate){if(this.get("environment.lighting.date"))return this._animateToLighting(b).then(function(){});b.environment.lighting=this.environment.lighting.clone();return b.goTo(this.viewpoint).then(function(){})}b.viewpoint=this.viewpoint;b.environment.lighting=this.environment.lighting.clone();return g.resolve()};a.prototype._animateToLighting=
function(b){var a=this,d;"global"===b.viewingMode&&(d=this._animateLightingWithCamera(b));this._currentAnimation&&(this._currentAnimation.stop(),this._currentAnimation=null);b.environment.lighting.cameraTrackingEnabled=!1;b.environment.lighting.directShadowsEnabled=this.environment.lighting.directShadowsEnabled;b.environment.lighting.ambientOcclusionEnabled=this.environment.lighting.ambientOcclusionEnabled;null!=this.environment.lighting.displayUTCOffset&&(b.environment.lighting.displayUTCOffset=
this.environment.lighting.displayUTCOffset);this._currentAnimation=b.goTo(this.viewpoint);this._currentAnimation.then(function(c){d&&d.remove();a._currentAnimation===c&&(b.environment.lighting.cameraTrackingEnabled=!0);"finished"===c.state&&(b.environment.lighting=a.environment.lighting.clone())});return this._currentAnimation};a.prototype._getTime=function(b){var a=b.getTime();b=3600*b.getUTCHours()+60*b.getUTCMinutes()+b.getUTCSeconds();return[a,b]};a.prototype._setTime=function(b,a,d){b.setTime(a);
b.setUTCHours(d/3600);b.setUTCMinutes(d%3600/60);b.setUTCSeconds(d%3600%60);return b};a.prototype._animateLightingWithCamera=function(b){var a=this,d=y.vec3d,c=this._getTime(new Date(b.environment.lighting.date.toString())),e=c[0],f=c[1],c=this._getTime(this.environment.lighting.date),k=c[0],l=c[1],g=b.renderCoordsHelper,m=[0,0,0];g.toRenderCoords(b.camera.position,m);var n=[0,0,0];g.toRenderCoords(this.viewpoint.camera.position,n);var h=[0,0,0],q=new Date;return b.watch("camera",function(c){g.toRenderCoords(c.position,
h);c=d.dist2(m,h);var p=d.dist2(n,h),r=0;0!==c+p&&(r=c/(c+p));b.environment.lighting.date=a._setTime(q,e+(k-e)*r,f+(l-f)*r)})};a.createFrom=function(b,c){return(new a).updateFrom(b,c)};a.sanitizeJSON=function(b){var a;a=void 0!==b.visibleLayers&&Array.isArray(b.visibleLayers)?h(b.visibleLayers):[];a={id:b.id||"",title:b.title||{text:""},thumbnail:b.thumbnail||{url:""},viewpoint:b.viewpoint,baseMap:b.baseMap,visibleLayers:a};void 0!==b.description&&(a.description=b.description);void 0!==b.environment&&
(a.environment=m.sanitizeJSON(b.environment));return a};c([e.shared("esri.webscene.Slide")],a.prototype,"declaredClass",void 0);c([e.shared({reader:{exclude:["baseMap"],add:["basemap"]}})],a.prototype,"classMetadata",void 0);c([e.property({value:""})],a.prototype,"id",void 0);c([e.property({type:A})],a.prototype,"title",void 0);c([e.property({type:B})],a.prototype,"description",void 0);c([e.property({type:t})],a.prototype,"thumbnail",void 0);c([e.property({type:p})],a.prototype,"viewpoint",void 0);
c([e.property({reader:function(a,c){return!c.baseMap||0===c.baseMap.baseMapLayers.length?null:u.fromJSON(c.baseMap)},setter:function(a){return s.ensureType(a)}})],a.prototype,"basemap",void 0);c([e.property({reader:function(a){return a.map(function(a){return{id:a.id}})},setter:w.referenceSetter})],a.prototype,"visibleLayers",void 0);c([e.property({type:m})],a.prototype,"environment",void 0);return a=c([e.subclass()],a)}(l);var t=function(f){function a(){f.apply(this,arguments)}k(a,f);a.prototype.toJSON=
function(){return{url:this.url}};a.prototype.clone=function(){return new a({url:this.url})};c([e.property({value:""})],a.prototype,"url",void 0);return a=c([e.subclass()],a)}(l),A=function(f){function a(){f.apply(this,arguments)}k(a,f);a.prototype.toJSON=function(){return{text:this.text}};a.prototype.clone=function(){return new a({text:this.text})};c([e.property({value:""})],a.prototype,"text",void 0);return a=c([e.subclass()],a)}(l),B=function(f){function a(){f.apply(this,arguments)}k(a,f);a.prototype.toJSON=
function(){return{text:this.text}};a.prototype.clone=function(){return new a({text:this.text})};c([e.property({value:""})],a.prototype,"text",void 0);return a=c([e.subclass()],a)}(l);return q});