// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../core/declare ../../layers/LayerView ../../../geometry/Extent ../../../core/urlUtils ./support/projectExtentUtils ../lib/glMatrix ../webgl-engine/Stage ../webgl-engine/lib/Texture ../webgl-engine/lib/RenderGeometry ../webgl-engine/lib/GeometryData ../webgl-engine/lib/GeometryUtil ../webgl-engine/materials/Material ../webgl-engine/lib/Util".split(" "),function(k,z,A,B,C,D,l,E,F,G,H,I,p){var q=p.assert,J=D.mat4d,m=p.VertexAttrConstants,K=function(a){a.remove()};k=k(z,{declaredClass:"esri.views.3d.layers.DynamicLayerView3D",
supportsDraping:!0,hasDraped:!0,drawingOrder:0,_updatingOverlay:!1,constructor:function(){this._extents=[];this._images=[];this.fullExtentInViewSpatialReference=null},initialize:function(){this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this.on("suspend",function(){this.clear();this.emit("draped-data-change")}.bind(this));this.on("resume",function(){for(var a=this._extents.length,c=0;c<a;c++)this.fetch(c)}.bind(this));var a=this.notifyChange.bind(this,"suspended");this._layerPropertyWatches=
[this.layer.watch("opacity",this._opacityChangeHandler.bind(this)),this.layer.watch("exportImageParameters.version",this._refetch.bind(this)),this.layer.watch("minScale",a),this.layer.watch("maxScale",a)];this.view.resourceController.registerIdleFrameWorker(this,{idleBegin:function(){this._hasScaleRange()&&this.notifyChange("suspended")}});(a=C.toView(this).then(function(a){this.fullExtentInViewSpatialReference=a}.bind(this)))&&this.addResolvingPromise(a)},destroy:function(){this.clear();this._layerPropertyWatches.forEach(K);
this._layerPropertyWatches.length=0;this.view.resourceController.deregisterIdleFrameWorker(this)},setDrapingExtent:function(a,b,c,e){var d=(b[2]-b[0])/(b[3]-b[1]);this._extents[a]={extent:b,spatialReference:c,imageSize:1.0001<d?[e,e/d]:0.9999>d?[e*d,e]:[e,e]};this.suspended||this.fetch(a)},fetch:function(a){var b=this._extents[a],c=b.extent,e=new A(c[0],c[1],c[2],c[3],b.spatialReference);this.layer.getImageUrl({extent:e,width:b.imageSize[0],height:b.imageSize[1]},function(b){this._images[a]||(this._images[a]=
{texture:null,material:null,rendergeometry:null,domImage:null,worldExtent:c,loading:!1});var e=this._images[a],g=e.domImage||new Image;0!==b.indexOf("data:")&&B.canUseXhr(b)&&(g.crossOrigin="anonymous");g.src=b;e.loading=!0;g.onload=function(){q(e.domImage===g);e.worldExtent=c;this._createStageObjects(a,g);0===a&&(this._images[1]&&this._images[1].rendergeometry)&&this._createStageObjects(1,null);e.loading=!1;this._evaluateUpdatingState();this.emit("draped-data-change")}.bind(this);g.onerror=function(){e.loading=
!1;this._clearDomImage(e);this._evaluateUpdatingState()}.bind(this);e.domImage=g;this._evaluateUpdatingState()}.bind(this))},clear:function(){for(var a in this._images)this.clearImage(a)},clearImage:function(a){if(a=this._images[a])a.htmlImage&&(a.htmlImage.removeAttribute("src"),a.htmlImage.removeAttribute("onload"),a.htmlImage.removeAttribute("onerror"),a.htmlImage=null),a.rendergeometry&&(this.view._stage.getTextureGraphicsRenderer().removeRenderGeometries([a.rendergeometry]),a.rendergeometry=
null),a.texture&&(this.view._stage.remove(l.ModelContentType.TEXTURE,a.texture.getId()),a.texture=null),a.material&&(this.view._stage.remove(l.ModelContentType.MATERIAL,a.material.getId()),a.material=null),this._clearDomImage(a),a.loading=!1},canResume:function(){if(!this.inherited(arguments))return!1;var a=this.layer.minScale,b=this.layer.maxScale;if(0<a||0<b){var c=this.view.scale;if(c<b||0<a&&c>a)return!1}return!0},_refetch:function(){for(var a=0;a<this._extents.length;a++)this._extents[a]&&this.fetch(a)},
_drawingOrderSetter:function(a,b){if(a!==b){var c={};this._images.forEach(function(b){b&&b.material&&(b.material.setRenderPriority(a),c[b.material.getId()]=!0)});p.objectEmpty(c)||(this.view._stage.getTextureGraphicsRenderer().updateRenderOrder(c),this.emit("draped-data-change"))}return a},_hasScaleRange:function(){return 0<this.get("layer.minScale")||0<this.get("layer.maxScale")},_opacityChangeHandler:function(a){this._images.forEach(function(b){b&&b.material&&b.material.setParameterValues({opacity:a})}.bind(this));
this.emit("draped-data-change")},_clearDomImage:function(a){a.domImage&&(a.domImage.removeAttribute("src"),a.domImage.removeAttribute("onload"),a.domImage.removeAttribute("onerror"),a.domImage=null)},_evaluateUpdatingState:function(){if(this._updatingOverlay)this.set("updating",!0);else{var a=!1,b;for(b in this._images)if(this._images[b].loading){a=!0;break}this.set("updating",a)}},_createStageObjects:function(a,b){var c=this.view._stage,e=c.getTextureGraphicsRenderer(),d=this._images[a];b?(d.texture&&
c.remove(l.ModelContentType.TEXTURE,d.texture.getId()),d.texture=new E(b,"dynamicMapLayer",{width:b.width,height:b.height}),c.add(l.ModelContentType.TEXTURE,d.texture)):q(d.texture);d.material?b&&d.material.setParameterValues({textureId:d.texture.getId()}):(d.material=new I({ambient:[1,1,1],diffuse:[0,0,0],transparent:!0,opacity:this.layer.get("opacity"),textureId:d.texture.getId()},"dynamicMapLayer"),d.material.setRenderPriority(this.drawingOrder),c.add(l.ModelContentType.MATERIAL,d.material));if(0===
a)c=d.worldExtent,c=H.createSquareGeometry([[c[0],c[1],-1],[c[2],c[1],-1],[c[2],c[3],-1],[c[0],c[3],-1]],!0);else{q(1===a);c=this._images[0].worldExtent;if(!c)return;c=L(c,d.worldExtent,-1)}var f=new F(c);f.material=d.material;f.origin={vec3:[0,0,0],id:"0_0"};f.transformation=J.identity();f.name="dynamicMapLayer";f.uniqueName="dynamicMapLayer#"+c.id;e.addRenderGeometries([f]);d.rendergeometry&&e.removeRenderGeometries([d.rendergeometry]);d.rendergeometry=f}});var L=function(){var a=new Float32Array([0,
0,1]);return function(b,c,e){var d=[b[1]-c[1],b[3]-b[1],c[3]-b[3],123456],f=[b[0]-c[0],b[2]-b[0],c[2]-b[2],123456],g=c[2]-c[0],l=c[3]-c[1],t=0<f[0]&&0<f[2]?3:2;b=0<d[0]&&0<d[2]?3:2;var r=(b+1)*(t+1),h=new Float32Array(3*r),r=new Float32Array(2*r);b=new Uint32Array(6*(b*t-1));for(var w=0,k=0,p=0,n=0,s=0,u=0;4>u;u++){var q=d[u];if(!(0>=q)){for(var x=0,v=0;4>v;v++){var y=f[v];0>=y||(h[k++]=c[0]+x,h[k++]=c[1]+w,h[k++]=e,r[p++]=x/g,r[p++]=w/l,3>v&&(3>u&&!(1===v&&1===u))&&(b[s++]=n,b[s++]=n+1,b[s++]=n+
t+1,b[s++]=n+1,b[s++]=n+t+2,b[s++]=n+t+1),n++,x+=y)}w+=q}}c={};c[m.POSITION]={size:3,data:h};c[m.NORMAL]={size:3,data:a};c[m.UV0]={size:2,data:r};e={};d=new Uint32Array(b.length);for(h=0;h<d.length;h++)d[h]=0;e[m.POSITION]=b;e[m.NORMAL]=d;e[m.UV0]=b;return{faces:{type:"triangle",indices:e,positionKey:m.POSITION},vertexAttr:c,id:G.getNewId().toString()}}}();return k});