// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../core/declare dojo/promise/all dojo/Deferred dojo/_base/lang dojo/io-query ../../../config ../../../layers/support/LabelClass ../../../core/urlUtils ../../../core/watchUtils ../../../geometry/support/webMercatorUtils ../../../geometry/support/scaleUtils ../../layers/GraphicsLayerView ../../../layers/graphics/controllers/SnapshotController ../../../geometry/SpatialReference ../../../geometry/Extent ../../../processors/SpatialIndex ./graphics/SymbolConverter ./graphics/TextureCollection ./graphics/Graphics3DSymbol ./graphics/Graphics3DGraphic ./graphics/graphicUtils ./support/LayerViewUpdatingPercentage ../support/ResourceController ../lib/glMatrix ../support/earthUtils ../support/projectionUtils ../support/intersectionUtils ../webgl-engine/Stage ../webgl-engine/lib/Util ../webgl-engine/lib/Layer ../webgl-engine/lib/FloatingBoxLocalOriginFactory ../webgl-engine/materials/HUDMaterial ../support/PromiseLightweight ../webgl-engine/lib/TextTextureAtlas ../webgl-engine/lib/MaterialCollection ../../../core/arrayUtils".split(" "),
function(u,z,A,L,M,B,C,D,v,E,N,p,O,F,P,Q,G,R,S,T,U,V,W,H,w,q,x,r,I,J,X,Y,Z,$,aa,ba){var y=function(a){a.remove()},s=-0.3*w.earthRadius,ca=0.5*w.earthRadius*Math.PI,da=0.9*w.earthRadius,t=H.vec4d,g=H.vec3d,l=g.create();u=u([p,V],{declaredClass:"esri.views.3d.layers.GraphicsLayerView3D",supportsDraping:!0,hasDraped:!1,drawingOrder:0,"symbols-updating":!1,_progressMaxNumNodes:1,updateElevation:!0,_overlayUpdating:!1,initialize:function(){this._stage=this.view._stage;this._stageLayer=new J(this.layer.id,
{state:this.suspended?"HIDDEN":"VISIBLE"},this.layer.id);this._stage.add(r.ModelContentType.LAYER,this._stageLayer);this._labelStageLayer=new J(this.layer.id,{state:this.suspended?"HIDDEN":"IGNORED"},this.layer.id+"_labels");this._stage.add(r.ModelContentType.LAYER,this._labelStageLayer);this._stage.addToViewContent([this._stageLayer.getId(),this._labelStageLayer.getId()]);this.view.labelManager.addSceneServiceLayerView(this);this._streamDataSupplier=this.view.resourceController.registerClient(this,
W.ClientType.SYMBOLOGY,this._addUrlToken.bind(this));this._symbols={};this._graphics={};this._graphicsKeys={};this._graphicsBySymbol={};this._elevationDirtyGraphicsQueue=[];this._elevationDirtyGraphicsSet={};this._updatingGraphicIds={};this._graphicsDrapedIds={};this.hudMaterialCollection=this.textTextureAtlas=null;this._sharedResources={textures:new R(this._streamDataSupplier,this._stage,{wrapClamp:!0})};this._symbolCreationContext={sharedResources:this._sharedResources,renderer:this.layer.renderer,
stage:this._stage,streamDataSupplier:this._streamDataSupplier,elevationProvider:null,renderSpatialReference:this.view.renderSpatialReference,renderCoordsHelper:this.view.renderCoordsHelper,overlaySR:null,layer:this.layer,layerOrder:this.view.getDrawingOrder(this.layer.uid)||0,localOriginFactory:new X(5E6,16),clippingExtent:null};this._graphicsController=null;this._graphicsControllerClientSideFiltering=!1;this._graphicsCollectionEventHandle=this._graphicsCollection=null;this._graphicsControllerEventHandles=
[];this._graphicsControllerLoading=!0;this._initGraphicsController();this._spatialIndex=new Q;this._spatialIndexNumPendingQueries=this._spatialIndexNumGraphics=0;this.view.resourceController.registerIdleFrameWorker(this,{needsUpdate:this._needsIdleUpdate,idleFrame:this._idleUpdate});this._viewChangeListenerHandles=[];this._viewChangeUpdate=this._viewChangeUpdate.bind(this);this._viewChangeListenerHandles.push(this.view.on("resize",this._viewChangeUpdate));this._viewChangeListenerHandles.push(this.view.navigation.on("currentViewChanged",
this._viewChangeUpdate));this._scaleVisibility=this._scaleVisibilityDirty=this._frustumVisibility=this._frustumVisibilityDirty=!0;this._scaleVisibilityQuery=!1;this._clippingChangedHandle=this.view.watch("clippingArea",this._updateClippingExtent.bind(this));this._updateClippingExtent();this._updateSuspendScaleVisibleFinish=this._updateSuspendScaleVisibleFinish.bind(this);this._viewChangeUpdate();this._suspendResumeExtent=this.computedExtent=null;this._suspendResumeExtentEngine={extent:Array(4),planes:Array(4),
maxSpan:0,center:{origin:g.create(),direction:g.create()}};this._suspendResumeExtentEngineDirty=!0;for(var a=0;4>a;a++)this._suspendResumeExtentEngine.extent[a]={origin:g.create(),direction:g.create(),cap:{next:null,direction:g.create()}},this._suspendResumeExtentEngine.planes[a]=t.create();this._suspendResumeExtentEngine.planes[4]=t.create();this.on("suspend",function(){this._stageLayer.setState("HIDDEN");this._labelStageLayer.setState("HIDDEN");this._hideAllGraphics();this.updateElevation=!1}.bind(this));
this.on("resume",function(){this._stageLayer.setState("VISIBLE");this._labelStageLayer.setState("IGNORED");this.updateElevation&&this._markAllGraphicsElevationDirty();this._showLabelsChangeOnResume&&this._showLabelsChange();this.view.basemapTerrain&&this._updateGraphicsVisibility()});this._layerEventHandles=[this.layer.watch("renderer",this._rendererChange.bind(this)),this.layer.watch("opacity",this._opacityChange.bind(this)),this.layer.watch("elevationInfo",this._elevationInfoChange.bind(this)),
this.layer.watch("showLabels",this._showLabelsChange.bind(this)),this.layer.watch("minScale",this._layerMinMaxScaleChangeHandler.bind(this)),this.layer.watch("maxScale",this._layerMinMaxScaleChangeHandler.bind(this)),this.layer.on("graphic-update",this._graphicUpdateHandler.bind(this))];this._elevationUpdateEventHandle=this._scaleChangeEventHandle=null;this._showLabelsChangeOnResume=!1;this._labelClasses=[];this.addResolvingPromise(this._initLabelingInfo());this._basemapTerrainEventHandle=this.view.watch("basemapTerrain",
this._basemapTerrainChanged.bind(this));this._basemapTerrainChanged(this.view.basemapTerrain);this._viewIsSpherical="global"===this.view.viewingMode;var b=new A;this.fullExtentInViewSpatialReference=this._renderSREqualsViewSR=this._viewSR=null;v.whenOnce(this,"view.spatialReference",function(a){this._viewSR=a;this._renderSREqualsViewSR=this.view.renderSpatialReference.equals(a);this._symbolCreationContext.overlaySR=a;var e=this.get("layer.fullExtent.spatialReference");e&&!e.equals(a)&&"local"===this.view.viewingMode&&
B.geometryService?B.geometryService.project([this.layer.fullExtent],a).then(function(a){a&&(Array.isArray(a)&&1===a.length)&&(this.fullExtentInViewSpatialReference=a[0])}.bind(this)).always(function(){b.resolve()}):b.resolve()}.bind(this));this.addResolvingPromise(b.promise)},_addUrlToken:function(a){if(-1!==a.indexOf("?token\x3d")||0===a.indexOf("data:"))return a;var b=L.mixin({token:this.layer.token}),b=M.objectToQuery(b);a+=b?"?"+b:"";null==this._canUseXhr&&(this._canUseXhr=D.canUseXhr(a));return!this._canUseXhr?
D.addProxy(a):a},_updateClippingExtent:function(){var a=this._symbolCreationContext.clippingExtent,b=[];q.extentToBoundingRect(this.view.clippingArea,b,this.view.spatialReference)?this._symbolCreationContext.clippingExtent=[b[0],b[1],-Infinity,b[2],b[3],Infinity]:this._symbolCreationContext.clippingExtent=null;!ba.equals(this._symbolCreationContext.clippingExtent,a)&&this._graphicsController&&(this._graphicsControllerClientSideFiltering?this._recreateAllGraphics():this._graphicsController.extent?
(this._graphicsController.extent=null,this._graphicsControllerClientSideFiltering=!0):this._graphicsController.extent=this.view.clippingArea)},_basemapTerrainChanged:function(a){this._symbolCreationContext.elevationProvider=a;this._tilingSchemeHandle&&this._tilingSchemeHandle.remove();a?this._tilingSchemeHandle=v.whenOnce(a,"tilingScheme",this._recreateAllGraphics.bind(this)):this._recreateAllGraphics();a?(this._elevationUpdateEventHandle=a.on("elevation-change",this._elevationUpdateHandler.bind(this)),
this.updateElevation=!1,this._layerMinMaxScaleChangeHandler()):(this._elevationUpdateEventHandle&&(this._elevationUpdateEventHandle.remove(),this._elevationUpdateEventHandle=null),this._scaleChangeEventHandle&&(this._scaleChangeEventHandle.remove(),this._scaleChangeEventHandle=null))},_getVerticalUnitValueForSR:function(a){a=N.getUnitValueForSR(a);return 1E5<a?1:a},_scaleVerticalUnits:function(a,b){function c(a,b){for(var c=0;c<a.length;++c)for(var e=a[c],d=0;d<e.length;++d)e[d][2]*=b}for(var e=0;e<
a.length;++e){var d=a[e].geometry;if(d.hasZ)d.z?d.z*=b:d.paths?c(d.paths,b):d.rings&&c(d.rings,b);else break}},_getVerticalUnitScale:function(){if("esri.layers.FeatureLayer"===this.layer.declaredClass){var a=this.layer.spatialReference,b=this.view.spatialReference;if(a.equals(b))return 1;a=this._getVerticalUnitValueForSR(a);b=this._getVerticalUnitValueForSR(b);return a/b}return 1},_initGraphicsController:function(){var a=this.layer.createGraphicsController({layerView:this,options:{maxPageSize:300,
extent:this.view.clippingArea}});v.whenTrueOnce(this.view,"basemapTerrain.ready",function(){z([this,a]).then(function(a){this._graphicsController=a[1];this._graphicsController instanceof O?(a=this._graphicsController.on("query-end",function(a){this._graphicsControllerLoading=!1;this._evaluateUpdatingState()}.bind(this)),this._graphicsControllerEventHandles.push(a)):this._graphicsControllerLoading=!1;this._graphicsCollection=this._graphicsController.graphics;this._graphicsCollectionEventHandle=this._graphicsCollection.on("change",
this._collectionChangeHandler.bind(this));0<this._graphicsCollection.length&&this.add(this._graphicsCollection.toArray());this._evaluateUpdatingState()}.bind(this))}.bind(this))},_viewChangeUpdate:function(){this._frustumVisibilityDirty=!0},destroy:function(){this._graphicsCollection=null;this._graphicsCollectionEventHandle&&this._graphicsCollectionEventHandle.remove();this._graphicsControllerEventHandles.forEach(y);this._elevationUpdateEventHandle&&(this._elevationUpdateEventHandle.remove(),this._elevationUpdateEventHandle=
null);this._tilingSchemeHandle&&this._tilingSchemeHandle.remove();this._layerEventHandles.forEach(y);this._scaleChangeEventHandle&&(this._scaleChangeEventHandle.remove(),this._scaleChangeEventHandle=null);this._basemapTerrainEventHandle.remove();this._basemapTerrainEventHandle=null;var a=[this._stageLayer.getId(),this._labelStageLayer.getId()];this._stage.removeFromViewContent(a);this._stage.remove(r.ModelContentType.LAYER,a[0]);this._stage.remove(r.ModelContentType.LAYER,a[1]);this.view.resourceController.deregisterIdleFrameWorker(this);
this.view.labelManager.removeSceneServiceLayerView(this);var a=!1,b;for(b in this._graphics)a=a||this._graphics[b].isDraped(),this._graphics[b].destroy();this._graphics={};this._graphicsKeys=null;for(var c in this._symbols)this._symbols[c].destroy();this._graphicsDrapedIds={};this.hasDraped=!1;this._viewChangeListenerHandles.forEach(y);this._clippingChangedHandle.remove();null!=this._controller&&this._controller.destroy();a&&this.emit("draped-data-change");this._spatialIndex&&this._spatialIndex.destroy()},
add:function(a){this.isResolved()?this._add(a):this.then(function(){this._add(a)}.bind(this))},remove:function(a){for(var b=!1,c=a.length,e=0;e<c;e++){var d=a[e].id,f=this._graphics[d];if(f){f.isDraped()&&(delete this._graphicsDrapedIds[d],b=!0);var h=f.graphics3DSymbol.symbol.id;f.destroy();delete this._graphics[d];delete this._graphicsBySymbol[h][d];this._graphicsKeys=null}}this._updateHasDraped();b&&this.emit("draped-data-change");this.view.labelManager.setDirty()},getRenderingInfo:function(a){var b=
this.inherited(arguments);if(b&&b.color){var c=b.color;b.color=[c.r/255,c.g/255,c.b/255,c.a]}return b},_drawingOrderSetter:function(a){this._symbolCreationContext.layerOrder=a;var b={},c={},e;for(e in this._graphics)this._graphics[e].setDrawOrder(a,b,c);for(var d in c)this._symbols[d].setDrawOrder(a,b);I.objectEmpty(b)||(this.view._stage.getTextureGraphicsRenderer().updateRenderOrder(b),this.emit("draped-data-change"));return a},getGraphicsFromStageObject:function(a,b){var c=null;if(this._graphicsCollection){var e=
a.getMetadata();this._graphicsCollection.some(function(a){return a.id===e.graphicId?c=a:!1})}var d=new Z.Promise;null!=c?d.done(c):d.reject();return d},getGraphics3DGraphics:function(){return this._graphics},getGraphics3DGraphicsKeys:function(){null==this._graphicsKeys&&(this._graphicsKeys=Object.keys(this._graphics));return this._graphicsKeys},_collectionChangeHandler:function(a){var b=this._getVerticalUnitScale();if(1!==b){var c=a.added.slice();this._scaleVerticalUnits(c,b);this.add(c)}else this.add(a.added);
this.remove(a.removed)},_needsIdleUpdate:function(){return this._frustumVisibilityDirty||this.view.basemapTerrain&&(this._scaleVisibilityDirty||0<this._elevationDirtyGraphicsQueue.length)},_idleUpdate:function(a){if(this._frustumVisibilityDirty&&(this._updateSuspendFrustumVisible(),this._frustumVisibilityDirty=!1,a.done()))return;if(this.view.basemapTerrain){if(this._scaleVisibilityDirty&&(this._updateSuspendScaleVisible(),this._scaleVisibilityDirty=!1,a.done()))return;var b=this._elevationDirtyGraphicsQueue.length;
if(0<b){for(var c=this._stageLayer.getId(),e=this._labelStageLayer.getId(),d=0,f=0;f<b;f++){var h=this._elevationDirtyGraphicsQueue[f],k=this._graphics[h];k&&k.alignWithElevation(this.view.basemapTerrain,this.view.renderCoordsHelper);delete this._elevationDirtyGraphicsSet[h];d++;if(20<=d){this.view._stage.processDirtyLayer(c);this.view._stage.processDirtyLayer(e);if(a.done())break;d=0}}this.view._stage.processDirtyLayer(c);this.view._stage.processDirtyLayer(e);this._elevationDirtyGraphicsQueue.splice(0,
f+1);this.view.labelManager.setDirty()}this._evaluateUpdatingState()}},_add:function(a){if(this.view.basemapTerrain.tilingScheme){for(var b=a.length,c=this._scaleRangeEnabled(),e=Array(b),d=Array(b),f=Array(b),h=0;h<b;h++){var k=a[h],g=k.geometry;if(null!=g&&(this._expandComputedExtent(g),g=this.getRenderingInfo(k)))if(d[h]=g.symbol,f[h]=g,g=this._getOrCreateGraphics3DSymbol(d[h],g.renderer))e[h]=g,this._beginGraphicUpdate(k)}for(h=0;h<b;h++)(k=e[h])&&k.then(function(a,b,e,d){this._graphicsBySymbol[b.id]||
(this._graphicsBySymbol[b.id]={});this._createCanvas3DGraphic(e,a,d,c);this._endGraphicUpdate(a);this.view.labelManager.setDirty()}.bind(this,a[h],d[h],k,f[h]),function(a){this._endGraphicUpdate(a)}.bind(this,a[h]))}},_getOrCreateGraphics3DSymbol:function(a,b){var c=this._symbols[a.id];if(!c){var e=G.toWeb3DSymbol(a,!0,!1);if(e){var d;if(b&&b.backgroundFillSymbol&&(c=G.toWeb3DSymbol(b.backgroundFillSymbol,!1,!0)))d=c.symbolLayers;c=new S(e,this._symbolCreationContext,d);this._symbols[a.id]=c}}return c},
_createCanvas3DGraphic:function(a,b,c,e){if(!this._graphics[b.id]){var d=a.createGraphics3DGraphic(b,c);this.layerLabelsEnabled()&&(d=this._createLabelsForGraphic(b,d,c));this._graphics[b.id]=d;this._graphicsKeys=null;this._graphicsBySymbol[a.symbol.id][b.id]=d;d.initialize(this._stageLayer,this._labelStageLayer,this._stage);if(a=d.isDraped())this.hasDraped=this._graphicsDrapedIds[b.id]=!0;d.centroid=null;"point"!==b.geometry.type&&d instanceof T&&(d.centroid=U.computeCentroid(b.geometry,this._viewSR));
c=!this.suspended;if(this._shouldAddToSpatialIndex(b,d,e)){var f=this._addGraphicToSpatialIndex(b,d);e&&f&&(c=c&&this._graphicVisibleAtScale(b,d))}e=d.setVisibilityFlag("VISIBILITY_SCALERANGE",c);b=d.setVisibilityFlag("VISIBILITY_GRAPHIC",b.visible);e!==b&&a&&this.emit("draped-data-change")}},_shouldAddToSpatialIndex:function(a,b,c){return c||b.mustAlignToTerrain()},_addGraphicsToSpatialIndex:function(){if(this._graphicsCollection)for(var a=this._graphicsCollection.toArray(),b=a.length,c=this._scaleRangeEnabled(),
e=0;e<b;e++){var d=a[e],f=this._graphics[d.id];f&&!f.addedToSpatialIndex&&this._shouldAddToSpatialIndex(d,f,c)&&this._addGraphicToSpatialIndex(d,f)}},_addGraphicToSpatialIndex:function(a,b){var c=a.geometry.spatialReference,e=this._viewSR,d={id:a.id};if(c.equals(e))d.geometry=a.geometry.toJSON(!0);else{if(c.wkid===F.WGS84.wkid&&e.isWebMercator)c=E.geographicToWebMercator(a.geometry);else if(c.isWebMercator&&e.wkid===F.WGS84.wkid)c=E.webMercatorToGeographic(a.geometry);else return console.warn("Cannot convert graphic geometry to map spatial reference, elevation and scale updates are disabled"),
!1;d.geometry=c.toJSON(!0)}this._spatialIndexNumGraphics++;this._spatialIndex.runProcess([d],this.layer.id);b.addedToSpatialIndex=!0},_recreateSymbol:function(a){var b=this._graphicsBySymbol[a],c=[],e=!1,d;for(d in b){var f=b[d];f.isDraped()&&(delete this._graphicsDrapedIds[d],e=!0);c.push(f.graphic);f.destroy();this._graphics[d]=null}this._graphicsBySymbol[a]={};this._symbols[a].destroy();this._symbols[a]=null;this._updateHasDraped();e&&this.emit("draped-data-change");this.add(c)},_clearSymbolsAndGraphics:function(){var a=
!1,b;for(b in this._graphics)a=a||this._graphics[b].isDraped(),this._graphics[b].destroy();this._graphics={};this._graphicsKeys=null;for(var c in this._symbols)this._symbols[c].destroy();this._symbols={};this._graphicsBySymbol={};this._elevationDirtyGraphicsSet={};this._elevationDirtyGraphicsQueue=[];this._updatingGraphicIds={};this._graphicsDrapedIds={};this.hasDraped=!1;a&&this.emit("draped-data-change");this.view.labelManager.setDirty();this.textTextureAtlas&&(this.textTextureAtlas.dispose(),this.textTextureAtlas=
null);this.hudMaterialCollection&&(this.hudMaterialCollection.dispose(),this.hudMaterialCollection=null)},_initLabelingInfo:function(){var a=new A;this.layer.then(function(){var b=this.layer.labelingInfo;if(b){this._labelClasses=Array(b.length);for(var c=[],e=0;e<b.length;e++){var d=this._getOrCreateGraphics3DSymbol(b[e].symbol);d.then(function(a,c){this._labelClasses[a]={labelClass:b[a],graphics3DSymbolLayer:c,graphics3DGraphics:[]}}.bind(this,e,d));c.push(d)}z(c).then(function(){a.resolve()})}else a.resolve()}.bind(this));
return a.promise},_createLabelsForGraphic:function(a,b,c){if(this._labelClasses&&0<this._labelClasses.length)for(var e=0;e<this._labelClasses.length;e++){var d=this._labelClasses[e];if(C.evaluateWhere(d.labelClass.where,a.attributes)){var f=d.labelClass.getLabelExpression();if(f&&(f=C.buildLabelText(f,a.attributes,this.layer.fields))){e=d.graphics3DSymbolLayer.childGraphics3DSymbols[0];c=this._evalLabelPlacementParams(a,b,c);null==this.textTextureAtlas&&(this.textTextureAtlas=new $(this.layer.id,
this._stage),this.hudMaterialCollection=new aa(this._stage));if(a=e.createGraphics3DGraphic(a,{text:f,centerOffset:c.centerOffset,translation:c.translation,screenOffset:c.screenOffset,anchor:c.anchor},this.hudMaterialCollection,this.textTextureAtlas))a._labelClass=d.labelClass,b.addLabelGraphic(a),d.graphics3DGraphics.push(b),a.setVisibilityFlag("VISIBILITY_LABEL_SHOW",this.layerLabelsEnabled()),this.view.labelManager.setInitialLabelGraphicState(a);break}}}return b},_evalLabelPlacementParams:function(a,
b,c){c=m[this.layer.labelingInfo[0].labelPlacement]||m["default"];if("polygon"===a.geometry.type||"polyline"===a.geometry.type||"extent"===a.geometry.type)return{anchor:"center"};if("point"!==a.geometry.type)return{anchor:c.anchor};var e=b.graphics3DSymbolLayer.symbol.symbolLayers[0];a={screenOffset:[0,0],centerOffset:[0,0,0,-1],translation:b.getCenterObjectSpace(),anchor:c.anchor};"Icon"===e.type?(e=b._graphics[0].getScreenSize(),b.isDraped()?a.anchor="center":(b=b._graphics[0].stageObject.getGeometryRecords()[0].materials[0],
b instanceof Y?(b=b.getParams(),a.screenOffset=[e[0]/2*(c.normalizedOffset[0]-2*(b.anchorPos[0]-0.5)),e[1]/2*(c.normalizedOffset[1]-2*(b.anchorPos[1]-0.5))]):a.screenOffset=[e[0]/2*c.normalizedOffset[0],e[1]/2*c.normalizedOffset[1]])):"Object"===e.type&&(b=b._graphics[0].getBoundingBoxObjectSpace(),e=[b[3]-b[0],b[4]-b[1],b[5]-b[2]],b=Math.max(e[0],e[1]),a.centerOffset[0]=1.1*b/2*c.normalizedOffset[0],a.translation[2]+=1.1*e[2]/2*c.normalizedOffset[1],b=g.length(e),a.centerOffset[2]=1.1*b/2*c.normalizedOffset[2]);
return a},_recreateAllGraphics:function(){this._clearSymbolsAndGraphics();this.computedExtent=null;this._updateSuspendResumeExtent();this._graphicsCollection&&this.view.basemapTerrain.tilingScheme&&this.add(this._graphicsCollection.toArray())},_rendererChange:function(a,b,c,e){this._symbolCreationContext.renderer=a;this._recreateAllGraphics()},_opacityChange:function(a){a=!1;for(var b in this._graphicsBySymbol){var c=this._graphicsBySymbol[b];this._symbols[b].layerPropertyChanged("opacity");if(!a)for(var e in c)if(c[e].isDraped()){this.emit("draped-data-change");
a=!0;break}}},layerLabelsEnabled:function(){return this.layer.get("labelsVisible")},_showLabelsChange:function(a){if(this.get("suspended"))this._showLabelsChangeOnResume=!0;else if(this._graphicsCollection){var b=this.layerLabelsEnabled();this._graphicsCollection.forEach(function(a){var e=this._graphics[a.id];if(e){if(b&&0===e._labelGraphics.length){var d=this.getRenderingInfo(a),e=this._createLabelsForGraphic(a,e,d);for(a=0;a<e._labelGraphics.length;a++)d=e._labelGraphics[a],d.initialize(this._labelStageLayer,
this._stage)}for(a=0;a<e._labelGraphics.length;a++)d=e._labelGraphics[a],d.setVisibilityFlag("VISIBILITY_LABEL_SHOW",b)}}.bind(this));this.view.labelManager.setDirty();this._showLabelsChangeOnResume=!1}},_elevationInfoChange:function(a){this._labelClasses&&this._labelClasses.forEach(function(a){a.graphics3DSymbolLayer.layerPropertyChanged("elevationInfo",{})});for(var b in this._graphicsBySymbol)if(a=this._graphicsBySymbol[b],this._symbols[b].layerPropertyChanged("elevationInfo",a))for(var c in a)for(var e=
a[c],d=e.graphic,e=e._labelGraphics,f=0;f<e.length;f++){var h=e[f];h.graphics3DSymbolLayer.updateGraphicElevationInfo(d,h)}else this._recreateSymbol(b)},_scaleUpdateHandler:function(a){if(!this.suspended&&0<this._spatialIndexNumGraphics){var b=a.extent,c=a.scale;this._spatialIndexNumPendingQueries++;this._spatialIndex.intersects(b,void 0,void 0,!0).then(function(a){this._spatialIndexNumPendingQueries--;for(var d=this._visibleAtScale(c),f=!1,h=a.results.length,k=0;k<h;k++){var g=this._graphics[a.results[k]];
if(g){var n=g.centroid;if(!n||!(b[0]>n.x||b[1]>n.y||b[2]<n.x||b[3]<n.y)){for(var n=g.setVisibilityFlag("VISIBILITY_SCALERANGE",d),m=0;m<g._labelGraphics.length;m++){var l=g._labelGraphics[m];if(l._labelClass&&null!=l._labelClass.minScale&&null!=l._labelClass.maxScale)var p=this._visibleAtScaleLabel(c,l._labelClass),n=n||l.setVisibilityFlag("VISIBILITY_SCALERANGE_LABEL",p)}n&&this.view.labelManager.setDirty();n&&g.isDraped()&&(f=!0)}}}f&&this.emit("draped-data-change")}.bind(this))}this._scaleVisibilityDirty=
!0},_visibleAtScaleLabel:function(a,b){return a>b.maxScale&&(!b.minScale||a<b.minScale)},_visibleAtScale:function(a){var b=this.layer.get("minScale"),c=this.layer.get("maxScale");return a>c&&(!b||a<b)},_graphicVisibleAtScale:function(a,b){var c;b.centroid?c=b.centroid:"point"===a.geometry.type&&(c=a.geometry);return c?(c=this.view.basemapTerrain?this.view.basemapTerrain.getScale(c):1,this._visibleAtScale(c)):!0},_scaleRangeEnabled:function(){var a=this.layer.get("minScale");return null!==a&&0<a&&
8E7>a||1E3<this.layer.get("maxScale")},_layerMinMaxScaleChangeHandler:function(){if(this.view.basemapTerrain){var a=this._scaleRangeEnabled();a&&!this._scaleChangeEventHandle?(this._scaleChangeEventHandle=this.view.basemapTerrain.on("scale-change",this._scaleUpdateHandler.bind(this)),this.suspended||this._addGraphicsToSpatialIndex()):!a&&this._scaleChangeEventHandle&&(this._scaleChangeEventHandle.remove(),this._scaleChangeEventHandle=null);this.suspended||this._updateGraphicsVisibility();this._scaleVisibilityDirty=
!0}},_graphicUpdateHandler:function(a){var b=this._graphics[a.graphic.id];if(b)switch(a.property){case "visible":b.setVisibilityFlag("VISIBILITY_GRAPHIC",a.newValue)&&(b.isDraped()&&this.emit("draped-data-change"),this.view.labelManager.setDirty())}},_updateGraphicsVisibility:function(){if(null!=this._graphicsCollection){var a=!1;this._graphicsCollection.forEach(function(b){var c=this._graphics[b.id];c&&(b=this._graphicVisibleAtScale(b,c),c.setVisibilityFlag("VISIBILITY_SCALERANGE",b)&&c.isDraped()&&
(a=!0))}.bind(this));a&&this.emit("draped-data-change");this.view.labelManager.setDirty()}},_hideAllGraphics:function(){if(this._graphicsCollection){var a=!1;this._graphicsCollection.forEach(function(b){(b=this._graphics[b.id])&&b.setVisibilityFlag("VISIBILITY_SCALERANGE",!1)&&b.isDraped()&&(a=!0)}.bind(this));a&&this.emit("draped-data-change");this.view.labelManager.setDirty()}},_updateSuspendResumeExtentEngine:function(){if(this._suspendResumeExtentEngineDirty){this._suspendResumeExtentEngineDirty=
!1;var a,b=this._suspendResumeExtent,c=this._suspendResumeExtentEngine,e=this.view.renderCoordsHelper.worldUpAtPosition;g.set3(b[0],b[1],s,c.extent[0].origin);g.set3(b[2],b[1],s,c.extent[1].origin);g.set3(b[2],b[3],s,c.extent[2].origin);g.set3(b[0],b[3],s,c.extent[3].origin);if(!this._renderSREqualsViewSR){var d=this._viewSR,f=this.view.renderSpatialReference;for(a=0;4>a;a++)q.vectorToVector(c.extent[a].origin,d,c.extent[a].origin,f)}g.add(c.extent[0].origin,c.extent[2].origin,c.center.origin);g.scale(c.center.origin,
0.5);e(c.center.origin,c.center.direction);for(a=0;4>a;a++)d=c.extent[a],e(d.origin,d.direction),f=c.extent[3==a?0:a+1],d.cap.next=f.origin,g.direction(f.origin,d.origin,d.cap.direction),g.cross(c.extent[a].cap.direction,c.extent[a].direction,c.planes[a]),c.planes[a][3]=-g.dot(c.planes[a],c.extent[a].origin);c.maxSpan=Math.max(Math.abs(b[0]-b[2]),Math.abs(b[1]-b[3]))}},_isVisibleInFrustumGlobal:function(){var a=this._suspendResumeExtentEngine,b=this.view.getFrustum();if(0>g.dot(a.center.direction,
b.direction))return!0;for(var c=0;4>c;c++)if(0>g.dot(a.extent[c].direction,b.direction))return!0;return!1},_isVisibleInFrustum:function(){var a=this.view.getFrustum();this._updateSuspendResumeExtentEngine();if(this._viewIsSpherical){if(this._suspendResumeExtentEngine.maxSpan>ca)return!0;if(a.altitude()>=da)return this._isVisibleInFrustumGlobal()}for(var b=0;b<this._suspendResumeExtentEngine.extent.length;b++){var c=this._suspendResumeExtentEngine.extent[b];if(x.frustumRay(a.planes,c.origin,null,c.direction)||
x.frustumLineSegment(a.planes,c.origin,c.cap.next,c.cap.direction))return!0}for(b=0;b<a.lines.length;b++)if(c=a.lines[b],x.frustumLineSegment(this._suspendResumeExtentEngine.planes,c.origin,c.endpoint,c.direction))return!0;return!1},_updateSuspendFrustumVisible:function(){if(this._suspendResumeExtent){var a=this._isVisibleInFrustum();a!==this._frustumVisibility&&(this._frustumVisibility=a,this.notifyChange("suspended"))}},_updateSuspendScaleVisibleFinish:function(a){this._scaleVisibilityQuery=!1;
this._scaleVisibility!==a&&(this._scaleVisibility=a,this.notifyChange("suspended"))},_updateSuspendScaleVisible:function(){var a=this.view.basemapTerrain;!this._suspendResumeExtent||!a||!this._scaleRangeEnabled()?this._updateSuspendScaleVisibleFinish(!0):this._scaleVisibilityQuery||(this._scaleVisibilityQuery=!0,a.queryVisibleScaleRange(this._suspendResumeExtent,this.layer.minScale,this.layer.maxScale,this._updateSuspendScaleVisibleFinish))},canResume:function(){return!this.inherited(arguments)||
!this._frustumVisibility||!this._scaleVisibility?!1:!0},_elevationUpdateHandler:function(a){a=a.extent;if(this.suspended){if(!this.updateElevation){var b=this.computedExtent;b&&(a[2]>b.xmin&&a[0]<b.xmax&&a[3]>b.ymin&&a[1]<b.ymax)&&(this.updateElevation=!0)}}else-Infinity===a[0]?this._markAllGraphicsElevationDirty():0<this._spatialIndexNumGraphics&&(this._spatialIndexNumPendingQueries++,this._spatialIndex.intersects(a,void 0,void 0,!0).then(function(a){this._spatialIndexNumPendingQueries--;a=a.results;
for(var b=a.length,d=0;d<b;d++){var f=a[d],h=this._graphics[f];h&&h.mustAlignToTerrain()&&this._markGraphicElevationDirty(f)}this._evaluateUpdatingState()}.bind(this)))},_markGraphicElevationDirty:function(a){this._elevationDirtyGraphicsSet[a]||(this._elevationDirtyGraphicsSet[a]=!0,this._elevationDirtyGraphicsQueue.push(a))},_markAllGraphicsElevationDirty:function(){for(var a in this._graphics)this._markGraphicElevationDirty(a);this._evaluateUpdatingState()},_evaluateUpdatingState:function(){var a=
this._elevationDirtyGraphicsQueue.length+Object.keys(this._updatingGraphicIds).length;this._progressMaxNumNodes=Math.max(a,this._progressMaxNumNodes);0===a&&(this._progressMaxNumNodes=1);this.updatingPercentage=this._graphicsControllerLoading||this._overlayUpdating?100:100*a/this._progressMaxNumNodes;this.updating=0<a||0<this._spatialIndexNumPendingQueries||this._graphicsControllerLoading||this._overlayUpdating},_beginGraphicUpdate:function(a){this._updatingGraphicIds[a.id]=!0;this.get("symbols-updating")||
this.set("symbols-updating",!0);this._evaluateUpdatingState()},_endGraphicUpdate:function(a){a&&delete this._updatingGraphicIds[a.id];this.get("symbols-updating")&&I.objectEmpty(this._updatingGraphicIds)&&(this.view.flushDisplayModifications(),this.set("symbols-updating",!1));this._evaluateUpdatingState()},_expandComputedExtent:function(a){var b,c,e,d,f,h;if("point"===a.type)b=c=a.x,e=d=a.y,a.z&&(f=h=a.z);else{h=a.extent;if(!h)return;b=h.xmin;c=h.xmax;e=h.ymin;d=h.ymax;f=h.zmin;h=h.zmax}var g=this._viewSR;
!a.spatialReference.equals(g)&&q.xyzToVector(b,e,0,a.spatialReference,l,g)&&(b=l[0],e=l[1],q.xyzToVector(c,d,0,a.spatialReference,l,g),c=l[0],d=l[1]);!isNaN(b)&&(!isNaN(c)&&!isNaN(e)&&!isNaN(d)&&!isNaN(f)&&!isNaN(h))&&((g=this.computedExtent)?(g.xmin=Math.min(b,g.xmin),g.xmax=Math.max(c,g.xmax),g.ymin=Math.min(e,g.ymin),g.ymax=Math.max(d,g.ymax)):this.computedExtent=g=new P(b,e,c,d,a.spatialReference),null!=f&&null!=h&&(g.zmin=null!=g.zmin?Math.min(f,g.zmin):f,g.zmax=null!=g.zmax?Math.max(h,g.zmax):
h),this._updateSuspendResumeExtent())},_updateSuspendResumeExtent:function(){if(this.computedExtent){this._suspendResumeExtent||(this._suspendResumeExtent=t.create());var a=this.computedExtent,b=this._suspendResumeExtent,c=0.5*a.width*(1.2-1),e=0.5*a.height*(1.2-1);a.width<1E-7*a.height?c+=e/20:a.height<1E-7*a.width&&(e+=c/20);t.set4(a.xmin-c,a.ymin-e,a.xmax+c,a.ymax+e,b)}else this._suspendResumeExtent=null;this._suspendResumeExtentEngineDirty=this._scaleVisibilityDirty=this._frustumVisibilityDirty=
!0},_updateHasDraped:function(){this.hasDraped=!1;for(var a in this._graphicsDrapedIds)if(this._graphicsDrapedIds.hasOwnProperty(a)){this.hasDraped=!0;break}},getStats:function(){var a=0,b=0,c=0,e=0,d;for(d in this._graphics){var f=this._graphics[d];f&&f.areVisibilityFlagsSet("VISIBILITY_SCALERANGE",null)&&a++;f&&f.areVisibilityFlagsSet("VISIBILITY_GRAPHIC",null)&&b++;f&&f.areVisibilityFlagsSet("VISIBILITY_SCALERANGE_LABEL",null)&&c++;f&&f.areVisibilityFlagsSet("VISIBILITY_LABEL_SHOW",null)&&e++}d=
"null";this._suspendResumeExtent&&(d=this._suspendResumeExtent.map(function(a){return a.toPrecision(4)}).join(", "));f="null";this.computedExtent&&(f=[this.computedExtent.xmin,this.computedExtent.ymin,this.computedExtent.xmax,this.computedExtent.ymax].map(function(a){return a.toPrecision(4)}).join(", "));return{numCollection:this._graphicsCollection&&this._graphicsCollection.toArray().length||null,numGraphics:this._graphics&&Object.keys(this._graphics).length||null,numDraped:this._graphicsDrapedIds&&
Object.keys(this._graphicsDrapedIds).length||null,numUpdatingGraphics:this._updatingGraphicIds&&Object.keys(this._updatingGraphicIds).length||null,numVisibleScale:a,numVisibleGraphic:b,numVisibleLabelScale:c,numVisibleShowLabels:e,numElevationDirty:this._elevationDirtyGraphicsQueue&&this._elevationDirtyGraphicsQueue.length||null,visibilityFrustum:this._frustumVisibility,resumeExtent:d,computedExtent:f,suspended:this.suspended}}});var m={"above-center":{normalizedOffset:[0,1,0],anchor:"bottom"},"above-left":{normalizedOffset:[-1,
1,0],anchor:"bottom-right"},"above-right":{normalizedOffset:[1,1,0],anchor:"bottom-left"},"below-center":{normalizedOffset:[0,-1,2],anchor:"top"},"below-left":{normalizedOffset:[-1,-1,0],anchor:"top-right"},"below-right":{normalizedOffset:[1,-1,0],anchor:"top-left"},"center-center":{normalizedOffset:[0,0,1],anchor:"center"},"center-left":{normalizedOffset:[-1,0,0],anchor:"right"},"center-right":{normalizedOffset:[1,0,0],anchor:"left"}};p={"above-center":["default","esriServerPointLabelPlacementAboveCenter"],
"above-left":["esriServerPointLabelPlacementAboveLeft"],"above-right":["esriServerPointLabelPlacementAboveRight"],"below-center":["esriServerPointLabelPlacementBelowCenter"],"below-left":["esriServerPointLabelPlacementBelowLeft"],"below-right":["esriServerPointLabelPlacementBelowRight"],"center-center":["esriServerPointLabelPlacementCenterCenter"],"center-left":["esriServerPointLabelPlacementCenterLeft"],"center-right":["esriServerPointLabelPlacementCenterRight"]};for(var K in p){var ea=m[K];p[K].forEach(function(a){m[a]=
ea})}Object.freeze&&(Object.freeze(m),Object.keys(m).forEach(function(a){Object.freeze(m[a]);Object.freeze(m[a].normalizedOffset)}));return u});