// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/typescript ../../../core/watchUtils ../../../core/promiseUtils ../../../core/lang dojo/_base/lang dojox/color dojo/has ../../layers/LayerView ../../../Graphic ../../../symbols/Symbol3D ./i3s/I3SUtil ./i3s/I3SProjectionUtil ./support/LayerViewUpdatingPercentage ../support/projectionUtils ../support/aaBoundingBox ../webgl-engine/Stage ../webgl-engine/lib/Layer ../webgl-engine/lib/Geometry ../webgl-engine/lib/GeometryData ../webgl-engine/lib/Object3D ../webgl-engine/lib/Texture ../webgl-engine/materials/Material ../webgl-engine/lib/Util ../webgl-engine/lib/base64Binary ../lib/glMatrix".split(" "),
function(ra,sa,ba,L,M,Q,G,ca,da,ea,fa,ga,U,ha,B,R,ia,S,V,T,ja,ka,la,ma,K,na,u,ta,A){function W(l,b){var a=!1,d;b.encoding===B.DDS_ENCODING_STRING?d=K.DDS_ENCODING:a=!(X(l.width)&&X(l.height));var e=b.usedByEngineMats.some(function(a){return a.getParams().atlasRegions});return{mipmap:!e&&!b.atlas&&!a,wrapClamp:e||b.atlas||!b.wrap,encoding:d,noUnpackFlip:!0}}function Y(l,b){for(var a=b.toLowerCase(),d=0,e=Object.keys(l);d<e.length;d++){var c=e[d];if(c.toLowerCase()===a)return l[c]}return null}var w=
u.assert,oa=u.clamp,X=u.isPowerOfTwo,N=u.fallbackIfUndefined,O=u.objectEmpty,r=u.VertexAttrConstants,l=T.ModelContentType,pa=[0.8,0.8,0.8],qa=[0.5,0.5,0.5],C=1,P=null;return function(u){function b(){u.apply(this,arguments)}ba(b,u);b.prototype.initialize=function(){var a=this.layer.version,a=!fa("trident")||1<a.major||1===a.major&&3<a.minor;this.useCompressedTextures=this.view.has("s3tc")&&a;this._initGraphicsController();this.dbg=!1;this.maxGpuMemory=1E3;this.geoMemoryEstimate=this.texMemoryEstimate=
this.gpuMemoryEstimate=0;this._stage=this.view._stage;this._matId2Meta={};this._texId2Meta={};this._requestedTexImageIds={};this._nodeId2Meta={};this._colorOverride=null;for(var a=new Uint8Array(256),d=0;d<a.length;d++)a[d]=255;this._whiteTexture=new K(a,"white",{width:8,height:8});this._stage.add(T.ModelContentType.TEXTURE,this._whiteTexture);this._layerEventHandles=[Q.init(this.layer,"renderer",this._rendererChange.bind(this)),Q.watch(this.layer,"opacity",this._opacityChange.bind(this)),Q.init(this.view,
"clippingArea",this._clippingAreaChanged.bind(this))];this._addThisLayerToStage();this.setVisibility(!this.suspended);this.debugLODVis=this.debugNodeVis=!1};b.prototype.destroy=function(){this._stage.remove(T.ModelContentType.TEXTURE,this._whiteTexture.getId());this._removeThisLayerFromStage();this._layerEventHandles.forEach(function(a){a.remove()});this._stage=null;this._controller.destroy();this._nodeId2Meta=this._texId2Meta=this._matId2Meta=null};b.prototype.memEstimateTextureAdded=function(a){a=
a.getEstimatedTexMemRequiredMB();this.gpuMemoryEstimate+=a;this.texMemoryEstimate+=a};b.prototype.memEstimateTextureRemoved=function(a){a=a.getEstimatedTexMemRequiredMB();this.gpuMemoryEstimate-=a;this.texMemoryEstimate-=a};b.prototype.memEstimateGeometryAdded=function(a){a=a.estimateGpuMemoryUsage()/1E6;this.gpuMemoryEstimate+=a;this.geoMemoryEstimate+=a};b.prototype.memEstimateGeometryRemoved=function(a){a=a.estimateGpuMemoryUsage()/1E6;this.gpuMemoryEstimate-=a;this.geoMemoryEstimate-=a};b.prototype.isBundleAlreadyAddedToStage=
function(a,d){var e=!1,c=!1;if(null!=this._nodeId2Meta[a.id]&&this._nodeId2Meta[a.id].engineObjectsPerBundle&&this._nodeId2Meta[a.id].engineObjectsPerBundle[d])for(var c=!0,h=this._nodeId2Meta[a.id].engineObjectsPerBundle[d],m=0;m<h.length&&!(e=h[m].isPartiallyHidden());m++);return{wasPartiallyHidden:e,alreadyLoaded:c}};b.prototype._initGraphicsController=function(){var a=this,d={addBundle:this._addBundle.bind(this),isBundleAlreadyAddedToStage:this.isBundleAlreadyAddedToStage.bind(this),isOverMemory:this.isOverMemory.bind(this),
removeNodeData:this._removeNodeDataFromStage.bind(this),removeFeatures:this._removeFeatures.bind(this),getAddedFeatures:this._getAddedFeatures.bind(this),areAllBundlesLoaded:this._areAllBundlesLoaded.bind(this),wholeNodeSwitchEnabled:!0},e={additionalStartNodeLoadingHandler:this._startNodeLoading.bind(this),additionalCancelNodeLoadingHandler:this.cancelNodeLoading.bind(this),getTexturePrefetchFunctions:function(){return{_calcDesiredTextureLOD:a._calcDesiredTextureLOD.bind(a),_imageIsPartOfTextureBundle:a._imageIsPartOfTextureBundle.bind(a),
_matId2Meta:a._matId2Meta,_texId2Meta:a._texId2Meta,useCompressedTextures:function(){return a.useCompressedTextures}}},_nodeDebugVisualizer:this._nodeDebugVisualizer,setPolygonOffset:this._setPolygonOffset.bind(this),traversalOptions:{initDepthFirst:!0,neighborhood:!0,perLevelTraversal:!1,allowPartialOverlaps:!1},getLoadedAttributes:this.getLoadedAttributes.bind(this),setAttributeData:this.setAttributeData.bind(this)};this.layer.createGraphicsController({layerView:this,layerViewRequiredFunctions:d,
layerViewOptionalFunctions:e})};b.prototype.setMaxGpuMemory=function(a){this.maxGpuMemory=a};b.prototype.setVisibility=function(a){if(this._stage&&this._engineLayer){var d=this._engineLayer.getId(),e=0<=this._stage.getViewContent().indexOf(d);!!a!==e&&(d=[d],null!=this._nodeDebugVisualizer&&d.push(this._nodeDebugVisualizer.engineLayer.getId()),a?this._stage.addToViewContent(d):this._stage.removeFromViewContent(d))}};b.prototype.getEngineLayer=function(){return this._engineLayer};b.prototype.getStats=
function(){var a={nodesInIndex:0,knownFeatures:0,displayedFeatures:0,displayedGeometries:0,displayedComponents:0,geometryDataSize:0,activeMaterials:0};if(!this._controller)return a;for(var d in this._controller.nodeIndex)if(this._controller.nodeIndex.hasOwnProperty(d)){a.nodesInIndex++;var e=this._controller.nodeIndex[d];if(null!=e.features)for(var c=0;c<e.features.length;c++)a.knownFeatures++}a.activeMaterials=Object.keys(this._matId2Meta).length;return a};b.prototype._addThisLayerToStage=function(){var a=
this._stage;this._initTexture=new K(null,"i3sInitTexture");a.add(l.TEXTURE,this._initTexture);var d=this.layer.id;this._engineLayer=d=new ja(d,{},d);a.add(l.LAYER,d);null!=this._nodeDebugVisualizer&&this._nodeDebugVisualizer.dispose()};b.prototype._removeThisLayerFromStage=function(){this.cancelNodeLoading();if(null!=this._engineLayer){var a=this._stage;a.remove(l.TEXTURE,this._initTexture.getId());for(var d in this._controller.nodeIndex)this._controller.nodeIndex.hasOwnProperty(d)&&(this._removeNodeDataFromStage(this._controller.nodeIndex[d]),
delete this._controller.nodeIndex[d]);w(O(this._nodeId2Meta));w(O(this._matId2Meta));w(O(this._texId2Meta));a.remove(l.LAYER,this._engineLayer.getId());null!=this._nodeDebugVisualizer&&this._nodeDebugVisualizer.dispose();this._nodeDebugVisualizer=void 0;this._matId2Meta={};this._texId2Meta={};this._requestedTexImageIds={};this._nodeId2Meta={};this._engineLayer=void 0;this.gpuMemoryEstimate=0}};b.prototype._startNodeLoading=function(){this._updateAllTextureLOD()};b.prototype.cancelNodeLoading=function(){null!=
this._nodeDebugVisualizer&&this._nodeDebugVisualizer.clear();this._requestedTexImageIds={}};b.prototype._isAllHidden=function(a){a=this._nodeId2Meta[a.id].engineObjects;for(var d=0;d<a.length;d++)if(!a[d].isAllHidden())return!1;return!0};b.prototype.getLoadedAttributes=function(a){if((a=this._nodeId2Meta[a.id])&&1===a.engineObjects.length)return a.engineObjects[0].getMetadata().loadedAttributes};b.prototype.setAttributeData=function(a,d,e){if((a=this._nodeId2Meta[a.id])&&1===a.engineObjects.length){a=
a.engineObjects[0];var c=a.getMetadata();c.loadedAttributes=d;c.attributeData=e;this._setObjectSymbology(a)}};b.prototype._createUnitTestData=function(a){var d=this.view.navigation.targetCamera,d={viewParams:{eye:d.eye,center:d.center,up:d.up,viewMatrix:d.viewMatrix,projectionMatrix:d.projectionMatrix,fovX:d.fovX,viewport:d.viewport,perPixelRatio:d.perPixelRatio},visibleObjects:[]};a=a.getAll("objects");for(var e in a){var c=a[e];if(c.getParentLayer()===this._engineLayer){var h=c.getMetadata(),c=
h.i3sNode,h=h.features.map(function(a){return a.id});h.sort();d.visibleObjects.push({featureIDs:h,nodeId:c})}}console.debug(""+d.visibleObjects.length);return JSON.stringify(d)};b.prototype.isOverMemory=function(){return this.gpuMemoryEstimate>this.maxGpuMemory?(console.warn("over memory: "+this.gpuMemoryEstimate+" tex "+this.texMemoryEstimate+" geom "+this.geoMemoryEstimate),!0):!1};b.prototype._getAddedFeatures=function(a){if(null==this._nodeId2Meta[a])return null;var d=[];a=this._nodeId2Meta[a].engineObjects;
for(var e=0;e<a.length;e++)d=d.concat(a[e].getMetadata().features);return d};b.prototype._calcEngineMaterialTransparencyParams=function(a,d,e){var c=this.layer.opacity;null==c&&(c=1);var h=1-oa(N(d.transparency,0),0,1),c=c*h;a=1>c||a&&ca.endsWith(a.channels,"a")||!0===d.useVertexColorAlpha||e;return{opacity:c,transparent:a}};b.prototype._calcEngineMaterialDoubleSidedParams=function(a){return null!=a.doubleSided?a.doubleSided:!0};b.prototype._calcEngineMaterialCullFaceParams=function(a){return a.cullFace?
a.cullFace:null!=a.doubleSided?a.doubleSided?"none":"back":"none"};b.prototype._createEngineMaterial=function(a,d,e,c,h,m){var k,g;null!=a&&(k=(g=this._texId2Meta[d])&&g.engineTex?g.engineTex.getId():this._initTexture.getId());var f=e.params,b=N(f.diffuse,pa),n,q;null!=a&&(q=B.getAppropriateTextureEncoding(a.encoding,this.useCompressedTextures),n=-1<q?a.encoding[q]:a.encoding);var p="";"standard"!==e.type&&(p+="Unknown material type '"+e.type+"', must be 'standard'");void 0===f.reflectivity&&(p+=
"Material parameter 'reflectivity' is missing.");0<p.length&&this.layer.warningEvent(p,1);e={ambient:this._colorOverride||b,diffuse:this._colorOverride||b,specular:N(f.specular,qa),shininess:N(f.shininess,64),atlasRegions:f.vertexRegions,textureId:k&&this._colorOverride?this._whiteTexture.getId():k,vertexColors:!0,flipV:!1,doubleSided:this._calcEngineMaterialDoubleSidedParams(f),cullFace:this._calcEngineMaterialCullFaceParams(f)};k=this._calcEngineMaterialTransparencyParams(a,f);da.mixin(e,k);e=new na(e,
c);e.metadata={i3sMatId:c,i3sTexId:d,i3sTex:a,i3sMatParams:f};if(null!=a){g?g.usedByEngineMats.push(e):(g={id:d,featureMBS:{},usedByEngineMats:[e],images:a.images,encoding:n,encodingIdx:q,atlas:!0===a.atlas,wrap:"none"!==a.wrap[0]||"none"!==a.wrap[1]},this._texId2Meta[d]=g);for(a=0;a<h.length;a++)f=h[a],g.featureMBS[f.id]=f.engineMBS;if(void 0!==m[d]){null==g.engineTex&&(h=m[d].data,a=W(h,g),g.engineTex=new K(h,g.id,a),this._stage.add(l.TEXTURE,g.engineTex),g.desiredLOD=m[d].desiredLOD,g.curLOD=g.desiredLOD,
this.memEstimateTextureAdded(g.engineTex));h=g.engineTex.getId();for(a=0;a<g.usedByEngineMats.length;a++)f=g.usedByEngineMats[a],null==this._colorOverride&&f.setParameterValues({textureId:h}),f.metadata.originalTextureId=h;m[d].createdTextureForDomImage();delete m[d]}else this._updateTextureLOD(g)}this._matId2Meta[c]||(this._matId2Meta[c]={});this._matId2Meta[c][d]={engineMat:e,refCount:1};return e};b.prototype._createVertexAndIndexArrays=function(a,d,e){var c,h=a.params.vertexAttributes,m={},k;for(k in h)if(h.hasOwnProperty(k)&&
"classification"!==k){var g=h[k];c=B.valueType2TypedArrayClassMap[g.valueType];w(null!=c,"unsupported vertex attribute value type: "+g.valueType);m[k]={data:new c(d,g.byteOffset,g.count*g.valuesPerElement),size:g.valuesPerElement}}if(null==m[r.COLOR]){c=B.valueType2TypedArrayClassMap.UInt8;m[r.COLOR]={data:new c(4*h.position.count),size:4};for(var f=0;f<m[r.COLOR].data.length;f++)m[r.COLOR].data[f]=0===f%3?255:0}k=!1;null==m[r.NORMAL]&&(k=!0,c=B.valueType2TypedArrayClassMap.Float32,m[r.NORMAL]={data:new c(3*
h.position.count),size:3});var h=[],g=a.params.faces,b;if(null!=g&&"PerAttributeArray"!==a.params.topology){var n={};for(name in g)g.hasOwnProperty(name)&&(c=g[name],w(0===c.count%3),w(c.count===g.position.count),w("UInt32"===c.valueType),n[name]=c.byteOffset);var q=a.params.components.length;b=Array(q);for(var p=g.position.componentIndices||[0],l=0;l<q;l++){var s=a.params.components[l],t=l<q-1?p[l+1]-p[l]:g.position.count-p[l];c={type:"triangle",positionKey:"position",indices:{},componentRange:[p[l],
p[l]+t]};for(name in g)g.hasOwnProperty(name)&&(c.indices[name]=new Uint32Array(d,n[name],t),n[name]+=4*t);if(null==c.indices[r.COLOR]){c.indices[r.COLOR]=new Uint32Array(t);for(f=0;f<t;f++)c.indices[r.COLOR][f]=f}if(k&&null==c.indices[r.NORMAL]){c.indices[r.NORMAL]=new Uint32Array(t);for(f=0;f<t;f++)c.indices[r.NORMAL][f]=f}b[l]=c;var f=s.textureID||"none",v=void 0;"none"!==f&&(v=e.textureDefinitions[f],w(void 0!==v,"geometry wants unknown texture "+f));if(v&&!0===v.atlas&&null!=v.regions){w(0<v.regions.length,
"texture marked as atlas carries no region definition");f=v.regions[s.regionID].subimageRegion;h=h.concat([65536*f[0],65536*(f[2]-f[0]),65536*(1-f[3]),65536*(f[3]-f[1])]);f=new Uint32Array(t);for(s=0;s<t;s++)f[s]=h.length/4-1;c.indices[r.REGION]=f}}}else{c={type:"triangle",positionKey:"position",indices:{}};a=m.position.data.length/m.position.size;if(a>C||null==P){for(;a>C;)C*=2;P=new Uint32Array(C);for(f=0;f<C;f++)P[f]=f}a=new Uint32Array(P.buffer,0,a);for(b in m)c.indices[b]=a;a=c.indices[c.positionKey];
c.componentRange=[0,null!=a?a.length-1:0];b=[c]}0<h.length&&(a=new Uint16Array(h),m[r.REGION]={data:a,size:4});return{indexArrays:b,vertexArrays:m}};b.prototype._createEngineMats=function(a,d,e,c,h){for(var m=a.params.components.length,k=Array(m),g=0;g<m;g++){var f=a.params.components[g],b=f.materialID,n=e.materialDefinitions[b];null!=n.href&&(n=c[n.hrefConcat].materialDefinitions[b]);w(void 0!==n,"geometry wants unknown material "+b);var q=f.textureID||"none",p=void 0;"none"!==q&&((null==e.textureDefinitions||
null==e.textureDefinitions[q])&&this.layer.warningEvent("textureDefinitions missing in shared resource",1),p=e.textureDefinitions[q]);f=void 0;this._matId2Meta[b]&&this._matId2Meta[b][q]?(b=this._matId2Meta[b][q],f=b.engineMat,b.refCount++):f=this._createEngineMaterial(p,q,n,b,d,h);k[g]=f}return k};b.prototype._areAllBundlesLoaded=function(a,d){if(null==this._nodeId2Meta[a.id]||null==this._nodeId2Meta[a.id].engineObjectsPerBundle)return!1;for(var e=0;e<a.featureData.length;e++){if(null==this._nodeId2Meta[a.id].engineObjectsPerBundle[e])return!1;
if(!d)for(var c=this._nodeId2Meta[a.id].engineObjectsPerBundle[e],h=0;h<c.length;h++)if(c[h].isPartiallyHidden())return!1}return!0};b.prototype._getObjectIdField=function(){return this.layer.objectIdField||"OBJECTID"};b.prototype._findGraphic=function(a){a=Y(a.attributes,this._getObjectIdField());for(var d=0,e=Object.keys(this._nodeId2Meta);d<e.length;d++)for(var c=e[d],h=this._nodeId2Meta[c].engineObjects,m=0;m<h.length;m++){var b=h[m].getMetadata().featureIds.indexOf(a);if(-1!==b)return{node:this._controller.nodeIndex[c],
nodeId:c,bundleNr:m,index:b}}return null};b.prototype.whenGraphicBounds=function(a){var d=this._findGraphic(a);if(null!=d){a=this._nodeId2Meta[d.nodeId].engineObjects[d.bundleNr];for(var d=a.getMetadata().faceRanges[d.index],d=a.geometries[0].calculateBoundingInfo(0,d),e=d.bbMin,c=d.bbMax,d=[],h=0;8>h;++h){var b=[h&1?e[0]:c[0],h&2?e[1]:c[1],h&4?e[2]:c[2]];A.mat4d.multiplyVec3(a.objectTransformation,b);d[3*h]=b[0];d[3*h+1]=b[1];d[3*h+2]=b[2]}if(S.bufferToBuffer(d,this.view.renderSpatialReference,0,
d,this.view.spatialReference,0,8)){a=V.create(V.NEGATIVE_INFINITY);for(e=0;e<d.length;e+=3)for(c=0;3>c;c++)a[c]=Math.min(a[c],d[e+c]),a[c+3]=Math.max(a[c+3],d[e+c]);return G.resolve(a)}}return G.reject()};b.prototype.whenGraphicAttributes=function(a,d){var e=this,c=Y(a.attributes,this._getObjectIdField());return B.whenGraphicAttributes(this.layer,a,c,d,function(){return e._findGraphic(a)})};b.prototype.getGraphicsFromStageObject=function(a,d){var e=a.getMetadata(),c=a.getFaceRangeIndexFromTriangleNr(d);
if(null!=c&&null!=e.graphics&&null!=e.graphics[0].attributes)return G.resolve(e.graphics[c]);if(null!=c&&null!=e.featureIds&&null!=e.featureIds[c]){var h={};h[this._getObjectIdField()]=e.featureIds[c];for(var b=0,k=Object.keys(e.attributeData);b<k.length;b++){var g=k[b];h[g]=e.attributeData[g][c]}e=new U(null,null,h);e.layer=this.layer;return G.resolve(e)}return G.reject()};b.prototype._calculateNormals=function(a,d){var e=d.normal,c=d.position,h=a[0].indices.normal,b=a[0].indices.position;w(h.length===
b.length);for(var k=A.vec3.create(),g=A.vec3.create(),f=0;f<b.length;f+=3){var l=3*b[f],n=c.data[l],q=c.data[l+1],p=c.data[l+2],l=3*b[f+1];k[0]=c.data[l]-n;k[1]=c.data[l+1]-q;k[2]=c.data[l+2]-p;l=3*b[f+2];g[0]=c.data[l]-n;g[1]=c.data[l+1]-q;g[2]=c.data[l+2]-p;A.vec3.cross(k,g,k);A.vec3.normalize(k);for(l=0;3>l;l++)n=3*h[f+l],e.data[n]=k[0],e.data[n+1]=k[1],e.data[n+2]=k[2]}};b.prototype._addBundle=function(a,d,e,c,h,b,k){if(!0===this.debugNodeVis&&null!=this._nodeDebugVisualizer){var g="grey";switch(a.level){case 1:g=
"red";break;case 2:g="green";break;case 3:g="blue";break;case 4:g="yellow";break;case 5:g="magenta";break;case 6:g="brown"}this._nodeDebugVisualizer.show(a,this._controller.crsIndex,g)}var g=this._stage,f={};f[l.OBJECT]={};f[l.GEOMETRY]={};f[l.MATERIAL]={};f[l.TEXTURE]={};var Z=this._engineLayer,n=Z.getId(),q=c[a.sharedResource.hrefConcat];if(null!=this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjectsPerBundle&&this._nodeId2Meta[a.id].engineObjectsPerBundle[k])this._hideFaceRangesOutsideBoundingBox(a,
this._clippingArea),null!=h&&h.done();else if(!this.isOverMemory()){null==this._nodeId2Meta[a.id]&&(this._nodeId2Meta[a.id]={engineObjects:[],engineObjectsPerBundle:[]});this._nodeId2Meta[a.id].engineObjectsPerBundle[k]=[];if(null!=d){for(var p=0;p<d.length;p++){var r=d[p].geometries,s=d[p].features,t=d[p].featureDataAttributes,v=c[a.geometryData[k].hrefConcat];w(v instanceof ArrayBuffer,"I3S: geometry data is not an ArrayBuffer");null==v._isReprojected&&(v._isReprojected={});for(var $=s[0].id.toString(),
aa=[],H=[],I=[],u=void 0,y=0;y<r.length;++y){var z=r[y],x=this._createVertexAndIndexArrays(z,v,q);if(0!==x.indexArrays.length){var B=this._createEngineMats(z,s,q,c,b),u=R.reprojectPoints(this._controller.isMeshPyramid?R.ReprojectionTypes.PER_VERTEX:R.ReprojectionTypes.BOUNDINGBOX,x.vertexArrays.position.data,x.vertexArrays.normal.data,a.mbs,v._isReprojected[z.id],this._controller.crsIndex,this._controller.crsVertex,this.view.renderSpatialReference);v._isReprojected[z.id]=!0;this._controller.isMeshPyramid&&
this._calculateNormals(x.indexArrays,x.vertexArrays);z=A.mat4d.create(z.transformation);A.mat4d.multiply(u.localTrafo,z,z);for(var F=0;F<B.length;F++){var D=B[F];f[l.MATERIAL][D.getId()]=D}x=new ka(new la(x.indexArrays,x.vertexArrays),$+"_"+y);this.memEstimateGeometryAdded(x.getData());f[l.GEOMETRY][x.getId()]=x;aa[y]=x;H[y]=z;I[y]=B}}r=[];for(v=0;v<s.length;v++)y=new U(void 0,void 0,t[v]),y.set("layer",this.layer),r.push(y);s=new ma({idHint:a.id,name:$,geometries:aa,materials:I,transformations:H,
castShadow:!0,metadata:{graphics:r,i3sNode:a.id,ceLayer:n,features:s,faceRanges:d[p].faceRanges,featureIds:d[p].featureIds,attributeData:e?e.attributeData:null,loadedAttributes:e?e.loadedAttributes:null,layerId:this.layer.id}});t=A.mat4d.create();A.mat4d.identity(t);A.mat4d.multiply(t,u.globalTrafo,t);s.setObjectTransformation(t);this._nodeId2Meta[a.id].engineObjectsPerBundle[k].push(s);this._nodeId2Meta[a.id].engineObjects.push(s);f[l.OBJECT][s.getId()]=s;this._setObjectSymbology(s);null!=this._clippingArea&&
this._hideFaceRangesOutsideBoundingBox(a,this._clippingArea)}g.beginMod();a=f[l.OBJECT];for(var E in a)a.hasOwnProperty(E)&&Z.addObject(a[E]);for(var J in f)if(f.hasOwnProperty(J))for(name in E=f[J],E)E.hasOwnProperty(name)&&null==g.get(J,name)&&g.add(J,E[name]);g.endMod()}null!=h&&h.done()}};b.prototype._clippingAreaChanged=function(){var a=this,d=[];S.extentToBoundingBox(this.view.clippingArea,d,this.view.renderSpatialReference)?this._clippingArea=d:this._clippingArea=null;if(this._controller){var e=
this._controller.nodeIndex;e&&Object.keys(this._nodeId2Meta).forEach(function(d){return a._hideFaceRangesOutsideBoundingBox(e[d],a._clippingArea)});this._controller.updateClippingArea(this.view.clippingArea)}};b.prototype._hideFaceRangesOutsideBoundingBox=function(a,d){if(this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjects){var e=[0,0,0,0];S.mbsToMbs(a.mbs,this._controller.crsIndex,e,this.view.renderSpatialReference);for(var e=null!=d?B.intersectBoundingBoxWithMbs(d,e):2,c=this._nodeId2Meta[a.id].engineObjects,
h=0;h<c.length;h++){var b=c[h];if(0===e)b.hideAllFaceRanges();else if(b.unhideAllFaceRange(),2!==e){var k=b.getObjectTransformation(),g=b.getGeometryRecords()[0].transformation;A.mat4d.multiply(k,g);if(!(0!==k[1]||0!==k[2]||0!==k[3]||0!==k[4]||0!==k[6]||0!==k[7]||0!==k[8]||0!==k[9]||0!==k[11]||1!==k[15])){for(var g=(d[0]-k[12])/k[0],f=(d[1]-k[13])/k[5],l=(d[2]-k[14])/k[10],n=(d[3]-k[12])/k[0],q=(d[4]-k[13])/k[5],k=(d[5]-k[14])/k[10],p=b.getGeometryRecords()[0].geometry.getData(),r=p.getFaces()[0].indices.position,
p=p.getVertexAttr().position.data,s=[],t=b.getMetadata().faceRanges,v=void 0,w=void 0,u=void 0,H=void 0,I=void 0,C=void 0,y=0;y<t.length;y+=1){for(var z=t[y],x=z[0],G=z[1],v=w=u=Number.MAX_VALUE,H=I=C=-Number.MAX_VALUE;x<=G;x+=1)for(var F=0;3>F;F+=1)var D=3*r[3*x+F],E=p[D],J=p[D+1],D=p[D+2],v=Math.min(E,v),w=Math.min(J,w),u=Math.min(D,u),H=Math.max(E,H),I=Math.max(J,I),C=Math.max(D,C);(v>n||H<g||w>q||I<f||u>k||C<l)&&s.push(z)}0<s.length&&b.hideFaceRange(b.getGeometryRecords()[0],s)}}}}};b.prototype._hideFeatures=
function(a,d){for(var e=this._nodeId2Meta[a.id].engineObjects,c=0;c<e.length;c++){for(var h=e[c],b=[],k=h.getMetadata().features,g=h.getMetadata().faceRanges,f=0;f<d.length;f++)for(var l=d[f],n=0;n<k.length;n++)l===k[n].id&&(null!=g&&1===h.getGeometryRecords().length?b.push(g[n]):h.hideAllFaceRanges());0<b.length&&h.hideFaceRange(h.getGeometryRecords()[0],b)}};b.prototype._removeFeatures=function(a,d){null!=this._nodeId2Meta[a.id]&&(this._hideFeatures(a,d),!0===this._isAllHidden(a)&&this._removeNodeDataFromStage(a))};
b.prototype._removeNodeDataFromStage=function(a){if(!(null==this._nodeId2Meta[a.id]||null==this._nodeId2Meta[a.id].engineObjects)){for(var d=this._stage,e=this._engineLayer,c=this._nodeId2Meta[a.id].engineObjects,b=0;b<c.length;++b){var m=c[b];e.removeObject(m);for(var k=m.getGeometryRecords(),g=0;g<k.length;g++){var f=k[g];this.memEstimateGeometryRemoved(f.geometry.getData());d.remove(l.GEOMETRY,f.geometry.getId());for(var r=0;r<f.materials.length;r++){var n=f.materials[r],q=n.getId(),p=n.metadata.i3sMatId,
u=n.metadata.i3sTexId||"none",s=this._matId2Meta[p][u];w(0<s.refCount);s.refCount--;0===s.refCount&&this._removeMaterial(q,u,p,n,d)}}d.remove(l.OBJECT,m.getId())}delete this._nodeId2Meta[a.id]}};b.prototype._removeMaterial=function(a,d,e,c,b){b.remove(l.MATERIAL,a);if("none"!==d){a=this._texId2Meta[d];var m=a.usedByEngineMats;c=m.indexOf(c);w(-1<c);m[c]=m[m.length-1];m.pop();if(1>m.length){if((c=a.engineTex)&&c!==this._initTexture)this.memEstimateTextureRemoved(c),b.remove(l.TEXTURE,a.engineTex.getId());
a.engineTex=void 0;a.desiredLOD=-1;a.curLOD=-1;delete this._texId2Meta[d]}}delete this._matId2Meta[e][d];O(this._matId2Meta[e])&&delete this._matId2Meta[e]};b.prototype._updateAllTextureLOD=function(){for(var a in this._texId2Meta)this._texId2Meta.hasOwnProperty(a)&&this._updateTextureLOD(this._texId2Meta[a])};b.prototype._calcDesiredTextureLOD=function(a,d){var e,c=0;for(e in a)if(a.hasOwnProperty(e)){var b=a[e],b=2*b[3]/A.vec3.dist(b,this._controller.camPos)*this._controller.screenSizeFactor;b>
c&&(c=b)}c/=9;for(e=d.length-1;0<e&&d[e].size<c;)e--;return e};b.prototype._updateTextureLOD=function(a){var d=this;a.desiredLOD=this._calcDesiredTextureLOD(a.featureMBS,a.images);if(a.curLOD!==a.desiredLOD&&(0>a.curLOD||!a.curLOD||0===a.desiredLOD||a.desiredLOD>a.curLOD||a.desiredLOD<a.curLOD-1)){if(0===a.images.length)return;var e=a.images[a.desiredLOD],c=-1<a.encodingIdx?e.hrefConcat[a.encodingIdx]:e.hrefConcat;if(!this._requestedTexImageIds[e.id]){var b={metadata:{texMeta:a,image:e}};this._requestedTexImageIds[e.id]=
!0;this._imageIsPartOfTextureBundle(e)?this._controller.streamDataSupplier.request(c,"binary",b).then(this._extractTextureImageFromBlob.bind(this)):this._controller.streamDataSupplier.request(c,"image",b).then(function(a,c,e,b){d._textureImageLoaded(a,c,b.image,b.texMeta)})}}a.engineTex||(a.engineTex=this._initTexture,a.curLOD=-1);if(this.debugLODVis){e=ea.fromHsv(270*(a.desiredLOD/a.images.length),100,100).toRgb().map(function(a){return a/255});for(c=0;c<a.usedByEngineMats.length;c++)a.usedByEngineMats[c].setParameterValues({ambient:e,
diffuse:e})}};b.prototype._extractTextureImageFromBlob=function(a,d,e,c){var b=c.texMeta;if(0>b.desiredLOD||c.image.size>b.images[b.desiredLOD].size)delete this._requestedTexImageIds[c.image.id];else{var m=this;w("binary"===e);var k="";try{var g=e=0;-1<b.encodingIdx?(e=c.image.byteOffset[b.encodingIdx],g=c.image.length[b.encodingIdx]):(e=c.image.byteOffset,g=c.image.length);var f=new Uint8Array(d,e,g),l=new Blob([f],{type:b.encoding}),k=window.URL.createObjectURL(l)}catch(n){k="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAIElEQVQ4T2P8zyD6n4ECwDhqAMNoGDCMhgEwDw2DdAAAdzkhQdS8dl8AAAAASUVORK5CYII\x3d",
console.error("error loading texture "+a+" "+n)}var q=new Image;q.onerror=function(){window.URL.revokeObjectURL(k);q.src="";q.onerror=void 0;q.onload=void 0};q.onload=function(){m._controller.queueAnimationFrameFunctionCall(m._textureImageLoaded,m,[a,q,c.image,c.texMeta,k],void 0,1);window.URL.revokeObjectURL(k);q.src="";q.onerror=void 0;q.onload=void 0};q.src=k}};b.prototype._textureImageLoaded=function(a,d,e,c){delete this._requestedTexImageIds[e.id];if(!(0>c.desiredLOD)){a=c.images[c.desiredLOD];
var b=c.images[c.curLOD];if(!this.isOverMemory()||!(null==b||e.size>b.size))if(!b||e.size>b.size&&e.size<=a.size||e.size<b.size&&e.size>=a.size){if((b=c.engineTex)&&b!==this._initTexture)this.memEstimateTextureRemoved(b),this._stage.remove(l.TEXTURE,c.engineTex.getId());b=W(d,c);c.engineTex=new K(d,c.id,b);this._stage.add(l.TEXTURE,c.engineTex);c.curLOD=c.desiredLOD;this.memEstimateTextureAdded(c.engineTex);d=c.engineTex.getId();for(b=0;b<c.usedByEngineMats.length;b++){var m=c.usedByEngineMats[b];
null==this._colorOverride&&m.setParameterValues({textureId:d});m.metadata.originalTextureId=d}e!==a&&(c.curLOD=c.images.indexOf(e),w(-1<c.curLOD),this._requestedTexImageIds[a.id]||(e={metadata:{texMeta:c,image:a}},this._requestedTexImageIds[a.id]=!0,this._controller.streamDataSupplier.request(a.hrefConcat,"binary",e).then(this._extractTextureImageFromBlob.bind(this))))}}};b.prototype._imageIsPartOfTextureBundle=function(a){return!this._controller.isMeshPyramid};b.prototype._setPolygonOffset=function(a,
d){if(null!=this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjectsPerBundle)for(var b={polygonOffset:d},c=0;c<this._nodeId2Meta[a.id].engineObjectsPerBundle.length;c++)for(var h=this._nodeId2Meta[a.id].engineObjectsPerBundle[c],m=0;m<h.length;m++)for(var k=h[m].getGeometryRecords(),g=0;g<k.length;g++)for(var f=k[g].materials,l=0;l<f.length;l++)f[l].setParameterValues(b)};b.prototype._rendererChange=function(a){(this._currentRenderer=a)&&(a.colorInfo||a.sizeInfo)&&console.warn("renderer.colorInfo and renderer.sizeInfo are not supported for Scene Services. Use visualVariables instead.")};
b.prototype._getRenderer=function(a){return!a||a.symbol?null:this._rndForScale||this._currentRenderer};b.prototype._getSymbol=function(a){if(a.symbol)return a.symbol;var d=this._getRenderer(a);return d&&d.getSymbol(a)};b.prototype._getRenderingInfo=function(a){var d=this._getRenderer(a),b=this._getSymbol(a);if(!b||!(b instanceof ha))return null;var b={symbol:b},c;if(d&&d.visualVariables){a=d.getVisualVariableValues(a);for(d=0;d<a.length;d++){var h=a[d];"color"===h.variable.type&&(c=h.value)}}c&&(b.color=
[c.r/255,c.g/255,c.b/255,c.a]);return b};b.prototype._getSymbolFillColor=function(a){a=a.symbolLayers;for(var d=0;d<a.length;d++){var b=a.getItemAt(d);if("Fill"===b.type&&b.material&&b.material.color)return a=b.material.color,[a.r/255,a.g/255,a.b/255,a.a]}};b.prototype._setObjectSymbology=function(a){for(var d=a.getMetadata(),b=[],c=d.graphics,h=!1,l=c.length,k=d.faceRanges?d.faceRanges.length:l,g={attributes:{}},f=function(a){k===l&&null==d.attributeData?g=c[a]:Object.keys(d.attributeData).forEach(function(b){g.attributes[b]=
d.attributeData[b][a]});var f=r._getRenderingInfo(g),p=null!=d.faceRanges?d.faceRanges[a]:null;if(f){var n=f.color;null==n&&f.symbol&&(n=r._getSymbolFillColor(f.symbol));n&&1>n[3]&&(h=!0);b.push({faceRanges:p,color:n})}else b.push({faceRanges:p,color:void 0})},r=this,n=0;n<k;n++)f(n);this.layer.cachedDrawingInfo.color?a.setFacerangeColors(b,"replace"):a.setFacerangeColors(b,"blend");a=a.getGeometryRecords();for(f=0;f<a.length;f++)for(var n=a[f],q=0;q<n.materials.length;q++){var p=n.materials[q],u=
p.getParams().transparent,s=p.getParams().opacity;p.metadata.symbolIsTransparent=h;var t=this._calcEngineMaterialTransparencyParams(p.metadata.i3sTex,p.metadata.i3sMatParams,p.metadata.symbolIsTransparent);(u!==t.transparent||s!==t.opacity)&&p.setParameterValues({transparent:t.transparent,opacity:t.opacity})}};b.prototype._opacityChange=function(a){for(var b in this._matId2Meta)for(var e in this._matId2Meta[b]){a=this._matId2Meta[b][e].engineMat;var c=a.getParams().transparent,h=a.getParams().opacity,
l=this._calcEngineMaterialTransparencyParams(a.metadata.i3sTex,a.metadata.i3sMatParams,a.metadata.symbolIsTransparent);(c!==l.transparent||h!==l.opacity)&&a.setParameterValues({transparent:l.transparent,opacity:l.opacity})}};L([M.shared("esri.views.3d.layers.SceneLayerView3D")],b.prototype,"declaredClass",void 0);L([M.property()],b.prototype,"layer",void 0);L([M.property()],b.prototype,"view",void 0);return b=L([M.subclass([ia])],b)}(ga)});