// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports","dojo/i18n!../nls/basemaps"],function(a,c,b){return{streets:{id:"streets",title:b.streets,thumbnailUrl:a.toUrl("../images/basemap/streets.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",showLegend:!1}]},satellite:{id:"satellite",title:b.satellite,thumbnailUrl:a.toUrl("../images/basemap/satellite.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",showLegend:!1}]},hybrid:{id:"hybrid",
title:b.hybrid,thumbnailUrl:a.toUrl("../images/basemap/hybrid.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer",isReference:!0,showLegend:!1}]},terrain:{id:"terrain",title:b.terrain,thumbnailUrl:a.toUrl("../images/basemap/terrain.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer",
showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Reference_Overlay/MapServer",isReference:!0,showLegend:!1}]},topo:{id:"topo",title:b.topo,thumbnailUrl:a.toUrl("../images/basemap/topo.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer",showLegend:!1}]},gray:{id:"gray",title:b.gray,thumbnailUrl:a.toUrl("../images/basemap/gray.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer",
showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer",isReference:!0,showLegend:!1}]},"dark-gray":{id:"dark-gray",title:b["dark-gray"],thumbnailUrl:a.toUrl("../images/basemap/dark-gray.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Reference/MapServer",isReference:!0,showLegend:!1}]},
oceans:{id:"oceans",title:b.oceans,thumbnailUrl:a.toUrl("../images/basemap/oceans.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Reference/MapServer",isReference:!0,showLegend:!1}]},"national-geographic":{id:"national-geographic",title:b["national-geographic"],thumbnailUrl:a.toUrl("../images/basemap/national-geographic.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer",
showLegend:!1}]},osm:{id:"osm",title:b.osm,thumbnailUrl:a.toUrl("../images/basemap/osm.jpg"),baseMapLayers:[{layerType:"OpenStreetMap",showLegend:!1}]},"dark-gray-vector":{id:"dark-gray-vector",title:b["dark-gray"],thumbnailUrl:a.toUrl("../images/basemap/dark-gray.jpg"),baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/3e3099d7302f4d99bc6f916dcc07ed59/resources/styles/root.json",layerType:"VectorTileLayer"}]},"gray-vector":{id:"gray-vector",title:b.gray,thumbnailUrl:a.toUrl("../images/basemap/gray.jpg"),
baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/bdf1eec3fa79456c8c7c2bb62f86dade/resources/styles/root.json",layerType:"VectorTileLayer"}]},"streets-vector":{id:"streets-vector",title:b.streets,thumbnailUrl:a.toUrl("../images/basemap/streets.jpg"),baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/3b8814f6ddbd485cae67e8018992246e/resources/styles/root.json",layerType:"VectorTileLayer"}]},"topo-vector":{id:"topo-vector",title:b.topo,thumbnailUrl:a.toUrl("../images/basemap/topo.jpg"),
baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/be44936bcdd24db588a1ae5076e36f34/resources/styles/root.json",layerType:"VectorTileLayer"}]},"streets-night-vector":{id:"streets-night-vector",title:b["streets-night-vector"],thumbnailUrl:a.toUrl("../images/basemap/streets-night.jpg"),baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/f96366254a564adda1dc468b447ed956/resources/styles/root.json",layerType:"VectorTileLayer"}]},"streets-relief-vector":{id:"streets-relief-vector",
title:b["streets-relief-vector"],thumbnailUrl:a.toUrl("../images/basemap/streets-relief.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer",showLegend:!1},{url:"//www.arcgis.com/sharing/rest/content/items/ad06088bd1174866aad2dddbf5ec9642/resources/styles/root.json",layerType:"VectorTileLayer",isReference:!0,showLegend:!1}]},"streets-navigation-vector":{id:"streets-navigation-vector",title:b["streets-navigation-vector"],thumbnailUrl:a.toUrl("./images/basemap/streets-navigation.jpg"),
baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/00cd8e843bae49b3a040423e5d65416b/resources/styles/root.json",layerType:"VectorTileLayer"}]}}});