// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../config ../../core/Accessor ../../core/Error ../../core/Evented ../../core/promiseUtils ../../geometry/Point ../../geometry/support/webMercatorUtils ../../Graphic ../../symbols/PictureMarkerSymbol ../../tasks/GeometryService ../../tasks/support/ProjectParameters ../../portal/Portal dojo/_base/lang dojo/Deferred require".split(" "),function(l,m,d,n,h,p,q,r,s,t,u,v,k,f,w){return m.createSubclass([n],{properties:{geolocationOptions:{},goToLocationEnabled:{},graphic:{type:r},state:{dependsOn:["view.ready"],
readOnly:!0},view:{}},declaredClass:"esri.widgets.Locate.LocateViewModel",constructor:function(){this.locate=this.locate.bind(this)},getDefaults:function(){return k.mixin(this.inherited(arguments),{geolocationOptions:{maximumAge:0,timeout:15E3,enableHighAccuracy:!0},graphic:{}})},initialize:function(){navigator.geolocation?window.hasOwnProperty("isSecureContext")&&!window.isSecureContext&&(console.log(this.declaredClass,"navigator.geolocation requires a secure origin."),this._geolocationUsable=!1):
(console.log(this.declaredClass,"navigator.geolocation unsupported."),this._geolocationUsable=!1)},destroy:function(){this._clear()},_geolocationUsable:!0,geolocationOptions:null,goToLocationEnabled:!0,graphic:null,_graphicSetter:function(a){a&&!a.symbol&&(a.symbol=new s({url:w.toUrl("./images/sdk_gps_location.png"),width:21,height:21}));this._set("graphic",a)},state:"disabled",_stateGetter:function(){return!this._geolocationUsable?"feature-unsupported":!this.get("view.ready")?"disabled":this._locating?
"locating":"ready"},view:null,locate:function(){if("disabled"===this.state)return h.reject(d(this.declaredClass,"Cannot locate when disabled."));this._locating&&(this._locating.cancel(),this._locating=null);var a=this._getCurrentPosition().then(function(a){this.view.graphics.remove(this.graphic);this.graphic&&(this.graphic=this.graphic.clone(),this.view.graphics.push(this.graphic));this.emit("locate",{position:a});return a}.bind(this)).otherwise(function(a){a||(a=d(this.declaredClass,"Could not get current position."));
this._emitError(a);return a}.bind(this));this._locating=a;this.notifyChange("state");return h.timeout(a,15E3).always(function(){this._locating=null;this.notifyChange("state")}.bind(this))},_clear:function(){this.view&&this.view.graphics.remove(this.graphic)},_clearCurrentLocationVars:function(){this._scale=this._position=this._graphic=null},_positionToObject:function(a){return a?{coords:k.mixin({},a.coords),timestamp:a.timestamp}:{}},_getCurrentPosition:function(){var a=new f;this._clearCurrentLocationVars();
navigator.geolocation.getCurrentPosition(function(b){a.isFulfilled()||(b=this._positionToObject(b),this._setPosition(b).then(function(b){a.resolve(b)}.bind(this),function(b){b||(b=d(this.declaredClass,"Error setting position."));a.reject(b)}.bind(this)))}.bind(this),function(b){b||(b=d(this.declaredClass,"Could not get current position."));a.reject(b)}.bind(this),this.geolocationOptions);return a.promise},_getGeometryServiceUrl:function(){var a=new f,b=l.geometryServiceUrl;if(b)a.resolve(b);else{var c=
v.getDefault();c.load().always(function(){b=c.get("helperServices.geometry.url");a.resolve(b)})}return a.promise},_projectPoint:function(a){var b=new f,c=this.get("view.spatialReference");c.isWebMercator?b.resolve(q.geographicToWebMercator(a)):c.isWGS84?b.resolve(a):this._getGeometryServiceUrl().then(function(e){if(e){var g=new u({geometries:[a],outSR:c});(new t({url:e})).project(g).then(function(a){a&&a.length?b.resolve(a[0]):b.reject(d(this.declaredClass,"Point was not projected."))}.bind(this),
b.reject)}else b.resolve(d(this.declaredClass,"please specify a geometry service on esri/config to project."))});return b.promise},_getScale:function(a){a=a&&a.coords&&a.coords.accuracy;return this.scale||a||5E4},_createPoint:function(a){if(a=a&&a.coords)return new p({longitude:a.longitude,latitude:a.latitude,z:a.altitude||null,spatialReference:{wkid:4326}})},_animatePoint:function(a,b,c,e){this._graphic=e=this._createGraphic(a,b);return!this.goToLocationEnabled?h.resolve(b):this.view.goTo({target:a,
scale:c}).then(function(){return b}.bind(this)).otherwise(function(a){a||(a=d(this.declaredClass,"Could not center."));return a}.bind(this))},_setPosition:function(a){var b=new f,c,e;this._clearCurrentLocationVars();this._position=a;if(c=this._createPoint(a))this._graphic=e=this._createGraphic(c,a);var g=this._getScale(a);this._scale=g;c?this._projectPoint(c).then(function(c){this._animatePoint(c,a,g,e).then(b.resolve,b.reject)}.bind(this),function(a){a||(a=d(this.declaredClass,"Error projecting point."));
b.reject(a)}.bind(this)):(c=d(this.declaredClass,"Invalid point"),b.reject(c));return b.promise},_createGraphic:function(a,b){var c=this.graphic;if(a&&b&&c)return c.geometry=a,c},_emitError:function(a){this.emit("locate-error",{error:a})}})});