// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/typescript ../../../core/Accessor ../../../core/HandleRegistry ../../../geometry/SpatialReference ./TilingScheme ./terrainUtils".split(" "),function(n,p,h,b,e,k,l,m,c,f){return function(g){function a(){g.apply(this,arguments)}h(a,g);a.prototype.dojoConstructor=function(){this._changeHandles=new l};a.prototype.normalizeCtorArgs=function(d){this._layers=d.layers;this._extentHelper=
d.extentHelper;this._manifold=d.manifold;return{changeCallback:d.changeCallback,viewSpatialReference:d.viewSpatialReference}};a.prototype.initialize=function(){var d=this;this._changeHandles.add(this._layers.on("change",function(){return d._update()}));this._changeHandles.add(this._extentHelper.watch("layerViewsExtent",function(){return d._setAdHocTilingScheme()}));this._update();this.tilingSchemeLocked||this._setAdHocTilingScheme()};a.prototype.destroy=function(){this._changeHandles.destroy();this._changeHandles=
null};a.prototype._update=function(){var d=this;this._waitTask=null;if(!this.tilingSchemeLocked){var a=this._layers.find(function(a){if(f.isTiledLayer(a))return a.isResolved()&&!d._isTileInfoSupported(a.tileInfo)?!1:!a.isRejected()});if(a)if(a.isResolved()){var b=new c(a.tileInfo),a=f.getKnownTiledServiceLevelCap(a.url);Infinity>a&&b.capMaxLod(a);this._lockTilingScheme(b)}else this._updateWhen(a)}};a.prototype._updateWhen=function(a){var b=this,c=a.always(function(){c===b._waitTask&&b._update()});
this._waitTask=c};a.prototype._lockTilingScheme=function(a){var b=this;this.tilingSchemeLocked=!0;this.tilingScheme=a;this._extentHelper.tilingScheme=this.tilingScheme;this._updateTiledLayerExtent();this._changeHandles.removeAll();this._changeHandles.add(this._extentHelper.watch("tiledLayersExtent",function(){return b._updateTiledLayerExtent()}));this._signalChange()};a.prototype._updateTiledLayerExtent=function(){this.extent=this._extentHelper.tiledLayersExtent};a.prototype._setAdHocTilingScheme=
function(){if("spherical"===this._manifold)this.tilingScheme=this._extentHelper.spatialReference.isWebMercator?c.WebMercatorAuxiliarySphere:c.makeWGS84WithTileSize(256),this.extent=this._extentHelper.layerViewsExtent,this._signalChange();else{var a=this._extentHelper.layerViewsExtent;a&&(this.tilingScheme=c.fromExtent(a,this._extentHelper.spatialReference),this.extent=a,this._signalChange())}};a.prototype._isTileInfoSupported=function(a){if("spherical"===this._manifold){if(a.spatialReference.isWebMercator)return c.WebMercatorAuxiliarySphere.compatibleWith(a);
if(a.spatialReference.equals(m.WGS84))return c.makeWGS84WithTileSize(a.rows).compatibleWith(a)}else return!c.checkUnsupported(a)&&a.spatialReference.equals(this.viewSpatialReference)};a.prototype._signalChange=function(){this.changeCallback&&this.changeCallback()};b([e.property()],a.prototype,"tilingScheme",void 0);b([e.property()],a.prototype,"extent",void 0);b([e.property({value:!1})],a.prototype,"tilingSchemeLocked",void 0);b([e.property()],a.prototype,"changeCallback",void 0);b([e.property()],
a.prototype,"viewSpatialReference",void 0);return a=b([e.subclass()],a)}(k)});