// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("./terrainUtils ./TileUtils ./TerrainConst ./TileGeometryFactory ./UpsampleInfo ./ElevationData ../support/mathUtils ../lib/glMatrix ../../../core/arrayUtils".split(" "),function(e,w,k,D,E,F,x,u,z){function A(a){this.waitingAgents=[];this.init(a)}var f=u.vec3d,s=u.vec2d,q=u.vec4d,G=u.mat4d,B=e.weakAssert,v=f.create(),h=q.create(),r=q.create(),H=f.create(),l={},t=k.LayerClass.LAYER_CLASS_COUNT,I=k.LayerClass.MAP,n=k.LayerClass.ELEVATION,p=k.TileUpdateTypes;e=function(a,b,c){this.lij=[0,0,0];
this.extent=q.create();this.extentWGS84Rad=q.create();this.centerAtSeaLevel=f.create();this.center=f.create();this.tileUp=H;this.elevationBounds=s.create();this.children=[null,null,null,null];this.layerInfo=Array(t);this.intersectsClippingArea=this.isWithinClippingArea=!0;this.clippingArea=null;this._maxTesselation=0};e.prototype.init=function(a,b,c,d){this.lij[0]=a[0];this.lij[1]=a[1];this.lij[2]=a[2];q.set4(0,0,0,0,this.extent);q.set4(0,0,0,0,this.extentWGS84Rad);this.intersectsClippingArea=this.isWithinClippingArea=
!0;this.clippingArea=null;this.radius=this.edgeLen=0;this.vlevel=a?a[0]:0;b&&b.elevationBounds?s.set(b.elevationBounds,this.elevationBounds):s.set2(0,0,this.elevationBounds);this.parent=b;for(a=0;4>a;a++)this.children[a]=null;this.pendingUpdates=0;this.renderData=null;this.renderOrder=this.screenDepth=0;this.visible=!1;this.parentSurface=c;for(a=0;a<t;a++)if(c){var y=c.numLayers(a),e;this.layerInfo[a]?(e=this.layerInfo[a],e.length=y):(e=Array(y),this.layerInfo[a]=e);for(var g=0;g<y;g++)e[g]=C(a,e[g]),
b&&a==n&&(e[g].elevationBounds=b.layerInfo[a][g].elevationBounds)}else this.layerInfo[a]=null;this._maxTesselation=Math.min(d.pixelSize[0],k.MAX_TILE_TESSELATION)};e.prototype.dispose=function(){for(var a=0;a<t;a++)for(var b=this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.upsampleFromTile&&(E.Pool.release(d.upsampleFromTile),d.upsampleFromTile=null)}};e.prototype.updateScreenDepth=function(a){f.set(this.center,r);r[3]=1;G.multiplyVec4(a,r,r);this.screenDepth=r[2]/r[3]};e.prototype.shouldSplit=
function(a,b){var c=this.lij[0];if(1>c)return p.SPLIT;f.subtract(this.center,b,v);var d=f.length(v),d=this.edgeLen/(2*a[0]*d);return d<a[1]?this.vlevel!==this.lij[0]?(this.vlevel=this.lij[0],p.VSPLITMERGE):p.NONE:c>=a[4]?(c+=Math.ceil(-x.log2(a[1]/d)),c!==this.vlevel?(this.vlevel=c,p.VSPLITMERGE):p.NONE):10<c&&(f.scale(this.tileUp,f.dot(this.tileUp,v),h),f.subtract(h,v),f.length2(h)>this.radius*this.radius&&(f.scale(h,this.radius/f.length(h)),f.add(h,this.centerAtSeaLevel),f.subtract(b,h,h),Math.abs(f.dot(h,
this.tileUp)/f.length(h))*d<0.15*a[1]))?p.NONE:p.SPLIT};e.prototype.createElevationDataFromLERC=function(a){var b;try{b=F.createFromLERC(this.lij,this.extent,a,{noDataValue:k.ELEVATION_NODATA_VALUE})}catch(c){console.warn("Error decoding %s: %s",a.url,c.message)}return b};e.prototype.getWGS84Extent=function(){return this.extentWGS84Rad.map(x.rad2deg)};e.prototype.load=function(a){for(var b=0;b<t;b++)this.layerInfo[b]&&this._createOrUpdateAgents(0,b);a.loadTile(this)};e.prototype.unload=function(a){this.renderData&&
a.unloadTile(this);for(a=0;a<t;a++)for(var b=this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.loadingAgent&&d.loadingAgent!==l&&(d.loadingAgent.dispose(),this.parentSurface.agentTypeByLayerIndex(c,a).Pool.release(d.loadingAgent),d.loadingAgent=null);d.pendingUpdates=0}this.pendingUpdates&=~k.TileUpdateTypes.UPDATE_GEOMETRY;this.pendingUpdates&=~k.TileUpdateTypes.UPDATE_TEXTURE};e.prototype.updateClippingStatus=function(a){z.equals(a,this.clippingArea)||(a?(this.intersectsClippingArea=this._intersectsExtent(a),
this.isWithinClippingArea=this._isWithinExtent(a)):this.isWithinClippingArea=this.intersectsClippingArea=!0,this.clippingArea=a,this.renderData&&this.updateGeometry())};e.prototype.updateVisibility=function(a,b,c){a=c||this.isVisible(a,b)&&this.intersectsClippingArea;if(a!==this.visible){this.visible=a;b=this.layerInfo[0];for(c=0;c<b.length;c++){var d=b[c];d.loadingAgent&&d.loadingAgent!==l&&d.loadingAgent.setSuspension(!a)}}return a};e.prototype.getLayerInfo=function(a,b){return this.layerInfo[b][a]};
e.prototype.hasLayerData=function(a,b){var c=this.layerInfo[b][a];return c&&c.data};e.prototype.tileDataAvailable=function(a,b,c){return(b=this.layerInfo[c][b].tilemapData)?null!=b.dataValue?b.dataValue:b.isTileAvailable(a.lij[1],a.lij[2]):!0};e.prototype.requestLayerData=function(a,b,c){k.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d requested by tile %s",this.lij.toString(),b,a,c.tile.lij.toString());var d=this.layerInfo[b][a];if(-1<d.waitingAgents.indexOf(c))return console.warn("agent already requested this piece of map data (tile %s, agent tile %s, layer: %d/%d)",
this.lij.toString(),c.tile.lij.toString(),b,a),!0;if(d.data)return console.warn("agent requested existing data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),c.tile.lij.toString(),b,a),d.waitingAgents.push(c),setTimeout(c.dataArrived.bind(c,this),0),!0;if(d.pendingUpdates&p.DECODE_LERC)return d.waitingAgents.push(c),!0;d.waitingAgents.push(c);if(!d.requestPromise){var e=this.parentSurface.requestTileData(this,a,b);a=function(){d.requestPromise===e&&(d.requestPromise=null)};d.requestPromise=
e;e.then(a,a)}return d.requestPromise?!0:!1};e.prototype.descendants=function(a){a||(a=[]);for(var b=0;4>b;b++){var c=this.children[b];c&&(c.descendants(a),a.unshift(this.children[b]))}return a};e.prototype.isLij=function(a){return this.lij[0]===a[0]&&this.lij[1]===a[1]&&this.lij[2]==a[2]};e.prototype.findByLij=function(a){if(this.isLij(a))return this;for(var b=0;4>b;b++){var c=this.children[b];if(c&&(c=c.findByLij(a)))return c}return null};e.prototype.unrequestLayerData=function(a,b,c){k.TILE_LOADING_DEBUGLOG&&
console.log("tile %s layer %d/%d canceled by tile %s",this.lij.toString(),b,a,c.tile.lij.toString());var d=this.layerInfo[b][a],e=d.waitingAgents;c=e.indexOf(c);B(-1<c,"agent has not requested this piece of map data");e[c]=e[e.length-1];e.length--;1>e.length&&(B(d.requestPromise||d.rawData,"no pending operations on layerInfo that agents were waiting for"),d.requestPromise&&(this.parentSurface.cancelRequest(d.requestPromise),d.requestPromise=null),k.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d request/loading canceled",
this.lij.toString(),b,a))};e.prototype.dataArrived=function(a,b,c){a=this.layerInfo[b][a];a.data=c;for(c=0;c<a.waitingAgents.length;c++)a.waitingAgents[c].dataArrived(this);a.waitingAgents.length=0};e.prototype.dataMissing=function(a,b,c){c.notInTilemap||console.error("Tile %s layer %d/%d error",this.lij.toString(),b,a);a=this.layerInfo[b][a];for(b=0;b<a.waitingAgents.length;b++)a.waitingAgents[b].dataMissing(this);a.waitingAgents.length=0};e.prototype.updateTexture=function(a){this.renderData&&(a?
this.parentSurface._renderer.updateTileTexture(this):(this.pendingUpdates|=k.TileUpdateTypes.UPDATE_TEXTURE,this.parentSurface._pendingUpdates=!0))};e.prototype.updateElevationBounds=function(){s.set2(Number.MAX_VALUE,-Number.MAX_VALUE,this.elevationBounds);for(var a=this.layerInfo[n],b=!1,c=0;c<a.length;c++){var d=a[c];if(d.elevationBounds){var e=this.parentSurface.layerViewByIndex(c,n);w.fallsWithinLayer(this,e,!1)&&(this.elevationBounds[0]=Math.min(this.elevationBounds[0],d.elevationBounds[0]),
this.elevationBounds[1]=Math.max(this.elevationBounds[1],d.elevationBounds[1]),b=!0)}}b||s.set2(0,0,this.elevationBounds);this.updateRadiusAndCenter()};e.prototype.updateRadiusAndCenter=function(){f.scale(this.tileUp,0.5*(this.elevationBounds[0]+this.elevationBounds[1]),h);f.add(this.centerAtSeaLevel,h,this.center)};e.prototype.setLayerElevationBounds=function(a,b){var c=this.layerInfo[n][a];if(!c.elevationBounds||c.elevationBounds[2]<b[2])c.elevationBounds=b,this.updateElevationBounds()};e.prototype.updateGeometry=
function(){this.pendingUpdates|=k.TileUpdateTypes.UPDATE_GEOMETRY;this.parentSurface._pendingUpdates=!0};e.prototype.modifyLayers=function(a,b,c){for(var d=b.length,e=this.layerInfo[c],f=Array(d),g=0;g<e.length;g++){var m=e[g];m.loadingAgent&&m.loadingAgent!==l&&(m.loadingAgent.dispose(),this.parentSurface.agentTypeByLayerIndex(g,c).Pool.release(m.loadingAgent),m.loadingAgent=null);m.waitingAgents.length=0}if(c===I)for(g=0;g<e.length;g++)void 0===a[g]&&(m=e[g],m.data instanceof WebGLTexture&&this.parentSurface._renderer.releaseTileTexture(m.data));
for(g=0;g<d;g++)a=b[g],f[g]=-1<a?e[a]:C(c);this.layerInfo[c]=f};e.prototype.restartAgents=function(a){if(this.renderData)if(this._createOrUpdateAgents(0,a),a===n){this.updateGeometry();a=this.layerInfo[a];for(var b=0;b<a.length;b++)a[b].pendingUpdates|=k.TileUpdateTypes.UPDATE_GEOMETRY;this.parentSurface._pendingUpdates=!0}else this.updateTexture(!0)};e.prototype.updateAgents=function(a){if(this.renderData){for(var b=this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.loadingAgent===l&&(d.loadingAgent=
null)}this._createOrUpdateAgents(0,a)}};e.prototype.agentDone=function(a,b){var c=this.layerInfo[b],d=c[a];d.loadingAgent=l;!d.data&&!d.upsampleFromTile&&a<c.length-1&&this._createOrUpdateAgents(a+1,b)};e.prototype._createOrUpdateAgents=function(a,b){var c;c=b===n?!1:!this.visible;for(var d=a,e=this.layerInfo[b];d<e.length;){var f=e[d],g=!1,m=this.parentSurface.layerViewByIndex(d,b);if(null!==f.loadingAgent&&f.loadingAgent!==l)g=f.loadingAgent.update();else if(f.loadingAgent!==l&&w.fallsWithinLayer(this,
m,!1)){var k=this.parentSurface.agentTypeByLayerIndex(d,b),h=k.Pool.acquire();(g=h.init(this,d,b,c))?f.loadingAgent=h:(k.Pool.release(h),f.loadingAgent=l)}if(g&&!m.isTransparent())break;d++}};e.prototype.geometryState=function(a){var b,c=this._getElevationInfo(a?a.samplerData:null),d=this.lij[0],e=!1;c.samplerData?(b=this.vlevel-d,b=Math.max(d-c.maxTileLevel,k.ELEVATION_DESIRED_RESOLUTION_LEVEL-b),d=this._maxTesselation,b=x.clamp((d>>b)+1,2,d+1)):b=8>d?this._numSubdivisionsAtLevel[d]+1:2;b=D.supportedNumVertsPerRow(b);
d=this.clippingArea;if(!this.intersectsClippingArea||this.isWithinClippingArea)d=null;a?(a.numVertsPerRow!==b&&(a.numVertsPerRow=b,e=!0),c.changed&&(a.samplerData=c.samplerData,e=!0),z.equals(a.clippingArea,d)||(a.clippingArea=d,e=!0),a.needsUpdate=e):a={numVertsPerRow:b,samplerData:c.samplerData,needsUpdate:!0,clippingArea:d};return a};e.prototype._getElevationInfo=function(a){for(var b=this.layerInfo[n],c=b.length,d=Array(c),e=0,f=0,g=!1,k=0;k<c;k++){var h=b[k];if(h.upsampleFromTile){var h=h.upsampleFromTile.tile,
l=h.layerInfo[n][k].data;if(!a||a[e]!==l.samplerData)g=!0;d[e++]=l.samplerData;f=Math.max(f,h.lij[0])}else if(h.data&&(l=this.parentSurface.layerViewByIndex(k,n),w.fallsWithinLayer(this,l,!1))){if(!a||a[e]!==h.data.samplerData)g=!0;d[e++]=h.data.samplerData;f=this.lij[0]}}a&&a.length!==e&&(g=!0);0<e?d.length=e:d=null;return{changed:g,samplerData:d,maxTileLevel:f}};e.prototype._isWithinExtent=function(a){var b=this.extent;return b[0]>=a[0]&&a[2]>=b[2]&&b[1]>=a[1]&&a[3]>=b[3]};e.prototype._intersectsExtent=
function(a){var b=this.extent;return b[2]>=a[0]&&a[2]>=b[0]&&b[3]>=a[1]&&a[3]>=b[1]};A.prototype.init=function(a){this.waitingAgents.length=0;this.rawData=this.requestPromise=this.loadingAgent=this.upsampleFromTile=this.tilemapRequest=this.tilemapData=this.data=null;this.pendingUpdates=0;a===n&&(this.elevationBounds=null)};var C=function(a,b){return b?(b.init(a),b):new A(a)};return e});