// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper ../../core/accessoireSupport/typescript dojo/_base/lang ../../core/Accessoire ../../core/watchUtils ../../core/HandleRegistry".split(" "),function(p,q,h,e,f,k,l,m,n){return function(g){function a(b){g.call(this)}h(a,g);a.prototype.dojoConstructor=function(){this._handles=new n;this._extent=this._spatialReference=this._waitTask=null;this._isStarted=this._isDone=!1};a.prototype.normalizeCtorArgs=function(b){b=
k.mixin({},b);this._view=b.view;delete b.view;return b};a.prototype.initialize=function(){var b=this;this.watch("mapCollectionPaths",function(){b._isStarted&&(b.reset(),b.start())})};a.prototype.destroy=function(){this._handles&&(this._handles.destroy(),this._handles=null,this._isStarted=!1);this._cancelLoading()};a.prototype.reset=function(){this._handles.removeAll();this._isStarted=!1;this._spatialReference=null;this.notifyChange("spatialReference");this._extent=null;this.notifyChange("extent");
this._isDone=!1;this.notifyChange("isDone")};a.prototype.start=function(){this._handles.removeAll();this._isStarted=!0;for(var b=this._updateLayerChange.bind(this),d=0;d<this.mapCollectionPaths.length;d++)this._handles.add(m.on(this._view,this.mapCollectionPaths[d],"change",b,b,b))};a.prototype._ownerNameFromCollectionName=function(b){var d=b.lastIndexOf(".");return-1===d?"view":"view."+b.slice(0,d)};a.prototype._ensureLoadedOwnersFromCollectionName=function(b){b=this._ownerNameFromCollectionName(b).split(".");
for(var d,c=0;c<b.length;c++){d=this.get(b.slice(0,c+1).join("."));if(!d)break;if(d.load&&!d.isFulfilled())return{owner:null,loading:d.load()}}return{owner:d}};a.prototype._cancelLoading=function(){this._waitTask=null};a.prototype._updateWhen=function(b){var d=this,c=!0,a=!1,e=b.always(function(){c?a=!0:e===d._waitTask&&d._update()}),c=!1;a||(this._waitTask=e);return a};a.prototype._updateLayerChange=function(){!this.spatialReference&&this._isDone&&(this._isDone=!1,this.notifyChange("isDone"));this._update()};
a.prototype._update=function(){this._cancelLoading();if(!this._isDone){this._isDone=!0;for(var b=0;b<this.mapCollectionPaths.length;b++){var a=this.mapCollectionPaths[b],c=this._ensureLoadedOwnersFromCollectionName(a);if(c.loading&&!this._updateWhen(c.loading)){this._isDone=!1;break}if((c=c.owner)&&(!c.isRejected||!c.isRejected()))if((a=this.view.get(a))&&this._processSpatialReferenceSources(a))break}this._isDone&&this.notifyChange("isDone")}};a.prototype._processSpatialReferenceSources=function(a){for(var d=
0;d<a.length;d++){var c=a.getItemAt(d);if(c.load&&!c.isFulfilled()&&!this._updateWhen(c.load()))return this._isDone=!1,!0;if(!c.load||c.isResolved()){var e=c.fullExtent;if((c.spatialReference||!this._extent)&&e)this._extent=e,this.notifyChange("extent");if(c.spatialReference)return this._spatialReference=c.spatialReference,this.notifyChange("spatialReference"),!0;if(c.layers&&this._processSpatialReferenceSources(c.layers))return!0}}return!1};e([f.shared("esri.views.support.DefaultsFromMap")],a.prototype,
"declaredClass",void 0);e([f.shared(["map.basemap.baseLayers","map.layers","map.ground.layers"])],a.prototype,"defaultMapCollectionPaths",void 0);e([f.property({readOnly:!0,getter:function(){return this._isDone}})],a.prototype,"isDone",void 0);e([f.property({readOnly:!0,getter:function(){return this._view}})],a.prototype,"view",void 0);e([f.property({readOnly:!0,getter:function(){return this._spatialReference}})],a.prototype,"spatialReference",void 0);e([f.property({readOnly:!0,getter:function(){return this._extent}})],
a.prototype,"extent",void 0);e([f.property({dependsOn:["view.defaultsFromMapCollectionPaths"],getter:function(){return this.view.defaultsFromMapCollectionPaths||this.defaultMapCollectionPaths}})],a.prototype,"mapCollectionPaths",void 0);return a=e([f.subclass()],a)}(l)});