// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/on dojo/has ../../../core/Collection ../ResourceLoader ../TileInfoView ../Tile ../math/vec2 ../collections/ReferenceMap ../collections/Set ../engine/Container ../engine/Bitmap ./LayerView2D ./TileQueue".split(" "),function(v,k,w,x,y,p,z,A,l,t,B,C,D){var u=k("esri-mobile");k=C.createSubclass({declaredClass:"esri.views.2d.layers.TiledLayerView2D",constructor:function(a){this.container=new E;this._viewHdl=v.pausable(this,"view-change",function(){this.needUpdate()}.bind(this));this._viewWtch=
this.watch("suspended, view.stationary",function(){!this.suspended&&(!u||u&&this.view.stationary)?(this.needUpdate(),this._viewHdl.resume()):this._viewHdl.pause()}.bind(this))},initialize:function(){this.then(this.setup.bind(this))},destroy:function(){this._viewWtch.remove();this._viewWtch=null;this._viewHdl.remove();this._viewHdl=null;this._updatingDependenciesWatcher.forEach(function(a){a.remove()})},_tCol:null,_rtCol:null,setup:function(){var a=this.layer;this.tileInfoView=new y({tileInfo:a.tileInfo,
fullExtent:a.fullExtent});this._rtCol=this._tCol=new F;var b=[];a.tileMap&&(this._rtCol=new G({tileInfoView:this.tileInfoView,tileMap:a.tileMap,tiles:this._tCol}),b.push(this._rtCol));this._loadingCol=new H({loader:this.createLoader(),tileInfoView:this.tileInfoView,layer:this.layer,tiles:this._rtCol,view:this.view});b.push(this._loadingCol);this.container.set({tileInfoView:this.tileInfoView,tiles:this._loadingCol,state:this.view.state});var d=function(){this.updating=this._rtCol.updating||this._loadingCol.updating}.bind(this);
this._updatingDependenciesWatcher=b.map(function(a){return a.watch("updating",d,!0)})},update:function(){if(!this.suspended){var a=this.tileInfoView.getTileSpans(this.view.state);this._tCol.tileSpans=a}},createLoader:function(){return new x({queue:new D({tileInfo:this.layer.tileInfo,state:this.view.state})})}});var E=t.createSubclass({declaredClass:"TileContainer",properties:{tileInfoView:{},tiles:{},state:{}},constructor:function(){this.levels={}},_hdl:null,_tilesSetter:function(a){var b=this._hdl;
this._get("tiles")!==a&&(b&&(this.removeAllChildren(),b.remove(),b=null),a&&(b=a.on("change",this._colChange.bind(this)),this._tilesAdded(a.toArray())),this._hld=b,this._set("tiles",a))},_tilesAdded:function(a){var b,d;b=0;for(d=a.length;b<d;b++){var c=a[b].tile,g=a[b].data,e=c.coords[2],f=this.levels[e],h=this.tileInfoView.getTileOrigin(z.create(),c.coords);f||(this.levels[e]=f=new t,f.coords=this.state.center,f.resolution=c.lodInfo.resolution,this.addChild(f));c.bitmap=new B({coords:h,source:g});
f.addChild(c.bitmap)}},_tilesRemoved:function(a){var b,d,c,g;b=0;for(d=a.length;b<d;b++)if(c=a[b].tile,(g=this.levels[c.coords[2]])&&c.bitmap)g.removeChild(c.bitmap),0===g.numChildren&&(this.removeChild(g),delete this.levels[c.level])},_colChange:function(a){0<a.added.length&&this._tilesAdded(a.added);0<a.removed.length&&this._tilesRemoved(a.removed)}}),F=l.createSubclass({declaredClass:"TileSet",_tileSpansSetter:function(a){(!a||0===a.length)&&this.removeAll();var b=this.keys(),d={},c=[],g=[],e,
f,h,m,k,q,r,s,l,n;h=0;for(n=a.length;h<n;h++){e=a[h];f=e.lodInfo;q=e.row;r=f.z;m=e.colFrom;for(l=e.colTo;m<=l;m++)s=f.getWorldForX(m),k=f.normalizeX(m),e=p.getId(k,q,r,s),this.contains(e)?d[e]=this.getItem(e):(d[e]=new p([k,q,r,s],f),c.push(d[e]))}h=0;for(n=b.length;h<n;h++)d[b[h]]||g.push(b[h]);this.addMany(c);this.removeMany(g)}}),G=A.createSubclass({declaredClass:"TileMapTilesCollection",properties:{updating:!1,tileInfoView:{},tileMap:{},tiles:{}},constructor:function(){this._loading=new l;this._tileMapCallback=
this._tileMapCallback.bind(this)},_hdl:null,_tilesSetter:function(a){var b=this._hdl;this._get("tiles")!==a&&(b&&(this.removeAll(),b.remove(),b=null),a&&(b=a.on("change",this._colChange.bind(this)),this._tilesAdded(a.toArray())),this._hld=b,this._set("tiles",a))},_tileMapCallback:function(a,b){this._loading.contains(b)&&(this._loading.remove(b),this.updating=this._loading.length,a!==b&&(a=new p([a.col,a.row,a.level,0],this.tileInfoView.getInfoForZoom(a.level)),a.world=b.world),this.add(a.id,a))},
_tilesAdded:function(a){var b,d,c;b=0;for(d=a.length;b<d;b++)c=a[b],!this._loading.contains(c)&&!this.contains(c)&&(this._loading.add(c),this.updating=this._loading.length,this.tileMap.getTile(c,this._tileMapCallback))},_tilesRemoved:function(a){this._loading.removeMany(a);this.removeMany(a)},_colChange:function(a){0<a.added.length&&this._tilesAdded(a.added);0<a.removed.length&&this._tilesRemoved(a.removed)}}),H=w.createSubclass({declaredClass:"TileLoader",properties:{updating:!1,loader:{},tileInfoView:{},
layer:{},tiles:{},view:{}},constructor:function(){this._tileLoadHandler=this._tileLoadHandler.bind(this);this._tileErrorHandler=this._tileErrorHandler.bind(this);this._loadingList=[];this._removingList=[]},destroy:function(){this._viewHdl.remove();this._viewHdl=null},initialize:function(){this._viewHdl=this.view.watch("stationary",function(a){if(a&&!this._loadingList.length&&(!this.tiles._loading||!this.tiles._loading.length))a=this._removingList.map(function(a){return this.find(function(d){return a===
d.tile})}.bind(this)),this.removeMany(a),this._removingList.length=0,this.updating=this._loadingList.length}.bind(this))},_hdl:null,_tilesSetter:function(a){var b=this._hdl;this._get("tiles")!==a&&(b&&(this.removeAll(),b.remove(),b=null),a&&(this._tilesAdded(a.toArray()),b=a.on("change",this._colChange.bind(this))),this._hld=b,this._set("tiles",a))},_tilesAdded:function(a){var b,d,c;b=0;for(d=a.length;b<d;b++)c=a[b],this._loadingList.push(c),this.updating=!0,this.loader.load({id:c.id,url:this.layer.getTileUrl(c.level,
c.row,c.col),tile:c,loadCallback:this._tileLoadHandler,errorCallback:this._tileErrorHandler})},_tilesRemoved:function(a){var b,d,c,g,e,f=this._loadingList;b=0;for(d=a.length;b<d;b++)if(e=a[b],e.bitmap)this._removingList.push(e);else{c=0;for(g=f.length;c<g;c++)if(f[c]===e){f.splice(c,1);break}this.loader.cancel(e.id);this._removeIntersectingTiles(e)}this.updating=f.length},_colChange:function(a){0<a.added.length&&this._tilesAdded(a.added);0<a.removed.length&&this._tilesRemoved(a.removed)},_tileLoadHandler:function(a){var b=
a.request.tile,d=this._loadingList,c;this.add({tile:b,data:a.data});a=0;for(c=d.length;a<c;a++)if(d[a]===b){d.splice(a,1);break}this.view.stationary&&!d.length&&(!this.tiles._loading||!this.tiles._loading.length)?(b=this._removingList.map(function(a){return this.find(function(b){return a===b.tile})}.bind(this)),this.removeMany(b),this._removingList.length=0):this._removeIntersectingTiles(b);this.updating=d.length},_removeIntersectingTiles:function(a){var b=this._loadingList,d=this._removingList,c,
g,e,f=!1;for(g=d.length-1;0<=g;g--)if(c=d[g],a.intersects(c)){for(e=b.length-1;0<=e;e--)c.intersects(b[e])&&(f=!0);f||(d.splice(g,1),this.removeAt(this.findIndex(function(a){return a.tile===c})))}},_tileErrorHandler:function(a){}});return k});