// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require dojo/Deferred dojo/_base/lang ../../../kernel ../../../core/declare ../../../core/Scheduler ../../../core/HandleRegistry ./LayerView2D".split(" "),function(h,k,l,m,n,p,q,r){return n(r,{declaredClass:"esri.views.2d.layers.VectorTileLayerView2D",constructor:function(a){var c=new k;this.addResolvingPromise(c.promise);this._handleRegistry=new q;h(["./vector-tile"],function(a){a.supported()?(this.vectorTile=a,a.identityManager=m.id,this.update=this.update.bind(this),this._viewHdl=this.watch("view.viewpoint",
this.update),this._updateTask=p.addFrameTask({update:this.update}),c.resolve()):c.reject(Error("VectorTileLayer is not supported"));this.container.watch("surface",function(a){var b=this.layer,c=b.style,e=this.view.state;this.gl=new this.vectorTile.Renderer({container:a,center:[e.longitude,e.latitude],zoom:this.getZoom(e.resolution),bearing:-e.rotation});this.gl.getCanvas().style["transform-origin"]="center";this.gl.getCanvas().style.transform="rotate(-"+e.rotation+"deg)";this.gl.setSize(e.width,e.height);
this._applyGLStyle(c);this._applyStyles(b.styles||[])}.bind(this))}.bind(this));return c.promise},getDefaults:function(){return l.mixin(this.inherited(arguments),{styles:[]})},initialize:function(a){this._handleRegistry.add(this.layer.watch("styles",function(a){a=a||[];this._applyStyles(a)}.bind(this)));this._handleRegistry.add(this.layer.watch("style",function(a){this.gl&&this._applyGLStyle(a);this.emit("style-change",this.layer.style)}.bind(this)))},destroy:function(){this._updateTask&&(this._updateTask.remove(),
this._updateTask=null);if(this.gl){var a=this.gl.style&&this.gl.style.sources.esri&&this.gl.style.sources.esri?this.gl.style.sources.esri._pyramid:null;a&&a.clearTiles();this.gl.remove();this.gl=null}this._viewHdl&&(this._viewHdl.remove(),this._viewHdl=null);this._handleRegistry&&(this._handleRegistry.destroy(),this._handleRegistry=null)},update:function(){if(this.gl){var a=this.view.state;this._version!==a.version&&(this._version=a.version,this.canResume()&&(this.gl.setSize(a.width,a.height),this.gl.jumpTo({center:[a.longitude,
a.latitude],zoom:this.getZoom(a.resolution),bearing:-a.rotation}),this.gl.getCanvas().style.transform="rotate(-"+a.rotation+"deg)"))}},getZoom:function(a){var c=this.layer.tileInfo.lods,g=null,d=null,b=0,f=c.length-1;for(b;b<f;b++){g=c[b];d=c[b+1];if(g.resolution<=a)return g.level;if(d.resolution===a)return d.level;if(g.resolution>a&&d.resolution<a){b=c[b].level+1-(a-d.resolution)/(g.resolution-d.resolution);b=Math.ceil(b)-Math.log(Math.abs(Math.ceil(b)-b+1))/Math.LN2;if(0.995<b-Math.floor(b)||0.0050>
b-Math.floor(b))b=Math.round(b);return b}}},_applyStyles:function(a){var c=this.styles,g=this.gl,d,b,f,e=[];d=0;for(b=c.length;d<b;d++)f=c[d],-1===a.indexOf(f)?g.removeClass(f):e.push(f);d=0;for(b=a.length;d<b;d++)f=a[d],-1===e.indexOf(f)&&(g.addClass(f),e.push(f));this.styles=e},_applyGLStyle:function(a){var c=this.gl;c&&(a?(a.animationLoop=c.animationLoop,c.setStyle(a),a._loaded&&(Object.getOwnPropertyNames(a.sources).forEach(function(a){this.fire("source.add",{source:this.sources[a]})},a),a.fire("load"),
a.sprite&&a.sprite.loaded()&&a.fire("change"))):c.setStyle(null))}})});