// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ./parts/Model ./parts/View ./lib/Selector ./lib/Camera ./lib/gl-matrix ./lib/Util ./lib/ModelContentType".split(" "),function(t,u,s,x,q,y,p,m,v){t=p.vec2d;u=p.vec2;var h=p.vec3d;p=function(){function b(a,d){this._intersectTolerance=q.DEFAULT_TOLERANCE;this._viewContent=[];this._externalIntersectionHandlers=[];this.onSelectionChange=function(){};this.onGeometryPicked=function(){};this.container=a;this.model=new s;this.view=new x(a,this,this.model.getDirtySet(),d);this.view.setLights(this.model.getAmbientLight(),
this.model.getDirectionalLight())}b.prototype.setNeedsRender=function(){this.view.setNeedsRender()};b.prototype.dispose=function(){this.view.dispose();this.model=this.view=null};b.prototype.setSelectionObject=function(a,d,c){this.model.setSelection(a,c);this.view.setSelectionObject(void 0!==a?a.getId():void 0,c);if(!d)this.onSelectionChange(a,c)};b.prototype.getSelectionObject=function(){return this.model.getSelection()};b.prototype.frame=function(a,d){void 0===d&&(d=0);var c=Math.max(1E-6,a.getBSRadius());
d=Math.max(2,d+2);var b=c*d,c=this.getCamera(),f=c.computeDirection(),b=1.5*b/Math.tan(c.fov);h.scale(f,-b);h.set(a.getCenter(),c.center);h.add(c.center,f,c.eye);c=new y(c.eye,c.center,c.up);this.setCamera(c)};b.prototype.beginMod=function(){b.DebugSettings.fineGrainedContentValidation&&this.model.validateContent()};b.prototype.endMod=function(a){void 0===a&&(a=!1);b.DebugSettings.fineGrainedContentValidation&&!a&&this.model.validateContent()};b.prototype.add=function(a,d){this.model.add(a,d);"function"===
typeof d.addParentStage&&d.addParentStage(this)};b.prototype.remove=function(a,d){var c=this.model.remove(a,d);"function"===typeof c.removeParentStage&&c.removeParentStage(this);return c};b.prototype.notifyDirty=function(a,d,c,b){this.model.notifyDirty(a,d,c,b)};b.prototype.processDirty=function(){var a=this.model.getDirtySet(),d=a.getDirtyMaterials();if(a.hasDirtyGeometryRecords()||d){b.DebugSettings.endFrameContentValidation&&this.model.validateContent();b.DebugSettings.logDirtySet&&console.log("Dirty set: "+
this.model.getDirtySet().formatDebugInfo(!1));var c=a.getAddRemoveUpdateListFilteredByLayers(this._viewContent,!0);(0<c[0].length+c[1].length+c[2].length||d)&&this.view.modify(c[0],c[1],c[2],d);b.DebugSettings.logDirtySet&&(console.log("RGs add: "+c[0].map(function(a){return a.uniqueName})),console.log("RGs remove: "+c[1].map(function(a){return a.uniqueName})));a.getAddRemoveUpdateList(!0);a.clearDirtyMaterials();this.view.setNeedsRender()}};b.prototype.processDirtyLayer=function(a){var d=this.model.getDirtySet(),
c=d.getDirtyMaterials();a=d.getAddRemoveUpdateListFilteredByLayers([a],!0);(0<a[0].length+a[1].length+a[2].length||c)&&this.view.modify(a[0],a[1],a[2],c);d.clearDirtyMaterials()};b.prototype.get=function(a,d){return this.model.get(a,d)};b.prototype.getAll=function(a){return this.model.getAll(a)};b.prototype.addTextureListener=function(a){this.view.addTextureListener(a)};b.prototype.removeTextureListener=function(a){this.view.removeTextureListener(a)};b.prototype.getContainer=function(){return this.container};
b.prototype.getCamera=function(){return this.view.getCamera()};b.prototype.setCamera=function(a){this.view.setCamera(a)};b.prototype.getViewParams=function(a){return this.view.getViewParams(a)};b.prototype.setViewParams=function(a){this.view.setViewParams(a)};b.prototype.getLayers=function(){return this.model.getAll(v.LAYER)};b.prototype.getAmbientLight=function(){return this.model.getAmbientLight()};b.prototype.getDirectionalLight=function(){return this.model.getDirectionalLight()};b.prototype.setAmbientLight=
function(a){this.model.setAmbientLight(a);this.view.setLights(this.model.getAmbientLight(),this.model.getDirectionalLight())};b.prototype.setDirectionalLight=function(a){this.model.setDirectionalLight(a);this.view.setLights(this.model.getAmbientLight(),this.model.getDirectionalLight())};b.prototype.getCanvas=function(){return this.view.getCanvas()};b.prototype.setRenderParams=function(a){this.view.setRenderParams(a)};b.prototype.getRenderParams=function(){return this.view.getRenderParams()};b.prototype.has=
function(a){return this.view.has(a)};b.prototype.getViewContent=function(){return this._viewContent.slice(0)};b.prototype.setViewContent=function(a){var d=m.array2object(this._viewContent),c=m.array2object(a),b=m.subtractObjects(c,d),d=m.subtractObjects(d,c);this.processDirty();c=this.model.getDirtySet();b=c.getResidentRenderGeometriesFilteredByLayers(m.object2array(b));d=c.getResidentRenderGeometriesFilteredByLayers(m.object2array(d));this.view.modify(b,d,[]);this._viewContent=a.slice(0)};b.prototype.addToViewContent=
function(a){for(var d=[],c=0;c<a.length;c++)-1===this._viewContent.indexOf(a[c])&&d.push(a[c]);0<a.length&&(this.processDirty(),a=this.model.getDirtySet().getResidentRenderGeometriesFilteredByLayers(d),this.view.modify(a,[],[]),this._viewContent.push.apply(this._viewContent,d))};b.prototype.removeFromViewContent=function(a){this.processDirty();for(var d=this.model.getDirtySet(),c=this._viewContent,b=[],f=0;f<a.length;f++){var g=c.indexOf(a[f]);-1<g&&(c[g]=c[c.length-1],c.pop(),b.push(a[f]))}a=d.getResidentRenderGeometriesFilteredByLayers(b);
this.view.modify([],a,[])};b.prototype.getViewFrustumObjects=function(){return this.view.getFrustumObjects()};b.prototype.getLocalOrigin=function(a,d,c){return this.model.getOrigin(a,d,c)};b.prototype.addModelListener=function(a){return this.model.addModelListener(a)};b.prototype.removeModelListener=function(a){this.model.removeModelListener(a)};b.prototype.getFrameTask=function(){return this.view.getFrameTask()};b.prototype.requestScreenCapture=function(a,d){this.view.requestScreenCapture(a,d)};
b.prototype.getAllTexturesLoaded=function(){return this.view.getAllTexturesLoaded()};b.prototype.getTextureLoaded=function(a){return this.view.getTextureLoaded(a)};b.prototype.addExternalRenderer=function(a,d){"function"===typeof d.intersect&&this._externalIntersectionHandlers.push(d);return this.view.addExternalRenderer(a,d)};b.prototype.removeExternalRenderer=function(a){var d=this._externalIntersectionHandlers.indexOf(a);-1<d&&this._externalIntersectionHandlers.splice(d,1);return this.view.removeExternalRenderer(a)};
b.prototype.getContentDebugStrings=function(a){return this.model.formatDebugInfo(a)};b.prototype.getRenderStats=function(){return this.view.getCombinedStats()};b.prototype.getRenderStatString=function(a){var d=this.getRenderStats(),c="";if(a){var c=c+"\x3ctable\x3e",b;for(b in d)c+="\x3ctr\x3e\x3ctd\x3e"+b+'\x3c/td\x3e\x3ctd style\x3d"text-align: right"\x3e'+Math.round(d[b])+"\x3c/td\x3e\x3c/tr\x3e";c+="\x3c/table\x3e"}else for(b in d)c+=b+": "+d[b]+"\n";return c};b.prototype.pick=function(a,b,c,
k){var f=h.create(),g=h.create();this.view.getPickRay(a,f,g);return this.pickRay(f,g,a,a,b,c,k)};b.prototype.pickRayWithBeginPoint=function(a,b,c,k,f){this.view.pickRayWithBeginPoint(a,b,c,k,f)};b.prototype.pickRay=function(a,b,c,k,f,g,l){k=this.view.getCamera();c||(c=z,k.projectPoint(b,c));var n;if(f){n=Array(f.length);for(var e=0;e<n.length;e++)n[e]=this.model.get(s.ContentType.LAYER,f[e])}else{n=[];f=this.getViewContent();for(var m=this.model.getAll(s.ContentType.LAYER),e=0;e<f.length;e++){var h=
m[f[e]];h&&"VISIBLE"===h.getState()&&n.push(h)}}l?l.init(n,a,b,c,k,this._intersectTolerance,g):l=new q(n,a,b,c,k,this._intersectTolerance,g);for(e=0;e<this._externalIntersectionHandlers.length;e++)this._externalIntersectionHandlers[e].intersect(l,a,b,c);if(l.getHudResults().length){e=l.getHudResults();e.sort(function(a,b){return b.dist-a.dist});b=e[e.length-1];c=A;k.projectPoint(b.center,c);c[0]=Math.round(c[0]);c[1]=Math.round(c[1]);g=B;this.view.getPickRay(c,a,g);r.init(n,a,g,c,k,this._intersectTolerance,
!1);for(e=0;e<this._externalIntersectionHandlers.length;e++)this._externalIntersectionHandlers[e].intersect(r,a,g,c);if(null==r.getMinResult().dist||b.dist<=r.getMinResult().dist)l.getMinResult().set(b.object,b.name,b.dist,b.normal,b.priority),l.getMinResult().setIntersector("stage")}return l};b.prototype.getIntersectTolerance=function(){return this._intersectTolerance};b.prototype.setIntersectTolerance=function(a){void 0===a&&(a=1E-5);this._intersectTolerance=a};b.prototype.select=function(a){var b=
this.pick(a,null,!0,w).getMinResult(),c=b.object;this.onGeometryPicked(c,a,b);if(c&&(a=c.getParentLayer(),c===this.model.getSelection()||a&&"PICKABLE"!==a.getInteraction()))b=c.getFaceRangeFromTriangleNr(b.triangleNr),null==b||null!=this.model.getSelectionFaceRange()&&(JSON.stringify(b),JSON.stringify(this.model.getSelectionFaceRange()))};b.prototype.getTextureGraphicsRenderer=function(){return this.view.getTextureGraphicsRenderer()};b.prototype.debugHideFaceRange=function(a,b){var c=this.getAll("objects")[a];
c.hideFaceRange(c.getGeometryRecords()[0],[c.getMetadata().faceRanges[b]])};b.prototype.debugHideAllFaceRange=function(a){a=this.getAll("objects")[a];for(var b in a.getMetadata().faceRanges)a.hideFaceRange(a.getGeometryRecords()[0],[a.getMetadata().faceRanges[b]])};b.prototype.debugUnhideFaceRange=function(a,b){this.getAll("objects")[a].unhideAllFaceRange()};b.DebugSettings={fineGrainedContentValidation:!1,endFrameContentValidation:!1,logDirtySet:!1};b.ModelContentType=v;return b}();var z=t.create(),
A=u.create(),B=h.create(),r=new q,w=new q;w.mode="select";return p});