// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define([],function(){function B(a,b,c){return Array.isArray(a)?(t(a,c[b],c),!0):!1}function t(a,b,c){var d;if(a)if(a.forEach)a.forEach(b,c);else if(void 0!==a.length)for(d=0;d<a.length;)b.call(c,a[d],d,a),d++;else for(d in a)a.hasOwnProperty(d)&&b.call(c,a[d],d,a)}function x(a,b,c){for(var d=Object.keys(b),e=0;e<d.length;){if(!c||c&&void 0===a[d[e]])a[d[e]]=b[d[e]];e++}return a}function da(a,b){return x(a,b,!0)}function h(a,b,c){b=b.prototype;var d;d=a.prototype=Object.create(b);d.constructor=a;d._super=
b;c&&x(d,c)}function F(a,b){return function(){return a.apply(b,arguments)}}function ea(a,b){return typeof a==Ha?a.apply(b?b[0]||void 0:void 0,b):a}function P(a,b,c){t(Q(b),function(b){a.addEventListener(b,c,!1)})}function R(a,b,c){t(Q(b),function(b){a.removeEventListener(b,c,!1)})}function qa(a,b){for(;a;){if(a==b)return!0;a=a.parentNode}return!1}function Q(a){return a.trim().split(/\s+/g)}function y(a,b,c){if(a.indexOf&&!c)return a.indexOf(b);for(var d=0;d<a.length;){if(c&&a[d][c]==b||!c&&a[d]===
b)return d;d++}return-1}function S(a){return Array.prototype.slice.call(a,0)}function ra(a,b,c){for(var d=[],e=[],f=0;f<a.length;){var g=b?a[f][b]:a[f];0>y(e,g)&&d.push(a[f]);e[f]=g;f++}c&&(d=b?d.sort(function(a,c){return a[b]>c[b]}):d.sort());return d}function T(a,b){for(var c,d=b[0].toUpperCase()+b.slice(1),e=0;e<sa.length;){c=(c=sa[e])?c+d:b;if(c in a)return c;e++}}function ta(a){a=a.ownerDocument||a;return a.defaultView||a.parentWindow||window}function p(a,b){var c=this;this.manager=a;this.callback=
b;this.element=a.element;this.target=a.options.inputTarget;this.domHandler=function(b){ea(a.options.enable,[a])&&c.handler(b)};this.init()}function Ia(a){var b=a.options.inputClass;return new (b?b:Ja?fa:Ka?U:ua?ga:V)(a,La)}function La(a,b,c){var d=c.pointers.length,e=c.changedPointers.length,f=b&l&&0===d-e,d=b&(k|m)&&0===d-e;c.isFirst=!!f;c.isFinal=!!d;f&&(a.session={});c.eventType=b;b=a.session;f=c.pointers;d=f.length;b.firstInput||(b.firstInput=va(c));1<d&&!b.firstMultiple?b.firstMultiple=va(c):
1===d&&(b.firstMultiple=!1);var e=b.firstInput,g=(d=b.firstMultiple)?d.center:e.center,n=c.center=wa(f);c.timeStamp=ha();c.deltaTime=c.timeStamp-e.timeStamp;c.angle=ia(g,n);c.distance=W(g,n);var e=c.center,g=b.offsetDelta||{},n=b.prevDelta||{},h=b.prevInput||{};if(c.eventType===l||h.eventType===k)n=b.prevDelta={x:h.deltaX||0,y:h.deltaY||0},g=b.offsetDelta={x:e.x,y:e.y};c.deltaX=n.x+(e.x-g.x);c.deltaY=n.y+(e.y-g.y);c.offsetDirection=xa(c.deltaX,c.deltaY);c.scale=d?W(f[0],f[1],X)/W(d.pointers[0],d.pointers[1],
X):1;c.rotation=d?ia(f[1],f[0],X)-ia(d.pointers[1],d.pointers[0],X):0;g=b.lastInterval||c;f=c.timeStamp-g.timeStamp;c.eventType!=m&&(f>Ma||void 0===g.velocity)?(e=g.deltaX-c.deltaX,g=g.deltaY-c.deltaY,n=e/f||0,h=g/f||0,f=n,d=h,n=G(n)>G(h)?n:h,e=xa(e,g),b.lastInterval=c):(n=g.velocity,f=g.velocityX,d=g.velocityY,e=g.direction);c.velocity=n;c.velocityX=f;c.velocityY=d;c.direction=e;b=a.element;qa(c.srcEvent.target,b)&&(b=c.srcEvent.target);c.target=b;a.emit("hammer.input",c);a.recognize(c);a.session.prevInput=
c}function va(a){for(var b=[],c=0;c<a.pointers.length;)b[c]={clientX:C(a.pointers[c].clientX),clientY:C(a.pointers[c].clientY)},c++;return{timeStamp:ha(),pointers:b,center:wa(b),deltaX:a.deltaX,deltaY:a.deltaY}}function wa(a){var b=a.length;if(1===b)return{x:C(a[0].clientX),y:C(a[0].clientY)};for(var c=0,d=0,e=0;e<b;)c+=a[e].clientX,d+=a[e].clientY,e++;return{x:C(c/b),y:C(d/b)}}function xa(a,b){return a===b?Y:G(a)>=G(b)?0<a?H:I:0<b?J:K}function W(a,b,c){c||(c=ya);var d=b[c[0]]-a[c[0]];a=b[c[1]]-a[c[1]];
return Math.sqrt(d*d+a*a)}function ia(a,b,c){c||(c=ya);return 180*Math.atan2(b[c[1]]-a[c[1]],b[c[0]]-a[c[0]])/Math.PI}function V(){this.evEl=Na;this.evWin=Oa;this.allow=!0;this.pressed=!1;p.apply(this,arguments)}function fa(){this.evEl=za;this.evWin=Aa;p.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function Ba(){this.evTarget=Pa;this.evWin=Qa;this.started=!1;p.apply(this,arguments)}function U(){this.evTarget=Ra;this.targetIds={};p.apply(this,arguments)}function Sa(a,b){var c=
S(a.touches),d=this.targetIds;if(b&(l|z)&&1===c.length)return d[c[0].identifier]=!0,[c,c];var e,f=S(a.changedTouches),g=[],h=this.target;e=c.filter(function(a){return qa(a.target,h)});if(b===l)for(c=0;c<e.length;)d[e[c].identifier]=!0,c++;for(c=0;c<f.length;)d[f[c].identifier]&&g.push(f[c]),b&(k|m)&&delete d[f[c].identifier],c++;if(g.length)return[ra(e.concat(g),"identifier",!0),g]}function ga(){p.apply(this,arguments);var a=F(this.handler,this);this.touch=new U(this.manager,a);this.mouse=new V(this.manager,
a)}function ja(a,b){this.manager=a;this.set(b)}function Ta(a){if(-1<a.indexOf(L))return L;var b=-1<a.indexOf(M),c=-1<a.indexOf(N);return b&&c?M+" "+N:b||c?b?M:N:-1<a.indexOf(ka)?ka:Ca}function u(a){this.id=Ua++;this.manager=null;this.options=da(a||{},this.defaults);this.options.enable=void 0===this.options.enable?!0:this.options.enable;this.state=Z;this.simultaneous={};this.requireFail=[]}function Da(a){return a==K?"down":a==J?"up":a==H?"left":a==I?"right":""}function $(a,b){var c=b.manager;return c?
c.get(a):a}function r(){u.apply(this,arguments)}function aa(){r.apply(this,arguments);this.pY=this.pX=null}function la(){r.apply(this,arguments)}function ma(){u.apply(this,arguments);this._input=this._timer=null}function na(){r.apply(this,arguments)}function oa(){r.apply(this,arguments)}function ba(){u.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function D(a,b){b=b||{};b.recognizers=void 0===b.recognizers?D.defaults.preset:b.recognizers;return new pa(a,
b)}function pa(a,b){b=b||{};this.options=da(b,D.defaults);this.options.inputTarget=this.options.inputTarget||a;this.handlers={};this.session={};this.recognizers=[];this.element=a;this.input=Ia(this);this.touchAction=new ja(this,this.options.touchAction);Ea(this,!0);t(b.recognizers,function(a){var b=this.add(new a[0](a[1]));a[2]&&b.recognizeWith(a[2]);a[3]&&b.requireFailure(a[3])},this)}function Ea(a,b){var c=a.element;c.style&&t(a.options.cssProps,function(a,e){c.style[T(c.style,e)]=b?a:""})}function Va(a,
b){var c=document.createEvent("Event");c.initEvent(a,!0,!0);c.gesture=b;b.target.dispatchEvent(c)}var sa=" webkit moz MS ms o".split(" "),Wa=document.createElement("div"),Ha="function",C=Math.round,G=Math.abs,ha=Date.now,Ua=1,ca=/mobile|tablet|ip(ad|hone|od)|android/i,ua="ontouchstart"in window,Ja=void 0!==T(window,"PointerEvent"),Ka=ua&&ca.test(navigator.userAgent),Ma=25,l=1,z=2,k=4,m=8,Y=1,H=2,I=4,J=8,K=16,s=H|I,A=J|K,ca=s|A,ya=["x","y"],X=["clientX","clientY"];p.prototype={handler:function(){},
init:function(){this.evEl&&P(this.element,this.evEl,this.domHandler);this.evTarget&&P(this.target,this.evTarget,this.domHandler);this.evWin&&P(ta(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&R(this.element,this.evEl,this.domHandler);this.evTarget&&R(this.target,this.evTarget,this.domHandler);this.evWin&&R(ta(this.element),this.evWin,this.domHandler)}};var Xa={mousedown:l,mousemove:z,mouseup:k},Na="mousedown wheel",Oa="mousemove mouseup";h(V,p,{handler:function(a){var b=
Xa[a.type];b&l&&0===a.button&&(this.pressed=!0);b&z&&1!==a.which&&(b=k);this.pressed&&this.allow&&(b&k&&(this.pressed=!1),this.callback(this.manager,b,{pointers:[a],changedPointers:[a],pointerType:"mouse",srcEvent:a}))}});var Ya={pointerdown:l,pointermove:z,pointerup:k,pointercancel:m,pointerout:m},Za={2:"touch",3:"pen",4:"mouse",5:"kinect"},za="pointerdown wheel",Aa="pointermove pointerup pointercancel";window.MSPointerEvent&&(za="MSPointerDown wheel",Aa="MSPointerMove MSPointerUp MSPointerCancel");
h(fa,p,{handler:function(a){var b=this.store,c=!1,d=a.type.toLowerCase().replace("ms",""),d=Ya[d],e=Za[a.pointerType]||a.pointerType,f="touch"==e,g=y(b,a.pointerId,"pointerId");d&l&&(0===a.button||f)?0>g&&(b.push(a),g=b.length-1):d&(k|m)&&(c=!0);0>g||(b[g]=a,this.callback(this.manager,d,{pointers:b,changedPointers:[a],pointerType:e,srcEvent:a}),c&&b.splice(g,1))}});var $a={touchstart:l,touchmove:z,touchend:k,touchcancel:m},Pa="touchstart",Qa="touchstart touchmove touchend touchcancel";h(Ba,p,{handler:function(a){var b=
$a[a.type];b===l&&(this.started=!0);if(this.started){var c;c=S(a.touches);var d=S(a.changedTouches);b&(k|m)&&(c=ra(c.concat(d),"identifier",!0));c=[c,d];b&(k|m)&&0===c[0].length-c[1].length&&(this.started=!1);this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:a})}}});var ab={touchstart:l,touchmove:z,touchend:k,touchcancel:m},Ra="touchstart touchmove touchend touchcancel";h(U,p,{handler:function(a){var b=ab[a.type],c=Sa.call(this,a,b);c&&this.callback(this.manager,
b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:a})}});h(ga,p,{handler:function(a,b,c){var d="mouse"==c.pointerType;if("touch"==c.pointerType)this.mouse.allow=!1;else if(d&&!this.mouse.allow)return;b&(k|m)&&(this.mouse.allow=!0);this.callback(a,b,c)},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var Fa=T(Wa.style,"touchAction"),Ga=void 0!==Fa,Ca="auto",ka="manipulation",L="none",M="pan-x",N="pan-y";ja.prototype={set:function(a){"compute"==a&&(a=this.compute());
Ga&&this.manager.element.style&&(this.manager.element.style[Fa]=a);this.actions=a.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var a=[];t(this.manager.recognizers,function(b){ea(b.options.enable,[b])&&(a=a.concat(b.getTouchAction()))});return Ta(a.join(" "))},preventDefaults:function(a){if(!Ga){var b=a.srcEvent;a=a.offsetDirection;if(this.manager.session.prevented)b.preventDefault();else{var c=this.actions,d=-1<c.indexOf(L),e=-1<c.indexOf(N),
c=-1<c.indexOf(M);if(d||e&&a&s||c&&a&A)return this.preventSrc(b)}}},preventSrc:function(a){this.manager.session.prevented=!0;a.preventDefault()}};var Z=1,q=2,E=4,w=8,v=w,O=16;u.prototype={defaults:{},set:function(a){x(this.options,a);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(a){if(B(a,"recognizeWith",this))return this;var b=this.simultaneous;a=$(a,this);b[a.id]||(b[a.id]=a,a.recognizeWith(this));return this},dropRecognizeWith:function(a){if(B(a,"dropRecognizeWith",
this))return this;a=$(a,this);delete this.simultaneous[a.id];return this},requireFailure:function(a){if(B(a,"requireFailure",this))return this;var b=this.requireFail;a=$(a,this);-1===y(b,a)&&(b.push(a),a.requireFailure(this));return this},dropRequireFailure:function(a){if(B(a,"dropRequireFailure",this))return this;a=$(a,this);a=y(this.requireFail,a);-1<a&&this.requireFail.splice(a,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(a){return!!this.simultaneous[a.id]},
emit:function(a){function b(b){c.manager.emit(c.options.event+(b?d&O?"cancel":d&w?"end":d&E?"move":d&q?"start":"":""),a)}var c=this,d=this.state;d<w&&b(!0);b();d>=w&&b(!0)},tryEmit:function(a){if(this.canEmit())return this.emit(a);this.state=32},canEmit:function(){for(var a=0;a<this.requireFail.length;){if(!(this.requireFail[a].state&(32|Z)))return!1;a++}return!0},recognize:function(a){a=x({},a);ea(this.options.enable,[this,a])?(this.state&(v|O|32)&&(this.state=Z),this.state=this.process(a),this.state&
(q|E|w|O)&&this.tryEmit(a)):(this.reset(),this.state=32)},process:function(a){},getTouchAction:function(){},reset:function(){}};h(r,u,{defaults:{pointers:1},attrTest:function(a){var b=this.options.pointers;return 0===b||a.pointers.length===b},process:function(a){var b=this.state,c=a.eventType,d=b&(q|E);a=this.attrTest(a);return d&&(c&m||!a)?b|O:d||a?c&k?b|w:!(b&q)?q:b|E:32}});h(aa,r,{defaults:{event:"pan",threshold:10,pointers:1,direction:ca},getTouchAction:function(){var a=this.options.direction,
b=[];a&s&&b.push(N);a&A&&b.push(M);return b},directionTest:function(a){var b=this.options,c=!0,d=a.distance,e=a.direction,f=a.deltaX,g=a.deltaY;e&b.direction||(b.direction&s?(e=0===f?Y:0>f?H:I,c=f!=this.pX,d=Math.abs(a.deltaX)):(e=0===g?Y:0>g?J:K,c=g!=this.pY,d=Math.abs(a.deltaY)));a.direction=e;return c&&d>b.threshold&&e&b.direction},attrTest:function(a){return r.prototype.attrTest.call(this,a)&&(this.state&q||!(this.state&q)&&this.directionTest(a))},emit:function(a){this.pX=a.deltaX;this.pY=a.deltaY;
var b=Da(a.direction);b&&this.manager.emit(this.options.event+b,a);this._super.emit.call(this,a)}});h(la,r,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return[L]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.scale-1)>this.options.threshold||this.state&q)},emit:function(a){this._super.emit.call(this,a);1!==a.scale&&this.manager.emit(this.options.event+(1>a.scale?"in":"out"),a)}});h(ma,u,{defaults:{event:"press",pointers:1,time:500,threshold:5},
getTouchAction:function(){return[Ca]},process:function(a){var b=this.options,c=a.pointers.length===b.pointers,d=a.distance<b.threshold,e=a.deltaTime>b.time;this._input=a;if(!d||!c||a.eventType&(k|m)&&!e)this.reset();else if(a.eventType&l)this.reset(),this._timer=setTimeout(F(function(){this.state=v;this.tryEmit()},this),b.time);else if(a.eventType&k)return v;return 32},reset:function(){clearTimeout(this._timer)},emit:function(a){this.state===v&&(a&&a.eventType&k?this.manager.emit(this.options.event+
"up",a):(this._input.timeStamp=ha(),this.manager.emit(this.options.event,this._input)))}});h(na,r,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return[L]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.rotation)>this.options.threshold||this.state&q)}});h(oa,r,{defaults:{event:"swipe",threshold:10,velocity:0.65,direction:s|A,pointers:1},getTouchAction:function(){return aa.prototype.getTouchAction.call(this)},attrTest:function(a){var b=this.options.direction,
c;b&(s|A)?c=a.velocity:b&s?c=a.velocityX:b&A&&(c=a.velocityY);return this._super.attrTest.call(this,a)&&b&a.direction&&a.distance>this.options.threshold&&G(c)>this.options.velocity&&a.eventType&k},emit:function(a){var b=Da(a.direction);b&&this.manager.emit(this.options.event+b,a);this.manager.emit(this.options.event,a)}});h(ba,u,{defaults:{event:"tap",pointers:1,taps:1,interval:300,time:250,threshold:2,posThreshold:10},getTouchAction:function(){return[ka]},process:function(a){var b=this.options,c=
a.pointers.length===b.pointers,d=a.distance<b.threshold,e=a.deltaTime<b.time;this.reset();if(a.eventType&l&&0===this.count)return this.failTimeout();if(d&&e&&c){if(a.eventType!=k)return this.failTimeout();c=this.pTime?a.timeStamp-this.pTime<b.interval:!0;d=!this.pCenter||W(this.pCenter,a.center)<b.posThreshold;this.pTime=a.timeStamp;this.pCenter=a.center;this.count=!d||!c?1:this.count+1;this._input=a;if(0===this.count%b.taps)return this.hasRequireFailures()?(this._timer=setTimeout(F(function(){this.state=
v;this.tryEmit()},this),b.interval),q):v}return 32},failTimeout:function(){this._timer=setTimeout(F(function(){this.state=32},this),this.options.interval);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){this.state==v&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});D.VERSION="2.0.4";D.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,preset:[[na,{enable:!1}],[la,{enable:!1},["rotate"]],[oa,{direction:s}],
[aa,{direction:s},["swipe"]],[ba],[ba,{event:"doubletap",taps:2},["tap"]],[ma]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};pa.prototype={set:function(a){x(this.options,a);a.touchAction&&this.touchAction.update();a.inputTarget&&(this.input.destroy(),this.input.target=a.inputTarget,this.input.init());return this},stop:function(a){this.session.stopped=a?2:1},recognize:function(a){var b=this.session;if(!b.stopped){this.touchAction.preventDefaults(a);
var c,d=this.recognizers,e=b.curRecognizer;if(!e||e&&e.state&v)e=b.curRecognizer=null;for(var f=0;f<d.length;)c=d[f],2!==b.stopped&&(!e||c==e||c.canRecognizeWith(e))?c.recognize(a):c.reset(),!e&&c.state&(q|E|w)&&(e=b.curRecognizer=c),f++}},get:function(a){if(a instanceof u)return a;for(var b=this.recognizers,c=0;c<b.length;c++)if(b[c].options.event==a)return b[c];return null},add:function(a){if(B(a,"add",this))return this;var b=this.get(a.options.event);b&&this.remove(b);this.recognizers.push(a);
a.manager=this;this.touchAction.update();return a},remove:function(a){if(B(a,"remove",this))return this;var b=this.recognizers;a=this.get(a);b.splice(y(b,a),1);this.touchAction.update();return this},on:function(a,b){var c=this.handlers;t(Q(a),function(a){c[a]=c[a]||[];c[a].push(b)});return this},off:function(a,b){var c=this.handlers;t(Q(a),function(a){b?c[a].splice(y(c[a],b),1):delete c[a]});return this},emit:function(a,b){this.options.domEvents&&Va(a,b);var c=this.handlers[a]&&this.handlers[a].slice();
if(c&&c.length){b.type=a;b.preventDefault=function(){b.srcEvent.preventDefault()};for(var d=0;d<c.length;)c[d](b),d++}},destroy:function(){this.element&&Ea(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};x(D,{INPUT_START:l,INPUT_MOVE:z,INPUT_END:k,INPUT_CANCEL:m,STATE_POSSIBLE:Z,STATE_BEGAN:q,STATE_CHANGED:E,STATE_ENDED:w,STATE_RECOGNIZED:v,STATE_CANCELLED:O,STATE_FAILED:32,DIRECTION_NONE:Y,DIRECTION_LEFT:H,DIRECTION_RIGHT:I,DIRECTION_UP:J,DIRECTION_DOWN:K,DIRECTION_HORIZONTAL:s,
DIRECTION_VERTICAL:A,DIRECTION_ALL:ca,Manager:pa,Input:p,TouchAction:ja,TouchInput:U,MouseInput:V,PointerEventInput:fa,TouchMouseInput:ga,SingleTouchInput:Ba,Recognizer:u,AttrRecognizer:r,Tap:ba,Pan:aa,Swipe:oa,Pinch:la,Rotate:na,Press:ma,on:P,off:R,each:t,merge:da,extend:x,inherit:h,bindFn:F,prefixed:T,inArray:y});return D});