// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../core/declare ../core/lang ../core/jsonDictionary dojo/_base/array dojo/_base/lang ../symbols/support/jsonUtils ./Renderer".split(" "),function(q,e,k,l,f,g,r){var m=k({esriNormalizeByLog:"log",esriNormalizeByPercentOfTotal:"percent-of-total",esriNormalizeByField:"field"}),n=k({esriClassifyNaturalBreaks:"natural-breaks",esriClassifyEqualInterval:"equal-interval",esriClassifyQuantile:"quantile",esriClassifyStandardDeviation:"standard-deviation",esriClassifyGeometricalInterval:"geometrical-interval"}),
p=q(r,{declaredClass:"esri.renderer.ClassBreaksRenderer",type:"classBreaks",classMetadata:{properties:{requiredFields:{dependsOn:["field","normalizationField"]},expressionTree:{dependsOn:["expression"]},normalizationType:{dependsOn:["normalizationField","normalizationTotal"]}},reader:{exclude:["minValue"]}},constructor:function(){this._symbols={}},getDefaults:function(){return f.mixin(this.inherited(arguments),{field:null,expression:null,backgroundFillSymbol:null,classificationMethod:null,defaultSymbol:null,
classBreakInfos:[],isMaxInclusive:!0,normalizationField:null,normalizationTotal:null,normalizationType:null})},_backgroundFillSymbolReader:g.fromJSON,_classificationMethodReader:function(a){return n.fromJSON(a)},_normalizationTypeReader:function(a){return m.fromJSON(a)},_normalizationTypeGetter:function(a){var b=!!this.normalizationField,c=null!=this.normalizationTotal;if(b||c)a=b&&"field"||c&&"percent-of-total",b&&c&&console.warn("warning: both normalizationField and normalizationTotal are set!");
else if("field"===a||"percent-of-total"===a)a=null;return a},_defaultSymbolReader:g.fromJSON,_classBreakInfosReader:function(a,b){var c=b.minValue;a&&(a[0]&&null!=a[0].classMaxValue)&&l.forEach(a,function(a){var b=a.classMaxValue;a.minValue=c;c=a.maxValue=b},this);return a},_classBreakInfosSetter:function(a){this._symbols={};a&&a.forEach(this._processCBInfo,this);return a},collectRequiredFields:function(a){this.inherited(arguments);[this.field,this.normalizationField].forEach(function(b){b&&(a[b]=
!0)})},expressionTree:null,_expressionTreeGetter:function(){return this.expression?this._parseExpr(this.expression,{vars:{$feature:"any"}}):null},addClassBreakInfo:function(a,b,c){a=f.isObject(a)?a:{minValue:a,maxValue:b,symbol:c};this.classBreakInfos.push(a);this._processCBInfo(a)},removeClassBreakInfo:function(a,b){var c,d,h=this.classBreakInfos.length,f=this._symbols;for(d=0;d<h;d++)if(c=[this.classBreakInfos[d].minValue,this.classBreakInfos[d].maxValue],c[0]==a&&c[1]==b){delete f[a+"-"+b];this.classBreakInfos.splice(d,
1);break}},getBreakIndex:function(a){var b=this.field,c=a.attributes,d=this.classBreakInfos.length,h=this.isMaxInclusive;if(this.expression)a=this._executeExpr(this.expressionTree,this._createExprContext(a));else if(f.isFunction(b))a=b(a);else{a=parseFloat(c[b]);var b=this.normalizationType,e;b&&(e=parseFloat(this.normalizationTotal),c=parseFloat(c[this.normalizationField]),"log"===b?a=Math.log(a)*Math.LOG10E:"percent-of-total"===b&&!isNaN(e)?a=100*(a/e):"field"===b&&!isNaN(c)&&(a/=c))}for(c=0;c<
d;c++)if(b=[this.classBreakInfos[c].minValue,this.classBreakInfos[c].maxValue],b[0]<=a&&(h?a<=b[1]:a<b[1]))return c;return-1},getClassBreakInfo:function(a){a=this.getBreakIndex(a);return-1!==a?this.classBreakInfos[a]:null},getSymbol:function(a){a=this.getBreakIndex(a);return(a=-1<a&&[this.classBreakInfos[a].minValue,this.classBreakInfos[a].maxValue])?this._symbols[a[0]+"-"+a[1]]:this.defaultSymbol},toJSON:function(){var a=this.classBreakInfos||[],b=e.fixJson,c=a[0]&&a[0].minValue,d=this.backgroundFillSymbol,
a=f.mixin(this.inherited(arguments),{type:this.type,field:this.field,expression:this.expression,defaultSymbol:this.defaultSymbol&&this.defaultSymbol.toJSON(),backgroundFillSymbol:d&&d.toJSON(),defaultLabel:this.defaultLabel,normalizationField:this.normalizationField,normalizationTotal:this.normalizationTotal,minValue:-Infinity===c?-Number.MAX_VALUE:c,classBreakInfos:l.map(a,function(a){a=f.mixin({},a);a.symbol=a.symbol&&a.symbol.toJSON();a.classMaxValue=Infinity===a.maxValue?Number.MAX_VALUE:a.maxValue;
delete a.minValue;delete a.maxValue;return b(a)})});a.classificationMethod=n.toJSON(this.classificationMethod);a.normalizationType=m.toJSON(this.normalizationType);a.hasOwnProperty("normalizationType")&&!a.normalizationType&&delete a.normalizationType;a.hasOwnProperty("classificationMethod")&&!a.classificationMethod&&delete a.classificationMethod;return b(a)},clone:function(){return new p({field:this.field,backgroundFillSymbol:this.backgroundFillSymbol&&this.backgroundFillSymbol.clone(),classificationMethod:this.classificationMethod,
defaultSymbol:this.defaultSymbol&&this.defaultSymbol.clone(),expression:this.expression,classBreakInfos:e.clone(this.classBreakInfos),isMaxInclusive:this.isMaxInclusive,normalizationField:this.normalizationField,normalizationTotal:this.normalizationTotal,normalizationType:this.normalizationType,visualVariables:e.clone(this.visualVariables)})},_processCBInfo:function(a){var b=a.minValue,c=a.maxValue,d=a.symbol;d&&!d.declaredClass&&(a.symbol=g.fromJSON(d));this._symbols[b+"-"+c]=a.symbol}});return p});