// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../core/declare ../core/Accessoire ../core/JSONSupporter ../core/jsonDictionary ../core/screenUtils dojo/_base/lang dojo/_base/array ../Color ../arcade/arcade".split(" "),function(D,E,F,w,x,p,e,m,u){var r=w({sizeInfo:"size",colorInfo:"color",transparencyInfo:"opacity",rotationInfo:"rotation"}),B=w({width:"width",depth:"depth",height:"height",widthAndDepth:"width-and-depth",all:"all"}),y=Math.PI;return D([E,F],{declaredClass:"esri.renderer.Renderer",classMetadata:{properties:{requiredFields:{dependsOn:["visualVariables"]}},
reader:{exclude:["rotationType","rotationExpression"]}},constructor:function(){this._ipDataCache={}},getDefaults:function(){return p.mixin(this.inherited(arguments),{authoringInfo:null})},_rotationRE:/^\[([^\]]+)\]$/i,_meterIn:{inches:39.3701,feet:3.28084,yards:1.09361,miles:6.21371E-4,"nautical-miles":5.39957E-4,millimeters:1E3,centimeters:100,decimeters:10,meters:1,kilometers:0.0010,"decimal-degrees":180/20015077},_scaleExpr:"view.scale",_requiredFieldsGetter:function(){var a=Object.create(null);
this.collectRequiredFields(a);return Object.keys(a)},collectRequiredFields:function(a){var b=[];this.visualVariables&&(b=b.concat(this.visualVariables));b.forEach(function(b){b&&b.field&&(a[b.field]=!0);b&&b.normalizationField&&(a[b.normalizationField]=!0)})},_visualVariablesReader:function(a,b){return this._readVariables(a,b)},_visualVariablesSetter:function(a){var b=this._ipDataCache;e.forEach(this.visualVariables,function(a,d){b.hasOwnProperty(d)&&(b[d]=null)},this);e.some(a,function(a){return!!a.target})&&
a.sort(function(a,b){return a.target===b.target?0:a.target?1:-1});e.forEach(a,function(a,d){"color"===a.type?b[d]=this._processColorInfo(a):"opacity"===a.type?b[d]=this._processOpacityInfo(a):"size"===a.type&&(b[d]=this._processSizeInfo(a))},this);return a},getSymbol:function(a){},getVisualVariableValues:function(a,b){var c=this.visualVariables,d;c&&(d=e.map(c,function(c){var d,C=c.type,e=C+"Info";b=p.mixin({},b);b[e]=c;switch(C){case "size":d=this.getSize(a,b);break;case "color":d=this.getColor(a,
b);break;case "opacity":d=this.getOpacity(a,b);break;case "rotation":d=this.getRotationAngle(a,b)}return{variable:c,value:d}},this));return d},hasVisualVariables:function(a,b){return a?!!this.getVisualVariablesForType(a,b):!(!this.getVisualVariablesForType("size",b)&&!this.getVisualVariablesForType("color",b)&&!this.getVisualVariablesForType("opacity",b)&&!this.getVisualVariablesForType("rotation",b))},getVisualVariablesForType:function(a,b){var c=this.visualVariables,d;c&&(d=e.filter(c,function(c){return c.type===
a&&("string"===typeof b?c.target===b:!1===b?!c.target:!0)}))&&0===d.length&&(d=void 0);return d},getSize:function(a,b){var c=this._getVarInfo(b&&b.sizeInfo,"size"),d=c.variable,c=this._ipDataCache[c.cacheKey],f=null;if(d)var n=d.minSize,f=d.maxSize,n="object"===typeof n&&n?this._getSize(a,n,c&&c.minSize,b):n,f="object"===typeof f&&f?this._getSize(a,f,c&&c.maxSize,b):f,f=this._getSize(a,d,c&&c.root,b,[n,f]);return f},getSizeRangeAtScale:function(a,b){var c,d=this._getVarInfo(a,"size"),f=this._ipDataCache[d.cacheKey],
n={scale:b};if((a=d.variable)&&b){var e=a.minSize,d=a.maxSize,e="object"===typeof e&&e?this._getSize({},e,f&&f.minSize,n):e,f="object"===typeof d&&d?this._getSize({},d,f&&f.maxSize,n):d;if(null!=e||null!=f)c={minSize:e,maxSize:f}}return c},getColor:function(a,b){var c=this._getVarInfo(b&&b.colorInfo,"color");return this._getColorComponent(a,c.variable,this._ipDataCache[c.cacheKey])},getOpacity:function(a,b){var c=this._getVarInfo(b&&b.opacityInfo,"opacity");return this._getColorComponent(a,c.variable,
this._ipDataCache[c.cacheKey],!0)},getRotationAngle:function(a,b){var c=this._getVarInfo(b&&b.rotationInfo,"rotation").variable,d="arithmetic"===c.rotationType,c=c.field,f=a.attributes,n=0;c&&(p.isFunction(c)?n=c.apply(this,arguments):f&&(n=f[c]||0),n=(n+(d?-90:0))*(d?-1:1));return n},toJSON:function(){var a,b=this.visualVariables,c=p.clone(this.authoringInfo),d=this.getVisualVariablesForType("rotation",!1),f=d&&d[0],d=(d=f&&f.field)&&(p.isFunction(d)?d:"["+d+"]");b&&(a=[],e.forEach(b,function(b){"size"===
b.type?a.push(this._writeSizeInfo(b)):"color"===b.type?a.push(this._writeColorInfo(b)):"opacity"===b.type?a.push(this._writeOpacityInfo(b)):"rotation"===b.type&&!f&&a.push(this._writeRotationInfo(b))},this));c&&e.forEach(c.visualVariables,function(a){"opacity"===a.type&&(a.type=r.toJSON(a.type))});return{rotationType:d&&(f.rotationType||"geographic"),rotationExpression:d,visualVariables:a,authoringInfo:c}},_getVarInfo:function(a,b){var c;a&&a.type===b?(c=e.indexOf(this.visualVariables,a),a=this.visualVariables[c]):
(a=(c=this.getVisualVariablesForType(b))&&c[0],c=e.indexOf(this.visualVariables,a));return{variable:a,cacheKey:c}},_readSizeInfo:function(a){a.axis&&(a.axis=B.fromJSON(a.axis));return a},_readColorInfo:function(a){a&&(e.forEach(a.colors,function(b,c){p.isArray(b)?a.colors[c]=m.fromJSON(b):a.colors[c]=new m(b)}),e.forEach(a.stops,function(b,c){b.color&&p.isArray(b.color)?a.stops[c].color=m.fromJSON(b.color):b.color&&(a.stops[c].color=new m(b.color))}));return a},_readOpacityInfo:function(a){var b;
a&&(b=p.mixin({},a),b.transparencyValues&&(b.opacityValues=e.map(b.transparencyValues,function(a){return 1-a/100}),delete b.transparencyValues),b.stops&&(b.stops=e.map(b.stops,function(a){a=p.mixin({},a);a.opacity=1-a.transparency/100;delete a.transparency;return a})));return b},_readVariables:function(a,b){a&&(a=e.map(a,function(a){a.type=r.fromJSON(a.type);"size"===a.type?a=this._readSizeInfo(a):"color"===a.type?a=this._readColorInfo(a):"opacity"===a.type&&(a=this._readOpacityInfo(a));return a},
this));var c=b.rotationType,d=b.rotationExpression;if(d)if(c={type:"rotation",rotationType:c},p.isFunction(d))c.field=d,a.push(c);else if((d=d.match(this._rotationRE))&&d[1])c.field=d[1],a.push(c);return a},_processColorInfo:function(a){a&&(e.forEach(a.colors,function(b,c){b instanceof m||(a.colors[c]=new m(b))}),e.forEach(a.stops,function(b,c){b.color&&!(b.color instanceof m)&&(a.stops[c].color=new m(b.color))}));return this._interpolateData(a)},_processOpacityInfo:function(a){return this._interpolateData(a)},
_processSizeInfo:function(a){a.stops&&Array.isArray(a.stops)?a.stops=this._processSizeInfoStops(a.stops):(a.minSize=a.minSize&&this._processSizeInfoSize(a.minSize),a.maxSize=a.maxSize&&this._processSizeInfoSize(a.maxSize));return{root:this._interpolateData(a),minSize:this._interpolateData(a.minSize),maxSize:this._interpolateData(a.maxSize)}},_processSizeInfoSize:function(a){"object"===typeof a?a.stops=this._processSizeInfoStops(a.stops):a=x.toPt(a);return a},_processSizeInfoStops:function(a){a&&Array.isArray(a)&&
a.forEach(function(a){a.size=x.toPt(a.size)});return a},_getSize:function(a,b,c,d,f){var n=a.attributes,e=b.field,s=b.expression,h=b.stops,g=0,m="number"===typeof a,k=m?a:null;if(e||s){var r=d&&d.scale,l=f?f[0]:b.minSize,q=f?f[1]:b.maxSize,t=b.minDataValue,u=b.maxDataValue,w=b.valueUnit||"unknown",A=b.valueRepresentation,g=b.scaleBy,x=b.normalizationField,z=n?parseFloat(n[x]):void 0,v=d&&d.shape;s&&(k=s.toLowerCase()===this._scaleExpr?null==r?this._getAverageValue(b):r:null);"number"!==typeof k&&
(p.isFunction(e)?k=e.apply(this,arguments):n&&(k=n[e]));if(null==k||x&&!m&&(isNaN(z)||0===z))return null;!isNaN(z)&&!m&&(k/=z);if(h)q=this._lookupData(k,c),k=q[0],l=q[1],k===l?g=h[k].size:(k=h[k].size,h=h[l].size,g=k+(h-k)*q[2]);else if(null!=l&&null!=q&&null!=t&&null!=u)k<=t?g=l:k>=u?g=q:(h=(k-t)/(u-t),"area"===g&&v?(l=(k="circle"===v)?y*Math.pow(l/2,2):l*l,q=k?y*Math.pow(q/2,2):q*q,h=l+h*(q-l),g=k?2*Math.sqrt(h/y):Math.sqrt(h)):g=l+h*(q-l));else if("unknown"===w)null!=l&&null!=t?(l&&t?(h=k/t,g=
"circle"===v?2*Math.sqrt(h*Math.pow(l/2,2)):"square"===v||"diamond"===v||"image"===v?Math.sqrt(h*Math.pow(l,2)):h*l):g=k+(l||t),g=g<l?l:g,null!=q&&g>q&&(g=q)):g=k;else{h=(d&&d.resolution?d.resolution:1)*this._meterIn[w];if("area"===A)g=Math.sqrt(k/y)/h,g*=2;else if(g=k/h,"radius"===A||"distance"===A)g*=2;null!=l&&g<l&&(g=l);null!=q&&g>q&&(g=q)}}else b&&(g=h&&h[0]&&h[0].size,null==g&&(g=b.minSize));return g=isNaN(g)?0:g},_getAverageValue:function(a){var b=a.stops,c;b?(c=b[0].value,a=b[b.length-1].value):
(c=a.minDataValue||0,a=a.maxDataValue||0);return(c+a)/2},_getColorComponent:function(a,b,c,d,f){var e=a.attributes,m=b&&b.field,s="number"===typeof a?a:null,h;if(m){var g=b.normalizationField,r=e?parseFloat(e[g]):void 0;"number"!==typeof s&&(p.isFunction(m)?s=m.apply(this,arguments):e&&(s=e[m]));null!=s&&(g&&(!isNaN(r)&&0!==r)&&(s/=r),h=d?this._getOpacity(s,b,c):this._getColor(s,b,c))}else b&&(e=b.stops,d?(h=e&&e[0]&&e[0].opacity,null==h&&(h=b.opacityValues&&b.opacityValues[0])):h=e&&e[0]&&e[0].color||
b.colors&&b.colors[0]);f&&(f.data=s,f.value=h);return f||h},_interpolateData:function(a){var b;if(a)if(a.colors||a.opacityValues){var c=(a.colors||a.opacityValues).length,d=a.minDataValue,f=(a.maxDataValue-d)/(c-1);b=[];for(a=0;a<c;a++)b[a]=d+a*f}else a.stops&&(b=e.map(a.stops,function(a){return a.value}));return b},_getOpacity:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.opacityInfo;a&&(c=a[0],d=a[1],c===d?d=this._getOpacValue(b,c):(c=this._getOpacValue(b,c),b=this._getOpacValue(b,d),
d=c+(b-c)*a[2]));return d},_getOpacValue:function(a,b){return a.opacityValues?a.opacityValues[b]:a.stops[b].opacity},_getColor:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.colorInfo;a&&(d=a[0],c=a[1],d=d===c?this._getColorObj(b,d):m.blendColors(this._getColorObj(b,d),this._getColorObj(b,c),a[2]),d=new m(d));return d},_getColorObj:function(a,b){return a.colors?a.colors[b]:a.stops[b].color},_lookupData:function(a,b){var c;if(b){var d=0,f=b.length-1;e.some(b,function(b,c){if(a<b)return f=
c,!0;d=c;return!1});c=[d,f,(a-b[d])/(b[f]-b[d])]}return c},_writeRotationInfo:function(a){a&&(a=p.mixin({},a),a.type=r.toJSON(a.type));return a},_writeSizeInfo:function(a){if(a){a=p.mixin({},a);var b=a.legendOptions,c=a.axis;a.type=r.toJSON(a.type);c&&(a.axis=B.toJSON(c));if(b&&(a.legendOptions=p.mixin({},b),b=b.customValues))a.legendOptions.customValues=b.slice(0)}return a},_writeColorInfo:function(a){a&&(a=p.mixin({},a),a.type=r.toJSON(a.type),a.colors&&(a.colors=e.map(a.colors,function(a){return m.toJSON(a)})),
a.stops&&(a.stops=e.map(a.stops,function(a){a=p.mixin({},a);a.color&&(a.color=m.toJSON(a.color));return a})));return a},_writeOpacityInfo:function(a){var b;a&&(b=p.mixin({},a),b.type=r.toJSON(b.type),b.opacityValues&&(b.transparencyValues=e.map(b.opacityValues,function(a){return 100*(1-a)}),delete b.opacityValues),b.stops&&(b.stops=e.map(b.stops,function(a){a=p.mixin({},a);a.transparency=100*(1-a.opacity);delete a.opacity;return a})));return b},_createExprContext:function(a){return{vars:{$feature:u.constructFeature(a)}}},
_parseExpr:function(a,b){return u.parseScript(a,b)},_executeExpr:function(a,b){return u.executeScript(a,b,-1)}})});