// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../core/declare dojo/_base/lang dojo/Deferred ../../../core/Accessoire ../../../core/AccessoirePromise ../../../core/urlUtils ../../../core/promiseUtils ../../support/WebSocketConnector ../../../tasks/QueryTask ../../../request".split(" "),function(p,d,q,r,s,l,h,t,n,u){return p([r,s],{classMetadata:{properties:{url:{dependsOn:["layerDefinition"]},parsedUrl:{dependsOn:["url"]},connectionInfo:{dependsOn:["layerDefinition"]}}},getDefaults:function(a){var b=this.inherited(arguments),e=a.layer;
e&&(b=d.mixin(b,{url:e.url,connectionInfo:{direction:e.socketDirection,socketUrl:e.socketUrl}}));return b},initialize:function(){this.addResolvingPromise(this._fetchLayers())},_connectionInfoGetter:function(){if(this.layer.hasMemorySource||this.layer.socketUrl)return{serviceSocketUrls:[this.layer.socketUrl]};var a={},b=this.layerDefinition,e=[],f=[],c=[],d,g,k;b.streamUrls&&b.streamUrls.forEach(function(b){"ws"===b.transport&&(e=b.urls,a.token=b.token)},this);e.forEach(function(a){0===a.lastIndexOf("wss",
0)?c.push(a):f.push(a)});if((b="https"===l.appUrl.scheme||0===this.url.lastIndexOf("https:",0)?c:0===f.length?c:f)&&1<b.length)for(d=0;d<b.length-1;d++)g=d+Math.floor(Math.random()*(b.length-d)),k=b[g],b[g]=b[d],b[d]=k;a.serviceSocketUrls=b;return a},_latestUrlGetter:function(){var a=this.layerDefinition;return(a=a.keepLatestArchive&&a.keepLatestArchive.featuresUrl)?a:null},_latestQueryTaskGetter:function(){var a=this.latestUrl;return a?new n(a):null},_relatedFeaturesInfoGetter:function(){var a=(this.layerDefinition||
{}).relatedFeatures;return a=a&&a.featuresUrl?a:null},_relatedFeaturesQueryTaskGetter:function(){var a=this.relatedFeaturesInfo;return(a=a?a.featuresUrl:null)?new n(a):null},_parsedUrlGetter:function(){return this.url?l.urlToObject(this.url):null},url:null,createWebSocketConnector:function(a){var b=this,e=new q;b.then(function(){var f=b.connectionInfo,c,h=b.layer.spatialReference,g,k,m={};try{c=b.makeFilter()}catch(l){e.reject(l);return}if(f){f.socketUrl?k=[f.socketUrl]:f.serviceSocketUrls&&(k=f.serviceSocketUrls.map(function(a){return a+
"/"+b.layer.socketDirection}));m.socketUrls=k;if(c&&(c.where||c.geometry||c.outFields)||f.token)g=d.mixin(g||{},{where:c.where,geometry:c.geometry,outFields:c.outFields,token:f.token});a&&(h&&a.wkid!==h.wkid)&&(g=d.mixin(g||{},{outSR:a.wkid}));m.queryParams=g;m.layerSource=b;f=new t(m);e.resolve(f)}else e.reject(Error("No web socket urls found"))});return e.promise},getWebSocketToken:function(){return this._fetchLayer().then(function(){var a=null;this.layerDefinition.streamUrls&&this.layerDefinition.streamUrls.some(function(b){if("ws"===
b.transport)return a=b.token,!0},this);return a}.bind(this))},makeFilter:function(a){var b=this.layer,e=null,f=null,c;a?(a.hasOwnProperty("definitionExpression")&&(c=d.mixin(c||{},{where:a.definitionExpression})),a.hasOwnProperty("geometryDefinition")&&(e=a.geometryDefinition,c=d.mixin(c||{},{geometry:e}))):(b.hasOwnProperty("definitionExpression")&&b.definitionExpression&&(c=d.mixin(c||{},{where:b.definitionExpression})),b.hasOwnProperty("geometryDefinition")&&b.geometryDefinition&&(e=JSON.stringify(b.geometryDefinition.toJSON()),
c=d.mixin(c||{},{geometry:e})));b.hasOwnProperty("outFields")&&(b.outFields&&"*"!==b.outFields[0]&&(f=b.outFields.join(",")),c=d.mixin(c||{},{outFields:f}));return c},_fetchLayers:function(){return this._fetchStreamLayer().then(function(a){a.ssl&&(this.url=this.url.replace(/^http:/i,"https:"));this.layerDefinition=a.data;return this._fetchArchiveLayer()}.bind(this)).then(function(a){this.archivedLayerDefinition=a&&a.data;return this._fetchRelatedLayer()}.bind(this)).then(function(a){this.relatedLayerDefinition=
a&&a.data}.bind(this))},_fetchStreamLayer:function(){return this._requestServiceDefinition({url:this.layer.parsedUrl.path,content:d.mixin({f:"json"},this.layer.parsedUrl.query)})},_fetchArchiveLayer:function(){var a=this.latestUrl;return!a?h.resolve():this._requestServiceDefinition({url:a})},_fetchRelatedLayer:function(){var a=this.relatedFeaturesInfo;return!a?h.resolve():this._requestServiceDefinition({url:a.featuresUrl})},_requestServiceDefinition:function(a){return!a||!a.url?h.reject(Error("url is a required options property")):
u(a.url,{query:d.mixin(a.content||{},{f:"json"}),responseType:"json",callbackParamName:"callback"})}})});