// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/accessoireSupport/typescript ../core/Error ../config ../identity/IdentityManager ../request ../geometry/Extent ../core/JSONSupporter ../core/LoadableAccessoire ./PortalQueryParams ./PortalQueryResult ./PortalUser ../core/promiseUtils ../core/requireUtils dojo/promise/all dojo/_base/kernel dojo/_base/lang".split(" "),function(l,D,t,b,c,u,v,h,w,x,y,z,p,A,B,q,m,r,C,k){var n;return function(s){function a(a){s.call(this);
this.useStandardizedQuery=this.user=this.urlKey=this.url=this.units=this.thumbnailUrl=this.templatesGroupQuery=this.symbolSetsGroupQuery=this.supportsHostedServices=this.showHomePageDescription=this.rotatorPanels=this.restUrl=this.region=this.portalProperties=this.portalMode=this.portalHostname=this.name=this.modified=this.maxTokenExpirationMinutes=this.layerTemplatesGroupQuery=this.isPortal=this.isOrganization=this.ipCntryCode=this.id=this.httpsPort=this.httpPort=this.homePageFeaturedContentCount=
this.homePageFeaturedContent=this.galleryTemplatesGroupQuery=this.featuredItemsGroupQuery=this.featuredGroups=this.extraQuery=this.description=this.defaultExtent=this.defaultBasemap=this.customBaseUrl=this.culture=this.created=this.commentsEnabled=this.colorSetsGroupQuery=this.canSignInIDP=this.canSignInArcGIS=this.canSharePublic=this.canShareBingPublic=this.canSearchPublic=this.canProvisionDirectPurchase=this.canListPreProvisionedItems=this.canListData=this.canListApps=this.bingKey=this.authorizedCrossOriginDomains=
this.authMode=this.allSSL=this.access=null}t(a,s);a.prototype.normalizeCtorArgs=function(a){return"string"===typeof a?{url:a}:a};a.prototype.getDefaults=function(a){return k.mixin(this.inherited(arguments),{url:v.portalUrl})};a.prototype.initialize=function(){var f=this;this._esriId_credentialCreateHandle=h.on("credential-create",function(){f.loaded&&(!f.credential&&f.authMode===a.AUTH_MODE_AUTO)&&(f.credential=h.findCredential(f.restUrl),f.credential&&f._fetchSelf().then(function(a){f.read(a)}))})};
a.prototype.destroy=function(){this._esriId_credentialCreateHandle&&(this._esriId_credentialCreateHandle.remove(),this._esriId_credentialCreateHandle=null)};a.prototype._defaultBasemapReader=function(a){return a?n.fromJSON(a):null};a.prototype._extraQueryGetter=function(){return this.id&&!this.canSearchPublic?" AND orgid:"+this.id:null};a.prototype._isOrganizationGetter=function(){return!!this.access};a.prototype._restUrlGetter=function(){var a=this.url;if(a)var b=a.indexOf("/sharing"),a=0<b?a.substring(0,
b):this.url.replace(/\/+$/,""),a=a+"/sharing/rest";return a};a.prototype._thumbnailUrlGetter=function(){var a=this.restUrl,b=this.thumbnail;return a&&b?this._normalizeSSL(a+"/portals/self/resources/"+b):null};a.prototype._userReader=function(a){var b=null;a&&(b=B.fromJSON(a),b.portal=this);return b};a.prototype.load=function(){var b=this,c=q.resolve().then(function(){return b.authMode===a.AUTH_MODE_IMMEDIATE?h.getCredential(b.restUrl):b.authMode===a.AUTH_MODE_AUTO?h.checkSignInStatus(b.restUrl).otherwise(function(){return null}):
null}).then(function(a){b.credential=a;return m.when(l,"../Basemap")}).then(function(a){n=a}).then(function(){return b._fetchSelf()}).then(function(a){b.read(a)});this.addResolvingPromise(c);return this};a.prototype.fetchBasemaps=function(){var a=new p;a.query=this.basemapGalleryGroupQuery;return this.queryGroups(a).then(function(b){a.num=100;a.query=null;return b.total?b.results[0].queryItems(a):null}).then(function(a){return a&&a.total?a.results.map(function(a){return new n({portalItem:a})}):[]})};
a.prototype.fetchFeaturedGroups=function(){var a=this.featuredGroups,b=new p;b.num=100;b.sortField="title";if(a&&a.length){for(var c=[],e=0;e<a.length;e++){var g=a[e];c.push('(title:"'+g.title+'" AND owner:'+g.owner+")")}b.query=c.join(" OR ");return this.queryGroups(b).then(function(a){return a.results})}return q.resolve([])};a.getDefault=function(){a._default||(a._default=new a);return a._default};a.prototype.queryGroups=function(a){return this._queryPortal("/community/groups",a,"PortalGroup")};
a.prototype.queryItems=function(a){return this._queryPortal("/search",a,"PortalItem")};a.prototype.queryUsers=function(a){a.sortField||(a.sortField="username");return this._queryPortal("/community/users",a,"PortalUser")};a.prototype.toJSON=function(){throw new u("internal:not-yet-implemented","Portal.toJSON is not yet implemented");};a.prototype._fetchSelf=function(){return this._request(this.restUrl+"/portals/self",{query:{culture:C.locale}})};a.prototype._queryPortal=function(b,c,d){var e=this,
g=function(d){return e._request(e.restUrl+b,c.toRequestOptions(e)).then(function(b){var f=c.clone();f.start=b.nextStart;return new A({nextQueryParams:f,queryParams:c,total:b.total,results:a._resultsToTypedArray(d,{portal:e},b)})}).then(function(a){return r(a.results).always(function(){return a})})};return d?m.when(l,"./"+d).then(function(a){return g(a)}):g()};a.prototype._normalizeSSL=function(b){var c=this.allSSL||window&&"https:"===window.location.protocol;if(this.isPortal){var d=a._getLocation(b);
if(-1<this.portalHostname.toLowerCase().indexOf(d.hostname.toLowerCase())&&d.port&&"80"!==d.port&&"443"!==d.port)return b=d.pathname,0!==b.indexOf("/")&&(b="/"+b),c?"https://"+d.hostname+(this.httpsPort&&443!==this.httpsPort?":"+this.httpsPort:"")+b+d.search:"http://"+d.hostname+(this.httpPort&&80!==this.httpPort?":"+this.httpPort:"")+b+d.search}return c?b.replace("http:","https:"):b};a.prototype._normalizeUrl=function(a){var b=this.credential&&this.credential.token;return this._normalizeSSL(b?a+
(-1<a.indexOf("?")?"\x26":"?")+"token\x3d"+b:a)};a.prototype._requestToTypedArray=function(b,c,d){var e=this,g=function(d){return e._request(b,c).then(function(b){var c=a._resultsToTypedArray(d,{portal:e},b);return r(c).always(function(){return c})})};return d?m.when(l,"./"+d).then(function(a){return g(a)}):g()};a.prototype._request=function(b,c){var d={f:"json"},e={disableIdentityLookup:this.authMode===a.AUTH_MODE_ANONYMOUS},g;c&&(k.mixin(d,c.query),g=c.responseType,e.method=c.method);return w(this._normalizeSSL(b),
k.mixin({callbackParamName:"callback",query:d,responseType:g,timeout:0},e)).then(function(a){return a.data})};a._getLocation=function(a){var b=document.createElement("a");b.href=a;return{protocol:b.protocol,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,host:b.host}};a._resultsToTypedArray=function(a,b,c){if(c){if(c=c.listings||c.notifications||c.userInvitations||c.tags||c.items||c.groups||c.comments||c.provisions||c.results||c.relatedItems||c,a||b)c=c.map(function(c){c=
k.mixin(a?a.fromJSON(c):c,b);"function"===typeof c.load&&c.load();return c})}else c=[];return c};a.AUTH_MODE_ANONYMOUS="anonymous";a.AUTH_MODE_AUTO="auto";a.AUTH_MODE_IMMEDIATE="immediate";b([c.shared("esri.portal.Portal")],a.prototype,"declaredClass",void 0);b([c.property()],a.prototype,"access",void 0);b([c.property()],a.prototype,"allSSL",void 0);b([c.property({value:a.AUTH_MODE_AUTO})],a.prototype,"authMode",void 0);b([c.property()],a.prototype,"authorizedCrossOriginDomains",void 0);b([c.property()],
a.prototype,"basemapGalleryGroupQuery",void 0);b([c.property()],a.prototype,"bingKey",void 0);b([c.property()],a.prototype,"canListApps",void 0);b([c.property()],a.prototype,"canListData",void 0);b([c.property()],a.prototype,"canListPreProvisionedItems",void 0);b([c.property()],a.prototype,"canProvisionDirectPurchase",void 0);b([c.property()],a.prototype,"canSearchPublic",void 0);b([c.property()],a.prototype,"canShareBingPublic",void 0);b([c.property()],a.prototype,"canSharePublic",void 0);b([c.property()],
a.prototype,"canSignInArcGIS",void 0);b([c.property()],a.prototype,"canSignInIDP",void 0);b([c.property()],a.prototype,"colorSetsGroupQuery",void 0);b([c.property()],a.prototype,"commentsEnabled",void 0);b([c.property({type:Date})],a.prototype,"created",void 0);b([c.property()],a.prototype,"credential",void 0);b([c.property()],a.prototype,"culture",void 0);b([c.property()],a.prototype,"customBaseUrl",void 0);b([c.property()],a.prototype,"defaultBasemap",void 0);b([c.property({type:x})],a.prototype,
"defaultExtent",void 0);b([c.property()],a.prototype,"description",void 0);b([c.property({dependsOn:["id","canSearchPublic"],readOnly:!0})],a.prototype,"extraQuery",void 0);b([c.property()],a.prototype,"featuredGroups",void 0);b([c.property()],a.prototype,"featuredItemsGroupQuery",void 0);b([c.property()],a.prototype,"galleryTemplatesGroupQuery",void 0);b([c.property()],a.prototype,"helpBase",void 0);b([c.property()],a.prototype,"helperServices",void 0);b([c.property()],a.prototype,"helpMap",void 0);
b([c.property()],a.prototype,"homePageFeaturedContent",void 0);b([c.property()],a.prototype,"homePageFeaturedContentCount",void 0);b([c.property()],a.prototype,"httpPort",void 0);b([c.property()],a.prototype,"httpsPort",void 0);b([c.property({value:null})],a.prototype,"id",void 0);b([c.property()],a.prototype,"ipCntryCode",void 0);b([c.property({dependsOn:["access"],readOnly:!0})],a.prototype,"isOrganization",void 0);b([c.property()],a.prototype,"isPortal",void 0);b([c.property()],a.prototype,"layerTemplatesGroupQuery",
void 0);b([c.property()],a.prototype,"maxTokenExpirationMinutes",void 0);b([c.property({type:Date})],a.prototype,"modified",void 0);b([c.property()],a.prototype,"name",void 0);b([c.property()],a.prototype,"portalHostname",void 0);b([c.property()],a.prototype,"portalMode",void 0);b([c.property()],a.prototype,"portalProperties",void 0);b([c.property()],a.prototype,"region",void 0);b([c.property({dependsOn:["url"],readOnly:!0})],a.prototype,"restUrl",void 0);b([c.property()],a.prototype,"rotatorPanels",
void 0);b([c.property()],a.prototype,"showHomePageDescription",void 0);b([c.property()],a.prototype,"stylesGroupQuery",void 0);b([c.property()],a.prototype,"supportsHostedServices",void 0);b([c.property()],a.prototype,"symbolSetsGroupQuery",void 0);b([c.property()],a.prototype,"templatesGroupQuery",void 0);b([c.property()],a.prototype,"thumbnail",void 0);b([c.property({dependsOn:["restUrl","thumbnail"],readOnly:!0})],a.prototype,"thumbnailUrl",void 0);b([c.property()],a.prototype,"units",void 0);
b([c.property()],a.prototype,"url",void 0);b([c.property()],a.prototype,"urlKey",void 0);b([c.property()],a.prototype,"user",void 0);b([c.property()],a.prototype,"useStandardizedQuery",void 0);return a=b([c.subclass([z])],a)}(y)});