// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/accessoireSupport/typescript ../core/Error ../core/lang ../geometry/Extent ../core/JSONSupporter ../core/LoadableAccessoire ./Portal ../core/promiseUtils".split(" "),function(q,r,h,d,c,k,l,e,m,n,f,p){return function(g){function b(a){g.call(this);this.url=this.typeKeywords=this.type=this.title=this.thumbnailUrl=this.tags=this.snippet=this.portal=this.ownerFolder=this.name=this.modified=this.itemUrl=this.itemControl=
this.isLayer=this.id=this.extent=this.description=this.created=null}h(b,g);b.prototype._isLayerGetter=function(){return-1<"Map Service;Feature Service;Feature Collection;Scene Service;Image Service;Stream Service;Vector Tile Service".split(";").indexOf(this.type)};b.prototype._itemUrlGetter=function(){var a=this.get("portal.restUrl");return a?a+"/content/items/"+this.id:null};b.prototype._thumbnailUrlGetter=function(){var a=this.itemUrl,b=this.thumbnail;return a&&b?this.portal._normalizeUrl(a+"/info/"+
b):null};b.prototype.load=function(){var a=this;this.portal||(this.portal=f.getDefault());var b=this.portal.load().then(function(){return a.resourceInfo?a.resourceInfo:a.id&&a.itemUrl?a.portal._request(a.itemUrl):{}}).then(function(b){a.resourceInfo=b;a.read(b)});this.addResolvingPromise(b);return this};b.prototype.fetchData=function(a){void 0===a&&(a="json");return this.portal._request(this.itemUrl+"/data",{responseType:a})};b.prototype.fetchRelatedItems=function(a){return this.portal._requestToTypedArray(this.itemUrl+
"/relatedItems",{query:a},"PortalItem")};b.prototype.update=function(a){var b=this,d=a&&a.data;a={method:"post"};a.query=this.toJSON();for(var c in a.query)null===a.query[c]&&(a.query[c]="");a.query.clearEmptyFields=!0;"string"===typeof d?a.query.text=d:d&&"function"===typeof d.toJSON&&(a.query.text=JSON.stringify(d));return(c=this.portal&&this.portal.user&&this.portal.user.userContentUrl)?(this.ownerFolder&&(c+="/"+this.ownerFolder),this.portal._request(c+("/items/"+this.id+"/update"),a).then(function(){return b.loaded?
b._reload():b.load()})):p.reject(new k("portal:not-signed-in","Not signed in"))};b.prototype.toJSON=function(){var a=this.extent,a={created:this.created&&this.created.getTime(),description:this.description,extent:a&&[[a.xmin,a.ymin],[a.xmax,a.ymax]],id:this.id,modified:this.modified&&this.modified.getTime(),name:this.name,ownerFolder:this.ownerFolder,thumbnail:this.thumbnail,title:this.title,type:this.type,typeKeywords:this.typeKeywords,url:this.url};return l.fixJson(a)};b.fromJSON=function(a){if(!a)return null;
if(a.declaredClass)throw Error("JSON object is already hydrated");return new b({resourceInfo:a})};b.prototype._reload=function(){var a=this;return this.portal._request(this.itemUrl,{query:{_ts:(new Date).getTime()}}).then(function(b){a.resourceInfo=b;a.read(b);return a})};d([c.shared("esri.portal.PortalItem")],b.prototype,"declaredClass",void 0);d([c.property({type:Date})],b.prototype,"created",void 0);d([c.property()],b.prototype,"description",void 0);d([c.property({type:e,reader:function(a){return a&&
a.length?new e(a[0][0],a[0][1],a[1][0],a[1][1]):null}})],b.prototype,"extent",void 0);d([c.property()],b.prototype,"id",void 0);d([c.property({dependsOn:["type"],readOnly:!0})],b.prototype,"isLayer",void 0);d([c.property()],b.prototype,"itemControl",void 0);d([c.property({dependsOn:["portal.restUrl"],readOnly:!0})],b.prototype,"itemUrl",void 0);d([c.property({type:Date})],b.prototype,"modified",void 0);d([c.property()],b.prototype,"name",void 0);d([c.property()],b.prototype,"ownerFolder",void 0);
d([c.property({type:f})],b.prototype,"portal",void 0);d([c.property()],b.prototype,"resourceInfo",void 0);d([c.property()],b.prototype,"snippet",void 0);d([c.property()],b.prototype,"tags",void 0);d([c.property()],b.prototype,"thumbnail",void 0);d([c.property({dependsOn:["itemUrl","thumbnail","portal.credential.token"],readOnly:!0})],b.prototype,"thumbnailUrl",void 0);d([c.property()],b.prototype,"title",void 0);d([c.property()],b.prototype,"type",void 0);d([c.property()],b.prototype,"typeKeywords",
void 0);d([c.property()],b.prototype,"url",void 0);return b=d([c.subclass([n])],b)}(m)});