// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/accessoireSupport/typescript ../core/Error ../core/JSONSupporter ./PortalFolder ./PortalGroup ../core/promiseUtils ../core/requireUtils dojo/promise/all".split(" "),function(l,u,m,d,c,h,n,p,q,r,s,t){return function(k){function a(){k.call(this);this.username=this.url=this.userContentUrl=this.thumbnailUrl=this.portal=this.modified=this.created=null}m(a,k);a.prototype._thumbnailUrlGetter=function(){var b=
this.url,a=this.thumbnail;return b&&a?this.portal._normalizeUrl(b+"/info/"+a):null};a.prototype._userContentUrlGetter=function(){var b=this.get("portal.restUrl");return b?b+"/content/users/"+this.username:null};a.prototype._urlGetter=function(){var b=this.get("portal.restUrl");return b?b+"/community/users/"+this.username:null};a.prototype.addItem=function(b){var a=this,f=b&&b.item,e=b&&b.data;b=b&&b.folder;var g={method:"post"};f&&(g.query=f.toJSON(),"string"===typeof e?g.query.text=e:e&&"function"===
typeof e.toJSON&&(g.query.text=JSON.stringify(e)));e=this.userContentUrl;b&&(e+="/"+b.id);return this.portal._request(e+"/addItem",g).then(function(b){f.id=b.id;f.portal=a.portal;return f.loaded?f._reload():f.load()})};a.prototype.deleteItem=function(b){var a=this.userContentUrl;b.ownerFolder&&(a+="/"+b.ownerFolder);return this.portal._request(a+("/items/"+b.id+"/delete"),{method:"post"}).then(function(){b.id=null;b.portal=null})};a.prototype.fetchFolders=function(){var b=this;return this.portal._request(this.userContentUrl,
{query:{num:1}}).then(function(a){return a&&a.folders?a.folders.map(function(a){a=p.fromJSON(a);a.portal=b.portal;return a}):[]})};a.prototype.fetchItems=function(a){var d=this;a||(a={});var c=this.userContentUrl;a.folder&&(c+="/"+a.folder.id);var e;return s.when(l,"./PortalItem").then(function(g){e=g;return d.portal._request(c,{query:{folders:!1,num:a.num||10,start:a.start||1}})}).then(function(a){var b;return a&&a.items?(b=a.items.map(function(a){a=e.fromJSON(a);a.portal=d.portal;a.load();return a}),
t(b).always(function(){return{items:b,nextStart:a.nextStart,total:a.total}})):{items:[],nextStart:-1,total:0}})};a.prototype.queryFavorites=function(a){return this.favGroupId?(this._favGroup||(this._favGroup=new q({id:this.favGroupId,portal:this.portal})),this._favGroup.queryItems(a)):r.reject(new h("internal:unknown","Unknown internal error",{internalError:"Unknown favGroupId"}))};a.prototype.toJSON=function(){throw new h("internal:not-yet-implemented","PortalGroup.toJSON is not yet implemented");
};d([c.shared("esri.portal.PortalUser")],a.prototype,"declaredClass",void 0);d([c.property({type:Date})],a.prototype,"created",void 0);d([c.property()],a.prototype,"favGroupId",void 0);d([c.property({type:Date})],a.prototype,"modified",void 0);d([c.property()],a.prototype,"portal",void 0);d([c.property()],a.prototype,"thumbnail",void 0);d([c.property({dependsOn:["url","thumbnail","portal.credential.token"],readOnly:!0})],a.prototype,"thumbnailUrl",void 0);d([c.property({dependsOn:["portal.restUrl"],
readOnly:!0})],a.prototype,"userContentUrl",void 0);d([c.property({dependsOn:["portal.restUrl"],readOnly:!0})],a.prototype,"url",void 0);d([c.property()],a.prototype,"username",void 0);return a=d([c.subclass()],a)}(n)});