// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
require({cache:{"esri/numberUtils":function(){define(["dojo/has","dojo/number","dojo/i18n!dojo/cldr/nls/number","./kernel"],function(y,F,n,f){var m=function(f,p){return f-p},u={_reNumber:/^-?(\d+)(\.(\d+))?$/i,getDigits:function(f){var p=String(f),k=p.match(u._reNumber);f={integer:0,fractional:0};k&&k[1]?(f.integer=k[1].split("").length,f.fractional=k[3]?k[3].split("").length:0):-1<p.toLowerCase().indexOf("e")&&(k=p.split("e"),p=k[0],k=k[1],p&&k&&(p=Number(p),k=Number(k),(f=0<k)||(k=Math.abs(k)),
p=u.getDigits(p),f?(p.integer+=k,p.fractional=k>p.fractional?0:p.fractional-k):(p.fractional+=k,p.integer=k>p.integer?1:p.integer-k),f=p));return f},getFixedNumbers:function(f,p){var k,n;k=Number(f.toFixed(p));k<f?n=k+1/Math.pow(10,p):(n=k,k-=1/Math.pow(10,p));k=Number(k.toFixed(p));n=Number(n.toFixed(p));return[k,n]},getPctChange:function(f,p,k,n){var m={prev:null,next:null},u;null!=k&&(u=f-k,k=p-k-u,m.prev=Math.floor(Math.abs(100*k/u)));null!=n&&(u=n-f,k=n-p-u,m.next=Math.floor(Math.abs(100*k/u)));
return m},round:function(f,p){var k=f.slice(0),n,y,F,t,h,r,J,H,z,P=!p||null==p.tolerance?2:p.tolerance,x=p&&p.indexes,Q=!p||null==p.strictBounds?!1:p.strictBounds;if(x)x.sort(m);else{x=[];for(r=0;r<k.length;r++)x.push(r)}for(r=0;r<x.length;r++)if(z=x[r],n=k[z],y=0===z?null:k[z-1],F=z===k.length-1?null:k[z+1],t=u.getDigits(n),t=t.fractional){J=0;for(H=!1;J<=t&&!H;)h=u.getFixedNumbers(n,J),h=Q&&0===r?h[1]:h[0],H=u.hasMinimalChange(n,h,y,F,P),J++;H&&(k[z]=h)}return k},hasMinimalChange:function(f,n,k,
m,y){f=u.getPctChange(f,n,k,m);n=null==f.prev||f.prev<=y;k=null==f.next||f.next<=y;return n&&k||f.prev+f.next<=2*y},_reAllZeros:RegExp("\\"+n.decimal+"0+$","g"),_reSomeZeros:RegExp("(\\d)0*$","g"),format:function(f,n){n=n||{places:20,round:-1};var k=F.format(f,n);k&&(k=k.replace(u._reSomeZeros,"$1").replace(u._reAllZeros,""));return k}};y("extend-esri")&&(f.numberUtils=u);return u})},"dojo/debounce":function(){define([],function(){return function(y,F){var n;return function(){n&&clearTimeout(n);var f=
this,m=arguments;n=setTimeout(function(){y.apply(f,m)},F)}}})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/debounce dojo/has dojo/sniff dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dojo/dom-class dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../numberUtils ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/VectorFieldRenderer ../renderers/HeatmapRenderer ../symbols/PictureFillSymbol ../symbols/SimpleLineSymbol ../symbols/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi".split(" "),function(y,
F,n,f,m,u,B,p,k,da,W,S,t,h,r,J,H,z,P,x,Q,T,U,I,E,K,N,L,X,Y,Z,R,$,aa,ba,O,ca,V){var G=F([ca,H],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,dotDensitySwatchSize:26,dotCoverage:75,gradientHeight:30,transparencyRampColor:new B([64,64,64]),defaultText:"Aa",sizeRampLightColor:new B([255,255,255]),sizeRampDarkColor:new B([128,128,128]),gradientWidth:34,colorRampBorder:"1px solid",_specialChars:{lt:"\x3c",gt:"\x3e"},_ieTimer:100,_isRightToLeft:!1,
_align:null,_legendAlign:null,constructor:function(a,b){n.mixin(this,V.widgets.legend);this._i18n=V.widgets.legend;a=a||{};a.map?b?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0,this._respectVisibility=!1===a.respectVisibility?!1:!0,this.arrangement=a.arrangement===G.ALIGN_RIGHT?G.ALIGN_RIGHT:G.ALIGN_LEFT,this.arrangement===G.ALIGN_RIGHT&&(this.alignRight=!0),this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=[],this.hideLayersInLegend=
{},this.refresh=p(this.refresh,0)):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},postMixInProperties:function(){this.inherited(arguments);var a=["ar","he"],b,c;for(b=0;b<a.length;b+=1)c=a[b],y.locale&&-1!==y.locale.indexOf(c)&&(-1!==y.locale.indexOf("-")?-1!==y.locale.indexOf(c+"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=this.alignRight?"left":
"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},startup:function(){this.inherited(arguments);this._initialize();9>k("ie")&&(this._repaintItems=n.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(a){if(this.domNode){a?(this.layerInfos=
a,this.layers=[],f.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=a.hideLayers,this._addSubLayersToHide(a)):this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=this.layerInfos=
null);for(a=this.domNode.children.length-1;0<=a;a--)h.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){this.layerInfos&&(this.layers=[],f.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=a.hideLayers,this._addSubLayersToHide(a)):
this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var a=[],b=[];f.forEach(this.map.layerIds,function(c){c=this.map.getLayer(c);var d;this._isSupportedLayerType(c)&&(c.arcgisProps&&c.arcgisProps.title&&(c._titleForLegend=c.arcgisProps.title),this.layers.push(c));"esri.layers.KMLLayer"==c.declaredClass&&
(d=c.getLayers(),f.forEach(d,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==c.declaredClass&&(d=c.getFeatureLayers(),f.forEach(d,function(a){b.push(a.id)},this))},this);f.forEach(this.map.graphicsLayerIds,function(c){var d=this.map.getLayer(c);-1==f.indexOf(a,c)&&-1==f.indexOf(b,c)&&(this._isSupportedLayerType(d)&&d._params&&d._params.drawMode)&&(d.arcgisProps&&d.arcgisProps.title&&(d._titleForLegend=d.arcgisProps.title),this.layers.push(d))},this)}this._createLegend()},_activate:function(){this._deactivate();
this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=m.connect(this.map,"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=m.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=m.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=m.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),f.forEach(this.layers,function(a){a.ovcConnect=m.connect(a,"onVisibilityChange",this,"_refreshLayers");a.ovcConnect=
m.connect(a,"onOpacityChange",this,"_refreshLayers");a.oscConnect=m.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(a.odcConnect=m.connect(a,"_onDynamicLayersChange",n.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(a.oirConnect=m.connect(a,"onRenderingChange",n.partial(this._updateImageServiceLayers,this,a)));"esri.layers.ArcGISImageServiceVectorLayer"===
a.declaredClass&&(a.oivrConnect=m.connect(a,"onRendererChange",n.hitch(this,"_refreshLayers")))},this))},_deactivate:function(){this._ozeConnect&&m.disconnect(this._ozeConnect);this._olaConnect&&m.disconnect(this._olaConnect);this._olroConnect&&m.disconnect(this._olroConnect);this._olrConnect&&m.disconnect(this._olrConnect);f.forEach(this.layers,function(a){a.ovcConnect&&m.disconnect(a.ovcConnect);a.oscConnect&&m.disconnect(a.oscConnect);a.odcConnect&&m.disconnect(a.odcConnect);a.oirConnect&&m.disconnect(a.oirConnect);
a.oivrConnect&&m.disconnect(a.oivrConnect)},this)},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},_updateAllMapLayers:function(){this.layers=[];f.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this.layers.push(a)},this);f.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&
(a._params&&a._params.drawMode)&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=!1;r.set(this.domNode,"position","relative");h.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);var b=[];f.forEach(this.layers,function(c){if("esri.layers.KMLLayer"==c.declaredClass||"esri.layers.GeoRSSLayer"==c.declaredClass){var e;c.loaded?("esri.layers.KMLLayer"==c.declaredClass?e=c.getLayers():"esri.layers.GeoRSSLayer"==c.declaredClass&&
(e=c.getFeatureLayers(),this.hideLayersInLegend[c.id]&&(e=f.filter(e,function(a){return-1==f.indexOf(this.hideLayersInLegend[c.id],a.id)},this))),f.forEach(e,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&c._titleForLegend&&(a._titleForLegend=c._titleForLegend+" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_polygons),b.push(a))},
this)):m.connect(c,"onLoad",n.hitch(this,function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===c.declaredClass)if(c.loaded){if((!this._respectVisibility||this._respectVisibility&&c.visible)&&0<c.layerInfos.length&&f.some(c.layerInfos,function(a){return a.legendURL})){var g=!1;f.forEach(c.layerInfos,function(b){b.legendURL&&-1<f.indexOf(c.visibleLayers,b.name)&&(g||(h.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(c._titleForLegend||c.name||c.id)+"\x3c/span\x3e"},
this.domNode),g=!0),h.create("div",{innerHTML:"\x3cimg src\x3d'"+b.legendURL+"'/\x3e"},this.domNode),a=!0)},this)}}else m.connect(c,"onLoad",n.hitch(this,function(){this.refresh(this.layerInfos)}));else b.push(c)},this);var c=[];f.forEach(b,function(a){if(a.loaded){if((!this._respectVisibility||this._respectVisibility&&a.visible)&&(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var b=h.create("div",{id:this.id+"_"+a.id,style:{display:"none"},"class":"esriLegendService"});
h.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},h.create("td",{align:this._align},h.create("tr",{},h.create("tbody",{},h.create("table",{width:"95%"},b)))));h.place(b,this.id,"first");a.legendResponse||a.renderer?this._createLegendForLayer(a):c.push(this._legendRequest(a))}}else var g=m.connect(a,"onLoad",this,function(a){m.disconnect(g);g=null;this.refresh()})},this);0===c.length&&!a?(t.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new W(c)).addCallback(n.hitch(this,
function(b){a?t.byId(this.id+"_msg").innerHTML="":t.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()}))},_createLegendForLayer:function(a){if(a.legendResponse||a.renderer){var b=!1;if(a.legendResponse){var c=a.dynamicLayerInfos||a.layerInfos;c&&c.length?f.forEach(c,function(c,e){if(!this.hideLayersInLegend[a.id]||-1==f.indexOf(this.hideLayersInLegend[a.id],c.id)){var g=this._buildLegendItems(a,c,e);b=b||g}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,
{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(c=a.url?a.url.substring(a.url.lastIndexOf("/")+1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(r.set(t.byId(this.id+"_"+a.id),"display","block"),r.set(t.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);m.connect(a,"onLoad",n.hitch(this,"_legendRequest"))},
_legendRequestServer:function(a){var b=a.url,c=b.indexOf("?"),b=-1<c?b.substring(0,c)+"/legend"+b.substring(c):b+"/legend";(c=a._getToken())&&(b+="?token\x3d"+c);var d=n.hitch(this,"_processLegendResponse"),e={f:"json"};a._params.dynamicLayers&&(e.dynamicLayers=S.stringify(this._createDynamicLayers(a)),"[{}]"===e.dynamicLayers&&(e.dynamicLayers="[]"));a._params.bandIds&&(e.bandIds=a._params.bandIds);a._params.renderingRule?e.renderingRule=a._params.renderingRule:a.rasterFunctionInfos&&0<a.rasterFunctionInfos.length&&
f.forEach(a.rasterFunctionInfos,function(a){a&&(a.name&&"none"===a.name.toLowerCase())&&(e.renderingRule=S.stringify({rasterFunction:a.name}))});return U({url:b,content:e,callbackParamName:"callback",load:function(b,c){d(a,b,c)},error:T.defaults.io.errorHandler})},_legendRequestTools:function(a){var b=a.url.toLowerCase().indexOf("/rest/"),b=a.url.substring(0,b)+a.url.substring(b+5,a.url.length),b=this._legendUrl+"?soapUrl\x3d"+window.escape(b);if(!k("ie")||8<k("ie"))b+="\x26returnbytes\x3dtrue";var c=
n.hitch(this,"_processLegendResponse");return U({url:b,content:{f:"json"},callbackParamName:"callback",load:function(b,e){c(a,b,e)},error:T.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&b.layers?(a.legendResponse=b,t.byId(this.id+"_"+a.id)&&h.empty(t.byId(this.id+"_"+a.id)),h.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},h.create("td",{align:this._align},h.create("tr",{},h.create("tbody",{},h.create("table",{width:"95%"},t.byId(this.id+"_"+
a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+u.toJson(b))},_buildLegendItems:function(a,b,c){var d=!1,e=t.byId(this.id+"_"+a.id),g=b.parentLayerId;if(b.subLayerIds)a=h.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:{display:"none"},"class":-1==g?0<c?"esriLegendGroupLayer":"":this._legendAlign},-1==g?e:t.byId(this.id+"_"+a.id+"_"+g+"_group")),h.create("td",{innerHTML:x.encode(b.name),align:this._align},h.create("tr",{},h.create("tbody",
{},h.create("table",{width:"95%","class":"esriLegendLayerLabel"},a))));else{if(this._respectVisibility&&a.visibleLayers&&-1==(","+a.visibleLayers+",").indexOf(","+b.id+","))return d;c=h.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:{display:"none"},"class":-1<g?this._legendAlign:""},-1==g?e:t.byId(this.id+"_"+a.id+"_"+g+"_group"));h.create("td",{innerHTML:x.encode(b.name)||"",align:this._align},h.create("tr",{},h.create("tbody",{},h.create("table",{width:"95%","class":"esriLegendLayerLabel"},c))));
a.legendResponse?d=d||this._buildLegendItems_Tools(a,b,c):a.renderer&&(d=d||this._buildLegendItems_Renderer(a,b,c))}return d},_buildLegendItems_Tools:function(a,b,c){var d=b.parentLayerId,e=this.map.getScale(),g=!1,q=function(a,b){var c,d;for(c=0;c<a.length;c++)if(b.dynamicLayerInfos)for(d=0;d<b.dynamicLayerInfos[d].length;d++){if(b.dynamicLayerInfos[d].mapLayerId==a[c].layerId)return a[c]}else if(b.id==a[c].layerId)return a[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&
this._isLayerInScale(a,b,e)){var v=!0;if(this._respectCurrentMapScale&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISMapServiceLayer"===a.declaredClass)){var w=this._getEffectiveScale(a,b);if(w.minScale&&w.minScale<e||w.maxScale&&w.maxScale>e)v=!1}if(v){var e=q(a.legendResponse.layers,b),s=e.legendType,l=e.layerType,k=e.legend;if(k){"esri.layers.ArcGISImageServiceLayer"!==a.declaredClass&&this._sanitizeLegendResponse(a,e,b);c=h.create("table",{cellpadding:0,cellspacing:0,
width:"95%","class":"esriLegendLayer"},c);var n=h.create("tbody",{},c);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b);f.forEach(k,function(c){if(!(10.1<=a.version&&!c.values&&1<k.length&&(a._hideDefaultSymbol||"\x3call other values\x3e"===c.label||!c.label&&!("esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.3<=a.version||"Raster Layer"===l))))if(c.url&&0===c.url.indexOf("http")||c.imageData&&0<c.imageData.length)g=!0,this._buildRow_Tools(c,n,a,b.id,s)},this)}}}g&&(r.set(t.byId(this.id+
"_"+a.id+"_"+b.id),"display","block"),-1<d&&(r.set(t.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,a,d)));return g},_sanitizeLegendResponse:function(a,b,c){var d=b.legend;if(10.1<=a.version&&1<d.length&&!b._sanitized){a=n.getObject("layerDefinition.drawingInfo.renderer",!1,c);var e,g;a||(a=n.getObject("drawingInfo.renderer",!1,c));f.some(d,function(a){if(a.values)return!0})&&f.some(d,function(a,b){a.values||(g=b,e=a);return!!e});a?"uniqueValue"===a.type?e&&(d.splice(g,
1),d.push(e)):"classBreaks"===a.type&&(e&&d.splice(g,1),d.reverse(),e&&d.push(e)):e&&(d.splice(g,1),d.push(e));b._sanitized=!0}},_buildRow_Tools:function(a,b,c,d,e){var g=h.create("tr",{},b),q;this.alignRight?(b=h.create("td",{align:this._isRightToLeft?"left":"right"},g),q=h.create("td",{align:this._isRightToLeft?"left":"right",width:35},g)):(q=h.create("td",{width:35,align:"center"},g),b=h.create("td",{},g));g=a.url;(!k("ie")||9<=k("ie")||9>k("ie")&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass)&&
a.imageData&&0<a.imageData.length?g="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(g=c.url+"/"+d+"/images/"+a.url,(d=c._getToken())&&(g+="?token\x3d"+d));d=h.create("img",{src:g,border:0,style:"opacity:"+c.opacity},q);a=h.create("td",{innerHTML:x.encode(a.label),align:this._align},h.create("tr",{},h.create("tbody",{},h.create("table",{width:"95%",dir:"ltr"},b))));e&&("Stretched"===e&&10.3<=c.version&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass)&&(a.style.verticalAlign=
"top",a.style.lineHeight="1",d.style.marginBottom="-1px",d.style.display="block",b.style.verticalAlign="top");9>k("ie")&&(d.style.filter="alpha(opacity\x3d"+100*c.opacity+")")},_getVariable:function(a,b,c){var d;a&&(d=(a=a.getVisualVariablesForType(b,c))&&a[0]);return d},_getVariables:function(a,b,c){a=[this._getVariable(a,"colorInfo",!1),this._getVariable(a,"opacityInfo",!1),this._getVariable(a,"sizeInfo",!1)];return b?f.filter(a,function(a){return!(!a||!(a.field===b&&a.normalizationField==c))}):
a},_getFieldAlias:function(a,b){var c=b.infoTemplate,c=c&&c.getFieldInfo&&c.getFieldInfo(a),d=n.isFunction(a)?null:b.getField(a),e=c||d,g="";e&&(g=c&&c.label||d&&d.alias||e.name||e.fieldName);return g},_getRampTitle:function(a,b){var c,d=a.field,e=a.normalizationField,g=!1,q=!1,v=!1,h,d=n.isFunction(d)?null:d,e=n.isFunction(e)?null:e;if(a.legendOptions&&a.legendOptions.title)c=a.legendOptions.title;else{if(b.renderer.authoringInfo&&b.renderer.authoringInfo.visualVariables){var f=b.renderer.authoringInfo.visualVariables;
for(h=0;h<f.length;h++){var l=f[h];if("colorInfo"===l.type&&"ratio"===l.style){g=!0;break}else if("colorInfo"===l.type&&"percent"===l.style){q=!0;break}else if("colorInfo"===l.type&&"percentTotal"===l.style){v=!0;break}}}(g=v&&"showRatioPercentTotal"||q&&"showRatioPercent"||g&&"showRatio"||e&&"showNormField"||d&&"showField"||null)&&(c=I.substitute({field:d&&this._getFieldAlias(d,b),normField:e&&this._getFieldAlias(e,b)},this._i18n[g]))}return c},_getRendererTitle:function(a,b){var c;if(a){var d,e,
g;a instanceof L&&(d=a.attributeField,e=a.normalizationField,g="percent-of-total"===a.normalizationType);d=n.isFunction(d)?null:d;(g=(e=n.isFunction(e)?null:e)&&"showNormField"||(g?"showNormPct":null)||d&&"showField"||null)&&(c=I.substitute({field:d&&this._getFieldAlias(d,b),normField:e&&this._getFieldAlias(e,b)},this._i18n[g]))}return c},_buildLegendItems_Renderer:function(a,b,c){var d=b.parentLayerId,e=this.map,g=e.getScale(),q,v=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,g)){var w,
s,l="esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass?a.renderer.renderer:a.renderer,k,C,p,m,u;if(l instanceof X&&(l=(l="zoom"===l.rangeType?l.getRendererInfoByZoom(e.getZoom()):l.getRendererInfoByScale(g))&&l.renderer,!l))return!1;var A=this._getVariables(l),y=f.filter(A,function(a){return!!a}).length,g=A[0],e=A[1],A=A[2],M,D;g&&(k=this._getMedianColor(l,g),g.field&&(p=n.isFunction(g.field)?null:a.getField(g.field)));e&&e.field&&(u=n.isFunction(e.field)?null:a.getField(e.field));A&&A.field&&
(m=n.isFunction(A.field)?null:a.getField(A.field));if(l instanceof $)q=v=!0,this._showHeatRamp(a,b,l,c);else if(l instanceof Y)q=v=!0,this._showDotDensityLegend(a,b,l,c);else if(l instanceof Z)q=v=!0,s=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),w=h.create("tbody",{},s),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(s,a,b),l.latestObservationRenderer&&l.latestObservationRenderer instanceof K&&this._buildRow_Renderer(a,l.latestObservationRenderer.symbol,
k,x.encode(l.latestObservationRenderer.label)||this.NLS_currentObservations,null,w),l.observationRenderer&&l.observationRenderer instanceof K&&this._buildRow_Renderer(a,l.observationRenderer.symbol,k,x.encode(l.observationRenderer.label)||this.NLS_previousObservations,null,w);else if(l instanceof N){if(l.infos&&0<l.infos.length){q=v=!0;s=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);w=h.create("tbody",{},s);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(s,
a,b);l.attributeField&&A&&this._addSubHeader(w,this._getFieldAlias(l.attributeField,a));var z=[];f.forEach(l.infos,function(b){var c=null;a._editable&&a.types&&(c=this._getTemplateFromTypes(a.types,b.value));var d=b.label;null==d&&(d=b.value);-1===f.indexOf(z,d)&&(z.push(d),this._buildRow_Renderer(a,b.symbol,k,x.encode(d),c,w))},this)}D=this._displayDefaultSymbol(a,l,c)}else if(l instanceof L){if(l.infos&&0<l.infos.length||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass){q=v=!0;M=this._isUnclassedRenderer(l);
!g&&1===l.infos.length&&(C=(C=l.infos[0])&&C.symbol);M||(s=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),w=h.create("tbody",{},s),y=this._getRendererTitle(l,a),this._buildRow_Renderer(a,null,k,x.encode(y),null,w));s=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);w=h.create("tbody",{},s);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(s,a,b);if(!M||!A)y=l.infos.slice(0).reverse(),f.forEach(y,function(b){var c=
b.label;null==c&&!M&&(c=b.minValue+" - "+b.maxValue);this._buildRow_Renderer(a,b.symbol,k,x.encode(c),null,w)},this);if("esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(a.renderer.style===R.STYLE_SCALAR||a.renderer.style===R.STYLE_SINGLE_ARROW))this._buildRow_Renderer(a,l.defaultSymbol,null,"",null,w),a._hideDefaultSymbol=!0}M||(D=this._displayDefaultSymbol(a,l,c))}else l instanceof K&&(q=v=!0,s=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),
w=h.create("tbody",{},s),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(s,a,b),C=null,a._editable&&(a.templates&&0<a.templates.length)&&(C=a.templates[0]),s=1<y?null:p||u||m,this._buildRow_Renderer(a,l.symbol,k,x.encode(s?this._getRampTitle(1<y?null:g||e||A,a):l.label),C,w),C=g?null:l.symbol,s&&(p=u=m=null));if(q){if(g&&(g.field||g.valueExpression))this._showGradientRamp(a,b,l,null,c,g,p,null,A?!0:!1);if(A&&(A.field||A.valueExpression))q=g||l instanceof N?!1:!0,this._showSizeLegend(a,b,
l,A,k,c,m,null,q);if(e&&(e.field||e.valueExpression))m=C&&!C.url&&C.color?C.color:this.transparencyRampColor,this._showGradientRamp(a,b,l,m,c,e,u,null,!1)}D||(D=this._displayDefaultSymbol(a,l,c));v=v||D}v&&(r.set(t.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<d&&(r.set(t.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,d)));return v},_isUnclassedRenderer:function(a,b){var c;if(a instanceof L&&a.infos&&1===a.infos.length){c=a.attributeField;var d=a.normalizationField;
c=b?c===b:!!this._getVariables(a,c,d).length}return c},_displayDefaultSymbol:function(a,b,c){var d;!a._hideDefaultSymbol&&b.defaultSymbol&&(d=!0,c=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),c=h.create("tbody",{},c),this._buildRow_Renderer(a,b.defaultSymbol,null,x.encode(b.defaultLabel)||"others",null,c));return d},_showGradientRamp:function(a,b,c,d,e,g,q,v,f){f=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(!f?" esriLegendSubFragment":
"")},e);e=h.create("tbody",{},f);(a._hoverLabel||a._hoverLabels||v)&&this._createHoverAction(f,a,b,v);(q||g.valueExpression)&&this._addSubHeader(e,this._getRampTitle(g,a));(b=this._getRampStops(c,g,d))&&b.length&&this._drawGradientRamp(e,b,!0,a,this._getRampBorderColor(c),!!d)},_getMedianColor:function(a,b){var c,d;b.colors?(c=b.minDataValue,d=b.maxDataValue):b.stops&&(c=b.stops[0].value,d=b.stops[b.stops.length-1].value);return a.getColor(c+(d-c)/2,{colorInfo:b})},_getRampStops:function(a,b,c){var d,
e,g,q,h=!1;b.colors||b.opacityValues?(e=b.maxDataValue-b.minDataValue,d=f.map([0,0.25,0.5,0.75,1],function(a){g=b.minDataValue+a*e;return Number(g.toFixed(6))}),this._checkPrecision(0,4,d)):b.stops&&(d=f.map(b.stops,function(a){return a.value}),(h=f.some(b.stops,function(a){return!!a.label}))&&(q=f.map(b.stops,function(a){return a.label})));var w=d[0],k,l,n;e=d[d.length-1]-w;return f.map(d,function(g,f){c?(k=new B(c.toRgba()),l=a.getOpacity(g,{opacityInfo:b}),null!=l&&(k.a=l)):k=a.getColor(g,{colorInfo:b});
n="";0===f?n=this._specialChars.lt+" ":f===d.length-1&&(n=this._specialChars.gt+" ");return{value:g,color:k,offset:1-(g-w)/e,label:h?q[f]:n+E.format(g)}},this).reverse()},_checkPrecision:function(a,b,c){var d=a+(b-a)/2,e=c[a],g=c[d],q=c[b],h=Math.floor(e),f=Math.floor(g),k=Math.floor(q);h===e&&(k===q&&f!==g&&h!==f&&k!==f)&&(c[d]=f);a+1!==d&&this._checkPrecision(a,d,c);d+1!==b&&this._checkPrecision(d,b,c)},_getRampBorderColor:function(a){var b;if(a instanceof K)b=a.symbol;else if(a instanceof N||a instanceof
L)b=a.infos[0].symbol;return(a=b&&-1===b.type.indexOf("linesymbol")?b.getStroke():null)&&a.color},_drawGradientRamp:function(a,b,c,d,e,g){var q=h.create("tr",{},a),v,w,s,l,n,p=b.length-1,m;l=0;this.alignRight?(a=h.create("td",{align:this._isRightToLeft?"left":"right"},q),v=h.create("td",{align:this._isRightToLeft?"left":"right",width:this.gradientWidth},q)):(v=h.create("td",{width:this.gradientWidth,align:"center"},q),a=h.create("td",{},q));q=e&&0<e.a&&!(240<=e.r&&240<=e.g&&240<=e.b);w=h.create("div",
{"class":q?"":"esriLegendBorderLessColorRamp",style:"position: relative; width:"+this.gradientWidth+"px;"},v);v=h.create("div",{"class":"esriLegendColorRamp"+(g?" esriLegendTransparencyRamp":"")},w);g=r.get(v,"width");q&&(e=9>k("ie")?e.toHex():"rgba("+e.toRgba().join(",")+")",r.set(v,"border",this.colorRampBorder+" "+e));c?(e=this.gradientHeight*p,r.set(v,"height",e+"px")):e=r.get(v,"height");r.set(w,"height",e+"px");q=z.createSurface(v,g,e);9>k("ie")&&(l=q.getEventSource(),r.set(l,"position","relative"),
r.set(l.parentNode,"position","relative"),l=1);try{c&&f.forEach(b,function(a,b){a.offset=b/p}),n=q.createRect({x:-l,y:-l,width:g+l,height:e+l}),n.setFill({type:"linear",x1:0,y1:0,x2:0,y2:e,colors:b}).setStroke(null),q.createRect({width:g,height:e}).setFill(new B([255,255,255,1-d.opacity])).setStroke(null),this._surfaceItems.push(q)}catch(t){q.clear(),q.destroy()}f.forEach(b,function(a,c){if(a.label){m="top:"+100*a.offset+"%;";var d="";0===c&&(d+=" esriLegendColorRampTickFirst");c===b.length-1&&(d+=
" esriLegendColorRampTickLast");h.create("div",{"class":"esriLegendColorRampTick"+d,innerHTML:"\x26nbsp;",style:m},w)}});s=h.create("div",{"class":"esriLegendColorRampLabels",style:{height:e+this.gradientHeight+"px"}},a);c?f.forEach(b,function(a){h.create("div",{"class":"esriLegendColorRampLabel",innerHTML:x.encode(a.label)||"\x26nbsp;"},s)}):(h.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.high},s),h.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.low,
style:"top: "+(e+this.gradientHeight-2*this.gradientHeight)+"px;"},s))},_showHeatRamp:function(a,b,c,d,e){var g,q=c.field;g=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);d=h.create("tbody",{},g);(a._hoverLabel||a._hoverLabels||e)&&this._createHoverAction(g,a,b,e);(q=q&&a.getField(q))&&this._addSubHeader(d,this._getFieldAlias(q.name,a));b=this._getHeatmapStops(c);b.length&&this._drawGradientRamp(d,b,!1,a)},_getHeatmapStops:function(a){var b=a.colorStops;a=
a.colors;var c,d,e,g;if(b&&b[0])if(c=b.length-1,a=b[0]&&null!=b[0].ratio){if((a=b[c])&&1!==a.ratio)b=b.slice(0),b.push({ratio:1,color:a.color}),c++}else d=b[0].value,e=b[c].value-d,b=f.map(b,function(a){return{color:a.color,ratio:(a.value-d)/e}});else a&&a[0]&&(c=a.length-1,g=1/(a.length-1),b=f.map(a,function(a,b){return{color:a,ratio:b*g}}));b=f.map(b,function(a,b){var d="";0===b?d="Low":b===c&&(d="High");return{color:a.color,label:d,offset:1-a.ratio}});return b.reverse()},_showDotDensityLegend:function(a,
b,c,d){var e=c.legendOptions,g,q,k,w,s,l,p,m=this.dotDensitySwatchSize,r=Math.round(m/2);e&&(q=e.backgroundColor,k=e.outline,w=e.valueUnit,s=e.dotCoverage);s=(s||this.dotCoverage)/100;p=Math.round(m*m/Math.pow(c.dotSize,2)*s);d=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);l=h.create("tbody",{},d);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(d,a,b);this._addSubHeader(l,I.substitute({value:c.dotValue,unit:w||""},this.NLS_dotValue));f.forEach(c.fields,
function(b){b=n.mixin({},b);b.numPoints=p;g=new aa(c._generateImageSrc(m,m,[b],{x:0,y:0},{x:m,y:m},q),k||c.outline,m,m);b=a.getField(b.name)||b;this._buildRow_Renderer(a,g,null,x.encode(this._getFieldAlias(b.name,a)),null,l,{type:"path",path:"M "+-r+","+-r+" L "+r+","+-r+" L "+r+","+r+" L "+-r+","+r+" L "+-r+","+-r+" E"})},this)},_showSizeLegend:function(a,b,c,d,e,g,q,f,k){var s=d.legendOptions,s=s&&s.customValues;e=this._getSizeSymbol(c,e);if(!(d.valueUnit&&"unknown"!==d.valueUnit||!e||!s&&(null==
d.minSize||null==d.maxSize))){k=h.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(!k?" esriLegendSubFragment":"")},g);g=h.create("tbody",{},k);(a._hoverLabel||a._hoverLabels||f)&&this._createHoverAction(k,a,b,f);(q||d.valueExpression)&&this._addSubHeader(g,this._getRampTitle(d,a));b=s||this._getDataValues(c,e,d);for(q=k=b.length-1;0<=q;q--)f=b[q],e=O.fromJson(e.toJson()),this._applySize(e,c,d,f),f=E.format(f),s="",q===k?s=this._specialChars.gt+" ":0===q&&(s=this._specialChars.lt+
" "),s="\x3cspan class\x3d'esriLegendSizeRampLabel'\x3e"+x.encode(s+f)+"\x3c/span\x3e",this._buildRow_Renderer(a,e,null,s,null,g)}},_getSizeSymbol:function(a,b){var c,d;if(a instanceof K)c=a.symbol;else if(a instanceof R)c=a.defaultSymbol;else if(a instanceof N||a instanceof L)c=a.infos[0].symbol,d=1<a.infos.length;if(c=c&&-1!==c.type.indexOf("fillsymbol")?null:c)if(c=O.fromJson(c.toJson()),b||d)-1!==c.type.indexOf("linesymbol")?c.setColor(new B(this.sizeRampDarkColor)):(c.setColor(new B(this.sizeRampLightColor)),
c.setOutline&&(d=new ba,d.setColor(new B(this.sizeRampDarkColor)),d.setWidth(1.5),c.setOutline(d)));return c},_getDataValues:function(a,b,c,d,e){d=null==d?5:d;e=null==e?20:e;var g=a.getSizeRangeAtScale(c,this.map.getScale());d=this._interpolateSizeRange(g,d);var h=f.map(d,function(a){return this._getDataValueFromSize(a,c,g)},this),k,n,h=E.round(h);for(k=1;k<h.length-1;k++)if(n=this._roundDataValue(a,b,c,h[k],h[k-1],e))h[k]=n[0],d[k]=n[1];return h},_interpolateSizeRange:function(a,b){var c=a.minSize,
d=(a.maxSize-c)/(b-1),e,g=[];for(e=0;e<b;e++)g.push(c+d*e);return g},_getDataValueFromSize:function(a,b,c){var d=c.minSize;c=c.maxSize;var e=b.minDataValue;b=b.maxDataValue;return a=a<=d?e:a>=c?b:(a-d)/(c-d)*(b-e)+e},_roundDataValue:function(a,b,c,d,e,g){var h=this._getSize(b,a,c,d);e=this._getSize(b,a,c,e);var f,k=E.getDigits(d),n=k.integer,k=k.fractional,l,m,p,r,t,u,x,y,z,D,B;0<d&&1>d&&(f=Math.pow(10,k),d*=f,n=E.getDigits(d).integer);for(n-=1;0<=n&&!(l=Math.pow(10,n),k=Math.floor(d/l)*l,l*=Math.ceil(d/
l),null!=f&&(k/=f,l/=f),m=(k+l)/2,m=E.round([k,m,l],{indexes:[1]})[1],p=this._getSize(b,a,c,k),r=this._getSize(b,a,c,l),t=this._getSize(b,a,c,m),u=E.getPctChange(h,p,e,null),x=E.getPctChange(h,r,e,null),y=E.getPctChange(h,t,e,null),z=u.prev<=g,D=x.prev<=g,z&&D&&(u.prev<=x.prev?(z=!0,D=!1):(D=!0,z=!1)),z?B=[k,p]:D?B=[l,r]:y.prev<=g&&(B=[m,t]),B);n--);return B},_applySize:function(a,b,c,d){var e=a.type;b=this._getSize(a,b,c,d);switch(e){case "simplemarkersymbol":a.setSize(b);break;case "picturemarkersymbol":e=
a.width;c=a.height;a.setHeight(b);a.setWidth(b*(e/c));break;case "simplelinesymbol":case "cartographiclinesymbol":a.setWidth(b);break;case "textsymbol":a.font&&a.font.setSize(b)}},_getSize:function(a,b,c,d){return b.getSize(d,{sizeInfo:c,scale:this.map.getScale(),shape:-1!==a.type.indexOf("markersymbol")?a.style:null})},_buildRow_Renderer:function(a,b,c,d,e,g,k){var f=h.create("tr",{},g),n;this.alignRight?(g=h.create("td",{align:this._isRightToLeft?"left":"right"},f),b&&(n=h.create("td",{align:this._isRightToLeft?
"left":"right",width:35},f))):(b&&(n=h.create("td",{width:35,align:"center"},f)),g=h.create("td",{},f));var m=f=30,l;if(b){if("simplemarkersymbol"==b.type)f=Math.min(Math.max(f,b.size+12),125),m=Math.min(Math.max(m,b.size+12),125);else if("picturemarkersymbol"==b.type)f=Math.min(Math.max(f,b.width),125),m=Math.min(b.height||m,125);else if("textsymbol"==b.type){var p,r;b.text||(p=b.text,r=!0,b.setText(this.defaultText));f=Math.min(Math.max(f,b.getWidth()+12),125);m=Math.min(Math.max(m,b.getHeight()+
12),125);r&&b.setText(p)}l=h.create("div",{style:"width:"+f+"px;height:"+m+"px;"},n)}I.isDefined(d)&&"number"===typeof d&&(d=""+d);h.create("td",{innerHTML:d||"",align:this._align},h.create("tr",{},h.create("tbody",{},h.create("table",{width:"95%"},g))));b&&(a=this._drawSymbol(l,b,c,f,m,e,a,k),this._surfaceItems.push(a))},_addSubHeader:function(a,b){var c=h.create("tr",{},a),c=h.create("td",{align:this._align,colspan:2},c);h.create("td",{innerHTML:x.encode(b)||"",align:this._align},h.create("tr",
{},h.create("tbody",{},h.create("table",{width:"95%"},c))))},_drawSymbol:function(a,b,c,d,e,g,f,h){b=O.fromJson(b.toJson());var m=f.opacity;c&&b.setColor(new B(c.toRgba()));if("simplelinesymbol"===b.type||"cartographiclinesymbol"===b.type||"textsymbol"===b.type){if(!b.color)return;c=b.color.toRgba();c[3]*=m;b.color.setColor(c)}else"simplemarkersymbol"===b.type||"simplefillsymbol"===b.type?(b.color&&(c=b.color.toRgba(),c[3]*=m,b.color.setColor(c)),b.outline&&b.outline.color&&(c=b.outline.color.toRgba(),
c[3]*=m,b.outline.color.setColor(c))):"picturemarkersymbol"===b.type&&(a.style.opacity=m,a.style.filter="alpha(opacity\x3d("+100*m+"))");a=z.createSurface(a,d,e);9>k("ie")&&(c=a.getEventSource(),r.set(c,"position","relative"),r.set(c.parentNode,"position","relative"));g=this._getDrawingToolShape(b,g)||O.getShapeDescriptors(b);var p,m=(c=g.defaultShape)&&"text"===c.type;try{m&&!c.text&&(c.text=this.defaultText),p=a.createShape(h||c).setFill(g.fill).setStroke(g.stroke),m&&p.setFont(g.font)}catch(l){a.clear();
a.destroy();return}var t=p.getBoundingBox();h=t.width;g=t.height;var m=-(t.x+h/2),u=-(t.y+g/2);c=a.getDimensions();m={dx:m+c.width/2,dy:u+c.height/2};if("simplemarkersymbol"===b.type&&"path"===b.style)d=f._getScaleMatrix(t,b.size),p.applyTransform(P.scaleAt(d.xx,d.yy,{x:c.width/2,y:c.height/2}));else if(h>d||g>e)f=h/d>g/e,d=((f?d:e)-5)/(f?h:g),n.mixin(m,{xx:d,yy:d});p.applyTransform(m);return a},_getDrawingToolShape:function(a,b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c=
{type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 E"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 E"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 E"};break;case "esriFeatureEditToolCircle":c={type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),
stroke:a.getStroke()}},_repaintItems:function(){f.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&n.isArray(a.children)&&f.forEach(a.children,this._repaint,this)}},_createHoverAction:function(a,b,c,d){if(d=b._hoverLabel||b._hoverLabels&&b._hoverLabels[c.id]||d)d=x.encode(d),b.mouseMoveHandler=b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=
m.connect(a,"onmousemove",n.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,r.set(t.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(n.hitch(this,function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=!0,t.byId(this.id+"_hoverLabel")){var d=t.byId(this.id+"_hoverLabel");d.innerHTML="\x3cspan\x3e"+c+"\x3c/span\x3e";r.set(d,"top",b+"px");r.set(d,"left",a+15+"px");r.set(d,"display",
"")}else h.create("div",{innerHTML:"\x3cspan\x3e"+c+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},d)),b.mouseOutHandler=b.mouseOutHandler||{},b.mouseOutHandler[c.id]=m.connect(a,"onmouseout",n.hitch(this,function(a){this.mouseY=this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,r.set(t.byId(this.id+"_hoverLabel"),"display","none"))}))},_removeHoverHandlers:function(){var a;f.forEach(this.layers,
function(b){if(b.mouseMoveHandler)for(a in b.mouseMoveHandler)m.disconnect(b.mouseMoveHandler[a]);if(b.mouseOutHandler)for(a in b.mouseOutHandler)m.disconnect(b.mouseOutHandler[a])})},_createDynamicLayers:function(a){var b=[],c;f.forEach(a.dynamicLayerInfos||a.layerInfos,function(d){c={id:d.id};c.source=d.source&&d.source.toJson();var e;a.layerDefinitions&&a.layerDefinitions[d.id]&&(e=a.layerDefinitions[d.id]);e&&(c.definitionExpression=e);var g;a.layerDrawingOptions&&a.layerDrawingOptions[d.id]&&
(g=a.layerDrawingOptions[d.id]);g&&(c.drawingInfo=g.toJson());c.minScale=d.minScale||0;c.maxScale=d.maxScale||0;b.push(c)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var d,e=b.dynamicLayerInfos||b.layerInfos;for(d=0;d<e.length;d++)if(c==e[d].id){-1<e[d].parentLayerId&&(r.set(t.byId(this.id+"_"+a+"_"+e[d].parentLayerId+"_group"),"display","block"),
this._findParentGroup(a,b,e[d].parentLayerId));break}},_addSubLayersToHide:function(a){function b(c,d){var e=a.layer.dynamicLayerInfos||a.layer.layerInfos,g,h;for(g=0;g<e.length;g++)if(e[g].id===c&&e[g].subLayerIds)for(h=0;h<e[g].subLayerIds.length;h++){var k=e[g].subLayerIds[h];-1===f.indexOf(d,k)&&(d.push(k),b(k,d))}}a.layer.layerInfos&&f.forEach(this.hideLayersInLegend[a.layer.id],function(c){b(c,this.hideLayersInLegend[a.layer.id])},this)},_isLayerInScale:function(a,b,c){var d,e=!0;if(a.legendResponse&&
a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var g=a.legendResponse.layers[d];if(b.id==g.layerId){var f,h;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==g.minScale&&a.tileInfo&&(f=a.tileInfo.lods[0].scale),0==g.maxScale&&a.tileInfo&&(h=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(f=Math.min(a.minScale,g.minScale)||a.minScale||g.minScale,h=Math.max(a.maxScale,g.maxScale));if(0<f&&f<c||h>c)e=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<
c||a.maxScale&&a.maxScale>c)e=!1;return e},_getServiceTitle:function(a){var b=a._titleForLegend;b||((b=a.url)?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):
b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&a.vectorFieldPixelFilter&&(a=a.vectorFieldPixelFilter.outputUnit?this["NLS_"+a.vectorFieldPixelFilter.outputUnit]:this["NLS_"+a.vectorFieldPixelFilter.inputUnit],I.isDefined(a)&&(b+=" ("+a+")"));return x.encode(b)},_getEffectiveScale:function(a,b){var c=b.minScale,d=b.maxScale;if(I.isDefined(b.parentLayerId)){var e=a.layerInfos,g=b.parentLayerId,f;for(f=e.length-1;0<=f;f--)if(e[f].id==
g)if(0==c&&0<e[f].minScale?c=e[f].minScale:0<c&&0==e[f].minScale||0<c&&0<e[f].minScale&&(c=Math.min(c,e[f].minScale)),d=Math.max(d||0,e[f].maxScale||0),-1<e[f].parentLayerId)g=e[f].parentLayerId;else break}return{minScale:c,maxScale:d}},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===
a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1}});n.mixin(G,{ALIGN_LEFT:0,ALIGN_RIGHT:1});k("extend-esri")&&n.setObject("dijit.Legend",G,Q);return G});