// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../core/declare ../../../core/Accessoire ../../../core/Evented ../../../core/watchUtils ../../../core/HandleRegistry ../../../geometry/Point ../../../geometry/support/webMercatorUtils ../../../geometry/SpatialReference ../support/sunUtils ../support/earthUtils ./EnvironmentRenderer".split(" "),function(f,q,r,g,s,h,t,k,l,m,u){var e=new Date,n={hours:0,minutes:0,seconds:0},p=[0.5773502691896258,-0.5773502691896258,0.5773502691896258];f=f([q,r],{declaredClass:"esri.views.3d.environment.SceneViewEnvironmentManager",
referencePointUpdateInterval:3E3,referencePointUpdateDistThreshold:1E6,classMetadata:{properties:{updating:{dependsOn:["noReferencePositionQueries"],readOnly:!0,getter:function(){return!this.noReferencePositionQueries&&(!!this._referencePosUpdateQuery||null!=this._referencePosUpdateTimer)}},noReferencePositionQueries:{},view:{}}},constructor:function(){this._viewHandles=new s;this._environmentRenderer=null;this._viewConnected=this._trackingEnabled=this._preserveAbsoluteDateTime=!1;this._referencePosResetPreserveAbsoluteTime=
null;this._resetReferencePosition()},destroy:function(){this._viewHandles.destroy();this.disposeRendering()},disposeRendering:function(){this._environmentRenderer&&(this._environmentRenderer.destroy(),this._environmentRenderer=null);this._resetReferencePosition()},updateReadyChange:function(a){a&&!this._viewConnected?(this._viewConnected=!0,this.connectView(this.view)):!a&&this._viewConnected&&(this._viewConnected=!1,this.disconnectView(this.view))},connectView:function(a){this._environmentRenderer=
new u({view:a});this._viewHandles.add([g.on(this.view,"environment.lighting","date-will-change",this._lightingDateHandler.bind(this)),this.view.watch("interacting,stationary",this._interactingStationaryHandler.bind(this)),this.view.watch("environment.lighting.directShadowsEnabled,environment.lighting.ambientOcclusionEnabled",this._updateRenderParamsHandler.bind(this)),this.view.watch("spatialReference",this._spatialReferenceHandler.bind(this)),g.init(this.view,"viewingMode",this._viewingModeHandler.bind(this)),
g.init(this.view,"environment.lighting.cameraTrackingEnabled",this._updateCameraTracking.bind(this)),this.watch("noReferencePositionQueries",this._cameraHandler.bind(this,null))]);this._updateRenderParamsHandler();this._updateLightParams();this._cameraHandler()},_updateCameraTracking:function(a){if(this._trackingEnabled=a)a=g.on(this,"view.navigation","currentViewChanged",this._cameraHandler.bind(this,null),this._cameraHandler.bind(this,null)),this._viewHandles.add(a,"camera");else{if(a=this.get("view.environment.lighting"))a.positionTimezoneInfo.autoUpdated=
!1;this._viewHandles.remove("camera")}},disconnectView:function(a){this.disposeRendering();this._viewHandles.removeAll()},_lightingDateHandler:function(a){if(a=a.date){var c=this.view.environment.lighting;if(!c.positionTimezoneInfo.autoUpdated){this._preserveAbsoluteDateTime=!0;if("local"===this.view.viewingMode){var b=this.view.camera.position;if(!this._referencePosMapCoords||!this._referencePosMapCoords.equals(b)){this._requestReferencePositionUpdate(b);return}}this._preupdateTracking(a);this._referencePosWGS84&&
(b=m.positionToTimezone(this._referencePosWGS84,n),c.autoUpdate(null,b))}this._updateLightParams(a)}},_preupdateTracking:function(a){!this._trackingEnabled&&this.get("view.environment.lighting.cameraTrackingEnabled")&&this._cameraHandler(a)},_cameraHandler:function(a){var c=this.view.camera;c&&("global"===this.view.viewingMode?this._cameraHandlerGlobal(c,a):this._cameraHandlerLocal(c,a))},_cameraHandlerGlobal:function(a,c){var b=a.position;this._referencePosWGS84||(this._referencePosWGS84=new h({spatialReference:k.WGS84}));
b.spatialReference.isWebMercator?t.webMercatorToGeographic(b,!1,this._referencePosWGS84):(this._referencePosWGS84.x=b.x,this._referencePosWGS84.y=b.y);this._referencePosWGS84.z=b.z;this._autoUpdateTimezone(b,c)||this._updateLightParams(c)},_cameraHandlerLocal:function(a,c){var b=a.position;(!this._referencePosMapCoords||this._exceedsReferencePosDistThreshold(b))&&this._requestReferencePositionUpdate(b,!0)},_interactingStationaryHandler:function(){!this.view.interacting&&this.view.stationary&&this._executePendingReferencePositionUpdate()},
_updateLightParams:function(a){var c=this.view.environment.lighting;a=a||c.date;var c=this.view._stage,b;this._referencePosWGS84?(b=l.computeColorAndIntensity(a,this._referencePosWGS84),l.computeDirection(a,this._referencePosWGS84,this.view.viewingMode,b.diffuse.direction)):b={diffuse:{color:[1,1,1],intensity:0.5,direction:p},ambient:{color:[1,1,1],intensity:0.5}};c.setDirectionalLight(b.diffuse);c.setAmbientLight(b.ambient)},_autoUpdateTimezone:function(a,c){if(!this.view.get("environment.lighting.cameraTrackingEnabled"))return!1;
e.setTime((c||this.view.environment.lighting.date).getTime());var b=m.positionToTimezone(a,n),d=this.view.environment.lighting.positionTimezoneInfo;if(d.autoUpdated){if(d.hours===b.hours&&d.minutes===b.minutes&&d.seconds===b.seconds)return!1}else d.hours=b.hours,d.minutes=b.minutes,d.seconds=b.seconds;var f=e.getUTCHours()-(b.hours-d.hours),g=e.getUTCMinutes()-(b.minutes-d.minutes),d=e.getUTCSeconds()-(b.seconds-d.seconds);e.setUTCHours(f);e.setUTCMinutes(g);e.setUTCSeconds(d);return c?!1:this.view.environment.lighting.autoUpdate(e,
b)},_updateRenderParamsHandler:function(){var a=this.get("view._stage");a&&a.setRenderParams({shadowMap:this.view.environment.lighting.directShadowsEnabled,ssao:this.view.environment.lighting.ambientOcclusionEnabled})},_spatialReferenceHandler:function(){this._resetReferencePosition()},_viewingModeHandler:function(a){this._resetReferencePosition()},_resetReferencePosition:function(){this._cancelReferencePosUpdates();this._referencePosWGS84=this._referencePosResetPreserveAbsoluteTime=this._referencePosMapCoordsDesired=
this._referencePosMapCoords=null},_requestReferencePositionUpdate:function(a,c){this.view.mapCoordsHelper.canProject()&&!this.noReferencePositionQueries&&(this._referencePosUpdateQuery||null!=this._referencePosUpdateTimer||this.view.interacting||!this.view.stationary?(this._referencePosMapCoordsDesired?this._referencePosMapCoordsDesired.copy(a):this._referencePosMapCoordsDesired=a.clone(),this._referencePosResetPreserveAbsoluteTime=!!c):(c&&(this._preserveAbsoluteDateTime=!1),this._referencePosMapCoords?
this._referencePosMapCoords.copy(a):this._referencePosMapCoords=a.clone(),this._referencePosUpdateQuery=this.view.mapCoordsHelper.toGeographic(this._referencePosMapCoords).then(function(a){this._referencePosUpdateQuery=null;if(!isNaN(a[0])&&!isNaN(a[1])){var c=this._referencePosMapCoords.z*this.view.mapCoordsHelper.unitInMeters;this._referencePosWGS84?(this._referencePosWGS84.x=a[0],this._referencePosWGS84.y=a[1],this._referencePosWGS84.z=c):this._referencePosWGS84=new h({x:a[0],y:a[1],z:c,spatialReference:k.WGS84});
this._referencePosChanged();null==this._referencePosUpdateTimer&&this._executePendingReferencePositionUpdate()}this.notifyChange("updating")}.bind(this),function(a){this._referencePosUpdateQuery=null;this.notifyChange("updating")}.bind(this)),this._referencePosUpdateTimer=window.setTimeout(function(){this._referencePosUpdateTimer=null;this._referencePosUpdateQuery||this._executePendingReferencePositionUpdate();this.notifyChange("updating")}.bind(this),this.referencePointUpdateInterval),this.notifyChange("updating")))},
_executePendingReferencePositionUpdate:function(){var a=this._referencePosMapCoordsDesired,c=this._referencePosResetPreserveAbsoluteTime;a&&this._exceedsReferencePosDistThreshold(a)&&(this._referencePosResetPreserveAbsoluteTime=this._referencePosMapCoordsDesired=null,this._requestReferencePositionUpdate(a,c))},_referencePosChanged:function(){this._preserveAbsoluteDateTime?this._updateLightParams():this._autoUpdateTimezone(this._referencePosWGS84)||this._updateLightParams()},_exceedsReferencePosDistThreshold:function(a){return this._referencePosMapCoords?
(a=this._referencePosMapCoords.distance(a),this.view.mapCoordsHelper&&(a*=this.view.mapCoordsHelper.unitInMeters),a>this.referencePointUpdateDistThreshold):!0},_cancelReferencePosUpdates:function(){this._referencePosUpdateQuery&&(this._referencePosUpdateQuery.cancel(),this._referencePosUpdateQuery=null);null!=this._referencePosUpdateTimer&&(window.clearTimeout(this._referencePosUpdateTimer),this._referencePosUpdateTimer=null)}});f.FIXED_LIGHT_DIRECTION=p;return f});