// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/views/3d/environment/materials/StarMaterial.xml":'\x3c?xml version\x3d"1.0" encoding\x3d"UTF-8"?\x3e\r\n\r\n\x3csnippets\x3e\r\n\r\n\x3csnippet name\x3d"vertexShaderStar"\x3e\x3c![CDATA[\r\n\tprecision mediump float;\r\n\tuniform mat4 proj;\r\n\tuniform mat4 view;\r\n\tuniform mat4 model;\r\n\tuniform vec4 viewport;\r\n\r\n\tattribute vec3 $position;\r\n\tattribute vec4 $color;\r\n  attribute float $size;\r\n\r\n\tvarying vec4 vcolor;\r\n\tvarying float vsize;\r\n\r\n\t$matchPixelCenter\r\n\r\n\tvoid main(void) {\r\n\t\tvec4 posProj \x3d proj * view * model*vec4($position*1.0e25,1.0);//move infinitely far away\r\n\t\tgl_Position \x3d matchPixelCenter(posProj, viewport.zw); //pixel align position\r\n    gl_Position.z \x3d gl_Position.w; // project atmosphere onto the far plane\r\n\t\tvcolor \x3d $color/1.2;\r\n\t\tvsize \x3d size*5.0;\r\n\t\tgl_PointSize \x3d vsize;\r\n\t}\r\n]]\x3e\x3c/snippet\x3e\r\n\r\n\x3csnippet name\x3d"fragmentShaderStar"\x3e\x3c![CDATA[\r\n\tprecision mediump float;\r\n\r\n\tvarying vec4 vcolor;\r\n\tvarying float vsize;\r\n\r\n\tvoid main() {\r\n\t\tfloat cap \x3d 0.7;\r\n\t\tfloat scale \x3d 1.0/cap;\r\n\t\tfloat helper \x3d clamp(length(abs(gl_PointCoord-vec2(0.5))),0.0,cap);\r\n\t\tfloat alpha \x3d clamp((cap-helper)*scale,0.0,1.0);\r\n\t\tfloat intensity \x3d alpha*alpha*alpha;\r\n\t\tif (vsize \x3c 3.0)\r\n\t\t\tintensity *\x3d 0.5;\r\n\t\tgl_FragColor \x3d vec4(1.0,1.0,1.0,intensity);\r\n\t\tgl_FragColor.xyz *\x3d vcolor.xyz;\r\n\t}\r\n]]\x3e\x3c/snippet\x3e\r\n\x3c/snippets\x3e\r\n'}});
define("dojo/text!./materials/StarMaterial.xml require ../../../request ../../../core/watchUtils ../../../core/promiseUtils ../lib/glMatrix ../support/ExternalRenderer ../webgl-engine/lib/GeometryRenderer ../webgl-engine/lib/Util ../webgl-engine/lib/VertexBufferLayout ../webgl-engine/materials/internal/MaterialUtil ../webgl-engine/lib/GLSLProgram ../webgl-engine/lib/webglConstants ../webgl-engine/lib/RenderPass ../webgl-engine/lib/RenderSlot".split(" "),function(w,x,y,z,A,h,B,C,D,E,F,u,s,G,v){var r=
h.mat4d;h=h.mat3d;var d=D.VertexAttrConstants,H="9bb2ff;9eb5ff;aabfff;bbccff;ccd8ff ;dae2ff;e4e9ff;eeefff;f8f6ff;fff9fb;fff5ef;fff1e5;ffeddb;ffe9d2;ffe6ca;ffe3c3;ffe0bb;ffddb4;ffdaad;ffd6a5;ffd29c;ffcc8f;ffc178;ffa94b;ff7b00".split(";"),I=h.toMat4(h.createFrom(1,0,0,0,0.9174771405229186,0.39778850739794974,0,-0.39778850739794974,0.9174771405229186)),J=h.toMat4(h.createFrom(1,0,0,0,0.9174771405229186,-0.39778850739794974,0,0.39778850739794974,0.9174771405229186)),t=null;return B.createSubclass({classMetadata:{properties:{view:{},
numBinaryFloats:{value:2},numBinaryUInt8:{value:1},bytesPerStar:{value:9},slot:{value:v.BACKGROUND,setter:function(a){this.needsRender=!0;return a}}}},constructor:function(){this._renderData={model:r.identity()};this.slot=v.BACKGROUND;this._vertexBufferLayout=new E([d.POSITION,d.COLOR,d.SIZE],[3,4,1],[s.FLOAT,s.UNSIGNED_BYTE,s.FLOAT])},initialize:function(){this._loadDataPromise=this._loadBrightStarCatalogue();this.addResolvingPromise(this._loadDataPromise)},destroy:function(){this._loadDataPromise.isFulfilled()||
this._loadDataPromise.cancel("Atmosphere has been removed.");this._dateHandle&&(this._dateHandle.remove(),this._dateHandle=null);this._program&&this._program.dispose()},setup:function(a){this._numStars=this._starData.byteLength/this.bytesPerStar;var b=new Float32Array(this._starData,0,this._numStars*this.numBinaryFloats),c=new Uint8Array(this._starData,4*this._numStars*this.numBinaryFloats,this._numStars*this.numBinaryUInt8),b=this._createStarGeometryData(b,c);this._renderer=new C(b,this._vertexBufferLayout,
this._fillInterleaved,a.gl);this._renderer.enablePointRendering(!0);this._dateHandle=z.init(this,"view.environment.lighting.date",this._update.bind(this));a.shaderSnippets.vertexShaderStar||a.shaderSnippets._parse(w);this._program=u.fromSnippets("vertexShaderStar","fragmentShaderStar",a.shaderSnippets,a.gl)},render:function(a){if(a.slot!==this.slot||a.pass!==G.MATERIAL)return!1;var b=this.renderContext.gl,c=this._program;c.use();c.uniformMatrix4fv("view",a.camera.viewMatrix);c.uniformMatrix4fv("proj",
a.camera.projectionMatrix);c.uniform4fv("viewport",a.camera.fullViewport);c.uniformMatrix4fv("model",this._renderData.model);b.web3DDefaultState.depthFunc!==b.LEQUAL&&b.depthFunc(b.LEQUAL);b.enable(b.BLEND);b.depthMask(!1);this._renderer.render(this._program);u.unuse(b);b.depthMask(!0);b.disable(b.BLEND);b.web3DDefaultState.depthFunc!==b.LEQUAL&&b.depthFunc(b.web3DDefaultState.depthFunc);return!0},_fillInterleaved:function(a,b,c,f,q,g,e){c=q.getStride();var k=4*c,n=F.fill;q=q.getAttributes();var p=
a.faces.indices[d.POSITION],m=a.vertexAttr[d.POSITION].data;f=e+q[d.POSITION].offset;for(var l=0;l<p.length;++l){var h=3*p[l];n(m,h,g,f,b,3);f+=c}b=a.faces.indices[d.COLOR];p=a.vertexAttr[d.COLOR].data;f=4*(e+q[d.COLOR].offset);m=new Uint8Array(g.buffer);for(l=0;l<b.length;++l)h=4*b[l],n(p,h,m,f,null,4),f+=k;k=a.faces.indices[d.SIZE];a=a.vertexAttr[d.SIZE].data;f=e+q[d.SIZE].offset;for(l=0;l<k.length;++l)g[f]=a[k[l]],f+=c},_computeDayDuration:function(a){var b=new Date(a.getFullYear(),0,1,11,58,56),
c=new Date(a.getFullYear()+1,0,1,11,58,55);return(a-b)/(c-b)},_update:function(a){if(a){var b=a.getHours()/12,c=a.getMinutes()/60*(2/24),d=a.getSeconds()/60*(2/1440),b=(b+c+d-0.9972222)%2;a=2*this._computeDayDuration(a);c=r.create(J);r.rotateZ(c,-a*Math.PI);r.multiply(I,c,c);r.rotateZ(c,-b*Math.PI);this._renderData.model=c;this.needsRender=!0}},_hexToRGB:function(a){return[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)]},_unpackUint8Attributes:function(a){return 192<=
a?[2.9,a-192]:160<=a?[2.5,a-160]:128<=a?[2,a-128]:96<=a?[1.5,a-96]:64<=a?[1,a-64]:32<=a?[0.7,a-32]:[0.4,a]},_createStarGeometryData:function(a,b){for(var c=new Float32Array(3*this._numStars),f=new Uint8Array(4*this._numStars),h=new Float32Array(this._numStars),g=new Uint32Array(this._numStars),e=0;e<this._numStars;e++){var k=2*e,n=3*e,p=4*e,m=a[k+0],k=a[k+1];c[n+0]=-Math.cos(m)*Math.sin(k);c[n+1]=-Math.sin(m)*Math.sin(k);c[n+2]=-Math.cos(k);n=this._unpackUint8Attributes(b[e]);m=this._hexToRGB(H[n[1]]);
f[p+0]=255*m[0];f[p+1]=255*m[1];f[p+2]=255*m[2];f[p+3]=255;h[e]=n[0];g[e]=e}e={};e[d.POSITION]=g;e[d.NORMAL]=g;e[d.UV0]=g;e[d.COLOR]=g;e[d.SIZE]=g;g={};g[d.POSITION]={size:3,data:c};g[d.COLOR]={size:4,data:f};g[d.SIZE]={size:1,data:h};return{faces:{type:"point",indices:e,positionKey:d.POSITION},vertexAttr:g}},_loadBrightStarCatalogue:function(){return t?(this._starData=t,A.resolve()):y(x.toUrl("./resources/stars.wsv"),{responseType:"array-buffer",failOk:!0}).then(function(a){if(a=a.data)this._starData=
t=a;else throw Error("no data received");}.bind(this)).otherwise(function(a){console.error("Failed to load star data:",a);throw a;})}})});