// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports dojo/string ../lib/lights ../lib/ModelContentType ../lib/ModelDirtySet ../lib/RenderGeometry ../lib/Util ../lib/gl-matrix".split(" "),function(C,D,r,h,d,s,A,k,n){var e=k.assert,t=k.verify,p=n.vec3d,B=n.mat4d,u=k.logWithBase;return function(){function b(){this.dirtySet=new s(this);this.ambientLight=new h.AmbientLight([1,1,1],0.3);this.directionalLight=new h.DirectionalLight([1,1,1],0.7,p.normalize([1,1,1]));this._uniqueName2idx={};this._uniqueIdx=0;this._id2origin={};this._modelListeners=
[];this.content={};for(var a in d)this.content[d[a]]={}}b.prototype.getAll=function(a){a=this.content[a];e(void 0!==a);return a};b.prototype.get=function(a,c){return this.getAll(a)[c]};b.prototype.add=function(a,c){var f=this.content[a];e(void 0!==f);var b=c.getId();e(null==f[b],"Model/Stage already contains object to be added");f[b]=c;a===d.LAYER&&this.notifyDirty(a,c,"layerAdded");this._notifyContentAdded(a,c)};b.prototype.remove=function(a,c){var f=this.content[a];e(void 0!==f);var b=f[c];e(void 0!==
b,"Model/Stage doesn't contain object to be removed");delete f[c];a===d.TEXTURE&&b.unload();a===d.LAYER&&this.notifyDirty(a,b,"layerRemoved");this._notifyContentRemoved(a,b);return b};b.prototype.getDirtySet=function(){return this.dirtySet};b.prototype.notifyDirty=function(a,c,f,b){this.dirtySet.handleUpdate(c,f,b)};b.prototype.getAmbientLight=function(){return this.ambientLight};b.prototype.setAmbientLight=function(a){this.ambientLight.set(a)};b.prototype.getDirectionalLight=function(){return this.directionalLight};
b.prototype.setDirectionalLight=function(a){this.directionalLight.set(a)};b.prototype.getSelection=function(){return this.selection};b.prototype.setSelection=function(a,c){this.selection=a;this.selectionFaceRange=c};b.prototype.getSelectionFaceRange=function(){return this.selectionFaceRange};b.prototype.getOrigin=function(a,c,f){void 0===f&&(f=10);var b=0;c=c*f/1E4;1<c&&(b=Math.ceil(u(c,2)));c=1E4*Math.pow(2,b);f=Math.round(a[0]/c);var d=Math.round(a[1]/c);a=Math.round(a[2]/c);var b=b+"_"+f+"_"+d+
"_"+a,e=this._id2origin[b];null==e&&(e={vec3:p.createFrom(f*c,d*c,a*c),id:b},this._id2origin[b]=e);return e};b.prototype.getGeometryRenderGeometries=function(a,c,b){for(var d=a.getId(),e=c.geometry,m=e.getData(),k=!!e.singleUse,h=m.getFaces(),n=m.getVertexAttr(),m=m.getId(),p=c.materials,r=c.instanceParameters,x=a.getCombinedTransformation(c),s=B.maxScale(x),t=c.origin,y=a.getVisibleIndexRanges(c),g=0,u=e.getNumGroups();g<u;++g){var l=e.getBoundingInfo(g),v=c.getId()+"#"+g,q=this._uniqueName2idx[v];
null==q&&(q=this._uniqueIdx++,this._uniqueName2idx[v]=q);var z={},w;for(w in h[g].indices)z[w]=n[w];l=new A({faces:h[g],vertexAttr:z,id:m+"#"+g},l,p[g],x,s,a.getCastShadow(),k,d,v,q,g);l.origin=t||this.getOrigin(l.center,l.bsRadius);l.displayedIndexRange=y?y[g]:null;l.instanceParameters=r?c.instanceParameters[g]:null;b.push(l)}};b.prototype.formatDebugInfo=function(a){var c=[];if(a){c[0]="\x3ctable\x3e";for(var b in d)a=d[b],c[0]+="\x3ctr\x3e\x3ctd\x3e"+a+'\x3c/td\x3e\x3ctd style\x3d"text-align: right"\x3e'+
Object.keys(this.getAll(a)).length+"\x3c/td\x3e\x3c/tr\x3e";c[0]+="\x3c/table\x3e";c[1]=this.dirtySet.formatDebugInfo(!0)}else{c[0]="";for(b in d)a=d[b],c[0]+=r.pad(String(Object.keys(this.getAll(a)).length),6," ")+" "+a+", ";c[1]=this.dirtySet.formatDebugInfo(!1)}return c};b.prototype.validateContent=function(){var a=this.getAll(d.OBJECT),c;for(c in a)this.validateObject(a[c]);a=this.getAll(d.LAYER);for(name in a)this.validateLayer(a[name]);a=this.getAll(d.MATERIAL);for(name in a)this.validateMaterial(a[name])};
b.prototype.validateObject=function(a){a=a.geometryRecords;for(var c=0;c<a.length;++c){var b=a[c];e(null!=this.get(d.GEOMETRY,b.geometry.id));var h=b.geometry.numGroups;e(h<=b.materials.length,"object materials do not match geometry groups");t(h===b.materials.length,"object materials do not match geometry groups");for(var k=0;k<h;++k)e(null!=this.get(d.MATERIAL,b.materials[k].getId()))}};b.prototype.validateLayer=function(a){a=a.getObjects();for(var c=0;c<a.length;++c){var b=this.get(d.OBJECT,a[c].getId());
e(null!=b)}};b.prototype.validateMaterial=function(a){a=a.getAllTextureIds();for(var c=0;c<a.length;++c){var b=this.get(d.TEXTURE,a[c]);e(null!=b)}};b.prototype.addModelListener=function(a){e(-1===this._modelListeners.indexOf(a));this._modelListeners.push(a)};b.prototype.removeModelListener=function(a){a=this._modelListeners.indexOf(a);e(-1!==a);this._modelListeners.splice(a,a)};b.prototype._notifyContentAdded=function(a,c){this._modelListeners.forEach(function(b){b.contentAdded&&b.contentAdded(a,
c)})};b.prototype._notifyContentRemoved=function(a,c){this._modelListeners.forEach(function(b){b.contentRemoved&&b.contentRemoved(a,c)})};b.ContentType=d;return b}()});