// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../lib/GLTextureRep ../lib/GLSLProgramRep ../lib/GLMaterialRep ../lib/ShaderSnippets ../lib/GLSLShaderRep ../lib/GLVBORep ../lib/TextureRenderer ../lib/Util ../lib/gl-matrix ../lib/webgl-utils ../lib/GLDefaultState ./Model ./Viewport ../materials/repository ../lib/SSAOHelperObscurance ../lib/HighlightHelper ../lib/OffscreenRenderingHelper ../../../../core/sniff ../lib/tracer".split(" "),function(n,H,q,r,s,t,u,v,w,x,p,y,z,A,B,C,D,E,F,G,m){var l=p.vec3d,f=p.vec4d;n=function(){function b(a,
c,b,h){var e=this;this._backgroundColor=f.createFrom(1,1,1,1);this._lightDirection=l.createFrom(0,1,0);this._didRender=!1;this._idleSuspend=this._needsRender=!0;this._shouldRender=!1;this._screenCaptureQueue=[];this._container=a;this._stage=c;this._initializeContext(h);this._initializeShaders();this._vboRep=new v;this._textureRep=new q(c.getAll(A.ContentType.TEXTURE),this._programRep,function(){return e._viewport.getCamera().viewport},this._gl);this._materialRep=new s(this._textureRep,this._programRep);
this._viewport=new B(this._programRep,this._vboRep,this._materialRep,this._textureRep,this._gl);this._initializeViewportCamera();this._textureRenderer=new w(this._gl,this._canvas,this._programRep,this._materialRep,this._textureRep,b);this._initializeFrameTask()}b.prototype._initializeFrameTask=function(){var a=this;this._frameTask={preRender:function(){m.begin();a._stage.processDirty();a.needsRender()?(a._shouldRender=!0,a._viewport.getCamera().setGLViewport(a._gl),a._gl.clearColor.apply(a._gl,a._backgroundColor),
a._gl.clear(16640)):a._shouldRender=!1},render:function(){a._shouldRender&&(a._didRender=!0,a._gl.web3DDefaultState.apply(),a._viewport.render(a._lightDirection,null))},postRender:function(){m.end()},update:function(){a._performScreenCaptures();a.resetNeedsRender()}}};b.prototype._initializeViewportCamera=function(){var a=this._container.getBoundingClientRect(),c=this._viewport.getCamera();c.viewport[2]=a.width;c.viewport[3]=a.height;this._viewport.setCamera(c)};b.prototype._initializeContext=function(a){this._canvas=
a.canvas;this._canvas||(this._canvas=document.createElement("canvas"));this._canvas.setAttribute("style","width: 100%; height:100%; display:block;");var c={alpha:a.alpha||!1};null!=a.antialias&&(c.antialias=a.antialias,G("ff")&&!1===a.antialias&&(c.stencil=!0));a=y.setupWebGL(this._canvas,c);this._gl=m.instrumentContext(a[0]);this._gl.pixelStorei(37440,!0);this._gl.web3DDefaultState=new z(this._gl);this._container.appendChild(this._canvas)};b.prototype._initializeShaders=function(){this._shaderSnippets=
new t;this._shaderRep=new u;this._programRep=new r;C.initializeShaders(this._shaderSnippets,this._shaderRep,this._programRep,this._gl);E.loadShaders(this._shaderSnippets,this._shaderRep,this._programRep,this._gl);D.loadShaders(this._shaderSnippets,this._shaderRep,this._programRep,this._gl);F.loadShaders(this._shaderSnippets,this._shaderRep,this._programRep,this._gl)};b.prototype.dispose=function(){this._viewport.dispose();this._viewport=null;this._textureRenderer.dispose();this._textureRenderer=null;
this._programRep.dispose();this._programRep=null;this._container.contains(this._canvas)&&this._container.removeChild(this._canvas);this._gl=this._canvas=this._container=null};b.prototype.getCombinedStats=function(){return this._viewport.getCombinedStats()};b.prototype.setNeedsRender=function(){this._didRender=!1;this._needsRender=!0};b.prototype.resetNeedsRender=function(){this._didRender&&(this._didRender=this._needsRender=!1);this._viewport.resetNeedsRender();this._textureRep.resetNeedsRender()};
b.prototype.needsRender=function(){return this._needsRender||!this._idleSuspend||this._viewport.needsRender()||this._textureRep.needsRender()};b.prototype.getFrameTask=function(){return this._frameTask};b.prototype.setLights=function(a,c){l.set(c.direction,this._lightDirection);f.set4(a.color[0],a.color[1],a.color[2],a.intensity,k.ambient);f.set4(c.color[0],c.color[1],c.color[2],c.intensity,k.diffuse);f.set4(c.color[0],c.color[1],c.color[2],Math.min(c.intensity+a.intensity,1),k.specular);l.set(c.direction,
k.direction);this._viewport.setLightingData(k);this._needsRender=!0};b.prototype.getViewParams=function(a){var c=this._viewport.getViewParams(a);if(!a||a.backgroundColor)c.backgroundColor=this._backgroundColor;return c};b.prototype.setViewParams=function(a){this._needsRender=!0;a.backgroundColor&&(this._backgroundColor=a.backgroundColor);this._viewport.setViewParams(a)};b.prototype.setRenderParams=function(a){this._needsRender=!0;"anisotropicFiltering"in a&&this._textureRep.setMaxAnisotropy(a.anisotropicFiltering);
"backfaceCulling"in a&&(this._gl.web3DDefaultState.cullEnabled=a.backfaceCulling);void 0!==a.idleSuspend&&(this._idleSuspend=!!a.idleSuspend);this._viewport.setRenderParams(a)};b.prototype.getRenderParams=function(){var a=this._viewport.getRenderParams();a.anisotropicFiltering=this._textureRep.getMaxAnisotropy();a.backfaceCulling=this._gl.web3DDefaultState.cullEnabled;a.idleSuspend=this._idleSuspend;return a};b.prototype.has=function(a){return"s3tc"===a?!!this._gl.getExtension("WEBGL_compressed_texture_s3tc"):
!1};b.prototype.getFrustumObjects=function(){return this._viewport.getFrustumObjects()};b.prototype.modify=function(a,c,b,h){this._viewport.modify(a,c,b,h)};b.prototype.setSelectionObject=function(a,c){this._viewport.setSelectionObject(a,c)};b.prototype.setCamera=function(a){this._viewport.setCamera(a)};b.prototype.getCamera=function(){return this._viewport.getCamera()};b.prototype.getPickRay=function(a,c,b){this._viewport.getPickRay(a,c,b)};b.prototype.pickRayWithBeginPoint=function(a,c,b,h,e){this._viewport.pickRayWithBeginPoint(a,
c,b,h,e)};b.prototype.getCanvas=function(){return this._canvas};b.prototype.getTextureGraphicsRenderer=function(){return this._textureRenderer};b.prototype.requestScreenCapture=function(a,c){this._screenCaptureQueue.push({settings:a||{},callback:c});this._needsRender=!0};b.prototype.getAllTexturesLoaded=function(){return 0===this._textureRep.getLoadingCount()};b.prototype.getTextureLoaded=function(a){return this._textureRep.getIsLoaded(a)};b.prototype.addTextureListener=function(a){this._textureRep.addTextureListener(a)};
b.prototype.removeTextureListener=function(a){this._textureRep.removeTextureListener(a)};b.prototype.addExternalRenderer=function(a,c){return this._viewport.addExternalRenderer(a,c)?(c.initializeRenderContext({gl:this._gl,shaderSnippets:this._shaderSnippets,shaderRep:this._shaderRep,programRep:this._programRep,textureRep:this._textureRep}),!0):!1};b.prototype.removeExternalRenderer=function(a){return this._viewport.removeExternalRenderer(a)};b.prototype._performScreenCaptures=function(){if(0!==this._screenCaptureQueue.length){for(var a=
0;a<this._screenCaptureQueue.length;a++){var c=this._screenCaptureQueue[a],b=0,h=0,e=this._canvas.width,g=this._canvas.height,d=this._canvas.width,f=this._canvas.height;if(d=c.settings.area)b=d.x,h=d.y,e=d.width,g=d.height;void 0!==c.settings.width&&void 0!==c.settings.height?(d=c.settings.width/c.settings.height,g*d<e?(d*=g,b+=Math.floor((e-d)/2),e=Math.floor(d)):(d=e/d,h+=Math.floor((g-d)/2),g=Math.floor(d)),d=c.settings.width,f=c.settings.height):(d=e,f=g);var k=this._canvas;if(0!==b||0!==h||e!==
this._canvas.width||g!==this._canvas.height||d!==this._canvas.width||f!==this._canvas.height){this._resizeCanvas||(this._resizeCanvas=document.createElement("canvas"));this._resizeCanvas.width=d;this._resizeCanvas.height=f;var k=this._resizeCanvas.getContext("2d"),l=new Uint8Array(4*e*g);this._gl.readPixels(b,this._canvas.height-(h+g),e,g,6408,5121,l);b=k.getImageData(0,0,d,f);x.resampleHermite(l,e,g,b.data,d,f,!0);k.putImageData(b,0,0);k=this._resizeCanvas}e={png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg"}[c.settings.format?
c.settings.format.toLowerCase():"png"];g=1;void 0!==c.settings.quality&&(g=c.settings.quality/100);e=k.toDataURL(e,g);c.callback({dataURL:e,x:0,y:0,width:d,height:f})}this._screenCaptureQueue=[]}};return b}();var k={ambient:f.create(),diffuse:f.create(),specular:f.create(),direction:l.create()};return n});