// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports dojo/has ../lib/PerformanceTimer ../lib/Camera ../lib/Util ../lib/BitSet ../lib/gl-matrix ./Visualizer".split(" "),function(d,N,O,p,t,A,u,m,v){var q=m.vec3;d=m.vec4d;var x=m.mat4d,r=2E4,e=[0,0],y=x.create(),c=[d.create(),d.create(),d.create(),d.create(),d.create(),d.create()],w={get:function(a){return!0}},k=0;return function(){function a(b,l,a,c,d){this._content={};this._visibleContent=new u;this._frustumCullingEnabled=!0;this._maxFarNearRatio=r;this._stats={renderGeometriesTotal:0,
renderGeometriesVisible:0,visualizerRenderTimer:null,viewportRenderTimer:null};this._needsRender=!0;this._gl=d;this._visualizer=new v(b,l,a,c,d);this._camera=new t(q.createFrom(0,100,-100),q.createFrom(0,0,0));k&&(this._stats.visualizerRenderTimer=new p(10),this._stats.viewportRenderTimer=new p(10))}a.prototype.getCombinedStats=function(){var b={},l=this._visualizer.getCombinedStats(),a;for(a in l)b[a]=l[a];b.renderGeometriesTotal=this._stats.renderGeometriesTotal;b.renderGeometriesVisible=this._stats.renderGeometriesVisible;
k&&(b.visualizerTotalRenderTime=this._stats.visualizerRenderTimer.getTotal(),b.visualizerCurrentRenderTime=this._stats.visualizerRenderTimer.getLastFiltered(),b.viewportTotalRenderTime=this._stats.viewportRenderTimer.getTotal(),b.viewportCurrentRenderTime=this._stats.viewportRenderTimer.getLastFiltered(),b.totalNumFramesRendered=this._stats.viewportRenderTimer.getNumMeasurements());void 0!==this._gl.getUsedTextureMemory&&(b.textureMemory=this._gl.getUsedTextureMemory());void 0!==this._gl.getUsedRenderbufferMemory&&
(b.renderbufferMemory=this._gl.getUsedRenderbufferMemory());void 0!==this._gl.getUsedVBOMemory&&(b.VBOMemory=this._gl.getUsedVBOMemory());if(void 0!==this._gl.getUsedTextureMemoryStats){var l=this._gl.getUsedTextureMemoryStats(),c;for(c in l)b["texMem type: "+c]=l[c]}return b};a.prototype.dispose=function(){this._visualizer.dispose();this._visualizer=null};a.prototype.setLightingData=function(b){this._visualizer.setLightingData(b)};a.prototype.getLightingData=function(){return this._visualizer.getLightingData()};
a.prototype.getViewParams=function(b){var a=this._visualizer.getViewParams(b);if(!b||b.frustumCullingEnabled)a.frustumCullingEnabled=this._frustumCullingEnabled;if(!b||b.maxFarNearRatio)a.maxFarNearRatio=this._maxFarNearRatio;return a};a.prototype.setViewParams=function(b){void 0!==b.frustumCullingEnabled&&(this._frustumCullingEnabled=b.frustumCullingEnabled);void 0!==b.maxFarNearRatio&&(this._maxFarNearRatio=-1===b.maxFarNearRatio?r:b.maxFarNearRatio);this._visualizer.setViewParams(b);this._needsRender=
!0};a.prototype.setRenderParams=function(b){this._visualizer.setRenderParams(b)};a.prototype.getRenderParams=function(){return this._visualizer.getRenderParams()};a.prototype.getFrustumObjects=function(){var b={},a;for(a in this._content)this._visibleContent.get(this._content[a].idx)&&(b[this._content[a].name]=1);return b};a.prototype.modify=function(b,a,c,d){this._visualizer.modify(b,a,c,d);this._content=this._visualizer.getContent()};a.prototype.getContent=function(){return this._content};a.prototype.setSelectionObject=
function(b,a){this._visualizer.setSelectionObject(b,a)};a.prototype.setCamera=function(b){this._camera.copyFrom(b);this._computeVisibleContentAndUpdateNearFar();this._needsRender=!0};a.prototype.getCamera=function(){return this._camera};a.prototype.getPickRay=function(b,a,c){return this.pickRayWithBeginPoint(b,void 0,this._camera.viewMatrix,a,c)};a.prototype.pickRayWithBeginPoint=function(b,a,c,d,e){return this._visualizer.getPickRay(b,a,this._camera,c,d,e)};a.prototype.addExternalRenderer=function(b,
a){return this._visualizer.addExternalRenderer(b,a)};a.prototype.removeExternalRenderer=function(b){return this._visualizer.removeExternalRenderer(b)};a.prototype.getExternalRenderers=function(){return this._visualizer.getExternalRenderers()};a.prototype.render=function(b,a){k&&this._stats.viewportRenderTimer.start();var c=this._computeVisibleContentAndUpdateNearFar();k&&this._stats.visualizerRenderTimer.start();this._visualizer.render(this._camera,b,c,a);k&&(this._stats.visualizerRenderTimer.stop(),
this._stats.viewportRenderTimer.stop())};a.prototype.resetNeedsRender=function(){this._needsRender=!1;this._visualizer.resetNeedsRender()};a.prototype.needsRender=function(){return this._needsRender||this._visualizer.needsRender()};a.prototype._computeVisibleContentAndUpdateNearFar=function(){return this._frustumCullingEnabled||0<this._maxFarNearRatio?(e[1]=0,this._computeFrustumCullingAndNearFar(this._camera.eye,this._visibleContent,e),0<this._maxFarNearRatio&&0<e[1]&&(this._camera.far=e[1],this._camera.near=
Math.max(e[0],this._camera.far/this._maxFarNearRatio)),this._visibleContent):w};a.prototype._computeFrustumCullingAndNearFar=function(b,a,d){x.perspective(this._camera.fovY,this._camera.aspect,1,10,y);A.matrix2frustumPlanes(this._camera.viewMatrix,y,c);a.clearAll();this._stats.renderGeometriesTotal=0;this._stats.renderGeometriesVisible=0;b=-Number.MAX_VALUE;var e=-Number.MAX_VALUE,k=c[0][0],m=c[0][1],p=c[0][2],q=c[0][3],r=c[1][0],t=c[1][1],u=c[1][2],v=c[1][3],w=c[2][0],B=c[2][1],C=c[2][2],D=c[2][3],
E=c[3][0],F=c[3][1],G=c[3][2],H=c[3][3],I=c[4][0],J=c[4][1],K=c[4][2],L=c[4][3],M=c[5][3],z;for(z in this._content){var s=this._content[z];this._stats.renderGeometriesTotal++;if(!s.material.isBackdrop){var f=s.center,g=f[0],h=f[1],n=f[2],f=s.bsRadius;if(k*g+m*h+p*n+q>f)continue;if(r*g+t*h+u*n+v>f)continue;if(w*g+B*h+C*n+D>f)continue;if(E*g+F*h+G*n+H>f)continue;h=I*g+J*h+K*n;g=h+f;f=-h+f;g>b&&(b=g);f>e&&(e=f)}a.set(s.idx);this._stats.renderGeometriesVisible++}a=b!==-Number.MAX_VALUE;e+=M;0<this._stats.renderGeometriesVisible&&
a&&(d[0]=0.99*Math.max(1-(b+L),2),d[1]=1.01*Math.max(10+e,d[0]+1))};return a}()});