// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../lib/Renderer ../lib/SSAOHelperObscurance ../lib/ShadowMap ../lib/NearFarCalc ../lib/Util ../lib/gl-matrix ../lib/RenderPass ../lib/HighlightHelper ../lib/OffscreenRenderingHelper".split(" "),function(w,x,n,p,q,r,h,m,s,t,u){var g=m.vec3d,l=m.mat4d,v=h.assert;return function(){function b(a,f,b,c,d){this._drawSSAOMapDebugQuad=this._drawShadowMapDebugQuad=!1;this._needsRender=!0;this._content={};this._gl=d;this._renderer=new n(a,f,b,c,d,!1);this._programRep=a;this._shadowMap=
new q(a,d);this._ssaoHelper=new p(a,c,d);this._nearFarCalc=new r;this._highlightHelper=new t(a,c,d);this._offscreenRenderingHelper=new u(a,d)}b.prototype.getCombinedStats=function(){return this._renderer.getCombinedStats()};b.prototype.dispose=function(){this._renderer.dispose();this._shadowMap.getEnableState()&&this._shadowMap.setEnableState(!1);this._ssaoHelper.getEnableState()&&this._ssaoHelper.setEnableState(!1);this._highlightHelper.getEnableState()&&this._highlightHelper.setEnableState(!1);
this._offscreenRenderingHelper.getEnableState()&&this._offscreenRenderingHelper.setEnableState(!1)};b.prototype.setLightingData=function(a){this._renderer.setLightingData(a)};b.prototype.getLightingData=function(){return this._renderer.getLightingData()};b.prototype.getViewParams=function(a){var f=a||{};if(!a||a.pixelRatio)f.pixelRatio=this._renderer.getPixelRatio();return f};b.prototype.setViewParams=function(a){null!=a.pixelRatio&&this._renderer.setPixelRatio(a.pixelRatio)};b.prototype.setRenderParams=
function(a){void 0!==a.shadowMapResolution&&!1===this._shadowMap.getEnableState()&&this._shadowMap.setTextureResolution(a.shadowMapResolution);void 0!==a.shadowMap&&a.shadowMap!==this._shadowMap.getEnableState()&&this._shadowMap.setEnableState(a.shadowMap);void 0!==a.shadowMapMaxCascades&&this._shadowMap.setMaxNumCascades(a.shadowMapMaxCascades);!0!==this._highlightHelper.getEnableState()&&this._highlightHelper.setEnableState(!0);void 0!==a.ssao&&a.ssao!==this._ssaoHelper.getEnableState()&&this._ssaoHelper.setEnableState(a.ssao);
void 0!==a.ssaoAttenuation&&this._ssaoHelper.setAttenuation(a.ssaoAttenuation);void 0!==a.ssaoRadius&&this._ssaoHelper.setRadius(a.ssaoRadius);void 0!==a.ssaoFilterRadius&&this._ssaoHelper.setFilterRadius(a.ssaoFilterRadius);void 0!==a.ssaoSamples&&this._ssaoHelper.setSamples(a.ssaoSamples);void 0!==a.drawShadowMapDebugQuad&&(this._drawShadowMapDebugQuad=a.drawShadowMapDebugQuad);void 0!==a.drawSSAODebugQuad&&(this._drawSSAOMapDebugQuad=a.drawSSAODebugQuad);this._ssaoHelper.getEnableState()?this._renderer.ssaoEnabled=
!0:this._renderer.ssaoEnabled=!1;void 0!==a.offscreenRendering&&a.offscreenRendering!==this._offscreenRenderingHelper.getEnableState()&&(this._offscreenRenderingHelper.setEnableState(a.offscreenRendering),this._renderer.offscreenRenderingEnabled=a.offscreenRendering);this._needsRender=!0};b.prototype.getRenderParams=function(){var a={};this._shadowMap.getIsSupported()&&(a.shadowMap=this._shadowMap.getEnableState(),a.shadowMapResolution=this._shadowMap.getTextureResolution(),a.shadowMapMaxCascades=
this._shadowMap.getMaxNumCascades());this._ssaoHelper.getIsSupported()&&(a.ssao=this._ssaoHelper.getEnableState(),a.ssaoAttenuation=this._ssaoHelper.getAttenuation(),a.ssaoRadius=this._ssaoHelper.getRadius(),a.ssaoFilterRadius=this._ssaoHelper.getFilterRadius(),a.ssaoSamples=this._ssaoHelper.getSamples());return a};b.prototype.modify=function(a,f,b,c){this._renderer.modify(a,f,b,c);c=0;for(var d=f.length;c<d;++c)delete this._content[f[c].uniqueName];c=0;for(f=a.length;c<f;++c)this._content[a[c].uniqueName]=
a[c];c=0;for(a=b.length;c<a;++c)v(this._content[b[c].renderGeometry.uniqueName]===b[c].renderGeometry)};b.prototype.getContent=function(){return this._content};b.prototype.getPickRay=function(a,b,e,c,d,k){g.unproject(g.createFrom(a[0],a[1],0),c,e.projectionMatrix,e.fullViewport,d);g.unproject(g.createFrom(a[0],a[1],1),c,e.projectionMatrix,e.fullViewport,k)};b.prototype.getProjectionMatrix=function(a,b,e,c,d){b=h.fovx2fovy(b,a[2],a[3]);l.perspective(180*b/Math.PI,a[2]/a[3],e,c,d)};b.prototype.setSelectionObject=
function(a,b){this._renderer.setSelectionObject(a,b)};b.prototype.addExternalRenderer=function(a,b){return this._renderer.addExternalRenderer(a,b)};b.prototype.removeExternalRenderer=function(a){return this._renderer.removeExternalRenderer(a)};b.prototype.getExternalRenderers=function(){return this._renderer.getExternalRenderers()};b.prototype.resetNeedsRender=function(){this._needsRender=!1;this._renderer.resetNeedsRender()};b.prototype.needsRender=function(){return this._needsRender||this._renderer.needsRender()};
b.prototype.render=function(a,b,e,c){var d=a.viewport,k;if(this._shadowMap.getEnableState()||this._ssaoHelper.getEnableState())k=this._nearFarCalc.calculateSceneNearFar(a,this._content,e);if(this._shadowMap.getEnableState()){this._shadowMap.prepare(a,b,this._content,e,k);b=this._shadowMap.getCascades();for(var g=0;g<b.length;++g){var h=b[g];h.camera.setGLViewport(this._gl);this._renderer.renderGeometryPass(s.MATERIAL_DEPTH_SHADOWMAP,h.camera,e)}this._shadowMap.finish(c);a.setGLViewport(this._gl)}this._shadowMap.bindAll(this._programRep);
this._renderer.renderAuxiliaryBuffers(a,e,this._shadowMap,this._ssaoHelper,k,c,this._offscreenRenderingHelper);this._renderer.render(a,e,this._shadowMap,this._ssaoHelper,c,this._highlightHelper,this._offscreenRenderingHelper);this._drawShadowMapDebugQuad&&this._shadowMap.getEnableState()&&(a=l.ortho(d[0],d[2],d[1],d[3],-1,1),this._shadowMap.drawDebugQuad(a));this._drawSSAOMapDebugQuad&&this._ssaoHelper.getEnableState()&&(a=l.ortho(d[0],d[2],d[1],d[3],-1,1),this._ssaoHelper.drawQuad(a))};return b}()});