// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../core/Accessoire ../../core/JSONSupporter ../../core/lang ../../core/screenUtils dojo/_base/lang dojo/number ../../PopupTemplate ../../widgets/Popup/PopupRendererViewModel ../../symbols/support/jsonUtils".split(" "),function(n,p,l,k,m,q,r,s,t){var h=n.createSubclass([p],{declaredClass:"esri.layers.support.LabelClass",classMetadata:{properties:{requiredFields:{dependsOn:["labelExpression","labelExpressionInfo","where"]}}},labelExpression:null,labelExpressionInfo:null,labelPlacement:null,
_labelPlacementReader:function(a,c){var d=a;this._labelPlacementLookup.hasOwnProperty(d)||(d=l.valueOf(this._labelPlacementLookup,d));return d},maxScale:0,minScale:0,_requiredFieldsGetter:function(){var a=Object.create(null);this._collectRequiredFields(a);return Object.keys(a)},sizeInfo:null,_sizeInfoReader:function(a,c){return a?{minSize:k.pt2px(a.minSize)||0,maxSize:k.pt2px(a.maxSize)||0}:a},symbol:null,_symbolReader:t.fromJSON,useCodedValues:null,where:null,_labelPlacementLookup:{"above-center":"esriServerPointLabelPlacementAboveCenter",
"above-left":"esriServerPointLabelPlacementAboveLeft","above-right":"esriServerPointLabelPlacementAboveRight","below-center":"esriServerPointLabelPlacementBelowCenter","below-left":"esriServerPointLabelPlacementBelowLeft","below-right":"esriServerPointLabelPlacementBelowRight","center-center":"esriServerPointLabelPlacementCenterCenter","center-left":"esriServerPointLabelPlacementCenterLeft","center-right":"esriServerPointLabelPlacementCenterRight","above-after":"esriServerLinePlacementAboveAfter",
"above-along":"esriServerLinePlacementAboveAlong","above-before":"esriServerLinePlacementAboveBefore","above-start":"esriServerLinePlacementAboveStart","above-end":"esriServerLinePlacementAboveEnd","below-after":"esriServerLinePlacementBelowAfter","below-along":"esriServerLinePlacementBelowAlong","below-before":"esriServerLinePlacementBelowBefore","below-start":"esriServerLinePlacementBelowStart","below-end":"esriServerLinePlacementBelowEnd","center-after":"esriServerLinePlacementCenterAfter","center-along":"esriServerLinePlacementCenterAlong",
"center-before":"esriServerLinePlacementCenterBefore","center-start":"esriServerLinePlacementCenterStart","center-end":"esriServerLinePlacementCenterEnd","always-horizontal":"esriServerPolygonPlacementAlwaysHorizontal"},getLabelExpression:function(){return this.labelExpressionInfo?this.labelExpressionInfo.value:this._validateLabelExpression(this.labelExpression)?this._convertLabelExpression(this.labelExpression):""},toJSON:function(){if(this.sizeInfo)var a={minSize:k.px2pt(this.sizeInfo.minSize||
0),maxSize:k.px2pt(this.sizeInfo.maxSize||0)};a={labelExpression:this.labelExpression,labelExpressionInfo:this.labelExpressionInfo&&m.clone(this.labelExpressionInfo),useCodedValues:this.useCodedValues,maxScale:this.maxScale,minScale:this.minScale,where:this.where,sizeInfo:a,labelPlacement:this._labelPlacementLookup.hasOwnProperty(this.labelPlacement)?this._labelPlacementLookup[this.labelPlacement]:this.labelPlacement,symbol:this.symbol&&this.symbol.toJSON()};return l.fixJson(a)},_collectRequiredFields:function(a){this._collectLabelExpressionRequiredFields(this.getLabelExpression(),
a);this._collectWhereRequiredFields(this.where,a)},_validateLabelExpression:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},_convertLabelExpression:function(a){return a.replace(/\[/g,"{").replace(/\]/g,"}")},_collectWhereRequiredFields:function(a,c){if(null!=a){var d=a.split(" ");3===d.length&&(c[d[0]]=!0);7===d.length&&(c[d[0]]=!0,c[d[4]]=!0)}},_collectLabelExpressionRequiredFields:function(a,c){var d=a.match(/{[^}]*}/g);d&&d.forEach(function(a){c[a.slice(1,-1)]=!0})}});h.evaluateWhere=function(a,
c){var d=function(a,c,b){switch(c){case "\x3d":return a==b?!0:!1;case "\x3c\x3e":return a!=b?!0:!1;case "\x3e":return a>b?!0:!1;case "\x3e\x3d":return a>=b?!0:!1;case "\x3c":return a<b?!0:!1;case "\x3c\x3d":return a<=b?!0:!1}return!1};try{if(null==a)return!0;var e=a.split(" ");if(3===e.length)return d(c[e[0]],e[1],e[2]);if(7===e.length){var f=d(c[e[0]],e[1],e[2]),g=e[3],b=d(c[e[4]],e[5],e[6]);switch(g){case "AND":return f&&b;case "OR":return f||b}}return!1}catch(h){console.log("Error.: can't parse \x3d "+
a)}};h.buildLabelText=function(a,c,d,e){return a.replace(/{[^}]*}/g,function(a){return h.formatField(a.slice(1,-1),a,c,d,e)})};h.formatField=function(a,c,d,e,f){var g;for(g=0;g<e.length;g++)if(e[g].name==a){c=d[e[g].name];var b=e[g].domain;if(b&&m.isObject(b)){if("codedValue"==b.type)for(a=0;a<b.codedValues.length;a++)b.codedValues[a].code==c&&(c=b.codedValues[a].name);else"range"==b.type&&(b.minValue<=c&&c<=b.maxValue)&&(c=b.name);break}b=e[g].type;if("date"==b)b=f&&f.dateFormat||"shortDate",b=r.prototype._dateFormatJsonDict.fromJSON(b),
(b="DateFormat"+s.prototype._dateFormats[b])&&(c=l.substitute({myKey:c},"{myKey:"+b+"}"));else if("integer"==b||"small-integer"==b||"long"==b||"double"==b)f&&(f.numberFormat&&f.numberFormat.digitSeparator&&f.numberFormat.places)&&(c=q.format(c,{places:f.numberFormat.places}))}return null==c?"":c};return h});