// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../core/declare dojo/_base/lang dojo/_base/array dojo/io-query ../../request ../../core/urlUtils ../../core/Accessoire".split(" "),function(g,m,n,p,q,r,s){var l=function(a,b,c){this.id=[a,b,c].join("/");this.level=a;this.row=b;this.col=c},h=function(a,b,c,d,f){this.id=[a,b,c,d,f].join("/");this.level=a;this.row=b;this.col=c;this.width=d;this.height=f;this.promise=this.location=this.valid=this.dataValue=this.data=null};h.prototype={setData:function(a){var b=a?a.data:null,c=null,d;m.mixin(this,
a||{});if(b&&0<b.length)if(d=b.length,1===d)c=b[0];else{c=b[0];for(a=1;a<d;a++)if(b[a]!==c){c=null;break}}null!==c&&(this.data=null,this.dataValue=c);return this},isTileAvailable:function(a,b){var c=this.location,d=this.data,f=this.dataValue,e;this.valid?null!==f?c=f:(f=c.left,e=c.top,c=(a-e)*c.width+(b-f),c=c<d.length?d[c]:0):c=0;return!!c}};g=g(s,{declaredClass:"esri.layers.support.TileMap",constructor:function(){this._tileMapCache={}},width:8,height:8,getTileMap:function(a,b,c,d,f){var e=null!=
a.level?a:new h(a,b,c,d,f);a=q(this._getTileMapUrl(e.level,e.row,e.col,e.width,e.height),{responseType:"json",callbackParamName:"callback",timeout:3E3,failOk:!0}).then(function(a){return e.setData(a.data)});return e.promise=a},getTile:function(a,b,c,d){var f=this._getResamplingBudget(),e=null;a&&null!=a.level?(e=a,d=b):e=new l(a,b,c);0<f?this._process({tile:e,requestedTile:e,callback:d,resamplingBudget:f}):d.call(this,e,e)},statusOf:function(a,b,c){var d=this._getResamplingBudget();a=new l(a,b,c);
if(0===d)return 1;for(;0<=d;){b=this._tileToTileMap(a);if(!this._tileMapCache[b.id])return-1;b=this._tileMapCache[b.id];if(!b.promise.isFulfilled())return-1;if(b.isTileAvailable(a.row,a.col))return 1;a=this._parentTile(a);if(!a)break;d--}return 0},_process:function(a){var b=this._tileToTileMap(a.tile);this._getTileMap(b).then(function(b){var d=a.tile,f=this._parentTile(d);b.isTileAvailable(d.row,d.col)?a.callback.call(this,d,a.requestedTile):0<a.resamplingBudget&&f?(a.resamplingBudget--,a.tile=f,
this._process(a)):a.callback.call(this,a.requestedTile,a.requestedTile)}.bind(this),function(){a.callback.call(this,a.requestedTile,a.requestedTile)}.bind(this))},_getTileMap:function(a){this._tileMapCache[a.id]?(a=this._tileMapCache[a.id],a=a.promise):(this._tileMapCache[a.id]=a,a=this.getTileMap(a));return a},_parentTile:function(a){var b=this.layer.tileInfo.lods,c,d,f=null;n.some(b,function(b,f){return a.level===b.level?(c=b,d=f,!0):!1});0<d&&(b=b[d-1],f=new l(b.level,Math.floor(a.row*c.resolution/
b.resolution+0.01),Math.floor(a.col*c.resolution/b.resolution+0.01)));return f},_tileToTileMap:function(a){return new h(a.level,Math.floor(a.row/this.width)*this.width,Math.floor(a.col/this.height)*this.height,this.width,this.height)},_getTileMapUrl:function(a,b,c,d,f){var e=this.layer,g=e.tileServers,h=e.parsedUrl,e=e.token,k=h.query;a=[g&&g.length?g[b%g.length]:h.path,"tilemap",a,b,c,d,f].join("/");k&&(a+="?"+p.objectToQuery(k));if(e&&(!k||!k.token))a+=(-1===a.indexOf("?")?"?":"\x26")+"token\x3d"+
e;return r.addProxy(a)},_getResamplingBudget:function(){var a=this.layer,b=0;a.resampling&&(b=a.tileInfo.lods.length);return b}});g.TileMapData=h;return g});