// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require dojo/_base/url dojo/Deferred ../../config ../../kernel ../../core/declare ../../core/urlUtils ../../core/promiseUtils ../../core/requireUtils ../../request ./VectorTileTokenHandler".split(" "),function(q,r,s,t,l,n,g,u,v,m,w){var p=n(String,{constructor:function(a,b){this.value=a;this.token=b},valueOf:function(){var a=this.value,b=this.token;b||(b=(b=l.id&&l.id.findCredential(a))&&b.token||null);b&&(a+=(-1===a.indexOf("?")?"?":"\x26")+"token\x3d"+b);return a},toString:function(){return this.valueOf()},
replace:function(a,b){return String.prototype.replace.call(this.valueOf(),a,b)}}),k=n([],{loadMetadata:function(a,b,c){var d=null,f=c&&c.credential;return u.resolve(a).then(function(){return this._vectorTile?this._vectorTile:v.when(q,"../../views/2d/layers/vector-tile")}.bind(this)).then(function(c){this._vectorTile=c;this._vectorTile.config.ACCESS_TOKEN=b;this._vectorTile.tokenHandler?c=this._vectorTile.tokenHandler:(c=new w,this._vectorTile.tokenHandler=c);f&&c.addCredential(f);if("string"!==typeof a)return a;
if(d=k.isMapboxUrl(a)?this._vectorTile.normalizeStyleURL(a,b):g.normalize(a).replace(/\/*$/,""))return this._corsify(d),m(this._appendToken(d,f),{query:{f:"json"},responseType:"json"}).then(function(a){return a.data})}.bind(this)).then(function(a){return this._processMetadata(d,a,c)}.bind(this)).then(function(a){return this._loadStyle(a,c)}.bind(this))},_configureStyle:function(a,b){var c=a.layerDefinition,d=a.style,f=a.serviceUrl,e=a.styleUrl;if(c&&d&&d.sources.esri){var h=c.tilejson||"2.0.0",g=
c.tileInfo&&c.tileInfo.format||"pbf",k=c.tileMap?this._getAbsolutePath(c.tileMap,f):null,l=(c.tiles||[]).map(function(a){return new p(this._getAbsolutePath(a.valueOf(),f),b&&b.credential&&b.credential.token)}.bind(this));d.sources.esri={type:"vector",scheme:"xyz",tilejson:h,format:g,index:k,tiles:l,description:c.description,name:c.name};d.glyphs=this._corsify(this._getAbsolutePath(d.glyphs,e));d.sprite=this._corsify(this._getAbsolutePath(d.sprite,e))}return{style:d,layerDefinition:c,serviceUrl:f,
styleUrl:e}},_loadStyle:function(a,b){var c=new s,d=a.style.sources;b&&b.tileServers&&Object.getOwnPropertyNames(d).forEach(function(c){c=d[c];var e=b.tileServers.map(function(c){return new p(this._getAbsolutePath(c,a.serviceUrl,b))}.bind(this));c.tiles=e;e.forEach(this._corsify)}.bind(this));this._vectorTile.identityManager=l.id;c.resolve(a);return c.promise},_processMetadata:function(a,b,c){var d,f,e,h,g=c&&c.credential;if(b&&b.currentVersion)return d=b,e=a,h=this._getAbsolutePath(b.defaultStyles,
e),this._corsify(h),m(this._appendToken(h,g),{query:{f:"json"},responseType:"json"}).then(function(a){f=a.data;return this._configureStyle({style:f,layerDefinition:d,styleUrl:h,serviceUrl:e},c)}.bind(this));f=b;h=a;return b&&b.sources&&b.sources.esri&&b.sources.esri.url?(e=this._getAbsolutePath(b.sources.esri.url,h),this._corsify(e),m(this._appendToken(e,g),{query:{f:"json"},responseType:"json"}).then(function(a){d=a.data;return this._configureStyle({style:f,layerDefinition:d,styleUrl:h,serviceUrl:e},
c)}.bind(this))):this._configureStyle({style:f,styleUrl:h})},_appendToken:function(a,b){return!b||!b.token||-1!==a.indexOf("token\x3d")?a:a+=(-1===a.indexOf("?")?"?":"\x26")+"token\x3d"+b.token},_corsify:function(a){a=a.valueOf();var b=t.request.corsEnabledServers;if(!g.canUseXhr(a)){var c=new r(a),c=(c.host+(c.port?":"+c.port:"")).toLowerCase();-1===b.indexOf(c)&&b.push(c)}return a},_getAbsolutePath:function(a,b){var c;b=g.urlToObject(b||"").path;if(/^https?:\/\//i.test(a))c=a;else{if(0===a.indexOf("//"))return location.protocol+
a;b=b.replace(/(\/+\w+\.\w+)$/,"");/\/+$/.test(b)||(b+="/");0===a.indexOf("/")&&(a=a.substring(1));c=b+a}return g.normalize(c)}});k.isMapboxUrl=function(a){return-1<a.search(/^mapbox:\/\/styles\//)};k.getCredentialFromUrl=function(a){var b;"string"===typeof a&&!k.isMapboxUrl(a)&&(a=g.urlToObject(a),a.query&&a.query.token&&(b={url:a.path,token:a.query.token}));return b};return k});