// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports dojo/has ../Renderer ../SimpleRenderer ../UniqueValueRenderer ../../symbols/support/jsonUtils ../../core/urlUtils ../../core/promiseUtils ../../core/Error ../../request ../../portal/PortalQueryParams".split(" "),function(G,k,l,v,w,x,y,z,f,e,h,m){function n(a){return!a?!1:a.styleUrl||a.styleName?"renderer":a.symbol&&a.symbol.type&&"styleSymbolReference"===a.symbol.type?"symbol":!1}function p(a){A(a);(l("ie")||l("trident"))&&B(a);return y.fromJSON(a)}function g(a){return a="https:"===
location.protocol?a.replace(/^http:/,"https:"):a.replace(/^https:/,"http:")}function q(a,c){if(a.symbolLayers)for(var b=0;b<a.symbolLayers.length;b++){var d=a.symbolLayers[b];d.resource&&(d=d.resource,d.href&&(d.href=c(d.href)))}}function A(a){q(a,function(a){return g(z.fixUrl(a))})}function B(a){q(a,function(a){return-1!==a.indexOf(".svg",a.length-4)?(a.slice(0,a.length-4)+".png").replace("/resource/","/resource/png/"):a})}function r(a){return h(g(a),{query:{f:"json"},responseType:"json"}).then(function(a){return a.data})}
function s(a,c){return!c?f.reject(e("layer-templates:portal-missing","A portal is required to query styles, but non was provided")):c.load().then(function(){if(!c.stylesGroupQuery)throw e("layer-templates:styles-group-query-missing","The styles group query needs to be configured in the portal to query styles");var a=new m({disableExtraQuery:!0,query:c.stylesGroupQuery});return c.queryGroups(a)}).then(function(b){b=b.results;if(!b||!Array.isArray(b)||0===b.length)throw e("layer-templates:styles-missing",
"The styles group does not contain any styles");b=b[0];var c=new m({disableExtraQuery:!0,query:'typekeywords:"'+a+'"'});return b.queryItems(c)}).then(function(b){b=b.results;if(!b||!Array.isArray(b)||0===b.length)throw e("layer-templates:style-missing","The style '${styleName}' is not part of the styles group",{styleName:a});return b[0].load()}).then(function(a){return a.fetchData()})}function C(a){return!a.symbolSetUrl?f.reject(e("layer-templates:symbol-set-url-missing","Style does not provide symbol set url",
{style:a})):h(g(a.symbolSetUrl),{query:{f:"json"},responseType:"json"}).then(function(c){c=c.data;if(0===c.length||!c[0].name)throw e("layer-templates:symbol-set-missing-data","Invalid syntax or missing data in symbol set",{style:a});for(var b={},d=0;d<c.length;d++){var t=p(c[d]);b[c[d].name]=t;c[d].name===a.defaultItem&&(b.defaultSymbol=t)}b.defaultSymbol||(b.defaultSymbol=b[c[0].name]);return b})}function D(a,c){for(var b=0;b<a.items.length;b++)if(a.items[b].name===c)return h(g(a.items[b].webRef),
{query:{f:"json"},responseType:"json"}).then(function(a){return p(a.data)});return f.reject(e("layer-templates:symbol-name-not-found","The symbol name '${symbolName}' could not be found",{symbolName:c}))}function u(a,c){var b=v.fromJSON(a);b.sizeInfo&&(c.sizeInfo=b.sizeInfo);b.colorInfo&&(c.colorInfo=b.colorInfo);b.visualVariables&&(c.visualVariables=b.visualVariables);return c}function E(a,c){var b=a.symbol;if(!b.name)return f.reject(e("layer-templates:style-symbol-reference-name-missing","Missing name in style symbol reference"));
var d;if(b.styleUrl)d=r(b.styleUrl);else if(b.styleName)d=s(b.styleName,c);else return f.reject(e("layer-templates:style-url-and-name-missing","Either styleUrl or styleName is required in layerDefinition"));return d.then(function(a){return D(a,b.name)}).then(function(b){b=new w({symbol:b});return u(a,b)})}function F(a,c){var b;if(a.styleUrl)b=r(a.styleUrl);else if(a.styleName)b=s(a.styleName,c);else return f.reject(e("layer-templates:style-symbol-reference-name-missing","Missing name in style symbol reference"));
return b.then(function(a){return C(a)}).then(function(b){var c=new x({defaultSymbol:a.defaultSymbol&&b[a.defaultSymbol.name]?b[a.defaultSymbol.name]:b.defaultSymbol,field:a.field1}),e;for(e in b)b.hasOwnProperty(e)&&c.addUniqueValueInfo(e,b[e]);return u(a,c)})}k.hasContentByReference=n;k.createRenderer=function(a,c){var b=n(a);return"renderer"===b?F(a,c):"symbol"===b?E(a,c):f.resolve(null)}});