// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["dojo/_base/array","dojo/_base/lang","../Color"],function(s,u,e){function t(a,b){var c,d,h;if(a)switch(c={},b){case "point":c.color=new e(a.color);c.noDataColor=new e(a.noDataColor);c.outline={color:new e(a.outline.color),width:a.outline.width};c.size=a.size;c.noDataSize=a.noDataSize;c.minSize=a.minSize;c.maxSize=a.maxSize;break;case "polyline":c.color=new e(a.color);c.noDataColor=new e(a.noDataColor);c.width=a.width;c.noDataWidth=a.noDataWidth;c.minWidth=a.minWidth;c.maxWidth=a.maxWidth;
break;case "polygon":d=a.marker,h=a.background,c.marker={color:new e(d.color),noDataColor:new e(d.noDataColor),outline:{color:new e(d.outline.color),width:d.outline.width},size:d.size,noDataSize:d.noDataSize,minSize:d.minSize,maxSize:d.maxSize},c.background={color:new e(h.color),outline:{color:new e(h.outline.color),width:h.outline.width}}}return c}function m(a){var b;a&&(b=u.mixin({},a),b.color&&(b.color=new e(b.color)),b.noDataColor&&(b.noDataColor=new e(b.noDataColor)),b.outline&&(b.outline={color:b.outline.color&&
new e(b.outline.color),width:b.outline.width}));return b}var n=[128,128,128,1],p=[128,128,128,1],f=[128,128,128,0.8],g=[128,128,128,0.8],f={primary:{color:[227,139,79,0.8],noDataColor:f,outline:{color:[255,255,255,1],width:1},noDataSize:4,size:12,minSize:8,maxSize:50},secondary:[{color:[128,128,128,0.8],noDataColor:f,outline:{color:[255,255,255,1],width:1},noDataSize:4,size:12,minSize:8,maxSize:50},{color:[255,255,255,0.8],noDataColor:f,outline:{color:[128,128,128,1],width:1},noDataSize:4,size:12,
minSize:8,maxSize:50}]},g={primary:{color:[227,139,79,0.8],noDataColor:g,outline:{color:[51,51,51,1],width:1},noDataSize:4,size:12,minSize:8,maxSize:50},secondary:[{color:[178,178,178,0.8],noDataColor:g,outline:{color:[51,51,51,1],width:1},noDataSize:4,size:12,minSize:8,maxSize:50},{color:[26,26,26,0.8],noDataColor:g,outline:{color:[128,128,128,1],width:1},noDataSize:4,size:12,minSize:8,maxSize:50}]},k={r:0,g:0,b:0,a:0},q={color:k,outline:{color:{r:166,g:166,b:166,a:1},width:1}},k={color:k,outline:{color:{r:166,
g:166,b:166,a:1},width:1}},l={"default":{name:"default",label:"Default",description:"Default theme for visualizing features by varying their size to show data.",basemapGroups:{light:"streets gray topo terrain national-geographic oceans osm".split(" "),dark:["satellite","hybrid","dark-gray"]},pointSchemes:{light:f,dark:g},lineSchemes:{light:{primary:{color:[226,119,40,1],noDataColor:n,noDataWidth:1,width:1,minWidth:1,maxWidth:18},secondary:[{color:[77,77,77,1],noDataColor:n,noDataWidth:1,width:1,minWidth:1,
maxWidth:18},{color:[153,153,153,1],noDataColor:n,noDataWidth:1,width:1,minWidth:1,maxWidth:18}]},dark:{primary:{color:[226,119,40,1],noDataColor:p,noDataWidth:1,width:1,minWidth:1,maxWidth:18},secondary:[{color:[255,255,255,1],noDataColor:p,noDataWidth:1,width:1,minWidth:1,maxWidth:18},{color:[153,153,153,1],noDataColor:p,noDataWidth:1,width:1,minWidth:1,maxWidth:18}]}},polygonSchemes:{light:{primary:{marker:f.primary,background:k},secondary:[{marker:f.secondary[0],background:k},{marker:f.secondary[1],
background:k}]},dark:{primary:{marker:g.primary,background:q},secondary:[{marker:g.secondary[0],background:q},{marker:g.secondary[1],background:q}]}}}},r={};(function(){var a,b,c,d,h,e,f,g;for(a in l)for(d in b=l[a],c=b.basemapGroups,h=r[a]={basemaps:[].concat(c.light).concat(c.dark),point:{},polyline:{},polygon:{}},c){e=c[d];for(f=0;f<e.length;f++)g=e[f],b.pointSchemes&&(h.point[g]=b.pointSchemes[d]),b.lineSchemes&&(h.polyline[g]=b.lineSchemes[d]),b.polygonSchemes&&(h.polygon[g]=b.polygonSchemes[d])}})();
return{getAvailableThemes:function(a){var b=[],c,d,e;for(c in l)d=l[c],e=r[c],a&&-1===s.indexOf(e.basemaps,a)||b.push({name:d.name,label:d.label,description:d.description,basemaps:e.basemaps.slice(0)});return b},getSchemes:function(a){var b=a.basemap,c=a.geometryType;a=r[a.theme];var d;(a=(a=a&&a[c])&&a[b])&&(d={primaryScheme:t(a.primary,c),secondarySchemes:s.map(a.secondary,function(a){return t(a,c)})});return d},cloneScheme:function(a){var b;a&&(b=m(a),b.marker&&(b.marker=m(b.marker)),b.background&&
(b.background=m(b.background)));return b}}});