// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/declare ../../../core/Accessor ../../../layers/support/LOD".split(" "),function(k,l,r,g,d,s,t){k=function(k){function a(){k.apply(this,arguments);this._lodByScale={};this._scales=[];this.effectiveLODs=null;this.effectiveMaxZoom=this.effectiveMinZoom=-1;this.effectiveMaxScale=this.effectiveMinScale=0;this.enabled=!0;this.lods=null;this.maxZoom=this.minZoom=-1;this.maxScale=
this.minScale=0;this.snapToZoom=!0}r(a,k);a.prototype.initialize=function(){var h=this,b=this.lods,c=this.minScale,e=this.maxScale,a=this.minZoom,f=this.maxZoom,d=-1,g=-1,k=!1,l=!1;0!==c&&(0!==e&&c<e)&&(e=[e,c],c=e[0],e=e[1]);if(b&&b.length){b=b.map(function(b){return b.clone()});b.sort(function(b,h){return h.scale-b.scale});b.forEach(function(b,h){return b.level=h});for(var n,p=0,q=b;p<q.length;p++){var m=q[p];!k&&(0<c&&c>=m.scale)&&(d=m.level,k=!0);!l&&(0<e&&e>=m.scale)&&(g=n?n.level:-1,l=!0);n=
m}-1===a&&(a=0===c?0:d);-1===f&&(f=0===e?b.length-1:g);a=Math.max(a,0);a=Math.min(a,b.length-1);f=Math.max(f,0);f=Math.min(f,b.length-1);a>f&&(c=[f,a],a=c[0],f=c[1]);c=b[a].scale;e=b[f].scale;b.splice(0,a);b.splice(f-a+1,b.length);b.forEach(function(b,a){h._lodByScale[b.scale]=b;h._scales[a]=b.scale});this._set("effectiveLODs",b);this._set("effectiveMinZoom",a);this._set("effectiveMaxZoom",f)}this._set("effectiveMinScale",c);this._set("effectiveMaxScale",e)};a.prototype.constrain=function(h,b,a){if(!this.enabled||
b&&h.scale===b.scale)return h;var e=this.effectiveMinScale,d=this.effectiveMaxScale;a=h.targetGeometry;var f=b&&b.targetGeometry,g=0!==e&&h.scale>e;if(0!==d&&h.scale<d||g)e=g?e:d,f&&(b=(e-b.scale)/(h.scale-b.scale),a.x=f.x+(a.x-f.x)*b,a.y=f.y+(a.y-f.y)*b),h.scale=e;this.snapToZoom&&this.effectiveLODs&&(h.scale=this._getClosestScale(h.scale));return h};a.prototype.zoomToScale=function(a){if(!this.effectiveLODs)return 0;a-=this.effectiveMinZoom;a=Math.max(0,a);var b=this._scales;if(0>=a)return b[0];
if(a>=b.length)return b[b.length-1];var c=Math.round(a-0.5),e=Math.round(a);return b[e]+(e-a)*(b[c]-b[e])};a.prototype.scaleToZoom=function(a){if(!this.effectiveLODs)return-1;var b=this._scales,c=0,e=b.length-1,d,f;for(c;c<e;c++){d=b[c];f=b[c+1];if(d<=a)return c+this.effectiveMinZoom;if(f===a)return c+1+this.effectiveMinZoom;if(d>a&&f<a)return c+1-(a-f)/(d-f)+this.effectiveMinZoom}return c};a.prototype.snapScale=function(a,b){void 0===b&&(b=0.95);if(!this.effectiveLODs)return a;var c=this.scaleToZoom(a);
return(c+1)%Math.floor(c+1)>=b?this.zoomToScale(Math.ceil(c)):this.zoomToScale(Math.floor(c))};a.prototype.clone=function(){return new a({enabled:this.enabled,lods:this.lods,minZoom:this.minZoom,maxZoom:this.maxZoom,minScale:this.minScale,maxScale:this.maxScale})};a.prototype._getClosestScale=function(a){if(this._lodByScale[a])return this._lodByScale[a].scale;a=this._scales.reduce(function(b,c,d,g){return Math.abs(c-a)<=Math.abs(b-a)?c:b},this._scales[0]);return this._lodByScale[a].scale};g([d.shared("esri.views.2d.constraints.ZoomConstraint")],
a.prototype,"declaredClass",void 0);g([d.property({readOnly:!0})],a.prototype,"effectiveLODs",void 0);g([d.property({readOnly:!0})],a.prototype,"effectiveMinZoom",void 0);g([d.property({readOnly:!0})],a.prototype,"effectiveMaxZoom",void 0);g([d.property({readOnly:!0})],a.prototype,"effectiveMinScale",void 0);g([d.property({readOnly:!0})],a.prototype,"effectiveMaxScale",void 0);g([d.property()],a.prototype,"enabled",void 0);g([d.property({type:[t]})],a.prototype,"lods",void 0);g([d.property()],a.prototype,
"minZoom",void 0);g([d.property()],a.prototype,"maxZoom",void 0);g([d.property()],a.prototype,"minScale",void 0);g([d.property()],a.prototype,"maxScale",void 0);g([d.property()],a.prototype,"snapToZoom",void 0);return a=g([d.subclass()],a)}(d.declared(s));Object.defineProperty(l,"__esModule",{value:!0});l.default=k});