// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/tsSupport/declare ./Layer ./FeatureLayer ./support/Field ./support/LabelClass ./mixins/PortalLayer ../PopupTemplate ../request ../core/lang ../core/jsonDictionary ../core/MultiOriginJSONSupport ../core/urlUtils ../core/requireUtils ../core/promiseUtils ../core/Error ../geometry/Extent ../geometry/SpatialReference ../renderers/support/jsonUtils ../portal/PortalItem dojo/_base/lang dojo/io-query dojo/promise/all ./support/arcgisLayerURL".split(" "),
function(n,J,w,e,b,x,p,y,z,A,B,h,C,D,E,g,q,k,r,f,m,F,G,s,t,u,l){var H=D({onTheGround:"on-the-ground",relativeToGround:"relative-to-ground",absoluteHeight:"absolute-height"}),I={"features-points":"esriGeometryPoint","features-lines":"esriGeometryPolyline","features-polygons":"esriGeometryPolygon"};return function(v){function a(c,d){v.call(this);this.copyright=null;this.popupEnabled=!0;this.layerId=null;this.version={major:0,minor:0,versionString:""};this.elevationInfo=this.fullExtent=this.fields=null;
this.labelsVisible=!1;this.labelingInfo=null;this.legendEnabled=!0;this.renderer=null;this.cachedDrawingInfo={color:!1};this.objectIdField=this.popupTemplate=this.spatialReference=null;this.titleIncludesUrl=!0;this.blendMode=this.title=null;this._alreadyIssuedWarnings={};this._canUseXhr=null;this._addTrailingSlash=!1;this._popupSource={popupEnabled:"none",popupTemplate:"none"}}w(a,v);a.prototype.normalizeCtorArgs=function(c,d){return"string"===typeof c?s.mixin({},{url:c},d):c};a.prototype.readCopyright=
function(c,d){return d.copyrightText};a.prototype.readPopupEnabled=function(c,d){return null!=d.disablePopup?(this._popupSource.popupEnabled="service",!d.disablePopup):!0};a.prototype.readLayerId=function(c,d){return d.id};a.prototype.readVersion=function(c,d){var a=d.store;if("string"===typeof a.version){var a={major:0,minor:0,versionString:a.version},b=a.versionString.split(".");2<=b.length&&(a.major=parseInt(b[0],10),a.minor=parseInt(b[1],10));return a}return null};a.prototype.readFields=function(c){this._fieldsSource=
"service";return c.map(y.fromJSON)};a.prototype.readFullExtent=function(c,d){var a=d.store,b=a.indexCRS||a.geographicCRS,b=b&&parseInt(b.substring(b.lastIndexOf("/")+1,b.length),10);return null==a||null==a.extent?null:new f({xmin:a.extent[0],ymin:a.extent[1],xmax:a.extent[2],ymax:a.extent[3],spatialReference:b})};a.prototype.readElevationInfo=function(c){c=C.clone(c);c.mode=H.fromJSON(c.mode);return c};Object.defineProperty(a.prototype,"geometryType",{get:function(){return I[this.profile]||"esriGeometryMesh"},
enumerable:!0,configurable:!0});a.prototype.readLabelsVisible=function(c,d){return d.showLabels};a.prototype.readLabelingInfo=function(c,d){var a=this;c=d.drawingInfo.labelingInfo;if(!c)return null;var b=/\[([^\[\]]+)\]/ig;return c.map(function(c){c=z.fromJSON(c);var d=c.labelExpression;d&&(c.labelExpression=d.replace(b,function(c,d){var b=a.getField(d);return"["+(b&&b.name||d)+"]"}));return c})};a.prototype.readLegendEnabled=function(c,d){return null!=d.showLegend?d.showLegend:!0};a.prototype.readRenderer=
function(c,d){(c=d.drawingInfo.renderer)&&(c=F.fromJSON(c));return c};a.prototype.readCachedDrawingInfo=function(c,d){if(null==c||"object"!==typeof c)c={};null==c.color&&(c.color=!1);return c};a.prototype.readSpatialReference=function(c,d){if(null!=d.spatialReference)return m.fromJSON(d.spatialReference);var a=d.store,a=(a=a.indexCRS||a.geographicCRS)&&parseInt(a.substring(a.lastIndexOf("/")+1,a.length),10);return null!=a?new m(a):null};Object.defineProperty(a.prototype,"url",{set:function(c){var a=
g.urlToObject(c),b=l.parse(a.path);b&&null!=b.sublayer&&(this.layerId=b.sublayer,a=t.objectToQuery(a.query),c=b.url.path,a&&(c=c+"?"+a));this._set("url",c)},enumerable:!0,configurable:!0});a.prototype.readPopupTemplate=function(c,a){a.popupInfo&&(this._popupSource.popupTemplate="service");return a.popupInfo&&B.fromJSON(a.popupInfo)};a.prototype.readObjectIdField=function(c,a){!c&&a.fields&&a.fields.some(function(a){"esriFieldTypeOID"===a.type&&(c=a.name);return!!c});return c};a.prototype.readProfile=
function(c,a){return a.store.profile};a.prototype.readRootNode=function(c,a){return a.store.rootNode};a.prototype.readTitle=function(c,a){if(null!=c)return c;var b=[];if(this.titleIncludesUrl){var e=l.parse(this.parsedUrl.path);e&&e.title&&b.push(e.title)}a.name&&(e=l.cleanTitle(a.name),(0===b.length||-1===b[0].toLowerCase().indexOf(e.toLowerCase()))&&b.push(e));return b.join(" - ")};Object.defineProperty(a.prototype,"parsedUrl",{get:function(){var c=this._get("url");if(!c)return null;c=g.urlToObject(c);
null!=this.layerId&&l.match.test(c.path)&&(c.path=c.path+"/layers/"+this.layerId);return c},enumerable:!0,configurable:!0});a.prototype.load=function(){var c=this,a=this.loadFromPortal(function(){return c._fetchService()}).then(function(){return u([c._verifyRootNode(),c._setCompanionFeatureLayer()])});this.addResolvingPromise(a);return this};a.prototype.createGraphicsController=function(c){var a=this;c.layer=this;c.addUrlTokenFunction=this._addUrlToken.bind(this);c.warningEvent=this.warningEvent.bind(this);
var b=q.when(n,"./graphics/controllers/I3SOnDemandController").then(function(a){return new a(c)});b.then(function(c){a.emit("graphics-controller-create",{graphicsController:c})});return b};a.prototype.createLayerView=function(c){var a=this,b=this.profile||"features-meshes";return q.when(n,"features-meshes"===b||"meshpyramids"===b?"../views/3d/layers/SceneLayerView3D":"../views/3d/layers/SceneLayerGraphicsView3D").then(function(b){return new b({view:c,layer:a})})};a.prototype.getField=function(a){return!this.companionFeatureLayer?
void 0:this.companionFeatureLayer.getField(a)};a.prototype.warningEvent=function(a,d){null==this._alreadyIssuedWarnings[a]&&(this._alreadyIssuedWarnings[a]=!0,this.emit("i3s-load-log",{type:1===d?"fatal":"warning",msg:a}),console.warn("i3s-load-log warningEvent severity "+d," message "+a))};a.prototype._readExtent=function(a){a=a.store;var d=a.indexCRS||a.geographicCRS,d=d&&parseInt(d.substring(d.lastIndexOf("/")+1,d.length),10);return null==a||null==a.extent?new f:new f({xmin:a.extent[0],ymin:a.extent[1],
xmax:a.extent[2],ymax:a.extent[3],spatialReference:d})};a.prototype._addUrlToken=function(a){var d=s.mixin({},this.parsedUrl.query,{token:this.token}),d=t.objectToQuery(d);a+=d?"?"+d:"";null==this._canUseXhr&&(this._canUseXhr=g.canUseXhr(a));return!this._canUseXhr?g.addProxy(a):a};a.prototype._fetchService=function(){var a=this;return null==this.layerId&&/SceneServer\/*$/i.test(this.url)?h(this._addUrlToken(this.url),{query:{f:"json"},responseType:"json"}).then(function(d){d.data&&(Array.isArray(d.data.layers)&&
0<d.data.layers.length)&&(a.layerId=d.data.layers[0].id);return a._fetchServiceLayer()}):this._fetchServiceLayer()};a.prototype._fetchServiceLayer=function(){var a=this;return h(this._addUrlToken(this.parsedUrl.path),{responseType:"json"}).then(function(d){d.ssl&&(a.url=a.url.replace(/^http:/i,"https:"));d=d.data;var b=d.store;null==b.indexCRS&&null==b.geographicCRS&&a.warningEvent("Input data invalid: layer.layerInfo.indexCRS is undefined.",1);a.read(d);if(1!==a.version.major)throw new r("scenelayer:version-not-supported",
"SceneLayer version is not supported.",{serviceVersion:b.serviceVersion,url:a.parsedUrl.path});})};a.prototype._verifyRootNode=function(){if(-1!==["meshpyramids","features-points"].indexOf(this.profile)){var a=g.join(this.parsedUrl.path,this.rootNode);return h(this._addUrlToken(a),{query:{f:"json"},responseType:"json"}).then(function(a){return a.data}).otherwise(function(d){throw new r("scenelayer:root-node-missing","Root node missing.",{error:d,url:a});})}};a.prototype._setCompanionFeatureLayer=
function(){var a=this;return this._fetchCompanionFeatureLayer().then(function(d){if(a.companionFeatureLayer=d)d.fields&&!a.fields&&a.__accessor__.setDefault("fields",d.fields.slice()),null!=d.popupTemplate&&("portal"!==a._popupSource.popupTemplate&&("portal"===d._popupSource.popupTemplate||"service"!==a._popupSource.popupTemplate))&&a.__accessor__.setDefault("popupTemplate",d.popupTemplate),null!=d.popupEnabled&&("portal"!==a._popupSource.popupEnabled&&("portal"===d._popupSource.popupEnabled||"service"!==
a._popupSource.popupEnabled))&&a.__accessor__.setDefault("popupEnabled",!!d.popupEnabled)})};a.prototype._fetchCompanionFeatureLayer=function(){var a=this;return-1===["meshpyramids","features-points"].indexOf(this.profile)?k.resolve(null):(this.portalItem&&this.portalItem.isResolved()?this._fetchCompanionFeatureLayerFromRelatedItems(this.portalItem):this._fetchCompanionFeatureLayerFromUrl()).then(function(a){a._popupSource={popupEnabled:null,popupTemplate:null};return a.load()}).otherwise(function(b){console.warn("Companion FeatureLayer could not be loaded. Popups will not work for this SceneLayer: "+
a.title);return null})};a.prototype._fetchCompanionFeatureLayerFromRelatedItems=function(a){var b=this;return a.fetchRelatedItems({relationshipType:"Service2Data",direction:"forward"}).then(function(a){return(a=a.filter(function(a){return"Feature Service"===a.type})[0])?b._fetchCompanionFeatureLayerFromPortalItem(new G({id:a.id,portal:a.portal})):b._fetchCompanionFeatureLayerFromUrl()})};a.prototype._fetchCompanionFeatureLayerFromPortalItem=function(a){var b=this;return a.load().then(function(a){return b._findMatchingCompanionSublayerUrl(a.url)}).then(function(b){return k.resolve(new p({url:b,
portalItem:a}))})};a.prototype._fetchCompanionFeatureLayerFromUrl=function(){return this._findMatchingCompanionSublayerUrl().then(function(a){return k.resolve(new p({url:a}))})};a.prototype._findMatchingCompanionSublayerUrl=function(a){var b=this.parsedUrl.path.match(/^(.*)\/SceneServer\/layers\/([\d]*)\/?$/i);if(!b)return k.reject();null==a&&(a=b[1]+"/FeatureServer");var e=a.replace(/^(.*FeatureServer)(\/[\d]*\/?)?$/i,"$1");a={query:{f:"json"},responseType:"json"};var g=b[1]+"/SceneServer",f=parseInt(b[2],
10),b=h(this._addUrlToken(g),a).otherwise(function(a){return{layers:null}});a=h(this._addUrlToken(e),a);return u([a,b]).then(function(a){var b=a[0];a=a[1];a=a.data&&a.data.layers;b=b.data&&b.data.layers;if(!Array.isArray(b))throw Error("expected layers array");if(Array.isArray(a))for(var c=0;c<Math.min(a.length,b.length);c++){if(a[c].id===f)return e+"/"+b[c].id}else if(f<b.length)return e+"/"+b[f].id;throw Error("could not find matching companion sublayer");})};e([b.shared("esri.layers.SceneLayer")],
a.prototype,"declaredClass",void 0);e([b.shared("portal/loaders/SceneLayerLoader")],a.prototype,"portalLoaderModule",void 0);e([b.shared({id:{json:{ignore:!0}}})],a.prototype,"properties",void 0);e([b.property({type:String})],a.prototype,"copyright",void 0);e([b.read("copyright",["copyrightText"])],a.prototype,"readCopyright",null);e([b.property({type:Boolean})],a.prototype,"popupEnabled",void 0);e([b.read("popupEnabled",["disablePopup"])],a.prototype,"readPopupEnabled",null);e([b.property({type:Number})],
a.prototype,"layerId",void 0);e([b.read("layerId",["id"])],a.prototype,"readLayerId",null);e([b.property({readOnly:!0})],a.prototype,"version",void 0);e([b.read("version",["store.version"])],a.prototype,"readVersion",null);e([b.property()],a.prototype,"fields",void 0);e([b.read("fields")],a.prototype,"readFields",null);e([b.property({readOnly:!0})],a.prototype,"attributeStorageInfo",void 0);e([b.property({type:f})],a.prototype,"fullExtent",void 0);e([b.read("fullExtent",["store.indexCRS","store.geographicCRS"])],
a.prototype,"readFullExtent",null);e([b.property()],a.prototype,"elevationInfo",void 0);e([b.read("elevationInfo")],a.prototype,"readElevationInfo",null);e([b.property({type:String,dependsOn:["profile"]})],a.prototype,"geometryType",null);e([b.property({type:Boolean})],a.prototype,"labelsVisible",void 0);e([b.read("labelsVisible",["showLabels"])],a.prototype,"readLabelsVisible",null);e([b.property()],a.prototype,"labelingInfo",void 0);e([b.read("labelingInfo",["drawingInfo.labelingInfo"])],a.prototype,
"readLabelingInfo",null);e([b.property({type:Boolean})],a.prototype,"legendEnabled",void 0);e([b.read("legendEnabled",["showLegend"])],a.prototype,"readLegendEnabled",null);e([b.property()],a.prototype,"renderer",void 0);e([b.read("renderer",["drawingInfo.renderer"])],a.prototype,"readRenderer",null);e([b.property()],a.prototype,"cachedDrawingInfo",void 0);e([b.read("cachedDrawingInfo")],a.prototype,"readCachedDrawingInfo",null);e([b.property({type:m})],a.prototype,"spatialReference",void 0);e([b.read("spatialReference",
["spatialReference","store.indexCRS","store.geographicCRS"])],a.prototype,"readSpatialReference",null);e([b.property()],a.prototype,"url",null);e([b.property()],a.prototype,"popupTemplate",void 0);e([b.read("popupTemplate",["popupInfo"])],a.prototype,"readPopupTemplate",null);e([b.property({type:String})],a.prototype,"objectIdField",void 0);e([b.read("objectIdField",["fields"])],a.prototype,"readObjectIdField",null);e([b.property({type:String})],a.prototype,"profile",void 0);e([b.read("profile",["store.profile"])],
a.prototype,"readProfile",null);e([b.property({type:String})],a.prototype,"rootNode",void 0);e([b.read("rootNode",["store.rootNode"])],a.prototype,"readRootNode",null);e([b.property({type:Boolean})],a.prototype,"titleIncludesUrl",void 0);e([b.property({type:String})],a.prototype,"title",void 0);e([b.read("title",["title","name"])],a.prototype,"readTitle",null);e([b.property({dependsOn:["layerId"]})],a.prototype,"parsedUrl",null);e([b.property()],a.prototype,"store",void 0);return a=e([b.subclass()],
a)}(b.declared(x,E,A))});