// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require dojo/_base/lang dojo/Deferred ../core/sniff ../core/Collection ../geometry/SpatialReference ./FeatureLayer".split(" "),function(g,c,h,f,l,k,m){return m.createSubclass({declaredClass:"esri.layers.StreamLayer",constructor:function(a,d){"WebSocket"in window||(this.loadError=Error("WebSocket is not supported in this browser"),console.log("WebSocket is not supported in this browser. StreamLayer will not have real-time connection with the stream service."))},normalizeCtorArgs:function(a,
d){return"string"===typeof a?c.mixin({},{url:a},d):a&&a.layerDefinition?c.mixin({},{collectionLayer:a},d):a},getDefaults:function(a){return c.mixin(this.inherited(arguments)||{},{purgeOptions:{displayCount:2E3},outFields:["*"]})},properties:{definitionExpression:{value:null,set:function(a){this.source?this._set("requestedDefinitionExpression",a):this._set("source",a)}},geometryDefinition:{value:null,set:function(a){a&&"extent"!==a.type?this.emit("error",new TypeError("Invalid geometry. It must have an extent")):
this.get("source")?this._set("requestedGeometryDefinition",a):this._set("geometryDefinition",a)}},maxReconnectAttempts:10,maximumTrackPoints:1,objectIdField:{json:{readFrom:["fields"],read:function(a,d){if(!a){var b=d.fields;b.some(function(b){"esriFieldTypeOID"===b.type&&(a=b.name);return!!a})}var e=1,c=[];if(!a){b.forEach(function(a){"objectid"===a.name.split("_")[0]&&c.push(a.name)});if(c.length)for(;-1!==c.indexOf("objectid_"+e);)e+=1;a="objectid_"+e}return a}}},portalLoaderModule:{get:function(){return"portal/loaders/StreamLayerLoader"}},
purgeOptions:{value:null,set:function(a){var d=this._get("purgeOptions"),b={},c=!1;if(a&&!("object"!==typeof a||d===a))if(a.hasOwnProperty("displayCount")&&0<a.displayCount&&(b.displayCount=a.displayCount,c=!0),a.hasOwnProperty("age")&&0<=a.age&&(b.age=a.age,c=!0),c)return this._set("purgeOptions",b)}},requestedDefinitionExpression:null,requestedGeometryDefinition:null,socketDirection:"subscribe",spatialReference:{value:null,type:k,json:{readFrom:["spatialReference"],read:function(a){return a&&k.fromJSON(a)}}}},
createGraphicsSource:function(){var a=new h;g(["./graphics/sources/StreamLayerSource"],c.hitch(this,function(d){var b=new d({layer:this});b.then(c.hitch(this,function(){this.emit("graphics-source-create",{graphicsSource:b});a.resolve(b)}),function(b){a.reject(b)})}));return a.promise},createGraphicsController:function(a){var d=new h,b=a.layerView,e=b.view.map.view===b.view?this.graphics:new l,f=c.mixin(a.options||{},{layer:this,layerView:b,graphics:e});g(["./graphics/controllers/StreamController"],
c.hitch(this,function(a){var b=new a(f);b.then(c.hitch(this,function(){this.emit("graphics-controller-create",{graphicsController:b});d.resolve(b)}),function(a){d.reject(a)})}));return d.promise},_initLayerProperties:function(a){this.source=a;a=a.layerDefinition;this.read(a);this.source.relatedFeaturesInfo&&(this.objectIdField=this.source.relatedFeaturesInfo.joinField);a._ssl&&(this.url=this.url.replace(this.reHttp,"https:"));this._verifyFields();this._fixSymbolUrls();this.useQueryTimestamp=f("ie")||
f("safari")},_verifyFields:function(){var a=this.parsedUrl&&this.parsedUrl.path||"undefined";this.objectIdField||console.log("StreamLayer: 'objectIdField' property is not defined (url: "+a+")")}})});