// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../config ../../core/Accessor ../../core/Error ../../core/Evented ../../core/promiseUtils ../../geometry/Point ../../geometry/support/webMercatorUtils ../../Graphic ../../symbols/PictureMarkerSymbol ../../tasks/GeometryService ../../tasks/support/ProjectParameters ../../portal/Portal dojo/_base/lang dojo/Deferred require".split(" "),function(k,l,d,m,f,n,p,q,r,s,t,u,g,h,v){return l.createSubclass([m],{properties:{geolocationOptions:{},goToLocationEnabled:{},graphic:{type:q},state:{dependsOn:["view.ready",
"tracking"],readOnly:!0},tracking:{readOnly:!0},view:{}},declaredClass:"esri.widgets.Track.TrackViewModel",getDefaults:function(){return g.mixin(this.inherited(arguments),{geolocationOptions:{maximumAge:0,timeout:15E3,enableHighAccuracy:!0},graphic:{}})},initialize:function(){navigator.geolocation?window.hasOwnProperty("isSecureContext")&&!window.isSecureContext&&(console.log(this.declaredClass,"navigator.geolocation requires a secure origin."),this._geolocationUsable=!1):(console.log(this.declaredClass,
"navigator.geolocation unsupported."),this._geolocationUsable=!1)},destroy:function(){this._clear();this._viewReady&&this._viewReady.cancel();this._stopWatchingPosition()},_geolocationUsable:!0,_watchId:null,_trackStartingTimeoutId:null,geolocationOptions:null,goToLocationEnabled:!0,graphic:null,_graphicSetter:function(a){a&&!a.symbol&&(a.symbol=new r({url:v.toUrl("./images/sdk_gps_location.png"),width:21,height:21}));this._set("graphic",a)},state:"disabled",_stateGetter:function(){return!this._geolocationUsable?
"feature-unsupported":!this.get("view.ready")?"disabled":this.tracking?"tracking":null!==this._trackStartingTimeoutId?"waiting":"ready"},tracking:!1,_trackingGetter:function(a){return null!==this._watchId},view:null,start:function(){"disabled"===this.state||this.tracking||this._startTracking()},stop:function(){"disabled"!==this.state&&this.tracking&&this._stopTracking()},_clear:function(){this.view&&this.view.graphics.remove(this.graphic)},_stopWatchingPosition:function(){null!==this._watchId&&(navigator.geolocation.clearWatch(this._watchId),
this._watchId=null);this.notifyChange("tracking");this._clearCurrentLocationVars()},_stopTracking:function(){this._stopWatchingPosition();this._clear()},_startTracking:function(){this._stopWatchingPosition();var a=navigator.geolocation.watchPosition(function(b){this._watchId=a;this.notifyChange("tracking");b=this._positionToObject(b);this._setPosition(b).then(function(){this.view.graphics.remove(this.graphic);this.graphic&&(this.graphic=this.graphic.clone(),this.view.graphics.push(this.graphic));
this.emit("track",{position:b})}.bind(this)).otherwise(function(a){a||(a=d(this.declaredClass,"Error setting the position."));this._emitError(a)}.bind(this)).always(function(){clearTimeout(this._trackStartingTimeoutId);this._trackStartingTimeoutId=null;this.notifyChange("state")}.bind(this))}.bind(this),function(a){a||(a=d(this.declaredClass,"Could not get tracking position."));this._emitError(a);clearTimeout(this._trackStartingTimeoutId);this._trackStartingTimeoutId=null;this.notifyChange("state")}.bind(this),
this.geolocationOptions);this._trackStartingTimeoutId=setTimeout(function(){this._trackStartingTimeoutId=null;this.notifyChange("state")}.bind(this),15E3);this.notifyChange("state")},_clearCurrentLocationVars:function(){this._scale=this._position=this._graphic=null},_positionToObject:function(a){return a?{coords:g.mixin({},a.coords),timestamp:a.timestamp}:{}},_getGeometryServiceUrl:function(){var a=new h,b=k.geometryServiceUrl;if(b)a.resolve(b);else{var c=u.getDefault();c.load().always(function(){b=
c.get("helperServices.geometry.url");a.resolve(b)})}return a.promise},_projectPoint:function(a){var b=new h,c=this.get("view.spatialReference");c.isWebMercator?b.resolve(p.geographicToWebMercator(a)):c.isWGS84?b.resolve(a):this._getGeometryServiceUrl().then(function(e){if(e){var w=new t({geometries:[a],outSR:c});(new s({url:e})).project(w).then(function(a){a&&a.length?b.resolve(a[0]):b.reject(d(this.declaredClass,"Point was not projected."))}.bind(this),b.reject)}else b.resolve(d(this.declaredClass,
"please specify a geometry service on esri/config to project."))});return b.promise},_getScale:function(a){a=a&&a.coords&&a.coords.accuracy;return this.scale||a||5E4},_createPoint:function(a){if(a=a&&a.coords)return new n({longitude:a.longitude,latitude:a.latitude,z:a.altitude||null,spatialReference:{wkid:4326}})},_animatePoint:function(a,b,c,e){this._graphic=e=this._createGraphic(a,b);return!this.goToLocationEnabled?f.resolve(b):this.view.goTo({target:a,scale:c}).then(function(){return b}.bind(this)).otherwise(function(a){a||
(a=d(this.declaredClass,"Could not center."));return a}.bind(this))},_setPosition:function(a){var b;this._clearCurrentLocationVars();this._position=a;var c=this._createPoint(a);c&&(this._graphic=b=this._createGraphic(c,a));var e=this._getScale(a);this._scale=e;return!c?f.reject(d(this.declaredClass,"Invalid point")):this._projectPoint(c).then(function(c){return this._animatePoint(c,a,e,b)}.bind(this)).otherwise(function(a){a||(a=d(this.declaredClass,"Error projecting point."));return a}.bind(this))},
_createGraphic:function(a,b){var c=this.graphic;if(a&&b&&c)return c.geometry=a,c},_emitError:function(a){this.emit("track-error",{error:a})}})});