// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
require({cache:{"esri/tasks/ImageServiceIdentifyResult":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../geometry/jsonUtils ./FeatureSet".split(" "),function(k,d,n,h,c,a){k=k(null,{declaredClass:"esri.tasks.ImageServiceIdentifyResult",constructor:function(e){e.catalogItems&&(this.catalogItems=new a(e.catalogItems));e.location&&(this.location=c.fromJson(e.location));this.catalogItemVisibilities=e.catalogItemVisibilities;this.name=e.name;this.objectId=e.objectId;this.value=
e.value;this.processedValues=e.processedValues;this.properties=e.properties}});n("extend-esri")&&d.setObject("tasks.ImageServiceIdentifyResult",k,h);return k})},"esri/layers/rasterFormats/LercCodec":function(){define([],function(){var k={defaultNoDataValue:-3.4027999387901484E38,decode:function(n,h){var c;h=h||{};var a=h.inputOffset||0,e=h.encodedMaskData||null===h.encodedMaskData,b={},f=new Uint8Array(n,a,10);b.fileIdentifierString=String.fromCharCode.apply(null,f);if("CntZImage"!=b.fileIdentifierString.trim())throw"Unexpected file identifier string: "+
b.fileIdentifierString;var a=a+10,g=new DataView(n,a,24);b.fileVersion=g.getInt32(0,!0);b.imageType=g.getInt32(4,!0);b.height=g.getUint32(8,!0);b.width=g.getUint32(12,!0);b.maxZError=g.getFloat64(16,!0);a+=24;if(!e)if(g=new DataView(n,a,16),b.mask={},b.mask.numBlocksY=g.getUint32(0,!0),b.mask.numBlocksX=g.getUint32(4,!0),b.mask.numBytes=g.getUint32(8,!0),b.mask.maxValue=g.getFloat32(12,!0),a+=16,0<b.mask.numBytes){var e=new Uint8Array(Math.ceil(b.width*b.height/8)),g=new DataView(n,a,b.mask.numBytes),
f=g.getInt16(0,!0),x=2,w=0;do{if(0<f)for(;f--;)e[w++]=g.getUint8(x++);else for(var u=g.getUint8(x++),f=-f;f--;)e[w++]=u;f=g.getInt16(x,!0);x+=2}while(x<b.mask.numBytes);if(-32768!==f||w<e.length)throw"Unexpected end of mask RLE encoding";b.mask.bitset=e;a+=b.mask.numBytes}else 0==(b.mask.numBytes|b.mask.numBlocksY|b.mask.maxValue)&&(e=new Uint8Array(Math.ceil(b.width*b.height/8)),b.mask.bitset=e);g=new DataView(n,a,16);b.pixels={};b.pixels.numBlocksY=g.getUint32(0,!0);b.pixels.numBlocksX=g.getUint32(4,
!0);b.pixels.numBytes=g.getUint32(8,!0);b.pixels.maxValue=g.getFloat32(12,!0);a+=16;e=b.pixels.numBlocksX;f=b.pixels.numBlocksY;e+=0<b.width%e?1:0;f+=0<b.height%f?1:0;b.pixels.blocks=Array(e*f);x=1E9;for(u=w=0;u<f;u++)for(var v=0;v<e;v++){var l=0,g=new DataView(n,a,Math.min(10,n.byteLength-a)),r={};b.pixels.blocks[w++]=r;var m=g.getUint8(0);l++;r.encoding=m&63;if(3<r.encoding)throw"Invalid block encoding ("+r.encoding+")";if(2===r.encoding)a++,x=Math.min(x,0);else{if(0!==m&&2!==m){m>>=6;r.offsetType=
m;if(2===m)r.offset=g.getInt8(1),l++;else if(1===m)r.offset=g.getInt16(1,!0),l+=2;else if(0===m)r.offset=g.getFloat32(1,!0),l+=4;else throw"Invalid block offset type";x=Math.min(r.offset,x);if(1===r.encoding)if(m=g.getUint8(l),l++,r.bitsPerPixel=m&63,m>>=6,r.numValidPixelsType=m,2===m)r.numValidPixels=g.getUint8(l),l++;else if(1===m)r.numValidPixels=g.getUint16(l,!0),l+=2;else if(0===m)r.numValidPixels=g.getUint32(l,!0),l+=4;else throw"Invalid valid pixel count type";}a+=l;if(3!=r.encoding)if(0===
r.encoding){g=(b.pixels.numBytes-1)/4;if(g!==Math.floor(g))throw"uncompressed block has invalid length";l=new ArrayBuffer(4*g);m=new Uint8Array(l);m.set(new Uint8Array(n,a,4*g));l=new Float32Array(l);for(m=0;m<l.length;m++)x=Math.min(x,l[m]);r.rawData=l;a+=4*g}else 1===r.encoding&&(g=Math.ceil(r.numValidPixels*r.bitsPerPixel/8),l=Math.ceil(g/4),l=new ArrayBuffer(4*l),m=new Uint8Array(l),m.set(new Uint8Array(n,a,g)),r.stuffedData=new Uint32Array(l),a+=g)}}b.pixels.minValue=x;b.eofOffset=a;var a=null!=
h.noDataValue?h.noDataValue:k.defaultNoDataValue,f=h.encodedMaskData,l=h.returnMask,x=0,w=b.pixels.numBlocksX,u=b.pixels.numBlocksY,v=Math.floor(b.width/w),r=Math.floor(b.height/u),g=2*b.maxZError,f=f||(b.mask?b.mask.bitset:null),A,e=new (h.pixelType||Float32Array)(b.width*b.height);l&&f&&(A=new Uint8Array(b.width*b.height));for(var l=new Float32Array(v*r),q,s,m=0;m<=u;m++){var p=m!==u?r:b.height%u;if(0!==p)for(var z=0;z<=w;z++){var E=z!==w?v:b.width%w;if(0!==E){var t=m*b.width*r+z*v,F=b.width-E,
y=b.pixels.blocks[x],B,C;if(2>y.encoding){if(0===y.encoding)B=y.rawData;else{B=y.stuffedData;C=y.bitsPerPixel;q=y.numValidPixels;s=y.offset;var L=g,P=l,K=b.pixels.maxValue,G=(1<<C)-1,S=0,I=void 0,H=0,M=void 0,Q=void 0,U=Math.ceil((K-s)/L),I=4*B.length-Math.ceil(C*q/8);B[B.length-1]<<=8*I;for(I=0;I<q;I++)0===H&&(Q=B[S++],H=32),H>=C?(M=Q>>>H-C&G,H-=C):(H=C-H,M=(Q&G)<<H&G,Q=B[S++],H=32-H,M+=Q>>>H),P[I]=M<U?s+M*L:K;B=l}C=0}else c=2===y.encoding?0:y.offset;var J;if(f)for(s=0;s<p;s++){t&7&&(J=f[t>>3],J<<=
t&7);for(q=0;q<E;q++)t&7||(J=f[t>>3]),J&128?(A&&(A[t]=1),e[t++]=2>y.encoding?B[C++]:c):(A&&(A[t]=0),e[t++]=a),J<<=1;t+=F}else if(2>y.encoding)for(s=0;s<p;s++){for(q=0;q<E;q++)e[t++]=B[C++];t+=F}else for(s=0;s<p;s++){for(q=0;q<E;q++)e[t++]=c;t+=F}if(1===y.encoding&&C!==y.numValidPixels)throw"Block and Mask do not match";x++}}}c=A;A={width:b.width,height:b.height,pixelData:e,minValue:b.pixels.minValue,maxValue:b.pixels.maxValue,noDataValue:a};c&&(A.maskData=c);h.returnEncodedMask&&b.mask&&(A.encodedMaskData=
b.mask.bitset?b.mask.bitset:null);if(h.returnFileInfo&&(A.fileInfo=d(b),h.computeUsedBitDepths)){c=A.fileInfo;J=b.pixels.numBlocksX*b.pixels.numBlocksY;B={};for(C=0;C<J;C++)a=b.pixels.blocks[C],0===a.encoding?B.float32=!0:1===a.encoding?B[a.bitsPerPixel]=!0:B[0]=!0;b=Object.keys(B);c.bitDepths=b}return A}},d=function(d){return{fileIdentifierString:d.fileIdentifierString,fileVersion:d.fileVersion,imageType:d.imageType,height:d.height,width:d.width,maxZError:d.maxZError,eofOffset:d.eofOffset,mask:d.mask?
{numBlocksX:d.mask.numBlocksX,numBlocksY:d.mask.numBlocksY,numBytes:d.mask.numBytes,maxValue:d.mask.maxValue}:null,pixels:{numBlocksX:d.pixels.numBlocksX,numBlocksY:d.pixels.numBlocksY,numBytes:d.pixels.numBytes,maxValue:d.pixels.maxValue,minValue:d.pixels.minValue,noDataValue:this.noDataValue}}};return k})},"esri/layers/PixelBlock":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(k,d,n,h){k=k([],{declaredClass:"esri.layers.PixelBlock",planes:null,width:null,
height:null,pixelType:null,pixels:[],statistics:[],constructor:function(c){if(c){if(!c.width||Math.floor(c.width)!==c.width)throw"PixelBlock: incorrect width";if(!c.height||Math.floor(c.height)!==c.height)throw"PixelBlock: incorrect height";if(!c.pixels||!c.statistics)throw"PixelBlock: pixel data or statistics not present";this.width=c.width;this.height=c.height;this.pixels=c.pixels;this.pixelType=c.pixelType||null;this.statistics=c.statistics;this.mask=c.mask||null}},getPlaneCount:function(){return this.pixels.length!==
this.statistics.length?console.error("Inconsistent pixel data and statistics"):this.statistics.length},addData:function(c){if(!c.pixels||!c.statistics)throw"Pixel data or statistics are not present";if(c.pixels.length!==this.width*this.height)throw"Inconsistent pixel data size";this.statistics.push(c.statistics);this.pixels.push(c.pixels)},getAsRGBA:function(){var c=new ArrayBuffer(4*this.width*this.height);switch(this.pixelType){case "S8":case "S16":case "U16":case "S32":case "U32":case "F32":case "F64":this._fillFromNon8Bit(c);
break;default:this._fillFrom8Bit(c)}return new Uint8ClampedArray(c)},getAsRGBAFloat:function(){var c=new Float32Array(4*this.width*this.height);this._fillFrom32Bit(c);return c},clone:function(){var c=new this.constructor;c.width=this.width;c.height=this.height;c.pixelType=this.pixelType;this.mask&&(c.mask=new Uint8Array(this.mask));var a,e;if(this.pixels){c.pixels=[];e=this.pixels.length;for(a=0;a<e;a++)c.pixels[a]=new Float32Array(this.pixels[a])}if(this.statistics){c.statistics=[];e=this.statistics.length;
for(a=0;a<e;a++)c.statistics[a]=d.clone(this.statistics[a])}return c},_fillFrom8Bit:function(c){var a=this.pixels,e=this.mask;if(!c||!a||!a.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");var b,f,g;b=f=g=a[0];3<=a.length&&(f=a[1],g=a[2]);var a=new Uint32Array(c),d=this.width*this.height;if(b.length!==d)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");if(e&&e.length===d)for(c=0;c<d;c++)e[c]&&(a[c]=-16777216|g[c]<<16|f[c]<<8|b[c]);
else for(c=0;c<d;c++)a[c]=-16777216|g[c]<<16|f[c]<<8|b[c]},_fillFromNon8Bit:function(c){var a=this.pixels,e=this.mask,b=this.statistics;if(!c||!a||!a.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");var f=1,g=0;b&&0<b.length?(g=b[0].minValue,f=255/(b[0].maxValue-b[0].minValue)):(f=255,"S8"===this.pixelType?(g=-128,f=127):"U16"===this.pixelType?f=65535:"S16"===this.pixelType?(g=-32768,f=32767):"U32"===this.pixelType?f=4294967295:"S32"===this.pixelType?(g=-2147483648,
f=2147483647):"F32"===this.pixelType?(g=-3.4*1E39,f=3.4*1E39):"F64"===this.pixelType&&(g=-Number.MAX_VALUE,f=Number.MAX_VALUE),f=255/(f-g));c=new Uint32Array(c);var b=this.width*this.height,d,w,h;d=a[0];if(d.length!==b)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");if(3<=a.length)if(w=a[1],h=a[2],e&&e.length===b)for(a=0;a<b;a++)e[a]&&(c[a]=-16777216|(h[a]-g)*f<<16|(w[a]-g)*f<<8|(d[a]-g)*f);else for(a=0;a<b;a++)c[a]=-16777216|(h[a]-g)*f<<16|(w[a]-g)*f<<8|(d[a]-g)*f;else if(e&&
e.length===b)for(a=0;a<b;a++)w=(d[a]-g)*f,e[a]&&(c[a]=-16777216|w<<16|w<<8|w);else for(a=0;a<b;a++)w=(d[a]-g)*f,c[a]=-16777216|w<<16|w<<8|w},_fillFrom32Bit:function(c){var a=this.pixels,e=this.mask;if(!c||!a||!a.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");var b,f,g;b=f=g=a[0];3<=a.length&&(f=a[1],g=a[2]);var d=this.width*this.height;if(b.length!==d)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");var h=0;if(e&&e.length===d)for(a=
0;a<d;a++)c[h++]=b[a],c[h++]=f[a],c[h++]=g[a],c[h++]=e[a];else for(a=0;a<d;a++)c[h++]=b[a],c[h++]=f[a],c[h++]=g[a],c[h++]=255}});n("extend-esri")&&d.setObject("layers.PixelBlock",k,h);return k})},"esri/layers/RasterFunction":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../lang"],function(k,d,n,h,c){var a=k(null,{declaredClass:"esri.layers.RasterFunction",functionName:null,arguments:null,functionArguments:null,variableName:null,outputPixelType:null,constructor:function(a){if(d.isObject(a)){var b=
0;this.functionName=a.rasterFunction;this.functionArguments=d.clone(a.rasterFunctionArguments||a.arguments);d.mixin(this,a);if(a=this.functionArguments)if(a.Raster=this._toRasterFunction(a.Raster),a.Raster2=this._toRasterFunction(a.Raster2),a.DEM=this._toRasterFunction(a.DEM),a.FillRaster=this._toRasterFunction(a.FillRaster),a.Rasters&&a.Rasters.length)for(b=0;b<a.Rasters.length;b++)a.Rasters[b]=this._toRasterFunction(a.Rasters[b])}},_toRasterFunction:function(e){return e&&(e.rasterFunction||e.functionName)?
new a(e):e},_rfToJson:function(a){a&&"esri.layers.RasterFunction"===a.declaredClass&&(a=a.toJson());return a},toJson:function(){var a=d.clone(this.functionArguments||this.arguments);if(a&&(a.Raster=this._rfToJson(a.Raster),a.Raster2=this._rfToJson(a.Raster2),a.DEM=this._rfToJson(a.DEM),a.FillRaster=this._rfToJson(a.FillRaster),a.Rasters&&a.Rasters.length)){var b,f=[];for(b=0;b<a.Rasters.length;b++)f.push(this._rfToJson(a.Rasters[b]));a.Rasters=f}return c.filter({rasterFunction:this.functionName,rasterFunctionArguments:a,
variableName:this.variableName,outputPixelType:this.outputPixelType?this.outputPixelType:null},function(a){if(null!==a&&void 0!==a)return!0})}});n("extend-esri")&&d.setObject("layers.RasterFunction",a,h);return a})},"esri/layers/MosaicRule":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../lang ../geometry/Point".split(" "),function(k,d,n,h,c,a){var e=k(null,{declaredClass:"esri.layers.MosaicRule",method:null,where:null,sortField:null,sortValue:null,ascending:!1,lockRasterIds:null,
viewpoint:null,objectIds:null,operation:null,multidimensionalDefinition:[],constructor:function(b){d.isObject(b)&&(d.mixin(this,b),b.mosaicMethod&&(this.method=b.mosaicMethod),this.method&&"esri"!==this.method.toLowerCase().substring(0,4)&&(this.method=this._getMethodEnum(this.method)),b.mosaicOperation&&(this.operation=b.mosaicOperation),this.operation&&"MT_"!==this.operation.toUpperCase().substring(0,3)&&(this.operation=this._getOperatorEnum(this.operation)),b.fids&&(this.objectIds=b.fids),b.viewpoint&&
(this.viewpoint=new a(b.viewpoint)),this.multidimensionalDefinition=b.multidimensionalDefinition||[])},toJson:function(){var a=null,f=this.multidimensionalDefinition?this.multidimensionalDefinition.length:0;if(f)for(var a=[],e=0;e<f;e++)a.push("esri.layers.DimensionalDefinition"===this.multidimensionalDefinition[e].declaredClass?this.multidimensionalDefinition[e].toJson():this.multidimensionalDefinition[e]);a={mosaicMethod:this.method,where:this.where,sortField:this.sortField,sortValue:this.sortValue,
ascending:this.ascending,lockRasterIds:this.lockRasterIds,viewpoint:this.viewpoint?this.viewpoint.toJson():null,fids:this.objectIds,mosaicOperation:this.operation,multidimensionalDefinition:a};return c.filter(a,function(a){if(null!==a)return!0})},_getMethodEnum:function(a){if(a){var f=e.METHOD_NONE;switch(a.toLowerCase()){case "byattribute":f=e.METHOD_ATTRIBUTE;break;case "center":f=e.METHOD_CENTER;break;case "lockraster":f=e.METHOD_LOCKRASTER;break;case "nadir":f=e.METHOD_NADIR;break;case "northwest":f=
e.METHOD_NORTHWEST;break;case "seamline":f=e.METHOD_SEAMLINE;break;case "viewpoint":f=e.METHOD_VIEWPOINT}return f}},_getOperatorEnum:function(a){if(a)switch(a.toLowerCase()){case "first":return e.OPERATION_FIRST;case "last":return e.OPERATION_LAST;case "max":return e.OPERATION_MAX;case "min":return e.OPERATION_MIN;case "blend":return e.OPERATION_BLEND;case "mean":return e.OPERATION_MEAN;case "sum":return e.OPERATION_SUM}}});d.mixin(e,{METHOD_NONE:"esriMosaicNone",METHOD_CENTER:"esriMosaicCenter",
METHOD_NADIR:"esriMosaicNadir",METHOD_VIEWPOINT:"esriMosaicViewpoint",METHOD_ATTRIBUTE:"esriMosaicAttribute",METHOD_LOCKRASTER:"esriMosaicLockRaster",METHOD_NORTHWEST:"esriMosaicNorthwest",METHOD_SEAMLINE:"esriMosaicSeamline",OPERATION_FIRST:"MT_FIRST",OPERATION_LAST:"MT_LAST",OPERATION_MIN:"MT_MIN",OPERATION_MAX:"MT_MAX",OPERATION_MEAN:"MT_MEAN",OPERATION_BLEND:"MT_BLEND",OPERATION_SUM:"MT_SUM"});n("extend-esri")&&d.setObject("layers.MosaicRule",e,h);return e})},"esri/tasks/ImageServiceIdentifyParameters":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/_base/array dojo/has ../kernel ../lang ../geometry/jsonUtils".split(" "),
function(k,d,n,h,c,a,e,b){k=k(null,{declaredClass:"esri.tasks.ImageServiceIdentifyParameters",geometry:null,mosaicRule:null,renderingRule:null,renderingRules:null,pixelSizeX:null,pixelSizeY:null,pixelSize:null,returnGeometry:!1,returnCatalogItems:!0,timeExtent:null,toJson:function(a){var c=a&&a.geometry||this.geometry;a={geometry:c,returnGeometry:this.returnGeometry,returnCatalogItems:this.returnCatalogItems,mosaicRule:this.mosaicRule?n.toJson(this.mosaicRule.toJson()):null,renderingRule:this.renderingRule?
n.toJson(this.renderingRule.toJson()):null};c&&(a.geometryType=b.getJsonType(c));c=this.timeExtent;a.time=c?c.toJson().join(","):null;e.isDefined(this.pixelSizeX)&&e.isDefined(this.pixelSizeY)?a.pixelSize=n.toJson({x:parseFloat(this.pixelSizeX),y:parseFloat(this.pixelSizeY)}):this.pixelSize&&(a.pixelSize=this.pixelSize?n.toJson(this.pixelSize.toJson()):null);this.renderingRules&&(a.renderingRules=n.toJson(h.map(this.renderingRules,function(a){return a.toJson()})));return a}});c("extend-esri")&&d.setObject("tasks.ImageServiceIdentifyParameters",
k,a);return k})},"esri/layers/DimensionalDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../lang"],function(k,d,n,h,c){k=k(null,{declaredClass:"esri.layers.DimensionalDefinition",variableName:null,dimensionName:null,values:[],isSlice:!1,constructor:function(a){d.isObject(a)&&d.mixin(this,a)},toJson:function(){return c.filter({variableName:this.variableName,dimensionName:this.dimensionName,values:this.values,isSlice:this.isSlice},function(a){return null!==
a})}});n("extend-esri")&&d.setObject("layers.DimensionalDefinition",k,h);return k})},"esri/layers/rasterFormats/ImageCanvasDecoder":function(){define(["require","dojo/_base/declare","dojo/Deferred","dojo/sniff"],function(k,d,n,h){var c;return d(null,{constructor:function(a){this.ctx=a.ctx;this._loadRasterFormatModule()},decode:function(a,c){if(!c.width||!c.height)throw"Native decoding requires the image format, width and height";var b=new n,f,d=new Uint8Array(a),h=this._getFormat(a);if("error"===
h)throw"invalid format";"jpeg"===h&&(f=this._getMask(d,c));var k="",u,v;for(u=0;u<d.length;u+=65535)v=d.subarray(u,u+65535>d.length-1?d.length-1:u+65535),k+=String.fromCharCode.apply(null,v);var d="data:image/"+h+";base64,"+window.btoa(k),l=new Image,r;l.src=d;var m=this;l.onload=function(){m.ctx.clearRect(0,0,c.width,c.height);m.ctx.drawImage(l,0,0);var a=m.ctx.getImageData(0,0,l.width,l.height);r=a.data;if(f)for(u=0;u<f.length;u++)r[4*u+3]=f[u]?255:0;m.ctx.putImageData(a,0,0);b.resolve(null)};l.onerror=
function(){b.reject("cannot load image")};return b},_getFormat:function(a){a=new Uint8Array(a,0,10);var c="error";255===a[0]&&216===a[1]?c="jpeg":137===a[0]&&(80===a[1]&&78===a[2]&&71===a[3])&&(c="png");return c},_getMask:function(a,d){var b;try{if(!c)throw"The zlib decoder module is not loaded.";var f=0,g=0,h=Math.round(a.length/2);1===h%2&&(h+=1);for(var k=a.length-2,f=h;f<k&&!(255===a[f]&&217===a[f+1]);f++);h=f+=2;if(h<a.length-1){var n=(new c(a.subarray(h))).getBytes();b=new Uint8Array(d.width*
d.height);for(f=h=0;f<n.length;f++)for(g=7;0<=g;g--)b[h++]=n[f]>>g&1}}catch(v){}return b},_loadRasterFormatModule:function(){10>h("ie")||k(["./Zlib"],function(a){c=a})}})})},"esri/layers/pixelFilters/VectorFieldPixelFilter":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../lang dojo/_base/array".split(" "),function(k,d,n,h,c,a){k=k(null,{declaredClass:"esri.layers.pixelFilters.VectorFieldPixelFilter",speedUnits:["esriMetersPerSecond","esriKilometersPerHour","esriKnots",
"esriFeetPerSecond","esriMilesPerHour"],constructor:function(a){d.mixin(this,a);this.isDataUV=a&&a.isDataUV?a.isDataUV:!1;this.computeMagnitudeAndDirection=d.hitch(this,this.computeMagnitudeAndDirection);this.unitConversionFactor=1;this._updateUnitConvFactor()},setUnits:function(a,b){this.inputUnit=a;this.outputUnit=b;this.unitConversionFactor=1;this._updateUnitConvFactor()},_updateUnitConvFactor:function(){var c=a.indexOf(this.speedUnits,this.inputUnit),b=a.indexOf(this.speedUnits,this.outputUnit);
if(this.inputUnit&&this.outputUnit&&0<=c&&0<=b){var d=[1,0.277778,0.514444,0.3048,0.44704,0];this.unitConversionFactor=d[c]/d[b]}},computeMagnitudeAndDirection:function(a){if(!c.isDefined(a))throw"Could not compute magnitude and direction. No pixel data is available.";var b=a.pixelBlock;if(!c.isDefined(b)||2!==b.getPlaneCount())throw"Could not compute magnitude and direction. Pixel data does not contain two bands.";var d=a.extent,g=(d.xmax-d.xmin)/b.width,h=(d.ymax-d.ymin)/b.height,k=d.xmin+g/2,d=
d.ymax-h/2;b.statistics[0].minValue=0;b.statistics[0].maxValue=0;var n=180/Math.PI,v=[],l=0,r=0,m=0,A=!c.isDefined(b.mask),q,s,p,z,E,t,F,y;E=F=Infinity;t=y=-Infinity;for(l=0;l<b.height;l++)for(r=0;r<b.width;r++,m++)if(v.push([k+g*r,d-h*l]),A||b.mask[m])p=q=b.pixels[0][m]*this.unitConversionFactor,z=s=b.pixels[1][m],this.isDataUV&&(p=Math.sqrt(q*q+s*s),z=90-n*Math.atan2(s,q),b.pixels[0][m]=p*this.unitConversionFactor,b.pixels[1][m]=z),p>t&&(t=p),p<E&&(E=p),z>y&&(y=z),z<F&&(F=z);b.statistics[0].maxValue=
t;b.statistics[0].minValue=E;b.statistics[1].maxValue=y;b.statistics[1].minValue=F;a.locations=v;return a}});n("extend-esri")&&d.setObject("layers.pixelFilters.VectorFieldPixelFilter",k,h);return k})},"esri/tasks/ImageServiceIdentifyTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../request ../geometry/normalizeUtils ./Task ./ImageServiceIdentifyResult".split(" "),function(k,d,n,h,c,a,e,b){k=k(e,{declaredClass:"esri.tasks.ImageServiceIdentifyTask",constructor:function(a){this._url.path+=
"/identify";this._handler=d.hitch(this,this._handler)},__msigns:[{n:"execute",c:3,a:[{i:0,p:["geometry"]}],e:2}],_handler:function(a,d,c,e,h){try{var k=new b(a);this._successHandler([k],"onComplete",c,h)}catch(l){this._errorHandler(l,e,h)}},execute:function(a,b,e,h){var k=h.assembly;a=this._encode(d.mixin({},this._url.query,{f:"json"},a.toJson(k&&k[0])));var n=this._handler,l=this._errorHandler;return c({url:this._url.path,content:a,callbackParamName:"callback",load:function(a,c){n(a,c,b,e,h.dfd)},
error:function(a){l(a,e,h.dfd)}})},onComplete:function(){}});a._createWrappers(k);n("extend-esri")&&d.setObject("tasks.ImageServiceIdentifyTask",k,h);return k})},"esri/layers/Raster":function(){define("require dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/config dojo/json dojo/sniff ../kernel ../Evented ../request ../geometry/Extent ../SpatialReference ../deferredUtils ./PixelBlock ./rasterFormats/LercCodec".split(" "),function(k,d,n,h,c,a,e,b,f,g,x,w,u,v,l,r){var m,
A,q;d=d(g,{declaredClass:"esri.layers.Raster",imageServiceUrl:null,validPixelTypes:"U1 U2 U4 U8 U16 U32 S8 S16 S32 F32".split(" "),validFormats:"lerc jpeg jpg jpgpng png png8 png24 png32 bip bsq".split(" "),_eventMap:{"raster-read-complete":["pixelData","params"]},constructor:function(a){if(!a)throw"Image Service URL is not defined";this.imageServiceUrl=a;this.registerConnectEvents();this._loadRasterFormatModules()},read:function(d,t,e){var f=this,g=new h(v._dfdCanceller);if(10>b("ie"))throw"This browser is not supported.";
if(!d.imageServiceParameters)throw"Insufficient parameters to read data";var k=n.clone(d.imageServiceParameters),l=d.pixelType;c.some(this.validPixelTypes,function(a){return a===l})||(k.pixelType="F32");c.some(this.validFormats,function(a){return a.toLowerCase()===k.format.toLowerCase()})||(k.format="lerc");var m=d.decodeFunc,K;this._prepareGetImageParameters(k);g._pendingDfd=x({url:this.imageServiceUrl+"/exportImage",handleAs:"arraybuffer",content:n.mixin(k,{f:"image"}),load:function(G){var b=k.format.toUpperCase();
"BSQ"!==b&&"BIP"!==b&&(b=f._getFormat(G));if("ERROR"===b)G=Error(String.fromCharCode.apply(null,new Uint8Array(G))),G.log=a.isDebug,f._resolve([G],null,e,g,!0);else{if(void 0===m||null===m)m=f._getFormatDecoderDfd(b);m?m(G,{width:k.width,height:k.height,planes:null,pixelType:l,noDataValue:k.noData}).then(function(a){K={pixelBlock:a,extent:k.extent};f._resolve([K,k],"onRasterReadComplete",t,g)},function(a){f._resolve([a],null,e,g,!0)}):(G=Error("Format '"+k.format+"' is not supported."),G.log=a.isDebug,
f._resolve([G],null,e,g,!0))}},error:function(a){f._resolve([a],null,e,g,!0)}});return g.promise},onRasterReadComplete:function(){},_prepareGetImageParameters:function(a){if(a.size&&a.bbox){var b=a.size.split(",");a.width=parseFloat(b[0]);a.height=parseFloat(b[1]);a.extent||(b=a.bbox.split(","),a.extent=new w(parseFloat(b[0]),parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3]),new u(a.bboxSR)))}else{if(!a.width||Math.floor(a.width)!==a.width||!a.height||Math.floor(a.height)!==a.height)throw"Incorrect Image Dimensions";
if(!a.extent||"esri.geometry.Extent"!==a.extent.declaredClass)throw"Incorrect extent";var b=a.extent,d=b.spatialReference.wkid||e.toJson(b.spatialReference.toJson());delete a._ts;n.mixin(a,{bbox:b.xmin+","+b.ymin+","+b.xmax+","+b.ymax,imageSR:d,bboxSR:d,size:a.width+","+a.height},a.disableClientCaching?{_ts:(new Date).getTime()}:{})}},_adjustExtent:function(a,b,d){var c=a.ymax-a.ymin,e=a.xmax-a.xmin;d>=b?a.ymax=a.ymin+e*b/d:(e=c*d/b,a.xmax=a.xmin+e);return a},_resolve:function(a,b,d,c,e){b&&this[b].apply(this,
a);d&&d.apply(null,a);c&&v._resDfd(c,a,e)},_getFormatDecoderDfd:function(a){var b=null;switch(a){case "LERC":b=this._decodeLerc;break;case "JPEG":b=this._decodeJpeg;break;case "PNG":b=this._decodePng;break;case "BSQ":b=this._decodeBsq;break;case "BIP":b=this._decodeBip}b=n.hitch(this,b);return function(a,d){var c=new h;try{var e=b(a,d);c.resolve(e)}catch(f){c.reject(f)}return c}},_getFormat:function(a){a=new Uint8Array(a,0,10);var b="";255===a[0]&&216===a[1]?b="JPEG":137===a[0]&&80===a[1]&&78===a[2]&&
71===a[3]?b="PNG":67===a[0]&&110===a[1]&&116===a[2]&&90===a[3]&&73===a[4]&&109===a[5]&&97===a[6]&&103===a[7]&&101===a[8]&&32===a[9]?b="LERC":-1<String.fromCharCode.apply(null,a).toLowerCase().indexOf("error")&&(b="ERROR");return b},_validateDecodeParams:function(a){if(!a.height||Math.floor(a.height)!==a.height)throw"Height not provided.";if(!a.width||Math.floor(a.width)!==a.width)throw"Width not provided.";},_decodeJpeg:function(a,b){if(!m)throw"The jpeg decoder module is not loaded.";this._validateDecodeParams(b);
var d=(new m).decode(a);if(d.height!==b.height||d.width!==b.width)throw"The decoded image dimensions are incorrect.";var c=[],e,f;for(e=0;e<d.pixels.length;e++)f=d.pixels[e],c.push(this._calculateBandStatistics(f));return new l({width:d.width,height:d.height,pixels:d.pixels,pixelType:"U8",mask:d.mask,statistics:c})},_decodePng:function(a,b){if(!A)throw"The png decoder module is not loaded.";this._validateDecodeParams(b);var d=new Uint8Array(a),c=new A(d),d=new Uint8Array(4*b.width*b.height);c.copyToImageData(d,
c.decodePixels());for(var e=c=0,f,e=new Uint8Array(b.width*b.height),c=0;c<b.width*b.height;c++)e[c]=d[4*c+3];for(var g=new l({width:b.width,height:b.height,pixels:[],pixelType:"U8",mask:e,statistics:[]}),c=0;3>c;c++){f=new Uint8Array(b.width*b.height);for(e=0;e<b.width*b.height;e++)f[e]=d[4*e+c];g.addData({pixels:f,statistics:this._calculateBandStatistics(f)})}return g},_decodeBsq:function(a,b){if(!q)throw"The bsq decoder module is not loaded.";this._validateDecodeParams(b);p=b.noDataValue;b.pixelType=
z(b.pixelType);var d=q.decodeBSQ(a,{bandCount:b.planes,width:b.width,height:b.height,pixelType:s,noDataValue:p}),c=[],e,f=null;for(e=0;e<d.pixels.length;e++)f=d.pixels[e],c.push(this._calculateBandStatistics(f));return new l({width:b.width,height:b.height,pixels:d.pixels,pixelType:b.pixelType,mask:d.maskData,statistics:c})},_decodeBip:function(a,b){this._validateDecodeParams(b);p=b.noDataValue;b.pixelType=z(b.pixelType);var d=q.decodeBIP(a,{bandCount:b.planes,width:b.width,height:b.height,pixelType:s,
noDataValue:p}),c=[],e,f=null;for(e=0;e<d.pixels.length;e++)f=d.pixels[e],c.push(this._calculateBandStatistics(f));return new l({width:b.width,height:b.height,pixels:d.pixels,pixelType:b.pixelType,mask:d.maskData,statistics:c})},_decodeLerc:function(a,b){this._validateDecodeParams(b);p=b.noDataValue;b.pixelType=z(b.pixelType);for(var d=0,c,e=0,f,g=a.byteLength-10;e<g;){var h=r.decode(a,{inputOffset:e,encodedMaskData:c,returnMask:0===d?!0:!1,returnEncodedMask:0===d?!0:!1,returnFileInfo:!0,pixelType:s,
noDataValue:p}),e=h.fileInfo.eofOffset;0===d&&(c=h.encodedMaskData,f=new l({width:b.width,height:b.height,pixels:[],pixelType:b.pixelType,mask:h.maskData,statistics:[]}));d++;if(h.height!==b.height||h.width!==b.width)throw"The decoded image dimensions are incorrect";f.addData({pixels:h.pixelData,statistics:{minValue:h.minValue,maxValue:h.maxValue,noDataValue:h.noDataValue}})}return f},_calculateBandStatistics:function(a){var b=Infinity,d=-Infinity,c=a.length,e,f=0;for(e=0;e<c;e++)f=a[e],b=f<b?f:b,
d=f>d?f:d;return{minValue:b,maxValue:d}},_loadRasterFormatModules:function(){10>b("ie")||k(["./rasterFormats/JpgPlus","./rasterFormats/Png","./rasterFormats/Raw"],function(a,b,d){m=a;A=b;q=d})}});var s=null,p=null,z=function(a){"U1"===a||"U2"===a||"U4"===a||"U8"===a?(a="U8",p=Math.pow(2,8)-1,s=Uint8Array):"U16"===a?(p=p||Math.pow(2,16)-1,s=Uint16Array):"U32"===a?(p=p||Math.pow(2,32)-1,s=Uint32Array):"S8"===a?(p=p||0-Math.pow(2,7),s=Int8Array):"S16"===a?(p=p||0-Math.pow(2,15),s=Int16Array):"S32"===
a?(p=p||0-Math.pow(2,31),s=Int32Array):s=Float32Array;return a};b("extend-esri")&&n.setObject("layers.Raster",d,f);return d})},"esri/layers/ImageServiceLayerMixin":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/json dojo/_base/config dojo/_base/connect dojo/has dojo/io-query ../kernel ../config ../lang ../request ../deferredUtils ../urlUtils ../geometry/Extent ../geometry/Point ../geometry/Polygon ./MosaicRule ./RasterFunction ./DimensionalDefinition ./Raster ./PixelBlock ./pixelFilters/VectorFieldPixelFilter ./rasterFormats/ImageCanvasDecoder ./TimeInfo ./Field ../graphic ../tasks/ImageServiceIdentifyTask ../tasks/ImageServiceIdentifyParameters".split(" "),
function(k,d,n,h,c,a,e,b,f,g,x,w,u,v,l,r,m,A,q,s,p,z,E,t,F,y,B,C,L,P){k=k(null,{declaredClass:"esri.layers.ImageServiceLayerMixin",_rasterFieldPrefix:"Raster.",_renderingRuleFieldSubPrefix:"ServicePixelValue.",_eventMap:{"rendering-change":!0,"mosaic-rule-change":!0},constructor:function(a,b){this.useMapTime=b&&b.hasOwnProperty("useMapTime")?!!b.useMapTime:!0},_initialize:function(a,b){this._url=l.urlToObject(a);this.raster=new z(a);this.infoTemplate=b&&b.infoTemplate;var c=b&&b.imageServiceParameters;
this.format=c&&c.format;this.compressionTolerance=c&&c.compressionTolerance?c.compressionTolerance:0.01;this.interpolation=c?c.interpolation:null;this.compressionQuality=c?c.compressionQuality:null;this.bandIds=c?c.bandIds:null;this.mosaicRule=c?c.mosaicRule:null;this.renderingRule=c?c.renderingRule:null;this.useMapDimensionValue=b&&b.hasOwnProperty("useMapDimensionValue")?!!b.useMapDimensionValue:!0;this.activeMapDimensions=b&&b.activeMapDimensions;this._params=d.mixin({},this._url.query,{f:"image",
interpolation:this.interpolation,format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},c?c.toJson():{});this.pixelFilter=b&&b.pixelFilter;this.originalPixelData=this.pixelData=null;this.hasDataChanged=!0;this._requestDataHandler=d.hitch(this,this._requestDataHandler);this._requestDataErrorHandler=d.hitch(this,this._requestDataErrorHandler);this._rasterReadPromise=null;this._initLayer=d.hitch(this,this._initLayer);this._queryVisibleRastersHandler=
d.hitch(this,this._queryVisibleRastersHandler);this._visibleRasters=[];this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._renderingRuleAttributeTable={};this._useRenderingRuleAttributeTable=!1;this._loadCallback=b&&b.loadCallback;(c=b&&b.resourceInfo)?this._initLayer(c):u({url:this._url.path,content:d.mixin({f:"json"},this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},disableClientCaching:!1,_initLayer:function(a,
b){if(!(null===a||void 0===a)){this._findCredential();(this.credential&&this.credential.ssl||a&&a._ssl)&&this._useSSL();var c=this.minScale,e=this.maxScale;d.mixin(this,a);this.minScale=c;this.maxScale=e;this.initialExtent=this.fullExtent=this.extent=new r(a.extent);this.spatialReference=this.initialExtent.spatialReference;this.pixelSizeX=parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);for(var f=this.minValues,h=this.maxValues,g=this.meanValues,k=this.stdvValues,l=this.bands=
[],c=0,e=this.bandCount;c<e;c++)l[c]={min:f[c],max:h[c],mean:g[c],stddev:k[c]};this.timeInfo=(c=this.timeInfo)&&c.timeExtent?new y(c):null;e=this.fields=[];if(f=a.fields)for(c=0;c<f.length;c++)e.push(new B(f[c]));this.version=a.currentVersion;this.version||(this.version="fields"in a||"objectIdField"in a||"timeInfo"in a?10:9.3);w.isDefined(a.minScale)&&!this._hasMin&&this.setMinScale(a.minScale);w.isDefined(a.maxScale)&&!this._hasMax&&this.setMaxScale(a.maxScale);c={};a.defaultMosaicMethod?(c.method=
a.defaultMosaicMethod,c.operation=a.mosaicOperator,c.sortField=a.sortField,c.sortValue=a.sortValue):c.method=q.METHOD_NONE;this.defaultMosaicRule=new q(c);this.defaultMosaicRule.ascending=!0;this._useRenderingRuleAttributeTable=10<this.version&&"esriImageServiceDataTypeThematic"===this.serviceDataType&&!this.hasRasterAttributeTable;this._setDefaultRenderingRule(!0);this._isScientificData()&&(!this.mosaicRule||this.mosaicRule&&!this.mosaicRule.multidimensionalDefinition)&&this._setDefaultMultidimensionalDefinition(!0);
10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(d.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=d.clone(a.features));a&&(a.fields&&0<a.fields.length)&&(this._rasterAttributeTableFields=d.clone(a.fields))}));this._isVectorData()&&!w.isDefined(this.pixelFilter)&&(this.vectorFieldPixelFilter=new t,this.vectorFieldPixelFilter.isDataUV="esriImageServiceDataTypeVector-UV"===this.serviceDataType,this.pixelFilter=this.vectorFieldPixelFilter.computeMagnitudeAndDirection,
this.getKeyProperties().then(d.hitch(this,this._setFlowRepresentation)));this.loaded=!0;this.onLoad(this);if(c=this._loadCallback)delete this._loadCallback,c(this)}},getKeyProperties:function(){var b=this._url.path+"/keyProperties",c=new n(v._dfdCanceller);10<this.version?(c._pendingDfd=u({url:b,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a)},function(a){c.errback(a)})):(b=Error("Layer does not have key properties"),b.log=a.isDebug,c.errback(b));
return c},getRasterAttributeTable:function(b){var d=this._url.path+"/rasterAttributeTable",e=new n(v._dfdCanceller),f={f:"json"},h=this.hasRasterAttributeTable;b&&b.renderingRule&&(f.renderingRule=c.toJson(b.renderingRule.toJson()),h=!0);10<this.version&&h?(e._pendingDfd=u({url:d,content:f,handleAs:"json",callbackParamName:"callback"}),e._pendingDfd.then(function(a){e.callback(a)},function(a){e.errback(a)})):(b=Error("Layer does not support raster attribute table"),b.log=a.isDebug,e.errback(b));return e},
_getRenderingRuleAttributeTable:function(a){var b=new n(v._dfdCanceller);if(!a||!a.renderingRule)return b.errback(Error("Rendering rule is not specified")),b;a=a.renderingRule;var c=a.functionName;this._renderingRuleAttributeTable&&c&&this._renderingRuleAttributeTable.hasOwnProperty(c)?b.resolve(this._renderingRuleAttributeTable[c]):b=this.getRasterAttributeTable({renderingRule:a}).then(d.hitch(this,function(a){var b;a&&(a.features&&a.features.length&&a.fields&&a.fields.length)&&(b={features:d.clone(a.features),
fields:d.clone(a.fields)},c&&(this._renderingRuleAttributeTable[c]=b));return b}));return b},_getRasterAttributeTableFeatures:function(){var a=new n;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return a.resolve(this._rasterAttributeTableFeatures),a;if(10<this.version&&this.hasRasterAttributeTable)return a=this.getRasterAttributeTable(),a.then(d.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=d.clone(a.features))})),
a;a.resolve(this._rasterAttributeTableFeatures);return a},_getRenderingRuleAttributeTableFeatures:function(a){a=a&&a.renderingRule;return!a?(a=new n,a.errback(Error("Rendering rule is not specified")),a):this._getRenderingRuleAttributeTable({renderingRule:a}).then(function(a){return a&&a.features})},getCustomRasterFields:function(a){var b=a?a.rasterAttributeTableFieldPrefix:this._rasterFieldPrefix;a=10.3<=this.version?"esriFieldTypeDouble":"esriFieldTypeString";var c={name:this._rasterFieldPrefix+
"ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:a},e={name:this._rasterFieldPrefix+"ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:a},f={name:this._rasterFieldPrefix+"ServicePixelValue.Raw",alias:"Raw Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeDouble"},g=this.fields?d.clone(this.fields):[];a=g.length;g[a]=e;if(10.4<=this.version&&"esri.layers.ArcGISImageServiceLayer"===this.declaredClass&&(!this.rasterFunctionInfos||
!this.rasterFunctionInfos.length||this._isRasterFunctionInfoAvailable("none")))a++,g[a]=f;if(this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")||this.fields&&0<this.fields.length)a++,g[a]=c;if(w.isDefined(this.pixelFilter)&&("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType))c={name:this._rasterFieldPrefix+"Magnitude",alias:"Magnitude",domain:null,editable:!1,type:"esriFieldTypeDouble"},e={name:this._rasterFieldPrefix+
"Direction",alias:"Direction",domain:null,editable:!1,type:"esriFieldTypeDouble"},a++,g[a]=c,a++,g[a]=e;a=this._rasterAttributeTableFields;if((c=this.renderingRule&&this.renderingRule.functionName)&&this._renderingRuleAttributeTable&&this._renderingRuleAttributeTable.hasOwnProperty(c))a=this._renderingRuleAttributeTable[c].fields;a&&0<a.length&&(a=h.filter(a,function(a){return"esriFieldTypeOID"!==a.type&&"value"!==a.name.toLowerCase()}),a=h.map(a,function(a){var c=d.clone(a);c.name=b+a.name;return c}),
g=g.concat(a));var k=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;10.4<=this.version&&this.rasterFunctionInfos&&h.forEach(this.rasterFunctionInfos,function(a){a&&(a.name&&"none"!==a.name.toLowerCase())&&(a={name:k+a.name.replace(/ /gi,"_"),alias:a.name,domain:null,editable:!1,type:"esriFieldTypeDouble"},g.push(a))});return g},_prepareGetImageParameters:function(a,b,e,f){f=w.isDefined(f)?f:this._params;var g=a.spatialReference.wkid||c.toJson(a.spatialReference.toJson(!1));delete f._ts;
d.mixin(f,{bbox:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,imageSR:g,bboxSR:g,size:b+","+e},this.disableClientCaching?{_ts:(new Date).getTime()}:{});delete f.compressionTolerance;f.format&&"LERC"===f.format.toUpperCase()&&(f.compressionTolerance=this.compressionTolerance);f.token=this._getToken()},getImageUrl:function(a,b,c,e,g){g=w.isDefined(g)?g:this._params;this._prepareGetImageParameters(a,b,c,g);a=d.clone(g);this._cleanupRequestParams(a);b=this._url.path+"/exportImage?";c=l.addProxy(b+f.objectToQuery(d.mixin(a,
{f:"image"})));var h=a.token;c.length>x.defaults.io.postLength||this.useMapImage?this._jsonRequest=u({url:b,content:d.mixin(a,{f:"json"}),callbackParamName:"callback",load:function(a,b){var c=a.href;h&&(c+=-1===c.indexOf("?")?"?token\x3d"+h:"\x26token\x3d"+h);e(l.addProxy(c))},error:this._errorHandler}):e(c)},onRenderingChange:function(){},onMosaicRuleChange:function(){},setInterpolation:function(a,b){this.interpolation=this._params.interpolation=a;b||this.refresh(!0)},setCompressionQuality:function(a,
b){this.compressionQuality=this._params.compressionQuality=a;b||this.refresh(!0)},setCompressionTolerance:function(a,b){this.compressionTolerance=a;b||this.refresh(!0)},setBandIds:function(a,b){var c=!1;this.bandIds!==a&&(c=!0);this.bandIds=a;this._params.bandIds=a.join(",");if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setDefaultBandIds:function(a){this.bandIds=this._params.bandIds=null;a||this.refresh(!0)},setDisableClientCaching:function(a){this.disableClientCaching=a},setMosaicRule:function(a,
b){var d=!1;this.mosaicRule!==a&&(d=!0);this.mosaicRule=a;this._params.mosaicRule=c.toJson(a.toJson());if(d&&!b)this.onMosaicRuleChange();b||this.refresh(!0)},setRenderingRule:function(a,b){var d=!1;this.renderingRule!==a&&(d=!0);this.renderingRule=a;this._params.renderingRule=a?c.toJson(a.toJson()):null;this._useRenderingRuleAttributeTable&&this._getRenderingRuleAttributeTable({renderingRule:a});if(d&&!b)this.onRenderingChange();b||this.refresh(!0)},setImageFormat:function(a,b){this.format=this._params.format=
a;b||this.refresh(!0)},setInfoTemplate:function(a){this.infoTemplate=a},setDefinitionExpression:function(a,b){var c=this.mosaicRule?this.mosaicRule.toJson():{};this.mosaicRule||(this.defaultMosaicRule?c=this.defaultMosaicRule.toJson():c.method=q.METHOD_NONE);c.where=a;c=new q(c);this.setMosaicRule(c,b);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:null},setPixelFilter:function(a){this.pixelFilter=a},getPixelData:function(a){return a?(this._useBrowserDecoding()&&
(this.originalPixelData={pixelBlock:this._getPixelBlockFromCanvas(this._context,this._map.width,this._map.height),extent:this._map.extent}),this.originalPixelData):this.pixelData},redraw:function(){this.hasDataChanged=!1;this._setPixelData(this.originalPixelData)},queryVisibleRasters:function(a,b,c,e){var f=this._map,g=v._fixDfd(new n(v._dfdCanceller));this._visibleRasters=[];var k,l,r=!0,w=this.infoTemplate?this.infoTemplate.info:null,p=w?d.clone(this.infoTemplate.info.fieldInfos):null;if(this.infoTemplate.info.mediaInfos&&
this.infoTemplate.info.mediaInfos.length){var u=[];h.forEach(this.infoTemplate.info.mediaInfos,function(a){u=u.concat(a&&a.value&&a.value.fields||[])});u.length&&h.forEach(p,function(a){a&&-1<u.indexOf(a.fieldName)&&(a.visible=!0)})}if(p&&0<p.length){r=!1;for(k=0;k<p.length;k++)if((l=p[k])&&l.fieldName.toLowerCase()!==this._rasterFieldPrefix.toLowerCase()+"servicepixelvalue"&&(l.visible||w.title&&-1<w.title.toLowerCase().indexOf(l.fieldName.toLowerCase()))){r=!0;break}}var q=(l=this._removeVisualizationStretchFunction(this.renderingRule))&&
l.functionName,t=[];if(10.4<=this.version){var x=!1;if(this.rasterFunctionInfos&&p){var A=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;h.forEach(this.rasterFunctionInfos,function(a){var b=A+a.name.replace(/ /gi,"_");h.some(p,function(a){return a.visible&&a.fieldName===b})&&(x=x||q&&q===a.name,t.push(new s({rasterFunction:a.name})))})}l&&!x&&t.push(l)}k=new P;k.geometry=a.geometry;k.returnGeometry=this._map.spatialReference.equals(this.spatialReference);k.returnCatalogItems=r;k.timeExtent=
a.timeExtent;k.mosaicRule=this.mosaicRule||null;k.renderingRule=10.4>this.version&&l||null;k.renderingRules=t||null;f&&(a=new m((f.extent.xmax-f.extent.xmin)/(2*f.width),(f.extent.ymax-f.extent.ymin)/(2*f.height),f.extent.spatialReference),k.pixelSize=a);b.requestParams=k;var y=this;a=new L(this.url);(g._pendingDfd=a.execute(k)).addCallbacks(function(a){y._queryVisibleRastersHandler(a,b,c,e,g)},function(a){y._resolve([a],null,e,g,!0)});return g},_queryVisibleRastersHandler:function(a,b,e,f,g){function k(){var a=
this.getCustomRasterFields(b),c=this._getDomainFields(a),f=b?b.returnDomainValues:!1,K=b&&b.rasterAttributeTableFieldPrefix,q,s,I,u,t,v,x,y,z,A;this._useRenderingRuleAttributeTable&&this.renderingRule?(a=this._getRenderingRuleAttributeTableFeatures({renderingRule:this.renderingRule}),A=l):a=this._getRasterAttributeTableFeatures();a.then(d.hitch(this,function(a){for(q=0;q<p.length;q++){D=p[q];D.setInfoTemplate(this.infoTemplate);D._layer=this;if(l){z=l.replace(/ /gi,"").split(",");s=l;I=z;m&&m.length>=
q&&(s=m[q].replace(/ /gi,", "),I=m[q].split(" "));D.attributes[this._rasterFieldPrefix+"ItemPixelValue"]=I;D.attributes[this._rasterFieldPrefix+"ServicePixelValue"]=z;n&&(D.attributes[this._rasterFieldPrefix+"ServicePixelValue.Raw"]=n.replace(/ /gi,"").split(","));if(this.pixelFilter){var b=new E({height:1,width:1,pixelType:"F32",pixels:[],statistics:[]});h.forEach(I,function(a){b.addData({pixels:[a],statistics:{minValue:a,maxValue:a,noDataValue:null}})});this.pixelFilter({pixelBlock:b,extent:new r(0,
0,0,0,this._map.spatialReference)});if("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType)D.attributes[this._rasterFieldPrefix+"Magnitude"]=b.pixels[0][0],D.attributes[this._rasterFieldPrefix+"Direction"]=b.pixels[1][0]}h.forEach(B,function(a){D.attributes[a.name]=a.value});var k=A||s;if(a&&0<a.length&&(u=h.filter(a,function(a){if(a&&a.attributes)return a.attributes.hasOwnProperty("Value")?a.attributes.Value==k:a.attributes.VALUE==
k}),0<u.length&&(t=d.clone(u[0]),K&&t))){y={};for(v in t.attributes)t.attributes.hasOwnProperty(v)&&(x=K+v,y[x]=t.attributes[v]);t.attributes=y;D.attributes=d.mixin(D.attributes,t.attributes)}}f&&(c&&0<c.length)&&h.forEach(c,function(a){if(a){var b=D.attributes[a.name];w.isDefined(b)&&(b=this._getDomainValue(a.domain,b),w.isDefined(b)&&(D.attributes[a.name]=b))}},this);R.push(D);this._visibleRasters.push(D)}this._resolve([R,null,!0],null,e,g)}))}var l=a.value,n=a.value,m,p,q=0,s=0,t=this,x=this.objectIdField,
v,y,B=[];f=b.requestParams.renderingRules;var z=a.processedValues,F=this.renderingRule&&dojo.toJson(this._removeVisualizationStretchFunction(this.renderingRule).toJson());if(f&&z&&f.length===z.length){var L=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;h.forEach(f,function(a,b){if(a.functionName){var c={name:L+a.functionName.replace(/ /gi,"_"),value:z[b].replace(/ /gi,"").split(",")};B.push(c);F&&F===dojo.toJson(a.toJson())&&(l=z[b])}})}f=this.infoTemplate&&this.infoTemplate.info&&this.infoTemplate.info.layerOptions&&
this.infoTemplate.info.layerOptions.hasOwnProperty("showNoDataRecords")?this.infoTemplate.info.layerOptions.showNoDataRecords:!0;if(a.catalogItems){var P=0,T,N,O=a.catalogItems.features.length;y=0;p=Array(O);m=Array(O);v=Array(O);for(q=0;q<O;q++)-1<a.properties.Values[q].toLowerCase().indexOf("nodata")&&y++;T=O-y;for(q=0;q<O;q++)y=!0,-1<a.properties.Values[q].toLowerCase().indexOf("nodata")?(N=T++,f||(y=!1,p.length--,m.length--,v.length--)):N=P++,y&&(p[N]=a.catalogItems.features[q],m[N]=a.properties.Values[q],
v[N]=p[N].attributes[x])}this._visibleRasters=[];var D;if((a=-1<l.toLowerCase().indexOf("nodata"))&&!f)p=[],m=[],v=[];l&&(!p&&!a)&&(x="ObjectId",p=[],D=new C(new r(this.fullExtent),null,{ObjectId:0}),p.push(D));var R=[];p?!this._map.spatialReference.equals(this.spatialReference)&&v&&0<v.length?u({url:this._url.path+"/query",content:{f:"json",objectIds:v.join(","),returnGeometry:!0,outSR:c.toJson(t._map.spatialReference.toJson()),outFields:x},handleAs:"json",callbackParamName:"callback",load:function(a){if(0===
a.features.length)t._resolve([R,null,null],null,e,g);else{for(q=0;q<a.features.length;q++)for(s=0;s<p.length;s++)p[s].attributes[x]==a.features[q].attributes[x]&&(p[s].geometry=new A(a.features[q].geometry),p[s].geometry.setSpatialReference(t._map.spatialReference));k.call(t)}},error:function(a){t._resolve([R,null,null],null,e,g)}}):k.call(this):this._resolve([R,null,null],null,e,g)},getVisibleRasters:function(){var a=this._visibleRasters,b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(a[c]);return b},
_getDomainFields:function(a){if(a){var b=[];h.forEach(a,function(a){if(a.domain){var c={};c.name=a.name;c.domain=a.domain;b.push(c)}});return b}},_getDomainValue:function(a,b){if(a&&a.codedValues){var c;h.some(a.codedValues,function(a){return a.code===b?(c=a.name,!0):!1});return c}},_requestData:function(a,b,c){this._rasterReadPromise&&this._rasterReadPromise.cancel();a=d.clone(a);var e=a._normalize(!0);this._prepareGetImageParameters(e,b,c);b=d.clone(this._params);this._cleanupRequestParams(b);b.extent=
a;c=null;this._useBrowserDecoding()&&(c=new F({ctx:this._context}));b={imageServiceParameters:b,nBands:Math.min(this.bandCount,3),pixelType:this.pixelType,decodeFunc:c?d.hitch(c,"decode"):null};this._rasterReadPromise=this.raster.read(b,this._requestDataHandler,this._requestDataErrorHandler)},_requestDataHandler:function(a){if(!this._rasterReadPromise||!this._rasterReadPromise.isCanceled())this.originalPixelData=a,this.hasDataChanged=!0,this._setPixelData(a)},_setPixelData:function(a){a=this._clonePixelData(a);
this.pixelFilter&&this.pixelFilter(a);this.pixelData=a;if(!this._rasterReadPromise||!this._rasterReadPromise.isCanceled())this._drawPixelData(),this._rasterReadPromise=null},_drawPixelData:function(){},_requestDataErrorHandler:function(a){},_clonePixelData:function(a){if(null===a||void 0===a)return a;var b={};a.extent&&(b.extent=d.clone(a.extent));a=a.pixelBlock;if(null===a||void 0===a)return b;b.pixelBlock=a.clone();return b},_getPixelBlockFromCanvas:function(a,b,c){a=a.getImageData(0,0,b,c).data;
for(var d=b*c,e=0,f=0,g=new Uint8Array(d),h=new Uint8Array(d),k=new Uint8Array(d),l=new Uint8Array(d),m=Infinity,n=Infinity,p=Infinity,q=-Infinity,r=-Infinity,t=-Infinity,s,u,v,e=0;e<d;e++)s=a[f++],u=a[f++],v=a[f++],m=m<s?m:s,q=q>s?q:s,n=n<u?n:u,r=r>u?r:u,p=p<v?p:v,t=t>v?t:v,g[e]=s,h[e]=u,k[e]=v,l[e]=a[f++]&1;return new E({width:b,height:c,pixels:[g,h,k],pixelType:"U8",mask:l,statistics:[{minValue:m,maxValue:q},{minValue:n,maxValue:r},{minValue:p,maxValue:t}]})},_useBrowserDecoding:function(){return(void 0===
this.pixelFilter||null===this.pixelFilter)&&("jpeg"==this.format.toLowerCase()||-1<this.format.toLowerCase().indexOf("png"))},getMultidimensionalInfo:function(){var b=this._url.path+"/multiDimensionalInfo",c=new n(v._dfdCanceller);if(this._multidimensionalInfo)return c.resolve(this._multidimensionalInfo),c;10.3<=this.version&&this.hasMultidimensions?(c._pendingDfd=u({url:b,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(d.hitch(this,function(a){this._multidimensionalInfo=
a.multidimensionalInfo;c.callback(a.multidimensionalInfo)}),function(a){c.errback(a)})):(b=Error("Layer does not support multidimensional info"),b.log=a.isDebug,c.errback(b));return c},getDefaultMultidimensionalDefinition:function(){var a,b,c,e=[],f=new n(v._dfdCanceller);if(this._defaultMultidimensionalDefinition)return f.resolve(this._defaultMultidimensionalDefinition),f;f._pendingDfd=this.getMultidimensionalInfo();f._pendingDfd.then(d.hitch(this,function(d){a=d;b=a.variables[0].dimensions;for(c in b)b.hasOwnProperty(c)&&
(b[c].hasRanges&&!0==b[c].hasRanges?e.push(new p({variableName:"",dimensionName:b[c].name,isSlice:!1,values:[b[c].values[0]]})):e.push(new p({variableName:"",dimensionName:b[c].name,isSlice:!0,values:[b[c].extent[0]]})));this._defaultMultidimensionalDefinition=e;f.callback(e)}),function(a){f.errback(a)});return f},_setDefaultMultidimensionalDefinition:function(a){var b,c={};this.getDefaultMultidimensionalDefinition().then(d.hitch(this,function(e){b=e;0<b.length&&(this.mosaicRule?(c=d.clone(this.mosaicRule),
c.multidimensionalDefinition=b):this.defaultMosaicRule?(c=d.clone(this.defaultMosaicRule),c.multidimensionalDefinition=b):c=new q({multidimensionalDefinition:b}),this.setMosaicRule(c,a))}))},_setDefaultRenderingRule:function(a){var b={};if(!this.renderingRule&&"esri.layers.ArcGISImageServiceVectorLayer"!==this.declaredClass&&this.rasterFunctionInfos&&this.rasterFunctionInfos.length&&"none"!==this.rasterFunctionInfos[0].name.toLowerCase())b.rasterFunction=this.rasterFunctionInfos[0].name;else if(!this.renderingRule&&
"esri.layers.ArcGISImageServiceVectorLayer"==this.declaredClass&&10.3<this.version){var c="esriImageServiceDataTypeVector-UV"===this.serviceDataType?7:10;b.rasterFunction="Resample";b.rasterFunctionArguments={ResamplingType:c,InputCellSize:{x:this.pixelSizeX,y:this.pixelSizeY}}}b.hasOwnProperty("rasterFunction")&&(this.defaultRenderingRule=new s(b),this.setRenderingRule(this.defaultRenderingRule,a))},_cleanupRequestParams:function(a){if(!a)return a;if(a.time&&a.mosaicRule){var b=new q(c.fromJson(a.mosaicRule));
if(b&&b.multidimensionalDefinition&&0<b.multidimensionalDefinition.length){var d=h.filter(b.multidimensionalDefinition,function(a){return"StdTime"!==a.dimensionName});b.multidimensionalDefinition=d;a.mosaicRule=c.toJson(b.toJson())}}var b="displayOnPan drawMode styling id opacity visible resourceInfo useMapDimensionValue extent".split(" "),e;for(e in b)a.hasOwnProperty(b[e])&&delete a[b[e]];return a},_removeVisualizationStretchFunction:function(a){var b=a&&a.functionName;if(!b||"stretch"!==b.toLowerCase())return a;
var c=a.functionArguments.Raster;return c&&c.functionName&&h.some(this.rasterFunctionInfos,function(a){return c.functionName===a.name})?c:a},_isScientificData:function(){return"esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType||"esriImageServiceDataTypeScientific"===this.serviceDataType},_isVectorData:function(){return"esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType},
_isRasterFunctionInfoAvailable:function(a){return h.some(a&&(this.rasterFunctionInfos||[]),function(b){return b&&b.name&&b.name.toLowerCase()===a.toLowerCase()})},_createPixelData:function(a){a=new E({width:2,height:2,pixels:a,pixelType:this.pixelType,statistics:a});var b=this.fullExtent.getCenter(),b=new r(b.x,b.y,b.x+this.pixelSizeX,b.y+this.pixelSizeY,this.spatialReference);return{pixelBlock:a,extent:b}},_resolve:function(a,b,c,d,e){b&&this[b].apply(this,a);c&&c.apply(null,a);d&&v._resDfd(d,a,
e)},_toggleTime:function(){var a=this._map;this.timeInfo&&this.useMapTime&&a&&!this.suspended?(this._timeConnect||(this._timeConnect=e.connect(a,"onTimeExtentChange",this,this._onTimeExtentChangeHandler)),this._setTime(a.timeExtent)):(e.disconnect(this._timeConnect),this._timeConnect=null,this._setTime(null))},setUseMapTime:function(a,b){this.useMapTime=a;this._toggleTime();!b&&this._map&&this.refresh(!0)},_setTime:function(a){this._params&&(this._params.time=a?a.toJson().join(","):null)},_onTimeExtentChangeHandler:function(a){this.suspended||
(this._setTime(a),this.refresh(!0))}});b("extend-esri")&&d.setObject("layers.ImageServiceLayerMixin",k,g);return k})},"*noref":1}});
define("esri/layers/ArcGISImageServiceLayer","dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../config ./DynamicMapServiceLayer ./ImageServiceLayerMixin".split(" "),function(k,d,n,h,c,a,e){k=k([a,e],{declaredClass:"esri.layers.ArcGISImageServiceLayer",constructor:function(a,c){this._initialize(a,c);this.useMapImage=c&&c.useMapImage||!1},refresh:function(a){if(a)this.inherited(arguments);else{var c=this.disableClientCaching;this.disableClientCaching=!0;this.inherited(arguments);this.disableClientCaching=
c}},exportMapImage:function(a,e){var g=c.defaults.map,g=d.mixin({size:g.width+","+g.height},this._params,a?a.toJson(this.normalization):{},{f:"json"});delete g._ts;this._exportMapImage(this._url.path+"/exportImage",g,e)}});n("extend-esri")&&d.setObject("layers.ArcGISImageServiceLayer",k,h);return k});