// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define([],function(){function R(b,a,c,e,m){var n=0,l,f,h;l=a;for(f=c-e;l<c;l+=e)n+=(b[f]-b[l])*(b[l+1]+b[f+1]),f=l;if(m===0<n)for(l=a;l<c;l+=e)h=S(l,h);else for(l=c-e;l>=a;l-=e)h=S(l,h);return h}function H(b,a,c){c||(c=a);var e;do if(e=!1,!a.steiner&&(b[a.i]===b[a.next.i]&&b[a.i+1]===b[a.next.i+1]||0===x(b,a.prev.i,a.i,a.next.i))){a.prev.next=a.next;a.next.prev=a.prev;a.prevZ&&(a.prevZ.nextZ=a.nextZ);a.nextZ&&(a.nextZ.prevZ=a.prevZ);a=c=a.prev;if(a===a.next)return null;e=!0}else a=a.next;while(e||
a!==c);return c}function J(b,a,c,e,m,n,l,f){if(a){if(!f&&void 0!==m){var h=a,d=h;do null===d.z&&(d.z=N(b[d.i],b[d.i+1],m,n,l)),d.prevZ=d.prev,d=d.nextZ=d.next;while(d!==h);d.prevZ.nextZ=null;d.prevZ=null;var h=d,q,g,k,p,s,G,u=1;do{d=h;k=h=null;for(p=0;d;){p++;g=d;for(q=s=0;q<u&&!(s++,g=g.nextZ,!g);q++);for(G=u;0<s||0<G&&g;)0===s?(q=g,g=g.nextZ,G--):0===G||!g?(q=d,d=d.nextZ,s--):d.z<=g.z?(q=d,d=d.nextZ,s--):(q=g,g=g.nextZ,G--),k?k.nextZ=q:h=q,q.prevZ=k,k=q;d=g}k.nextZ=null;u*=2}while(1<p)}for(h=a;a.prev!==
a.next;){d=a.prev;g=a.next;a:{k=b;p=a;q=m;G=n;var B=l;s=p.prev.i;var z=p.i,u=p.next.i,y=k[s],A=k[s+1],E=k[z],F=k[z+1],C=k[u],D=k[u+1],z=y*F-A*E,L=y*D-A*C,M=z-L-(C*F-D*E);if(0>=M)k=!1;else{var I=D-A,O=y-C,P=A-F,Q=E-y,r=void 0,t=void 0,v=void 0,w=v=t=r=void 0;if(void 0!==q){w=y>E?y>C?y:C:E>C?E:C;r=A>F?A>D?A:D:F>D?F:D;y=N(y<E?y<C?y:C:E<C?E:C,A<F?A<D?A:D:F<D?F:D,q,G,B);q=N(w,r,q,G,B);for(w=p.nextZ;w&&w.z<=q;)if(r=w.i,w=w.nextZ,!(r===s||r===u))if(t=k[r],v=k[r+1],r=I*t+O*v-L,0<=r&&(t=P*t+Q*v+z,0<=t&&(v=
M-r-t,0<=v&&(r&&t||r&&v||t&&v)))){k=!1;break a}for(w=p.prevZ;w&&w.z>=y;)if(r=w.i,w=w.prevZ,!(r===s||r===u))if(t=k[r],v=k[r+1],r=I*t+O*v-L,0<=r&&(t=P*t+Q*v+z,0<=t&&(v=M-r-t,0<=v&&(r&&t||r&&v||t&&v)))){k=!1;break a}}else for(w=p.next.next;w!==p.prev;)if(r=w.i,w=w.next,t=k[r],v=k[r+1],r=I*t+O*v-L,0<=r&&(t=P*t+Q*v+z,0<=t&&(v=M-r-t,0<=v&&(r&&t||r&&v||t&&v)))){k=!1;break a}k=!0}}if(k)c.push(d.i/e),c.push(a.i/e),c.push(g.i/e),g.prev=d,d.next=g,a.prevZ&&(a.prevZ.nextZ=a.nextZ),a.nextZ&&(a.nextZ.prevZ=a.prevZ),
h=a=g.next;else if(a=g,a===h){if(f)if(1===f){f=b;k=a;a=c;h=e;g=k;do p=g.prev,d=g.next.next,p.i!==d.i&&(x(f,p.i,g.i,g.next.i)!==x(f,p.i,g.i,d.i)&&x(f,g.next.i,d.i,p.i)!==x(f,g.next.i,d.i,g.i)&&K(f,p,d)&&K(f,d,p))&&(a.push(p.i/h),a.push(g.i/h),a.push(d.i/h),p.next=d,d.prev=p,k=g.prevZ,g=g.nextZ&&g.nextZ.nextZ,k&&(k.nextZ=g),g&&(g.prevZ=k),g=k=d),g=g.next;while(g!==k);a=g;J(b,a,c,e,m,n,l,2)}else{if(2===f)a:{f=a;do{for(h=f.next.next;h!==f.prev;){if(d=f.i!==h.i)if(d=f.next.i!==h.i)if(d=f.prev.i!==h.i){b:{d=
b;g=f;k=f.i;p=h.i;s=g;do{u=s.i;q=s.next.i;if(u!==k&&q!==k&&u!==p&&q!==p&&x(d,u,q,k)!==x(d,u,q,p)&&x(d,k,p,u)!==x(d,k,p,q)){d=!0;break b}s=s.next}while(s!==g);d=!1}if(d=!d)if(d=K(b,f,h))if(d=K(b,h,f)){p=f.i;s=h.i;d=f;g=!1;k=(b[p]+b[s])/2;p=(b[p+1]+b[s+1])/2;do s=d.i,u=d.next.i,b[s+1]>p!==b[u+1]>p&&k<(b[u]-b[s])*(p-b[s+1])/(b[u+1]-b[s+1])+b[s]&&(g=!g),d=d.next;while(d!==f);d=g}}if(d){a=T(f,h);f=H(b,f,f.next);a=H(b,a,a.next);J(b,f,c,e,m,n,l);J(b,a,c,e,m,n,l);break a}h=h.next}f=f.next}while(f!==a)}}else J(b,
H(b,a),c,e,m,n,l,1);break}}}}function U(b,a,c,e){var m=[],n,l,f,h;n=0;for(l=a.length;n<l;n++)f=a[n]*e,h=n<l-1?a[n+1]*e:b.length,f=R(b,f,h,e,!1),f===f.next&&(f.steiner=!0),(f=H(b,f))&&m.push(V(b,f));m.sort(function(a,c){return b[a.i]-b[c.i]});for(n=0;n<m.length;n++)W(b,m[n],c),c=H(b,c,c.next);return c}function W(b,a,c){var e=c,m=a.i,n=b[m],m=b[m+1],l=-Infinity,f,h,d;do{h=e.i;d=e.next.i;if(m<=b[h+1]&&m>=b[d+1]){var q=b[h]+(m-b[h+1])*(b[d]-b[h])/(b[d+1]-b[h+1]);q<=n&&q>l&&(l=q,f=b[h]<b[d]?e:e.next)}e=
e.next}while(e!==c);if(f){c=b[f.i];e=b[f.i+1];h=n*e-m*c;d=n*m-m*l;for(var q=m-m,g=n-l,k=m-e,p=c-n,l=h-d-(l*e-m*c),s=0>=l?-1:1,x=f,u=Infinity,B,z,y,A,e=f.next;e!==x;)B=b[e.i],z=b[e.i+1],y=n-B,0<=y&&B>=c&&(A=(q*B+g*z-d)*s,0<=A&&(B=(k*B+p*z+h)*s,0<=B&&0<=l*s-A-B&&(z=Math.abs(m-z)/y,z<u&&K(b,e,a)&&(f=e,u=z)))),e=e.next;c=f}else c=null;c&&(a=T(c,a),H(b,a,a.next))}function N(b,a,c,e,m){b=1E3*(b-c)/m;b=(b|b<<8)&16711935;b=(b|b<<4)&252645135;b=(b|b<<2)&858993459;a=1E3*(a-e)/m;a=(a|a<<8)&16711935;a=(a|a<<
4)&252645135;a=(a|a<<2)&858993459;return(b|b<<1)&1431655765|((a|a<<1)&1431655765)<<1}function V(b,a){var c=a,e=a;do b[c.i]<b[e.i]&&(e=c),c=c.next;while(c!==a);return e}function x(b,a,c,e){b=(b[c+1]-b[a+1])*(b[e]-b[c])-(b[c]-b[a])*(b[e+1]-b[c+1]);return 0<b?1:0>b?-1:0}function K(b,a,c){return-1===x(b,a.prev.i,a.i,a.next.i)?-1!==x(b,a.i,c.i,a.next.i)&&-1!==x(b,a.i,a.prev.i,c.i):-1===x(b,a.i,c.i,a.prev.i)||-1===x(b,a.i,a.next.i,c.i)}function T(b,a){var c=new I(b.i),e=new I(a.i),m=b.next,n=a.prev;b.next=
a;a.prev=b;c.next=m;m.prev=c;e.next=c;c.prev=e;n.next=e;e.prev=n;return e}function S(b,a){var c=new I(b);a?(c.next=a.next,c.prev=a,a.next.prev=c,a.next=c):(c.prev=c,c.next=c);return c}function I(b){this.i=b;this.nextZ=this.prevZ=this.z=this.next=this.prev=null;this.steiner=!1}return function(b,a,c){c=c||2;var e=a&&a.length,m=e?a[0]*c:b.length,n=H(b,R(b,0,m,c,!0)),l=[];if(!n)return l;var f,h,d,q;e&&(n=U(b,a,n,c));if(b.length>80*c){f=a=b[0];h=e=b[1];for(var g=c;g<m;g+=c)d=b[g],q=b[g+1],d<f&&(f=d),q<
h&&(h=q),d>a&&(a=d),q>e&&(e=q);d=Math.max(a-f,e-h)}J(b,n,l,c,f,h,d);return l}});