// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../../Color ../../../renderers/SimpleRenderer ../../../renderers/ClassBreaksRenderer ../../../renderers/UniqueValueRenderer ../../../core/Accessor ./colorRampUtils ./sizeRampUtils dojo/_base/lang".split(" "),function(t,u,p,v,w,q,x,h){return w.createSubclass({properties:{layer:{},legendElements:{type:Array},ready:{},tearingDown:{},title:{},version:{readOnly:!0,dependsOn:["ready"]}},declaredClass:"esri.widgets.Legend.support.ActiveLayerInfo",getDefaults:function(){return{ready:!1,tearingDown:!1,
legendElements:[]}},layer:null,legendElements:null,ready:!1,tearingDown:!1,title:null,version:0,_versionGetter:function(){return this._get("version")+1},buildLegendElements:function(a,c){var b=a.visualVariables,d=[],g=this.layer.opacity,e=null,n=null,l=!1,k=[],f=[],h=[];b&&(b.forEach(function(a){"color"===a.type?k.push(a):"opacity"===a.type?f.push(a):"size"===a.type&&h.push(a)}),b=[],Array.prototype.push.apply(b,k),Array.prototype.push.apply(b,f),Array.prototype.push.apply(b,h),0===k.length&&(a.isInstanceOf(p)&&
a.classBreakInfos&&1===a.classBreakInfos.length)&&(n=(d=a.classBreakInfos[0])&&d.symbol.color.toRgba()),d=b.map(function(b){var d=this._getRampTitle(b,this.layer),h=q._getRampBorderColor(a),k=q._getRampOverlayColor(g),f;"color"===b.type?(e=this._getMedianColor(a,b),f={type:"color-ramp",title:d,borderColor:h,overlayColor:k,infos:q._getRampStops(a,b)}):"opacity"===b.type?f={type:"opacity-ramp",title:d,borderColor:h,overlayColor:k,infos:q._getRampStops(a,b,n)}:"size"===b.type&&(f={type:"size-ramp",title:d,
infos:x._getRampStops(a,b,e,c)},l||(l=!!f.infos));return f.infos&&f},this).filter(function(a){return!!a}));var m={type:"symbol-table",title:this._getRendererTitle(a,this.layer),infos:[]};if(a.isInstanceOf(p)){var r=this._isUnclassedRenderer(a,b);if(!r||!l)b=a.classBreakInfos.slice().reverse(),m.infos=b.map(function(a){return{label:a.label||(r?null:a.minValue+" - "+a.maxValue),value:[a.minValue,a.maxValue],symbol:this._getAppliedCloneSymbol(a.symbol,e,g)}},this),r&&(m.title=null)}a.isInstanceOf(v)&&
(m.infos=a.uniqueValueInfos.map(function(a){return{label:a.label||a.value,value:a.value,symbol:this._getAppliedCloneSymbol(a.symbol,e,g)}},this));var b=a.label||a.defaultLabel,s=a.symbol||a.defaultSymbol;s&&!r&&m.infos.push({label:a.isInstanceOf(u)?b:b||"others",symbol:this._getAppliedCloneSymbol(s,e,g)});0<m.infos.length&&this.legendElements.push(m);Array.prototype.push.apply(this.legendElements,d)},_getMedianColor:function(a,c){var b,d;c.colors?(b=c.minDataValue,d=c.maxDataValue):c.stops&&(b=c.stops[0].value,
d=c.stops[c.stops.length-1].value);return a.getColor(b+(d-b)/2,{colorInfo:c})},_getAppliedCloneSymbol:function(a,c,b){a=a.clone();var d=a.type;c&&(a.color=new t(c.toRgba()));if("simple-line-symbol"===d||"cartographic-line-symbol"===d||"text-symbol"===d){if(!a.color)return;c=a.color.toRgba();c[3]*=b;a.color=c}else if("simple-marker-symbol"===d||"simple-fill-symbol"===d)a.color&&(c=a.color.toRgba(),c[3]*=b,a.color=c),a.outline&&a.outline.color&&(c=a.outline.color.toRgba(),c[3]*=b,a.outline.color=c);
return a},_getRampTitle:function(a,c){var b=a.field,d=a.normalizationField,g=!1,e=!1,n=!1,b=h.isFunction(b)?null:b,d=h.isFunction(d)?null:d;if(a.legendOptions&&a.legendOptions.title)b=a.legendOptions.title;else{if(c.renderer.authoringInfo&&c.renderer.authoringInfo.visualVariables)for(var l=c.renderer.authoringInfo.visualVariables,k=0;k<l.length;k++){var f=l[k];if("colorInfo"===f.type)if("ratio"===f.style){g=!0;break}else if("percent"===f.style){e=!0;break}else if("percentTotal"===f.style){n=!0;break}}b=
{field:b&&this._getFieldAlias(b,c),normField:d&&this._getFieldAlias(d,c),ratio:g,ratioPercent:e,ratioPercentTotal:n}}return b},_getRendererTitle:function(a,c){var b=a.field,d,g,e;a instanceof p&&(d=a.normalizationField,g="percent-of-total"===a.normalizationType);b=h.isFunction(b)?null:b;d=h.isFunction(d)?null:d;if(b||d)e={field:b&&this._getFieldAlias(b,c),normField:d&&this._getFieldAlias(d,c),normByPct:g};return e},_getFieldAlias:function(a,c){var b=c.popupTemplate,d=b&&b.fieldInfos,b=h.isFunction(a)?
null:c.getField(a),g,e;d&&d.some(function(b){if(a===b.fieldName)return e=b,!0});(d=e||b)&&(g=e&&e.label||b&&b.alias||d.name||d.fieldName);return g},_isUnclassedRenderer:function(a,c){var b=!1;a.isInstanceOf(p)&&(a.classBreakInfos&&1===a.classBreakInfos.length)&&c&&(b=c.some(function(b){return!(!b||!(a.field===b.field&&a.normalizationField==b.normalizationField))}));return b}})});