// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/array ../core/declare dojo/_base/lang dojo/Deferred dojo/io-query ../request ../geometry/support/normalizeUtils ../layers/MapImageLayer ../layers/support/MapImage ./Task ./support/DataFile ./support/Date ./support/FeatureSet ./support/GPMessage ./support/GPResultImageLayer ./support/JobInfo ./support/LinearUnit ./support/ParameterValue ./support/RasterData".split(" "),function(k,h,e,m,n,g,p,q,r,s,t,u,v,w,x,l,y,z,A){h=h(s,{declaredClass:"esri.tasks.Geoprocessor",url:null,constructor:function(){this._updateTimers=
[];this._handleExecuteResponse=this._handleExecuteResponse.bind(this);this._handleGetResultImageResponse=this._handleGetResultImageResponse.bind(this);this._handleGetResultDataResponse=this._handleGetResultDataResponse.bind(this)},updateDelay:1E3,processSpatialReference:null,outSpatialReference:null,__msigns:[{n:"execute",c:1,a:[{i:0,p:["*"]}],e:2},{n:"submitJob",c:1,a:[{i:0,p:["*"]}],e:3}],_gpEncode:function(a,c,b){for(var d in a){var f=a[d];e.isArray(f)?a[d]=JSON.stringify(k.map(f,function(a){return this._gpEncode({item:a},
!0).item},this)):f instanceof Date&&(a[d]=f.getTime())}return this._encode(a,c,b)},_decode:function(a){var c=a.dataType,b=z.fromJSON(a);if(-1!==k.indexOf(["GPBoolean","GPDouble","GPLong","GPString"],c))return b;if("GPLinearUnit"===c)b.value=y.fromJSON(b.value);else if("GPFeatureRecordSetLayer"===c||"GPRecordSet"===c)b.value=v.fromJSON(b.value);else if("GPDataFile"===c)b.value=t.fromJSON(b.value);else if("GPDate"===c)a=b.value,e.isString(a)?b.value=u.fromJSON({date:a}):b.value=Date.fromJSON(a);else if("GPRasterData"===
c||"GPRasterDataLayer"===c)a=a.value.mapImage,b.value=a?r.fromJSON(a):A.fromJSON(b.value);else if(-1!==c.indexOf("GPMultiValue:")){var d=c.split(":")[1];a=b.value;b.value=k.map(a,function(a){return this._decode({paramName:"_name",dataType:d,value:a}).value},this)}else console.log(this.declaredClass+" : GP Data type not handled. : "+b.dataType),b=null;return b},submitJob:function(a,c){var b=this.outSpatialReference,d=c.assembly,b=this._gpEncode(e.mixin({},this.parsedUrl.query,{f:"json","env:outSR":b?
b.wkid||JSON.stringify(b.toJSON()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||JSON.stringify(this.processSpatialReference.toJSON()):null},a),null,d&&d[0]),f=new m,h=this._jobUpdateHandler.bind(this);g(this.parsedUrl.path+"/submitJob",{query:b,callbackParamName:"callback"}).then(function(a){h(a.data,f)}).then(null,function(a){f.reject(a)});return f.promise},_jobUpdateHandler:function(a,c){var b=a.jobId,d=l.fromJSON(a),f,e;clearTimeout(this._updateTimers[b]);
this._updateTimers[b]=null;c.progress(d);switch(d.jobStatus){case "job-submitted":case "job-executing":case "job-waiting":case "job-new":f=this._getJobStatus.bind(this);e=this._jobUpdateHandler.bind(this);this._updateTimers[b]=setTimeout(function(){f(b).then(function(a){e(a,c)})},this.updateDelay);break;default:c.resolve(d)}},_getJobStatus:function(a){return g(this.parsedUrl.path+"/jobs/"+a,{query:e.mixin({},this.parsedUrl.query,{f:"json"}),callbackParamName:"callback"}).then(function(a){return a.data})},
getResultData:function(a,c){return g(this.parsedUrl.path+"/jobs/"+a+"/results/"+c,{query:e.mixin({},this.parsedUrl.query,{f:"json",returnType:"data"}),callbackParamName:"callback"}).then(this._handleGetResultDataResponse)},_handleGetResultDataResponse:function(a){return this._decode(a.data)},checkJobStatus:function(a){return g(this.parsedUrl.path+"/jobs/"+a,{query:e.mixin({},this.parsedUrl.query,{f:"json"}),callbackParamName:"callback"}).then(this._handleCheckJobStatusResponse)},_handleCheckJobStatusResponse:function(a){return l.fromJSON(a.data)},
cancelJob:function(a){return g(this.parsedUrl.path+"/jobs/"+a+"/cancel",{query:e.mixin({},this.parsedUrl.query,{f:"json"}),callbackParamName:"callback"}).then(function(a){return a.data})},execute:function(a,c){var b=this.outSpatialReference,d=c.assembly,b=this._gpEncode(e.mixin({},this.parsedUrl.query,{f:"json","env:outSR":b?b.wkid||JSON.stringify(b.toJSON()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||JSON.stringify(this.processSpatialReference.toJSON()):
null},a),null,d&&d[0]);return g(this.parsedUrl.path+"/execute",{query:b,callbackParamName:"callback"}).then(this._handleExecuteResponse)},_handleExecuteResponse:function(a){a=a.data;var c=a.messages||[];return{results:(a.results||[]).map(this._decode,this),messages:c.map(w.fromJSON)}},getResultImage:function(a,c,b){b=this._gpEncode(e.mixin({},this.parsedUrl.query,{f:"json"},b.toJSON()));return g(this.parsedUrl.path+"/jobs/"+a+"/results/"+c,{query:b,callbackParamName:"callback"}).then(this._handleGetResultImageResponse)},
_handleGetResultImageResponse:function(a){return this._decode(a.data)},cancelJobStatusUpdates:function(a){clearTimeout(this._updateTimers[a]);this._updateTimers[a]=null},getResultImageLayer:function(a,c,b){if(null==c){var d=this.parsedUrl.path.indexOf("/GPServer/");a=this.parsedUrl.path.substring(0,d)+"/MapServer/jobs/"+a}else a=this.parsedUrl.path+"/jobs/"+a+"/results/"+c;this.parsedUrl.query&&(a+="?"+n.objectToQuery(this.parsedUrl.query));return null==c?new q(a,{imageParameters:b}):new x(a,{imageParameters:b})}});
p._createWrappers(h);return h});