// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/array ../core/declare dojo/_base/lang ../request ./Task ./support/AddressCandidate".split(" "),function(q,r,f,g,s,d){return r(s,{declaredClass:"esri.tasks.Locator",categories:null,countryCode:null,outSpatialReference:null,url:null,addressToLocations:function(a,c,b){var e,k,l,d,m,h,n;a.address&&(c=a.outFields,b=a.searchExtent,n=a.countryCode,e=a.magicKey,k=a.distance,h=a.categories,a.location&&this.normalization&&(l=a.location.clone().normalize()),d=a.maxLocations,m=a.forStorage,
a=a.address);b&&(b=b.shiftCentralMeridian());var p=this.outSpatialReference;a=this._encode(f.mixin({},this.parsedUrl.query,a,{f:"json",outSR:p&&JSON.stringify(p.toJSON()),outFields:c&&c.join(",")||null,searchExtent:b&&JSON.stringify(b.toJSON()),category:h&&h.join(",")||null,countryCode:n||null,magicKey:e||null,distance:k||null,location:l||null,maxLocations:d||null,forStorage:m||null}));return g(this.parsedUrl.path+"/findAddressCandidates",{query:a,callbackParamName:"callback"}).then(this._handleAddressToLocationsResponse)},
_handleAddressToLocationsResponse:function(a){a=a.data;var c=a.spatialReference,b;return(a.candidates||[]).map(function(a){if(b=a.location)b.spatialReference=c;return d.fromJSON(a)})},suggestLocations:function(a){a.hasOwnProperty("location")&&this.normalization&&(a.location=a.location.clone().normalize());a.searchExtent&&(a.searchExtent=a.searchExtent.shiftCentralMeridian());a=this._encode(f.mixin({},this.parsedUrl.query,{f:"json",text:a.text,maxSuggestions:a.maxSuggestions,searchExtent:a.searchExtent&&
JSON.stringify(a.searchExtent.toJSON()),category:a.categories&&a.categories.join(",")||null,countryCode:a.countryCode||null,location:a.location||null,distance:a.distance||null},{f:"json"}));return g(this.parsedUrl.path+"/suggest",{query:a,callbackParamName:"callback"}).then(this._handleSuggestLocationsResponse)},_handleSuggestLocationsResponse:function(a){return a.data.suggestions||[]},addressesToLocations:function(a){var c=this.outSpatialReference,b=[],e=a.categories,d=a.countryCode;q.forEach(a.addresses,
function(a,c){b.push({attributes:a})});a=this._encode(f.mixin({},this.parsedUrl.query,{category:e&&e.join(",")||null,sourceCountry:d||null},{addresses:JSON.stringify({records:b})},{f:"json",outSR:c&&JSON.stringify(c.toJSON())}));return g(this.parsedUrl.path+"/geocodeAddresses",{query:a,callbackParamName:"callback"}).then(this._handleAddressesToLocationsResponse)},_handleAddressesToLocationsResponse:function(a){a=a.data;var c=a.spatialReference,b;return(a.locations||[]).map(function(a){if(b=a.location)b.spatialReference=
c;return d.fromJSON(a)})},locationToAddress:function(a,c){a&&this.normalization&&(a=a.clone().normalize());var b=this.outSpatialReference,b=this._encode(f.mixin({},this.parsedUrl.query,{outSR:b&&JSON.stringify(b.toJSON()),location:a&&JSON.stringify(a.toJSON()),distance:c,f:"json"}));return g(this.parsedUrl.path+"/reverseGeocode",{query:b,callbackParamName:"callback"}).then(this._handleLocationToAddressResponse)},_handleLocationToAddressResponse:function(a){a=a.data;return d.fromJSON({address:a.address,
location:a.location,score:100})}})});