// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/array ../core/declare dojo/_base/lang ../request ../geometry/Extent ../geometry/support/normalizeUtils ./Task ./support/FeatureSet".split(" "),function(l,h,c,d,m,n,p,k){h=h(p,{declaredClass:"esri.tasks.QueryTask",source:null,gdbVersion:null,__msigns:[{n:"execute",c:2,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForIds",c:1,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForCount",c:1,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForExtent",c:1,a:[{i:0,p:["geometry"]}],e:2}],execute:function(a,
e,b){b=b.assembly;a=this._encode(c.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON(b&&b[0])));this.source&&(b={source:this.source.toJSON()},a.layer=JSON.stringify(b));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return d(this.parsedUrl.path+"/query",c.mixin({query:a,callbackParamName:"callback",callbackSuffix:e},this.requestOptions)).then(this._handleExecuteResponse)},executeRelationshipQuery:function(a){a=this._encode(c.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON()));this.gdbVersion&&
(a.gdbVersion=this.gdbVersion);return d(this.parsedUrl.path+"/queryRelatedRecords",c.mixin({query:a,callbackParamName:"callback"},this.requestOptions)).then(this._handleExecuteRelationshipQueryResponse)},executeForIds:function(a,e){var b=e.assembly,b=this._encode(c.mixin({},this.parsedUrl.query,{f:"json",returnIdsOnly:!0},a.toJSON(b&&b[0])));if(this.source){var g={source:this.source.toJSON()};b.layer=JSON.stringify(g)}this.gdbVersion&&(b.gdbVersion=this.gdbVersion);return d(this.parsedUrl.path+"/query",
c.mixin({query:b,callbackParamName:"callback"},this.requestOptions)).then(this._handleExecuteForIdsResponse)},executeForCount:function(a,e){var b=e.assembly,b=this._encode(c.mixin({},this.parsedUrl.query,{f:"json",returnIdsOnly:!0,returnCountOnly:!0},a.toJSON(b&&b[0])));if(this.source){var g={source:this.source.toJSON()};b.layer=JSON.stringify(g)}this.gdbVersion&&(b.gdbVersion=this.gdbVersion);return d(this.parsedUrl.path+"/query",c.mixin({query:b,callbackParamName:"callback"},this.requestOptions)).then(this._handleExecuteForCountResponse)},
executeForExtent:function(a,e){var b=e.assembly,b=this._encode(c.mixin({},this.parsedUrl.query,{f:"json",returnExtentOnly:!0,returnCountOnly:!0},a.toJSON(b&&b[0])));if(this.source){var g={source:this.source.toJSON()};b.layer=JSON.stringify(g)}this.gdbVersion&&(b.gdbVersion=this.gdbVersion);return d(this.parsedUrl.path+"/query",c.mixin({query:b,callbackParamName:"callback"},this.requestOptions)).then(this._handleExecuteForExtentResponse)},_handleExecuteResponse:function(a){return k.fromJSON(a.data)},
_handleExecuteRelationshipQueryResponse:function(a){a=a.data;var e=a.geometryType,b=a.spatialReference,c={};l.forEach(a.relatedRecordGroups,function(a){var f={};f.geometryType=e;f.spatialReference=b;f.features=a.relatedRecords;f=k.fromJSON(f);if(null!=a.objectId)c[a.objectId]=f;else for(var d in a)a.hasOwnProperty(d)&&"relatedRecords"!==d&&(c[a[d]]=f)});return c},_handleExecuteForIdsResponse:function(a){return a.data.objectIds},_handleExecuteForCountResponse:function(a){a=a.data;var c=a.features,
b=a.objectIds;if(b)a=b.length;else{if(c)throw Error("Unable to perform query. Please check your parameters.");a=a.count}return a},_handleExecuteForExtentResponse:function(a){a=a.data;if(a.hasOwnProperty("extent"))a.extent=m.fromJSON(a.extent);else{if(a.features)throw Error("Layer does not support extent calculation.");if(a.hasOwnProperty("count"))throw Error("Layer does not support extent calculation.");}return a}});n._createWrappers(h);return h});