// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["./GeometryData","./BufferVectorMath","./Util","./gl-matrix"],function(A,T,J,U){function Q(b,f,a,e,d){if(Math.abs(c.dot(f,b))>d)return!1;c.cross(b,f,a);c.normalize(a);c.cross(a,b,e);c.normalize(e);return!0}function R(b,f,a,e,d,h,g){return Q(b,f,d,h,g)||Q(b,a,d,h,g)||Q(b,e,d,h,g)}var c=U.vec3,M=U.vec3d,l=J.VertexAttrConstants,F=T.Vec3Compact,H=M.create(),V=M.create(),S={createSphereGeometry:function(b,f,a,e,d,h,g){b=b||50;e=void 0!==e?e:-Math.PI;d=void 0!==d?d:2*Math.PI;h=void 0!==h?h:0.5*
-Math.PI;g=void 0!==g?g:Math.PI;var k=Math.max(3,Math.floor(f)||8),m=Math.max(2,Math.floor(a)||6),n=(k+1)*(m+1);a=new Float32Array(3*n);f=new Float32Array(3*n);var n=new Float32Array(2*n),p,r,v=[],w=c.create(),s=0;for(r=0;r<=m;r++){var u=[],q=r/m,t=h+q*g,D=Math.cos(t);for(p=0;p<=k;p++){var z=p/k,x=e+z*d,B=Math.cos(x)*D*b,N=Math.sin(t)*b,x=-Math.sin(x)*D*b;a[3*s]=B;a[3*s+1]=N;a[3*s+2]=x;c.set3(B,N,x,w);c.normalize(w);f[3*s]=w[0];f[3*s+1]=w[1];f[3*s+2]=w[2];n[2*s]=z;n[2*s+1]=q;u.push(s);++s}v.push(u)}b=
new Uint32Array(3*2*k*(m-1));for(r=s=0;r<m;r++)for(p=0;p<k;p++)e=v[r][p],d=v[r][p+1],h=v[r+1][p+1],g=v[r+1][p],0===r?(b[s++]=e,b[s++]=h,b[s++]=g):r===m-1?(b[s++]=e,b[s++]=d,b[s++]=h):(b[s++]=e,b[s++]=d,b[s++]=h,b[s++]=h,b[s++]=g,b[s++]=e);J.assert(s===b.length);k={};k[l.POSITION]=b;k[l.NORMAL]=b;k[l.UV0]=b;m={};m[l.POSITION]={size:3,data:a};m[l.NORMAL]={size:3,data:f};m[l.UV0]={size:2,data:n};return new A([{type:"triangle",indices:k,positionKey:l.POSITION}],m)},createPolySphereGeometry:function(b,
f,a){function e(a,d){a>d&&(a=d+(d=a,0));var e=a.toString()+"."+d.toString();if(g[e])return g[e];var f=h.length;h.length+=3;F.add(h,3*a,h,3*d,h,f);F.scale(h,f,b/F.length(h,f));f/=3;return g[e]=f}var d=b,h;a?(h=[0,-1,0,1,0,0,0,0,1,-1,0,0,0,0,-1,0,1,0],d=[0,1,2,0,2,3,0,3,4,0,4,1,1,5,2,2,5,3,3,5,4,4,5,1]):(a=d*(1+Math.sqrt(5))/2,h=[-d,a,0,d,a,0,-d,-a,0,d,-a,0,0,-d,a,0,d,a,0,-d,-a,0,d,-a,a,0,-d,a,0,d,-a,0,-d,-a,0,d],d=[0,11,5,0,5,1,0,1,7,0,7,10,0,10,11,1,5,9,5,11,4,11,10,2,10,7,6,7,1,8,3,9,4,3,4,2,3,2,
6,3,6,8,3,8,9,4,9,5,2,4,11,6,2,10,8,6,7,9,8,1]);for(a=0;a<h.length;a+=3)F.scale(h,a,b/F.length(h,a));var g={};for(a=0;a<f;a++){for(var k=d.length,c=Array(4*k),n=0;n<k;n+=3){var p=d[n],r=d[n+1],v=d[n+2],w=e(p,r),s=e(r,v),u=e(v,p),q=4*n;c[q]=p;c[q+1]=w;c[q+2]=u;c[q+3]=r;c[q+4]=s;c[q+5]=w;c[q+6]=v;c[q+7]=u;c[q+8]=s;c[q+9]=w;c[q+10]=s;c[q+11]=u}d=c;g={}}f=new Float32Array(h);for(a=0;a<f;a+=3)F.normalize(f,a);h=new Float32Array(h);a={};a[l.POSITION]=d;a[l.NORMAL]=d;d={};d[l.POSITION]={size:3,data:h};d[l.NORMAL]=
{size:3,data:f};return new A([{type:"triangle",indices:a,positionKey:l.POSITION}],d)},createPointGeometry:function(b,f,a,e,d,h,g){var c=new Float32Array(3);c[0]=f?f[0]:0;c[1]=f?f[1]:0;c[2]=f?f[2]:0;f=new Float32Array(3);f[0]=b?b[0]:0;f[1]=b?b[1]:0;f[2]=b?b[2]:1;if(null==g)b=new Float32Array(2),b[0]=0,b[1]=0;else{b=new Float32Array(g.length);for(var m=0;m<g.length;m++)b[m]=g[m]}g=new Uint8Array(4);g[0]=a?255*a[0]:255;g[1]=a?255*a[1]:255;g[2]=a?255*a[2]:255;g[3]=a&&3<a.length?255*a[3]:255;a=new Float32Array(2);
a[0]=null!=e&&2==e.length?e[0]:1;a[1]=null!=e&&2==e.length?e[1]:1;if(null!=h){var n=new Float32Array(4);n[0]=h[0];n[1]=h[1];n[2]=h[2];n[3]=h[3]}m=new Uint32Array(1);m[0]=0;e={};e[l.POSITION]=m;e[l.NORMAL]=m;e[l.UV0]=m;e[l.COLOR]=m;e[l.SIZE]=m;null!=h&&(e[l.AUXPOS1]=m);m={};m[l.POSITION]={size:3,data:c};m[l.NORMAL]={size:3,data:f};m[l.UV0]={size:b.length,data:b};m[l.COLOR]={size:4,data:g};m[l.SIZE]={size:2,data:a};null!=h&&(m[l.AUXPOS1]={size:4,data:n});h=[{type:"point",indices:e,positionKey:l.POSITION}];
return d?{faces:h[0],vertexAttr:m,id:A.getNewId().toString()}:new A(h,m)},createPointArrayGeometry:function(b,f){for(var a=new Float32Array(3*b.length),e=new Float32Array(f?3*b.length:3),d=new Uint32Array(b.length),h=new Uint32Array(b.length),g=0;g<b.length;g++)a[3*g]=b[g][0],a[3*g+1]=b[g][1],a[3*g+2]=b[g][2],f&&(e[3*g]=f[g][0],e[3*g+1]=f[g][1],e[3*g+2]=f[g][2]),d[g]=g,h[g]=0;f||(e[0]=0,e[1]=1,e[2]=0);g=new Float32Array(2);g[0]=0;g[1]=0;var c={};c[l.POSITION]=d;c[l.NORMAL]=f?d:h;c[l.UV0]=h;d={};d[l.POSITION]=
{size:3,data:a};d[l.NORMAL]={size:3,data:e};d[l.UV0]={size:2,data:g};return new A([{type:"point",indices:c,positionKey:l.POSITION}],d)},createTriangleGeometry:function(){var b=new Float32Array(9);b[0]=0;b[1]=0;b[2]=0;b[3]=0;b[4]=0;b[5]=100;b[6]=100;b[7]=0;b[8]=0;var f=new Uint32Array(3);f[0]=0;f[1]=1;f[2]=2;var a=new Float32Array(3);a[0]=0;a[1]=1;a[2]=0;var e=new Uint32Array(3);e[0]=0;e[1]=0;e[2]=0;var d=new Float32Array(2);d[0]=0;d[1]=0;var h=new Uint32Array(3);h[0]=0;h[1]=0;h[2]=0;var g={};g[l.POSITION]=
f;g[l.NORMAL]=e;g[l.UV0]=h;f={};f[l.POSITION]={size:3,data:b};f[l.NORMAL]={size:3,data:a};f[l.UV0]={size:2,data:d};return new A([{type:"triangle",indices:g,positionKey:l.POSITION}],f)},createSquareGeometry:function(b,f){var a,e,d=new Float32Array(12);if(b)for(a=0;4>a;a++)for(e=0;3>e;e++)d[3*a+e]=b[a][e];else d[0]=-1,d[1]=-1,d[2]=0,d[3]=1,d[4]=-1,d[5]=0,d[6]=1,d[7]=1,d[8]=0,d[9]=-1,d[10]=1,d[11]=0;var h=new Uint32Array(6);h[0]=0;h[1]=1;h[2]=2;h[3]=2;h[4]=3;h[5]=0;e=new Float32Array(3);e[0]=0;e[1]=
0;e[2]=1;var g=new Uint32Array(6);for(a=0;6>a;a++)g[a]=0;a=new Float32Array(8);a[0]=0;a[1]=0;a[2]=1;a[3]=0;a[4]=1;a[5]=1;a[6]=0;a[7]=1;var c={};c[l.POSITION]=h;c[l.NORMAL]=g;c[l.UV0]=h;h={};h[l.POSITION]={size:3,data:d};h[l.NORMAL]={size:3,data:e};h[l.UV0]={size:2,data:a};d=[{type:"triangle",indices:c,positionKey:l.POSITION}];return f?{faces:d[0],vertexAttr:h,id:A.getNewId().toString()}:new A(d,h)},createBoxGeometry:function(){var b,f,a=[[-0.5,-0.5,0.5],[0.5,-0.5,0.5],[0.5,0.5,0.5],[-0.5,0.5,0.5],
[-0.5,-0.5,-0.5],[0.5,-0.5,-0.5],[0.5,0.5,-0.5],[-0.5,0.5,-0.5]],e=[0,0,1,-1,0,0,1,0,0,0,-1,0,0,1,0,0,0,-1],d=[0,0,1,0,1,1,0,1],h=[0,1,2,2,3,0,4,0,3,3,7,4,1,5,6,6,2,1,1,0,4,4,5,1,3,2,6,6,7,3,5,4,7,7,6,5],g=Array(36);for(b=0;6>b;b++)for(f=0;6>f;f++)g[6*b+f]=b;var c=Array(36);for(b=0;6>b;b++)c[6*b+0]=0,c[6*b+1]=1,c[6*b+2]=2,c[6*b+3]=2,c[6*b+4]=3,c[6*b+5]=0;return function(b){var f;Array.isArray(b)||(b=[b,b,b]);var p=new Float32Array(24);for(f=0;8>f;f++)p[3*f]=a[f][0]*b[0],p[3*f+1]=a[f][1]*b[1],p[3*
f+2]=a[f][2]*b[2];b={};b[l.POSITION]=new Uint8Array(h);b[l.NORMAL]=new Uint8Array(g);b[l.UV0]=new Uint8Array(c);f={};f[l.POSITION]={size:3,data:p};f[l.NORMAL]={size:3,data:new Float32Array(e)};f[l.UV0]={size:2,data:new Float32Array(d)};return new A([{type:"triangle",indices:b,positionKey:l.POSITION}],f)}}(),createDiamondGeometry:function(){var b=[[-0.5,0,-0.5],[0.5,0,-0.5],[0.5,0,0.5],[-0.5,0,0.5],[0,-0.5,0],[0,0.5,0]],f=[0,1,-1,1,1,0,0,1,1,-1,1,0,0,-1,-1,1,-1,0,0,-1,1,-1,-1,0],a=[5,1,0,5,2,1,5,3,
2,5,0,3,4,0,1,4,1,2,4,2,3,4,3,0],e=[0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7];return function(d){var c;Array.isArray(d)||(d=[d,d,d]);var g=new Float32Array(18);for(c=0;6>c;c++)g[3*c]=b[c][0]*d[0],g[3*c+1]=b[c][1]*d[1],g[3*c+2]=b[c][2]*d[2];d={};d[l.POSITION]=new Uint8Array(a);d[l.NORMAL]=new Uint8Array(e);c={};c[l.POSITION]={size:3,data:g};c[l.NORMAL]={size:3,data:new Float32Array(f)};return new A([{type:"triangle",indices:d,positionKey:l.POSITION}],c)}}(),createTetrahedronGeometry:function(){var b=
c.createFrom(-0.5,0,-0.5),f=c.createFrom(0.5,0,-0.5),a=c.createFrom(0,0,0.5),e=c.createFrom(0,0.5,0),d=c.create(),h=c.create(),g=c.create(),k=c.create(),m=c.create();c.subtract(b,e,d);c.subtract(b,f,h);c.cross(d,h,g);c.normalize(g,g);c.subtract(f,e,d);c.subtract(f,a,h);c.cross(d,h,k);c.normalize(k,k);c.subtract(a,e,d);c.subtract(a,b,h);c.cross(d,h,m);c.normalize(m,m);var n=[b,f,a,e],p=[0,-1,0,g[0],g[1],g[2],k[0],k[1],k[2],m[0],m[1],m[2]],r=[0,1,2,3,1,0,3,2,1,3,0,2],v=[0,0,0,1,1,1,2,2,2,3,3,3];return function(a){var b;
Array.isArray(a)||(a=[a,a,a]);var d=new Float32Array(12);for(b=0;4>b;b++)d[3*b]=n[b][0]*a[0],d[3*b+1]=n[b][1]*a[1],d[3*b+2]=n[b][2]*a[2];a={};a[l.POSITION]=new Uint8Array(r);a[l.NORMAL]=new Uint8Array(v);b={};b[l.POSITION]={size:3,data:d};b[l.NORMAL]={size:3,data:new Float32Array(p)};return new A([{type:"triangle",indices:a,positionKey:l.POSITION}],b)}}(),createConeGeometry:function(b,f,a,e){var d=0,h=c.createFrom(0,d,0),g=c.createFrom(0,d+b,0),k=c.createFrom(0,-1,0),m=c.createFrom(0,1,0);e&&(d=b,
g=c.createFrom(0,0,0),h=c.createFrom(0,d,0),k=c.createFrom(0,1,0),m=c.createFrom(0,-1,0));var h=[g,h],k=[k,m],m=a+2,n=0,g=Math.sqrt(b*b+f*f);if(e)for(e=a-1;0<=e;e--)n=e*(2*Math.PI/a),p=c.createFrom(Math.cos(n)*f,d,Math.sin(n)*f),h.push(p),n=c.createFrom(b*Math.cos(n)/g,-f/g,b*Math.sin(n)/g),k.push(n);else for(e=0;e<a;e++){var n=e*(2*Math.PI/a),p=c.createFrom(Math.cos(n)*f,d,Math.sin(n)*f);h.push(p);n=c.createFrom(b*Math.cos(n)/g,f/g,b*Math.sin(n)/g);k.push(n)}b=new Uint32Array(6*(a+2));a=new Uint32Array(6*
(a+2));d=f=0;for(e=3;e<h.length;e++)b[f++]=1,b[f++]=e-1,b[f++]=e,a[d++]=0,a[d++]=0,a[d++]=0;b[f++]=h.length-1;b[f++]=2;b[f++]=1;a[d++]=0;a[d++]=0;a[d++]=0;for(e=3;e<h.length;e++)b[f++]=e,b[f++]=e-1,b[f++]=0,a[d++]=e,a[d++]=e-1,a[d++]=1;b[f++]=0;b[f++]=2;b[f++]=h.length-1;a[d++]=1;a[d++]=2;a[d++]=k.length-1;d=1;Array.isArray(d)||(d=[d,d,d]);f=new Float32Array(3*m);for(e=0;e<m;e++)f[3*e]=h[e][0]*d[0],f[3*e+1]=h[e][1]*d[1],f[3*e+2]=h[e][2]*d[2];h=new Float32Array(3*m);for(e=0;e<m;e++)h[3*e]=k[e][0],
h[3*e+1]=k[e][1],h[3*e+2]=k[e][2];k={};k[l.POSITION]=b;k[l.NORMAL]=a;m={};m[l.POSITION]={size:3,data:f};m[l.NORMAL]={size:3,data:h};return new A([{type:"triangle",indices:k,positionKey:l.POSITION}],m)},createCylinderGeometry:function(b,f,a,e,d,h){e||(e=c.createFrom(1,0,0));d||(d=c.createFrom(0,0,0));h=void 0===h?!0:h;var g=c.create();c.normalize(e,g);e=c.create();c.scale(g,Math.abs(b),e);var k=c.create();c.scale(e,-0.5,k);c.add(k,d);var m=c.createFrom(0,1,0);Math.abs(0.2>1-c.dot(g,m))&&c.set3(0,0,
1,m);var n=c.create();c.cross(g,m,n);c.normalize(n);c.cross(n,g,m);var p=2*a+(h?2:0),r=a+(h?2:0);d=new Float32Array(3*p);b=new Float32Array(3*r);var v=new Float32Array(2*p),w=new Uint32Array(3*a*(h?4:2)),s=new Float32Array(3*a*(h?4:2));h&&(d[3*(p-2)+0]=k[0],d[3*(p-2)+1]=k[1],d[3*(p-2)+2]=k[2],v[2*(p-2)]=0,v[2*(p-2)+1]=0,d[3*(p-1)+0]=d[3*(p-2)+0]+e[0],d[3*(p-1)+1]=d[3*(p-2)+1]+e[1],d[3*(p-1)+2]=d[3*(p-2)+2]+e[2],v[2*(p-1)]=1,v[2*(p-1)+1]=1,b[3*(r-2)+0]=-g[0],b[3*(r-2)+1]=-g[1],b[3*(r-2)+2]=-g[2],b[3*
(r-1)+0]=g[0],b[3*(r-1)+1]=g[1],b[3*(r-1)+2]=g[2]);for(var u,q=0,t=c.create(),D=c.create(),g=0;g<a;g++){u=g*(2*Math.PI/a);c.scale(m,Math.sin(u),t);c.scale(n,Math.cos(u),D);c.add(t,D);b[3*g+0]=t[0];b[3*g+1]=t[1];b[3*g+2]=t[2];c.scale(t,f);c.add(t,k);d[3*g+0]=t[0];d[3*g+1]=t[1];d[3*g+2]=t[2];v[2*g+0]=g/a;v[2*g+1]=0;d[3*(g+a)+0]=d[3*g+0]+e[0];d[3*(g+a)+1]=d[3*g+1]+e[1];d[3*(g+a)+2]=d[3*g+2]+e[2];v[2*(g+a)+0]=g/a;v[2*g+1]=1;u=(g+1)%a;var z=function(a,b,d){w[a]=b;s[a]=d};h&&(z(q++,p-2,r-2),z(q++,g,r-2),
z(q++,u,r-2));z(q++,g,g);z(q++,g+a,g);z(q++,u,u);z(q++,u,u);z(q++,g+a,g);z(q++,u+a,u);h&&(z(q++,g+a,r-1),z(q++,p-1,r-1),z(q++,u+a,r-1))}f={};f[l.POSITION]=w;f[l.NORMAL]=s;f[l.UV0]=w;a={};a[l.POSITION]={size:3,data:d};a[l.NORMAL]={size:3,data:b};a[l.UV0]={size:2,data:v};return new A([{type:"triangle",indices:f,positionKey:l.POSITION}],a)},createTubeGeometry:function(b,f,a,e,d){a=a||10;e=null!=e?e:!0;J.assert(1<b.length);for(var c=[],g=[],k=0;k<a;k++){c.push([0,-k-1,-((k+1)%a)-1]);var l=2*(k/a)*Math.PI;
g.push([Math.cos(l)*f,Math.sin(l)*f])}return S.createPathExtrusionGeometry(g,b,[[0,0,0]],c,e,d)},createSquareTubeGeometry:function(b,f,a){a=a||!0;J.assert(1<b.length);f*=Math.SQRT2;return S.createPathExtrusionGeometry([[f,f],[-f,f],[-f,-f],[f,-f]],b,[],[[-1,-2,-3],[-3,-4,-1]],a,[[0,1],[-1,0],[0,-1],[1,0]])},createPathExtrusionGeometry:function(b,f,a,e,d,h,g){var k,m=b.length,n=new Float32Array(3*f.length*m+(6*a.length||0)),p=new Float32Array(f.length*m+(2*a.length||0)),r=new Float32Array(3*f.length*
m+(a?6:0)),v=0,w=0,s=0,u=65535<n.length/3?Uint32Array:Uint16Array,q=6*(f.length-1)*m+6*e.length,t=new u(q),u=new u(q),D=q=0,z=c.create(),x=c.create(),B=c.create(),N=c.create(),J=c.create(),F=c.create(),H=c.create(),M=c.create(),y=c.create(),K=c.create(),C=c.create(),O=c.create();c.set3(0,1,0,O);c.subtract(f[1],f[0],x);c.normalize(x);d?(c.add(f[0],h,C),c.normalize(C,B)):c.set3(0,0,1,B);R(x,B,O,O,F,B,0.99619469809);c.set(B,N);for(k=0;k<a.length;k++)c.scale(F,a[k][0],y),c.scale(B,a[k][2],C),c.add(y,
C),c.add(y,f[0]),n[v++]=y[0],n[v++]=y[1],n[v++]=y[2],p[s++]=0;r[w++]=-x[0];r[w++]=-x[1];r[w++]=-x[2];for(k=0;k<e.length;k++)t[q++]=0<e[k][0]?e[k][0]:-e[k][0]-1+a.length,t[q++]=0<e[k][1]?e[k][1]:-e[k][1]-1+a.length,t[q++]=0<e[k][2]?e[k][2]:-e[k][2]-1+a.length,u[D++]=0,u[D++]=0,u[D++]=0;var E=a.length;k=a.length-1;for(var P,L=0;L<f.length;L++){P=!1;0<L&&(d?(c.add(f[L],h,C),c.normalize(C,B)):c.set3(0,0,1,B),c.set(x,z),c.set(z,C),L<f.length-1?(c.subtract(f[L+1],f[L],x),c.normalize(x),c.add(C,x)):P=!0,
R(C,B,N,O,F,B,0.99619469809),c.set(B,N));g&&(R(x,B,N,O,M,H,0.99619469809),c.set(H,J));for(var G=0;G<m;G++)if(c.scale(F,b[G][0],y),c.scale(B,b[G][1],C),c.add(y,C),g?(c.scale(M,g[G][0],K),c.scale(H,g[G][1],C),c.add(K,C),c.normalize(K),c.scale(K,-1)):c.normalize(y,K),r[w++]=K[0],r[w++]=K[1],r[w++]=K[2],c.add(y,f[L]),n[v++]=y[0],n[v++]=y[1],n[v++]=y[2],p[s++]=b[G][1],!P){var I=(G+1)%m;t[q++]=E+G;t[q++]=E+m+G;t[q++]=E+I;t[q++]=E+I;t[q++]=E+m+G;t[q++]=E+m+I;if(g)for(I=0;6>I;I++)u[D++]=E-k+G;else for(I=
0;6>I;I++)u[D++]=t[q-6+I]-k}E+=m}P=f[f.length-1];for(k=0;k<a.length;k++)c.scale(F,a[k][0],y),c.scale(B,a[k][1],C),c.add(y,C),c.add(y,P),n[v++]=y[0],n[v++]=y[1],n[v++]=y[2],p[s++]=0;b=w/3;r[w++]=x[0];r[w++]=x[1];r[w++]=x[2];m=E-m;for(k=0;k<e.length;k++)t[q++]=0<=e[k][0]?E+e[k][0]:-e[k][0]-1+m,t[q++]=0<=e[k][2]?E+e[k][2]:-e[k][2]-1+m,t[q++]=0<=e[k][1]?E+e[k][1]:-e[k][1]-1+m,u[D++]=b,u[D++]=b,u[D++]=b;e={};e[l.POSITION]=t;e[l.NORMAL]=u;t={};t[l.POSITION]={size:3,data:n};t.zOffset={size:1,data:p};t[l.NORMAL]=
{size:3,data:r};return new A([{type:"triangle",indices:e,positionKey:l.POSITION}],t)},createPolylineGeometry:function(b,f){J.assert(1<b.length,"createPolylineGeometry(): polyline needs at least 2 points");J.assert(3===b[0].length,"createPolylineGeometry(): malformed vertex");for(var a=new Float32Array(3*b.length),e=new Uint32Array(2*(b.length-1)),d=0,c=0,g=0;g<b.length;g++){for(var k=0;3>k;k++)a[d++]=b[g][k];0<g&&(e[c++]=g-1,e[c++]=g)}c={};d={};c[l.POSITION]=e;d[l.POSITION]={size:3,data:a};a=[{type:"line",
indices:c,positionKey:l.POSITION}];return f?{faces:a[0],vertexAttr:d,id:A.getNewId().toString()}:new A(a,d)},addVertexColors:function(b,f,a){var e,d,c;if(a){var g={};a=b.getVertexAttr();for(c in a)g[c]=a[c];b=b.getFaces();a=Array(b.length);for(d=0;d<b.length;d++){e={};for(c in b[d].indices)e[c]=b[d].indices[c];a[d]={type:b[d].type,indices:e,positionKey:b[d].positionKey}}b=new A(a,g)}f=f||[1,1,1,1];c=new Uint8Array(4);c[0]=255*f[0];c[1]=255*f[1];c[2]=255*f[2];c[3]=255*(3<f.length?f[3]:1);b.getVertexAttr()[l.COLOR]=
{size:4,data:c};a=b.getFaces();for(d=0;d<a.length;d++)f=a[d],e=new Uint32Array(f.indices[f.positionKey].length),f.indices[l.COLOR]=e;return b},addNormals:function(b){var c=b.getVertexAttr();b=b.getFaces();for(var a=T.Vec3Compact.subtract,e=b.map(function(a){return a.indices.position.length/3}).reduce(function(a,b){return a+b}),e=new Float32Array(3*e),d=c.position.data,h=0,g=0;g<b.length;g++){for(var k=b[g].indices.position,l=new Uint32Array(k.length),n=0;n<k.length;n+=3){a(d,3*k[n],d,3*k[n+2],V,0);
a(d,3*k[n],d,3*k[n+1],H,0);M.cross(H,V);M.normalize(H);var p=h/3;e[h++]=H[0];e[h++]=H[1];e[h++]=H[2];l[n]=p;l[n+1]=p;l[n+2]=p}b[g].indices.normal=l}c.normal={size:3,data:e}},cgToGIS:function(b){var c=b.getVertexAttr();b=c.position.data;var c=c.normal.data,a,e;if(c)for(a=0;a<c.length;a+=3)e=c[a+1],c[a+1]=-c[a+2],c[a+2]=e;if(b)for(a=0;a<b.length;a+=3)e=b[a+1],b[a+1]=-b[a+2],b[a+2]=e}};return S});