// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports","./GLSLShader","./gl-matrix"],function(r,s,p,k){var l=k.vec2d,m=k.vec3d,n=k.vec4d,q=k.mat4d;return function(){function d(b,a){this.gl=a;this.shaders=b;this.globalIndex=d.nextGlobalProgramIndex++;this.glName=void 0;this.name2uniformLoc={};this.name2attribLoc={};this.name2uniform1={};this.name2uniform2={};this.name2uniform3={};this.name2uniform4={};this.name2uniformMatrix4={}}d.prototype.init=function(){if(void 0===this.glName){this.glName=this.gl.createProgram();for(var b=
0;b<this.shaders.length;++b)this.gl.attachShader(this.glName,this.shaders[b].getGLName());this.linkShaders()}};d.prototype.linkShaders=function(){if(null!=this.glName){var b=this.gl;b.linkProgram(this.glName);b.getProgramParameter(this.glName,this.gl.LINK_STATUS)||console.error("Could not initialize shader\nVALIDATE_STATUS: "+b.getProgramParameter(this.glName,b.VALIDATE_STATUS)+", gl error ["+b.getError()+"]infoLog: "+b.getProgramInfoLog(this.glName));this.name2uniformLoc={};this.name2attribLoc={}}};
d.prototype.clearLookupTables=function(){this.name2uniformLoc={};this.name2attribLoc={};this.name2uniform1={};this.name2uniform2={};this.name2uniform3={};this.name2uniform4={};this.name2uniformMatrix4={}};d.prototype.getId=function(){return this.globalIndex};d.prototype.getShader=function(b){return this.shaders["vertex"===b?0:1]};d.prototype.changeShaderDefines=function(b,a){this.shaders[b].changeDefines(a)&&this.linkShaders()};d.prototype.use=function(){d.lastUsedProgram!==this&&(this.init(),this.gl.useProgram(this.glName),
d.lastUsedProgram=this)};d.prototype.getLocation=function(b){this.init();null==this.name2uniformLoc[b]&&(this.name2uniformLoc[b]=this.gl.getUniformLocation(this.glName,b));return this.name2uniformLoc[b]};d.prototype.hasUniform=function(b){return null!==this.getLocation(b)};d.prototype.getAttribLocation=function(b){this.init();null==this.name2attribLoc[b]&&(this.name2attribLoc[b]=this.gl.getAttribLocation(this.glName,b));return this.name2attribLoc[b]};d.prototype.uniform1i=function(b,a){var c=this.name2uniform1[b];
if(null==c||a!==c)this.use(),this.gl.uniform1i(this.getLocation(b),a),this.name2uniform1[b]=a};d.prototype.uniform1f=function(b,a){var c=this.name2uniform1[b];if(null==c||a!==c)this.use(),this.gl.uniform1f(this.getLocation(b),a),this.name2uniform1[b]=a};d.prototype.uniform2f=function(b,a,c){var d=this.name2uniform2[b];if(null==d||a!==d[0]||c!==d[1])this.use(),this.gl.uniform2f(this.getLocation(b),a,c),null==d?this.name2uniform2[b]=l.createFrom(a,c):l.set2(a,c,d)};d.prototype.uniform2fv=function(b,
a){var c=this.name2uniform2[b];if(2<a.length||null==c||a[0]!==c[0]||a[1]!==c[1])this.use(),this.gl.uniform2fv(this.getLocation(b),a),null==c?this.name2uniform2[b]=l.create(a):l.set(a,c)};d.prototype.uniform3f=function(b,a,c,d){var e=this.name2uniform3[b];if(null==e||a!==e[0]||c!==e[1]||d!==e[2])this.use(),this.gl.uniform3f(this.getLocation(b),a,c,d),null==e?this.name2uniform3[b]=m.createFrom(a,c,d):m.set3(a,c,d,e)};d.prototype.uniform3fv=function(b,a){var c=this.name2uniform3[b];if(3<a.length||null==
c||a[0]!==c[0]||a[1]!==c[1]||a[2]!==c[2])this.use(),this.gl.uniform3fv(this.getLocation(b),a),null==c?this.name2uniform3[b]=m.create(a):m.set(a,c)};d.prototype.uniform4f=function(b,a,c,d,e){var f=this.name2uniform4[b];if(null==f||a!==f[0]||c!==f[1]||d!==f[2]||e!==f[3])this.use(),this.gl.uniform4f(this.getLocation(b),a,c,d,e),null==f?this.name2uniform4[b]=n.createFrom(a,c,d,e):n.set4(a,c,d,e,f)};d.prototype.uniform4fv=function(b,a){var c=this.name2uniform4[b];if(4<a.length||null==c||a[0]!==c[0]||a[1]!==
c[1]||a[2]!==c[2]||a[3]!==c[3])this.use(),this.gl.uniform4fv(this.getLocation(b),a),null==c?this.name2uniform4[b]=n.create(a):n.set(a,c)};d.prototype.uniformMatrix4fv=function(b,a){var c=this.name2uniformMatrix4[b];if(16<a.length||null==c||!(c[0]===a[0]&&c[1]===a[1]&&c[2]===a[2]&&c[3]===a[3]&&c[4]===a[4]&&c[5]===a[5]&&c[6]===a[6]&&c[7]===a[7]&&c[8]===a[8]&&c[9]===a[9]&&c[10]===a[10]&&c[11]===a[11]&&c[12]===a[12]&&c[13]===a[13]&&c[14]===a[14]&&c[15]===a[15]))this.use(),this.gl.uniformMatrix4fv(this.getLocation(b),
!1,a),null==c?this.name2uniformMatrix4[b]=q.create(a):q.set(a,c)};d.prototype.dispose=function(){if(null!=this.glName){for(var b=0;b<this.shaders.length;++b){var a=this.shaders[b].getGLName();this.gl.detachShader(this.glName,a);this.gl.deleteShader(a)}this.gl.deleteProgram(this.glName)}};d.fromSnippets=function(b,a,c,h,e){var f=[];b=Array.isArray(b)?b:[b];a=Array.isArray(a)?a:[a];for(var g=0;g<b.length;g++)f.push(new p(h.VERTEX_SHADER,c[b[g]],h,e));for(g=0;g<a.length;g++)f.push(new p(h.FRAGMENT_SHADER,
c[a[g]],h,e));return new d(f,h)};d.unuse=function(b){d.lastUsedProgram=null;b.useProgram(null)};d.nextGlobalProgramIndex=0;d.lastUsedProgram=null;return d}()});