// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports","./Util","./GLUtil"],function(p,q,f,m){var n=function(){function c(a){this.glName=a.createTexture();this.refCount=0}c.prototype.incRefCnt=function(){++this.refCount};c.prototype.decRefCnt=function(){--this.refCount;f.assert(0<=this.refCount)};c.prototype.getRefCnt=function(){return this.refCount};c.prototype.getGLName=function(){return this.glName};return c}();return function(){function c(a,g,e,d){this.NUM_PARALLEL=8;this.textures=a;this.programRep=g;this.getViewportToRestore=
e;this.gl=d;this.NUM_PARALLEL=8;this.id2textureRef={};this.loading={};this.queue=[];this.listeners=[];this.maxMaxAnisotropy=(this.afExt=d.getExtension("EXT_texture_filter_anisotropic")||d.getExtension("MOZ_EXT_texture_filter_anisotropic")||d.getExtension("WEBKIT_EXT_texture_filter_anisotropic"))?d.getParameter(this.afExt.MAX_TEXTURE_MAX_ANISOTROPY_EXT):1;this.maxAnisotropy=Math.min(8,this.maxMaxAnisotropy);this._needsRender=!0;this.initBuffer=new Uint8Array(256);this.initBufferTransparent=new Uint8Array(256);
a=0;for(g=this.initBuffer.length;a<g;++a)this.initBuffer[a]=255,this.initBufferTransparent[a]=0!==(a+1)%4?255:0}c.prototype.unload=function(a){var g=this.id2textureRef[a];void 0!==g&&(this.gl.deleteTexture(g.getGLName()),delete this.id2textureRef[a])};c.prototype.resetNeedsRender=function(){this._needsRender=!1};c.prototype.needsRender=function(){return this._needsRender};c.prototype.aquire=function(a,g,e,d){var b=this,c=this.id2textureRef[a];if(null==c){c=new n(this.gl);f.assert(null==this.id2textureRef[a]);
this.id2textureRef[a]=c;var h=this.textures[a];f.assert(void 0!==h);h.setUnloadFunc(this.unload.bind(this));var k=c.getGLName();this.initializeTexture(k,h,g,e);h.renderGl?(h.renderGl(k,this.gl),d&&d(c)):h.deferredLoading()?this.getLoadingCount()<this.NUM_PARALLEL?this.loadImage(a,k,d):this.queue.push([a,k,d]):h.loadGl(function(){b._needsRender=!0;d&&d(c)},k,this.gl,this.programRep,this.getViewportToRestore());this._needsRender=!0}c.incRefCnt();return c.getGLName()};c.prototype.release=function(a){a=
this.id2textureRef[a];void 0!==a&&(a.decRefCnt(),f.assert(0<=a.getRefCnt()))};c.prototype.getLoadingCount=function(){return Object.keys(this.loading).length};c.prototype.getIsLoaded=function(a){if(null==this.id2textureRef[a]||void 0!==this.loading[a])return!1;for(var g=0,c=this.queue.length;g<c;++g)if(this.queue[g][0]===a)return!1;return!0};c.prototype.addTextureListener=function(a){f.assert(-1===this.listeners.indexOf(a));this.listeners.push(a)};c.prototype.removeTextureListener=function(a){a=this.listeners.indexOf(a);
f.assert(-1!==a);this.listeners.splice(a,1)};c.prototype.getTexture=function(a){return this.textures[a]};c.prototype.setMaxAnisotropy=function(a){if(this.afExt&&(a=f.clamp(a,1,this.maxMaxAnisotropy),a!==this.maxAnisotropy)){this.maxAnisotropy=a;for(var c in this.id2textureRef)a=this.id2textureRef[c].getGLName(),this.gl.bindTexture(this.gl.TEXTURE_2D,a),this.gl.texParameterf(this.gl.TEXTURE_2D,this.afExt.TEXTURE_MAX_ANISOTROPY_EXT,this.maxAnisotropy)}};c.prototype.getMaxAnisotropy=function(){return this.maxAnisotropy};
c.prototype.initializeTexture=function(a,c,e,d){var b=this.gl;b.bindTexture(b.TEXTURE_2D,a);c.params&&c.params.wrapClamp&&(b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_S,b.CLAMP_TO_EDGE),b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_T,b.CLAMP_TO_EDGE));if(void 0!==e)if(Array.isArray(e.id)){a=e.num;f.assert(e.id.length===a*a);b.texImage2D(b.TEXTURE_2D,0,b.RGBA,256*a,256*a,0,b.RGBA,b.UNSIGNED_BYTE,null);d=b.createFramebuffer();b.bindFramebuffer(b.FRAMEBUFFER,d);for(var l=0;l<a;l++)for(var h=0;h<a;h++)b.framebufferTexture2D(b.FRAMEBUFFER,
b.COLOR_ATTACHMENT0,b.TEXTURE_2D,this.id2textureRef[e.id[l*a+h]].getGLName(),0),m.checkFramebufferStatus(b.FRAMEBUFFER,b),b.copyTexSubImage2D(b.TEXTURE_2D,0,256*h,256*l,0,0,256,256);b.generateMipmap(b.TEXTURE_2D);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.LINEAR_MIPMAP_LINEAR);b.bindFramebuffer(b.FRAMEBUFFER,null);b.deleteFramebuffer(d)}else b.texImage2D(b.TEXTURE_2D,0,b.RGBA,e.width,e.height,0,b.RGBA,b.UNSIGNED_BYTE,null),m.copyTextureToTexture(this.id2textureRef[e.id].getGLName(),a,e.x,
e.y,0,0,e.width,e.height,b);else b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.NEAREST),void 0!==d&&d?b.texImage2D(b.TEXTURE_2D,0,b.RGBA,8,8,0,b.RGBA,b.UNSIGNED_BYTE,this.initBufferTransparent):b.texImage2D(b.TEXTURE_2D,0,b.RGBA,8,8,0,b.RGBA,b.UNSIGNED_BYTE,this.initBuffer);this.afExt&&(c.params&&c.params.mipmap)&&b.texParameterf(b.TEXTURE_2D,this.afExt.TEXTURE_MAX_ANISOTROPY_EXT,this.maxAnisotropy)};c.prototype.next=function(a){if(a in this.loading){delete this.loading[a];var c=Object.keys(this.id2textureRef),
e=Object.keys(this.loading);this.listeners.forEach(function(d){d(a,c,e)});this.processQueue()}};c.prototype.loadImage=function(a,c,e){var d=this;f.assert(null==this.loading[a]);this.loading[a]=!0;var b=this.textures[a];f.assert(void 0!==b);setTimeout(function(){var f=d.id2textureRef[a];f&&f.getRefCnt()&&b.loadGl(function(){d.next(a);d._needsRender=!0;var b=d.id2textureRef[a];b&&b.getRefCnt()&&e&&e(b)},c,d.gl,d.programRep,d.getViewportToRestore())},0)};c.prototype.processQueue=function(){for(var a=
[],c=0,e=this.queue.length;c<e;++c){var d=this.queue[c][0],b=this.id2textureRef[d];void 0!==b&&(0===b.getRefCnt()?(this.gl.deleteTexture(b.getGLName()),delete this.id2textureRef[d]):a.push(this.queue[c]))}this.queue=a;a=Math.min(this.NUM_PARALLEL-Object.keys(this.loading).length,this.queue.length);for(c=0;c<a;++c)this.loadImage(this.queue[c][0],this.queue[c][1],this.queue[c][2]);this.queue.splice(0,a)};return c}()});