// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["./GLVBO","./VertexBufferLayout","./Util","./gl-matrix","./webgl-debug"],function(n,p,k,q,g){var r=q.mat4d,m={texImage2D:function(b,c,a,e,h,f,s,l){k.assert(1<=b.width&&1<=b.height);!0===l&&a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!1);s&&(!k.isPowerOfTwo(b.width)||!k.isPowerOfTwo(b.height))?(m.makePotTexture(b,c,a,e,h),a.bindTexture(a.TEXTURE_2D,c)):(a.bindTexture(a.TEXTURE_2D,c),a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,b));f?(a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR_MIPMAP_LINEAR),
a.generateMipmap(a.TEXTURE_2D)):a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.bindTexture(a.TEXTURE_2D,null);!0===l&&a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!0);return c},copyTextureToTexture:function(b,c,a,e,h,f,k,l,d){var g=d.createFramebuffer();d.bindFramebuffer(d.FRAMEBUFFER,g);d.framebufferTexture2D(d.FRAMEBUFFER,d.COLOR_ATTACHMENT0,d.TEXTURE_2D,b,0);m.checkFramebufferStatus(d.FRAMEBUFFER,d);d.bindTexture(d.TEXTURE_2D,c);d.copyTexSubImage2D(d.TEXTURE_2D,0,h,f,a,e,k,l);d.generateMipmap(d.TEXTURE_2D);
d.bindFramebuffer(d.FRAMEBUFFER,null);d.deleteFramebuffer(g)},makePotTexture:function(b,c,a,e,h){var f=k.nextHighestPowerOfTwo(b.width),g=k.nextHighestPowerOfTwo(b.height);k.assert(f!==b.width||g!==b.height);var l=a.createFramebuffer();a.bindFramebuffer(a.FRAMEBUFFER,l);a.bindTexture(a.TEXTURE_2D,c);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,f,g,0,a.RGBA,a.UNSIGNED_BYTE,null);a.generateMipmap(a.TEXTURE_2D);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,c,0);c=a.createTexture();a.bindTexture(a.TEXTURE_2D,
c);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,b);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST);b=p.Defaults.PosTex;var d=new n(k.createQuadVertexUvBuffer(),b,a);void 0===h&&(h=a.getParameter(a.VIEWPORT));a.viewport(0,0,f,g);e=e.get("texOnly");e.use();f=r.identity();e.uniformMatrix4fv("model",f);e.uniformMatrix4fv("view",f);e.uniformMatrix4fv("proj",
f);e.uniform4fv("color",[1,1,1,1]);e.uniform1i("tex",0);b.enableVertexAttribArrays(a,e);d.bind();d.setPointers(e);a.disable(a.DEPTH_TEST);a.drawArrays(a.TRIANGLE_STRIP,0,d.getNum());a.enable(a.DEPTH_TEST);b.disableVertexAttribArrays(a,e);a.viewport(h[0],h[1],h[2],h[3]);d.dispose();a.deleteTexture(c);a.bindFramebuffer(a.FRAMEBUFFER,null);a.deleteFramebuffer(l)},createEmptyTexture:function(b){var c=b.createTexture();b.bindTexture(b.TEXTURE_2D,c);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.NEAREST);
b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,b.NEAREST);b.texImage2D(b.TEXTURE_2D,0,b.RGBA,4,4,0,b.RGBA,b.UNSIGNED_BYTE,null);return c},checkError:function(b,c){var a=c.getError();a!=c.NO_ERROR&&alert(b+": gl error "+a)},checkFramebufferStatus:function(b,c){var a=c.checkFramebufferStatus(b);a!=c.FRAMEBUFFER_COMPLETE&&console.log("Framebuffer error 0x"+a)},handleError:function(b,c,a){alert(g.glEnumToString(b)+" was caused by call to: "+c+"("+g.glFunctionArgsToString(c,a)+")")},validateNoneOfTheArgsAreUndefined:function(b,
c){for(var a=0;a<c.length;++a)void 0===c[a]&&console.error("undefined passed to gl."+b+"("+g.glFunctionArgsToString(b,c)+")")}};return m});