// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports"],function(c,d){var b,a=b||(b={});a[a.BACKGROUND=0]="BACKGROUND";a[a.INTERNAL_MATERIAL=1]="INTERNAL_MATERIAL";a[a.OPAQUE_TERRAIN=2]="OPAQUE_TERRAIN";a[a.OPAQUE_MATERIAL=3]="OPAQUE_MATERIAL";a[a.OPAQUE_EXTERNAL=4]="OPAQUE_EXTERNAL";a[a.TRANSPARENT_MATERIAL=5]="TRANSPARENT_MATERIAL";a[a.TRANSPARENT_EXTERNAL=6]="TRANSPARENT_EXTERNAL";a[a.TRANSPARENT_TERRAIN=7]="TRANSPARENT_TERRAIN";a[a.POSTPROCESSING_HIGHLIGHT=8]="POSTPROCESSING_HIGHLIGHT";a[a.POSTPROCESSING_ATMOSPHERE=9]=
"POSTPROCESSING_ATMOSPHERE";a[a.OVERLAY=10]="OVERLAY";a[a.MAX_SLOTS=11]="MAX_SLOTS";return b});