// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ./IntervalUtilities ./ModelDirtyTypesTs ./Float32ArrayList ./InstanceBufferData ./VertexBufferLayout ./Lighting ../materials/internal/SimpleGLMaterial ../materials/internal/TexOnlyGLMaterial ./GLVBO ./GLSLProgram ./LinearDepthTextureHelper ./NormalTextureHelper ./HighlightTextureHelper ./RenderPass ./RenderSlot ./RenderContext ./ExternalRendererContainer ./BitSet ./Util ./gl-matrix".split(" "),function(M,N,O,ia,P,W,X,Y,Q,Z,I,R,$,aa,ba,t,x,ca,da,ea,B,J){var A=B.assert,S=B.array2object,
T=B.objectEmpty,D=B.getFirstObjectValue,K=B.setMatrixTranslation3;M=J.vec2d;N=J.vec3d;var L=J.vec4d,y=J.mat4d,fa=B.VertexAttrConstants,E=y.identity();B=N.create();var ga=1535,U={proj:E,view:E,nearFar:[-1,1],origin:B};B=function(){function k(a,b,d,c,e,f){this._lighting=new Y;this._mat2dataMerged={};this._mat2dataInstanced={};this._renderOrder=[];this._externalRenderers=new da;this._renderContext=new ca;this._framesRendered=0;this._isRendering=!1;this._pixelRatio=1;this._threshold=ga;this._needsRender=
!0;this._stats=new ha;this.offscreenRenderingEnabled=this.ssaoEnabled=!1;this._programRep=a;this._vboRep=b;this._materialRep=d;this._textureRep=c;this._orderedRendering=f;this._gl=e;this._selectionMaterial=new Q(a,L.createFrom(0.1,0.2,0.9,0.4),e.EQUAL);this._selectionMaterialLines=new Q(a,L.createFrom(0.1,0.2,0.9,0.4),e.EQUAL,e.LINES);this._renderContext.lightingData=this._lighting.get();e.enable(e.DEPTH_TEST);e.enable(e.CULL_FACE);e.disable(e.BLEND);e.blendFunc(e.SRC_ALPHA,e.ONE_MINUS_SRC_ALPHA);
this._bindParameters={view:null,proj:null,viewInvTransp:null,nearFar:null,lightingData:null,viewport:null,framebufferTex:null,shadowMap:null,origin:null,pixelRatio:null,instanceParameters:null,depthFBO:null,normalFBO:null,extensions:{angleInstancedArrays:e.getExtension("ANGLE_instanced_arrays")}};this._linearDepthTextureHelper=new $(e);this._normalTextureHelper=new aa(e);this._highlightTextureHelper=new ba(e);this._initializeFramebufferTexture();this._initializeQuadVBO();this._initializeIeTextureFix()}
k.prototype._initializeQuadVBO=function(){this._quadVBO=new I(new Float32Array([-1,-1,0,0,0,1,-1,0,1,0,-1,1,0,0,1,1,1,0,1,1]),X.Defaults.PosTex,this._gl)};k.prototype._initializeFramebufferTexture=function(){var a=this._gl,b=a.getContextAttributes().alpha?a.RGBA:a.RGB,d=a.createTexture();a.bindTexture(3553,d);a.texParameteri(3553,10241,9728);a.texParameteri(3553,10240,9728);a.texParameteri(3553,10242,33071);a.texParameteri(3553,10243,33071);a.texImage2D(3553,0,6408,4,4,0,6408,5121,null);this._framebuffer=
{format:b,texture:d,copied:!1}};k.prototype._initializeIeTextureFix=function(){if(6408===this._framebuffer.format){for(var a=this._gl,b=new Uint8Array(64),d=0;64>d;d++)b[d]=255;this._ieFixTexture=a.createTexture();a.bindTexture(3553,this._ieFixTexture);a.texParameteri(3553,10241,9728);a.texImage2D(3553,0,6408,4,4,0,6408,5121,b);this._ieFixMaterial=new Z(this._programRep,this._ieFixTexture,L.createFrom(1,1,1,1),!0,519)}};k.prototype.dispose=function(){for(var a in this._mat2dataMerged){this._releaseMaterials(a);
var b=this._mat2dataMerged[a],d;for(d in b.origin2data)b.origin2data[d].vbo.dispose()}this._mat2dataMerged=null;for(a in this._mat2dataInstanced)for(d in this._releaseMaterials(a),b=this._mat2dataInstanced[a],b.origin2data)b.origin2data[d].vbo.dispose();this._mat2dataInstanced=null;this._quadVBO.dispose();this._ieFixTexture&&(this._gl.deleteTexture(this._ieFixTexture),this._ieFixTexture=null);this._gl.deleteTexture(this._framebuffer.texture);this._framebuffer.texture=null;this._linearDepthTextureHelper.getEnableState()&&
this._linearDepthTextureHelper.disable();this._normalTextureHelper.getEnableState()&&this._normalTextureHelper.disable();this._highlightTextureHelper.getEnableState()&&this._highlightTextureHelper.setEnableState(!1)};k.prototype.setLightingData=function(a){this._lighting.set(a);this._needsRender=!0};k.prototype.getLightingData=function(){return this._lighting.get()};k.prototype.setPixelRatio=function(a){this._pixelRatio=a;this._needsRender=!0};k.prototype.getPixelRatio=function(){return this._pixelRatio};
k.prototype.addExternalRenderer=function(a,b){this._externalRenderers.addRenderer(a,b);return!0};k.prototype.removeExternalRenderer=function(a){this._externalRenderers.removeRenderer(a);return!0};k.prototype.getExternalRenderers=function(){return this._externalRenderers};k.prototype.resetNeedsRender=function(){this._needsRender=!1;this._externalRenderers.resetNeedsRender()};k.prototype.needsRender=function(){return this._needsRender||this._externalRenderers.needsRender()};k.prototype.getCombinedStats=
function(){this._stats.VBOallocatedSize=0;this._stats.VBOoptimalSize=0;this._stats.VBOusedSize=0;for(var a in this._mat2dataInstanced){var b=this._mat2dataInstanced[a],d;for(d in b.origin2data){var c=b.origin2data[d];this._stats.VBOallocatedSize+=c.buffer.getArray().length;this._stats.VBOusedSize+=c.buffer.getSize();this._stats.VBOoptimalSize+=c.optimalCount}}for(a in this._mat2dataMerged)for(d in b=this._mat2dataMerged[a],b.origin2data)c=b.origin2data[d],this._stats.VBOallocatedSize+=c.buffer.getArray().length,
this._stats.VBOusedSize+=c.buffer.getSize(),this._stats.VBOoptimalSize+=c.optimalCount;this._stats.VBOallocatedSize*=0.00390625;this._stats.VBOusedSize*=0.00390625;this._stats.VBOoptimalSize*=0.00390625;return this._stats};k.prototype.setSelectionObject=function(a,b){a?(Array.isArray(a)?this._selectionIndices=this._name2indices(S(a)):this._selectionIndices=this._name2indices(S([a])),this._selectionFaceIndexRange=void 0,null!=b&&1===b.length&&(this._selectionFaceIndexRange=[[3*b[0][0],3*b[0][1]]])):
this._selectionFaceIndexRange=this._selectionIndices=void 0;this._needsRender=!0};k.prototype.renderGeometrySlots=function(a){this._externalRenderers.render(x.INTERNAL_MATERIAL,a);this._externalRenderers.render(x.OPAQUE_TERRAIN,a);this._renderInternalSlot(x.OPAQUE_MATERIAL,a);this._externalRenderers.render(x.OPAQUE_EXTERNAL,a);this._renderInternalSlot(x.TRANSPARENT_MATERIAL,a);this._externalRenderers.render(x.TRANSPARENT_EXTERNAL,a);this._externalRenderers.render(x.TRANSPARENT_TERRAIN,a)};k.prototype._renderHighlights=
function(a,b,d,c){var e=!!c&&c.getEnableState()&&void 0!==this._selectionIndices;this._highlightTextureHelper.setEnableState(e);e&&(this._highlightTextureHelper.setupFBOs(a),this._highlightTextureHelper.prepareHighlightPass(),this.renderGeometryPass(t.MATERIAL_HIGHLIGHT,a,b,this._selectionIndices,this._selectionFaceIndexRange),this._gl.clear(this._gl.DEPTH_BUFFER_BIT),this._renderInternalSlot(x.OVERLAY,this._renderContext),this._highlightTextureHelper.finish(d),b=this._highlightTextureHelper.getHighlightFBO(),
c.render(a,d,b))};k.prototype._renderUnordered=function(a,b,d,c,e,f,g){var m=this._gl;this._isRendering=!0;this._stats.reset();this._framebuffer.copied=!1;this._updateGlobalUniforms(a.projectionMatrix);this._renderContext.pass=t.MATERIAL;this._renderContext.camera=a;this._renderContext.shadowMap=d;this._renderContext.ssaoHelper=c;this._renderContext.offscreenRenderingHelper=f;this._renderContext.depth=this._linearDepthTextureHelper.getDepthFBO();this._renderContext.normals=this._normalTextureHelper.getNormalFBO();
this._renderContext.highlight=this._highlightTextureHelper.getHighlightFBO();this._renderContext.visibleContent=b;this._renderContext.filterContent=null;this._renderContext.filterFaceRange=null;this.offscreenRenderingEnabled&&f.prepareRenderPass(a);this._externalRenderers.render(x.BACKGROUND,this._renderContext);this.renderGeometrySlots(this._renderContext);this.offscreenRenderingEnabled?(this._renderContext.framebufferTex=f.getColorTexture(),this._framebuffer.copied=!0):this._copyFramebufferToTexture(a.fullViewport);
this._externalRenderers.render(x.POSTPROCESSING_ATMOSPHERE,this._renderContext);this.offscreenRenderingEnabled&&(d=a.viewport,d=y.ortho(d[0],d[2],d[1],d[3],-1,1),f.drawQuad(d));m.clear(m.DEPTH_BUFFER_BIT);this._renderInternalSlot(x.OVERLAY,this._renderContext);this._renderHighlights(a,b,e,g);m.bindBuffer(m.ARRAY_BUFFER,null);R.unuse(m);this._ieFixMaterial&&!e&&(m.blendFuncSeparate(m.ZERO,m.ONE,m.ONE,m.ZERO),this._ieFixMaterial.bind(m,U),this._ieFixMaterial.bindView(m,U),this._quadVBO.bind(),this._quadVBO.setPointers(this._ieFixMaterial.getProgram()),
m.drawArrays(m.TRIANGLE_STRIP,0,this._quadVBO.getNum()),this._ieFixMaterial.release(m),m.blendFunc(m.SRC_ALPHA,m.ONE_MINUS_SRC_ALPHA));this._framesRendered++;this._isRendering=!1};k.prototype._renderOrdered=function(a,b){this._isRendering=!0;this._stats.reset();this._framebuffer.copied=!1;this._updateGlobalUniforms(a.projectionMatrix);this._bindParameters.view=a.viewMatrix;this._bindParameters.proj=a.projectionMatrix;this._bindParameters.viewInvTransp=a.viewInverseTransposeMatrix;F[0]=a.near;F[1]=
a.far;this._bindParameters.nearFar=F;this._bindParameters.lightingData=this._lighting.get();this._bindParameters.viewport=a.fullViewport;this._bindParameters.framebufferTex=this._framebuffer.texture;this._bindParameters.pixelRatio=this._pixelRatio;this._bindParameters.instanceParameters=void 0;this._bindParameters.depthFBO=this._linearDepthTextureHelper.getDepthFBO();this._bindParameters.normalFBO=this._normalTextureHelper.getNormalFBO();for(var d=!0,c=0;c<this._renderOrder.length;c++){var e=this._renderOrder[c][1];
if(e.instanced){var f=e.instanced,g=f[t.MATERIAL];if(g&&(!g.isVisible||g.isVisible()))this._renderInternalInstanced(f,g,this._bindParameters,Infinity,b,null,null,!1),d=!0}if(e.merged&&(f=e.merged,(g=f[t.MATERIAL])&&(!g.isVisible||g.isVisible())))d&&(d=g.getProgram(),d.use(),d.uniformMatrix4fv("model",E),d.hasUniform("modelNormal")&&d.uniformMatrix4fv("modelNormal",E),d=!1),this._renderInternalMerged(f,g,this._bindParameters,Infinity)}c=this._gl;c.bindBuffer(c.ARRAY_BUFFER,null);R.unuse(c);this._framesRendered++;
this._isRendering=!1};k.prototype.render=function(a,b,d,c,e,f,g){this._orderedRendering?this._renderOrdered(a,b):this._renderUnordered(a,b,d,c,e,g,f)};k.prototype.renderAuxiliaryBuffers=function(a,b,d,c,e,f,g){g=this.ssaoEnabled||this._externalRenderers.needsDepthMap();this._linearDepthTextureHelper.setEnableState(g);g&&(this._linearDepthTextureHelper.setupFBOs(a),this._linearDepthTextureHelper.prepareDepthPass(),this.renderGeometryPass(t.MATERIAL_DEPTH,a,b,void 0,void 0,d,c),this._linearDepthTextureHelper.finish(f));
this._normalTextureHelper.setEnableState(this.ssaoEnabled);this.ssaoEnabled&&(this._normalTextureHelper.setupFBOs(a),this._normalTextureHelper.prepareNormalPass(),this.renderGeometryPass(t.MATERIAL_NORMAL,a,b,void 0,void 0,d,c),this._normalTextureHelper.finish(f));this.ssaoEnabled&&c.computeSSAO(a,f,e,this._linearDepthTextureHelper.getDepthFBO(),this._normalTextureHelper.getNormalFBO());c.bindAll(this._programRep)};k.prototype.renderGeometryPass=function(a,b,d,c,e,f,g){this._isRendering=!0;this._updateGlobalUniforms(b.projectionMatrix);
this._renderContext.pass=a;this._renderContext.camera=b;this._renderContext.shadowMap=f;this._renderContext.ssaoHelper=g;this._renderContext.depth=this._linearDepthTextureHelper.getDepthFBO();this._renderContext.normals=this._normalTextureHelper.getNormalFBO();this._renderContext.visibleContent=d;this._renderContext.filterContent=c;this._renderContext.filterFaceRange=e;this.renderGeometrySlots(this._renderContext);this._isRendering=!1};k.prototype.renderSelection=function(a){this._isRendering=!0;
for(var b=0;b<x.MAX_SLOTS;++b)this._renderInternalSlot(b,a);this._isRendering=!1};k.prototype._copyFramebufferToTexture=function(a){var b=this._gl;b.bindTexture(b.TEXTURE_2D,this._framebuffer.texture);b.copyTexImage2D(b.TEXTURE_2D,0,this._framebuffer.format,a[0],a[1],a[2],a[3],0);this._renderContext.framebufferTex=this._framebuffer.texture;this._framebuffer.copied=!0};k.prototype._renderInternalSlot=function(a,b){this._bindParameters.view=b.camera.viewMatrix;this._bindParameters.proj=b.camera.projectionMatrix;
this._bindParameters.viewInvTransp=b.camera.viewInverseTransposeMatrix;F[0]=b.camera.near;F[1]=b.camera.far;this._bindParameters.nearFar=F;this._bindParameters.lightingData=this._lighting.get();this._bindParameters.viewport=b.camera.fullViewport;this._bindParameters.framebufferTex=this.offscreenRenderingEnabled?this._renderContext.offscreenRenderingHelper.getColorTexture():this._framebuffer.texture;this._bindParameters.shadowMap=b.shadowMap;this._bindParameters.pixelRatio=this._pixelRatio;this._bindParameters.instanceParameters=
void 0;this._bindParameters.depthFBO=this._linearDepthTextureHelper.getDepthFBO();for(var d in this._mat2dataInstanced){var c=this._mat2dataInstanced[d],e=c[b.pass];e&&(e.beginSlot(a)&&(!e.isVisible||e.isVisible()))&&this._renderInternalInstanced(c,e,this._bindParameters,a,b.visibleContent,b.filterContent,b.filterFaceRange,!1)}if(b.filterContent)for(d in this._mat2dataMerged)c=this._mat2dataMerged[d],(e=c[b.pass])&&(e.beginSlot(a)&&(!e.isVisible||e.isVisible()))&&this._renderInternalInstanced(c,e,
this._bindParameters,a,null,b.filterContent,b.filterFaceRange,!0);else{for(var c=this._programRep.getProgramsUsingUniform("model"),e=this._programRep.getProgramsUsingUniform("modelNormal"),f=0;f<c.length;f++){var g=c[f];g.use();g.uniformMatrix4fv("model",E);-1<e.indexOf(g)&&g.uniformMatrix4fv("modelNormal",E)}for(d in this._mat2dataMerged)c=this._mat2dataMerged[d],(e=c[b.pass])&&(e.beginSlot(a)&&(!e.isVisible||e.isVisible()))&&this._renderInternalMerged(c,e,this._bindParameters,a)}};k.prototype._renderInternalInstanced=
function(a,b,d,c,e,f,g,m){c=this._gl;var l=!1,h=b.getDrawMode(c),k=this._bindParameters.extensions.angleInstancedArrays,q;for(q in a.origin2data){var n=a.origin2data[q];d.origin=n.origin;var w=!1;if(b.instanced)for(var s in n.perGeometryDataInfo){var r=n.perGeometryDataInfo[s];l||(b.bind(c,d),l=!0);w||(n.vbo.bind(),n.vbo.setPointers(b.getProgram()),b.bindView(c,d),w=!0);r.instanceBuffer.bind();r.instanceBuffer.setPointers(b.getProgram());var u=r.to-r.from,p=r.refCount;h===c.TRIANGLES&&(this._stats.trianglesRendered+=
p*u/3);k.drawArraysInstancedANGLE(h,r.from,u,p);this._stats.drawCallsAngleInstanced++;this._stats.instancesDrawnAngle+=p}else{var r=n.instances,t;for(t in r){var u=r[t],p=u.idx,v=u.displayedIndexRange;g&&(v=g);if(!(v&&0===v.length)&&!(e&&!e.get(p)||f&&!f.get(p)))l||(b.bind(c,d),l=!0),w||(n.vbo.bind(),n.vbo.setPointers(b.getProgram()),b.bindView(c,d),w=!0),m||b.bindInstance(c,u),this._stats.drawCallsInstanced++,h===c.TRIANGLES&&(this._stats.trianglesRendered+=(u.to-u.from)/3),v?this._drawArraysFaceRange(v,
u.from,h):c.drawArrays(h,u.from,u.to-u.from)}}}l&&b.release(c,d)};k.prototype._drawArraysFaceRange=function(a,b,d){for(var c=this._gl,e=0;e<a.length;e++){var f=a[e];c.drawArrays(d,f[0]+b,f[1]-f[0]+1)}this._stats.drawCallsFragmented+=a.length-1};k.prototype._renderInternalMerged=function(a,b,d,c){c=this._gl;var e=!1,f;for(f in a.origin2data){var g=a.origin2data[f];d.origin=g.origin;if(!(g.displayedIndexRange&&0===g.displayedIndexRange.length)){e||(b.bind(c,d),e=!0);g.vbo.bind();g.vbo.setPointers(b.getProgram());
b.bindView(c,d);this._stats.drawCallsMerged++;var m=b.getDrawMode(c);m===c.TRIANGLES&&(this._stats.trianglesRendered+=g.vbo.getNum()/3);g.displayedIndexRange?this._drawArraysFaceRange(g.displayedIndexRange,0,m):c.drawArrays(m,0,g.vbo.getNum())}}e&&b.release(c,d)};k.prototype._updateGlobalUniforms=function(a){for(var b=this._programRep.getProgramsUsingUniform("proj"),d=0;d<b.length;d++)b[d].uniformMatrix4fv("proj",a);if(this._lighting){b=this._programRep.getProgramsUsingUniform("lightDirection");for(d=
0;d<b.length;d++)this._lighting.setUniforms(b[d])}};k.prototype.print=function(){var a=Object.keys(this._mat2dataMerged).length,b=Object.keys(this._mat2dataInstanced).length;console.log("number of materials (merged/instanced): "+a+"/"+b);var a=0,d;for(d in this._mat2dataMerged){var b=this._mat2dataMerged[d],c;for(c in b.origin2data)a+=Object.keys(b.origin2data[c].instances).length}var e=0;for(d in this._mat2dataInstanced)for(c in b=this._mat2dataInstanced[d],b.origin2data)e+=Object.keys(b.origin2data[c].instances).length;
console.log("number of instances (merged/instanced): "+a+"/"+e)};k.prototype.isEmpty=function(){for(var a in this._mat2dataInstanced){var b=this._mat2dataInstanced[a],d;for(d in b.origin2data)if(!T(b.origin2data[d].instances))return!1}for(a in this._mat2dataMerged)for(d in b=this._mat2dataMerged[a],b.origin2data)if(!T(b.origin2data[d].instances))return!1;return!0};k.prototype.modify=function(a,b,d,c){this._isRendering&&console.warn("Renderer.modify called while rendering");var e=[],f=[];this._mergedOrInstanced(a,
e,f);a=[];var g=[];this._mergedOrInstanced(b,a,g);b={};d&&this._performUpdates(d,b);d=[];this._modifyMerged(e,a,d,b);this._modifyInstanced(f,g,d);this._updateMergedFaceranges(b);this._releaseMaterials(d);this._modifyMaterials(c);this._needsRender=!0};k.prototype._isInstanced=function(a){var b=!1,d=D(a.data.faces.indices).length,b=(b=(b=b||!1===a.material.canBeMerged)||a.material.instanced)||a.material.isBackdrop;return a.singleUse?b:b=b||d>this._threshold};k.prototype._mergedOrInstanced=function(a,
b,d){for(var c=0;c<a.length;++c)1>D(a[c].data.faces.indices).length||(this._isInstanced(a[c])?d.push(a[c]):b.push(a[c]))};k.prototype._performUpdates=function(a,b){for(var d=0;d<a.length;d++){var c=a[d],e=c.renderGeometry,f=this._isInstanced(e),c=c.updateType;c&2&&this._updateFaceranges(e,f,b);c&4||!f&&c&16?this._updateVertexAttributes(e,f):f&&c&16?this._updateInstanceTransformation(e,f):c&8&&this._updateColorAttributes(e)}};k.prototype._updateFaceranges=function(a,b,d){var c=a.material.getId(),e=
a.origin.id,f=(b?this._mat2dataInstanced:this._mat2dataMerged)[c].origin2data[e],g=f.instances[a.uniqueName];g&&(g.displayedIndexRange=a.displayedIndexRange,b||(d[this._modifiedMergedFacerangesKey(c,e)]=f))};k.prototype._updateMergedFaceranges=function(a){for(var b in a){var d=a[b];d.displayedIndexRange=[];var c=d.instances,e=!0,f;for(f in c){var g=c[f];g.displayedIndexRange?(d.displayedIndexRange.push.apply(d.displayedIndexRange,O.offsetIntervals(g.displayedIndexRange,g.from)),e=!1):d.displayedIndexRange.push([g.from,
g.to-1])}d.displayedIndexRange=e?null:O.mergeIntervals(d.displayedIndexRange)}};k.prototype._updateVertexAttributes=function(a,b){var d=a.material,c=d.getId(),c=(b?this._mat2dataInstanced:this._mat2dataMerged)[c].origin2data[a.origin.id],e=c.instances[a.uniqueName],f,g;b||(f=a.origin.vec3,K(C,-f[0],-f[1],-f[2]),y.multiply(C,a.transformation,G),y.inverse(G,H),y.transpose(H),f=G,g=H);var m=d.getVertexBufferLayout().getStride();A(e.from+d.getOutputAmount(D(a.data.faces.indices).length)/m===e.to,"material VBO layout has changed");
d.fillInterleaved(a.data,f,g,a.instanceParameters,c.buffer.getArray(),e.from*m);c.vbo.updateSubData(c.buffer.getArray(),e.from*m,e.to*m)};k.prototype._updateInstanceTransformation=function(a,b){var d=a.origin.vec3,c=(b?this._mat2dataInstanced:this._mat2dataMerged)[a.material.getId()].origin2data[a.origin.id],e=c.instances[a.uniqueName];K(C,-d[0],-d[1],-d[2]);y.multiply(C,a.transformation,e.transformation);y.inverse(e.transformation,e.transformationNormal);y.transpose(e.transformationNormal,e.transformationNormal);
d=c.perGeometryDataInfo[a.data.id];if(c=d.instanceBufferData){var f=c.getSlot(a.idx);c.fill(f,0,e.transformation);c.fill(f,16,e.transformationNormal);e=c.getOffset(f);d.instanceBuffer.updateSubData(c.getArray(),e,e+32)}};k.prototype._updateColorAttributes=function(a){var b=a.material,d=b.getId(),c=a.origin.id,d=(this._isInstanced(a)?this._mat2dataInstanced:this._mat2dataMerged)[d].origin2data[c],c=d.instances[a.uniqueName],e={};e[fa.COLOR]=!0;var f=b.getVertexBufferLayout().getStride();A(c.from+b.getOutputAmount(D(a.data.faces.indices).length)/
f===c.to,"material VBO layout has changed");b.fillInterleaved(a.data,void 0,void 0,a.instanceParameters,d.buffer.getArray(),c.from*f,e);d.vbo.updateSubData(d.buffer.getArray(),c.from*f,c.to*f)};k.prototype._modifyMerged=function(a,b,d,c){a=this._compMat2delta(a,b,!1);for(var e in a){b=a[e];for(var f in b){var g=b[f],m=g.optimalCount,l=g.material,h=l.getVertexBufferLayout(),k=h.getStride(),q=this._mat2dataMerged[e];if(null==q){A(0<m);var n=l.getRenderPriority(),q={origin2data:{}};q[t.MATERIAL]=this._materialRep.aquire(l);
q[t.MATERIAL_DEPTH_SHADOWMAP]=this._materialRep.aquireDepthShadowMap(l);q[t.MATERIAL_NORMAL]=this._materialRep.aquireNormal(l);q[t.MATERIAL_DEPTH]=this._materialRep.aquireDepth(l);q[t.MATERIAL_HIGHLIGHT]=this._materialRep.aquireHighlight(l);this._mat2dataMerged[e]=q;this._orderedRendering&&this._insertIntoRenderOrder(q,n,"merged")}n=q.origin2data[f];null==n&&(A(0<m),n={instances:{},vbo:new I(void 0,h,this._gl),buffer:new P(m),optimalCount:0,origin:g.origin},q.origin2data[f]=n);if(0<m){var h=n.buffer.getSize(),
w=n.buffer.getArray(),q=m<g.sparseCount/2,s=n.buffer.resize(q?m:g.sparseCount),r=g.toRemove;if(q||s){for(var h=0,u=n.buffer.getArray(),q=0,p=r.length;q<p;++q)s=n.instances[r[q].uniqueName],n.optimalCount-=(s.to-s.from)*k,delete n.instances[r[q].uniqueName];var q={},x;for(x in n.instances)s=n.instances[x],A(null==q[s.from]),q[s.from]=s;for(var v in q){var s=q[v],p=s.from*k,z=s.to*k;u.set(w.subarray(p,z),h);s.from=h/k;h+=z-p;s.to=h/k}A(h===n.optimalCount)}else{q=0;for(s=r.length;q<s;++q)w=r[q].uniqueName,
A(void 0!==n.instances[w]),p=n.instances[w].from*k,z=n.instances[w].to*k,n.buffer.erase(p,z),delete n.instances[w],n.optimalCount-=z-p}K(C,-g.origin[0],-g.origin[1],-g.origin[2]);g=g.toAdd;r=!1;q=0;for(w=g.length;q<w;++q)p=g[q],z=p.data,y.multiply(C,p.transformation,G),y.inverse(G,H),y.transpose(H),s=h,l.fillInterleaved(z,G,H,p.instanceParameters,n.buffer.getArray(),h),z=l.getOutputAmount(D(z.faces.indices).length),u=s+z,A(null==n.instances[p.uniqueName]),s=new V(p.name,s/k,u/k,p.displayedIndexRange,
void 0,void 0,p.idx),p.displayedIndexRange&&(r=!0),n.instances[p.uniqueName]=s,n.optimalCount+=z,h+=z;A(n.optimalCount===m);n.vbo.setData(n.buffer.getArray(),n.buffer.getSize());if(r||n.displayedIndexRange)c[this._modifiedMergedFacerangesKey(e,f)]=n}else A(0===m),n.vbo.dispose(),delete q.origin2data[f],0===Object.keys(q.origin2data).length&&(d.push(e),delete this._mat2dataMerged[e],this._orderedRendering&&this._removeFromRenderOrder(q,"merged"))}}};k.prototype._modifyInstanced=function(a,b,d){a=this._compMat2delta(a,
b,!0);for(var c in a){b=a[c];for(var e in b){var f=b[e];if(0===f.optimalCount)f=this._mat2dataInstanced[c],f.origin2data[e].vbo.dispose(),delete f.origin2data[e],0===Object.keys(f.origin2data).length&&(d.push(c),delete this._mat2dataInstanced[c],this._orderedRendering&&this._removeFromRenderOrder(f,"instanced"));else{var g=f.material,m=this._mat2dataInstanced[c];if(null==m){var l=g.getRenderPriority(),m={origin2data:{}};m[t.MATERIAL]=this._materialRep.aquire(g);m[t.MATERIAL_DEPTH_SHADOWMAP]=this._materialRep.aquireDepthShadowMap(g);
m[t.MATERIAL_NORMAL]=this._materialRep.aquireNormal(g);m[t.MATERIAL_DEPTH]=this._materialRep.aquireDepth(g);m[t.MATERIAL_HIGHLIGHT]=this._materialRep.aquireHighlight(g);this._mat2dataInstanced[c]=m;this._orderedRendering&&this._insertIntoRenderOrder(m,l,"instanced")}var h=g.getVertexBufferLayout(),k=m[t.MATERIAL].instanced?g.getInstanceBufferLayout():null,q=k&&k.hasAttribute("instanceColor"),n=h.getStride(),l=m.origin2data[e];null==l&&(l={instances:{},vbo:new I(void 0,h,this._gl),buffer:new P(f.optimalCount),
optimalCount:0,perGeometryDataInfo:{},origin:f.origin},m.origin2data[e]=l);var m=l.buffer.getSize(),w=l.buffer.getArray(),s=f.optimalCount<f.sparseCount/2,r=l.buffer.resize(s?f.optimalCount:f.sparseCount),u;for(u in f.perGeometryDelta)if((h=l.perGeometryDataInfo[u])&&h.instanceBufferData){var p=f.perGeometryDelta[u].removeCount;0<p&&h.instanceBufferData.prepareFree(p)}var x=f.toRemove;if(s||r){s=0;for(m=x.length;s<m;++s){r=x[s];delete l.instances[r.uniqueName];u=r.data.id;var v=h=l.perGeometryDataInfo[u];
0===--v.refCount&&null==f.dataId2refCount[u]?(l.optimalCount-=(v.to-v.from)*n,delete l.perGeometryDataInfo[u]):h.instanceBufferData&&h.instanceBufferData.free(r.idx)}var m=0,s=l.buffer.getArray(),r={},z;for(z in l.perGeometryDataInfo)v=l.perGeometryDataInfo[z],A(null==r[v.from]),r[v.from]=v;for(name in r)v=r[name],p=v.from*n,h=v.to*n,s.set(w.subarray(p,h),m),v.from=m/n,m+=h-p,v.to=m/n;for(name in l.instances)p=l.instances[name],p.from=l.perGeometryDataInfo[p.dataId].from,p.to=l.perGeometryDataInfo[p.dataId].to}else{s=
0;for(w=x.length;s<w;++s)r=x[s],delete l.instances[r.uniqueName],u=r.data.id,h=l.perGeometryDataInfo[u],0===--h.refCount&&null==f.dataId2refCount[u]?(p=h.from*n,h=h.to*n,l.buffer.erase(p,h),l.optimalCount-=h-p,delete l.perGeometryDataInfo[u]):h.instanceBufferData&&h.instanceBufferData.free(r.idx)}K(C,-f.origin[0],-f.origin[1],-f.origin[2]);for(u in f.perGeometryDelta)if((h=l.perGeometryDataInfo[u])&&h.instanceBufferData)s=f.perGeometryDelta[u].addCount,0<s&&h.instanceBufferData.prepareAllocate(s);
w=f.toAdd;s=0;for(x=w.length;s<x;++s){r=w[s];p=r.data;u=p.id;h=l.perGeometryDataInfo[u];null==h?(g.fillInterleaved(p,void 0,void 0,void 0,l.buffer.getArray(),m),v=g.getOutputAmount(D(p.faces.indices).length),p=m/n,m+=v,h=m/n,l.optimalCount+=v,h={refCount:1,from:p,to:h,instanceBuffer:null,instanceBufferData:null},k&&(h.instanceBuffer=new I(void 0,k,this._gl),h.instanceBufferData=new W(k.getStride(),f.perGeometryDelta[u].addCount)),l.perGeometryDataInfo[u]=h):++h.refCount;A(h.from*n<=l.buffer.getSize()&&
h.to*n<=l.buffer.getSize());p=y.create();y.multiply(C,r.transformation,p);p=new V(r.name,h.from,h.to,r.displayedIndexRange,p,r.instanceParameters,r.idx,u);if(h=h.instanceBufferData)v=h.allocate(r.idx),h.fill(v,0,p.transformation),h.fill(v,16,p.transformationNormal),q&&h.fill(v,32,r.instanceParameters.color);l.instances[r.uniqueName]=p}A(l.optimalCount===f.optimalCount);l.vbo.setData(l.buffer.getArray(),l.buffer.getSize());for(u in l.perGeometryDataInfo)g=l.perGeometryDataInfo[u],g.instanceBuffer&&
(k=f.perGeometryDelta[u],0<k.addCount+k.removeCount&&(k=g.instanceBufferData.compact(),g.instanceBuffer.setData(k,k.length)))}}}};k.prototype._compMat2delta=function(a,b,d){var c={};this._updateMat2delta(a,!0,d,c);this._updateMat2delta(b,!1,d,c);return c};k.prototype._updateMat2delta=function(a,b,d,c){for(var e=0,f=a.length;e<f;++e){var g=a[e],k=g.origin,l=g.material,h=l.getId(),t=d?this._mat2dataInstanced[h]:this._mat2dataMerged[h],t=t&&t.origin2data[k.id],q=c[h];null==q&&(q={},c[h]=q);h=q[k.id];
if(null==h){h={optimalCount:null==t?0:t.optimalCount,sparseCount:null==t?0:t.buffer.getSize(),material:l,toAdd:[],toRemove:[],perGeometryDelta:null,origin:k.vec3};if(d){var n={};if(void 0!==t)for(var w in t.perGeometryDataInfo)n[w]=t.perGeometryDataInfo[w].refCount;h.dataId2refCount=n;h.perGeometryDelta={}}q[k.id]=h}k=l.getOutputAmount(D(g.data.faces.indices).length);d?(l=g.data.id,t=h.perGeometryDelta[l],t||(t={addCount:0,removeCount:0},h.perGeometryDelta[l]=t),b?(t.addCount++,null==h.dataId2refCount[l]&&
(h.dataId2refCount[l]=0),1===++h.dataId2refCount[l]&&(h.optimalCount+=k,h.sparseCount+=k),h.toAdd.push(g)):(t.removeCount++,0===--h.dataId2refCount[l]&&(delete h.dataId2refCount[l],h.optimalCount-=k),h.toRemove.push(g))):b?(h.optimalCount+=k,h.sparseCount+=k,h.toAdd.push(g)):(h.optimalCount-=k,h.toRemove.push(g))}};k.prototype._modifiedMergedFacerangesKey=function(a,b){return a+"_"+b};k.prototype._insertIntoRenderOrder=function(a,b,d){for(var c=a[t.MATERIAL].getMaterialId(),e=this._renderOrder.length,
f=0;f<e&&this._renderOrder[f][0]>=b;){var g=this._renderOrder[f][1];if(g.id===c){A(!g[d],"matData for type already exists");g[d]=a;return}f++}c={id:c,instanced:null,merged:null};c[d]=a;this._renderOrder.splice(f,0,[b,c])};k.prototype._removeFromRenderOrder=function(a,b){for(var d=a[t.MATERIAL].getMaterialId(),c=0;this._renderOrder[c][1].id!==d;)c++;d=this._renderOrder[c][1];d[b]=null;!d.instanced&&!d.merged&&this._renderOrder.splice(c,1)};k.prototype._updateRenderOrder=function(a,b){for(var d=b.length,
c=0;c<d&&b[c][1].id!==a;)c++;if(c<d){var e=b[c][1],e=(e.merged||e.instanced)[t.MATERIAL].getRenderPriority(),f=b[c][0];if(e!==b[c][0]){b[c][0]=e;f=e>f?-1:1;for(c+=f;-1<c&&c<d&&f*b[c][0]>f*e;){var g=b[c];b[c]=b[c-f];b[c-f]=g;c+=f}}}};k.prototype._modifyMaterials=function(a){for(var b in a)this._materialRep.updateMaterialParameters(b)};k.prototype.modifyRenderOrder=function(a){if(this._orderedRendering){for(var b in a)this._updateRenderOrder(b,this._renderOrder);this._needsRender=!0}};k.prototype._releaseMaterials=
function(a){if(Array.isArray(a))for(var b=0;b<a.length;b++)this._materialRep.release(a[b]),this._materialRep.releaseDepthShadowMap(a[b]),this._materialRep.releaseNormal(a[b]),this._materialRep.releaseDepth(a[b]),this._materialRep.releaseHighlight(a[b]);else this._materialRep.release(a),this._materialRep.releaseDepthShadowMap(a),this._materialRep.releaseNormal(a),this._materialRep.releaseDepth(a),this._materialRep.releaseHighlight(a)};k.prototype._name2indices=function(a){for(var b=new ea,d=0;2>d;++d){var c=
0===d?this._mat2dataMerged:this._mat2dataInstanced,e;for(e in c){var f=c[e].origin2data,g;for(g in f){var k=f[g].instances,l;for(l in k){var h=k[l];void 0!==a[h.name]&&b.set(h.idx)}}}}return b};return k}();var ha=function(){function k(){this.reset()}k.prototype.reset=function(){this.VBOusedSize=this.VBOoptimalSize=this.VBOallocatedSize=this.instancesDrawnAngle=this.drawCallsFragmented=this.drawCallsMerged=this.drawCallsAngleInstanced=this.drawCallsInstanced=this.trianglesRendered=0};return k}(),V=
function(){return function(k,a,b,d,c,e,f,g){this.name=k;this.from=a;this.to=b;this.displayedIndexRange=d;this.transformation=c;this.instanceParameters=e;this.idx=f;this.dataId=g;null!=c&&(this.transformationNormal=y.create(),y.set(c,this.transformationNormal),y.inverse(this.transformationNormal,this.transformationNormal),y.transpose(this.transformationNormal,this.transformationNormal))}}(),F=M.create(),C=y.identity(),G=y.create(),H=y.create();return B});