// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("./GLVBO ./GLSLProgram ./VertexBufferLayout ./GLUtil ./Camera ./Util ./gl-matrix".split(" "),function(qa,da,ra,ea,sa,k,u){var c=u.vec2d,J=u.vec3d,Z=u.vec4d,ta=u.mat3d,C=u.mat4d,G=u.mat4;return function(u,a){function v(a,b){J.set3(a[b],a[b+3],a[b+6],fa);return fa}var p,K=4096,D,U,ua=ea.createEmptyTexture(a),L=1,$=2,M=[0,0,0,0,0],e=function(){this.camera=new sa;this.lightMat=C.create()},O=[],n,l,w;for(n=0;4>n;++n)O[n]=new e;this.getIsSupported=function(){return a.getExtension("OES_standard_derivatives")};
this.setTextureResolution=function(a){K=a};this.getTextureResolution=function(){return K};this.setMaxNumCascades=function(a){$=k.clamp(Math.floor(a),1,4)};this.getMaxNumCascades=function(){return $};this.setEnableState=function(a){k.assert(a!==this.getEnableState());a?this.enable():this.disable()};this.getEnableState=function(){return void 0!==p};this.enable=function(){k.assert(!this.getEnableState());k.assert(this.getIsSupported(),"Shadow maps not supported");p=a.createTexture();a.bindTexture(a.TEXTURE_2D,
p);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,K,K,0,a.RGBA,a.UNSIGNED_BYTE,null);D=a.createRenderbuffer();a.bindRenderbuffer(a.RENDERBUFFER,D);a.renderbufferStorage(a.RENDERBUFFER,a.DEPTH_COMPONENT16,K,K);U=a.createFramebuffer();a.bindFramebuffer(a.FRAMEBUFFER,
U);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,p,0);a.framebufferRenderbuffer(a.FRAMEBUFFER,a.DEPTH_ATTACHMENT,a.RENDERBUFFER,D);ea.checkFramebufferStatus(a.FRAMEBUFFER,a);a.bindTexture(a.TEXTURE_2D,null);a.bindRenderbuffer(a.RENDERBUFFER,null);a.bindFramebuffer(a.FRAMEBUFFER,null)};this.disable=function(){k.assert(this.getEnableState());a.deleteFramebuffer(U);a.deleteRenderbuffer(D);a.deleteTexture(p);p=D=U=void 0};var ga=C.create(),ha=C.create(),ia=Z.create(),x=Array(8);
for(n=0;8>n;++n)x[n]=Z.create();var H=J.create(),I=J.create(),ja=c.create(),ka=c.create(),va=c.create(),la=c.create(),ma=c.create(),na=C.create(),oa=J.create();this.prepare=function(y,Q,R,e,s){k.assert(this.getEnableState());C.multiply(y.projectionMatrix,y.viewMatrix,ga);var d=s[0],q=s[1];2>d&&(d=2);2>q&&(q=2);d>=q&&(d=2,q=4);L=Math.min(1+Math.floor(k.logWithBase(q/d,4)),$);R=Math.pow(q/d,1/L);for(s=0;s<L+1;++s)M[s]=d*Math.pow(R,s);C.inverse(ga,ha);C.lookAt([0,0,0],[-Q[0],-Q[1],-Q[2]],[0,1,0],na);
R=y.viewMatrix;y=y.projectionMatrix;for(s=0;s<L;++s){e=O[s];d=-M[s];q=-M[s+1];d=(y[10]*d+y[14])/Math.abs(y[11]*d+y[15]);q=(y[10]*q+y[14])/Math.abs(y[11]*q+y[15]);k.assert(d<q);for(l=0;8>l;++l){Z.set4(0===l%4||3==l%4?-1:1,0===l%4||1==l%4?-1:1,4>l?d:q,1,ia);C.multiplyVec4(ha,ia,x[l]);for(w=0;3>w;++w)x[l][w]/=x[l][3]}J.negate(x[0],oa);C.translate(na,oa,e.camera.viewMatrix);for(l=0;8>l;++l)C.multiplyVec3(e.camera.viewMatrix,x[l]);J.set(x[0],H);J.set(x[0],I);for(l=1;8>l;++l)for(w=0;3>w;++w)H[w]=Math.min(H[w],
x[l][w]),I[w]=Math.max(I[w],x[l][w]);H[2]-=200;I[2]+=200;e.camera.near=-I[2];e.camera.far=-H[2];d=1/x[0][3];q=1/x[4][3];k.assert(d<q);var h=d+Math.sqrt(d*q),m=Math.sin(Math.acos(R[2]*Q[0]+R[6]*Q[1]+R[10]*Q[2])),h=h/m,d=x,u=h,p=m,m=ja,z=ka,g=va,E=la,h=ma;c.set2(0,0,B);for(var f=void 0,f=0;4>f;++f)c.add(B,d[f],B);c.scale(B,0.25);c.set2(0,0,V);for(f=4;8>f;++f)c.add(V,d[f],V);c.scale(V,0.25);c.lerp(d[4],d[5],0.5,P[0]);c.lerp(d[5],d[6],0.5,P[1]);c.lerp(d[6],d[7],0.5,P[2]);c.lerp(d[7],d[4],0.5,P[3]);for(var n=
0,F=c.dist2(P[0],B),f=1;4>f;++f){var t=c.dist2(P[f],B);t<F&&(F=t,n=f)}c.subtract(P[n],d[n+4],r);f=r[0];r[0]=-r[1];r[1]=f;c.subtract(V,B,pa);c.lerp(r,pa,p);c.normalize(r);n=p=void 0;p=n=c.dot(c.subtract(d[0],B,N),r);for(f=1;8>f;++f)F=c.dot(c.subtract(d[f],B,N),r),F<p?p=F:F>n&&(n=F);c.set(B,m);c.scale(r,p-u,N);c.add(m,N,m);for(var t=-1,G=1,f=u=F=0;8>f;++f){c.subtract(d[f],m,X);c.normalize(X);var D=r[0]*X[1]-r[1]*X[0];0<D?D>t&&(t=D,F=f):D<G&&(G=D,u=f)}k.verify(0<t,"leftArea");k.verify(0>G,"rightArea");
c.scale(r,p,S);c.add(S,B,S);c.scale(r,n,T);c.add(T,B,T);Y[0]=-r[1];Y[1]=r[0];z=k.rayRay2D(m,d[u],T,c.add(T,Y,N),1,z);g=k.rayRay2D(m,d[F],T,N,1,g);E=k.rayRay2D(m,d[F],S,c.add(S,Y,N),1,E);d=k.rayRay2D(m,d[u],S,N,1,h);k.verify(z,"rayRay");k.verify(g,"rayRay");k.verify(E,"rayRay");k.verify(d,"rayRay");g=ja;d=ka;m=la;E=ma;h=e.camera.projectionMatrix;c.scale(c.subtract(m,E,A),0.5);b[0]=A[0];b[1]=A[1];b[2]=0;b[3]=A[1];b[4]=-A[0];b[5]=0;b[6]=A[0]*A[0]+A[1]*A[1];b[7]=A[0]*A[1]-A[1]*A[0];b[8]=1;b[6]=-c.dot(v(b,
0),g);b[7]=-c.dot(v(b,1),g);g=c.dot(v(b,0),m)+b[6];z=c.dot(v(b,1),m)+b[7];f=c.dot(v(b,0),E)+b[6];E=c.dot(v(b,1),E)+b[7];g=-(g+f)/(z+E);b[0]+=b[1]*g;b[3]+=b[4]*g;b[6]+=b[7]*g;g=1/(c.dot(v(b,0),m)+b[6]);z=1/(c.dot(v(b,1),m)+b[7]);b[0]*=g;b[3]*=g;b[6]*=g;b[1]*=z;b[4]*=z;b[7]*=z;b[2]=b[1];b[5]=b[4];b[8]=b[7];b[7]+=1;g=c.dot(v(b,1),d)+b[7];z=c.dot(v(b,2),d)+b[8];f=c.dot(v(b,1),m)+b[7];E=c.dot(v(b,2),m)+b[8];g=-0.5*(g/z+f/E);b[1]+=b[2]*g;b[4]+=b[5]*g;b[7]+=b[8]*g;g=c.dot(v(b,1),d)+b[7];z=c.dot(v(b,2),d)+
b[8];f=-z/g;b[1]*=f;b[4]*=f;b[7]*=f;h[0]=b[0];h[1]=b[1];h[2]=0;h[3]=b[2];h[4]=b[3];h[5]=b[4];h[6]=0;h[7]=b[5];h[8]=0;h[9]=0;h[10]=1;h[11]=0;h[12]=b[6];h[13]=b[7];h[14]=0;h[15]=b[8];e.camera.projectionMatrix[10]=2/(H[2]-I[2]);e.camera.projectionMatrix[14]=-(H[2]+I[2])/(H[2]-I[2]);C.multiply(e.camera.projectionMatrix,e.camera.viewMatrix,e.lightMat);d=K/2;e.camera.viewport[0]=0===s%2?0:d;e.camera.viewport[1]=0===Math.floor(s/2)?0:d;e.camera.viewport[2]=d;e.camera.viewport[3]=d}M[L]=100*q;a.bindFramebuffer(a.FRAMEBUFFER,
U);a.activeTexture(a.TEXTURE7);a.bindTexture(a.TEXTURE_2D,null);a.activeTexture(a.TEXTURE0);a.clearColor(1,1,1,1);a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT)};var aa=[];this.getCascades=function(){for(var a=0;a<L;++a)aa[a]=O[a];aa.length=L;return aa};this.finish=function(b){k.assert(this.getEnableState());da.unuse(a);a.bindFramebuffer(a.FRAMEBUFFER,b)};this.bind=function(b){var c=this.getEnableState();a.activeTexture(a.TEXTURE7);a.bindTexture(a.TEXTURE_2D,c?p:ua);a.activeTexture(a.TEXTURE0);b.use();
b.uniform1i("depthTex",7);b.uniform1f("depthHalfPixelSz",c?0.5/K:-1);b.uniform1i("shadowMapNum",L);b.uniform4f("shadowMapDistance",M[0],M[1],M[2],M[3])};this.bindAll=function(a){a=a.getProgramsUsingUniform("shadowMapDistance");for(var b=0;b<a.length;b++)this.bind(a[b])};var t=G.create(),W=new Float32Array(64);this.bindView=function(a,b){if(this.getEnableState()){var c;G.translate(O[0].lightMat,b,t);for(c=0;16>c;++c)W[c]=t[c];G.translate(O[1].lightMat,b,t);for(c=0;16>c;++c)W[16+c]=t[c];G.translate(O[2].lightMat,
b,t);for(c=0;16>c;++c)W[32+c]=t[c];G.translate(O[3].lightMat,b,t);for(c=0;16>c;++c)W[48+c]=t[c];a.uniformMatrix4fv("shadowMapMatrix",W)}};e=new Float32Array(16);e[0]=0;e[1]=0;e[2]=0;e[3]=0;e[4]=256;e[5]=0;e[6]=1;e[7]=0;e[8]=0;e[9]=256;e[10]=0;e[11]=1;e[12]=256;e[13]=256;e[14]=1;e[15]=1;var ba=ra.Defaults.Pos2Tex,ca=new qa(e,ba,a);this.drawDebugQuad=function(b){k.assert(this.getEnableState());var c=u.get("showDepth");a.disable(a.DEPTH_TEST);c.use();c.uniformMatrix4fv("proj",b);c.uniform1i("depthTex",
0);a.bindTexture(a.TEXTURE_2D,p);ba.enableVertexAttribArrays(a,c);ca.bind();ca.setPointers(c);a.drawArrays(a.TRIANGLE_STRIP,0,ca.getNum());a.bindBuffer(a.ARRAY_BUFFER,null);ba.disableVertexAttribArrays(a,c);a.bindTexture(a.TEXTURE_2D,null);da.unuse(a);a.enable(a.DEPTH_TEST)};var B=c.create(),V=c.create(),P=[c.create(),c.create(),c.create(),c.create()],r=c.create(),pa=c.create(),N=c.create(),X=c.create(),S=c.create(),T=c.create(),Y=c.create(),fa=J.create(),A=c.create(),b=ta.create()}});