// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports","./Texture","./Util"],function(l,m,k,h){return function(){function b(c,a,e){this._idHint=e;this._text=c;this._textLines=c.split(/\r?\n/);this._params=a||{color:[0,0,0]};this._params.size=this._params.size||18;this._params.font=this._params.font||{family:"Arial"};this._params.font.family=this._params.font.family||"Arial";this._params.font.weight=this._params.font.weight||"normal";this._params.font.style=this._params.font.style||"normal";this._fillStyle="rgb("+this._params.color.map(function(a){return Math.floor(255*
a)}).toString()+")"}b.prototype.getId=function(){null==this._id&&(this._id=k.idGen.gen(this._idHint));return this._id};b.prototype.getParams=function(){return this._params};b.prototype.getString=function(){return this._text};b.prototype.renderGl=function(c,a){this._createTextTexture(c,a);a._isTracingEnabled&&(c._debugTracingType="TextTexture")};b.prototype.getTextWidth=function(){var c=this._create2DCanvas().getContext("2d");this._setTextProperties(c,this._params.size);var a=0,e;for(e in this._textLines){var b=
c.measureText(this._textLines[e]).width;b>a&&(a=b)}e=this._params.font;if("italic"===e.style||"oblique"===e.style||"string"===typeof e.weight&&("bold"===e.weight||"bolder"===e.weight)||"number"===typeof e.weight&&600<e.weight)a+=0.3*c.measureText("A").width;return a};b.prototype.getTextHeight=function(){return this.getLineHeight()*this._textLines.length};b.prototype.getTexcoordScale=function(){if(this._params.enableMipmapping){var c=this.getTextHeight(),a=this.getTextWidth();return[a/h.nextHighestPowerOfTwo(a),
c/h.nextHighestPowerOfTwo(c)]}return[1,1]};b.prototype.getLineHeight=function(){return Math.floor(1.2*this._params.size)};b.prototype.setUnloadFunc=function(c){this._unloadFunc=c};b.prototype.unload=function(){this._unloadFunc&&(this._unloadFunc(this._id),this._unloadFunc=null)};b.prototype.renderText=function(c,a,b,f,d,g){void 0===d&&(d=0);void 0===g&&(g=0);b=this.getLineHeight()*c;this._setTextProperties(f,this._params.size*c);c="center"===f.textAlign?0.5*a:"right"===f.textAlign?a:0;c+=d;d=0+g;
for(var h in this._textLines)f.fillText(this._textLines[h],c,d),d+=b};b.prototype._create2DCanvas=function(){null==b._textCanvas2D&&(b._textCanvas2D=document.createElement("canvas"),b._textCanvas2D.setAttribute("id","canvas2d"),b._textCanvas2D.setAttribute("width","1024"),b._textCanvas2D.setAttribute("height","1024"),b._textCanvas2D.setAttribute("style","display:none"));return b._textCanvas2D};b.prototype._setTextProperties=function(c,a){c.fillStyle=this._fillStyle;var b=this._params.font;c.font=
b.style+" "+b.weight+" "+a+"px "+b.family;c.textAlign="left";c.textBaseline="top";this._params.canvasStyle&&h.mergeObjects(c,this._params.canvasStyle,c)};b.prototype._createTextTexture=function(c,a){var e=this._create2DCanvas(),f=e.getContext("2d");f.save();var d=this.getTextWidth(),g=this.getTextHeight();this._params.enableMipmapping&&(d=h.nextHighestPowerOfTwo(d),g=h.nextHighestPowerOfTwo(g));a.bindTexture(a.TEXTURE_2D,c);e.setAttribute("width",d.toString());e.setAttribute("height",g.toString());
this.renderText(1,d,g,f);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,e);d=a.LINEAR;this._params.enableMipmapping&&(a.generateMipmap(a.TEXTURE_2D),b.MIPMAP_CREATE?(b.MIPMAP_CREATE(e,a),d=a.LINEAR_MIPMAP_LINEAR):(this._renderMipmap(a),d=a.LINEAR_MIPMAP_NEAREST));a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,
d);a.bindTexture(a.TEXTURE_2D,null);f.restore()};b.prototype._renderMipmap=function(b){var a=this._create2DCanvas(),e=a.getContext("2d"),f=parseInt(a.getAttribute("width"),10)/2,d=parseInt(a.getAttribute("height"),10)/2,g=0.5,h=1;do a.setAttribute("width",f.toString()),a.setAttribute("height",d.toString()),this.renderText(g,f,d,e),b.texSubImage2D(b.TEXTURE_2D,h,0,0,b.RGBA,b.UNSIGNED_BYTE,a),g*=0.5,f*=0.5,d*=0.5,h++;while(1<f&&1<d)};return b}()});