// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require exports ./Renderer ./GLFBO ./GLVBO ./VertexBufferLayout ./Camera ./Util ./gl-matrix ../materials/internal/TexOnlyGLMaterial".split(" "),function(p,C,r,s,t,u,v,w,n,x){var y=n.vec3d,z=n.vec4d,m=n.mat4d;p=function(){function f(a,g,e,b,c,d){this._acquiredTextures={};this._clearColor=z.createFrom(0,0,0,0);this._id2origin={};this._gl=a;this._canvas=g;this._programRep=e;this._materialRep=b;this._textureRep=c;this._modelDirtySet=d;this._renderer=new r(e,void 0,b,c,a,!0);this._renderer.setLightingData({ambient:[1,
1,1,1],diffuse:[0,0,0,0],specular:[0,0,0,0],direction:[0,-1,0]})}f.prototype.dispose=function(){for(var a in this._acquiredTextures)this._acquiredTextures[a].fbo.dispose(),this._textureRep.release(a);this._acquiredTextures=null;this._renderer.dispose();this._renderer=null};f.prototype.addRenderGeometries=function(a){var g=this;a.forEach(function(a){null==a.origin&&(a.origin=g.getOrigin(a.center,a.bsRadius))});this._renderer.modify(a,[])};f.prototype.removeRenderGeometries=function(a){this._renderer.modify([],
a)};f.prototype.updateRenderGeometries=function(a,g){var e=a.map(function(a){return{renderGeometry:a,updateType:g}});this._renderer.modify([],[],e,{})};f.prototype.updateRenderOrder=function(a){0<Object.keys(a).length&&this._renderer.modifyRenderOrder(a)};f.prototype.setBackgroundColor=function(a){this._clearColor=a};f.prototype.isEmpty=function(){return this._renderer.isEmpty()};f.prototype.processDirtyMaterials=function(){var a=this._modelDirtySet.getDirtyMaterials();a&&this._renderer.modify([],
[],[],a);this._modelDirtySet.clearDirtyMaterials()};f.prototype.draw=function(a,g){this.processDirtyMaterials();var e=a.getId(),b,c=this._gl;if(this._acquiredTextures[e])b=this._acquiredTextures[e].fbo;else{var d=this._textureRep.aquire(e);b=new s(6408,5121,!1,9728,c,d);var l=Object.keys(this._acquiredTextures).length;this._acquiredTextures[e]={glName:d,fbo:b,idx:l}}d=g.width;l=g.height;if(b.getWidth()!==d||b.getHeight()!==l)b.setSize(d,l),c.texParameteri(3553,10241,9729),c.texParameteri(3553,10240,
9729);k.near=1;k.far=1E4;b.bind();c.disable(2929);c.blendFuncSeparate(770,771,1,771);c.clearColor.apply(c,this._clearColor);c.clear(16384);this._renderer.setPixelRatio(g.pixelRatio||1);for(b=0;b<g.views.length;b++){var h=g.views[b];k.viewport=h.viewport;m.ortho(0,h.extent[2]-h.extent[0],0,h.extent[3]-h.extent[1],k.near,k.far,k.projectionMatrix);m.identity(k.viewMatrix);m.translate(k.viewMatrix,[-h.extent[0],-h.extent[1],0]);k.setGLViewport(c);A&&this._drawTestTexture(d,l,q[this._acquiredTextures[e].idx%
q.length]);this._renderer.render(k,B)}c.enable(c.DEPTH_TEST);c.blendFunc(c.SRC_ALPHA,c.ONE_MINUS_SRC_ALPHA);c.bindFramebuffer(c.FRAMEBUFFER,null);c.viewport(0,0,this._canvas.width,this._canvas.height)};f.prototype._drawTestTexture=function(a,g,e){var b=this._gl;if(!this._testPatternMat){for(var c=new Uint8Array(4*a*g),d=0,l=0;l<g;l++)for(var h=0;h<a;h++){var f=Math.floor(h/10),k=Math.floor(l/10);2>f||2>k||10*f>a-20||10*k>g-20?(c[d++]=255,c[d++]=255,c[d++]=255,c[d++]=255):(c[d++]=255,c[d++]=255,c[d++]=
255,f&1&&k&1?c[d++]=h&1^l&1?0:255:c[d++]=f&1^k&1?0:128)}d=b.createTexture();b.bindTexture(b.TEXTURE_2D,d);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.NEAREST);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,b.NEAREST);b.texImage2D(b.TEXTURE_2D,0,b.RGBA,a,g,0,b.RGBA,b.UNSIGNED_BYTE,c);this._testPatternMat=new x(this._programRep,d,[1,1,1,1],!0,b.ALWAYS);this._testPatternBindParams={proj:m.identity(),view:m.identity(),nearFar:[-1,1],origin:[0,0,0]};a=new Float32Array(20);a[0]=-1;a[1]=-1;a[2]=
0;a[3]=0;a[4]=0;a[5]=1;a[6]=-1;a[7]=0;a[8]=1;a[9]=0;a[10]=-1;a[11]=1;a[12]=0;a[13]=0;a[14]=1;a[15]=1;a[16]=1;a[17]=0;a[18]=1;a[19]=1;this._quadVBO=new t(a,u.Defaults.PosTex,b)}this._testPatternMat.setColor([e[0],e[1],e[2],1]);this._testPatternMat.bind(b,this._testPatternBindParams);this._testPatternMat.bindView(b,this._testPatternBindParams);this._quadVBO.bind();this._quadVBO.setPointers(this._testPatternMat.getProgram());b.drawArrays(b.TRIANGLE_STRIP,0,this._quadVBO.getNum());this._testPatternMat.release(b)};
f.prototype.getOrigin=function(a,g){var e=0,b=10*g/1E4;1<b&&(e=Math.ceil(w.logWithBase(b,2)));var b=1E4*Math.pow(2,e),c=Math.round(a[0]/b),d=Math.round(a[1]/b),f=Math.round(a[2]/b),e=e+"_"+c+"_"+d+"_"+f,h=this._id2origin[e];null==h&&(h={vec3:y.createFrom(c*b,d*b,f*b),id:e},this._id2origin[e]=h);return h};return f}();var A=!1,q=[[1,0.5,0.5],[0.5,0.5,1],[0.5,1,0.5]],B={get:function(){return!0}},k=new v;return p});