// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/array dojo/_base/lang dojo/_base/kernel ../core/lang ./SpatialReference ./Geometry ./Point ./support/webMercatorUtils ./support/mathUtils".split(" "),function(x,v,y,u,z,w,A,k,t,B){var q=x(A,{declaredClass:"esri.geometry.Extent",classMetadata:{properties:{cache:{dependsOn:"xmin ymin zmin mmin xmax ymax zmax mmax".split(" ")},center:{dependsOn:["cache"]},extent:{dependsOn:["cache"]},hasM:{dependsOn:["mmin","mmax"]},hasZ:{dependsOn:["zmin","zmax"]},height:{dependsOn:["ymin",
"ymax"]},width:{dependsOn:["xmin","xmax"]}}},normalizeCtorArgs:function(a,c,b,e,d){return this.isSR(a)?{spatialReference:a,xmin:0,ymin:0,xmax:0,ymax:0}:y.isObject(a)?(a.spatialReference=a.spatialReference||w.WGS84,a):{xmin:a,ymin:c,xmax:b,ymax:e,spatialReference:d||w.WGS84}},_centerGetter:function(a){a||(a=new k({spatialReference:this.spatialReference}));a.x=0.5*(this.xmin+this.xmax);a.y=0.5*(this.ymin+this.ymax);this.hasZ&&(a.z=0.5*(this.zmin+this.zmax));this.hasM&&(a.m=0.5*(this.mmin+this.mmax));
return a},_extentGetter:function(){return this.clone()},_hasMGetter:function(){return null!=this.mmin&&null!=this.mmax},_hasZGetter:function(){return null!=this.zmin&&null!=this.zmax},_heightGetter:function(){return Math.abs(this.ymax-this.ymin)},type:"extent",_widthGetter:function(){return Math.abs(this.xmax-this.xmin)},xmin:0,ymin:0,mmin:void 0,zmin:void 0,xmax:0,ymax:0,mmax:void 0,zmax:void 0,centerAt:function(a){var c=this.center;return null!=a.z&&this.hasZ?this.offset(a.x-c.x,a.y-c.y,a.z-c.z):
this.offset(a.x-c.x,a.y-c.y)},clone:function(){var a=new q;a.xmin=this.xmin;a.ymin=this.ymin;a.xmax=this.xmax;a.ymax=this.ymax;a.spatialReference=this.spatialReference;null!=this.zmin&&(a.zmin=this.zmin,a.zmax=this.zmax);null!=this.mmin&&(a.mmin=this.mmin,a.mmax=this.mmax);return a},contains:function(a){if(!a)return!1;var c=a.type;if("point"===c){var b=this.spatialReference,e=a.spatialReference,c=a.x,d=a.y;a=a.z;b&&(e&&!b.equals(e)&&b._canProject(e))&&(b=b.isWebMercator?k.lngLatToXY(c,d):k.xyToLngLat(c,
d,!0),c=b[0],d=b[1]);if(c>=this.xmin&&c<=this.xmax&&d>=this.ymin&&d<=this.ymax)return null!=a&&this.hasZ?a>=this.zmin&&a<=this.zmax:!0}else if("extent"===c)return this._containsExtent(a);return!1},equals:function(a){if(!a)return!1;var c=this.spatialReference;if(!c.equals(a.spatialReference))if(t.canProject(a.spatialReference,c))a=t.project(a,c);else return!1;return this.xmin===a.xmin&&this.ymin===a.ymin&&this.zmin===a.zmin&&this.mmin===a.mmin&&this.xmax===a.xmax&&this.ymax===a.ymax&&this.zmax===a.zmax&&
this.mmax===a.mmax},expand:function(a){a=0.5*(1-a);var c=this.width*a,b=this.height*a;this.xmin+=c;this.ymin+=b;this.xmax-=c;this.ymax-=b;this.hasZ&&(c=(this.zmax-this.zmin)*a,this.zmin+=c,this.zmax-=c);this.hasM&&(a*=this.mmax-this.mmin,this.mmin+=a,this.mmax-=a);return this},intersects:function(a){if(!a)return!1;var c=a.type,b=this.spatialReference,e=a.spatialReference;b&&(e&&!b.equals(e)&&b._canProject(e))&&(a=b.isWebMercator?t.geographicToWebMercator(a):t.webMercatorToGeographic(a,!0));switch(c){case "point":return this.contains(a);
case "multipoint":return this._intersectsMultipoint(a);case "extent":return this._intersectsExtent(a);case "polygon":return this._intersectsPolygon(a);case "polyline":return this._intersectsPolyline(a)}},normalize:function(){var a=this._normalize(!1,!0);Array.isArray(a)||(a=[a]);return a},offset:function(a,c,b){this.xmin+=a;this.ymin+=c;this.xmax+=a;this.ymax+=c;null!=b&&(this.zmin+=b,this.zmax+=b);return this},shiftCentralMeridian:function(){return this._normalize(!0)},toJSON:function(){var a=this.spatialReference,
a={xmin:this.xmin,ymin:this.ymin,xmax:this.xmax,ymax:this.ymax,spatialReference:a&&a.toJSON()};this.hasZ&&(a.zmin=this.zmin,a.zmax=this.zmax);this.hasM&&(a.mmax=this.mmax,a.mmin=this.mmin);return a},union:function(a){function c(a,c,d){return null==c?d:null==d?c:a(c,d)}this.xmin=Math.min(this.xmin,a.xmin);this.ymin=Math.min(this.ymin,a.ymin);this.xmax=Math.max(this.xmax,a.xmax);this.ymax=Math.max(this.ymax,a.ymax);if(this.hasZ||a.hasZ)this.zmin=c(Math.min,this.zmin,a.zmin),this.zmax=c(Math.max,this.zmax,
a.zmax);if(this.hasM||a.hasM)this.mmin=c(Math.min,this.mmin,a.mmin),this.mmax=c(Math.max,this.mmax,a.mmax);return this},_containsExtent:function(a){var c=a.xmin,b=a.ymin,e=a.zmin,d=a.xmax,f=a.ymax,g=a.zmax;a=a.spatialReference;return null!=e&&this.hasZ?this.contains(new k(c,b,e,a))&&this.contains(new k(c,f,e,a))&&this.contains(new k(d,f,e,a))&&this.contains(new k(d,b,e,a))&&this.contains(new k(c,b,g,a))&&this.contains(new k(c,f,g,a))&&this.contains(new k(d,f,g,a))&&this.contains(new k(d,b,g,a)):this.contains(new k(c,
b,a))&&this.contains(new k(c,f,a))&&this.contains(new k(d,f,a))&&this.contains(new k(d,b,a))},_intersectsMultipoint:function(a){var c=a.points.length,b;for(b=0;b<c;b++)if(this.contains(a.getPoint(b)))return!0;return!1},_intersectsExtent:function(a){var c,b;b=this.hasZ&&a.hasZ;if(this.xmin<=a.xmin){if(c=a.xmin,this.xmax<c)return!1}else if(c=this.xmin,a.xmax<c)return!1;if(this.ymin<=a.ymin){if(c=a.ymin,this.ymax<c)return!1}else if(c=this.ymin,a.ymax<c)return!1;if(b)if(this.zmin<=a.zmin){if(b=a.zmin,
this.zmax<b)return!1}else if(b=this.zmin,a.zmax<b)return!1;return!0},_intersectsPolygon:function(a){var c=[this.xmin,this.ymax],b=[this.xmax,this.ymax],e=[this.xmin,this.ymin],d=[this.xmax,this.ymin],f=[c,b,e,d],c=[[e,c],[c,b],[b,d],[d,e]],e=a.rings,d=e.length,g,h=new k(0,0,this.spatialReference);g=f.length;for(b=0;b<g;b++)if(h.x=f[b][0],h.y=f[b][1],a.contains(h))return!0;for(var h={x:0,y:0,spatialReference:a.spatialReference,type:"point"},p,m,b=0;b<d;b++)if(f=e[b],g=f.length){p=f[0];h.x=p[0];h.y=
p[1];if(this.contains(h))return!0;for(a=1;a<g;a++){m=f[a];h.x=m[0];h.y=m[1];if(this.contains(h)||this._intersectsLine([p,m],c))return!0;p=m}}return!1},_intersectsPolyline:function(a){var c=[[[this.xmin,this.ymin],[this.xmin,this.ymax]],[[this.xmin,this.ymax],[this.xmax,this.ymax]],[[this.xmax,this.ymax],[this.xmax,this.ymin]],[[this.xmax,this.ymin],[this.xmin,this.ymin]]],b,e=a.paths,d=e.length,f,g,h,p,m={x:0,y:0,spatialReference:a.spatialReference,type:"point"};for(a=0;a<d;a++)if(f=e[a],g=f.length){h=
f[0];m.x=h[0];m.y=h[1];if(this.contains(m))return!0;for(b=1;b<g;b++){p=f[b];m.x=p[0];m.y=p[1];if(this.contains(m)||this._intersectsLine([h,p],c))return!0;h=p}}return!1},_intersectsLine:function(a,c){var b=B._getLineIntersection2,e,d=c.length;for(e=0;e<d;e++)if(b(a,c[e]))return!0;return!1},_shiftCM:function(a){var c=this.spatialReference;if(a=a||c._getInfo()){var b=this._getCM(a);if(b){var e=c.isWebMercator?t.webMercatorToGeographic(b):b;this.xmin-=b.x;this.xmax-=b.x;c.isWebMercator||(e.x=this._normalizeX(e.x,
a).x);this.spatialReference=new w(z.substitute({Central_Meridian:e.x},4326===c.wkid?a.altTemplate:a.wkTemplate))}}return this},_getCM:function(a){var c,b=a.valid[0];a=a.valid[1];var e=this.xmin,d=this.xmax;if(!(e>=b&&e<=a)||!(d>=b&&d<=a))c=this.center;return c},_normalize:function(a,c,b){var e=this.spatialReference;if(e&&(b=b||e._getInfo())){var d=v.map(this._getParts(b),function(a){return a.extent});if(2<d.length)return a?this._shiftCM(b):this.set({xmin:b.valid[0],xmax:b.valid[1]});if(2===d.length){if(a)return this._shiftCM(b);
if(c)return d;var f=!0,g=!0;v.map(d,function(a){a.hasZ||(f=!1);a.hasM||(g=!1)});return{rings:v.map(d,function(a){var b=[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]];if(f)for(var c=(a.zmax-a.zmin)/2,d=0;d<b.length;d++)b[d].push(c);if(g){a=(a.mmax-a.mmin)/2;for(d=0;d<b.length;d++)b[d].push(a)}return b}),hasZ:f,hasM:g,spatialReference:e}}return d[0]||this}return this},_getParts:function(a){var c=this.cache._parts;if(!c){var c=[],b=this.xmin,e=this.xmax,d=this.ymin,
f=this.ymax,g=this.spatialReference,h=this.width,k=b,m=e,n=0,l=0,r,s;a=a||g._getInfo();r=a.valid[0];s=a.valid[1];l=this._normalizeX(b,a);b=l.x;n=l.frameId;l=this._normalizeX(e,a);e=l.x;l=l.frameId;a=b===e&&0<h;if(h>2*s){h=new q(k<m?b:e,d,s,f,g);b=new q(r,d,k<m?e:b,f,g);s=new q(0,d,s,f,g);d=new q(r,d,0,f,g);g=[];r=[];h.contains(s)&&g.push(n);h.contains(d)&&r.push(n);b.contains(s)&&g.push(l);b.contains(d)&&r.push(l);for(f=n+1;f<l;f++)g.push(f),r.push(f);c.push({extent:h,frameIds:[n]},{extent:b,frameIds:[l]},
{extent:s,frameIds:g},{extent:d,frameIds:r})}else b>e||a?c.push({extent:new q(b,d,s,f,g),frameIds:[n]},{extent:new q(r,d,e,f,g),frameIds:[l]}):c.push({extent:new q(b,d,e,f,g),frameIds:[n]});this.cache._parts=c}l=this.hasZ;d=this.hasM;if(l||d){n={};l&&(n.zmin=this.zmin,n.zmax=this.zmax);d&&(n.mmin=this.mmin,n.mmax=this.mmax);for(l=0;l<c.length;l++)c[l].extent.set(n)}return c},_normalizeX:function(a,c){var b=0,e=c.valid[0],d=c.valid[1],f=2*d;a>d?(b=Math.ceil(Math.abs(a-d)/f),a-=b*f):a<e&&(b=Math.ceil(Math.abs(a-
e)/f),a+=b*f,b=-b);return{x:a,frameId:b}},getWidth:function(){u.deprecated(this.declaredClass+".getWidth","Use .width instead","4.0");return this.width},getHeight:function(){u.deprecated(this.declaredClass+".getHeight","Use .height instead","4.0");return this.height},getCenter:function(){u.deprecated(this.declaredClass+".getCenter","Use .center instead","4.0");return this.center},update:function(a,c,b,e,d){u.deprecated(this.declaredClass+".update","Use .set instead","4.0");this.set({xmin:a,ymin:c,
xmax:b,ymax:e,spatialReference:d})}});return q});