// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["../core/declare","dojo/_base/lang","dojo/_base/kernel","./SpatialReference","./Geometry"],function(s,t,k,u,v){function m(a,b,c,e){89.99999<b?b=89.99999:-89.99999>b&&(b=-89.99999);b*=q;e||(e=[0,0]);e[0]=a*q*n;e[1]=n/2*Math.log((1+Math.sin(b))/(1-Math.sin(b)));return e}function p(a,b,c,e){a=a/n*r;e||(e=[0,0]);e[0]=c?a:a-360*Math.floor((a+180)/360);c=e;b=w/2-2*Math.atan(Math.exp(-1*b/n));c[1]=b*r;return e}var n=6378137,w=3.141592653589793,r=57.29577951308232,q=0.017453292519943,l=[0,0],g=s(v,
{declaredClass:"esri.geometry.Point",classMetadata:{properties:{cache:{dependsOn:["x","y","z","m"]},hasM:{dependsOn:["m"]},hasZ:{dependsOn:["z"]},longitude:{dependsOn:["x"]},latitude:{dependsOn:["y"]}}},normalizeCtorArgs:function(a,b,c,e,f){var d;Array.isArray(a)?(d=a,f=b,a=d[0],b=d[1],c=d[2],e=d[3]):t.isObject(a)?(d=a,a=null!=d.x?d.x:d.longitude,b=null!=d.y?d.y:d.latitude,c=null!=d.z?d.z:d.altitude,e=d.m,(f=d.spatialReference)&&"esri.SpatialReference"!==f.declaredClass&&(f=new u(f)),!d.declaredClass&&
(f&&f.isWebMercator&&null!=d.longitude&&null!=d.latitude)&&(b=m(d.longitude,d.latitude,!1,l),a=b[0],b=b[1])):this.isSR(c)?(f=c,c=null):this.isSR(e)&&(f=e,e=null);a={x:a,y:b};null!=f&&(a.spatialReference=f);null!=c&&(a.z=c);null!=e&&(a.m=e);return a},_latitudeGetter:function(){var a=this.spatialReference;if(a){if(a.isWebMercator)return p(this.x,this.y,!1,l)[1];if(4326===a.wkid)return this.y}return null},_latitudeSetter:function(a){var b=this.spatialReference;b&&(b.isWebMercator?this.y=m(this.x,a,!1,
l)[1]:4326===b.wkid&&(this.y=a))},_longitudeGetter:function(){var a=this.spatialReference;if(a){if(a.isWebMercator)return p(this.x,this.y,!1,l)[0];if(4326===a.wkid)return this.x}return null},_longitudeSetter:function(a){var b=this.spatialReference;b&&(b.isWebMercator?this.x=m(a,this.y,!1,l)[0]:4326===b.wkid&&(this.x=a))},_hasMGetter:function(){return void 0!==this.m},_hasMSetter:function(a,b){return a!==b?(this.m=a?0:void 0,a):b},_hasZGetter:function(){return void 0!==this.z},_hasZSetter:function(a,
b){return a!==b?(this.z=a?0:void 0,a):b},x:0,y:0,z:void 0,m:void 0,type:"point",clone:function(){var a=new g;a.x=this.x;a.y=this.y;a.z=this.z;a.m=this.m;a.spatialReference=this.spatialReference;return a},copy:function(a){g.copy(a,this);return this},equals:function(a){if(!a)return!1;var b=this.x,c=this.y,e=this.z,f=this.m,d=this.spatialReference,g=a.x,h=a.y,k=a.z,l=a.m;a=a.spatialReference;if(!d.equals(a))if(d.isWebMercator&&4326===a.wkid)h=m(g,h),g=h[0],h=h[1],a=d;else if(4326===d.wkid&&a.isWebMercator)h=
p(g,h),g=h[0],h=h[1],a=d;else return!1;return b===g&&c===h&&e===k&&f===l&&d.wkid===a.wkid},offset:function(a,b,c){this.x+=a;this.y+=b;null!=c&&this.hasZ&&(this.z+=c);return this},normalize:function(){var a=this.x,b=this.spatialReference;if(b){var c=b._getInfo();if(c){var b=c.valid[0],e=c.valid[1],c=2*e;a>e?(b=Math.ceil(Math.abs(a-e)/c),a-=b*c):a<b&&(b=Math.ceil(Math.abs(a-b)/c),a+=b*c)}}this.x=a;return this},distance:function(a){return g.distance(this,a)},toArray:function(){var a=this.hasZ,b=this.hasM;
return a&&b?[this.x,this.y,this.z,this.m]:a?[this.x,this.y,this.z]:b?[this.x,this.y,this.m]:[this.x,this.y]},toJSON:function(){var a=this.spatialReference,b={x:this.x,y:this.y};this.hasZ&&(b.z=this.z);this.hasM&&(b.m=this.m);b.spatialReference=a&&a.toJSON();return b},setX:function(a){k.deprecated(this.declaredClass+".setX","Use .x \x3d value instead","4.0");this.x=a;return this},setY:function(a){k.deprecated(this.declaredClass+".setY","Use .y \x3d value instead","4.0");this.y=a;return this},setLongitude:function(a){k.deprecated(this.declaredClass+
".setLongitude","Use .longitude \x3d value; instead","4.0");this.longitude=a;return this},setLatitude:function(a){k.deprecated(this.declaredClass+".setLatitude","Use .latitude \x3d value; instead","4.0");this.latitude=a;return this},getLongitude:function(){k.deprecated(this.declaredClass+".getLongitude","Use .longitude instead","4.0");return this.longitude},getLatitude:function(){k.deprecated(this.declaredClass+".getLatitude","Use .latitude instead","4.0");return this.latitude},update:function(a,
b,c){k.deprecated(this.declaredClass+".update","Use .x/y/z \x3d value instead","4.0");a={x:a,y:b};null!=c&&(a.z=c);return this.set(a)}});g.lngLatToXY=m;g.xyToLngLat=p;g.copy=function(a,b){b.x=a.x;b.y=a.y;b.z=a.z;b.m=a.m;b.spatialReference=Object.isFrozen(a.spatialReference)?a.spatialReference:a.spatialReference.clone()};g.distance=function(a,b){var c=a.x-b.x,e=a.y-b.y,f=a.hasZ&&b.hasZ?a.z-b.z:0;return Math.sqrt(c*c+e*e+f*f)};return g});