// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/array dojo/_base/lang ../core/lang ./SpatialReference ./Geometry ./Point ./Extent ./support/zmUtils".split(" "),function(M,m,N,O,P,Q,f,J,h){var p=M(Q,{declaredClass:"esri.geometry.Polyline",classMetadata:{properties:{cache:{dependsOn:["hasM","hasZ","paths"]},extent:{dependsOn:["cache"]}}},getDefaults:function(a){return{paths:[]}},normalizeCtorArgs:function(a,b){var c=null,e=void 0,d=void 0,g=null;a&&!Array.isArray(a)?(c=a.paths?a.paths:null,b||(a.spatialReference?
b=a.spatialReference:a.paths||(b=a)),e=a.hasZ,d=a.hasM):c=a;c=c||[];b=b||P.WGS84;c.length&&(c[0]&&null!=c[0][0]&&"number"==typeof c[0][0])&&(c=[c]);if(g=c[0]&&c[0][0])void 0===e&&void 0===d?(e=2<g.length,d=!1):void 0===e?e=!d&&3<g.length:void 0===d&&(d=!e&&3<g.length);return{paths:c,spatialReference:b,hasZ:e,hasM:d}},_extent:null,_path:0,_extentGetter:function(){function a(a){return function(b,c){return void 0===b?c:void 0===c?b:a(b,c)}}var b=this.paths,c=b.length;if(!c||!b[0].length)return null;
var e,d,g,f,n,h,q,m,C,r,s,p,D=h=b[0][0][0],E=q=b[0][0][1],F,G,k=a(Math.min),l=a(Math.max),t=this.spatialReference,H=[],u,v,w,x,y,z,A,B,I=this.hasZ,K=this.hasM,L=I?3:2;for(r=0;r<c;r++){e=b[r];u=v=e[0]&&e[0][0];w=x=e[0]&&e[0][1];p=e.length;A=B=y=z=void 0;for(s=0;s<p;s++)d=e[s],g=d[0],f=d[1],D=k(D,g),E=k(E,f),h=l(h,g),q=l(q,f),u=k(u,g),w=k(w,f),v=l(v,g),x=l(x,f),I&&2<d.length&&(n=d[2],F=k(F,n),m=l(m,n),y=k(y,n),z=l(z,n)),K&&d.length>L&&(d=d[L],G=k(G,n),C=l(C,n),A=k(A,d),B=l(B,d));H.push(new J({xmin:u,
ymin:w,zmin:y,mmin:A,xmax:v,ymax:x,zmax:z,mmax:B,spatialReference:t?t.clone():null}))}b=new J({xmin:D,ymin:E,xmax:h,ymax:q,spatialReference:t?t.toJSON():null});I&&(b.zmin=F,b.zmax=m);K&&(b.mmin=G,b.mmax=C);b._partwise=1<H.length?H:null;return b},paths:null,type:"polyline",addPath:function(a){this.clearCache();this._path=this.paths.length;this.paths[this._path]=[];m.forEach(a,this._addPoint,this);return this},clone:function(){var a=new p;a.spatialReference=this.spatialReference;a.paths=N.clone(this.paths);
a.hasZ=this.hasZ;a.hasM=this.hasM;return a},getPoint:function(a,b){if(this._validateInputs(a,b)){var c=this.paths[a][b],e=this.hasZ,d=this.hasM;return e&&d?new f(c[0],c[1],c[2],c[3],this.spatialReference):e?new f(c[0],c[1],c[2],void 0,this.spatialReference):d?new f(c[0],c[1],void 0,c[2],this.spatialReference):new f(c[0],c[1],this.spatialReference)}},insertPoint:function(a,b,c){if(this._validateInputs(a)&&O.isDefined(b)&&0<=b&&b<=this.paths[a].length)return this.clearCache(),h.updateSupportFromPoint(this,
c),Array.isArray(c)||(c=c.toArray()),this.paths[a].splice(b,0,c),this},removePath:function(a){if(this._validateInputs(a,null)){this.clearCache();a=this.paths.splice(a,1)[0];var b,c=a.length,e=this.spatialReference;for(b=0;b<c;b++)a[b]=new f(a[b],e);return a}},removePoint:function(a,b){if(this._validateInputs(a,b))return this.clearCache(),new f(this.paths[a].splice(b,1)[0],this.spatialReference)},setPoint:function(a,b,c){if(this._validateInputs(a,b))return this.clearCache(),h.updateSupportFromPoint(this,
c),Array.isArray(c)||(c=c.toArray()),this.paths[a][b]=c,this},toJSON:function(){var a=this.spatialReference,a={paths:this.paths,spatialReference:a&&a.toJSON()};this.hasZ&&(a.hasZ=!0);this.hasM&&(a.hasM=!0);return a},_initPathPointsToArray:function(a){for(var b=0;b<a.paths.length;b++)a.paths[b]=m.map(a.paths[b],function(b){h.updateSupportFromPoint(a,b,!0);Array.isArray(b)||(a.spatialReference||(a.spatialReference=b.spatialReference),b=b.toArray());return b});return a},_addPoint:function(a){Array.isArray(a)?
this.paths[this._path].push(a):this.paths[this._path].push(a.toArray());h.updateSupportFromPoint(this,a)},_insertPoints:function(a,b){this.clearCache();this._path=b;this.paths[this._path]||(this.paths[this._path]=[]);m.forEach(a,this._addPoint,this)},_validateInputs:function(a,b){return null!==a&&void 0!==a&&(0>a||a>=this.paths.length)||null!==b&&void 0!==a&&(0>b||b>=this.paths[a].length)?!1:!0}});return p});