// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/lang ../core/declare ../core/lang ./SpatialReference ./Geometry ./Point ./Extent ./support/coordsUtils ./support/mathUtils ./support/webMercatorUtils".split(" "),function(s,L,M,N,O,P,n,I,t,u,v){var w=function(a){return function(b,c){return null==b?c:null==c?b:a(b,c)}},p=w(Math.min),r=w(Math.max),m=M(P,{declaredClass:"esri.geometry.Polygon",classMetadata:{properties:{cache:{dependsOn:["hasM","hasZ","rings"]},extent:{dependsOn:["cache"]},centroid:{dependsOn:["cache"]},
isSelfIntersecting:{dependsOn:["cache"]}}},type:"polygon",getDefaults:function(a){return{rings:[]}},normalizeCtorArgs:function(a,b){var c=null,d=void 0,e=void 0,l=null;a&&!Array.isArray(a)?(c=a.rings?a.rings:null,b||(a.spatialReference?b=a.spatialReference:a.rings||(b=a)),d=a.hasZ,e=a.hasM):c=a;c=c||[];b=b||O.WGS84;c.length&&(c[0]&&null!=c[0][0]&&"number"==typeof c[0][0])&&(c=[c]);if(l=c[0]&&c[0][0])void 0===d&&void 0===e?(d=2<l.length,e=!1):void 0===d?d=!e&&3<l.length:void 0===e&&(e=!d&&3<l.length);
return{rings:c,spatialReference:b,hasZ:d,hasM:e}},_ring:0,_centroidGetter:function(a){var b=t.centroid([],this.rings,this.hasZ);if(isNaN(b[0])||isNaN(b[1])||this.hasZ&&isNaN(b[2]))return null;a=a||new n;a.x=b[0];a.y=b[1];a.spatialReference=this.spatialReference;this.hasZ&&(a.z=b[2]);return a},_extentGetter:function(a){var b=this.rings,c=b.length;if(!c||!b[0].length)return null;var d,e,l,g,f,h,k,J,q,m,n,s=f=b[0][0][0],t=h=b[0][0][1],z,u,v=this.spatialReference,E=[],A,B,C,D,x,y,F,G,H=this.hasZ,w=this.hasM,
K=H?3:2;for(q=0;q<c;q++){d=b[q];A=B=d[0]&&d[0][0];C=D=d[0]&&d[0][1];n=d.length;F=G=x=y=void 0;for(m=0;m<n;m++)e=d[m],l=e[0],g=e[1],s=p(s,l),t=p(t,g),f=r(f,l),h=r(h,g),A=p(A,l),C=p(C,g),B=r(B,l),D=r(D,g),H&&2<e.length&&(l=e[2],z=p(z,l),k=r(k,l),x=p(x,l),y=r(y,l)),w&&e.length>K&&(e=e[K],u=p(z,e),J=r(k,e),F=p(x,e),G=r(y,e));E.push(new I({xmin:A,ymin:C,zmin:x,mmin:F,xmax:B,ymax:D,zmax:y,mmax:G,spatialReference:v}))}a=a||new I;a.xmin=s;a.ymin=t;a.xmax=f;a.ymax=h;a.spatialReference=v;H&&(a.zmin=z,a.zmax=
k);w&&(a.mmin=u,a.mmax=J);a._partwise=1<E.length?E:null;return a},_isSelfIntersectingGetter:function(){var a=this.rings,b=a.length,c,d,e,l,g,f,h,k,m;for(l=0;l<b;l++){c=a[l];for(d=0;d<c.length-1;d++){f=[[c[d][0],c[d][1]],[c[d+1][0],c[d+1][1]]];for(e=l+1;e<b;e++)for(g=0;g<a[e].length-1;g++)if(h=[[a[e][g][0],a[e][g][1]],[a[e][g+1][0],a[e][g+1][1]]],(k=u._getLineIntersection2(f,h))&&!(k[0]===f[0][0]&&k[1]===f[0][1]||k[0]===h[0][0]&&k[1]===h[0][1]||k[0]===f[1][0]&&k[1]===f[1][1]||k[0]===h[1][0]&&k[1]===
h[1][1]))return!0}g=c.length;if(!(4>=g))for(d=0;d<g-3;d++){m=g-1;0===d&&(m=g-2);f=[[c[d][0],c[d][1]],[c[d+1][0],c[d+1][1]]];for(e=d+2;e<m;e++)if(h=[[c[e][0],c[e][1]],[c[e+1][0],c[e+1][1]]],(k=u._getLineIntersection2(f,h))&&!(k[0]===f[0][0]&&k[1]===f[0][1]||k[0]===h[0][0]&&k[1]===h[0][1]||k[0]===f[1][0]&&k[1]===f[1][1]||k[0]===h[1][0]&&k[1]===h[1][1]))return!0}}return!1},rings:null,addRing:function(a){if(a){this.clearCache();var b=this.rings,c=b.length;if(Array.isArray(a[0]))b[c]=a.concat();else{var d=
[];b[c]=d;b=0;for(c=a.length;b<c;b++)d[b]=a[b].toArray()}return this}},clone:function(){var a=new m;a.spatialReference=this.spatialReference;a.rings=L.clone(this.rings);a.hasZ=this.hasZ;a.hasM=this.hasM;return a},contains:function(a){if(!a)return!1;v.canProject(a,this.spatialReference)&&(a=v.project(a,this.spatialReference));return t.contains(this.rings,t.fromGeom(a))},isClockwise:function(a){var b=0,c=0,d=0,e,l=a.length,g,f,h,k=this.hasZ,m=this.hasM;for(e=0;e<l;e++)g=a[e],f=a[(e+1)%l],Array.isArray(g)?
(b+=g[0]*f[1]-f[0]*g[1],h=2,2<g.length&&(2<f.length&&k)&&(c+=g[0]*f[2]-f[0]*g[2],h=3),g.length>h&&(f.length>h&&m)&&(d+=g[0]*f[h]-f[0]*g[h])):(b+=g.x*f.y-f.x*g.y,g.hasZ&&f.hasZ&&(c+=g.x*f.z-f.x*g.z),g.hasM&&f.hasM&&(d+=g.x*f.m-f.x*g.m));return 0>=b&&0>=c&&0>=d},getPoint:function(a,b){if(this._validateInputs(a,b)){var c=this.rings[a][b],d=this.hasZ,e=this.hasM;return d&&!e?new n(c[0],c[1],c[2],void 0,this.spatialReference):e&&d?new n(c[0],c[1],void 0,c[2],this.spatialReference):d&&e?new n(c[0],c[1],
c[2],c[3],this.spatialReference):new n(c[0],c[1],this.spatialReference)}},insertPoint:function(a,b,c){if(this._validateInputs(a)&&N.isDefined(b)&&0<=b&&b<=this.rings[a].length)return this.clearCache(),this.rings[a].splice(b,0,c),this},removePoint:function(a,b){if(this._validateInputs(a,b))return this.clearCache(),new n(this.rings[a].splice(b,1)[0],this.spatialReference)},removeRing:function(a){if(this._validateInputs(a,null)){this.clearCache();a=this.rings.splice(a,1)[0];var b,c=a.length,d=this.spatialReference;
for(b=0;b<c;b++)a[b]=new n(a[b],d);return a}},setPoint:function(a,b,c){if(this._validateInputs(a,b))return this.clearCache(),Array.isArray(c)||(c=c.toArray()),this.rings[a][b]=c,this},toJSON:function(){var a=this.spatialReference,a={rings:this.rings,spatialReference:a&&a.toJSON()};this.hasZ&&(a.hasZ=!0);this.hasM&&(a.hasM=!0);return a},_insertPoints:function(a,b){this.clearCache();this._ring=b;this.rings[this._ring]||(this.rings[this._ring]=[]);s.forEach(a,this._addPoint,this)},_validateInputs:function(a,
b){return null!==a&&void 0!==a&&(0>a||a>=this.rings.length)||null!==b&&void 0!==a&&(0>b||b>=this.rings[a].length)?!1:!0}});m.createEllipse=function(a){var b=a.center.x,c=a.center.y,d=a.center.z,e=a.center.m,l=a.longAxis,g=a.shortAxis,f=a.numberOfPoints;a=a.map;var h,k,n,q=[],p=2*Math.PI/f;for(k=0;k<f;k++)h=Math.cos(k*p),n=Math.sin(k*p),h=a.toMap({x:l*h+b,y:g*n+c}),null!=d&&!h.hasZ&&(h.z=d),null!=e&&!h.hasM&&(h.m=e),q.push(h);q.push(q[0]);return new m({rings:[q],spatialReference:a.spatialReference})};
m.createCircle=function(a){return m.createEllipse({center:a.center,longAxis:a.r,shortAxis:a.r,numberOfPoints:a.numberOfPoints,map:a.map})};m.fromExtent=function(a){var b=a.clone().normalize();a=a.spatialReference;var c=!1,d=!1;s.map(b,function(a){a.hasZ&&(c=!0);a.hasM&&(d=!0)});b={rings:s.map(b,function(a){var b=[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]];if(c&&a.hasZ)for(var g=(a.zmax-a.zmin)/2,f=0;f<b.length;f++)b[f].push(g);if(d&&a.hasM){a=(a.mmax-a.mmin)/
2;for(f=0;f<b.length;f++)b[f].push(a)}return b}),spatialReference:a?a.toJSON():null};c&&(b.hasZ=!0);d&&(b.hasM=!0);return new m(b)};return m});