// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require dojo/_base/array dojo/_base/config dojo/_base/Deferred dojo/_base/lang dojo/_base/url dojo/request dojo/io-query dojo/when ./kernel ./config ./core/sniff ./core/lang ./core/urlUtils ./core/deferredUtils dojo/io/script dojo/io/iframe dojo/dom-construct".split(" "),function(V,w,B,O,p,x,C,Q,W,h,X,q,y,f,Y,Z,$,R){function J(a){a=new x(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function F(a,d,b){var l=!!a.useProxy,aa=a.method||"auto",k;k=a.crossOrigin;a=p.mixin({},a);a._ssl&&
(a.url=a.url.replace(/^http:/i,"https:"));var z=a.content,m=a.url,e=d&&a.form;k=y.isDefined(k)?k:g.useCors;a.load=function(a){var b;a&&(a.error?(b=p.mixin(Error(),a.error),b.log=B.isDebug):"error"===a.status&&(b=p.mixin(Error(),a),b.log=B.isDebug),b&&!y.isDefined(b.httpCode)&&(b.httpCode=b.code));return b||a};a.error=function(a,b){b&&b.xhr&&b.xhr.abort();a instanceof Error||(a=p.mixin(Error(),a));a.log=B.isDebug;return a};a._token&&(a.content=a.content||{},a.content.token=a._token);var r=0,n;z&&m&&
(n=Q.objectToQuery(z),r=n.length+m.length+1,q("esri-url-encodes-apostrophe")&&(r=n.replace(/'/g,"%27").length+m.length+1));a.timeout=y.isDefined(a.timeout)?a.timeout:g.timeout;a.handleAs=a.handleAs||"json";try{var s,t,A=k&&f.canUseXhr(a.urlObj)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),v=f.hasSameOrigin(a.urlObj,f.appUrl)||A,D="post"===aa||d||r>g.maxUrlLength?!0:!1,c=!v&&-1!==a.handleAs.indexOf("json")&&a.callbackParamName&&!d?!0:!1,E=f.getProxyRule(a.url)||g.forceProxy||l||(!c||
D)&&!v?!0:!1;d&&(!q("esri-file-upload")&&!E&&A)&&(E=!0);if(E)if(s=f.getProxyUrl(m,k),t=s.path,s._xo&&(A=!0),!D&&t.length+1+r>g.maxUrlLength&&(D=!0),a.url=t+"?"+m,D)a.content=p.mixin(s.query||{},z);else{var S=Q.objectToQuery(p.mixin(s.query||{},z));S&&(a.url+=(-1===m.indexOf("?")?"?":"\x26")+S);a.content=null}if(c&&!D)return!y.isDefined(a.isAsync)&&4>q("ff")&&(a.isAsync=!0),Z.get(u?u(a):a);var G=a.headers;if(!G||!G.hasOwnProperty("X-Requested-With"))G=a.headers=G||{},G["X-Requested-With"]=null;if(d){var K=
a.callbackParamName||"callback.html",T=a.callbackElementName||"textarea",H,L,I,M,x=e.elements?e.elements.length:0,P;if(z=a.content)for(H in z)if(I=z[H],y.isDefined(I)){L=null;for(M=0;M<x;M++)if(P=e.elements[M],P.name===H){L=P;break}L?L.value=I:b?e.append(H,I):e.appendChild(R.create("input",{type:"hidden",name:H,value:I}))}if(q("esri-file-upload"))w.forEach(e.elements,function(a){a.name===K&&e.removeChild(a)}),a.contentType=!1,a.postData=b?e:new FormData(e),delete a.form;else{e.enctype="multipart/form-data";
9>q("ie")&&(e.encoding="multipart/form-data");e.method="post";w.some(e.elements,function(a){return a.name===K})||e.appendChild(R.create("input",{type:"hidden",name:K,value:T}));if(-1!==m.toLowerCase().indexOf("addattachment")||-1!==m.toLowerCase().indexOf("updateattachment"))a.url=m+(-1===m.indexOf("?")?"?":"\x26")+K+"\x3d"+T,E&&(a.url=t+"?"+a.url);delete a.content}}if(A&&!a.hasOwnProperty("withCredentials"))if(b=E?t:m,-1!==w.indexOf(g.webTierAuthServers,J(b)))a.withCredentials=!0;else if(h.id){var F=
h.id.findServerInfo(b);F&&F.webTierAuth&&(a.withCredentials=!0)}a=u?u(a):a;if(D){a.data=a.content;if(d&&!q("esri-file-upload"))return $.send(a);!E&&q("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+ba++);return C.post(a.url,a)}a.query=a.content;return C.get(a.url,a)}catch(N){return d=new O,d.errback(a.error(N)),d}}function N(a){var d=g.corsStatus,b=f.canUseXhr(a,!0);-1<b&&g.corsEnabledServers.splice(b,1);d[J(a)]=1;return b}function U(a){var d=g.corsStatus;try{var b=
J(a.url);if(g.corsDetection&&g.useCors&&q("esri-cors")&&a.url&&-1!==a.url.toLowerCase().indexOf("/rest/services")&&!f.hasSameOrigin(a.urlObj,f.appUrl)&&!f.canUseXhr(a.urlObj)){if(d[b])return d[b];var l=new O;d[b]=l.promise;var h=a.url.substring(0,a.url.toLowerCase().indexOf("/rest/")+6)+"info";C.get(h,{query:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null},timeout:1E3*g.corsDetectionTimeout}).then(function(d){d?(f.canUseXhr(a.url)||g.corsEnabledServers.push(b),l.resolve()):l.reject()},
function(a){l.reject()});return l.promise}}catch(k){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}}function v(a,d,b,l){function f(a){a._pendingDfd=F(b,s,u);if(a._pendingDfd)a._pendingDfd.then(function(b){var c=null;a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;b.error?(c=p.mixin(Error(),b.error),c.log=B.isDebug):"error"===b.status&&(c=p.mixin(Error(),b),c.log=B.isDebug);c&&!y.isDefined(c.httpCode)&&(c.httpCode=c.code);if(c)throw c;a.callback({data:b,url:l.url,
requestOptions:l.requestOptions});a._pendingDfd=null}).then(null,function(c){var d,e,f;c&&(d=c.code,e=c.subcode,f=(f=c.messageCode)&&f.toUpperCase());if(c&&403==d&&(4==e||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!b._ssl){b._ssl=b._sslFromServer=!0;v(a,!0,b,l);return}}else if(c&&415==c.status){if(N(b.url),!b._err415){b._err415=1;v(a,!0,b,l);return}}else if(h.id&&-1!==w.indexOf(h.id._errorCodes,d)&&!h.id._isPublic(b.url)&&!n&&(403!=
d||-1===w.indexOf(ca,f)&&(!y.isDefined(e)||2==e&&b._token))){a._pendingDfd=h.id.getCredential(b.url,{token:b._token,error:c});a._pendingDfd.then(function(c){b._token=c.token;b._credential=c;b._ssl=b._sslFromServer||c.ssl;v(a,!0,b,l)}).then(null,function(b){a.errback(b);a._pendingDfd=null});return}a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;a.errback(c);a._pendingDfd=null});else{a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;var c=Error("Deferred object is missing");c.log=B.isDebug;a.errback(c);a._pendingDfd=
null}}var k=b.form,n=b.disableIdentityLookup,m=b._preLookup,e=!1;if(q("esri-workers")&&!1!==g.useWorkers)if(!0===b.useWorkers||!0===g.useWorkers)e=!0;else if(b.workerOptions){var r=b.workerOptions;if(r.callback||r.worker&&r.worker.worker instanceof Worker)e=!0}var u=k&&k.append,s=k&&(k.elements?w.some(k.elements,function(a){return"file"===a.type}):u),t=-1!==b.url.toLowerCase().indexOf("token\x3d")||b.content&&b.content.token||s&&w.some(k.elements,function(a){return"token"===a.name})?1:0;if(!d){a.then(function(a){/\/sharing\/rest\/accounts\/self/i.test(b.url)&&
(!t&&!b._token&&a.user&&a.user.username)&&g.webTierAuthServers.push(J(b.url));var c=b._credential;if(c){var d=h.id.findServerInfo(c.server);if(d=d&&d.owningSystemUrl)d=d.replace(/\/?$/,"/sharing"),(c=h.id.findCredential(d,c.userId))&&-1===h.id._getIdenticalSvcIdx(d,c)&&c.resources.splice(0,0,d)}return a}).always(function(a){delete b._credential;a&&(a.ssl=!!b._ssl)});var A=b.load,x=b.error;A&&a.then(function(b){var c=a._pendingDfd,c=c&&c.ioArgs;return A.call(c&&c.args,b,c)});x&&a.then(null,function(b){var c=
a._pendingDfd,c=c&&c.ioArgs;return x.call(c&&c.args,b,c)})}if(h.id&&!t&&!b._token&&!h.id._isPublic(b.url)&&(!n||m))if(d=h.id.findCredential(b.url))b._token=d.token,b._ssl=d.ssl;e?b.workerOptions&&b.workerOptions.worker?(C=b.workerOptions.worker,f(a)):V(["./workers/RequestClient"],function(d){if(b.workerOptions){var c=b.workerOptions;C=d.getClient(c.callback,c.cbFunction)}else C=d.getClient();f(a)}):f(a);return a.promise}function n(a,d){"string"!==typeof a&&console.error("esri/request: the first parameter should be a url string");
var b=p.mixin({},d),g={url:a,requestOptions:p.mixin({},d)};b.content=b.query;delete b.query;b.preventCache=!!b.cacheBust;delete b.cacheBust;b.handleAs=b.responseType;delete b.responseType;"array-buffer"===b.handleAs&&(b.handleAs="arraybuffer");b.url=f.fixUrl(a);"file"!==f.appUrl.scheme&&(b.url=f.getAbsoluteUrl(b.url));b.urlObj=new x(b.url);var h=new O(Y._dfdCanceller);W(U(b)).always(function(){v(h,!1,b,g)});return h.promise}var u,g=X.request,ca=["COM_0056","COM_0057"],ba=0;n._makeRequest=F;n._processRequest=
v;n._disableCors=N;n._detectCors=U;n.setRequestPreCallback=function(a){u=a};return n});