// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
require({cache:{"esri/geometry/support/castUtils":function(){define(["../Point","../Polyline","../Polygon","../Multipoint","../Extent"],function(s,t,p,a,h){return{cast:function(e){return!e||e.declaredClass?e||null:void 0!==e.x&&void 0!==e.y?new s(e):void 0!==e.paths?new t(e):void 0!==e.rings?new p(e):void 0!==e.points?new a(e):void 0!==e.xmin&&void 0!==e.ymin&&void 0!==e.xmax&&void 0!==e.ymax?new h(e):null}}})},"esri/webscene/Presentation":function(){define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/JSONSupporter ../core/collectionUtils ../core/accessoireSupport/typescript ./Slide".split(" "),
function(s,t,p,a,h,e,r,g){return function(f){function q(a){f.call(this,a);this.slides=null}p(q,f);q.prototype.getDefaults=function(){return{slides:[]}};q.prototype.clone=function(){return new q({slides:this.slides.map(function(a){return a.clone()})})};q.prototype.toJSON=function(){return{slides:this.slides.map(function(a){return a.toJSON()}).toArray()}};q.sanitizeJSON=function(a){return{slides:void 0!==a.slides&&Array.isArray(a.slides)?a.slides.map(function(a){return g.sanitizeJSON(a)}):[]}};a([r.shared("esri.webscene.Presentation")],
q.prototype,"declaredClass",void 0);a([r.property({reader:function(a){return a.map(function(a){return g.fromJSON(a)})},setter:e.referenceSetter})],q.prototype,"slides",void 0);return q=a([r.subclass()],q)}(h)})},"esri/webscene/Slide":function(){define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/JSONSupporter ../Viewpoint ../Basemap ../support/basemapUtils ../core/Collection ../core/collectionUtils ../core/promiseUtils ./Environment ./Lighting dojo/_base/lang ../views/3d/lib/glMatrix ../core/accessoireSupport/typescript".split(" "),
function(s,t,p,a,h,e,r,g,f,q,m,v,A,w,x,l){function u(a){return a.map(function(a){return{id:a.id}})}var B=0;s=function(n){function d(b){n.call(this,b);this.environment=this.visibleLayers=this.basemap=this.viewpoint=this.thumbnail=this.description=this.title=this.id=this._currentAnimation=null}p(d,n);d.prototype.getDefaults=function(){return{id:Date.now().toString(16)+"-slide-"+B++,thumbnail:{},title:{},description:{},viewpoint:new e,environment:new v,visibleLayers:[]}};d.prototype.clone=function(){return new d({id:this.id,
title:this.title.clone(),thumbnail:this.thumbnail.clone(),description:this.description&&this.description.clone()||null,viewpoint:this.viewpoint&&this.viewpoint.clone()||null,basemap:this.basemap&&this.basemap.clone()||null,visibleLayers:u(this.visibleLayers),environment:this.environment&&this.environment.clone()||null})};d.prototype.toJSON=function(){var b={id:this.id,title:this.title.toJSON(),thumbnail:this.thumbnail.toJSON(),viewpoint:this.viewpoint.toJSON(),baseMap:this.basemap.toJSON(),visibleLayers:u(this.visibleLayers).toArray(),
environment:this.environment.toJSON()};null!=this.description&&this.description.text&&(b.description=this.description.toJSON());return b};d.prototype._updateVisibleLayersFrom=function(b){var c=this,k=[];return m.eachAlways(this._allLayers(b.map).map(function(c){return b.whenLayerView(c).then(function(b){b.visible&&k.push({id:b.layer.id})})}).toArray()).then(function(){c.visibleLayers.removeAll();c.visibleLayers.addMany(k)})};d.prototype.updateFrom=function(b,c){var k=this;c=w.mixin({screenshot:w.mixin({format:"jpeg",
quality:80,width:120,height:75},c&&c.screenshot)},c);return this._updateVisibleLayersFrom(b).then(function(){k.viewpoint=b.viewpoint.clone();k.environment.lighting=A.prototype.clone.apply(b.environment.lighting);k.basemap=b.map.basemap&&b.map.basemap.clone()||null;return b.takeScreenshot(c.screenshot)}).then(function(b){k.thumbnail=new z({url:b.dataURL});return k})};d.prototype.applyTo=function(b,c){var k=this,a=w.mixin({animate:!0},c);return this._applyBasemap(b).then(function(){return k._applyLayerVisibility(b)}).then(function(){return k._applyViewpoint(b,
a)}).then(function(){return k})};d.prototype._applyBasemap=function(b){var c=this;return this.basemap?this.basemap.load().always(function(){b.map.basemap=g.clonePreservingTiledLayers(c.basemap,b.map.basemap)}):m.resolve()};d.prototype._allLayers=function(b){var c=new f;this._collectLayers(b,c);this._collectLayers(b.ground,c);return c};d.prototype._collectLayers=function(b,c){var k=this;b.layers.forEach(function(b){c.add(b);b.layers&&k._collectLayers(b,c)})};d.prototype._applyLayerVisibility=function(b){var c=
this;if(this.visibleLayers)return m.eachAlways(this._allLayers(b.map).map(function(k){return b.whenLayerView(k).then(function(b){b.visible=c.visibleLayers.some(function(k){return k.id===b.layer.id})})}).toArray())};d.prototype._applyViewpoint=function(b,c){this.viewpoint.camera.fov=b.camera.fov;if(c.animate){if(this.get("environment.lighting.date"))return this._animateToLighting(b).then(function(){});b.environment.lighting=this.environment.lighting.clone();return b.goTo(this.viewpoint).then(function(){})}b.viewpoint=
this.viewpoint;b.environment.lighting=this.environment.lighting.clone();return m.resolve()};d.prototype._animateToLighting=function(b){var c=this,k;"global"===b.viewingMode&&(k=this._animateLightingWithCamera(b));this._currentAnimation&&(this._currentAnimation.stop(),this._currentAnimation=null);b.environment.lighting.cameraTrackingEnabled=!1;b.environment.lighting.directShadowsEnabled=this.environment.lighting.directShadowsEnabled;b.environment.lighting.ambientOcclusionEnabled=this.environment.lighting.ambientOcclusionEnabled;
null!=this.environment.lighting.displayUTCOffset&&(b.environment.lighting.displayUTCOffset=this.environment.lighting.displayUTCOffset);this._currentAnimation=b.goTo(this.viewpoint);this._currentAnimation.then(function(a){k&&k.remove();c._currentAnimation===a&&(b.environment.lighting.cameraTrackingEnabled=!0);"finished"===a.state&&(b.environment.lighting=c.environment.lighting.clone())});return this._currentAnimation};d.prototype._getTime=function(b){var c=b.getTime();b=3600*b.getUTCHours()+60*b.getUTCMinutes()+
b.getUTCSeconds();return[c,b]};d.prototype._setTime=function(b,c,k){b.setTime(c);b.setUTCHours(k/3600);b.setUTCMinutes(k%3600/60);b.setUTCSeconds(k%3600%60);return b};d.prototype._animateLightingWithCamera=function(b){var c=this,k=x.vec3d,a=this._getTime(new Date(b.environment.lighting.date.toString())),d=a[0],f=a[1],a=this._getTime(this.environment.lighting.date),e=a[0],q=a[1],g=b.renderCoordsHelper,n=[0,0,0];g.toRenderCoords(b.camera.position,n);var l=[0,0,0];g.toRenderCoords(this.viewpoint.camera.position,
l);var m=[0,0,0],p=new Date;return b.watch("camera",function(a){g.toRenderCoords(a.position,m);a=k.dist2(n,m);var D=k.dist2(l,m),h=0;0!==a+D&&(h=a/(a+D));b.environment.lighting.date=c._setTime(p,d+(e-d)*h,f+(q-f)*h)})};d.createFrom=function(b,a){return(new d).updateFrom(b,a)};d.sanitizeJSON=function(b){var a;a=void 0!==b.visibleLayers&&Array.isArray(b.visibleLayers)?u(b.visibleLayers):[];a={id:b.id||"",title:b.title||{text:""},thumbnail:b.thumbnail||{url:""},viewpoint:b.viewpoint,baseMap:b.baseMap,
visibleLayers:a};void 0!==b.description&&(a.description=b.description);void 0!==b.environment&&(a.environment=v.sanitizeJSON(b.environment));return a};a([l.shared("esri.webscene.Slide")],d.prototype,"declaredClass",void 0);a([l.shared({reader:{exclude:["baseMap"],add:["basemap"]}})],d.prototype,"classMetadata",void 0);a([l.property({value:""})],d.prototype,"id",void 0);a([l.property({type:C})],d.prototype,"title",void 0);a([l.property({type:y})],d.prototype,"description",void 0);a([l.property({type:z})],
d.prototype,"thumbnail",void 0);a([l.property({type:e})],d.prototype,"viewpoint",void 0);a([l.property({reader:function(b,a){return!a.baseMap||0===a.baseMap.baseMapLayers.length?null:r.fromJSON(a.baseMap)},setter:function(b){return g.ensureType(b)}})],d.prototype,"basemap",void 0);a([l.property({reader:function(b){return b.map(function(b){return{id:b.id}})},setter:q.referenceSetter})],d.prototype,"visibleLayers",void 0);a([l.property({type:v})],d.prototype,"environment",void 0);return d=a([l.subclass()],
d)}(h);var z=function(f){function d(){f.apply(this,arguments)}p(d,f);d.prototype.toJSON=function(){return{url:this.url}};d.prototype.clone=function(){return new d({url:this.url})};a([l.property({value:""})],d.prototype,"url",void 0);return d=a([l.subclass()],d)}(h),C=function(f){function d(){f.apply(this,arguments)}p(d,f);d.prototype.toJSON=function(){return{text:this.text}};d.prototype.clone=function(){return new d({text:this.text})};a([l.property({value:""})],d.prototype,"text",void 0);return d=
a([l.subclass()],d)}(h),y=function(f){function d(){f.apply(this,arguments)}p(d,f);d.prototype.toJSON=function(){return{text:this.text}};d.prototype.clone=function(){return new d({text:this.text})};a([l.property({value:""})],d.prototype,"text",void 0);return d=a([l.subclass()],d)}(h);return s})},"esri/webscene/Environment":function(){define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/JSONSupporter ../core/accessoireSupport/typescript ./Lighting".split(" "),
function(s,t,p,a,h,e,r){return function(g){function f(a){g.call(this,a);this.lighting=null}p(f,g);f.prototype.getDefaults=function(){return{lighting:{}}};f.prototype.clone=function(){return new f({lighting:this.lighting.clone()})};f.prototype.toJSON=function(){return{lighting:this.lighting.toJSON()}};f.sanitizeJSON=function(a){return{lighting:a.lighting?r.sanitizeJSON(a.lighting):(new r).toJSON()}};a([e.shared("esri.webscene.Environment")],f.prototype,"declaredClass",void 0);a([e.property({type:r})],
f.prototype,"lighting",void 0);return f=a([e.subclass()],f)}(h)})},"esri/webscene/Lighting":function(){define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../core/JSONSupporter ../core/accessoireSupport/typescript".split(" "),function(s,t,p,a,h,e){return function(h){function g(a){h.call(this,a);this.displayUTCOffset=this.ambientOcclusionEnabled=this.directShadowsEnabled=this.date=null}p(g,h);g.prototype.clone=function(){return new g({date:null!=this.date?new Date(this.date.getTime()):
null,directShadowsEnabled:this.directShadowsEnabled,ambientOcclusionEnabled:this.ambientOcclusionEnabled,displayUTCOffset:null!=this.displayUTCOffset?this.displayUTCOffset:null})};g.prototype.toJSON=function(){var a={},e=this.date?this.date.getTime():null;14264208E5!==e&&(a.datetime=e);this.directShadowsEnabled&&(a.directShadows=!0);this.ambientOcclusionEnabled&&(a.ambientOcclusion=!0);null!=this.displayUTCOffset&&(a.displayUTCOffset=this.displayUTCOffset);return a};g.sanitizeJSON=function(a){var e=
{datetime:a.datetime};void 0!==a.directShadows&&(e.directShadows=!!a.directShadows);void 0!==a.ambientOcclusion&&(e.ambientOcclusion=!!a.ambientOcclusion);void 0!==a.displayUTCOffset&&(e.displayUTCOffset=a.displayUTCOffset);return e};a([e.shared("esri.webscene.Lighting")],g.prototype,"declaredClass",void 0);a([e.shared({reader:{exclude:["datetime","ambientOcclusion","directShadows"],add:["date","ambientOcclusionEnabled","directShadowsEnabled"]}})],g.prototype,"classMetadata",void 0);a([e.property({type:Date,
value:null,reader:function(a,e){return null!=e.datetime&&new Date(e.datetime)||null}})],g.prototype,"date",void 0);a([e.property({value:!1,reader:function(a,e){return!!e.directShadows}})],g.prototype,"directShadowsEnabled",void 0);a([e.property({value:!1,reader:function(a,e){return!!e.ambientOcclusion}})],g.prototype,"ambientOcclusionEnabled",void 0);a([e.property({value:null})],g.prototype,"displayUTCOffset",void 0);return g=a([e.subclass()],g)}(h)})},"esri/webscene/InitialViewProperties":function(){define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../Viewpoint ../core/Accessoire ../geometry/SpatialReference ./Environment ../core/accessoireSupport/typescript".split(" "),
function(s,t,p,a,h,e,r,g,f){return function(e){function m(a){e.call(this,a);this.viewpoint=this.viewingMode=this.spatialReference=this.environment=null}p(m,e);m.prototype.getDefaults=function(){return{environment:{}}};m.prototype.clone=function(){return new m({environment:this.environment.clone(),spatialReference:this.spatialReference?this.spatialReference.clone():null,viewingMode:this.viewingMode,viewpoint:this.viewpoint?this.viewpoint.clone():null})};a([f.shared("esri.webscene.InitialViewProperties")],
m.prototype,"declaredClass",void 0);a([f.property({type:g})],m.prototype,"environment",void 0);a([f.property({value:null,type:r})],m.prototype,"spatialReference",void 0);a([f.property({value:null,setter:function(a){if(!("local"!==a&&"global"!==a))return a}})],m.prototype,"viewingMode",void 0);a([f.property({value:null,type:h})],m.prototype,"viewpoint",void 0);return m=a([f.subclass()],m)}(e)})},"*noref":1}});
define("require exports ./core/tsSupport/extendsHelper ./core/tsSupport/decorateHelper ./Map ./core/Error ./core/requireUtils ./core/promiseUtils ./core/JSONSupporter ./core/LoadableAccessoire ./Basemap ./Viewpoint ./geometry/support/jsonUtils ./geometry/support/castUtils ./geometry/SpatialReference ./webscene/Presentation ./webscene/InitialViewProperties ./webscene/Environment ./portal/PortalItem ./portal/Portal dojo/_base/lang ./core/accessoireSupport/typescript".split(" "),function(s,t,p,a,h,e,
r,g,f,q,m,v,A,w,x,l,u,B,z,C,y,n){t=function(b){function c(a){b.call(this);this.resourceInfo=this.portalItem=this.initialViewProperties=this.presentation=this.authoringAppVersion=this.authoringApp=this.version=this.clippingEnabled=this.clippingArea=this.basemap=null}p(c,b);c.prototype.initialize=function(){if(this.resourceInfo){var a=void 0;try{a=this._validateJSON(this.resourceInfo)}catch(b){this.addResolvingPromise(g.reject(b));return}this.read(a)}};c.prototype.getDefaults=function(a){return y.mixin(this.inherited(arguments),
{presentation:{},initialViewProperties:{},version:{major:1,minor:3}})};c.prototype.load=function(){this.addResolvingPromise(this._loadFromSource());return this};c.prototype.toJSON=function(){var a={};this.initialViewProperties&&this.initialViewProperties.environment&&(a.environment=this.initialViewProperties.environment.toJSON());this.initialViewProperties&&this.initialViewProperties.viewpoint&&(a.viewpoint=this.initialViewProperties.viewpoint.toJSON());var b={version:this.version.major+"."+this.version.minor,
baseMap:this.basemap.toJSON(),operationalLayers:[],presentation:this.presentation.toJSON(),viewingMode:this.initialViewProperties?this.initialViewProperties.viewingMode:"global"};b.spatialReference=this.initialViewProperties&&this.initialViewProperties.spatialReference?this.initialViewProperties.spatialReference.toJSON():x.WebMercator.toJSON();0!==Object.keys(a).length&&(b.initialState=a);null!=this.authoringApp&&(b.authoringApp=this.authoringApp);null!=this.authoringAppVersion&&(b.authoringAppVersion=
this.authoringAppVersion);null!=this.clippingArea&&(b.clippingArea={geometry:this.clippingArea.toJSON(),clip:!!this.clippingEnabled});return b};c.prototype.read=function(a){this.inherited(arguments);if(a.baseMap&&Array.isArray(a.baseMap.elevationLayers)){var b=a.baseMap.elevationLayers.map(function(a){return{id:a.id}});this.presentation.slides.forEach(function(a){a.visibleLayers.addMany(b)})}return this};c.prototype._loadFromSource=function(){return this.resourceInfo?this._loadFromJSON(this.resourceInfo):
this.portalItem&&this.portalItem.id?this._loadFromItem(this.portalItem):g.resolve(null)};c.prototype._readAndLoadFromJSON=function(a){a=this._validateJSON(a);this.read(a);return this._loadFromJSON(a)};c.prototype._loadFromJSON=function(a){var b=this,c=d.layerCreatorParams();this.portalItem&&(c.portal=this.portalItem.portal||C.getDefault());return r.when(s,"./portal/creators/layersCreator").then(function(d){var e=[],f=a.operationalLayers,h=[];a.baseMap&&Array.isArray(a.baseMap.elevationLayers)&&h.push.apply(h,
a.baseMap.elevationLayers);var l=function(a){a.layers&&(a.layers=a.layers.filter(l));return"ArcGISTiledElevationServiceLayer"===a.layerType?(h.push(a),!1):!0};f&&(f=f.filter(l));if(0<h.length){var m=y.mixin({},c);m.defaultLayerType="ArcGISTiledElevationServiceLayer";e.push.apply(e,d.populateOperationalLayers(b.ground.layers,h,m))}f&&0<f.length&&e.push.apply(e,d.populateOperationalLayers(b.layers,f,c));return g.eachAlways(e).then(function(){})})};c.prototype._loadFromItem=function(a){var b=this;return a.load().then(function(a){return a.fetchData()}).then(function(a){b.resourceInfo=
a;return b._readAndLoadFromJSON(a)})};c.prototype._validateVersion=function(a){var b=a.split("."),c=b[0],b=b[1],d=/^\s*\d+\s*$/;if(!c||!c.match||!c.match(d))throw new e("webscene:invalid-version","Expected major version to be a number, but got '"+a+"'",{version:a});if(!b||!b.match||!b.match(d))throw new e("webscene:invalid-version","Expected minor version to be a number, but got '"+a+"'",{version:a});c=parseInt(c,10);b=parseInt(b,10);if(1!==c)throw new e("webscene:unsupported-version","Required major webscene version is '1', but got '"+
a+"'",{version:a});return{major:c,minor:b}};c.prototype._validateJSON=function(a){a=this._sanitizeJSON(a);var b=this._validateVersion(a.version);a.version=b.major+"."+b.minor;1===b.major&&2>=b.minor&&delete a.spatialReference;return a};c.prototype._sanitizeJSON=function(a){return{version:a.version||"0.0",baseMap:a.baseMap,operationalLayers:a.operationalLayers,authoringApp:a.authoringApp||"",authoringAppVersion:a.authoringAppVersion||"",viewingMode:a.viewingMode||"",presentation:a.presentation&&l.sanitizeJSON(a.presentation)||
{},initialState:a.initialState,spatialReference:a.spatialReference||x.WebMercator.toJSON(),clippingArea:a.clippingArea}};c.fromJSON=function(a){return new c({resourceInfo:a})};a([n.shared("esri.WebScene")],c.prototype,"declaredClass",void 0);a([n.shared({reader:{exclude:["baseMap","operationalLayers","spatialReference","initialState","viewingMode"],add:["basemap","clippingEnabled","initialViewProperties"]}})],c.prototype,"classMetadata",void 0);a([n.property({reader:function(a,b){if(!b.baseMap||!Array.isArray(b.baseMap.baseMapLayers)||
0===b.baseMap.baseMapLayers.length)return null;var c=y.mixin({},b.baseMap);delete c.elevationLayers;return m.fromJSON(c)}})],c.prototype,"basemap",void 0);a([n.property({reader:function(a){return a&&a.geometry?A.fromJSON(a.geometry):null},setter:function(a){return w.cast(a)}})],c.prototype,"clippingArea",void 0);a([n.property({value:!1,reader:function(a,b){if(b&&b.clippingArea)return!!b.clippingArea.clip}})],c.prototype,"clippingEnabled",void 0);a([n.property({readOnly:!0,reader:function(a){a=a.split(".");
var b=a[1];return{major:parseInt(a[0],10),minor:parseInt(b,10)}}})],c.prototype,"version",void 0);a([n.property()],c.prototype,"authoringApp",void 0);a([n.property()],c.prototype,"authoringAppVersion",void 0);a([n.property({type:l})],c.prototype,"presentation",void 0);a([n.property({type:u,reader:function(a,b){var c={};b.initialState&&b.initialState.environment&&(c.environment=B.fromJSON(b.initialState.environment));b.spatialReference&&(c.spatialReference=x.fromJSON(b.spatialReference));b.viewingMode&&
(c.viewingMode=b.viewingMode);b.initialState&&b.initialState.viewpoint&&(c.viewpoint=v.fromJSON(b.initialState.viewpoint));return new u(c)}})],c.prototype,"initialViewProperties",void 0);a([n.property({type:z})],c.prototype,"portalItem",void 0);a([n.property()],c.prototype,"resourceInfo",void 0);return c=a([n.subclass([q,f])],c)}(h);var d=function(){function a(){}a.propertyFilter=function(c,d){var e=d;switch(c.layerType){case "ArcGISFeatureLayer":e=a._featureLayerPropertyFilter(c,d)}return e};a.layerCreatorParams=
function(){return{propertyFilter:a.propertyFilter}};a._featureLayerPropertyFilter=function(a,b){b.mode=0;b.returnZ=!0;b.outFields=["*"];return b};return a}();return t});