// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../core/Accessoire ../core/ArrayPool ../core/HandleRegistry ../core/Scheduler ../core/watchUtils dojo/_base/lang dojo/dom-class".split(" "),function(m,h,n,p,q,l,f){var d={widthBreakpoint:{getValue:function(a){var c=a.viewSize[0];a=a.breakpoints;var b=this.values;return c<=a.xsmall?b.xsmall:c<=a.small?b.small:c<=a.medium?b.medium:c<=a.large?b.large:b.xlarge},values:{xsmall:"xsmall",small:"small",medium:"medium",large:"large",xlarge:"xlarge"},valueToClassName:{xsmall:"esri-view-width-xsmall esri-view-width-less-than-small esri-view-width-less-than-medium esri-view-width-less-than-large esri-view-width-less-than-xlarge",
small:"esri-view-width-small esri-view-width-greater-than-xsmall esri-view-width-less-than-medium esri-view-width-less-than-large esri-view-width-less-than-xlarge",medium:"esri-view-width-medium esri-view-width-greater-than-xsmall esri-view-width-greater-than-small esri-view-width-less-than-large esri-view-width-less-than-xlarge",large:"esri-view-width-large esri-view-width-greater-than-xsmall esri-view-width-greater-than-small esri-view-width-greater-than-medium esri-view-width-less-than-xlarge",
xlarge:"esri-view-width-xlarge esri-view-width-greater-than-xsmall esri-view-width-greater-than-small esri-view-width-greater-than-medium esri-view-width-greater-than-large"}},heightBreakpoint:{getValue:function(a){var c=a.viewSize[1];a=a.breakpoints;var b=this.values;return c<=a.xsmall?b.xsmall:c<=a.small?b.small:c<=a.medium?b.medium:c<=a.large?b.large:b.xlarge},values:{xsmall:"xsmall",small:"small",medium:"medium",large:"large",xlarge:"xlarge"},valueToClassName:{xsmall:"esri-view-height-xsmall esri-view-height-less-than-small esri-view-height-less-than-medium esri-view-height-less-than-large esri-view-height-less-than-xlarge",
small:"esri-view-height-small esri-view-height-greater-than-xsmall esri-view-height-less-than-medium esri-view-height-less-than-large esri-view-height-less-than-xlarge",medium:"esri-view-height-medium esri-view-height-greater-than-xsmall esri-view-height-greater-than-small esri-view-height-less-than-large esri-view-height-less-than-xlarge",large:"esri-view-height-large esri-view-height-greater-than-xsmall esri-view-height-greater-than-small esri-view-height-greater-than-medium esri-view-height-less-than-xlarge",
xlarge:"esri-view-height-xlarge esri-view-height-greater-than-xsmall esri-view-height-greater-than-small esri-view-height-greater-than-medium esri-view-height-greater-than-large"}},orientation:{getValue:function(a){a=a.viewSize;var c=this.values;return a[1]>=a[0]?c.portrait:c.landscape},values:{portrait:"portrait",landscape:"landscape"},valueToClassName:{portrait:"esri-view-orientation-portrait",landscape:"esri-view-orientation-landscape"}}},e={xsmall:544,small:768,medium:992,large:1200};return m.createSubclass({classMetadata:{properties:{breakpoints:{},
orientation:{},widthBreakpoint:{},heightBreakpoint:{}}},constructor:function(){this._handles=new n},getDefaults:function(){return l.mixin(this.inherited(arguments),{breakpoints:e})},initialize:function(){this._handles.add(q.init(this,"size",this._updateClassNames))},destroy:function(){this._removeActiveClassNames();this._handles.destroy();this.view=this._handles=null},_breakpointsSetter:function(a,c){if(a===c)return a;var b;b=(b=a)&&b.xsmall<b.small&&b.small<b.medium&&b.medium<b.large;var d;b||(d=
JSON.stringify(e,null,2),console.warn("provided breakpoints are not valid, using defaults:"+d));a=b?a:e;return l.mixin({},a)},_updateClassNames:function(){if(this.container){var a=h.acquire(),c=h.acquire(),b=!1,f=this._handles,g,e,k;for(g in d)e=this[g],k=d[g].getValue({viewSize:this.size,breakpoints:this.breakpoints}),e!==k&&(b=!0,this[g]=k,c.push(d[g].valueToClassName[e]),a.push(d[g].valueToClassName[k]));b&&f.add(p.addFrameTask({update:function(){f.remove("breakpointsOwner-css-update");this._applyClassNameChanges(a,
c);h.release(a);h.release(c)}.bind(this)}),"breakpointsOwner-css-update")}},_applyClassNameChanges:function(a,c){var b=this.container;b&&(f.remove(b,c),f.add(b,a))},_removeActiveClassNames:function(){var a=this.container,c;if(a)for(c in d)f.remove(a,d[c].valueToClassName[this[c]])}})});