// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../core/Accessor ../core/Collection ../core/Error ../core/HandleRegistry ../core/Scheduler ../core/promiseUtils ../core/watchUtils ./LayerViewFactory".split(" "),function(k,l,f,m,n,g,p,q){var h=function(a,b){var c=function(d){d&&d.forEach(function(d){b.push(d);c(d[a])});return b};return c};return k.createSubclass({constructor:function(){this._handles=new m;this._layerViewPromises={};this._layerViewBylayerUID={};this._doWork=this._doWork.bind(this);this.refresh=this.refresh.bind(this);this.factory=
new q;this._handles.add(p.init(this,"view.ready",function(a){this.ready=a}.bind(this)));this._handles.add(this.watch(["view.map.basemap","view.map.ground","view.map.layers","ready"],this.refresh),"watcher")},destroy:function(){this.view=null;this.empty();this.factory.destroy();this.factory=null;this._handles.destroy();this._map=this._layerViewBylayerUID=this._layerViewPromises=this._handles=null},_map:null,properties:{allLayerViews:{type:l},ready:{value:!1},view:null},layersToLayerViews:{"view.map.basemap.baseLayers":"view.basemapView.baseLayerViews",
"view.map.ground.layers":"view.groundView.layerViews","view.map.layers":"view.layerViews","view.map.basemap.referenceLayers":"view.basemapView.referenceLayerViews"},empty:function(){Object.keys(this._layerViewBylayerUID).forEach(this._disposeLayerView,this);Object.keys(this._layerViewPromises).forEach(function(a){this._layerViewPromises[a].cancel()},this);this._layerViewBylayerUID={};this._layerViewPromises={};this._refreshCollections()},refresh:function(){var a=this._handles;a.remove("refresh");
a.add(n.schedule(this._doWork),"refresh")},getAllLayerCollections:function(){return Object.keys(this.layersToLayerViews).map(this.get,this).filter(function(a){return null!=a})},getAllLayers:function(){var a=[];this.getAllLayerCollections().forEach(h("layers",a));return a},getAllLayerViewsCollections:function(){return Object.keys(this.layersToLayerViews).map(function(a){return this.layersToLayerViews[a]},this).map(this.get,this).filter(function(a){return null!=a})},getAllLayerViews:function(){var a=
[];this.getAllLayerViewsCollections().forEach(h("layerViews",a));return a},whenLayerView:function(a){this.refresh();this._doWork();return!this._layerViewPromises[a.uid]?g.reject(f("view:no-layerview-for-layer","No layerview has been found for the layer",{layer:a})):this._layerViewPromises[a.uid]},_doWork:function(){var a=this._handles,b=this.get("view.map");this._map!==b&&(this.empty(),this._map=b);if(a.has("refresh")){a.remove("refresh");a.remove("collection-change");this.factory.paused=!this.ready;
var b=this.getAllLayers(),c=b.map(function(a){return a.uid});b.forEach(this._createLayerView,this);this._refreshCollections();Object.keys(this._layerViewPromises).filter(function(a){return-1===c.indexOf(a)}).forEach(this._disposeLayerView,this);a.add(this.getAllLayerCollections().map(function(a){return a.on("change",this.refresh)},this),"collection-change")}},_refreshCollections:function(){Object.keys(this.layersToLayerViews).forEach(function(a){this._populateLayerViewsOwners(this.get(a),this.get(this.layersToLayerViews[a]),
this.view)},this);var a=this.getAllLayers();this.allLayerViews.removeAll();this.allLayerViews.addMany(a.map(function(a){return this._layerViewBylayerUID[a.uid]},this).filter(function(a){return null!=a}))},_populateLayerViewsOwners:function(a,b,c){a&&b&&(b.removeAll(),a.forEach(function(a){var e=this._layerViewBylayerUID[a.uid];e&&(e.layer=a,e.parent=c,b.push(e),a.layers&&this._populateLayerViewsOwners(a.layers,e.layerViews,e))},this))},_createLayerView:function(a){var b=this.view,c=this.factory,d=
this._layerViewBylayerUID,e=this._layerViewPromises;d[a.uid]?a.load():e[a.uid]||(e[a.uid]=c.create(b,a).then(function(c){if(!this.getAllLayers().some(function(b){return a===b}))throw f("view:no-layerview-for-layer","The layer has been removed from the map",{layer:a});d[a.uid]=c;this._refreshCollections();a.emit("layerview-create",{view:b,layerView:c});b.emit("layerview-create",{layer:a,layerView:c});return g.resolve(c)}.bind(this)),e[a.uid].always(this.refresh))},_disposeLayerView:function(a){if(this._layerViewPromises[a]){this._layerViewPromises[a].cancel();
delete this._layerViewPromises[a];var b=this._layerViewBylayerUID[a];if(b){var c=b.layer,d=b.view;this.factory.dispose(b);b.layer=b.parent=b.view=null;delete this._layerViewBylayerUID[a];c.emit("layerview-destroy",{view:d,layerView:b});d.emit("layerview-destroy",{layer:c,layerView:b})}}}})});