// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("require ../core/declare ../core/promiseUtils dojo/_base/array dojo/on dojo/Deferred dojo/promise/all ../layers/support/layerUtils ../geometry/support/scaleUtils ../geometry/Extent ../tasks/support/Query ../layers/GroupLayer ../core/Accessoire".split(" "),function(G,H,u,k,C,v,D,E,w,I,J,K,L){var r;return H(L,{declaredClass:"esri.views.PopupManager",classMetadata:{properties:{map:{dependsOn:["view.map"],readOnly:!0}}},constructor:function(){this._featureLayersCache={}},destroy:function(){this._featureLayersCache=
{};this.view=null},_clickHandle:null,_featureLayersCache:null,enabled:!1,_enabledSetter:function(a){this._clickHandle&&(a?this._clickHandle.resume():this._clickHandle.pause());return a},_mapGetter:function(){return this.get("view.map")||null},view:null,_viewSetter:function(a){this._clickHandle&&(this._clickHandle.remove(),this._clickHandle=null);a&&(this._clickHandle=C.pausable(a,"click",this._clickHandler.bind(this)),this.enabled||this._clickHandle.pause());return a},getMapLayer:function(a){var d;
if(a&&(d=a.findLayerById()))if(a=d.id,this._featureLayersCache[a]){var c=a.lastIndexOf("_");-1<c&&(a=a.substring(0,c),d=this.map.findLayerById(a))}return d},_showPopup:function(a){function d(){t.clear();t.close()}function c(a){if(null==a)return!1;var c=e.allLayerViews.find(function(c){return c.layer===a});return null==c?!1:a.loaded&&!c.suspended&&(a.popupEnabled&&a.popupTemplate||"esri.layers.GraphicsLayer"===a.declaredClass)}var e=this.view,t=e.popup,r=this,n=[];k.forEach(this.map.layers.toArray(),
function(a){a.isInstanceOf(K)?k.forEach(a.layers.toArray(),function(a){c(a)&&(!a.elevationInfo||"on-the-ground"===a.elevationInfo.mode)&&n.push(a)}):c(a)&&(!a.elevationInfo||"on-the-ground"===a.elevationInfo.mode)&&n.push(a)});0<e.graphics.length&&n.push(e.graphics);var l=null;if(a.graphic&&(a.graphic.popupTemplate||c(a.graphic.layer)))l=a.graphic;if(!n.length&&!l)d();else{var f=[],m=!!l;if(l)if(l.layer&&"esri.layers.SceneLayer"===l.layer.declaredClass){var b=e.whenLayerView(l.layer).then(function(a){return a.whenGraphicAttributes(l,
["*"])});f.unshift(D([b]))}else b=new v,f.unshift(b.resolve([l]));else{var h=r._calculateClickTolerance(n),f=a.mapPoint;if(!f){d();return}var q=1;e.state&&(q=e.state.resolution);(b=e.basemapTerrain)&&b.overlayManager&&(q=b.overlayManager.overlayPixelSizeInMapUnits(f));h*=q;b&&!b.spatialReference.equals(e.spatialReference)&&(h*=w.getUnitValueForSR(b.spatialReference)/w.getUnitValueForSR(e.spatialReference));var b=f.clone().offset(-h,-h),f=f.clone().offset(h,h),y=new I(Math.min(b.x,f.x),Math.min(b.y,
f.y),Math.max(b.x,f.x),Math.max(b.y,f.y),e.spatialReference),f=k.map(n,function(c){var b;if("esri.layers.ImageryLayer"===c.declaredClass){var d=new J;d.geometry=a.mapPoint;b=e.allLayerViews.find(function(a){return a.layer===c});var f={rasterAttributeTableFieldPrefix:"Raster.",returnDomainValues:!0};f.layerView=b;b=c.queryVisibleRasters(d,f).then(function(a){m=m||0<a.length;return a})}else if("esri.layers.SceneLayer"===c.declaredClass)b=u.resolve();else if(r._featureLayersCache[c.id]||"function"===
typeof c.queryFeatures&&(0===c.mode||1===c.mode))b=c.createQueryParameters(),b.geometry=y,b=c.queryFeatures(b).then(function(a){a=a.features;m=m||0<a.length;return a});else{d=[];if("esri.core.Collection\x3cesri.Graphic\x3e"===c.declaredClass)f=c;else if((b=e.allLayerViews.find(function(a){return a.layer===c}))&&(b.loadedGraphics||b._graphicsCollection))f=b.loadedGraphics||b._graphicsCollection;f&&(d=f.filter(function(a){return a&&a.popupTemplate&&a.visible&&y.intersects(a.geometry)}).toArray());m=
m||0<d.length;b=u.resolve(d)}return b})}!k.some(f,function(a){return!a.isFulfilled()})&&!m?d():t.open({promises:f,location:a.mapPoint})}},_getSubLayerFeatureLayers:function(a,d){var c=d||new v,e=[],t=a.length,u=Math.floor(this.view.extent.width/this.view.width),n=this.view.scale,l=!1,f=this,m=0;a:for(;m<t;m++){var b=a[m],h=b.dynamicLayerInfos||b.layerInfos;if(h){var q=null;if(b._params&&(b._params.layers||b._params.dynamicLayers))q=b.visibleLayers;for(var q=E._getVisibleLayers(h,q),y=E._getLayersForScale(n,
h),w=h.length,z=0;z<w;z++){var x=h[z],p=x.id,s=b.popupTemplates[p];if(!x.subLayerIds&&s&&s.popupTemplate&&-1<k.indexOf(q,p)&&-1<k.indexOf(y,p)){if(!r){l=!0;break a}var A=b.id+"_"+p,g=this._featureLayersCache[A];if(!g||!g.loadError)g||((g=s.layerUrl)||(g=x.source?this._getLayerUrl(b.url,"/dynamicLayer"):this._getLayerUrl(b.url,p)),g=new r(g,{id:A,drawMode:!1,mode:r.MODE_SELECTION,outFields:this._getOutFields(s.popupTemplate),resourceInfo:s.resourceInfo,source:x.source}),this._featureLayersCache[A]=
g),g.setDefinitionExpression(b.layerDefinitions&&b.layerDefinitions[p]),g.setGDBVersion(b.gdbVersion),g.popupTemplate=s.popupTemplate,g.setMaxAllowableOffset(u),g.setUseMapTime(!!b.useMapTime),b.layerDrawingOptions&&(b.layerDrawingOptions[p]&&b.layerDrawingOptions[p].renderer)&&g.setRenderer(b.layerDrawingOptions[p].renderer),e.push(g)}}}}if(l){var F=new v;G(["../layers/FeatureLayer"],function(a){r=a;F.resolve()});F.then(function(){f._getSubLayerFeatureLayers(a,c)})}else{var B=[];k.forEach(e,function(a){if(!a.loaded){var c=
new v;C.once(a,"load, error",function(){c.resolve()});B.push(c.promise)}});B.length?D(B).then(function(){e=k.filter(e,function(a){return!a.loadError&&a.isVisibleAtScale(n)});c.resolve(e)}):(e=k.filter(e,function(a){return a.isVisibleAtScale(n)}),c.resolve(e))}return c.promise},_getLayerUrl:function(a,d){var c=a.indexOf("?");return-1===c?a+"/"+d:a.substring(0,c)+"/"+d+a.substring(c)},_getOutFields:function(a){var d;a.info&&"esri.widgets.PopupTemplate"===a.declaredClass?(d=[],k.forEach(a.info.fieldInfos,
function(a){var e=a.fieldName&&a.fieldName.toLowerCase();e&&("shape"!==e&&0!==e.indexOf("relationships/"))&&d.push(a.fieldName)})):d=["*"];return d},_calculateClickTolerance:function(a){var d=6;k.forEach(a,function(a){if(a=a.renderer)"esri.renderer.SimpleRenderer"===a.declaredClass?((a=a.symbol)&&a.xoffset&&(d=Math.max(d,Math.abs(a.xoffset))),a&&a.yoffset&&(d=Math.max(d,Math.abs(a.yoffset)))):("esri.renderer.UniqueValueRenderer"===a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)&&
k.forEach(a.infos,function(a){(a=a.symbol)&&a.xoffset&&(d=Math.max(d,Math.abs(a.xoffset)));a&&a.yoffset&&(d=Math.max(d,Math.abs(a.yoffset)))})});return d},_clickHandler:function(a){var d=this;if(this.view.popup&&this.view.ready){var c=a.screenPoint;null!=c?this.view.hitTest(c.x,c.y).then(function(a){0<a.results.length&&d._showPopup(a.results[0])}):this._showPopup(a)}}})});