// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/dom dojo/dom-construct dojo/dom-class ../Graphic ../core/Accessoire ../core/Collection ../core/Evented ../core/HandleRegistry ../core/AccessoirePromise ../core/watchUtils ../core/promiseUtils ../core/Scheduler ../geometry/SpatialReference ../geometry/Extent ./BreakpointsOwner ./DOMContainer ./LayerViewManager ./BasemapView ./GroundView ./PopupManager ./ui/DefaultUI ./support/DefaultsFromMap ../widgets/Popup".split(" "),function(h,e,c,g,k,l,f,m,n,p,d,q,r,s,t,u,v,w,x,y,
z,A,B,C){return l.createSubclass([p,v,m,u],{declaredClass:"esri.views.View",classMetadata:{properties:{allLayerViews:{type:f},basemapView:{},container:{},animation:{},resizing:{},interacting:{},graphics:{type:f.ofType(k)},groundView:{},initialExtent:{readOnly:!0,type:t,dependsOn:["defaultsFromMap.extent"]},initialExtentRequired:{},layerViews:{type:f},map:{},popup:{type:C},ready:{readOnly:!0,dependsOn:"map spatialReference surface width height suspended initialExtentRequired initialExtent defaultsFromMap.isDone map.loaded".split(" ")},
defaultsFromMapCollectionPaths:{},root:{},spatialReference:{type:s,dependsOn:["defaultsFromMap.spatialReference"]},stationary:{dependsOn:["animation","interacting","resizing"]},surface:{},type:{},ui:{type:A},updating:{},width:{},height:{},suspended:{}}},constructor:function(a){this._viewHandles=new n;this._viewHandles.add(this.watch("ready",function(a,D){this._currentSpatialReference=a?this.spatialReference:null;this.notifyChange("spatialReference");!a&&D&&this.layerViewManager.empty()}.bind(this)));
this.defaultsFromMap=new B({view:this})},getDefaults:function(){return h.mixin(this.inherited(arguments),{layerViews:[],allLayerViews:[],graphics:[],padding:{left:0,top:0,right:0,bottom:0},popup:{},ui:{}})},initialize:function(){var a=this.validate().then(function(){this._isValid=!0;this.notifyChange("ready");return d.whenOnce(this,"ready")}.bind(this));this.addResolvingPromise(a);this.basemapView=new x({view:this});this.groundView=new y({view:this});this.layerViewManager=new w({view:this,allLayerViews:this.allLayerViews});
this._resetInitialViewPropertiesFromContent()},destroy:function(){this.basemapView.destroy();this.groundView.destroy();this.destroyLayerViews();this.ui.destroy();this.popup&&this.popup.destroy();this.defaultsFromMap.destroy();this.defaultsFromMap=null;this._viewHandles.destroy();this.container=this.map=null},destroyLayerViews:function(){this.layerViewManager.destroy()},_viewHandles:null,_isValid:!1,_readyCycleForced:!1,_userSpatialReference:null,_currentSpatialReference:null,activeTool:"navigation",
animation:null,basemapView:null,groundView:null,container:null,_containerSetter:function(a,b){a=e.byId(a);if(b===a)return b;b&&(g.remove(b,"esri-view"),this.popupManager.destroy(),this.popupManager=null,c.destroy(this.root),this.root=null);a?(g.add(a,"esri-view"),this.root=c.create("div",{className:"esri-view-root"},a,"first"),this.surface=c.create("div",{className:"esri-view-surface"},this.root),e.setSelectable(this.surface,!1),this._forceReadyCycle(),this.popupManager=new z({enabled:!0,view:this})):
this.surface=null;return a},graphics:null,_graphicsSetter:function(a){this._graphicsView&&(this._graphicsView.graphics=a);return a},interacting:!1,_interactingSetter:function(a){var b=this.surface;b&&b.setAttribute("data-interacting",a);return a},layerViews:null,map:null,_mapSetter:function(a,b){if(a===b)return a;a&&a.load&&a.load();this._forceReadyCycle();this._resetInitialViewPropertiesFromContent();return a},padding:null,_popupSetter:function(a,b){if(a===b)return b;this._viewHandles.remove("view-popup");
b&&b.destroy();a&&(a.viewModel.view=this,a._started||a.startup(),this._viewHandles.add([d.init(this,"root",function(b,d){var c=a.domNode;e.isDescendant(c.parentNode,d)&&c.parentNode.removeChild(c);b&&!c.parentNode&&a.placeAt(b)})],"view-popup"));return a},_readyGetter:function(a){return!(!this._isValid||this._readyCycleForced||!this.map||!(null!=this.surface&&0!==this.width&&0!==this.height&&this.spatialReference&&(!this.map.load||this.map.loaded)&&(this._currentSpatialReference||!this.initialExtentRequired||
this.initialExtent||this.defaultsFromMap&&this.defaultsFromMap.isDone)&&this.isSpatialReferenceSupported(this.spatialReference)))},spatialReference:null,_spatialReferenceGetter:function(){return this._userSpatialReference||this._currentSpatialReference||this.getDefaultSpatialReference()||null},_spatialReferenceSetter:function(a){return this._userSpatialReference=a},stationary:!0,_stationaryGetter:function(){return!this.animation&&!this.interacting&&!this.resizing},surface:null,type:null,_uiSetter:function(a,
b){if(a===b)return b;this._viewHandles.remove("ui");b&&b.destroy();a&&(a.view=this,this._viewHandles.add([d.init(this,"root",function(b){a.container=b?c.create("div",null,b):null})],"ui"));return a},updating:!1,initialExtentRequired:!0,initialExtent:null,_initialExtentGetter:function(){return this.defaultsFromMap&&this.defaultsFromMap.extent},whenLayerView:function(a){return this.layerViewManager.whenLayerView(a)},addHandler:function(a){this.gestureManager&&this.gestureManager.addHandler(a);return this},
removeHandler:function(a){this.gestureManager&&this.gestureManager.removeHandler(a);return this},pageToContent:function(a,b,c){var d=this.padding;c=this.pageToContainer(a,b,c);d&&(c[0]-=d.left,c[1]-=d.top);return c},getDefaultSpatialReference:function(){return this.get("defaultsFromMap.spatialReference")},validate:function(){return q.resolve()},isSpatialReferenceSupported:function(){return!0},_resetInitialViewPropertiesFromContent:function(){if(this.defaultsFromMap){var a=this.defaultsFromMap.start.bind(this.defaultsFromMap);
this.defaultsFromMap.reset();this._currentSpatialReference=null;this.notifyChange("spatialReference");this._viewHandles.remove("defaultsFromMap");this._viewHandles.add([d.watch(this,"spatialReference",a),d.watch(this,"initialExtentRequired",a),r.schedule(a)],"defaultsFromMap")}},_forceReadyCycle:function(){this.ready&&(this._readyCycleForced=!0,this.notifyChange("ready"),d.whenFalseOnce(this,"ready",function(){this._readyCycleForced=!1;this.notifyChange("ready")}.bind(this)))}})});