// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array ../core/declare dojo/Deferred dojo/on dojo/promise/all dojo/when ../config ../geometry/SpatialReference ../tasks/support/Query ../tasks/support/StatisticDefinition ../tasks/GenerateRendererTask ../tasks/support/UniqueValueDefinition ../tasks/support/ClassBreaksDefinition ../tasks/support/GenerateRendererParameters ../tasks/support/generateRenderer ../tasks/GeometryService ../tasks/support/ProjectParameters ../layers/support/TileInfo ../layers/support/HeatmapManager ../workers/heatmapCalculator ../geometry/support/mathUtils ../geometry/support/webMercatorUtils ../geometry/Point ../geometry/Extent".split(" "),
function(u,q,G,p,B,H,C,I,x,t,D,J,K,L,y,M,N,O,P,Q,E,z,F,R,S){var T=E.prototype._calculateIntensityMatrix,U=E.calculateStats,V=Q.prototype._getScreenPoints,A=G(null,{declaredClass:"esri.plugins.FeatureLayerStatistics",sampleSize:500,generalizeForScale:4E5,generalizeForResolution:105,mapWidth:1280,mapHeight:800,minDistance:12,minLength:30,minSize:15,minPixels:15,samplingThreshold:2E4,numBins:10,numClasses:5,classificationMethod:"equal-interval",standardDeviationInterval:1,geometryServiceUrl:window.location.protocol+
"//utility.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer",tileInfo:new P({rows:256,cols:256,dpi:96,format:"JPEG",compressionQuality:90,origin:{x:-2.0037508342787E7,y:2.0037508342787E7},spatialReference:{wkid:102100,latestWkid:3857},lods:[{level:0,resolution:156543.03392800014,scale:5.91657527591555E8},{level:1,resolution:78271.51696399994,scale:2.95828763795777E8},{level:2,resolution:39135.75848200009,scale:1.47914381897889E8},{level:3,resolution:19567.87924099992,scale:7.3957190948944E7},
{level:4,resolution:9783.93962049996,scale:3.6978595474472E7},{level:5,resolution:4891.96981024998,scale:1.8489297737236E7},{level:6,resolution:2445.98490512499,scale:9244648.868618},{level:7,resolution:1222.992452562495,scale:4622324.434309},{level:8,resolution:611.4962262813797,scale:2311162.217155},{level:9,resolution:305.74811314055756,scale:1155581.108577},{level:10,resolution:152.87405657041106,scale:577790.554289},{level:11,resolution:76.43702828507324,scale:288895.277144},{level:12,resolution:38.21851414253662,
scale:144447.638572},{level:13,resolution:19.10925707126831,scale:72223.819286},{level:14,resolution:9.554628535634155,scale:36111.909643},{level:15,resolution:4.77731426794937,scale:18055.954822},{level:16,resolution:2.388657133974685,scale:9027.977411},{level:17,resolution:1.1943285668550503,scale:4513.988705},{level:18,resolution:0.5971642835598172,scale:2256.994353},{level:19,resolution:0.29858214164761665,scale:1128.497176}]}),constructor:function(a){u.mixin(this,a);this._scaleCache=this._sampleCache=
null;this._gsTask=I.geometryService||new N(this.geometryServiceUrl);if(this.layer.loaded)this._createGRTask();else B.once(this.layer,"load",u.hitch(this,this._createGRTask))},destroy:function(){this.layer=this._grTask=this._scaleCache=this._sampleCache=null},getUniqueValues:function(a){var b=new p;!a||!a.field?this._rejectDfd(b,"FeatureLayerStatistics.getUniqueValues: 'field' parameter is missing."):this._callAfterLoad(this._findUniqueValues,{dfd:b,params:a});return b.promise},getFieldStatistics:function(a){var b=
new p;!a||!a.field?this._rejectDfd(b,"FeatureLayerStatistics.getFieldStatistics: 'field' parameter is missing."):this._callAfterLoad(this._getFieldStats,{dfd:b,params:a});return b.promise},getSpatialStatistics:function(a){var b=new p;!a||!a.features||!a.features.length?this._rejectDfd(b,"FeatureLayerStatistics.getSpatialStatistics: 'features' parameter is missing or it has no features."):this._callAfterLoad(this._spatialStats,{dfd:b,params:a});return b.promise},getSuggestedSizeRange:function(a){var b=
new p;this._callAfterLoad(this._getSizeRange,{dfd:b,params:a});return b.promise},getHeatmapStatistics:function(a){var b=new p;this._callAfterLoad(this._getHeatmapStats,{dfd:b,params:a});return b.promise},getHistogram:function(a){var b=new p;!a||!a.field?this._rejectDfd(b,"FeatureLayerStatistics.getHistogram: 'field' parameter is missing."):this._callAfterLoad(this._getHistogram,{dfd:b,params:a});return b.promise},getSampleFeatures:function(a){var b=new p;this._callAfterLoad(this._sampleFeatures,{dfd:b,
params:a});return b.promise},getSuggestedScaleRange:function(a){var b=new p;this._callAfterLoad(this._scaleRange,{dfd:b,params:a});return b.promise},getClassBreaks:function(a){var b=new p;!a||!a.field?this._rejectDfd(b,"FeatureLayerStatistics.getClassBreaks: 'field' parameter is missing."):this._callAfterLoad(this._findClassBreaks,{dfd:b,params:a});return b.promise},_srcQuery:"service-query",_srcGenRend:"service-generate-renderer",_srcMemory:"features-in-memory",_log10e:Math.LOG10E,_reNumber:/\s*(\+|-)?((\d+(\.\d+)?)|(\.\d+))\s*/gi,
_isCollection:function(){return!this.layer.url},_getFieldStats:function(a){var b=this,c=a.params,d=this.layer.getField(c.field);this._rejectNonNumeric(a.dfd,d,"getFieldStatistics")||(this._isCollection()?this._statsFromMemory(c).then(function(b){a.dfd.resolve(b)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics.getFieldStatistics: unable to calculate field statistics.")}):(c.normalizationType?this._statsFromGenRend(c):this._statsFromQuery(c)).then(function(b){a.dfd.resolve(b)}).otherwise(function(d){b._statsFromMemory(c).then(function(b){a.dfd.resolve(b)}).otherwise(function(c){b._rejectDfd(a.dfd,
"FeatureLayerStatistics.getFieldStatistics: unable to calculate field statistics.")})}))},_statsFromQuery:function(a){var b=this.layer,c=new p;if(b.url&&b.supportsStatistics){var d=new t,e=this,g=this._getRangeExpr(a.field,a.minValue,a.maxValue);g&&(d.where=g);d.outStatistics=q.map("min max avg stddev count sum var".split(" "),function(b){var c=new D;c.statisticType=b;c.onStatisticField=a.field;c.outStatisticFieldName="var"===b?"variance":b;return c});b.queryFeatures(d).then(function(a){a=(a=a&&a.features)&&
a[0]&&a[0].attributes;var b,d={source:e._srcQuery};for(b in a)d[b.toLowerCase()]=a[b];d.min===d.max&&(null!=d.min&&null==d.stddev)&&(d.stddev=d.variance=0);c.resolve(d)}).otherwise(function(a){e._rejectDfd(c,"FeatureLayerStatistics: Statistics query operation failed.")})}else this._rejectDfd(c,"FeatureLayerStatistics: Statistics query requires a layer that supports statistics.");return c.promise},_statsFromMemory:function(a){var b=new p,c;if("percent-of-total"===a.normalizationType){c=this._calcStatsFromMemory({field:a.field}).sum;
if(null==c){this._rejectDfd(b,"getFieldStatistics: invalid normalizationTotal.");return}a=u.mixin({normalizationTotal:c},a)}b.resolve(this._calcStatsFromMemory(a));return b.promise},_calcStatsFromMemory:function(a){var b=this._getDataValues(this.layer.graphics,a);a=this._calcStatistics(b,!a.normalizationType);a.source=this._srcMemory;return a},_getDataValues:function(a,b){var c=b.field,d=b.normalizationType,e=b.normalizationField,g=b.normalizationTotal,f=null==b.minValue?-Infinity:b.minValue,k=null==
b.maxValue?Infinity:b.maxValue,l,h,m,n=[];q.forEach(a,function(a){m=(l=a.attributes)&&l[c];d&&null!=m&&(h=l&&parseFloat(l[e]),"log"===d&&0!=m?m=Math.log(m)*this._log10e:"percent-of-total"===d&&!isNaN(g)&&0!=g?m=100*(m/g):"field"===d&&(!isNaN(h)&&0!=h)&&(m/=h));null!=m&&(!isNaN(m)&&m>=f&&m<=k)&&n.push(m)},this);return n},_calcStatistics:function(a,b){var c=Infinity,d=-Infinity,e=0,g=null,f=null,k=null,l=null;q.forEach(a,function(a){e++;g+=a;a<c&&(c=a);a>d&&(d=a)});if(e){var f=g/e,h=0;q.forEach(a,function(a){h+=
Math.pow(a-f,2)});l=b?1<e?h/(e-1):0:0<e?h/e:0;k=Math.sqrt(l)}return{min:e?c:null,max:e?d:null,count:e,sum:g,avg:f,stddev:k,variance:l}},_statsFromGenRend:function(a){var b=new p,c=this,d=a.normalizationType,e=a.normalizationField;this.getClassBreaks({field:a.field,classificationMethod:"standard-deviation",standardDeviationInterval:0.25,normalizationType:d,normalizationField:"field"===d?e:void 0,minValue:a.minValue,maxValue:a.maxValue}).then(function(a){var d,e,l;q.some(a.classBreakInfos,function(a,
b){a.hasAvg&&(d=a);return!!d});d&&(l=d.maxValue-d.minValue,e=d.minValue+l/2,l*=4);b.resolve({min:a.minValue,max:a.maxValue,avg:e,stddev:l,source:c._srcGenRend})}).otherwise(function(a){c._rejectDfd(b,"FeatureLayerStatistics.getFieldStatistics: unable to calculate class breaks.")});return b.promise},_spatialStats:function(a){var b=a.params.features,c=this.layer.geometryType,d={},c={point:"point"===c,mPoint:"multipoint"===c,line:"polyline"===c,polygon:"polygon"===c};c.point?d=this._getPointStats(b):
c.mPoint?d=this._getPointStats(b,!0):c.line?d=this._getLineStats(b):c.polygon&&(d=this._getPolygonStats(b));d.avgXY=this._getAvgXY(b,c);a.dfd.resolve(d)},_getPointStats:function(a,b){var c,d,e=a.length,g,f,k={},l={},h=0,m=0,n=Infinity,s=-Infinity,r=0,p=0,q,w,v=[];if(b)for(c=0;c<e;c++)a[c].geometry&&v.push.apply(v,a[c].geometry.points);else v=a;e=v.length;for(c=0;c<e;c++)if(b?(k.x=v[c][0],k.y=v[c][1],g=k):g=v[c].geometry,g){q=Infinity;w=-Infinity;for(d=0;d<e;d++)d!==c&&(b?(l.x=v[d][0],l.y=v[d][1],
f=l):f=v[d].geometry,f&&(f=z.getLength(g,f),0<f&&(f<q&&(q=f),f<n&&(n=f),f>w&&(w=f),f>s&&(s=f))));Infinity!==q&&(++r,h+=q);-Infinity!==w&&(++p,m+=w)}return{minDistance:Infinity!==n?n:null,maxDistance:-Infinity!==s?s:null,avgMinDistance:r?h/r:null,avgMaxDistance:p?m/p:null}},_getLineStats:function(a){var b,c=a.length,d,e={},g={},f=Infinity,k=-Infinity,l=0,h=0;for(b=0;b<c;b++)if(d=a[b].geometry)d=this._getLineLength(d,e,g),0<d&&(++h,l+=d,d<f&&(f=d),d>k&&(k=d));return{minLength:Infinity!==f?f:null,maxLength:-Infinity!==
k?k:null,avgLength:h?l/h:null}},_getLineLength:function(a,b,c){a=a.paths;var d,e=a.length,g,f=0;for(d=0;d<e;d++)g=a[d],g=this._getActualLineLength(g,b,c),0<g&&(f+=g);return f},_getApproxLineLength:function(a,b,c){var d=a[0],e=a[a.length-1],g=0;d&&(e&&d[0]===e[0]&&d[1]===e[1])&&(e=a[a.length-2]);d&&(e&&d!==e)&&(b.x=d[0],b.y=d[1],c.x=e[0],c.y=e[1],g=z.getLength(b,c));return g},_getActualLineLength:function(a,b,c){var d,e=a.length,g,f,k=0;for(d=0;d<e-1;d++)g=a[d],f=a[d+1],g&&f&&(b.x=g[0],b.y=g[1],c.x=
f[0],c.y=f[1],k+=z.getLength(b,c));return k},_getPolygonStats:function(a){var b,c=a.length,d,e=Infinity,g=-Infinity,f=0,k=0;for(b=0;b<c;b++)if(a[b].geometry&&(d=a[b].geometry.getExtent()))d=(d.getWidth()+d.getHeight())/2,0<d&&(++k,f+=d,d<e&&(e=d),d>g&&(g=d));return{minSize:Infinity!==e?e:null,maxSize:-Infinity!==g?g:null,avgSize:k?f/k:null}},_getAvgXY:function(a,b){var c,d,e,g=a.length,f,k,l,h,m=null,n=null,s=0,r;for(c=0;c<g;c++)if(d=a[c].geometry)if(b.point)++s,m+=d.x,n+=d.y;else if(b.mPoint){l=
d.points;k=l.length;for(d=0;d<k;d++)++s,m+=l[d][0],n+=l[d][1]}else if(b.line){h=d.paths;f=h.length;for(d=0;d<f;d++){l=h[d];k=l.length;for(e=0;e<k;e++)++s,m+=l[e][0],n+=l[e][1]}}else if(b.polygon){h=d.rings;f=h.length;for(d=0;d<f;d++){l=h[d];k=l.length;for(e=0;e<k;e++)++s,m+=l[e][0],n+=l[e][1]}}null!=m&&null!=n&&(r={x:m/s,y:n/s});return r},_getSizeRange:function(a){var b=this,c=this.layer,d=c.getMap();"polygon"!==c.geometryType?this._rejectDfd(a.dfd,"FeatureLayerStatistics.getSuggestedSizeRange: not supported for points and lines."):
d?this._getFeatures(d,a.params).then(function(c){b.getSpatialStatistics({features:c}).then(function(c){b._calcSizeRange(c,d,a.dfd)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics.getSuggestedSizeRange: unable to calculate spatial statistics.")})}).otherwise(function(c){b._rejectDfd(a.dfd,c.message)}):this._rejectDfd(a.dfd,"FeatureLayerStatistics.getSuggestedSizeRange: layer has to be added to the map.")},_getFeatures:function(a,b){var c=new p,d=this,e;b&&b.useMapExtent?(e=new t,
e.geometry=a.extent,e=this.layer.queryFeatures(e)):e={features:this.layer.graphics.slice(0)};C(e).then(function(a){(a=a&&a.features)&&a.length?c.resolve(a):d._rejectDfd(c,"FeatureLayerStatistics.getSuggestedSizeRange: layer has 0 features.")}).otherwise(function(a){d._rejectDfd(c,"FeatureLayerStatistics.getSuggestedSizeRange: unable to query features.")});return c.promise},_calcSizeRange:function(a,b,c){var d=a&&a.avgSize;b=b.getResolution();var e;null==d||isNaN(d)||!b?this._rejectDfd(c,"FeatureLayerStatistics.getSuggestedSizeRange: invalid average feature size."):
(d=Math.ceil(d/b),b=Math.ceil(d/4),4>b?b=4:16<b&&(b=16),e=5*b,e=50>e?50:e,null==e||isNaN(e)?this._rejectDfd(c,"FeatureLayerStatistics.getSuggestedSizeRange: invalid maxSize."):c.resolve({minSize:b,maxSize:e,spatialStatistics:a,avgFeatureSize:d}))},_getHeatmapStats:function(a){var b=this,c=this.layer,d=a.params,e=a.dfd,g=d.fieldOffset;a=d.field&&this.layer.getField(d.field);if(!d.field||!this._rejectNonNumeric(e,a,"getHeatmapStatistics"))d.field&&null==g?c.statisticsPlugin.getFieldStatistics({field:d.field}).then(function(a){b._calcHeatmapStats(a,
g,d,e)}).otherwise(function(a){b._rejectDfd(e,"FeatureLayerStatistics.getHeatmapStatistics: unable to calculate field statistics.")}):this._calcHeatmapStats(null,g,d,e)},_calcHeatmapStats:function(a,b,c,d){var e=this;if(a){var g=a.min,f=a.max;a.count?g===f&&0===g?b=1:0>=f?b="abs":0>g&&(b=-1.01*g):b=1}this._heatStatsFromMemory(c,b).then(function(c){c.fieldStatistics=a;c.fieldOffset=b;d.resolve(c)}).otherwise(function(a){e._rejectDfd(d,"FeatureLayerStatistics.getHeatmapStatistics: unable to calculate heatmap statistics.")})},
_heatStatsFromMemory:function(a,b){var c=new p,d=this.layer,e=d.graphics,g=e.length,f=d.getMap();if(!g)return c.resolve({count:0,min:null,max:null,avg:null,stddev:null,source:this._srcMemory}),c.promise;(d=(d=f&&T(V(e,f,d),f.width,f.height,a.blurRadius||10,a.field,b))&&d.matrix&&U(d.matrix))?c.resolve({count:g,min:d.min,max:d.max,avg:d.mean,stddev:d.stdDev,source:this._srcMemory}):this._rejectDfd(c,"FeatureLayerStatistics.getHeatmapStatistics: unable to calculate heatmap statistics.");return c.promise},
_getHistogram:function(a){var b=this,c=a.params,d=c.minValue,e=c.maxValue,g=null!=d&&null!=e,f=this.layer.getField(c.field);this._rejectNonNumeric(a.dfd,f,"getHistogram")||(c.normalizationType||c.classificationMethod&&"equal-interval"!==c.classificationMethod?this._binParamsFromGenRend(c).then(function(f){g?d>f.max||e<f.min?b._rejectDfd(a.dfd,"FeatureLayerStatistics.getHistogram: custom value range is beyond field value range."):(f=b._getFieldExpr(c,f.normTotal),f=b._getRangeExpr(f,d,e),b._binParamsFromGenRend(c,
f).then(function(c){b._getBins(a,c.sqlExpr,c.min,c.max,c.intervals,c.source,c.normTotal,c.excludeZerosExpr)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics.getHistogram: unable to calculate histogram parameters using custom min/max values.")})):b._getBins(a,f.sqlExpr,f.min,f.max,f.intervals,f.source,f.normTotal,f.excludeZerosExpr)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics.getHistogram: unable to calculate min/max from generate renderer operation.")}):g?
this._getBins(a,null,d,e,null,"parameters"):this.getFieldStatistics(c).then(function(c){c.count?b._getBins(a,null,c.min,c.max,null,c.source):b._rejectDfd(a.dfd,"FeatureLayerStatistics.getHistogram: cannot calculate histogram for 0 features (statistics.count \x3d 0).")}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics.getHistogram: unable to calculate min/max.")}))},_getBins:function(a,b,c,d,e,g,f,k){var l=this,h=a.params.field,m=a.params.numBins||this.numBins,n=(d-c)/m,s,r=c,p;if(!e){e=
[];for(s=1;s<=m;s++)p=r+n,e.push([r,p]),r=p}b=b||h;this._isCollection()?this._countBinsInMemory(a,c,d,e,f,g):this._queryBins(b,e,k).then(function(b){b=q.map(b,function(a,b){return{minValue:e[b][0],maxValue:e[b][1],count:a}});a.dfd.resolve({bins:b,minValue:c,maxValue:d,normalizationTotal:f,source:l._srcQuery,statisticsSource:g})}).otherwise(function(b){l._countBinsInMemory(a,c,d,e,f,g)})},_countBinsInMemory:function(a,b,c,d,e,g){var f=this;this._binsFromMemory(a.params,b,c,d,e).then(function(d){a.dfd.resolve({bins:d,
minValue:b,maxValue:c,normalizationTotal:e,source:f._srcMemory,statisticsSource:g})}).otherwise(function(b){f._rejectDfd(a.dfd,"FeatureLayerStatistics: unable to calculate histogram.")})},_queryBins:function(a,b,c){var d=this.layer,e,g,f=[],k=b.length;for(e=0;e<k;e++)g=new t,g.where=(c?c+" AND ":"")+a+" \x3e\x3d "+b[e][0]+(null!==b[e][1]?" AND "+a+(e===k-1?" \x3c\x3d ":" \x3c ")+b[e][1]:""),f.push(g);return H(q.map(f,function(a){return d.queryCount(a)}))},_binsFromMemory:function(a,b,c,d,e){var g=
new p,f=a.field,k=a.normalizationType;a=a.normalizationField;var l=this.layer.graphics,h,m,n,s,r,q=[];if(!l.length)return this._rejectDfd(g,"Layer has 0 features in memory."),g.promise;s=d.length;for(n=0;n<s;n++)q.push({minValue:d[n][0],maxValue:d[n][1],count:0});s=l.length;for(n=0;n<s;n++)h=(m=(h=l[n])&&h.attributes)&&m[f],null!=h&&(k?(r=null,m=m&&parseFloat(m[a]),"log"===k&&0!=h?r=Math.log(h)*this._log10e:"percent-of-total"===k&&!isNaN(e)&&0!=e?r=100*(h/e):"field"===k&&(!isNaN(m)&&0!=m)&&(r=h/m)):
r=h,null!=r&&(!isNaN(r)&&r>=b&&r<=c)&&(h=this._binIndex(d,r),-1<h&&q[h].count++));g.resolve(q);return g.promise},_binIndex:function(a,b){var c,d,e=-1;for(c=a.length-1;0<=c;c--)if(d=a[c][0],b>=d){e=c;break}return e},_binParamsFromGenRend:function(a,b){var c=this.layer,d=new p,e=this,g=this._getGRWhereInfo(c,a),f=g.where,k=a.numBins||this.numBins,l=this._createCBDefn(a,k),h=new y;h.classificationDefinition=l;h.where=f?f+(b?" AND "+b:""):b;!this._isCollection()&&10.1<=c.version?this._grTask.execute(h).then(function(b){e._resolveBinParams(b,
g,e._srcGenRend,a,d)}).otherwise(function(b){e._binParamsFromMemory(k,g,e._srcMemory,a,d)}):e._binParamsFromMemory(k,g,e._srcMemory,a,d);return d.promise},_binParamsFromMemory:function(a,b,c,d,e){var g=this;this._cbFromMemory(d,a).then(function(a){g._resolveBinParams(a,b,c,d,e)}).otherwise(function(a){g._rejectDfd(e,"FeatureLayerStatistics.getHistogram: unable to calculate class breaks.")})},_resolveBinParams:function(a,b,c,d,e){var g,f,k=[],l=a.infos;f=l.length;g=l[0].minValue;f=l[f-1].maxValue;
q.forEach(l,function(a,b){k.push([a.minValue,a.maxValue])});e.resolve({min:g,max:f,intervals:k,sqlExpr:this._getFieldExpr(d,a.normalizationTotal),excludeZerosExpr:b.excludeZerosExpr,normTotal:a.normalizationTotal,source:c})},_getGRWhereInfo:function(a,b){var c=b.field,d=b.normalizationType,e=b.normalizationField,g=a.getDefinitionExpression(),f;"log"===d?f="(NOT "+c+" \x3d 0)":"field"===d&&(f="(NOT "+e+" \x3d 0)");return{where:f?f+(g?" AND "+g:""):g,excludeZerosExpr:f}},_getFieldExpr:function(a,b){var c=
a.field,d=a.normalizationType,e=a.normalizationField,g=c;"percent-of-total"===d?g="(("+c+" / "+b+") * 100)":"log"===d?g="(log("+c+") * "+this._log10e+")":"field"===d&&(g="("+c+" / "+e+")");return g},_getRangeExpr:function(a,b,c){b=null!=b?a+" \x3e\x3d "+b:"";a=null!=c?a+" \x3c\x3d "+c:"";c="";return(c=b&&a?b+" AND "+a:b||a)?"("+c+")":""},_sampleFeatures:function(a){var b=this,c=a.params,d=a.dfd,e=this.layer,g=e.graphics;a=this._sampleCache;var f=c&&c.resample,k=c&&c.sampleSize||this.sampleSize;a&&
!f?d.resolve(this._cloneSample(a)):(d._time={start:this._getTime()},g.length&&k<=g.length?this._resolveSample(d,this._pickItems(g,k),this._srcMemory):(a=new t,a.where="1\x3d1",d._time.countStart=this._getTime(),e.queryCount(a).then(function(a){d._time.countEnd=b._getTime();d._totalFeatures=a;k>e.maxRecordCount&&(k=e.maxRecordCount);var f;if(a)if(a<=k)f=new t,f.where="1\x3d1",b._queryFeatures(f,c,e,g,d);else if(a<=b.samplingThreshold)a=new t,a.where="1\x3d1",d._time.idStart=b._getTime(),e.queryIds(a).then(function(a){d._time.idEnd=
b._getTime();var f=new t;f.objectIds=b._pickItems(a,k);b._queryFeatures(f,c,e,g,d)}).otherwise(function(a){f=new t;f.where="1\x3d1";b._queryFeatures(f,c,e,g,d)});else{f=new t;f.where="1\x3d1";if((a=e.advancedQueryCapabilities)&&a.supportsPagination)f.num=k;b._queryFeatures(f,c,e,g,d)}else b._resolveSample(d,[],b._srcQuery)}).otherwise(function(a){b._resolveSample(d,b._pickItems(g,g.length),b._srcMemory)})))},_queryFeatures:function(a,b,c,d,e){var g=this;a.outSpatialReference=b&&b.spatialReference;
a.maxAllowableOffset=b&&b.maxAllowableOffset;a.outFields=b&&b.outFields;e._time.featStart=this._getTime();c.queryFeatures(a).then(function(a){e._time.featEnd=g._getTime();g._resolveSample(e,a&&a.features||[],g._srcQuery)}).otherwise(function(a){g._resolveSample(e,g._pickItems(d,d.length),g._srcMemory)})},_pickItems:function(a,b){var c=a.length,d=[],e,g=[];if(b>=c)g=a.slice(0);else for(;g.length<b;)e=this._getRandomInt(0,c),-1===q.indexOf(d,e)&&(d.push(e),g.push(a[e]));return g},_getRandomInt:function(a,
b){return Math.floor(Math.random()*(b-a))+a},_resolveSample:function(a,b,c){b=b||[];var d,e=b.length,g;for(d=0;d<e&&!(g=(g=b[d].geometry)&&g.spatialReference);d++);a._time.end=(new Date).getTime();d=a._time;a._time=null;this._sampleCache={features:b,spatialReference:g&&new x(g.toJSON()),source:c,time:this._getTimeStats(d),totalFeatures:a._totalFeatures};a.resolve(this._cloneSample(this._sampleCache))},_cloneSample:function(a){return{features:q.map(a.features,function(a){return new a.constructor(a.toJSON())}),
spatialReference:a.spatialReference&&new x(a.spatialReference.toJSON()),source:a.source,time:u.clone(a.time),totalFeatures:a.totalFeatures}},_getTimeStats:function(a){var b=this._getTimeDiff;return{total:b(a.start,a.end),features:b(a.featStart,a.featEnd),featureIds:b(a.idStart,a.idEnd),featureCount:b(a.countStart,a.countEnd)}},_getTimeDiff:function(a,b){var c,d;null!=a&&null!=b&&(c=b-a,d="millisecond",1E3<=c&&(c/=1E3,d="second",60<=c&&(c/=60,d="minute")),c={value:Number(c.toFixed(2)),unit:d});return c},
_getTime:function(){return(new Date).getTime()},_scaleRange:function(a){var b=this,c=a.params,d=this.layer,e=this.layer.geometryType,g={point:"point"===e,mPoint:"multipoint"===e,line:"polyline"===e,polygon:"polygon"===e},e=c&&c.sampleSize||this.sampleSize,f=c&&c.map||d.getMap(),k=c&&c.mapWidth||this.mapWidth,l=c&&c.mapHeight||this.mapHeight,h=c&&c.generalizeForScale||this.generalizeForScale,m,n;f&&f.__tileInfo?(m=f.__tileInfo,n=f.spatialReference,f=f.extent.getWidth()/f.width/f.getScale()*h):(m=this.tileInfo,
n=m.spatialReference,f=this.generalizeForResolution/this.generalizeForScale*h);this.getSampleFeatures({sampleSize:e,spatialReference:n,maxAllowableOffset:f,outFields:[]}).then(function(e){var f=b._projectExtent(d.fullExtent,n),h=e.features;h&&h.length?b.getSpatialStatistics({features:h}).then(function(d){C(f).always(function(f){f=f&&f.hasOwnProperty("xmin")?f:null;var h=b._getLODForMinScale(c,d,g,m),n=g.polygon?b._getLODForMaxScale(c,d,g,m):null;b._processScaleRange(a.dfd,h,n,m,k,l,f,e,d,g)})}).otherwise(function(c){b._rejectDfd(a.dfd,
"FeatureLayerStatistics.getSuggestedScaleRange: unable to calculate spatial statistics.")}):b._rejectDfd(a.dfd,"FeatureLayerStatistics.getSuggestedScaleRange: sampling returned 0 features.")}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics.getSuggestedScaleRange: unable to sample features.")})},_processScaleRange:function(a,b,c,d,e,g,f,k,l,h){var m=l.avgXY,n=m&&new R(m.x,m.y,k.spatialReference&&new x(k.spatialReference.toJSON())),s=this,r,p=h.polygon?c?Math.floor(c.scale):null:0;
d=d.lods;var q;b&&(f&&n)&&(q=this._findClosestLOD(d,b,f,n,e,g));r=(b=q||b)?Math.ceil(b.scale):null;b||c?b&&n?this._countAtView(n,b,e,g).then(function(b){var c;b||(b=k.features[0],c=h.point?b.geometry:(b=b.geometry&&b.geometry.getExtent())&&b.getCenter());s._resolveScaleRange(a,r,p,c||n,k,l)}).otherwise(function(b){s._resolveScaleRange(a,r,p,n,k,l)}):this._resolveScaleRange(a,r,p,n,k,l):this._rejectDfd(a,"FeatureLayerStatistics.getSuggestedScaleRange: unable to find optimal scale range.")},_resolveScaleRange:function(a,
b,c,d,e,g){b<c?this._rejectDfd(a,"FeatureLayerStatistics.getSuggestedScaleRange: invalid scale range - calculated minScale is less than maxScale."):a.resolve({minScale:b,maxScale:c,center:d,sampleInfo:e,spatialStatistics:g})},_countAtView:function(a,b,c,d){a=this._getExtentFromCenter(a,b,c,d);b=new t;b.geometry=a;return this.layer.queryCount(b).promise},_projectExtent:function(a,b){if(a.spatialReference.equals(b))return new a.constructor(a.toJSON());if(F.canProject(a.spatialReference,b))return F.project(a,
b);var c=new O;c.geometries=[a];c.outSR=b;return this._gsTask.project(c).then(function(a){return a&&a[0]})},_getLODForMinScale:function(a,b,c,d){var e=a&&a.minDistance||this.minDistance,g=a&&a.minLength||this.minLength;a=a&&a.minSize||this.minSize;var f,k,l;c.point?(f=b.avgMinDistance,l=e):c.mPoint?(f=b.avgMinDistance,l=e):c.line?(f=b.avgLength,l=g):c.polygon&&(f=b.avgSize,l=a);0<f&&(k=this._findLOD(d,f,l));return k},_getLODForMaxScale:function(a,b,c,d){var e=this.mapWidth,g=a&&a.maxDistance||e/4,
f=a&&a.maxLength||e/4;a=a&&a.maxSize||e/2;var k,l,h;c.point?(k=b.minDistance,h=g):c.mPoint?(k=b.minDistance,h=g):c.line?(k=b.minLength,h=f):c.polygon&&(k=b.minSize,h=a);0<k&&(l=this._findLOD(d,k,null,h));return l},_findLOD:function(a,b,c,d){a=a&&a.lods;var e,g,f,k;if(a&&a.length){var l=null!=d,h=l?0:a.length-1,m=l?-1:1;for(f=l?a.length-1:0;l?f>=h:f<=h;f+=m)if(g=a[f],k=Math.round(b/g.resolution),l){if(k<=d){e=g;break}}else if(k>=c){e=g;break}}return e},_getExtentFromCenter:function(a,b,c,d){c=c/2*
b.resolution;b=d/2*b.resolution;return new S(a.x-c,a.y-b,a.x+c,a.y+b,new x(a.spatialReference.toJSON()))},_findClosestLOD:function(a,b,c,d,e,g){var f,k=a.length,l,h;for(f=0;f<k;f++)if(!(a[f].level<b.level))if(l=this._getExtentFromCenter(d,a[f],e,g),l.contains(c)){if(f===k-1){h=a[f];break}}else{h=a[f-1];break}return h=h&&h.level>b.level?h:null},_findUniqueValues:function(a){var b=this,c=a.params,d=this.layer.getField(c.field);d?this._isCollection()?this._uvFromMemory(c).then(function(c){b._resolveUVDfd(c,
a,d,b._srcMemory)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics: unable to calculate unique values.")}):this._uvFromStatisticsQuery(c).then(function(c){b._resolveUVDfd(c,a,d,b._srcQuery)}).otherwise(function(e){b._uvFromGenRenderer(c,d).then(function(c){b._resolveUVDfd(c,a,d,b._srcGenRend)}).otherwise(function(e){b._uvFromMemory(c).then(function(c){b._resolveUVDfd(c,a,d,b._srcMemory)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics: unable to calculate unique values.")})})}):
this._rejectDfd(a.dfd,"FeatureLayerStatistics.getUniqueValues: unknown 'field'.")},_uvFromStatisticsQuery:function(a){var b=this.layer,c=new p;if(b.supportsStatistics){var d="countOF"+a.field,e=this,g=new D;g.statisticType="count";g.onStatisticField=a.field;g.outStatisticFieldName=d;var f=new t;f.outStatistics=[g];f.groupByFieldsForStatistics=[a.field];b.queryFeatures(f).then(function(g){var l,h,m={},n,p;q.forEach(g.features,function(b){l=b.attributes;h=this._getAttributeVal(l,a.field);n=this._getAttributeVal(l,
d);null===h&&0===n&&(p=!0);if(null==h||""===h||"string"===typeof h&&""===u.trim(h))h=null;null==m[h]?m[h]={count:n,data:h}:m[h].count+=n},e);p?(f=new t,f.where=a.field+" is NULL",b.queryCount(f).then(function(a){m["null"].count+=a||0;c.resolve({count:m})}).otherwise(function(a){c.resolve({count:m})})):c.resolve({count:m})}).otherwise(function(a){e._rejectDfd(c,"FeatureLayerStatistics: Statistics query operation failed.")})}else this._rejectDfd(c,"FeatureLayerStatistics: Statistics query requires a layer that supports statistics.");
return c.promise},_uvFromGenRenderer:function(a,b){var c=this.layer,d=new p,e=this;if(10.1<=c.version){var g=new K;g.attributeField=a.field;var f=new y;f.classificationDefinition=g;f.where=c.getDefinitionExpression();this._grTask.execute(f).then(function(a){var c={},f,g=-1<q.indexOf(e._numericTypes,b.type);q.forEach(a.infos,function(a){f=a.value;if(null==f||""===f||"string"===typeof f&&(""===u.trim(f)||"\x3cnull\x3e"===f.toLowerCase()))f=null;null==c[f]?c[f]={count:a.count,data:g&&f?Number(f):f}:
c[f].count+=a.count});d.resolve({count:c})}).otherwise(function(a){e._rejectDfd(d,"FeatureLayerStatistics: Generate renderer operation failed.")})}else this._rejectDfd(d,"FeatureLayerStatistics: Generate renderer operation requires server version 10.1 or later.");return d.promise},_uvFromMemory:function(a){var b=this.layer,c=new p,d=a.field,e,g,f={};q.forEach(b.graphics,function(a){g=(e=a.attributes)&&e[d];if(null==g||""===g||"string"===typeof g&&""===u.trim(g))g=null;null==f[g]?f[g]={count:1,data:g}:
f[g].count++});c.resolve({count:f});return c.promise},_resolveUVDfd:function(a,b,c,d){var e=a.count;c=this.layer.getDomain(c.name);var g;a=[];b.params.includeAllCodedValues&&(c&&"codedValue"===c.type)&&q.forEach(c.codedValues,function(a){a=a.code;e.hasOwnProperty(a)||(e[a]={data:a,count:0})});for(g in e)c=e[g],a.push({value:c.data,count:c.count});b.dfd.resolve({source:d,uniqueValueInfos:a})},_findClassBreaks:function(a){var b=this,c=a.params,d=c.minValue,e=c.maxValue,g=null!=d||null!=e,f=c.classificationMethod,
k="percent-of-total"===c.normalizationType,l=c.numClasses||this.numClasses,h=!1!==c.analyzeData,m=this.layer.getField(c.field);if(!this._rejectNonNumeric(a.dfd,m,"getClassBreaks")){if(g)if(h){if(k&&null==c.normalizationTotal){this._rejectDfd(a.dfd,"FeatureLayerStatistics.getClassBreaks: normalizationTotal is required when minValue/maxValue are specified.");return}}else{if(null==d||null==e){this._rejectDfd(a.dfd,"FeatureLayerStatistics.getClassBreaks: both minValue AND maxValue are required when data analysis is disabled.");
return}if(f&&"equal-interval"!==f){this._rejectDfd(a.dfd,"FeatureLayerStatistics.getClassBreaks: data analysis can be disabled only for equal-interval classification.");return}if(k&&null==c.normalizationTotal){this._rejectDfd(a.dfd,"FeatureLayerStatistics.getClassBreaks: normalizationTotal is required when data analysis is disabled.");return}}else if(!h){this._rejectDfd(a.dfd,"FeatureLayerStatistics.getClassBreaks: both minValue AND maxValue are required when data analysis is disabled.");return}h?
this._cbFromGenRend(c,l).then(function(d){b._resolveCBDfd(a.dfd,c,d,b._srcGenRend)}).otherwise(function(d){g?b._rejectDfd(a.dfd,"FeatureLayerStatistics.getClassBreaks: cannot calculate class breaks in-memory when minValue/maxValue are specified."):b._cbFromMemory(c,l).then(function(d){b._resolveCBDfd(a.dfd,c,d,b._srcMemory)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics: unable to calculate class breaks.")})}):this._cbFromInterpolation(c,l).then(function(d){b._resolveCBDfd(a.dfd,
c,d,b._srcMemory)}).otherwise(function(c){b._rejectDfd(a.dfd,"FeatureLayerStatistics: unable to calculate class breaks.")})}},_cbFromGenRend:function(a,b){var c=this.layer,d=new p,e=this;if(c.url&&10.1<=c.version){var g=this._createCBDefn(a,b),c=this._getGRWhereInfo(c,a).where,f=this._getFieldExpr(a,a.normalizationTotal),f=this._getRangeExpr(f,a.minValue,a.maxValue),k=new y;k.classificationDefinition=g;k.where=c?c+(f?" AND "+f:""):f;this._grTask.execute(k).then(function(a){d.resolve(a)}).otherwise(function(a){e._rejectDfd(d,
"FeatureLayerStatistics: Generate renderer operation failed.")})}else this._rejectDfd(d,"FeatureLayerStatistics: Generate renderer operation requires server version 10.1 or later.");return d.promise},_cbFromMemory:function(a,b){var c=new p,d=this.layer.graphics;if(d.length){var e=this._createCBDefn(a,b),g;if("percent-of-total"===a.normalizationType){g=this._calcStatsFromMemory({field:a.field}).sum;if(null==g)return this._rejectDfd(c,"FeatureLayerStatistics: Invalid normalizationTotal."),c.promise;
a=u.mixin({normalizationTotal:g},a)}c.resolve(M.createClassBreaksRenderer({features:d,definition:e,values:this._getDataValues(d,a)}))}else this._rejectDfd(c,"Layer has 0 features in memory.");return c.promise},_cbFromInterpolation:function(a,b){var c=new p,d=a.minValue,e=a.maxValue;if(d>=e||!b||1>b)this._rejectDfd(c,"FeatureLayerStatistics.getClassBreaks: invalid input parameters: minValue, maxValue or numClasses.");else{var g=[],f,k,l=(e-d)/b;for(f=0;f<b;f++)k=d+f*l,g.push({minValue:k,maxValue:k+
l});g[b-1].maxValue=e;c.resolve({infos:g,normalizationTotal:a.normalizationTotal})}return c.promise},_createCBDefn:function(a,b){var c=a.field,d=a.classificationMethod||this.classificationMethod,e=a.normalizationType,g=a.normalizationField,f=new L;f.classificationField=c;f.breakCount=b;f.classificationMethod=d;f.standardDeviationInterval="standard-deviation"===d?a.standardDeviationInterval||this.standardDeviationInterval:void 0;f.normalizationType=e;f.normalizationField="field"===e?g:void 0;return f},
_resolveCBDfd:function(a,b,c,d){var e=c.infos,g=e[0].minValue,f=e[e.length-1].maxValue,k="standard-deviation"===b.classificationMethod,l=this._reNumber,h,m,n,e=q.map(e,function(a){n=a.label;m={minValue:a.minValue,maxValue:a.maxValue,label:n};k&&n&&(h=n.match(l),h=q.map(h,function(a){return+u.trim(a)}),2===h.length?(m.minStdDev=h[0],m.maxStdDev=h[1],0>h[0]&&0<h[1]&&(m.hasAvg=!0)):1===h.length&&(-1<n.indexOf("\x3c")?(m.minStdDev=null,m.maxStdDev=h[0]):-1<n.indexOf("\x3e")&&(m.minStdDev=h[0],m.maxStdDev=
null)));return m});a.resolve({minValue:g,maxValue:f,classBreakInfos:e,normalizationTotal:c.normalizationTotal,source:d})},_rejectDfd:function(a,b){a.reject(Error(b))},_rejectNonNumeric:function(a,b,c){var d;if(b){if(b.name===this.layer.objectIdField||-1===q.indexOf(this._numericTypes,b.type))this._rejectDfd(a,"FeatureLayerStatistics."+c+": 'field' should be numeric."),d=!0}else this._rejectDfd(a,"FeatureLayerStatistics."+c+": unknown 'field'."),d=!0;return d},_getAttributeVal:function(a,b){var c,
d;b=b.toLowerCase();if(a)for(d in a)if(d.toLowerCase()===b){c=a[d];break}return c},_callAfterLoad:function(a,b){if(this.layer.loaded)a.call(this,b);else B.once(this.layer,"load",u.hitch(this,a,b))},_numericTypes:["integer","small-integer","single","double"],_createGRTask:function(){this._grTask=new J(this.layer,{source:this.layer.source,gdbVersion:this.layer.gdbVersion})}});u.mixin(A,{add:function(a,b){if(!a.statisticsPlugin){var c=b||{};c.layer=a;a.statisticsPlugin=new A(c)}},remove:function(a){a.statisticsPlugin&&
(a.statisticsPlugin.destroy(),delete a.statisticsPlugin)}});return A});