// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/widgets/Popup/templates/PopupRenderer.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"${_css.container}"\x3e\r\n    \x3cdiv class\x3d"${_css.main}"\x3e\r\n      \x3cdiv class\x3d"${_css.loadingSpinnerContainer}"\x3e\x3cspan class\x3d"${_css.loadingSpinner}"\x3e\x3c/span\x3e\x3c/div\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"_contentNode"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("require ../Widget ./PopupRendererViewModel ../../core/requireUtils ../../core/watchUtils dojo/_base/lang dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/on dijit/_TemplatedMixin dijit/a11yclick dojo/i18n!./nls/PopupRenderer dojo/text!./templates/PopupRenderer.html".split(" "),function(t,u,v,w,r,q,x,k,d,p,y,s,m,z){var c={base:"esri-popup-renderer",container:"esri-popup-renderer-container",main:"esri-popup-renderer-main",content:"esri-popup-renderer-content",contentElement:"esri-popup-renderer-content-element",
text:"esri-popup-renderer-text",attachments:"esri-popup-renderer-attachments",attachmentsTitle:"esri-popup-renderer-attachments-title",attachmentsItem:"esri-popup-renderer-attachments-item",attachmentsItemIcon:"esri-popup-renderer-attachments-item-icon esri-icon-download",fields:"esri-popup-renderer-fields",btn:"esri-popup-renderer-button",icon:"esri-popup-renderer-icon",iconText:"esri-icon-font-fallback-text",media:"esri-popup-renderer-media",mediaContainer:"esri-popup-renderer-media-container",
mediaItemContainer:"esri-popup-renderer-media-item-container",mediaItem:"esri-popup-renderer-media-item",mediaItemTitle:"esri-popup-renderer-media-item-title",mediaItemCaption:"esri-popup-renderer-media-item-caption",mediaPrevious:"esri-media-previous",previousIconLTR:"esri-previous-icon-ltr esri-icon-left-triangle-arrow",previousIconRTL:"esri-previous-icon-rtl esri-icon-right-triangle-arrow",mediaNext:"esri-media-next",nextIconLTR:"esri-next-icon-ltr esri-icon-right-triangle-arrow",nextIconRTL:"esri-next-icon-rtl esri-icon-left-triangle-arrow",
mediaSummary:"esri-popup-renderer-media-summary",mediaCount:"esri-popup-renderer-media-count",mediaImageSummary:"esri-popup-renderer-media-image-summary",mediaImageIcon:"esri-popup-renderer-media-image-icon esri-icon-media",mediaChartSummary:"esri-popup-renderer-media-chart-summary",mediaChartIcon:"esri-popup-renderer-MediaChartIcon esri-icon-chart",loading:"esri-popup-renderer-loading",loadingSpinnerContainer:"esri-popup-renderer-loading-container",loadingSpinner:"esri-icon esri-icon-loading-indicator esri-rotating",
showMediaPagination:"esri-popup-renderer-show-media-pagination",chart:"esri-chart"},A=/^\s*(https?:\/\/[^\s]+)\s*$/i;return u.createSubclass([y],{declaredClass:"esri.widgets.Popup.PopupRenderer",templateString:z,properties:{viewModel:{type:v}},baseClass:c.base,constructor:function(){this._charts=[];this._chartTooltips=[]},postCreate:function(){this.inherited(arguments);var a=this,d=this.viewModel;this.own(r.init(d,"waitingForContent",this._loadingSpinner.bind(this)),r.init(d,"content",this._render.bind(this)),
p(this._contentNode,p.selector("."+c.mediaNext,s),function(){a._nextMedia(this)}),p(this._contentNode,p.selector("."+c.mediaPrevious,s),function(){a._previousMedia(this)}))},destroy:function(){this._destroyCharts();this._clearResizeTimer()},_i18n:m,_css:c,resize:function(){this._resizeCharts();this.emit("resize")},_clearResizeTimer:function(){this._mediaResizeTimer&&(clearTimeout(this._mediaResizeTimer),this._mediaResizeTimer=0)},_countMediaInfos:function(a){var d=0,b=0;a.forEach(function(a){"image"===
a.type?d++:-1!==a.type.indexOf("chart")&&b++});return{total:b+d,images:d,charts:b}},_createMediaNodes:function(a){this._destroyCharts();var g=a.mediaIndex,b=a.mediaInfos[g];a=a.node;d.empty(a);var e=d.create("div",{className:c.mediaItem},a),g=this._createMediaType(b,g);d.place(g,e,"only");b.title&&d.create("div",{className:c.mediaItemTitle,innerHTML:b.title},a);b.caption&&d.create("div",{className:c.mediaItemCaption,innerHTML:b.caption},a);this._clearResizeTimer();this._mediaResizeTimer=setTimeout(function(){this.resize();
this._clearResizeTimer()}.bind(this),0)},_createMediaType:function(a,g){var b=a.value,e;if("image"===a.type){var f=d.create("img",{alt:a.title||"",src:b.sourceURL});b.linkURL?(e=d.create("a",{title:a.title||"",href:b.linkURL,target:this._preventNewTab(b.linkURL)?"":"_blank"}),d.place(f,e)):e=f}else-1!==a.type.indexOf("chart")&&(e=d.create("div",{className:c.chart},e),b=["dojox/charting/Chart2D","dojox/charting/action2d/Tooltip"],f=a.value.theme||this.chartTheme,"string"===typeof f&&(f=f.replace(/\./gi,
"/"),-1===f.indexOf("/")&&(f="dojox/charting/themes/"+f)),f||(f="dojox/charting/themes/Claro"),b.push(f),this._cancelChartModules(),this._chartsPromise=w.when(t,b).then(function(b){this._showChart(e,a.type,a.value,b[0],b[1],b[2]);this._chartsPromise=null}.bind(this)));return e},_cancelChartModules:function(){this._chartsPromise&&this._chartsPromise.cancel()},_destroyCharts:function(){this._cancelChartModules();var a;if(this._chartTooltips&&this._chartTooltips.length)for(a=0;a<this._chartTooltips.length;a++)this._chartTooltips[a].destroy();
this._chartTooltips.length=0;if(this._charts&&this._charts.length)for(a=0;a<this._charts.length;a++)this._charts[a].destroy();this._charts.length=0},_loadingSpinner:function(a){k.toggle(this.domNode,c.loading,!!a)},_nextMedia:function(a){this._pageMedia(a,"next")},_pageMedia:function(a,d){var b,e=x.get(a,"data-element-index");e&&(b=parseInt(e,10),b=this._elementInfo[b]);if(b){var e=b.mediaInfos,c=b.mediaIndex;"previous"===d?c--:c++;e&&e.length&&(c=(c+e.length)%e.length);b.mediaIndex=c;this._createMediaNodes(b)}},
_preventNewTab:function(a){return(a=a&&q.trim(a).toLowerCase())&&(0===a.indexOf("mailto:")||0===a.indexOf("tel:"))},_previousMedia:function(a){this._pageMedia(a,"previous")},_render:function(a){this._elementInfo=[];this._destroyCharts();d.empty(this._contentNode);var c=this.viewModel;a&&("string"===typeof a?(a=this._renderText({type:"text",text:a}))&&d.place(a,this._contentNode,"only"):Array.isArray(a)&&a.forEach(function(a,e){var f;switch(a.type){case c.contentTypes.attachments:f=this._renderAttachments(a,
e);break;case c.contentTypes.fields:f=this._renderFields(a,e);break;case c.contentTypes.media:f=this._renderMedia(a,e);break;case c.contentTypes.text:f=this._renderText(a,e)}f&&d.place(f,this._contentNode,0===e?"only":"last")},this));this.resize()},_renderAttachments:function(a,g){var b,e=a.attachmentInfos;if(e&&e.length){b=d.create("div");k.add(b,[c.attachments,c.contentElement]);d.create("div",{className:c.attachmentsTitle,textContent:m.attach},b);var f=d.create("ul",{},b);e.forEach(function(a){var b=
d.create("li",{},f),b=d.create("a",{href:a.url,target:"_blank"},b);d.create("span",{className:c.attachmentsItemIcon},b);d.create("span",{className:c.attachmentsItem,textContent:a.name||m.noTitle},b)},this)}return b},_renderFields:function(a,g){var b=this.viewModel,e,f=b.graphic.getEffectivePopupTemplate();if(f=a.fieldInfos||f&&f.fieldInfos){var h=b.formattedAttributes;e=d.create("div");k.add(e,[c.fields,c.contentElement]);var b=d.create("table",{summary:m.fieldsSummary},e),l=d.create("tbody",{},b);
f.forEach(function(a){if(a.visible){var b=a.fieldName;a=a.label||b;var b=h[b]||"",c;b&&"string"===typeof b&&(c=b.replace(A,'\x3ca target\x3d"_blank" href\x3d"$1" title\x3d"'+a+'"\x3e'+m.view+"\x3c/a\x3e"));var e=d.create("tr",{},l),f=a,g=b;c&&c!==b&&(f=a,g=c);d.create("th",{innerHTML:f},e);d.create("td",{innerHTML:g},e)}},this)}return e},_renderMedia:function(a,g){var b,e=a.mediaInfos;if(e&&e.length){var f=this._countMediaInfos(e),h={tabIndex:"0",role:"button"};h["data-element-index"]=g;b=d.create("div");
k.add(b,[c.media,c.contentElement]);k.toggle(b,c.showMediaPagination,1<f.total);var l=d.create("ul",{className:c.mediaSummary},b),n=d.create("li",{className:c.mediaImageSummary},l);d.create("span",{className:c.mediaCount,"aria-label":m.numImages,textContent:"("+f.images+")"},n);d.create("span",{"aria-hidden":!0,className:c.mediaImageIcon},n);l=d.create("li",{className:c.mediaImageSummary},l);d.create("span",{className:c.mediaCount,"aria-label":m.numCharts,textContent:"("+f.charts+")"},l);d.create("span",
{"aria-hidden":!0,className:c.mediaChartIcon},l);f=d.create("div",{className:c.mediaContainer},b);l=d.create("div",q.mixin({title:m.previous},h),f);k.add(l,[c.btn,c.mediaPrevious]);n=d.create("span",{"aria-hidden":!0},l);k.add(n,[c.icon,c.previousIconLTR]);n=d.create("span",{"aria-hidden":!0},l);k.add(n,[c.icon,c.previousIconRTL]);d.create("span",{className:c.iconText,textContent:m.previous},l);e={mediaIndex:0,node:d.create("div",{className:c.mediaItemContainer},f),mediaInfos:e};this._elementInfo[g]=
e;this._createMediaNodes(e);h=d.create("div",q.mixin({title:m.next},h),f);k.add(h,[c.btn,c.mediaNext]);e=d.create("span",{"aria-hidden":!0},h);k.add(e,[c.icon,c.nextIconLTR]);e=d.create("span",{"aria-hidden":!0},h);k.add(e,[c.icon,c.nextIconRTL]);d.create("span",{className:c.iconText,textContent:m.next},h)}return b},_renderText:function(a,g){var b;a&&a.text&&(b=d.create("div",{innerHTML:a.text}),k.add(b,[c.text,c.contentElement]));return b},_resizeCharts:function(){if(this._charts&&this._charts.length)for(var a=
0;a<this._charts.length;a++){var c=this._charts[a],b=c.node;b&&(b.offsetWidth&&b.offsetHeight)&&c.resize()}},_showChart:function(a,c,b,d,f,h){a=new d(a,{margins:{l:4,t:4,r:4,b:4}});h&&a.setTheme(h);switch(c){case "pie-chart":a.addPlot("default",{type:"Pie",labels:!1});a.addSeries("Series A",b.fields);break;case "line-chart":a.addPlot("default",{type:"Markers"});a.addAxis("x",{min:0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1});a.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});
b.fields.forEach(function(a,b){a.x=b+1});a.addSeries("Series A",b.fields);break;case "column-chart":a.addPlot("default",{type:"Columns",gap:3});a.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});a.addSeries("Series A",b.fields);break;case "bar-chart":a.addPlot("default",{type:"Bars",gap:3}),a.addAxis("x",{includeZero:!0,fixUpper:"minor",minorLabels:!1}),a.addAxis("y",{vertical:!0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1}),a.addSeries("Series A",b.fields)}c=new f(a);a.render();
this._charts.push(a);this._chartTooltips.push(c)}})});