// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../PopupTemplate ../../core/Accessor ../../core/Collection ../../core/Evented ../../core/HandleRegistry ../../core/promiseUtils ../../core/watchUtils dojo/fx/easing dojo/_base/lang".split(" "),function(g,h,k,l,m,n,p,e,q){var f={id:"zoom-to"};return h.createSubclass([l],{declaredClass:"esri.widgets.Popup.PopupViewModel",properties:{actions:{type:k.ofType(g.Action)},animationOptions:{},content:{},featureCount:{readOnly:!0},features:{},location:{},pendingPromisesCount:{readOnly:!0},promises:{},
selectedFeature:{readOnly:!0},selectedFeatureIndex:{},state:{readOnly:!0},title:{},updateLocationEnabled:{},view:{},waitingForResult:{dependsOn:["pendingPromisesCount","featureCount"],readOnly:!0},zoomFactor:{},zoomScale:{readOnly:!0}},_handles:null,constructor:function(){this._handles=new m},getDefaults:function(a){return q.mixin(this.inherited(arguments),{actions:[f],animationOptions:{duration:300,easing:e.quadInOut},promises:[]})},initialize:function(){this._handles.add(p.init(this,"view.scale",
this._scaleWatcher))},destroy:function(){this._handles.destroy();this.view=this._handles=null},actions:[f],animationOptions:{duration:300,easing:e.quadInOut},content:null,featureCount:0,features:null,_featuresSetter:function(a){this._set("features",a);this._updateFeatureCount(a);this.pendingPromisesCount||(this.selectedFeatureIndex=-1,a.length&&(this.selectedFeatureIndex=0))},location:null,pendingPromisesCount:0,waitingForResult:!1,_waitingForResultGetter:function(){return 0<this.pendingPromisesCount&&
0===this.featureCount},promises:[],_promisesSetter:function(a){var b=this._get("promises");b&&b.forEach(function(a){a.cancel()});this.features=[];this._set("pendingPromisesCount",0);this._set("promises",a);a&&a.length&&(this._set("pendingPromisesCount",a.length),a=a.slice(0),a.forEach(function(a){a.always(function(b){a.isCanceled()||(this._set("pendingPromisesCount",this.pendingPromisesCount-1),this._updateFeatures(a,b))}.bind(this))},this))},selectedFeature:null,selectedFeatureIndex:-1,_selectedFeatureIndexSetter:function(a){if(isNaN(a)||
-1>a)a=-1;var b=null,c=this.features;c&&c.length&&(a=(a+c.length)%c.length,b=c[a]);this._set("selectedFeature",b);this._set("selectedFeatureIndex",a);this._selectedFeatureChange(b,this.updateLocationEnabled)},_stateGetter:function(){this._set("state",this.get("view.ready")?"ready":"disabled")},title:"",updateLocationEnabled:!1,_updateLocationEnabledSetter:function(a){this._selectedFeatureChange(this.selectedFeature,a);this._set("updateLocationEnabled",a)},view:null,zoomFactor:4,_zoomFactorSetter:function(a){var b=
this.view;b&&this._setZoomScale(b.scale,a);this._set("zoomFactor",a)},zoomScale:0,centerAtLocation:function(){if(this.location&&this.view)return this.view.goTo({target:this.location,scale:this.view.scale},this.animationOptions)},clear:function(){this.set({promises:[],features:[],content:null,title:null,location:null})},triggerAction:function(a){(a=this.actions.getItemAt(a))&&this.emit("trigger-action",{action:a})},next:function(){this.selectedFeatureIndex+=1;return this},previous:function(){this.selectedFeatureIndex-=
1;return this},zoomToLocation:function(){var a=this.view;if(a){var b=this.selectedFeature,c=b&&b.geometry,d=b&&b.symbol&&"3d"===a.type;c||d?(d={target:b},c&&("point"===c.type&&this._isScreenSize(b))&&(d.scale=this.zoomScale,this.location=c)):d={target:this.location,scale:this.zoomScale};return a.goTo(d,this.animationOptions)}return n.resolve()},_isScreenSize:function(a){if("3d"!==this.view.type||"esri.Graphic"!==a.declaredClass)return!0;var b=!0,c=this.view.getViewForGraphic(a);c&&c.whenGraphicBounds&&
c.whenGraphicBounds(a).then(function(a){b=!a||a[0]===a[3]&&a[1]===a[4]&&a[2]===a[5]});return b},_getSelectedFeatureActions:function(){this._originalActions&&(this.actions=this._originalActions,this._originalActions=null);var a=this.actions.filter(function(a){return!a.temporary},this),b=a,c=this.selectedFeature.getEffectivePopupTemplate();if(c&&c.actions){for(var b=c.actions,d=0;d<b.length;d++)b.getItemAt(d).temporary=!0;c.overwriteActions?this._originalActions=a:b=a.concat(b)}this.actions=b},_scaleWatcher:function(a){this._setZoomScale(a,
this.zoomFactor)},_getPointFromGeometry:function(a){switch(a&&a.type){case "point":return a;case "extent":return a.center;case "polygon":return a.centroid;case "multipoint":case "polyline":return a.extent.center;default:return null}},_selectedFeatureChange:function(a,b){a&&(b&&(this.location=this._getPointFromGeometry(this.selectedFeature.geometry)),this._getSelectedFeatureActions())},_updateFeatureCount:function(a){var b=0;a&&a.length&&(b=a.length);this._set("featureCount",b)},_setZoomScale:function(a,
b){this._set("zoomScale",a/b)},_updateFeatures:function(a,b){if(a&&this.promises)if(!this._validatePromise(a)||b instanceof Error)console.error(this.declaredClass+":: Invalid promise");else if(b&&b.length){var c={};if(!this.features||!this.features.length)c.features=b,c.selectedFeatureIndex=0;else{var d=b.filter(function(a){return-1===this.features.indexOf(a)},this);c.features=this.features.concat(d)}this.set(c)}},_validatePromise:function(a){return-1<this.promises.indexOf(a)}})});