// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../../core/Accessor ../../core/HandleRegistry ../../core/lang ../../core/urlUtils ../../core/promiseList ../../core/promiseUtils ../../core/watchUtils ../../request ../../tasks/support/StatisticDefinition ../../tasks/support/Query ../../tasks/QueryTask dojo/_base/lang dojo/Deferred dojo/promise/all dojo/i18n!dojo/cldr/nls/number".split(" "),function(A,B,h,C,D,r,w,x,E,y,F,q,J,v,z){var G=/\'/g,H=/href\s*=\s*(?:\"([^\"]+)\"|\'([^\']+)\')/ig,I=/(\{([^\{\r\n]+)\})/g,n={attachments:"attachments",
fields:"fields",media:"media",text:"text"},t={"short-date":"(datePattern: 'M/d/y', selector: 'date')","short-date-le":"(datePattern: 'd/M/y', selector: 'date')","long-month-day-year":"(datePattern: 'MMMM d, y', selector: 'date')","day-short-month-year":"(datePattern: 'd MMM y', selector: 'date')","long-date":"(datePattern: 'EEEE, MMMM d, y', selector: 'date')","short-date-short-time":"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')","short-date-le-short-time":"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",
"short-date-short-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')","short-date-le-short-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')","short-date-long-time":"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')","short-date-le-long-time":"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')","short-date-long-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",
"short-date-le-long-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')","long-month-year":"(datePattern: 'MMMM y', selector: 'date')","short-month-year":"(datePattern: 'MMM y', selector: 'date')",year:"(datePattern: 'y', selector: 'date')"};return A.createSubclass({declaredClass:"esri.widgets.Popup.PopupRendererViewModel",properties:{content:{readOnly:!0},contentEnabled:!0,contentTypes:{readOnly:!0},formattedAttributes:{readOnly:!0},graphic:{},title:{readOnly:!0},
waitingForContent:{readOnly:!0}},constructor:function(){this._handles=new B},initialize:function(){this._handles.add([w.init(this,"graphic",function(a){this._updateGraphic(a,this.contentEnabled)}.bind(this)),w.init(this,"contentEnabled",function(a){this._updateGraphic(this.graphic,a)}.bind(this))])},destroy:function(){this._handles.destroy();this._handles=null;this._clearRelatedInfo();this._cancelPromises();this.graphic=null;this._set("title",null);this._set("content",null);this._set("waitingForContent",
null)},content:null,contentEnabled:!0,contentTypes:n,formattedAttributes:null,graphic:null,title:"",waitingForContent:!1,_handles:null,_contentPromise:null,_contentPromiseLookup:null,_relatedRecordsPromise:null,_relatedRecordsQueryPromises:[],_relatedRecordsLayerPromises:[],_relatedLayersInfo:null,_relatedInfo:null,_dateFormats:t,_addValuesToHref:function(a,b,c,d){b=this._trimString(b);return h.substitute(b&&0===b.indexOf("${")?c:d,a)},_cancelPromises:function(){this._contentPromiseLookup&&(Object.keys(this._contentPromiseLookup).forEach(function(a){this._contentPromiseLookup[a].cancel()},
this),this._contentPromiseLookup=null);this._contentPromise&&(this._contentPromise.cancel(),this._contentPromise=null);this._relatedRecordsQueryPromises.forEach(function(a){a.cancel()});this._relatedRecordsQueryPromises.length=0;this._relatedRecordsLayerPromises.length&&(this._relatedRecordsLayerPromises.forEach(function(a){a.cancel()}),this._relatedRecordsLayerPromises.length=0);this._relatedRecordsPromise&&(this._relatedRecordsPromise.cancel(),this._relatedRecordsPromise=null)},_clearRelatedInfo:function(){this._relatedInfo=
this._relatedLayersInfo=null},_compileContent:function(a,b){var c=a.content;if("string"===typeof c)return this._compileText(a,{type:n.text,text:c}).text;if(Array.isArray(c))return c.map(function(c,d){switch(c.type){case n.attachments:return this._proxyAttachments(c,b&&b[d]);case n.fields:return c;case n.media:return this._compileMedia(a,c);case n.text:return this._compileText(a,c)}},this);try{throw Error(this.declaredClass+"::invalid content type.");}catch(d){console.warn(d.stack)}},_compileMedia:function(a,
b){var c=q.clone(b),d=c.mediaInfos,f=a.attributes,e=a.layer,k=this.formattedAttributes,g=a.substOptions,l,m;d&&(l=[],d.forEach(function(c){m=0;var b=c.value;switch(c.type){case "image":var d=b.sourceURL,d=d&&this._trimString(h.substitute(f,this._fixTokens(d,e)));m=!!d;break;case "pie-chart":case "line-chart":case "column-chart":case "bar-chart":var s,d=b.normalizeField;b.fields=b.fields.map(function(a){return(s=this._getLayerFieldInfo(e,a))?s.name:a},this);d&&(s=this._getLayerFieldInfo(e,d),b.normalizeField=
s?s.name:d);m=b.fields.some(function(a){return h.isDefined(f[a])||-1!==a.indexOf("relationships/")&&this._relatedInfo},this);break;default:return}if(m){c=q.clone(c);var b=c.value,d=c.title?this._processFieldsInLinks(this._fixTokens(c.title,e),f):"",p=c.caption?this._processFieldsInLinks(this._fixTokens(c.caption,e),f):"";c.title=d?this._trimString(h.substitute(k,d,g)):"";c.caption=p?this._trimString(h.substitute(k,p,g)):"";if("image"===c.type)b.sourceURL=h.substitute(f,this._fixTokens(b.sourceURL,
e)),b.linkURL&&(b.linkURL=this._trimString(h.substitute(f,this._fixTokens(b.linkURL,e))));else{var u,n=(d=a.template)&&d.fieldInfos;b.fields.forEach(function(a,c){if(-1!==a.indexOf("relationships/")){var d=this._getRelatedChartInfos(e,n,a,b,f,g);Array.isArray(d)?b.fields=d:b.fields[c]=d}else{d=f[a];d=void 0===d?null:d;u=f[b.normalizeField]||0;d&&u&&(d/=u);var k=n&&this._getFieldInfo(n,a);b.fields[c]={y:d,tooltip:(k&&k.label||a)+":"+this._formatValue(n,d,a,g,!!u)}}},this)}l.push(c)}},this));c.mediaInfos=
l;return c},_compileText:function(a,b){var c=q.clone(b);if(c&&c.text){var d=a.attributes,f=this.formattedAttributes,e=a.substOptions,d=this._processFieldsInLinks(this._fixTokens(c.text,a.layer),d);c.text=this._trimString(h.substitute(f,d,e))}return c},_compileTitle:function(a){var b="",c=a.title,d=a.layer,f=a.attributes;a=a.substOptions;var e=this.formattedAttributes;c&&-1===c.indexOf("{relationships/")&&(b=this._processFieldsInLinks(this._fixTokens(c,d),f),b=this._trimString(h.substitute(e,b,a)));
return b},_createGraphicInfo:function(a,b){var c=a.getEffectivePopupTemplate(),d=c&&c.title,f=c&&c.content,e=a.layer,k=e&&e._getDateOpts&&e._getDateOpts().properties,g=q.clone(a.attributes)||{};return{graphic:a,template:c,title:d,content:f,contentEnabled:b,layer:e,attributes:g,properties:k,substOptions:{dateFormat:{properties:k,formatter:"DateFormat"+t["short-date-short-time"]}}}},_fixTokens:function(a,b){return a.replace(I,function(a,d,f){return(a=this._getLayerFieldInfo(b,f))?"{"+a.name+"}":d}.bind(this))},
_encodeAttributes:function(a){var b=q.clone(a)||{};Object.keys(b).forEach(function(a){var d=b[a];"string"===typeof d&&(d=encodeURIComponent(d).replace(G,"\x26apos;"),b[a]=d)});return b},_formatAttributes:function(a){var b=a.graphic,c=a.template,d=a.attributes,f=a.layer,e=a.substOptions,k=a.properties,g=c&&c.fieldInfos,l=q.clone(d);this._relatedInfo&&Object.keys(this._relatedInfo).forEach(function(a){var c=this._relatedInfo[a];a=this._relatedLayersInfo[a];c&&(c.relatedFeatures.forEach(this._relatedFeaturesAttributes.bind(this,
a,d,l)),c.relatedStatsFeatures.forEach(this._relatedStatsAttributes.bind(this,a,d,l)))},this);g&&g.forEach(function(a){var c=a.fieldName,b=this._getLayerFieldInfo(f,c);b&&(c=a.fieldName=b.name);l[c]=this._formatValue(g,l[c],c,e);k&&(a.format&&a.format.dateFormat)&&(a=k.indexOf(c),-1<a&&k.splice(a,1))},this);if(f){var m=f.typeIdField;Object.keys(d).forEach(function(a){if(-1===a.indexOf("relationships/")){var c=d[a];if(h.isDefined(c)){var e=this._getDomainName(f,b,a,c);h.isDefined(e)?l[a]=e:a===m&&
(c=this._getTypeName(f,b,c),h.isDefined(c)&&(l[a]=c))}}},this)}return l},_formatValue:function(a,b,c,d,f){var e=a&&this._getFieldInfo(a,c);a=e&&e.format;c="number"===typeof b&&d.dateFormat.properties&&-1===d.dateFormat.properties.indexOf(c)&&(!a||!a.dateFormat);if(!h.isDefined(b)||!e||!h.isDefined(a))return c?this._forceLTR(b):b;var k="",g=[],e=a.hasOwnProperty("places")||a.hasOwnProperty("digitSeparator"),l=a.hasOwnProperty("digitSeparator")?a.digitSeparator:!0;if(e)k="NumberFormat",g.push("places: "+
(h.isDefined(a.places)&&(!f||0<a.places)?Number(a.places):"Infinity")),g.length&&(k+="("+g.join(",")+")");else if(a.dateFormat)k="DateFormat"+t[a.dateFormat]||t["short-date-short-time"];else return c?this._forceLTR(b):b;b=h.substitute({myKey:b},"{myKey:"+k+"}",d)||"";e&&!l&&z.group&&(b=b.replace(RegExp("\\"+z.group,"g"),""));return c?this._forceLTR(b):b},_forceLTR:function(a){return"\x26lrm;"+a},_getDomainName:function(a,b,c,d){return(a=a.getDomain&&a.getDomain(c,{feature:b}))&&a.codedValues?a.getName(d):
null},_getFieldInfo:function(a,b){for(var c=b.toLowerCase(),d,f=0;f<a.length;f++){var e=a[f];if(e.fieldName&&e.fieldName.toLowerCase()===c){d=e;break}}return d},_getLayerFieldInfo:function(a,b){return a&&a.getField?a.getField(b):null},_getTypeName:function(a,b){var c=a.getType&&a.getType(b);return c&&c.name},_processFieldsInLinks:function(a,b){var c=this._encodeAttributes(b);a&&(a=a.replace(H,function(a,f){return this._addValuesToHref(a,f,b,c)}.bind(this)));return a},_proxyAttachments:function(a,
b){var c=q.clone(a);if(b&&!(b instanceof Error)&&b.attachmentInfos&&b.attachmentInfos.length){var d=b.attachmentInfos.map(function(a){a.url=C.addProxy(a.url);return a},this);c.attachmentInfos=d}return c},_queryAttachments:function(a){var b=a.layer,c=a.attributes;a=b&&b.objectIdField;c=c&&a&&c[a];if(a&&b.hasAttachments&&c)return this._queryAttachmentInfos(b,c)},_queryAttachmentInfos:function(a,b){var c=a.url+"/"+a.layerId+"/"+b+"/attachments",d=a.token||"";return x(c,{query:{f:"json",token:d},callbackParamName:"callback"}).then(function(a){a=
a.data;a.attachmentInfos.forEach(function(a){a.url=c+"/"+a.id;d&&(a.url+="?token\x3d"+d);a.objectId=b});return a})},_queryContent:function(a){var b=a.template,b=b&&b.content;if(!b||"string"===typeof b)return r.resolve();if(!Array.isArray(b))return r.reject(Error(this.declaredClass+"::Invalid content type."));var c={};b.forEach(function(b,f){b.type===n.attachments&&(c[f]=this._queryAttachments(a))},this);if(0===Object.keys(c).length)return r.resolve();this._contentPromiseLookup=c;return D(c).always(function(a){this._contentPromiseLookup=
null;return a}.bind(this))},_trimString:function(a){return(a||"").trim()},_updateContent:function(a){if(a.contentEnabled){var b=this._queryContent(a).then(function(c){this._set("content",this._compileContent(a,c))}.bind(this),function(a){console.log(this.declaredClass+"::error loading template",a)}.bind(this)).always(function(){this._contentPromise=null}.bind(this));return this._contentPromise=b}return r.resolve()},_updateGraphic:function(a,b){if(this._handles&&(this._clearRelatedInfo(),this._cancelPromises(),
this._set("title",""),this._set("content",null),this._set("formattedAttributes",null),this._set("waitingForContent",!1),a)){this._set("waitingForContent",!0);var c=this._createGraphicInfo(a,b);this._relatedRecordsPromise=this._checkForRelatedRecords(c).then(function(){this._set("formattedAttributes",this._formatAttributes(c));this._set("title",this._compileTitle(c));return this._updateContent(c)}.bind(this)).always(function(){this._relatedRecordsPromise=null;this._relatedRecordsLayerPromises.length=
0;this._relatedRecordsQueryPromises.length=0;this._set("waitingForContent",!1)}.bind(this))}},_getAllFieldInfos:function(a){var b=[],c=a.template,d=c&&c.fieldInfos;a=a.contentEnabled;d&&(b=b.concat(d));a&&(c=c&&c.content,Array.isArray(c)&&c.forEach(function(a){b=b.concat(a&&a.fieldInfos)},this));return b},_checkForRelatedRecords:function(a){var b=this._getAllFieldInfos(a).filter(function(a){return a&&a.fieldName&&-1!==a.fieldName.indexOf("relationships/")},this);return b&&0<b.length?this._getRelatedRecords({graphic:a.graphic,
fieldsInfo:b}):r.resolve()},_relatedFeaturesAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){if("esriRelCardinalityOneToOne"===a.relation.cardinality){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]}},this)},_relatedStatsAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]},this)},_getRelatedChartInfos:function(a,b,c,d,f,e){var k,g,l,m,h,n;k=[];n=
this._fromRelatedFieldName(c);h=n[0];g=this._relatedInfo[h];h=this._relatedLayersInfo[h];g&&g.relatedFeatures.forEach(function(g){var h=g.attributes,p;Object.keys(h).forEach(function(g){if(g===n[1]){p={};m=h[g];d.normalizeField&&(l=-1!==d.normalizeField.indexOf("relationships/")?h[this._fromRelatedFieldName(d.normalizeField)[1]]:f[d.normalizeField]);m&&l&&(m/=l);if(d.tooltipField)if(-1!==d.tooltipField.indexOf("relationships/"))g=this._fromRelatedFieldName(d.tooltipField)[1],p.tooltip=h[g]+": "+this._formatValue(b,
m,h[g],e,!!l);else{if(g=this._getLayerFieldInfo(a,c))c=g.name;p.tooltip=c+": "+this._formatValue(b,m,d.tooltipField,e,!!l)}else p.tooltip=m;p.y=m;k.push(p)}},this)},this);return"esriRelCardinalityOneToMany"===h.relation.cardinality||"esriRelCardinalityManyToMany"===h.relation.cardinality?k:k[0]},_getRelatedRecords:function(a){var b=a.graphic;return this._relatedLayersInfo?this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);return a}.bind(this)):this._getRelatedLayersInfo(a).then(function(a){Object.keys(a).forEach(function(b){a[b]&&
(this._relatedLayersInfo[b].relatedLayerInfo=a[b].data)},this);return this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);return a}.bind(this))}.bind(this))},_getRelatedLayersInfo:function(a){var b=a.fieldsInfo,c,d={};c=a.graphic.layer;this._relatedLayersInfo||(this._relatedLayersInfo={});b.forEach(function(a){var b,d,g;b=this._fromRelatedFieldName(a.fieldName);d=b[0];b=b[1];d&&(this._relatedLayersInfo[d]||(c.relationships.some(function(a){if(a.id==d)return g=a,!0}),g&&(this._relatedLayersInfo[d]=
{relation:g,relatedFields:[],outStatistics:[]})),this._relatedLayersInfo[d]&&(this._relatedLayersInfo[d].relatedFields.push(b),a.statisticType&&(a=new E({statisticType:a.statisticType,onStatisticField:b,outStatisticFieldName:b}),this._relatedLayersInfo[d].outStatistics.push(a))))},this);Object.keys(this._relatedLayersInfo).forEach(function(a){var b;this._relatedLayersInfo[a]&&(b=this._relatedLayersInfo[a].relation,b=c.url+"/"+b.relatedTableId,this._relatedLayersInfo[a].relatedLayerUrl=b,d[a]=x(b,
{query:{f:"json"},callbackParamName:"callback"}))},this);Object.keys(d).forEach(function(a){this._relatedRecordsLayerPromises.push(d[a])},this);return v(d)},_queryRelatedLayers:function(a){var b={};Object.keys(this._relatedLayersInfo).forEach(function(c){b[c]=this._queryRelatedLayer({graphic:a,relatedInfo:this._relatedLayersInfo[c]})},this);return v(b)},_queryRelatedLayer:function(a){var b,c,d,f,e,h,g,l,m;b=a.graphic;c=b.layer.layerId;g=a.relatedInfo;a=g.relatedLayerInfo;l=g.relatedLayerUrl;m=g.relation;
a&&a.relationships&&a.relationships.some(function(a){if(a.relatedTableId===parseInt(c,10))return d=a,!0});d&&(a.fields.some(function(a){if(a.name===d.keyField)return f=-1!==["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"].indexOf(a.type)?"number":"string",!0}),e="string"===f?d.keyField+"\x3d'"+b.attributes[m.keyField]+"'":d.keyField+"\x3d"+b.attributes[m.keyField],e=new y({where:e,outFields:g.relatedFields}),g.outStatistics&&(0<g.outStatistics.length&&
a.supportsStatistics)&&(h=new y({where:e.where,outFields:e.outFields,outStatistics:g.outStatistics})),a=new F({url:l}),e=[a.execute(e)],h&&e.push(a.execute(h)));this._relatedRecordsQueryPromises=this._relatedRecordsQueryPromises.concat(e);return v(e)},_setRelatedRecords:function(a){this._relatedInfo=[];Object.keys(a).forEach(function(b){if(a[b]){var c=a[b];this._relatedInfo[b]={relatedFeatures:c[0].features};h.isDefined(c[1])&&(this._relatedInfo[b].relatedStatsFeatures=c[1].features)}},this)},_fromRelatedFieldName:function(a){return-1!==
a.indexOf("relationships/")?a.split("/").slice(1):[]},_toRelatedFieldName:function(a){return a&&0<a.length?"relationships/"+a[0]+"/"+a[1]:""}})});