// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/widgets/RendererSlider/templates/RendererSlider.html":'\x3cdiv class\x3d"${_css.container}" data-dojo-attach-point\x3d"_containerNode"\x3e\r\n  \x3cdiv class\x3d"${_css.topLabelNode} ${_css.topLabelNodeHover}" data-dojo-attach-point\x3d"_topNode"\x3e\r\n    \x3cspan data-dojo-attach-point\x3d"_topNodeSpan"\x3e\x3c/span\x3e \r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"${_css.slidernode}" data-dojo-attach-point\x3d"_sliderNode"\x3e\r\n    \x3cdiv class\x3d"${_css.sliderarea}" data-dojo-attach-point\x3d"_sliderArea"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"${_css.sliderarearight}" data-dojo-attach-point\x3d"_sliderAreaRight"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"${_css.bottomLabelNode} ${_css.bottomLabelNodeHover}" data-dojo-attach-point\x3d"_botNode"\x3e\r\n    \x3cspan  data-dojo-attach-point\x3d"_bottomNodeSpan"\x3e\x3c/span\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("./Widget ../core/numberUtils ./RendererSlider/sliderUtils dijit/_TemplatedMixin dijit/form/NumberTextBox dojo/_base/array dojo/_base/lang dojo/dnd/move dojo/dom-construct dojo/dom-style dojo/dom-class dojo/debounce dojo/on dojo/text!./RendererSlider/templates/RendererSlider.html".split(" "),function(C,f,u,D,y,s,m,E,v,q,A,F,k,G){return C.createSubclass([D],{declaredClass:"esri.widgets.RendererSlider",templateString:G,_visibleLabels:["data","handle"],_roundedDataLabels:[],_roundedHandleLabels:[],
_ratioLabels:[],_minRatioLabel:"",_maxRatioLabel:"",_isZoomed:!1,_minZoomLabel:"",_maxZoomLabel:"",_maximumNumberEditor:null,_minimumNumberEditor:null,_valueDifferenceByIndex:[],_primaryHandleIdx:null,_currentTopValue:[],_isLTR:!0,_ctrlDown:!1,_histogramSurface:null,_css:null,_minPrecisionForSmallNumbers:3,loaded:!1,intermediateChanges:!1,type:null,minimum:0,maximum:100,values:[50],precision:2,handles:[],primaryHandle:null,showHandles:!0,showTicks:!0,showLabels:!0,showRatioLabels:!1,minLabel:null,
maxLabel:null,constructor:function(b,d){this.inherited(arguments);this.domNode=d;this._css={container:"esri-renderer-slider",slidernode:"esri-slider-node",sliderarea:"esri-slider-area",sliderarearight:"esri-slider-area-right",moveable:"esri-moveable",handler:"esri-handle",handlerSpan:"esri-handle-span",handlerContainer:"esri-handle-container",handlerLabel:"esri-handle-label",handlerLabelSpan:"esri-handle-label-span",topLabelNode:"esri-top-label-node",bottomLabelNode:"esri-bottom-label-node",topLabelNodeHover:"esri-top-label-node-hover",
bottomLabelNodeHover:"esri-bottom-label-node-hover",heatmapTick:"esri-heatmap-tick",handlerTick:"esri-handler-tick",handlerTickTop:"esri-handler-tick-top",handlerTickBottom:"esri-handler-tick-bottom"};this.set("showLabels",b.showLabels||this._visibleLabels);this._updateTimeout=F(this._updateTimeout,0)},startup:function(){this.inherited(arguments);this.set("_sliderHeight",q.get(this._sliderArea,"height")||200);this._checkMinMaxDefaults();this.set("_isLTR",this.isLeftToRight());if(!this._isLTR){var b=
q.get(this._sliderNode,"padding-left")+q.get(this._sliderNode,"padding-right"),d=Math.round(q.get(this._sliderNode,"width"));this.set("_sliderNodeWidth_RTL",b+d)}this.set("precision",u.getCombinedPrecision(this.minimum,this.maximum));this._updateRoundedLabels();this._generateMoveables();this._generateMinMaxEditors();this._generateCtrlKeyListener();this.watch("values",this._valuesChange);this.watch("minimum",this._updateTimeout);this.watch("maximum",this._updateTimeout);this.watch("showRatioLabels",
this._updateTimeout);this.set("loaded",!0);this.emit("load")},destroy:function(){this.inherited(arguments)},setValue:function(b,d,e){var g=this.get("values"),c=g.slice(0);"object"===typeof g[0]?c[b].value=d:c[b]=d;(this.intermediateChanges||e)&&this.set("values",c);e?this.emit("stop",{values:this.get("values")}):this.emit("slide",{values:c})},_updateTimeout:function(){this._updateSlider()},_updateSlider:function(){this._reset();this._checkMinMaxDefaults();this._updateRoundedLabels();this._generateMoveables();
this._generateMinMaxEditors();this._generateCtrlKeyListener()},_checkMinMaxDefaults:function(){var b=this.values,d;this.minimum===this.maximum&&(b&&0<b.length)&&(isNaN(b[0])?this.set({minimum:0,maximum:2*b[0].value}):this.set({minimum:0,maximum:2*b[0]}));b&&0<b.lenth&&(d=!isNaN(b[0])?b[0]:b[0].value,this.minimum>d&&this.set("minimum",d),b=!isNaN(b[b.length-1])?b[b.length-1]:b[b.length-1].value,this.maximum<b&&this.set("maximum",b))},_calculateValueFromHandlePosition:function(b){var d=this.get("minimum"),
e=this.get("maximum"),g=this.get("precision"),c=this.get("step")||Math.pow(10,-g);return 1>=d&&-1<=d&&1>=e&&-1<=e||g>=this._minPrecisionForSmallNumbers?(b*(e-d)+d)/c*c:parseFloat((Math.round((b*(e-d)+d)/c)*c).toFixed(g))},_generateMoveables:function(){var b,d=this._sliderNode,e=this._sliderHeight,g=this.get("minimum"),c=this.get("maximum"),n=this.get("showLabels"),a=this.get("showTicks"),r=m.hitch(this,this.setValue),k=this.get("values");this._updateMinMaxLabels();this.set("_primaryHandleIdx",null);
b=s.map(k,m.hitch(this,function(k,l){var p,B,t,w,h,x;k&&k.primaryHandle&&this.set("_primaryHandleIdx",l);if("object"===typeof k&&k.hidden)return null;"object"===typeof k&&(k=k.value);p=v.create("div",{style:this._getHandleStyleString(k),className:this._css.moveable},d);p.handleContainer=x=v.create("div",{className:this._css.handlerContainer},p);p.arrowSpan=w=v.create("span",{className:this._css.handlerSpan},x);p.handler=B=v.create("div",{className:this._css.handler},x);if("HeatmapSlider"!==this.type&&
(!0===n||"object"===typeof n&&-1!==s.indexOf(n,"handles")))t=this._generateHandleLabel(p,l);a&&this._generateHandleTicks(p,l);h=new E.constrainedMoveable(p,{handle:x,within:!0,constraints:m.hitch(this,function(){return{t:0,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:e}})});h.onMoveStart=m.hitch(this,function(d){var a=this.handles,c=s.indexOf(a,l),g,f;this._currentTopValue[l]=d.node.style.top;p.labelNode&&p.labelNode._autoPositioned&&(q.set(p.labelNode,"top","3px"),p.labelNode._autoPositioned=
!1);u._autoPositionHandleLabels(this.get("moveables"));p._numberEditor&&(p._numberEditor.destroy(),p._numberEditor=null);this._primaryHandleIdx!==l?(0<a.length?(d=null!==a[c-1]?a[c-1]:null,a=null!==a[c+1]?a[c+1]:null,c=b[d],a=b[a]):(c=b[l-1],a=b[l+1]),c&&a?(c=c.style.top,a=a.style.top,g=Number(c.replace("px","")),f=Number(a.replace("px","")),h.constraints=m.hitch(this,function(){return{t:f+2,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:e-f-(e-g+4)}})):c?(c=c.style.top,g=Number(c.replace("px","")),
h.constraints=m.hitch(this,function(){return{t:0,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:e-(e-g+2)}})):a&&(a=a.style.top,f=Number(a.replace("px","")),h.constraints=m.hitch(this,function(){return{t:f+2,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:e-(f+2)}}))):(0<a.length?(d=null!==a[c-1]?a[c-1]:null,a=null!==a[c+1]?a[c+1]:null,c=b[d],a=b[a]):(c=b[l-1],a=b[l+1]),c&&a&&(c=c.style.top,a=a.style.top,g=Number(c.replace("px","")),f=Number(a.replace("px","")),h.constraints=m.hitch(this,function(){return{t:2,
l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:e-4}})))});h.onMoved=m.hitch(this,function(a){var d,h,k,n,p;l===this._primaryHandleIdx&&(k=Number(this._currentTopValue[l].replace("px",""))-Number(a.node.style.top.replace("px","")),this._currentTopValue[l]=a.node.style.top,s.forEach(b,m.hitch(this,function(a,b){a&&b!==l&&(n=Number(a.style.top.replace("px","")),p=n-k,d=1-Number(p/e),h=this._calculateValueFromHandlePosition(d),h<g||h>c||(q.set(a,"top",p+"px"),r(b,h,!1),a.labelNode&&(a.labelNode.spanNode.innerHTML=
this.showRatioLabels?this._getLabelValueFromIndex(b):f.format(h.toFixed(6)))))})));d=1-Number(a.node.style.top.replace("px",""))/e;h=this._calculateValueFromHandlePosition(d);null!==this._primaryHandleIdx&&(l!==this._primaryHandleIdx&&this._ctrlDown)&&(k=Number(this._currentTopValue[l].replace("px",""))-Number(a.node.style.top.replace("px","")),this._currentTopValue[l]=a.node.style.top,0===l?(n=Number(b[b.length-1].style.top.replace("px","")),a=n+k,a>e&&(a=e),0>a&&(a=0),q.set(b[b.length-1],"top",
a+"px"),a=1-a/e,a=this._calculateValueFromHandlePosition(a),r(b.length-1,a,!1),b[b.length-1].labelNode&&(b[b.length-1].labelNode.spanNode.innerHTML=f.format(a.toFixed(6)))):l===b.length-1&&(n=Number(b[0].style.top.replace("px","")),a=n+k,a>e&&(a=e),0>a&&(a=0),q.set(b[0],"top",a+"px"),a=1-a/e,a=this._calculateValueFromHandlePosition(a),r(0,a,!1),b[0].labelNode&&(b[0].labelNode.spanNode.innerHTML=f.format(a.toFixed(6)))));r(l,h,!1);this._updateRoundedLabels();t&&(a=f.format(parseFloat(f.round([h,parseFloat(this._getLabelValueFromIndex(l,
!0))])[0]).toFixed(this.precision)),t.spanNode.innerHTML=this.showRatioLabels?this._getLabelValueFromIndex(l):a);u._autoPositionHandleLabels(this.get("moveables"))});h.onMoveStop=m.hitch(this,function(a){a=Number(a.node.style.top.replace("px",""));a=this._calculateValueFromHandlePosition(1-a/e);r(l,a,!0);this._updateRoundedLabels();t&&(a=f.format(parseFloat(f.round([a,parseFloat(this._getLabelValueFromIndex(l,!0))])[0]).toFixed(this.precision)),t.spanNode.innerHTML=this.showRatioLabels?this._getLabelValueFromIndex(l):
a);u._autoPositionHandleLabels(this.get("moveables"))});this.showHandles||(q.set(B,"display","none"),q.set(w,"display","none"));return p}));this.set("moveables",b);u._autoPositionHandleLabels(this.get("moveables"))},_reset:function(){s.forEach(this.moveables,m.hitch(this,function(b){b&&b.parentElement.removeChild(b)}));this.moveables=[]},_getHandleStyleString:function(b){var d=this.get("minimum"),e=this.get("maximum");return"top: "+Math.round((1-(b-d)/(e-d))*this._sliderHeight)+"px; "+("left: "+(this._isLTR?
0:this._sliderNodeWidth_RTL)+"px;")},_generateHandleTicks:function(b,d){var e=this._css,f=e.handlerTick+" "+e.handlerTickTop,c=e.handlerTick+" "+e.handlerTickBottom,f=0===d?c:f;"HeatmapSlider"===this.type&&(f+=e.heatmapTick);b.tick=v.create("div",{className:f},b)},_updateLabels:function(){this._updateMinMaxLabels();this._updateRoundedLabels()},_resetLabelPositions:function(){s.forEach(this.moveables,function(b){if(b){var d=b.labelNode;d&&(q.set(d,"top","3px"),b.labelNode._autoPositioned=!1)}})},_generateHandleLabel:function(b,
d){var e,f;e=v.create("div",{className:this._css.handlerLabel},b);f=v.create("span",{className:this._css.handlerLabelSpan,innerHTML:this._getLabelValueFromIndex(d)},e);e.spanNode=f;b.labelNode=e;k(e,"click",m.hitch(this,function(){this._generateHandleLabelEditor(b,d)}));return e},_updateMinMaxLabels:function(){var b=this.minimum,d=this.maximum,e=this.showLabels,g=this.minLabel,c=this.maxLabel,n=this._topNodeSpan,a=this._bottomNodeSpan,r=this._isZoomed,k=this._maxZoomLabel,m=this._minZoomLabel,l=this.showRatioLabels,
p=this._maxRatioLabel,q=this._minRatioLabel,t=this._roundedDataLabels;!1===e||"object"===typeof e&&-1===s.indexOf(e,"data")?(n.innerHTML="",a.innerHTML=""):r?l?(n.innerHTML=p,a.innerHTML=q):(n.innerHTML=f.format(k),a.innerHTML=f.format(m)):l?(n.innerHTML=p,a.innerHTML=q):(r=isNaN(g)?g:f.round([g,c])[0],e=isNaN(c)?c:f.round([g,c])[1],g=isNaN(r)||null===r?g:f.format(r),c=isNaN(e)||null===e?c:f.format(e),b=f.format(t[0])||f.format(b),d=f.format(t[1])||f.format(d),n.innerHTML=c||d,a.innerHTML=g||b)},
_updateRoundedLabels:function(){this._roundedDataLabels=f.round([this.minimum,this.maximum]);switch(this.type){case "SizeInfoSlider":case "ClassedSizeSlider":case "ClassedColorSlider":this._roundedHandleLabels=f.round(this.values);break;case "ColorInfoSlider":case "OpacitySlider":this._roundedHandleLabels=f.round(this._getValuesFromObject(this.values))}this._updateRatioLabels()},_updateRatioLabels:function(){var b=this.get("showRatioLabels"),d=this.get("minimum"),e=this.get("maximum"),g=this._getValuesFromObject(this.values),
c=[],k,a;!1!==b&&("percent"!==b&&"percentTotal"!==b?this.set("showRatioLabels",!1):("percent"===b?(s.forEach(g,function(a){c.push(this._getRatioFromValue(a))},this),k=f.format(this._getRatioFromValue(d).toFixed(2)),a=f.format(this._getRatioFromValue(e).toFixed(2))):"percentTotal"===b&&(s.forEach(g,function(a){c.push(this._getRatioFromValue(a))},this),k=f.format(this._getRatioFromValue(d).toFixed(2)),a=f.format(this._getRatioFromValue(e).toFixed(2))),this.set({_ratioLabels:c,_minRatioLabel:k+"%",_maxRatioLabel:a+
"%"})))},_generateMinMaxEditors:function(){!this.showLabels||"object"===typeof this.showLabels&&-1===s.indexOf(this.showLabels,"data")||"HeatmapSlider"===this.type?(A.remove(this._topNode,this._css.topLabelNodeHover),A.remove(this._botNode,this._css.bottomLabelNodeHover)):(k(this._topNode,"click",m.hitch(this,this._generateMaxEditor)),k(this._botNode,"click",m.hitch(this,this._generateMinEditor)))},_generateMaxEditor:function(){if((!this._maximumNumberEditor||!this._topLabelNode)&&!this._isZoomed){var b=
this.get("minLabel"),d=this.get("maxLabel"),e=this.get("maximum"),g,c;this._topNodeSpan.innerHTML="";this._topLabelNode=v.create("input",{type:"text"},this._topNode);g=this.handles&&0<this.handles.length?this.values[this.handles[this.handles.length-1]]:this.values[this.values.length-1];"object"===typeof g&&(g=g.value);this.showRatioLabels&&(g=this._getLabelValueFromIndex(this.values.length-1,!0).replace("%",""),e=Number(this._maxRatioLabel.replace("%","")));this._maximumNumberEditor=c=new y({value:Number(e),
required:!0,constraints:{min:g,max:"percentTotal"===this.showRatioLabels?100:null,places:"0,20"}},this._topLabelNode);c.startup();c.focus();c.textbox.select();var n=!1;k(c,"keydown",m.hitch(this,function(a){!1!==n&&(c.validate=n);13===a.keyCode&&(a=c.get("value"),void 0===a&&(a=c.get("displayedValue")),a<=c.constraints.max&&a>=c.constraints.min?c.focusNode.blur():(n=c.validate,c.validate(!1),c.validate=function(){return!1}))}));k(c,"blur",m.hitch(this,function(){var a=isNaN(d)?d:f.round([b,d])[1],
a=isNaN(a)||null===a?d:f.format(a),c=f.format(this._roundedDataLabels[1])||f.format(e);this.showLabels||"object"===typeof this.showLabels&&-1!==s.indexOf(this.showLabels,"data")?this._topNodeSpan.innerHTML=this.showRatioLabels?this._maxRatioLabel:a||c:this._topNodeSpan.innerHTML="";this._maximumNumberEditor.destroy();this._maximumNumberEditor=null}));k(c,"change",m.hitch(this,function(a){var c;a<Number(g)||isNaN(a)||void 0===a?(a=isNaN(d)?d:f.round([b,d])[1],a=isNaN(a)||null===a?d:f.format(a),c=f.format(this._roundedDataLabels[1])||
f.format(e),this._topNodeSpan.innerHTML=this.showRatioLabels?this._maxRatioLabel:a||c):(c=this.showRatioLabels?this._getValueFromPercent(a):a,this._topNodeSpan.innerHTML=this.showRatioLabels?c:f.format(a),this.set("maximum",c),this._reset(),this._updateRoundedLabels(),this._generateMoveables(),this._generateMinMaxEditors(),this.emit("data-value-change",{min:this.minimum,max:this.maximum,values:m.clone(this.values)}))}))}},_generateMinEditor:function(){if((!this._minimumNumberEditor||!this._botLabelNode)&&
!this._isZoomed){var b=this.minLabel,d=this.maxLabel,e=this.minimum,g,c;this._bottomNodeSpan.innerHTML="";this._botLabelNode=v.create("input",{type:"text"},this._botNode);g=this.handles&&0<this.handles.length?this.values[this.handles[0]]:this.values[0];"object"===typeof g&&(g=g.value);this.showRatioLabels&&(g=this._getLabelValueFromIndex(0,!0).replace("%",""),e=Number(this._minRatioLabel.replace("%","")));this._minimumNumberEditor=c=new y({value:Number(e),required:!0,constraints:{max:g,min:"percentTotal"===
this.showRatioLabels?0:null,places:"0,20"}},this._botLabelNode);c.startup();c.focus();c.textbox.select();var n=!1;k(c,"keydown",m.hitch(this,function(a){!1!==n&&(c.validate=n);13===a.keyCode&&(a=c.get("value"),void 0===a&&(a=c.get("displayedValue")),a<=c.constraints.max&&a>=c.constraints.min?c.focusNode.blur():(n=c.validate,c.validate(!1),c.validate=function(){return!1}))}));k(c,"blur",m.hitch(this,function(){var a=isNaN(b)?b:f.round([b,d])[0],a=isNaN(a)||null===a?b:f.format(a),c=f.format(this._roundedDataLabels[0])||
f.format(e);this.showLabels||"object"===typeof this.showLabels&&-1!==s.indexOf(this.showLabels,"data")?this._bottomNodeSpan.innerHTML=this.showRatioLabels?this._minRatioLabel:a||c:this._bottomNodeSpan.innerHTML="";this._minimumNumberEditor.destroy();this._minimumNumberEditor=null}));k(c,"change",m.hitch(this,function(a){var c;a>Number(g)||isNaN(a)||void 0===a?(a=isNaN(b)?b:f.round([b,d])[0],a=isNaN(a)||null===a?b:f.format(a),c=f.format(this._roundedDataLabels[0])||f.format(e),this._bottomNodeSpan.innerHTML=
this.showRatioLabels?this._minRatioLabel:a||c):(c=this.showRatioLabels?this._getValueFromPercent(a):a,this._bottomNodeSpan.innerHTML=this.showRatioLabels?c:f.format(a),this.set("minimum",c),this._reset(),this._updateRoundedLabels(),this._generateMoveables(),this._generateMinMaxEditors(),this.emit("data-value-change",{min:this.minimum,max:this.maximum}))}))}},_generateHandleLabelEditor:function(b,d){if(!b._numberEditor){var e=this.get("handles"),f=this.get("maximum"),c=this.get("minimum"),n=this.get("_isZoomed"),
a=this.get("values"),r=a[d],q=s.indexOf(e,d),u=b.labelNode,l=!1,p,z,t,w,h;"object"===typeof r&&(r=r.value);u.spanNode.innerHTML="";w=v.create("input",{type:"text"},u);0<e.length?(p=null!==e[q-1]?e[q-1]:null,z=null!==e[q+1]?e[q+1]:null,e=a[p],a=a[z]):(e=a[d-1],a=a[d+1]);"object"===typeof e&&(e=e.value);"object"===typeof a&&(a=a.value);q=void 0!==e&&null!==e?e:n&&!isNaN(this._minZoomLabel)?this._minZoomLabel:c;t=void 0!==a&&null!==a?a:n&&!isNaN(this._maxZoomLabel)?this._maxZoomLabel:f;this.showRatioLabels&&
(r=this._getLabelValueFromIndex(d).replace("%",""),q=e?Number(this._getLabelValueFromIndex(p,!0).replace("%","")):Number(this._minRatioLabel.replace("%",""))||Number(this._getRatioFromValue(this.minimum)),t=a?Number(this._getLabelValueFromIndex(z,!0).replace("%","")):Number(this._maxRatioLabel.replace("%",""))||Number(this._getRatioFromValue(this.maximum)));h=new y({value:r,constraints:{min:q,max:t,places:"0,20"}},w);b._numberEditor=h;k(h,"keydown",m.hitch(this,function(a){!1!==l&&(h.validate=l);
13===a.keyCode&&(a=h.get("value"),void 0===a&&(a=h.get("displayedValue")),a<=h.constraints.max&&a>=h.constraints.min?h.focusNode.blur():(l=h.validate,h.validate(!1),h.validate=function(){return!1}))}));k(h,"blur",m.hitch(this,function(){isNaN(h.get("value"))&&h.set("value",r);if(n&&(h.get("value")>f||h.get("value")<c))this.set("_isZoomed",!1),this.emit("zoom-out");u.spanNode.innerHTML=this._getLabelValueFromIndex(d);h.destroy();b._numberEditor=null}));k(h,"change",m.hitch(this,function(a){var b=a;
a>h.constraints.max||a<h.constraints.min||isNaN(a)||void 0===a?u.spanNode.innerHTML=this._getLabelValueFromIndex(d):(this.showRatioLabels&&(b=this._getValueFromPercent(a)),"object"===typeof this.values[d]?this.values[d].value=b:this.values[d]=b,this._reset(),this._updateRoundedLabels(),this._generateMoveables(),this._generateMinMaxEditors(),this.emit("handle-value-change",{values:this.values}))}));h.focus();h.textbox.select()}},_getRatioFromValue:function(b){var d=this.get("showRatioLabels");return"percent"===
d?100*b:"percentTotal"===d?100*(b/(1+b)):null},_getValueFromPercent:function(b){var d,e=this.get("showRatioLabels");if("percent"===e)d=b/100;else if("percentTotal"===e){if(100<=b)return 100;d=b/(100-b)}return d},_getLabelValueFromIndex:function(b,d){return this.showRatioLabels&&this._ratioLabels[b]?!0===d?parseFloat(this._ratioLabels[b].toFixed(2))+"%":f.format(parseFloat(this._ratioLabels[b].toFixed(2)))+"%":!0===d?this._roundedHandleLabels[b]:f.format(this._roundedHandleLabels[b])},_getValuesFromObject:function(b){var d=
[];s.forEach(b,function(b){d.push(b.value)});return d},_getDecimalPlaces:function(b){return f.format(b,{places:"0,20",round:-1}).replace(/^-?\d*\.?|0+$/g,"").length},_collisionCheck:function(b,d){return!(b.right<d.left||b.left>d.right||b.bottom<d.top||b.top>d.bottom)},_generateCtrlKeyListener:function(){k(document,"keydown",m.hitch(this,function(b){this._ctrlDown=b.metaKey||b.ctrlKey}));k(document,"keyup",m.hitch(this,function(b){this._ctrlDown=b.metaKey||b.ctrlKey}))},_valuesChange:function(){this.emit("change",
{values:this.get("values")})}})});