// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define("../core/Accessor ../core/declare dijit/_WidgetBase dijit/Destroyable dijit/registry dojo/_base/lang dojo/_base/window dojo/dom dojo/dom-attr dojo/dom-class dojo/on".split(" "),function(m,k,c,n,f,e,p,q,l,g,r){function s(a){return function(b){this._set(a,b)}}function t(a,b){return function(d){u.call(this,a,b,d);this._set(a,d)}}function u(a,b,d){(Array.isArray(b)?b:[b]).forEach(function(b){var c=this[b.node||b||"domNode"];switch(b.type||"attribute"){case "attribute":e.isFunction(d)&&(d=d.bind(this));
b=b.attribute?b.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;c.tagName?l.set(c,b,d):c.set(b,d);break;case "innerText":c.innerHTML="";c.appendChild(this.ownerDocument.createTextNode(d));break;case "innerHTML":c.innerHTML=d;break;case "class":b=this._get(a),g.replace(c,d,b)}},this)}k.before(function(a,b){if(b.declaredClass===h||k.hasMixin(a,h)){var d=b.properties;Object.keys(d).forEach(function(a){var b=d[a];var c=b.set;a="function"===typeof c?c:null===c?s(b.name):"string"===typeof c||"object"===
typeof c?t(a,c):void 0;b.set=a})}});var h="esri.widgets._WidgetBase";return m.createSubclass([n],{properties:{"class":{},domNode:{},focused:{},id:{},srcNodeRef:{},style:{},widgetId:{}},declaredClass:h,postscript:function(a){var b=this.__accessor__;a=b.ctorArgs||a;var c;(c=this.getDefaults?a?this.getDefaults(a):this.getDefaults({}):null)&&Object.getOwnPropertyNames(c).forEach(function(a){b.setDefault(a,c[a],!0)},this);this.postMixInProperties();this.ownerDocument=this.ownerDocument||(this.srcNodeRef?
this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=p.body(this.ownerDocument);f.add(this);this.buildRendering();this.__accessor__.initialize();a&&(this.set(a),b.ctorArgs=null);b.initialize();this.initialize();this.postCreate();if(this.domNode){var e;if((a=this.srcNodeRef)&&a.parentNode&&this.domNode!==a)a.parentNode.replaceChild(this.domNode,a),e=!0;l.set(this.domNode,{widgetId:this.id,id:this.id});e&&delete this.srcNodeRef}this._created=!0},getDefaults:function(a){var b={};b.id=a.id?
a.id:a.srcNodeRef&&a.srcNodeRef.id||f.getUniqueId(this.declaredClass.replace(/\./g,"_"));delete a.id;a.srcNodeRef&&(b.srcNodeRef=a.srcNodeRef,delete a.srcNodeRef);return e.mixin(this.inherited(arguments),b)},normalizeCtorArgs:function(a,b){a=a||{};if(a.srcNodeRef||b)a.srcNodeRef=q.byId(b||a.srcNodeRef);return a},destroy:function(){this._customWidgetBaseDestroy()},postMixInProperties:c.prototype.postMixInProperties,buildRendering:c.prototype.buildRendering,postCreate:c.prototype.postCreate,startup:c.prototype.startup,
_beingDestroyed:!1,_destroyed:!1,_created:!1,"class":"",_setClassAttr:{node:"domNode",type:"class"},domNode:null,id:"",srcNodeRef:null,style:null,_setStyleAttr:c.prototype._setStyleAttr,destroyDescendants:c.prototype.destroyDescendants,destroyRecursive:c.prototype.destroyRecursive,destroyRendering:c.prototype.destroyRendering,emit:c.prototype.emit,on:function(a,b){return this.own(r(this.domNode,a,b))[0]},toString:c.prototype.toString,getChildren:c.prototype.getChildren,getParent:c.prototype.getParent,
isLeftToRight:c.prototype.isLeftToRight,placeAt:c.prototype.placeAt,focused:!1,onFocus:function(){},onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()},dojoAttachEvent:"",dojoAttachPoint:"",_customWidgetBaseDestroy:function(a){function b(b){b.destroyRecursive?b.destroyRecursive(a):b.destroy&&b.destroy(a)}this._beingDestroyed=!0;this.domNode&&f.findWidgets(this.domNode,this.containerNode).forEach(b);this.destroyRendering(a);f.remove(this.id);this._destroyed=!0}}).createSubclass({properties:{viewModel:{},
visible:{}},declaredClass:"esri.widgets.Widget",getDefaults:function(){return e.mixin(this.inherited(arguments),{viewModel:{}})},buildRendering:function(){this.inherited(arguments);g.add(this.domNode,"esri-widget")},destroy:function(){this.viewModel.destroy&&this.viewModel.destroy();this.viewModel=null},viewModel:null,visible:!0,_setVisibleAttr:function(a){this._set("visible",a);g.toggle(this.domNode,"esri-hidden",!a)}})});