// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports","./enums"],function(g,l,h){g=function(){function b(a){this._gl=null;this._extensions=void 0;this._blendEnabled=!1;this._blendColorState={r:0,g:0,b:0,a:0};this._blendFunctionState={srcRGB:1,dstRGB:0,srcAlpha:1,dstAlpha:0};this._blendEquationState={mode:32774,modeAlpha:32774};this._colorMaskState={r:!0,g:!0,b:!0,a:!0};this._polygonCullingEnabled=!1;this._cullFace=1029;this._frontFace=2305;this._scissorTestEnabled=!1;this._scissorRect={x:0,y:0,width:0,height:0};this._depthTestEnabled=
!1;this._depthFunction=513;this._clearDepth=1;this._depthWriteEnabled=!0;this._depthRange={zNear:0,zFar:1};this._stencilTestEnabled=!1;this._stencilFunction={face:1032,func:519,ref:0,mask:1};this._clearStencil=0;this._stencilWriteMask=1;this._stencilOperation={face:1032,fail:7680,zFail:7680,zPass:7680};this._lineWidth=1;this._clearColor={r:0,g:0,b:0,a:0};this._activeFramebuffer=this._activeVertexArrayObject=this._activeIndexBuffer=this._activeVertexBuffer=this._activeShaderProgram=-1;this._activeTextureUnit=
0;this._textureUnitMap={};this._gl=a;this._extensions=new k(a)}Object.defineProperty(b.prototype,"gl",{get:function(){return this._gl},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"extensions",{get:function(){return this._extensions},enumerable:!0,configurable:!0});b.prototype.setBlendingEnabled=function(a){this._blendEnabled!==a&&(!0===a?this._gl.enable(this._gl.BLEND):this._gl.disable(this._gl.BLEND),this._blendEnabled=a)};b.prototype.setBlendColor=function(a,c,e,b){if(a!==
this._blendColorState.r||c!==this._blendColorState.g||e!==this._blendColorState.b||b!==this._blendColorState.a)this._gl.blendColor(a,c,e,b),this._blendColorState.r=a,this._blendColorState.g=c,this._blendColorState.b=e,this._blendColorState.a=b};b.prototype.setBlendFunction=function(a,c){if(a!==this._blendFunctionState.srcRGB||c!==this._blendFunctionState.dstRGB)this._gl.blendFunc(a,c),this._blendFunctionState.srcRGB=a,this._blendFunctionState.srcAlpha=a,this._blendFunctionState.dstRGB=c,this._blendFunctionState.dstAlpha=
c};b.prototype.setBlendFunctionSeparate=function(a,c,b,d){if(this._blendFunctionState.srcRGB!==a||this._blendFunctionState.srcAlpha!==b||this._blendFunctionState.dstRGB!==c||this._blendFunctionState.dstAlpha!==d)this._gl.blendFuncSeparate(a,c,b,d),this._blendFunctionState.srcRGB=a,this._blendFunctionState.srcAlpha=b,this._blendFunctionState.dstRGB=c,this._blendFunctionState.dstAlpha=d};b.prototype.setBlendEquation=function(a){this._blendEquationState.mode!==a&&(this._gl.blendEquation(a),this._blendEquationState.mode=
a,this._blendEquationState.modeAlpha=a)};b.prototype.setBlendEquationSeparate=function(a,c){if(this._blendEquationState.mode!==a||this._blendEquationState.modeAlpha!==c)this._gl.blendEquationSeparate(a,c),this._blendEquationState.mode=a,this._blendEquationState.modeAlpha=c};b.prototype.seColorMask=function(a,c,b,d){if(this._colorMaskState.r!==a||this._colorMaskState.g!==c||this._colorMaskState.b!==b||this._colorMaskState.a!==d)this._gl.colorMask(a,c,b,d),this._colorMaskState.r=a,this._colorMaskState.g=
c,this._colorMaskState.b=b,this._colorMaskState.a=d};b.prototype.setClearColor=function(a,c,b,d){if(this._clearColor.r!==a||this._clearColor.g!==c||this._clearColor.b!==b||this._clearColor.a!==d)this._gl.clearColor(a,c,b,d),this._clearColor.r=a,this._clearColor.g=c,this._clearColor.b=b,this._clearColor.a=d};b.prototype.setFaceCullingEnabled=function(a){this._polygonCullingEnabled!==a&&(!0===a?this._gl.enable(this._gl.CULL_FACE):this._gl.disable(this._gl.CULL_FACE),this._polygonCullingEnabled=a)};
b.prototype.setCullFace=function(a){this._cullFace!==a&&(this._gl.cullFace(a),this._cullFace=a)};b.prototype.setFrontFace=function(a){this._frontFace!==a&&(this._gl.frontFace(a),this._frontFace=a)};b.prototype.setScissorTestEnabled=function(a){this._scissorTestEnabled!==a&&(!0===a?this._gl.enable(this._gl.SCISSOR_TEST):this._gl.disable(this._gl.SCISSOR_TEST),this._scissorTestEnabled=a)};b.prototype.setScissorRect=function(a,c,b,d){if(this._scissorRect.x!==a||this._scissorRect.y!==c||this._scissorRect.width!==
b||this._scissorRect.height!==d)this._gl.scissor(a,c,b,d),this._scissorRect.x=a,this._scissorRect.y=c,this._scissorRect.width=b,this._scissorRect.height=d};b.prototype.setDepthTestEnabled=function(a){this._depthTestEnabled!==a&&(!0===a?this._gl.enable(this._gl.DEPTH_TEST):this._gl.disable(this._gl.DEPTH_TEST),this._depthTestEnabled=a)};b.prototype.setClearDepth=function(a){this._clearDepth!==a&&(this._gl.clearDepth(a),this._clearDepth=a)};b.prototype.setDepthFunction=function(a){this._depthFunction!==
a&&(this._gl.depthFunc(a),this._depthFunction=a)};b.prototype.setDepthWriteEnabled=function(a){this._depthWriteEnabled!==a&&(this._gl.depthMask(a),this._depthWriteEnabled=a)};b.prototype.setDepthRange=function(a,c){if(this._depthRange.zNear!==a||this._depthRange.zFar!==c)this._gl.depthRange(a,c),this._depthRange.zNear=a,this._depthRange.zFar=c};b.prototype.setStencilTestEnabled=function(a){this._stencilTestEnabled!==a&&(!0===a?this._gl.enable(this._gl.STENCIL_TEST):this._gl.disable(this._gl.STENCIL_TEST),
this._stencilTestEnabled=a)};b.prototype.setClearStencil=function(a){a!==this._clearStencil&&(this._gl.clearStencil(a),this._clearStencil=a)};b.prototype.setStencilFunction=function(a,c,b){if(this._stencilFunction.func!==a||this._stencilFunction.ref!==c||this._stencilFunction.mask!==b)this._gl.stencilFunc(a,c,b),this._stencilFunction.face=1032,this._stencilFunction.func=a,this._stencilFunction.ref=c,this._stencilFunction.mask=b};b.prototype.setStencilFunctionSeparate=function(a,c,b,d){if(this._stencilFunction.face!==
a||this._stencilFunction.func!==c||this._stencilFunction.ref!==b||this._stencilFunction.mask!==d)this._gl.stencilFuncSeparate(a,c,b,d),this._stencilFunction.face=a,this._stencilFunction.func=c,this._stencilFunction.ref=b,this._stencilFunction.mask=d};b.prototype.setStencilWriteMask=function(a){this._stencilWriteMask!==a&&(this._gl.stencilMask(a),this._stencilWriteMask=a)};b.prototype.setStenciOp=function(a,c,b){if(this._stencilOperation.fail!==a||this._stencilOperation.zFail!==c||this._stencilOperation.zPass!==
b)this._gl.stencilOp(a,c,b),this._stencilOperation.face=1032,this._stencilOperation.fail=a,this._stencilOperation.zFail=c,this._stencilOperation.zPass=b};b.prototype.setStenciOpSeparate=function(a,b,e,d){if(this._stencilOperation.face!==a||this._stencilOperation.fail!==b||this._stencilOperation.zFail!==e||this._stencilOperation.zPass!==d)this._gl.stencilOpSeparate(a,b,e,d),this._stencilOperation.face=a,this._stencilOperation.face=a,this._stencilOperation.fail=b,this._stencilOperation.zFail=e,this._stencilOperation.zPass=
d};b.prototype.setLineWidth=function(a){var b=this._lineWidth;this._lineWidth!==a&&(this._gl.lineWidth(a),this._lineWidth=a);return b};b.prototype.setActiveTexture=function(a){var b=this._activeTextureUnit;0<=a&&a!==this._activeTextureUnit&&(this._gl.activeTexture(h.BASE_TEXTURE_UNIT+a),this._activeTextureUnit=a);return b};b.prototype.clear=function(a){a&&this._gl.clear(a)};b.prototype.drawArrays=function(a,b,e){this._gl.drawArrays(a,b,e)};b.prototype.drawElements=function(a,b,e,d){5123===e?this._gl.drawElements(a,
b,e,d):5125===e&&this._extensions.elementIndexUint?this._gl.drawElements(a,b,e,d):console.warn("Data type is uint however extension OES_Element_index_unit is not supported therefore this draw call cannot be made")};b.prototype.drawArraysInstanced=function(a,b,e,d){this._extensions.angleInstancedArrays?this._extensions.angleInstancedArrays.drawArraysInstancedANGLE(a,b,e,d):console.error("Extension ANGLE_instanced_arrays isn't supported!")};b.prototype.drawElementsInstanced=function(a,b,e,d,f){this._extensions.angleInstancedArrays?
this._extensions.angleInstancedArrays.drawElementsInstancedANGLE(a,b,e,d,f):console.error("Extension ANGLE_instanced_arrays isn't supported!")};b.prototype.setViewport=function(a,b,e,d){this._gl.viewport(a,b,e,d)};b.prototype.bindProgram=function(a){if(a){var b=a.id;this._activeShaderProgram!==b&&(a.initialize(),this._gl.useProgram(a.glName),this._activeShaderProgram=b)}else this._gl.useProgram(null),this._activeShaderProgram=-1};b.prototype.bindTexture=function(a,c){void 0===c&&(c=0);-1===b._MAX_TEXTURE_IMAGE_UNITS&&
(b._MAX_TEXTURE_IMAGE_UNITS=this._gl.getParameter(this._gl.MAX_TEXTURE_IMAGE_UNITS));(c>=b._MAX_TEXTURE_IMAGE_UNITS||0>c)&&console.error("Input texture unit is out of range of available units!");this.setActiveTexture(c);if(a){var e=this._textureUnitMap[c];void 0!==e&&e.id===a.id?a.applyChanges():(this._gl.bindTexture(a.descriptor.target,a.glName),a.applyChanges(),void 0===e?this._textureUnitMap[c]={id:a.id}:e.id=a.id)}else this._gl.bindTexture(a.descriptor.target,null),this._textureUnitMap[c]=null};
b.prototype.bindFramebuffer=function(a){a?void 0!==a.id&&this._activeFramebuffer===a.id||(a.initialize()||this._gl.bindFramebuffer(this._gl.FRAMEBUFFER,a.glName),this._activeFramebuffer=a.id):(this._gl.bindFramebuffer(this._gl.FRAMEBUFFER,null),this._activeFramebuffer=-1)};b.prototype.bindBuffer=function(a){a&&(34962===a.bufferType?this._activeVertexBuffer=b._bindBuffer(this._gl,a,a.bufferType,this._activeVertexBuffer):this._activeIndexBuffer=b._bindBuffer(this._gl,a,a.bufferType,this._activeIndexBuffer))};
b.prototype.bindVAO=function(a){var b=this._extensions.vao;!a&&b?(b.bindVertexArrayOES(null),this._activeVertexArrayObject=-1):this._activeVertexArrayObject!==a.id&&(a.initialize(),b?b.bindVertexArrayOES(a.glName):a.bindLayout(),this._activeVertexArrayObject=a.id)};b._bindBuffer=function(a,b,e,d){if(!b)return a.bindBuffer(e,null),-1;var f=b.id;if(d===f)return d;a.bindBuffer(e,b.glName);return f};b._MAX_TEXTURE_IMAGE_UNITS=-1;return b}();var k=function(){function b(a){this._depthTextureInit=this._elementIndexUintInit=
this._standardDerivativesInit=this._angleInstancedArraysInit=this._vaoInit=!1;this._gl=a}Object.defineProperty(b.prototype,"vao",{get:function(){this._vaoInit||(this._vao=this._gl.getExtension("OES_vertex_array_object")||this._gl.getExtension("MOZ_OES_vertex_array_object")||this._gl.getExtension("WEBKIT_OES_vertex_array_object"),this._vaoInit=!0);return this._vao},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"angleInstancedArrays",{get:function(){this._angleInstancedArraysInit||
(this._angleInstancedArrays=this._gl.getExtension("ANGLE_instanced_arrays"),this._angleInstancedArraysInit=!0);return this._angleInstancedArrays},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"standardDerivatives",{get:function(){this._standardDerivativesInit||(this._standardDerivatives=this._gl.getExtension("OES_standard_derivatives"),this._standardDerivativesInit=!0);return this._standardDerivatives},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"elementIndexUint",
{get:function(){this._elementIndexUintInit||(this._elementIndexUint=this._gl.getExtension("OES_element_index_uint"),this._elementIndexUintInit=!0);return this._elementIndexUint},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"depthTexture",{get:function(){this._depthTextureInit||(this._depthTexture=this._gl.getExtension("WEBGL_depth_texture")||this._gl.getExtension("MOZ_WEBGL_depth_texture")||this._gl.getExtension("WEBKIT_WEBGL_depth_texture"),this._depthTextureInit=!0);return this._depthTexture},
enumerable:!0,configurable:!0});return b}();return g});