// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["require","exports"],function(h,k){return function(){function d(a,b,c){this._glName=this._context=null;this._id=-1;this._desc=void 0;this._wrapModeDirty=this._samplingModeDirty=!1;this._context=a;this._desc={pixelFormat:b.pixelFormat,dataType:b.dataType,target:b.target?b.target:3553,samplingMode:b.samplingMode?b.samplingMode:9729,wrapMode:b.wrapMode?b.wrapMode:33071,flipped:void 0!==b.flipped?b.flipped:!1,hasMipmaps:void 0!==b.hasMipmaps?b.hasMipmaps:!1,level:void 0!==b.level?b.level:0,unpackAlignment:b.unpackAlignment?
b.unpackAlignment:4,width:b.width,height:b.height};this._id=++d._nextId;this.setData(c)}Object.defineProperty(d.prototype,"id",{get:function(){return this._id},enumerable:!0,configurable:!0});Object.defineProperty(d.prototype,"glName",{get:function(){return this._glName},enumerable:!0,configurable:!0});Object.defineProperty(d.prototype,"descriptor",{get:function(){return this._desc},enumerable:!0,configurable:!0});d.prototype.dispose=function(){if(this._context&&this._glName){var a=this._context.gl;
a.isTexture(this._glName)&&(a.deleteTexture(this._glName),this._glName=null)}};d.prototype.setData=function(a){var b=this._context.gl;this._glName||(this._glName=b.createTexture());this._context.bindTexture(this);var c=this._desc;d._validateTexture(c);b.pixelStorei(b.UNPACK_ALIGNMENT,c.unpackAlignment);b.pixelStorei(b.UNPACK_FLIP_Y_WEBGL,c.flipped?1:0);a instanceof ImageData||a instanceof HTMLImageElement||a instanceof HTMLCanvasElement||a instanceof HTMLVideoElement?(c.width&&c.height&&console.assert(a.width===
c.width&&a.height===c.height),b.texImage2D(b.TEXTURE_2D,c.level,c.pixelFormat,c.pixelFormat,c.dataType,a),void 0===this._desc.width&&(this._desc.width=a.width),void 0===this._desc.height&&(this._desc.height=a.height)):((!c.width||!c.height)&&console.error("Width and height must be specified!"),b.texImage2D(b.TEXTURE_2D,c.level,c.pixelFormat,c.width,c.height,0,c.pixelFormat,c.dataType,a));d._applySamplingMode(b,this._desc);d._applyWrapMode(b,this._desc);c.hasMipmaps&&this.generateMipmaps()};d.prototype.updateData=
function(a,b,c,d,f){f||console.error("An attempt to use uninitialized data!");this._glName||console.error("An attempt to update uninitialized texture!");var g=this._context.gl,e=this._desc;this._context.bindTexture(this);(0>a||0>b||c>e.width||d>e.height||a+c>e.width||b+d>e.height)&&console.error("An attempt to update out of bounds of the texture!");f instanceof ImageData||f instanceof HTMLImageElement||f instanceof HTMLCanvasElement||f instanceof HTMLVideoElement?(console.assert(f.width===c&&f.height===
d),g.texSubImage2D(g.TEXTURE_2D,e.level,a,b,e.pixelFormat,e.dataType,f)):g.texSubImage2D(g.TEXTURE_2D,e.level,a,b,c,d,e.pixelFormat,e.dataType,f)};d.prototype.generateMipmaps=function(){var a=this._desc;a.hasMipmaps||(a.hasMipmaps=!0,d._validateTexture(a));9729===a.samplingMode?a.samplingMode=9985:9728===a.samplingMode&&(a.samplingMode=9984);a=this._context.gl;a.generateMipmap(a.TEXTURE_2D)};d.prototype.setSamplingMode=function(a){a!==this._desc.samplingMode&&(this._desc.samplingMode=a,d._validateTexture(this._desc),
this._samplingModeDirty=!0)};d.prototype.setWrapMode=function(a){a!==this._desc.wrapMode&&(this._desc.wrapMode=a,d._validateTexture(this._desc),this._wrapModeDirty=!0)};d.prototype.applyChanges=function(){var a=this._context.gl,b=this._desc;this._samplingModeDirty&&(d._applySamplingMode(a,b),this._samplingModeDirty=!1);this._wrapModeDirty&&(d._applyWrapMode(a,b),this._wrapModeDirty=!1)};d._isPowerOfTwo=function(a){return 0===(a&a-1)};d._validateTexture=function(a){(0>=a.width||0>=a.height)&&console.error("The dimensions are not all positive!");
if(!d._isPowerOfTwo(a.width)||!d._isPowerOfTwo(a.height))33071!==a.wrapMode&&console.error("Non-power-of-two textures must have a wrap mode of CLAMP_TO_EDGE!"),a.hasMipmaps&&console.error("Mipmapping requires power-of-two textures!")};d._applySamplingMode=function(a,b){var c=b.samplingMode;if(9985===c||9987===c)c=9729;else if(9984===c||9986===c)c=9728;a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,c);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,b.samplingMode)};d._applyWrapMode=function(a,
b){a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,b.wrapMode);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,b.wrapMode)};d._nextId=0;return d}()});