// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0/esri/copyright.txt for details.
//>>built
define(["dojo/_base/lang","./ArcGISMapService","../../PopupTemplate","../../core/Accessor","../../core/JSONSupport"],function(h,n,k,f,p){var q={visible:"visibleSublayers",definitionExpression:"layerDefs"},l=function(a){return function(b){var c=this._layer;c&&this._get(a)!==b&&(this._set(a,b),c.exportImageParameters.notifyChange(q[a]))}},m=p.createSubclass({properties:{definitionExpression:{value:null,set:l("definitionExpression")},id:{readOnly:!0},minScale:{readOnly:!0},maxScale:{readOnly:!0},popupTemplate:{type:k},
url:{get:function(){return this._layer.parsedUrl.path+"/"+this.id}},title:{value:null},visible:{type:Boolean,set:l("visible")}},constructor:function(a){Object.defineProperty(this,"_layer",{value:a.layer,enumerable:!1,writable:!1});delete a.layer}}),r=m.createSubclass({properties:{sublayers:{readOnly:!0}}}),s=function(a,b){a&&b&&["definitionExpression","title","visible","url","popupTemplate"].filter(function(a){return null!=b[a]}).forEach(function(c){a[c]=b[c]})},g=function(a,b){var c=function(b){a(b);
b.sublayers&&b.sublayers.forEach(c)};b.forEach(c)},t=function(a){var b=[];g(function(a){b.push(a)},a);return b},u=function(a){return function(b){var c=a.map(function(a){return new a({layer:this})},this);if(!b)return c;var e=b.reduce(function(a,b){null!=b.id&&(a[b.id]=b);return a},{});g(function(a){null!=e[a.id]?s(a,e[a.id]):a.visible=!1},c);return c}};f=f.createSubclass({declaredClass:"esri.layers.mixins.ArcGISDynamicService::ExportImageParameters",properties:{layer:{},layers:{readOnly:!0,dependsOn:["visibleSublayers"],
get:function(){var a=this.visibleSublayers;return a?a.length?"show:"+a.map(function(a){return a.id}).join(","):"show:-1":null}},layerDefs:{readOnly:!0,dependsOn:["visibleSublayers"],get:function(){var a=this.get("visibleSublayers").filter(function(a){return null!=a.definitionExpression});if(!a.length)return null;var b=/[:;]/;return a.map(function(a){return a.definitionExpression}).some(b.test.bind(b))?JSON.stringify(a.reduce(function(a,b){a[b.id]=b.definitionExpression;return a},{})):a.map(function(a){return a.id+
":"+a.definitionExpression}).join(";")}},version:{value:0,dependsOn:"layers layerDefs layer.dpi layer.imageFormat layer.imageTransparency layer.gdbVersion".split(" "),get:function(){return this._get("version")+1}},visibleSublayers:{readOnly:!0,dependsOn:["layer.sublayers"],get:function(){var a=[],b=function(c){c.visible&&(c.sublayers?c.sublayers.forEach(b):a.push(c))};this.get("layer.sublayers").forEach(b);return a}}},toJSON:function(){var a=this.layer;return{dpi:a.dpi,format:a.imageFormat,transparent:a.imageTransparency,
gdbVersion:a.gdbVersion||null,layerTimeOptions:this.layerTimeOptions,layers:this.layers,layerDefs:this.layerDefs}}});return n.createSubclass({declaredClass:"esri.layers.mixins.ArcGISDynamicService",getDefaults:function(){return h.mixin(this.inherited(arguments),{exportImageParameters:{layer:this}})},_castSublayers:null,properties:{allSublayers:{readOnly:!0,dependsOn:["sublayers"],get:function(){var a=this.sublayers;return!a?[]:t(a)}},dpi:96,exportImageParameters:{value:null,type:f,readOnly:!0},gdbVersion:null,
imageFormat:"png8",imageTransparency:!0,loaded:{value:!1},supportsRotation:{dependsOn:["version"],readOnly:!0,get:function(){return 10.3<=this.version}},sublayers:{value:null,dependsOn:["loaded"],cast:function(a){return!this._castSublayers?a:this._castSublayers(a)},get:function(){return this._get("sublayers")},json:{readFrom:["layers","visibleLayers"],read:function(a,b){var c;if(b.layers){c={};var e=[];b.layers.map(function(a){var b={properties:{id:{value:a.id},visible:{value:a.defaultVisibility},
minScale:{value:a.minScale},maxScale:{value:a.maxScale},popupTemplate:{value:a.popupInfo&&k.fromJSON(a.popupInfo)||null},title:{value:a.name}}};a.subLayerIds?(b.properties.sublayers={get:function(){return a.subLayerIds.map(function(a){return new c[a]({layer:this._layer})},this)}},b=r.createSubclass(b)):b=m.createSubclass(b);c[a.id]=b;-1===a.parentLayerId&&e.push(b)});this._subLayerDefinitions=c;this._castSublayers=u(e)}else c=this._subLayerDefinitions;var d=this.__accessor__.store;d.has("sublayers")&&
[d._values].concat(d._originStores).forEach(function(a){a.sublayers&&(a.sublayers=this._castSublayers(a.sublayers))},this);return this._subLayerDefinitions&&b.visibleLayers&&(d=this._get("sublayers"))?(g(function(a){-1<b.visibleLayers.indexOf(a.id)?a.visible=!0:a.visible=!1},d),d):null}}}},findSublayerById:function(a){var b=this.allSublayers;if(!b)return null;var c=null;b.some(function(b){return b.id===a?(c=b,!0):!1});return c},getExportImageParameters:function(a){var b=10>this.version?a.extent:a.extent.clone().shiftCentralMeridian(),
c=a.width,e=a.height,d=b&&b.spatialReference;a=null==a.rotation||0===a.rotation||!this.supportsRotation?{}:{rotation:-a.rotation};d=d&&(d.wkid||JSON.stringify(d.toJSON()));return h.mixin({bbox:b&&b.xmin+","+b.ymin+","+b.xmax+","+b.ymax,bboxSR:d,imageSR:d,size:c+","+e},a,this.exportImageParameters.toJSON())}})});